thesofproject/sof

src/audio/detect_test.c
This patch solves the issue with wrong number of bytes
being passed to detecting function therefore causing a loss
of recorded data.
=> detector: fix bug of incorrect amount of samples in detecting function

src/drivers/intel/cavs/hda-dma.c
Adds additional logs in case of failure to waiting
functions.
=> hda-dma: add additional logs to waiting functions

tools/topology/sof-cml-demux-rt5682.m4
Dmic and hdmi1 have wrong pipeline id's in demux topology
so fix them.
=> topology: fix pipeline indexes in cml demux topology

scripts/cmake/git-hooks.cmake
Add support for non-unix systems that have bash shell.
=> cmake: git hooks for non-unix os

src/drivers/dw/dma.c
Fixes https://github.com/thesofproject/linux/issues/873
Two recent commits:
7275e422d86 ('dw-dma: handle interrupts per core')
433de9fb50c ('dw-dma: clear block/transfer irq after stop')
broke DW-DMA on Baytrail. Though they seem logical, they don't
produce the desired result on that platform. This patch restores the
original behaviour on BYT, CHT, BDW and HSW. It also eliminates the
redundant branch in the loop by replacing it with a simple mask to
restore the original IRQ processing order:
1. clear the source IRQ
2. clear the platform IRQ
3. call the callbacks
=> dw-dma: revert recent changes for Baytrail

tools/kmod_scripts/sof_remove.sh
remove additional modules in the right order to stress test SoundWire
support
=> kmod_scripts: first support for SoundWire

src/audio/kpb.c, src/lib/dma-trace.c, src/lib/panic.c, src/lib/trace.c
Replaces all occurrences of memcpy with memcpy_s.
=> memcpy: replace all occurrences with memcpy_s

src/audio/pipeline.c, src/include/sof/audio/component.h
In order to handle complex topologies, we need more precise control
over connected pipelines behaviour and propagation of events.
Better control is accomplished by limiting propagation of events in
case of mismatch between starting and desination pipelines that are
connected, for example when propagating from playback pipeline to branch
which endpoint is Host component, or reversely, when propagating from
capture pipeline to one with Dai endpoint.
This PR was extracted from https://github.com/thesofproject/sof/pull/1275
=> pipeline: Limit propagation of pipeline params, prepare and reset.

src/audio/host.c
Remove the duplicate dma_stop() during host_reset().
DMA should already be stopped when the host comp gets
the STOP trigger. This fixes the following error seen
during host reset:
intel/cavs/hda-dma.c:639 hda-dmac: 5 invalid channel -1
=> host: remove duplicate dma_stop()

src/audio/buffer.c
Using hex %x format in comp_update_buffer_consume for tracing addresses and bitfields is more readible than decimal format.
=> buffer: enhance trace message in comp_update_buffer_consume

src/drivers/intel/cavs/dmic.c
This patch updates the gain update coefficient to achieve
a longer ramp time. The previous 300 ms long ramp was not
enough to conceal all of the slow DC component settling seen
in the beginning of DMIC capture.
=> DMIC: Increase start gain ramp length to 400 ms

tools/topology/platform/intel/intel-generic-dmic.m4
This patch set consists of two commits
- The first patch adds the missing 4ch 32bit DAI creation. The DAI was not earlier created due to a mistake in topology.
- The second patch changes the 16 kHz DMIC FIFO to use 32 bit bit configuration. It improves a lot audio quality when the signal is amplified in volume control. The pipeline scheduling is also changed to default 1000us (48 frames -> 16 frames scheduling). The comments and actual topology config were conflicting.
=> DMIC topology updates patch set

Kconfig, src/lib/alloc.c
Slight refactor - moved DEBUG_BLOCK_FREE from C file to Kconfig.
=>  alloc: move DEBUG_BLOCK_FREE to kconfig

src/audio/dai.c
The recommended HDA HW programming sequence for setting the DMA format requires that the link DMA and host DMA channels be coupled before setting the format. This change means that host DMA or link DMA channels be reserved even if only one is used.
Statically assigned link DMA channels would mean that all the corresponding host DMA channels will need to be reserved, leaving only a few channels available at run-time. So, the suggestion here is to switch to dynamically assigning both host DMA channels and link DMA channels are run-time.
The host DMA channel is assigned when the pcm is opened as before. While choosing the link DMA channel, if the host DMA channel corresponding to the link DMA channel is already taken, the proposed method checks to make sure that the BE is connected to the FE …
=> dai: assign link DMA channel at run-time

Kconfig, src/arch/xtensa/up/xtos/reset-vector.S, src/platform/Kconfig
Apollolake+/i.MX have reset vector in ROM. So far we have
used platform config symbols to tell which platforms have
the reset vector in ROM.
Anyhow, things are starting to get ugly here with more
platforms to come so we add an internal config symbol
which will be set by each each platform when needed.
I couldn't find a definition for CONFIG_SKYLAKE and CONFIG_KABYLAKE are these supported now?
=> Introduce HAVE_RESET_VECTOR_ROM symbol

.travis.yml, scripts/docker_build/sof_builder/Dockerfile, scripts/xtensa-build-all.sh
Enable the IMX8 platform support in scripts and docker.
Add support in Travis CI.
Will update the SOF-CI later after this patch merged.
=> Add CI support for IMX8 platform

src/arch/xtensa/CMakeLists.txt
For #1310 
~Adds `bin_post_pv` target.~
~It's going to be used for signing post-pv firmware on some platforms.
Usage: build as usual, but use `make bin_post_pv` instead of `make bin`~
Adds support for 2 cmake variables.
`MEU_FLAGS` - overrides meu flags
`MEU_EXTRA_FLAGS` - adds additional flags after default meu flags
Sample usage:
```
cmake -DMEU_EXTRA_FLAGS=-mnpv\ true
make bin
```
=> meu: support for custom flags

CMakeLists.txt, src/arch/xtensa/CMakeLists.txt
Adds `make install` support for FW build.
For commands like:
```
cmake -DTOOLCHAIN=xt -DROOT_DIR=$CONFIG_PATH/xtensa-elf -DMEU_PATH=$MEU_PATH -DMEU_PRIVATE_KEY=$PRIVATE_KEY_PATH -DCMAKE_INSTALL_PREFIX=install ..
make apollolake_defconfig
make install -j6
```
It creates install dir like:
```
install
├── bin
│   ├── sof-apl.ldc
│   └── sof-apl.ri
└── include
└── uapi
├── abi.h
├── ipc
│   ├── control.h
│   ├── dai.h
│   ├── dai-intel.h
│   ├── header.h
│   ├── info.h
│   ├── pm.h
│   ├── stream.h
│   ├── topology.h
│   ├── trace.h
│   └── xtensa.h
└── user
├── detect_test.h
├── eq.h
├── fw.h
├── header.h
├── manifest.h
├── tokens.h
├── tone.h
└── trace.h
```
Resolves #1309 
=> cmake: add install target for fw

tools/kmod_scripts/sof_remove.sh
=> kmod_scripts: fix hdaudio support

src/include/sof/clk.h, src/include/uapi/ipc/trace.h, src/ipc/handler.c, src/lib/clk.c
The unit of trace header timestamp is ticks but it is nanosecond
in trace params. So we have to convert it to ticks.
=> trace: convert trace time stamp to ticks

CODEOWNERS, src/audio/CMakeLists.txt, src/audio/mux/CMakeLists.txt, src/audio/mux/mux.c, src/audio/mux/mux_generic.c, src/include/sof/audio/mux.h
While Mux component was in development, organization of source files and headers of audio components has changed, and Mux didn't conform to the new structure. This PR is to fix this.
=> MUX: Relocate mux source and header files to match structure.

tools/topology/sof-byt-codec.m4
Byt media pipeline has different parameters in topology for scheduling
deadline and frame count than apl. This produces funny 4-8x speed
playback. So unify with apl media pipe.
=> topology: unify byt media pipeline params with apl media pipe

src/drivers/dw/dma.c
dw-dma transfer size setting was changed in cleanup and because of that
we need to zero the ctrl_hi value before twiddling the bits.
=> dw-dma: set ctrl_hi to zero before bit masking

src/include/sof/dma-trace.h, src/lib/dma-trace.c
Fixes cache handling for dma-trace buffer.
Current implementation wasn't fully supporting
multicore traces. This patch changes buffer
writeback invalidations after buffer write to
invalidations before read and writebacks after
write. Also removes not needed cache operations
on retrieving current traces size.
Fixes #1494.
=> dma-trace: fix cache handling

src/include/sof/audio/format.h
Adds missing stdint header, since we are using types
defined in that file. Right now format.h compiles
by accident.
=> format: add missing #include <stdint.h>

src/audio/dai.c, src/drivers/intel/cavs/ssp.c, src/platform/apollolake/include/platform/platform.h, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h
Changes starting sequence of DAI. Now IO interface is
started before DMA. The purpose of this change is to
allow slave interfaces to prepare their FIFOs before
DMA starts transferring to them.
Fixes #1466.
=> dai: change starting sequence

src/drivers/dw/ssi-spi.c, src/include/sof/audio/format.h, src/include/sof/sof.h
Unifies multiple different align macros spread
across the source code. Now we have ALIGN_UP and
ALIGN_DOWN macros defined in sof.h.
=> sof: unify multiple ALIGN macros

src/lib/dma-trace.c, src/platform/apollolake/include/platform/platform.h, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h
Aligns copied trace size to DMA burst size for HD-DMA.
Previously we've copied data on the DSP side and sent
the right offset to the host, but actually if the data
wasn't aligned to the burst size, the host would read
old traces for the part of data not yet pushed to the
host.
=> dma-trace: align copied trace size to DMA burst size

src/include/sof/sof.h
This will add default ALIGN macro so #defines which are using ALIGN
can work in main code and linker scripts using linker definition for ALIGN
=> sof: add default ALIGN macro

src/arch/xtensa/smp/idc.c, src/arch/xtensa/smp/include/arch/idc.h, src/include/sof/idc.h, test/cmocka/src/audio/pipeline/pipeline_mocks.c, test/cmocka/src/audio/pipeline/pipeline_mocks.h
Refactors IDC sending in blocking mode to
utilize DONE interrupt instead of manually
polling for DONE bit. It allows for removal
of spinlock, which prevented longer IDC
timeouts.
Fixes #1503.
=> idc: refactor sending in blocking mode

rimage/pkcs1_5.c
It's for preventing possible buffer overflow.
It was partially done in #646 , but missed one occurrence of unsafe strcpy.
Fixes #257 
=> rimage: fix possible strcpy and sprintf overflows 

src/platform/apollolake/include/platform/platform.h, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h
Decreases PLATFORM_SSP_DELAY for cAVS platforms.
This delay is used after SSP start and before stop
to let frame and clock synchronize. It was very long,
so was decreased from 1/8 ms to 1/24 ms. Experiments
show that it's still enough for slave clock to synchronize
and to not lose first data sample.
=> ssp: cavs: decrease PLATFORM_SSP_DELAY

src/audio/pipeline.c
Adds missing check in pipeline_comp_copy for
PPL_STATUS_PATH_STOP. It fixes the issue, where
playback pipeline hasn't been able to stop copying
even with component returning such status.
=> pipeline: add missing check for PPL_STATUS_PATH_STOP

src/audio/dai.c, src/audio/pipeline.c
Fixes xrun handling by moving check from callback
to copy. Check in callback wasn't making any sense,
because bytes passed there have been already calculated
based on avail/free.
=> dai: fix xrun handling

tools/logger/logger.c
Resolves #1266 
Logger was aware only of debugfs entries for BYT/HSW platfroms.
This commit adds debugfs entries for APL/CNL.
=> logger: add debugfs entries for apl and cnl

src/audio/pipeline.c, src/lib/edf_schedule.c
Some idle task like for example KWD draining needs
significant amount of time to finish their job.
For example, to drain whole history buffer 6 milliseconds
are needed in non-synchronized mode and as much as 2100
milliseconds in synchronized mode with period 400 frames.
Therefore it is vital to exit idle task when it itself
is in *idle* state and allow other tasks to do their
job.
=> scheduler: enable idle task to be executed more than once

CMakeLists.txt
This commit updates paths of installed headers to match
new headers folders structure.
=> cmake: install: fix new headers paths

src/include/sof/alloc.h, src/lib/alloc.c
Currently we don't have atomic reallocation implemented. So make
unlocked versions of malloc, balloc and free, so they can be used in
single locking context with brealloc and realloc.
=> memory: implement realloc for rmalloc and rballoc

src/include/sof/audio/kpb.h, src/include/sof/audio/selector.h, src/include/user/kpb.h, src/include/user/selector.h
Move selector and kpb configuration structures to /sof/src/include/uapi/user to match eq and detect dummy structures configuration;
Signed-off-by: Wojciech Wittbrodt <wojciechx.wittbrodt@linux.intel.com>
=> include: user: move selector and kpb structures

src/arch/xtensa/boot_entry.S, src/arch/xtensa/smp/xtos/crt1-boards.S, src/arch/xtensa/smp/xtos/xtos-internal.h, src/lib/alloc.c, src/platform/apollolake/apollolake.x.in, src/platform/apollolake/boot_ldr.x.in, src/platform/apollolake/include/platform/memory.h, src/platform/apollolake/rom.x.in, src/platform/baytrail/baytrail.x.in, src/platform/cannonlake/boot_ldr.x.in, src/platform/cannonlake/cannonlake.x.in, src/platform/cannonlake/include/platform/memory.h, src/platform/cannonlake/rom.x.in, src/platform/haswell/haswell.x.in, src/platform/icelake/boot_ldr.x.in, src/platform/icelake/icelake.x.in, src/platform/icelake/include/platform/memory.h, src/platform/icelake/rom.x.in, src/platform/imx8/imx8.x.in, src/platform/intel/cavs/memory.c, src/platform/suecreek/boot_ldr.x.in, src/platform/suecreek/include/platform/memory.h, src/platform/suecreek/rom.x.in, src/platform/suecreek/suecreek.x.in, test/cmocka/include/mock_memory.h, test/cmocka/memory_mock.x.in, test/cmocka/src/lib/alloc/alloc.c
It introduces two significant optimizations:
> Separate the memory (heaps, stack) by cores so if we will turn off a specific core we can also turn off all memory of this core.
> Remove fixed defines and gaps, previously stack was at fixed position - end of memory and buffer heap was everything between stack and fw. Now everything will be packed at sof_fw memory segment and takes only this memory which is really needed, everything else we can turn off.
BSS section now includes heaps and stack
Removed many heap fixed position defines
Removed gap before fw text section in CNL
memmap init is using real linker positions for heaps
Temporary stack for boot_ldr placed in heap_hp_buffer (safe)
use linker stack position in boot entry
use linker heap position in sanity check
sof fw max_size limited …
=> memory: new memory layout

src/audio/dai.c, src/audio/host.c, src/drivers/dw/dma.c, src/drivers/dw/ssi-spi.c, src/drivers/imx/dummy-dma.c, src/drivers/imx/edma.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/dma.h, src/ipc/dma-copy.c, src/ipc/ipc-host-ptable.c
Refactors DMA callback data by using dedicated
callback struct along with callback status enum.
Previously field size was used to pass status
from component to DMA, which was misleading
and could cause potential issues e.g. value
0 was a valid number of bytes, but it was
also a value for DMA_RELOAD_END definition.
=>  dma: refactor callback data

Kconfig, src/drivers/CMakeLists.txt, src/drivers/Kconfig, src/drivers/dw/CMakeLists.txt, src/drivers/dw/Kconfig, src/platform/Kconfig
Resolves #1484 
Every platform should be handled in the same way. Not like it was now that we have some case for non-intel platform and fallback/default for Intel.
~~Assuming CONIG_CAVS is for intel as for now CAVS==INTEL and there is no point in adding symbol that will be 100% overlapping with another. We can add CONFIG_INTEL symbol when there will be non-cavs intel platform.~~ 
Forgot that we have byt&hsw also, so turns out we need that config.
=> cmake: drivers: split dw and intel

src/audio/volume/volume.c, src/include/sof/audio/volume.h
This patch adds feature to retrieve volume scale min and max from
IPC if the parameters are set. Volume min and max are now used
with ramp time parameter to compute gain ramp step to achieve
constant rate ramps with any volume scale. If the min and max are
zeros the previous FW operation is preserved.
Previously the firmware did not know the volume range so the
volume code uses in volume request a check to prevent exceeding
ramp length specified in topology by step size re-adjust. It was
done to prevent very long ramps to happen with volume scales with
large gain. However the smaller transitions remained longer than
necessary. This patch fixes that last remaining issue.
The ramp length check code is preserved to be compatible with
kernel versions those do not provide the min and max …
=> Volume: Use min and max volume scale values from IPC

src/audio/host.c, src/audio/pipeline.c, src/drivers/intel/cavs/hda-dma.c
Changes preload flow for host component using HDA-DMA.
Instead of waiting for DMA status for a limited amount
of time, it's better to just reschedule the pipeline
and check again. At least this time if the status
won't be set, we will know it's rather HW issue than
too small delay.
=> hda-dma: change preload from blocking to repeating

src/audio/host.c
Removes not needed check from host component.
It was supposed to detect if there is not enough
avail/free data, but since we've switched to
host copy on buffer callback this check is deprecated.
=> host: remove not needed check

src/platform/intel/cavs/memory.c
Structs sys_rt_x_blockXXX should not be created if not used
=> platform: fix compile error if PLATFORM_CORE_COUNT is 1

src/audio/component.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/volume/volume.c, src/include/sof/audio/component.h
Splits comp_set_period_bytes method to two separate
functions: comp_frame_fmt and comp_period_bytes.
Setting these two parameters in one function wasn't
intuitive nor atomic enough. Also setting value typed
variables through reference isn't pretty.
=> component: split comp_set_period_bytes method

src/arch/xtensa/boot_loader.c
Removes deprecated comment from boot_loader.
Memory window is enabled by ROM even before
FW is loaded, so there is no need for usage
of additional registers.
Closes #1389.
=> boot_loader: remove deprecated comment

src/include/sof/audio/buffer.h
Removes circular dependency between buffer and component
header files.
=> buffer: remove circular dependency

scripts/gen-doc.sh
Process of documentation building and publishing requires
3 repositories. It is troublesome for people that are responsible
f.e. only for documentation publishing. It makes the process
easier by turning some easy to break steps from publisher instructions
into a script.
=> scripts: add documentation generator

src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/tone.c, src/include/sof/audio/component.h
Removes checks for xruns in all components besides
dai. There is no need to check for underrun and
overrun in every component, because no free or avail
space in buffer doesn't mean that data is not continuous.
We can have processing modules inside the pipeline, which
work on different frame sizes than rest of the pipe. In
such cases we will detect false xrun. In the future we
can think about adding xruns checks to the components,
which will be connection points for multiple pipelines
e.g. separate pipe with the mixer in the beginning.
=>  component: remove checks for xruns

Kconfig
If all symbols in menu are not selectable if some
other symbol is not present, then there is no point
in showing that menu.
=> kconfig: hide cavs menu if not supported

src/drivers/intel/baytrail/ssp.c, src/drivers/intel/haswell/ssp.c
Fixes #1443 
It adds quirk support that was so far enabled only for CAVS platforms. Registers for BYT & HSW were already there.
=>  ssp: quirks for byt and hsw

src/lib/dma-trace.c
=> dma-trace: add missing error handling in dma_trace_start

src/platform/cannonlake/cannonlake.x.in, src/platform/icelake/icelake.x.in, src/platform/intel/cavs/include/cavs/memory.h, src/platform/intel/cavs/memory.c, src/platform/suecreek/suecreek.x.in
As adviced in PR #1557 it provides better memory/cache performance since it aligns with memory IO burst size and cache line size
This PR will use CACHE_LINE_SIZE in CNL, ICL and SUE
=>  memory: make buffers aligned to CACHE_LINE_SIZE

src/arch/host/include/arch/string.h, src/arch/xtensa/include/arch/string.h, src/audio/kpb.c, test/cmocka/src/universal_mocks.c
The current implementation of arch_memcpy_s() doesn't
allow to copy from adjecent memory block. This patch fixes
this problem.
=> memcpy: fix bug in arch_memcpy_s

tools/topology/sof/pipe-detect.m4
For detector component, the size of configure blob can be up to 200KB,
here enlarge the max to meet this requirement.
=> topology: pipe-detect: enlarge the bytes kcontrol size for blob settings

src/platform/apollolake/apollolake.x.in
Due to small number of memory banks in APL it will be not possible to power down some of them
so there is no point in align to memory banks, this would significantly limit free memory for buffers
=> memory: remove align to memory bank in APL

src/platform/imx8/imx8.x.in, src/platform/imx8/include/platform/memory.h, src/platform/imx8/memory.c
Similar to PR #1568 this will improve memory/cache performance
by aligning to the cache line size.
=> memory: make buffers aligned to BUF_HEAP_ALIGNMENT on the i.MX8

src/include/ipc/header.h
=> include: ipc: Fix inconsistency in the comments

rimage/elf.c
.static_log_entries does not exists if TRACE disabled so it needs to be optional for rimage
This + #1580 will fix: issue #1574
=> rimage: make .static_log_entries optional section

src/drivers/intel/baytrail/ssp.c, src/drivers/intel/cavs/ssp.c, src/drivers/intel/haswell/ssp.c, src/platform/suecreek/include/platform/clk-map.h
The first patch in the series fixes the second regression in #1575 on Sue Creek, which makes it unstable. This alone, however, doesn't fix Sue Creek completely. As described in #1575 there's also another regression, which breaks booting on Sue Creek. Reverting #1483 isn't any longer possible, #1567 doesn't apply any more either.
=> Sue Creek SSP clock fix and a cosmetic patch

src/audio/host.c, src/audio/kpb.c, src/drivers/dw/dma.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/audio/component.h, src/include/sof/dma.h, src/ipc/handler.c
Unifies host component for all DMA types.
We don't need to branch on CONFIG_DMA_GW anymore.
Closes #1052.
=> host: unify component for all DMA types

src/audio/kpb.c, src/drivers/intel/cavs/hda-dma.c
gcc will show errors if variables are set but not used, this will remove such a situations in fw if TRACE disabled
This + #1579 will fix: issue #1574
=> trace: remove unused variables if TRACE disabled

tools/topology/sof/pipe-detect.m4
We need to split detector config and model blob, create another bytes
kcontrol for model blob.
=> topology: pipe-detect: add kcontrol for model blob

src/audio/host.c
We do not have to use bytes to count copy_bytes since
copy_bytes variable is calculated based on hda-dma and
host buffer pointers. Bytes variable is not useful here - we 
should copy as much data as available in the host
buffer. Bytes variable gives additional unnecessary
limitation.
=> host: remove using bytes argument in host_buffer_cb

src/audio/host.c, src/drivers/dw/dma.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/dma.h, src/include/sof/dw-dma.h, src/platform/apollolake/include/platform/platform.h, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h
Amount of bytes we copied by host component should be
align to minimal possible chunk of data that can be
copied by hda-dma. In other case there is possibility of
occurrence mismatch between amount data we really copied
and buffer read and write pointers.
Should be merged after #842
=> host: add copy_bytes alignment in host_buffer_cb()

src/audio/host.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/dma-trace.h, src/lib/dma-trace.c, src/platform/apollolake/include/platform/platform.h, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h
I've made little cleanup in hda-dma defines:
1. HDA_BUFFER_ALIGNMENT and HDA_COPY_ALIGNMENT are not platform
specific. I've moved them from specific platform.h files to
hda-dma.c.
2. I've removed PLATFORM_HDA_BURST_SIZE define since it is the same
as HDA_COPY_ALIGNMENT - this change required using dma_get_attribute()
in dma_trace specific functions.
=> hda-dma: move HDA_ALIGNMENT defines to hda-dma.c

src/audio/host.c, src/audio/kpb.c, src/include/sof/audio/component.h, src/ipc/handler.c
Ignores host_trigger(), when host component is
configured in one shot copy mode. In such mode
the DMA is started every time in copy and stopped
automatically.
Fixes #1593.
=>  host: ignore host_trigger() for one shot copy mode

src/audio/host.c, src/audio/pipeline.c
Changes pipeline's preload conditions to take into
consideration the situation, where we don't always
want to do playback preload, because the sink part
of pipeline is already running e.g. mixer topology.
However the host component still needs to perform
preload on its own, so for now we make the decision
based on stream's direction.
Fixes #1526.
=> pipeline: change preload conditions

src/audio/detect_test.c
detect-test: refine model data management
Allocate model data memory at set_model stage.
Add struct model_data to manage model related stuff.
For set_model, re-allocate buffer at the 1st IPC, calculate crc after the
last IPC is handled.
For get_model, output the crc value at the 1st IPC.
=> KWD detector refinement

src/drivers/dw/dma.c
Changes DW-DMA release handling for configurations
not using hardware linked list support. We should
not make any additional copies in such case.
=> dw-dma: change release handling for non HW_LLI

src/drivers/dw/dma.c
Changes behavior for DMA_COPY_PRELOAD flag.
DW-DMA should just start transfer the same way
as for DMA_COPY_ONE_SHOT. It fixes playback
for platforms using DW-DMA for host transfers.
Fixes #1599.
=> dw-dma: change behavior for preload

src/audio/buffer.c
Improves traces for comp_update_buffer_produce
and comp_update_buffer_consume functions. Now
we will be able to easy identify failing components.
=> buffer: improve traces

src/audio/detect_test.c
We need initial a default buffer for model data at component new()
stage, and make sure we have non-0 size of this buffer otherwise, the
get_data cmd will fail.
=> detect-test: initial default size buffer for model data

src/audio/mux/mux.c
Mux component was lacking reset function implementation. This is to
address this issue.
=> Mux: implement comp_reset function.

src/drivers/intel/cavs/ssp.c
Support for M/N divider.
First FW will try to do it old way `SSCR0_SCR` and if clock is not divisible by bclk it will fallback to M/N.
~~@lgirdwood Please assign ABI number.~~ - No need after changing to automatic.
=> ssp: M/N divider

src/audio/buffer.c, src/audio/host.c, src/include/sof/audio/buffer.h, test/cmocka/src/audio/buffer/mock.c, test/cmocka/src/audio/kpb/kpb_mock.c, test/cmocka/src/audio/mixer/mock.c, tools/testbench/alloc.c
Depending on the topology, buffer size might not be multiple of dma
transfer size. So, round host buffer size up to nearest dma transfer
size multiple and possibly resize the host buffer.
=> Host buffer resize

tools/topology/sof-cml-rt5682-kwd.m4, tools/topology/sof/pipe-kfbm-capture.m4
topology: kwd: add volume component after dmic
topology: cml-rt5682-kwd: change to use S24_LE format for CML
=> kwd tplg update to support s24_le

tools/ctl/ctl.c
This fixes #1534 #1535 
Adding '-b' to support set/get control in binary mode, e.g. for set(),
using binary input file, for get(), dumping out in hex format.
Adding '-r' to indicate that there is no ABI header for the input file,
or ask for not dumping ABI header during getting.
Adding '-o' to specify the output file where will store the output kcontrol binary values.
Adding '-t' to specify the component specified type in ABI header.
=> sof-ctl: add support to binary input file.

src/audio/detect_test.c
We should use the absolute value for the activation comparing, and no
need to take extra handling to those samples with low enough level.
=> detect-test: refine the detect function

src/drivers/dw/dma.c, src/include/sof/audio/pipeline.h
pipeline: disable FW xrun recovery at the moment to rescue logs
dw-dma: add more logs when get avail data fail
=> Some minor fixes for debugging.

test/cmocka/src/audio/volume/volume_process.c
This patch adds check for sample to not exceed S24_LE range that
could happen in int32_t type storage. The existing check for
abs(delta) > 1 does not cover such case if e.g. the reference
volume code would output e.g. INT24_MAX and the FW component
INT24_MAX + 1.
Similar check is added for every reference volume function that
outputs S24_LE format.
=> Cmocka: Volume: Increase test coverage for S24_LE output format

tools/topology/sof-cml-rt5682-max98357a.m4, tools/topology/sof-cml-rt5682.m4
Add volume component, change to use 16KHz sample rate, and modify the
PCM ID from 5 to 8, as it is in lower priority comparing with pipelines
like amplifier.
=> topology: sof-cml-rt5682: refining for dmic16k pipeline

tools/topology/sof/pipe-eq-fir-volume-playback.m4, tools/topology/sof/pipe-eq-iir-volume-playback.m4
This patch provides needed maintenance. The pipelines
missed the volume ramp tokens and caused topology build fail for
topologies those would use the pipeline macros
pipe-eq-fir-volume-playback.m4 and pipe-eq-iir-volume-playback.m4.
The embedded filter coefficients in these pipelines were replaced
by included default FIR and IIR filter coefficients to fix ABI
incompatibility in the configuration blobs and ease future
maintenance of these pipelines.
=> Topology: Updates for single EQ pipeline definitions

tools/ctl/ctl.c
This is aim to fix #1640
For dumping to output file without '-r', we need to dump ABI header,
here fix it.
=> sof-ctl: fix ABI dumping doesn't work issue

src/audio/dai.c
In dai_playback_params() and dai_capture_params()
functions we do not have to take period values
from adjacent component. We can retrieve it from
dai component sof_ipc_comp_config struct.
=> dai: use periods from sof_ipc_comp_config in dai_params()

src/lib/alloc.c
The while loop in alloc_trace_runtime_heap() and
alloc_trace_buffer_heap() will always get the first matched heap from
get_heap_from_caps() and the loop will run infinitely.
This patch create a function alloc_trace_heap() which will be passed in
different heap_base and heap_count to fix the issue mentioned, and both
runtime_heap and buffer_heap can reuse this same function for tracing.
=> alloc: fix the heap alloc trace infinite loop issue

src/ipc/handler.c
This patch edit ipc_cmd (main ipc dispatcher) to return only at
the end of the function. This simplifies debugging a lot.
Along with that change additional log has been added at the
end of the function to show what was the the last request
and its return value.
=> handler: rework ipc_cmd to return only once and log last request

src/include/sof/common.h
Allows checking preprocessor symbols in compile-time.
Returns true for config with value 1, false for undefined
or any other value.
Expression like (CONFIG_MY ? a : b) rises compilation error when
CONFIG_MY is undefined, (IS_ENABLED(CONFIG_MY) ? a : b) can be
used instead of it.
It is intended to be used with Kconfig's bool configs - it should rise
error for other types, except positive integers, but it shouldn't be
used with them.
=> kconfig: IS_ENABLED macro

src/arch/xtensa/drivers/idc.c, src/audio/kpb.c, src/audio/pipeline_static.c, src/audio/volume/volume.c, src/drivers/dw/ssi-spi.c, src/drivers/imx/ipc.c, src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/sue-ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/audio/pipeline.h, src/include/sof/audio/volume.h, src/include/sof/drivers/dmic.h, src/include/sof/drivers/idc.h, src/include/sof/drivers/ipc.h, src/include/sof/lib/agent.h, src/include/sof/lib/wait.h, src/include/sof/schedule/edf_schedule.h, src/include/sof/schedule/ll_schedule.h, src/include/sof/schedule/schedule.h, src/include/sof/schedule/task.h, src/include/sof/trace/dma-trace.h, src/lib/agent.c, src/schedule/ll_schedule.c, src/schedule/schedule.c, src/trace/dma-trace.c, test/cmocka/src/audio/kpb/kpb_buffer.c, test/cmocka/src/audio/kpb/kpb_mock.c, test/cmocka/src/audio/pipeline/pipeline_free.c, test/cmocka/src/audio/pipeline/pipeline_mocks.h
Moves task structure and defines to the sof/task.h,
where they should be from the beginning. sof/schedule.h is
just for scheduler related things.
=> task: move task structure and defines to the right header

src/audio/mux/mux.c
This commit does not change FW behaviour since
both COMP_STATUS_STATE_ALREADY_SET and PPL_STATUS_PATH_STOP
defines are equal to 1. It just makes code more clear.
=> mux: return PPL_STATUS_PATH_STOP in mux_trigger()

src/audio/pipeline.c, src/ipc/ipc.c
This change allows us to free components and pipelines
in any order. Added setting component pointer to NULL
after comp_free() invocation. In pipeline_free() there is
a incovation of pipeline_comp_free() only if component
pointer is not NULL.
=> pipeline: refine pipeline_free() function

src/lib/alloc.c
When a block is used, we need reset the searching, to get the real
continuous blocks as required, here fix it.
=> alloc: allocate real continuous blocks in alloc_cont_blocks()

src/audio/host.c, src/include/ipc/stream.h
This change is to align sof_ipc_stream_params with its
kernel equivalent. The change is needed in both kernel
and FW because FW needs to use host_period_bytes which
where previously used to inform host about period IRQ.
Therefore now we introduce new member for it period_irq
and let host_period_bytes keep the proper value.
Corresponding Kernel PR is here https://github.com/thesofproject/linux/pull/1037
=>  ipc: align stream.h with kernel

src/audio/host.c, src/include/ipc/stream.h
Reverts thesofproject/sof#1592
It was merged too early - PR https://github.com/thesofproject/linux/pull/1082 on kernel side was merged to different branch than sof-dev.
PR that was planned to be merged together is still pending - https://github.com/thesofproject/linux/pull/1037
=> Revert " ipc: align stream.h with kernel"

src/arch/xtensa/include/xtensa/xtruntime-frames.h, src/arch/xtensa/init.c
Adds assert to verify if UserFrame's size is 16 bytes aligned.
=> arch: xtensa: add check for UserFrame's size alignment

src/audio/component.c, src/audio/dai.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/mixer.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/volume/volume.c, src/include/sof/audio/component.h, test/cmocka/src/audio/component/mock.c, test/cmocka/src/audio/mixer/mock.c
Component in comp_prepare() should change sink buffer
only when sink component is not connected to dma. 
comp_set_sink_buffer() checks whether sink component
is not connected to dma and only in that case tries to
resize sink buffer.
This PR also add dai buffer alignment in order to provide the same
alignment as in the host side. Otherwise it may appear buffer 
mismatch between host and dai (in simple host->dai pipeline)
resulting in issue #1650
PR fixes #1650
=> comp: add comp_set_sink_buffer() function

src/lib/alloc.c
Add proper stop condition during block hdr update
in alloc_cont_blocks() function.
=> alloc: fix blocks update in alloc_cont_blocks()

src/include/sof/lib/agent.h, src/lib/agent.c
This patch adds an option to temporarily disable system
agent. This is especially needed when SOF is performing
long last tasks like draining.
=> sys_agent: add option to temporarily enable/disable

src/drivers/intel/cavs/interrupt.c
This will fix interrupt.c build error if configured without traces.
=> trace: fix build error if traces are disabled

scripts/docker_build/sof_builder/Dockerfile
Install libglib2.0-dev with apt.
=> [skip ci]scripts: update glib support for fuzzer

src/arch/xtensa/xtos/exc-table.S
Before the commit the C exception handler table was declared empty
(suspiciously). This also caused my own tests to fail to call the panic
code whenever an exception occurred.
This commit fixes this by actually declaring the slots themselves and
initializing them to xtos_p_none, and also setting the correct size (64 * 4 instead of 0).
=> arch: xtensa: Fix exception handlers

tools/topology/CMakeLists.txt, tools/topology/sof-cml-demux-rt5682-max98357a.m4
This topology will add a mux pipeline to support echo reference for CML.
=> topology: add demux pipeline to CML max98357a tplg

src/debug/panic.c, tools/coredumper/sof-coredump-reader.py
Whenever one calls panic(), it eventually ends up in __panic. Here, the
various parameters (filename, line number etc.) are configured and
prepared for the upcoming panic dump.
For the sof-coredumper tool to work properly with panics, we need to
clear exccause (otherwise we would have a random value that may not even
be valid -- the exccause register is uninitialized at boot).
This does cause issues in case the exception code is in fact 0 (illegal
instruction) so hopefully this type of exception won't happen. The
exception dump will still work fine but the tool won't show this
particular cause in verbose mode.
=> panic: Distinguish exceptions from other panics

src/drivers/dw/dma.c
Adds check in dw-dma to make sure the channel is in fact
in active state before doing anything.
=> dw-dma: prevent from double stop sequence

src/schedule/ll_schedule.c
Fixes very rare race condition, when multiple cores
schedule something in low latency scheduler. We should
allow for timer client to execute one more time after
being cancelled. There won't be any tasks on the list
to process, but at least we will stop everything
gracefully.
=> ll_schedule: fix possible race condition

src/arch/xtensa/include/arch/init.h, src/arch/xtensa/include/arch/schedule/task.h, src/arch/xtensa/init.c, src/arch/xtensa/schedule/task.c, src/include/sof/init.h, src/include/sof/schedule/task.h, src/schedule/task.c
Abstracts slave core functions to arch layer. It doesn't
make sense to compile them, if they won't be used.
=> task: abstract slave core functions to arch layer

src/lib/alloc.c, src/platform/intel/cavs/lib/memory.c
Adds cache operations to alloc functions to get full
synchronized memory map between different cores.
Memory allocations aren't done so often so we can
afford to go through cache and perform so many
wtb/inv operations. This change allows slave cores
for allocation from runtime heap, buffer heaps etc.
=> alloc: fully synchronize memory map between cores

src/audio/eq_fir/eq_fir.c, src/audio/eq_fir/fir_hifi3.c, src/include/sof/audio/eq_fir/fir_hifi3.h
This patch fixes two similar mistakes from all the s16/s24/s32 dual
sample computing FIR core that was introduced in a previous update.
The FIR processing frames count processed double amount of samples
in buffer that corrupted FIR delay line and also the output write
to component sink buffer swapped two successive samples within one
channel.
The filter cores for s16 and s24 were simplified a bit since they can
use single output write pointer.
The FIR header file used wrong xtensa header file for HiFi2 while
it should have been for hifi3. Though no issues were observed due to
this mistake.
A check for frames count greater than zero was added into the copy()
function for extra safety. Also the return value from
comp_get_copy_limits() is not checked since the function always
returns zero. …
=> EQ FIR: Bug fix for HiFi3 optimized implementation

src/audio/eq_iir/CMakeLists.txt, src/audio/eq_iir/iir_hifi3.c, src/include/sof/audio/eq_iir/iir.h
This patch adds for HiFi3 xt-xcc compilation for an intrinsics
optimized direct form-II transposed (df2t) filter core version
that executes faster than the generic C version.
Due to HiFi3 instruction set the delay lines are changed from Q3.61
to Q17.47 format. It causes differences in bit-exactness but no
practical audio quality difference to generic C version.
=> EQ IIR: Add HiFi3 optimized version

CMakeLists.txt
In function target_link_libraries visibility modifiers have to be
consistent, otherwise we will get error while trying to use modifier,
if it wasn't used in root CMakeLists.
=> cmake: link sof libraries as private

tools/kmod_scripts/sof_insert.sh, tools/kmod_scripts/sof_remove.sh
Deal with missed codecs, new ones for SoundWire support and renaming of PCI/ACPI modules done by Jaroslav (the last part is required for tests with this week's upstream merge).
=> Fix kmod scripts

src/platform/imx8/lib/dai.c
ESAI implementation is still dummy, anyhow we need to initialize ESAI
spinlock in order to avoid FW crashes.
Similar with commit 2ee7a24f97d298f ("byt: hsw: ssp: move spinlock init
to earlier stage") we initialize the spinlock in an early stage at
dai_init.
We started to notice the crash after commit f7abaf7b3346e ("spinlock: allocate
spinlocks in uncached memory") which requires that the lock must be
dynamically allocated at init. Before, the lock was statically allocated
and there were no crashes.
=> imx8: dai: Initialize esai spinlock

CMakeLists.txt, scripts/cmake/misc.cmake, src/arch/xtensa/CMakeLists.txt
This PR  enables linking to precompiled static libs.
Example usage:
```cmake
sof_add_static_library(myClosedLib "path/to/lib/relative/to/current/dir/or/absolute")
```
=> cmake: support for 3rd party static libs

src/drivers/intel/cavs/dmic.c, src/include/sof/drivers/ssp.h, src/include/sof/lib/dai.h
Hi all,
I want to hear your opinion on having some generic DAI I/O access functions.
We will introduce IMX DAIs (SAI, ESAI) and for this, one should write identical:
* esai_read / sai_read
* esai_write / sai_write 
functions. 
Instead we can directly use the newly introduced generic functions:
* dai_read
* dai_write, etc
For the moment I wrapped ssp_read/dmic_read/etc around the newly introduce generic functions but in the future one might actually replace all ssp_read/dmic_read calls with dai_read functions.
What do you say?
=> [RFC] lib: dai: Introduce generic DAI I/O access functions

src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/sue-ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/drivers/ipc.h, src/ipc/handler.c, src/platform/cannonlake/include/platform/lib/shim.h, src/platform/cannonlake/power_down.S, src/platform/icelake/include/platform/lib/shim.h, src/platform/intel/cavs/include/cavs/drivers/sideband-ipc.h, src/platform/suecreek/include/platform/lib/shim.h
The first two patches are a minor cleanup in the IPC flow as well as cAVS 1.8 IPC HW definition fixes. Pls see their descriptions for full explanation.
=> ipc: fix sideband IPC (cAVS 1.8+) registers names and layout and make defs common

src/drivers/intel/cavs/dmic.c
This PR fixes bug that makes active FIFOs count go below 0,
if you call stop after pause.
=> dmic: fix stop after pause

tools/topology/sof-cht-nocodec.m4
Byt doesn't have enough memory to accomodate buffer size
increase from updating media pipeline's pcm_max_rate to
96kHz. So limit it to 48khz.
=> topology: change byt/cht max media pcm rate to 48kHz

src/platform/apollolake/include/platform/lib/dma.h
=> dma: Fix dma_chan_irq macro for APL.

src/drivers/dw/dma.c
Fixes simultaneous playback and capture on byt/cht platforms.
It's a temporary fix and will be replaced with the proper solution
soon.
Fixes #1677.
=> byt: fix simultaneous playback and capture

src/ipc/handler.c
src/include/sof/trace/trace.h:309:32: error: 'type' may be used uninitialized in this function [-Werror=maybe-uninitialized]
src/ipc/handler.c:1075:11: note: 'type' was declared here
uint32_t type;
This happens when hdr is NULL (even if it may never be at runtime the
compiler still complains) and verbose traces are enabled.
Additional comments: I uncovered this issue while rebasing my own working branch; somehow my config differed from default and lead to this error.
This variant of fixing it requires SEMVER minor ABI update. Another variant would be to just hardcode 0 as an initial value.
=> ipc: Fix compile error

src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/ssp.c
=> dmic: ssp: correct misused dma_get_drvdata instead of dai_get_drvdata.

tools/topology/sof-hda-generic-idisp.m4
Add missing virtual routes that will fail the probe.
Fix #1733
=> topology: add virtual routes for hda-idisp

zephyr/CMakeLists.txt, zephyr/alloc.c, zephyr/include/sof/alloc.h
Zephyr's k_mem_pool may not allocate memory aligned to cache lines and/or DMA transfers. So use mem_slab instead for buffers so each buffer is aligned correctly for DMA transfers and cache line manipulations.
=> Zephyr: Fix audio distortions

src/drivers/imx/interrupt.c, src/include/sof/common.h
Certain shared interrupts (in particular, those of the EDMA and ESAI -- drivers are being worked on) are of interest to the DSP. Since those interrupts aren't directly mapped to the DSP interrupts, we need to implement the IRQ_STEER cascaded interrupt support. This way we can access the shared interrupts 0-512 as the SOF platform interrupts 32-544 and allow the corresponding drivers for the DAI to register themselves for the correct interrupts.
In this pull request I implement the support for the IRQ_STEER interrupt controller as a cascaded interrupt controller.
Depends on PR #1738 and its commits are included here too.
=> Initial IRQ_STEER support for the i.MX platform

tools/topology/sof-cml-rt700.m4, tools/topology/sof-icl-rt700.m4
No need to have any whitespace or extra comments
CML had one issue with the PCM capture, now using PCM1 as for ICL
=> topology: align sof-icl-rt700 and sof-cml-rt700

src/drivers/interrupt.c
This error showed up while I was testing the IRQ_STEER call as printing
a weird value instead of a normal IRQ number (and I had an inconsistent
tree that lead to this error condition).
=> drivers: interrupts: Fix invalid trace_error call

src/drivers/imx/interrupt.c, src/platform/imx8/platform.c
In #1747 I forgot to actually call the platform_interrupt_init() function 
where I register the IRQ_STEER controller. This patch fixes that and activates
the IRQ_STEER controller.
(also, this passed the smoke test, namely I am in fact getting correctly numbered interrupts from the WIP code on the ESAI and EDMA drivers)
=> platform: imx: Enable IRQ_STEER driver

src/lib/notifier.c
Changes the way of sending notifications to slave cores
from blocking to non blocking mode. Blocking mode isn't
the best solution, because potentially we can be on higher
interrupt level, then the one for receiving idc result.
=> notifier: send idc notifications in non blocking mode

src/drivers/dw/dma.c
Fixes clearing done bit when using HW LL. There can be
a situation, when more than one linked list item has been
already transferred, so we need to clear all of them.
=> dw-dma: fix clearing done bit when using HW LL

src/drivers/imx/interrupt.c, src/platform/imx8/include/platform/drivers/interrupt.h
The interrupt numbers needed by the IRQ_STEER driver and those needed by
SOF's interrupt_* functions differ. While for this particular platform
it is known that there is a simple offset of 32, I implement this more
complex function to ensure that the interrupt numbers remain valid even
if somehow another cascaded interrupt controller is added.
This function is needed because the pure interrupt_get_irq() function
cannot properly treat the whole controller as only one, since it
receives interrupts over 8 hardware lines. This function determines
which hardware line is used then calls interrupt_get_irq() with the
correct controller name.
Additional comments: I intend to use this in the EDMA and ESAI drivers, although other IMX drivers that use …
=> drivers: imx: interrupt: Add convenience interrupt number translation

src/audio/dai.c, tools/topology/sof-cml-rt700.m4, tools/topology/sof-icl-rt700.m4
Now the sdw HW FIFO only accept 32bit sample, so force
dai format to 32bit to let volume component do the
conversion.
=> [SDW release] Refine FW and topology to make 16/24 bit pipeline work

tools/topology/sof-glk-da7219-kwd.m4
Currently glk kwd pipeline is set to run at 48kHz. This rate is wrong
and will create too big buffers and we will run out of memory. So set
the kwd pipeline rate to 16kHz.
=> topology: set glk kwd pipeline rate to 16kHz

src/arch/xtensa/drivers/idc.c, src/include/sof/drivers/idc.h
Adds support for sending idc messages from slave cores
to master core. Previously only master core could send
messages.
=> idc: add support for sending messages to master core

tools/ctl/ctl.c
If no control name is passed to sof-ctl, it currently pops an error,
dumps the usage and then segfaults:
root@gr-mrb:~# sof-ctl -D hw:0
Error: No control was requested.
Usage:   ...
Segmentation fault (core dumped)
Fix all that by jumping to the right label.
Signed-off-by: Dragos Tarcatu <dragos_tarcatu@mentor.com>
=> sof-ctl: fix segfault when no ctl name given

src/audio/dai.c, src/audio/host.c, src/drivers/dw/dma.c, src/drivers/dw/ssi-spi.c, src/drivers/imx/dummy-dma.c, src/drivers/imx/edma.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/lib/dma.h, src/ipc/dma-copy.c, src/ipc/ipc-host-ptable.c, src/platform/cannonlake/include/platform/lib/memory.h, src/platform/icelake/include/platform/lib/memory.h, src/trace/dma-trace.c
Extract common part of *_dma_chan_data into dma_chan_data structure with private pointer for class-specific data access, and expose it to the consumer for later use throughout lifecycle.
This is done in order to simplify API, as well as a preparation for future implementation of callbacks system for which it would be beneficial to have separate 'event caller' instances for each of the DMA channels for consumer to register to, as opposed to current, single DMA 'caller' exposed for registration.
Depends on fix: https://github.com/thesofproject/sof/pull/1751
=> dma: Refactor channel operations interface

src/drivers/intel/cavs/ssp.c, src/platform/intel/cavs/lib/pm_runtime.c
Some shim registers need M/N to not be 0/0 (state after dsp reset) in order to work.
=> ssp: pm: reset M/N and check CPA

src/ipc/handler.c, src/ipc/ipc-host-ptable.c
Fixes the bug, where any error in ipc_dma_trace_config handling
was always returned as -EINVAL.
=> ipc: return valid error in ipc_dma_trace_config

tools/tune/eq/eq_tplg_write.m
The existing IIR response names are not all upper case. This patch
removes the conversion to upper case to be able to automatically
generate the topology m4 syntax example equalizers.
Without this patch run of example_iir_eq.m script causes successive
topologies build to fail.
=> Tools: EQ: Don't force upper case EQ response name

tools/topology/CMakeLists.txt, tools/topology/sof-cml-da7219-max98357a.m4
add the topology files for Cometlake
with Intel ASoC DMIC 4ch capture, HDMI1/2/3 playback
with analog codec da7219 on SSP0 for headphone playback/headset mic
with digital codec max98357a on SSP1 for speaker playback
=> topology: cml: Add topology support for da7219+max98357a variant

src/audio/pipeline.c
This patch removes the IRQ disable during
pipeline_params() and pipeline_prepare() as there
is no potential race condition. Also, The disable of IRQs
result in long delays in queued interrupts.
=> pipeline: don't disable IRQ on prepare() and params()

src/audio/kpb.c
Adds missing flag during draining task initialization.
It's needed at the moment, so the EDF scheduler can ignore
deadline for this task. Scheduling flags will be soon
refactored.
=> kpb: add missing flag to task init

tools/topology/m4/dai.m4
SCHEDULE_DEADLINE is replaced with SCHEDULE_PERIOD, but there is one
missed in DAI_ADD for W_PIPELINE.
Fixes #1811.
=> topology: fix wrongly used SCHEDULE_DEADLINE

src/include/sof/common.h
Adds missing include of stddef.h, which defines offsetof
macro.
=> common: add missing include

src/arch/xtensa/include/arch/schedule/task.h, src/arch/xtensa/schedule/task.c, src/schedule/edf_schedule.c
The context switching layer is a common mechanism for all
pre-emptive schedulers and should not depend on data types
defined for any specific one.
=> task: remove edf specific elements from context switching layer

src/include/sof/trace/trace.h, src/platform/apollolake/include/platform/platform.h, src/platform/apollolake/include/platform/trace/trace.h, src/platform/baytrail/include/platform/trace/trace.h, src/platform/cannonlake/include/platform/platform.h, src/platform/cannonlake/include/platform/trace/trace.h, src/platform/haswell/include/platform/platform.h, src/platform/haswell/include/platform/trace/trace.h, src/platform/icelake/include/platform/platform.h, src/platform/icelake/include/platform/trace/trace.h, src/platform/imx8/include/platform/platform.h, src/platform/imx8/include/platform/trace/trace.h, src/platform/suecreek/include/platform/platform.h, src/platform/suecreek/include/platform/trace/trace.h, src/platform/tigerlake/include/platform/platform.h, src/platform/tigerlake/include/platform/trace/trace.h
Moves platform_trace_point macro from platform/platform.h
to platform/trace/trace.h. This way we don't need to
include platform header from generic sof/trace/trace.h.
=> trace: move platform_trace_point to dedicated headers

Kconfig, src/arch/xtensa/include/arch/lib/wait.h, src/platform/Kconfig, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/intel/cavs/lib/pm_memory.c, src/platform/suecreek/include/platform/platform.h, src/platform/tigerlake/include/platform/platform.h
The patches are required to remove circular dependencies that appear while introducing a new platform_wait... layer between the lib and the architecture layers.
=> Arch xtensa wait.h cleanup

src/audio/src/src.c
Currently SRC returns error when 0 size input or output data is detected
and pipeline interpretes this as fatal xrun error. This could happen
for example when host dma has no time to fill in first iteration of
samples. So instead of error, return 0 in this case as SRC in the
middle of the pipeline should handle also occasional 0 size data.
=> src: do not treat 0 size input data as error

src/lib/alloc.c
In alloc_cont_blocks() function after allocation we should
check whether new first_free block has been already used.
If it was used, we should find first not used block.
fixes #1714
=> alloc: fix first free update in alloc_cont_blocks()

tools/test/audio/sof-test-perf.sh, tools/test/audio/sof_test_perf.m, tools/test/audio/sof_test_perf_README.txt, tools/test/audio/sof_test_perf_config.m, tools/test/audio/sof_test_perf_top.m, tools/test/audio/src_test.m, tools/test/audio/std_utils/aap_test_measure.m, tools/test/audio/std_utils/aip_test_measure.m, tools/test/audio/std_utils/fr_test_input.m, tools/test/audio/std_utils/fr_test_measure.m, tools/test/audio/std_utils/g_test_input.m, tools/test/audio/std_utils/g_test_measure.m, tools/test/audio/std_utils/thdnf_test_input.m, tools/test/audio/std_utils/thdnf_test_measure.m, tools/test/audio/test_utils/chirp_test_analyze.m, tools/test/audio/test_utils/find_test_signal.m, tools/test/audio/test_utils/load_test_output.m, tools/test/audio/test_utils/mix_sweep.m, tools/test/audio/test_utils/remote_test_run.m, tools/test/audio/test_utils/write_test_data.m
This patch adds a shell script audio_quality_test.sh that
measures gain, frequency response, and total harmonic distortion
plus noise for a remote device.
Matlab or Octave is needed. The shell script launches by default
Octave to process the signal generation and test results analysis
scripts.
The remote device must be set to be accessible by ssh without
passwords. An external high quality USB sound card is recommended
as analog interface to connect to test device's analog interface.
The configuration file audio_quality_test_config.txt must be
edited for the remote device's user account, audio device, audio
format, and capture sound card audio device, and audio format.
=> Tools: Audio quality test for ssh accessible device

tools/test/audio/src_run.sh, tools/testbench/schedule.c, tools/testbench/testbench.c
This patch updates the locations of "make install" libraries default
install locations into shell script to run SRC test cases. The script
also now prints the used LD_LIBRARY path to ease setting up code
debugging.
The segfault of testbench executable is fixed by returning a valid
pointer reference instead of a NULL from test dummy function
arch_schedulers_get().  The rest of testbench version of schedule.c
was also updated to be like the current real version module.
Finally in the testbench.c main the file names string pointers are
initilizated to null as well as the word length parameter to avoid
a segfault if executable is started without command line arguments
to see the usage help text.
=> Tools: Test: Updates for testbench to match other changes in SOF

src/arch/xtensa/include/arch/drivers/timer.h, src/arch/xtensa/init.c, src/drivers/imx/timer.c, src/drivers/intel/baytrail/timer.c, src/drivers/intel/cavs/timer.c, src/drivers/intel/haswell/timer.c, src/include/sof/drivers/timer.h, src/include/sof/lib/notifier.h, src/include/sof/schedule/ll_schedule.h, src/include/sof/schedule/ll_schedule_domain.h, src/lib/agent.c, src/platform/apollolake/include/platform/platform.h, src/platform/baytrail/include/platform/platform.h, src/platform/baytrail/platform.c, src/platform/cannonlake/include/platform/platform.h, src/platform/haswell/include/platform/platform.h, src/platform/haswell/platform.c, src/platform/icelake/include/platform/platform.h, src/platform/imx8/include/platform/platform.h, src/platform/imx8/platform.c, src/platform/intel/cavs/platform.c, src/platform/library/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h, src/platform/tigerlake/include/platform/platform.h, src/schedule/CMakeLists.txt, src/schedule/ll_schedule.c, src/schedule/timer_domain.c
This patch introduces new structure called ll_schedule_domain.
It will be used to initialize ll scheduler with different
types of scheduling time domains. Right now it's only working
based on timer interrupts, but will be extended.
=> schedule: introduce ll_schedule_domain

scripts/qemu-check.sh
The qemu for BDW and HSW removed shm mbox and moved it into dram.
Change the scripts to the new version.
NOTE: this patch will cause regression with QEMU test untill QEMU docker updated.
=> scripts: qemu: fix qemu check for BDW and HSW

tools/topology/sof-cht-max98090.m4
Topology will fail to probe without these widgets
=> topology: cht-max98090 add missing virtual widgets

CODEOWNERS, src/arch/host/include/arch/drivers/timer.h, src/arch/xtensa/drivers/timer.c, src/arch/xtensa/include/arch/drivers/timer.h, src/drivers/imx/timer.c, src/drivers/intel/baytrail/timer.c, src/drivers/intel/cavs/timer.c, src/drivers/intel/haswell/timer.c, src/include/sof/drivers/timer.h, src/schedule/timer_domain.c
This patch checks if newly created timeout is not a
past time. Such issue will lead to dead scheduler.
NOTE! This will cause slight delay in tasks start time (only when previous tasks took more than scheduled period). I keep investigating what potential consequences it can cause, as for now it looks pretty safe.
=> ll_scheduler: add check for newly calculated timeout

tools/topology/sof-cht-max98090.m4
The DAI definition needs to come first otherwise the media pipeline with
be parsed incorrectly resulting in a failure to load the topology
=> topology: sof-cht-max98090 move DAI definition above media pipeline

src/audio/host.c, src/include/ipc/stream.h
This patch fixes the incorrect check for
host_period_bytes. This value was incorrectly used
to store host request for stream position. So
we introduced dedicated parameter for this purpose
(no_stream_position) and update all related checks accordingly.
=> ipc: align stream.h with kernel

src/arch/xtensa/include/arch/schedule/task.h, src/arch/xtensa/include/xtensa/xtruntime-frames.h, src/arch/xtensa/schedule/task.c, src/schedule/edf_schedule.c
Dynamic allocations of the stack with the default size
may impact the performance in case of frequently re-initiated
short tasks. This option may be useful in that case.
=> task: add option to provide stack allocated externally

src/drivers/imx/timer.c
This function is called too early for native timers to work. On the
other platform which uses native timers (Haswell) this function is also
empty.
With a non-empty such function I would get a timer interrupt before
registering for it.
=> drivers: imx: timer: Remove implementation for timer_start

src/audio/buffer.c, test/cmocka/src/audio/buffer/buffer_wrap.c
In case when we overwrite "old" data in buffer
(when buffer is full) we should align r_ptr
with w_ptr.
e.g.
we have full buffer:
buffer->avail = 10
buffer->free = 0
buffer->r_ptr = buffer->w_ptr = 0 
we produce additional 5 bytes:
comp_update_buffer_produce(buf, 5)
Here, we should align r_ptr with w_ptr, because
we have still 10 bytes data available.
buffer->avail = 10
buffer->free = 0
buffer->r_ptr = buffer->w_ptr = 5
=> buffer: add overwrite in circular wrap case

src/drivers/dw/dma.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/lib/dma.h
These functions replace the raw io_reg_* functions for accessing the DMA
hardware registers.
Every DMA driver makes auxiliary functions for accessing the hardware
registers; this is an effort to make common functions for this purpose.
This commit adds the generic functions.
I wonder how the DW DMA driver can use these, since it uses dma_base instead of dma_chan_base for computing the I/O addresses. Should I add other functions for that case and possibly rename those I introduce with this patch?
Cannot test locally, so I rely on CI to help me fix the build if it breaks.
=> [RFC] sof: lib: dma: Add register access helper functions

src/audio/kpb.c
This patch makes logs related to state change in KPB
component verbose.
=> kpb: make change state logs verbose

src/schedule/ll_schedule.c
Low latency scheduler is low latency, so the tasks shouldn't
be preempted by other things. This doesn't change any flow,
because xtos sets highest possible irq level in interrupt
dispatcher anyway.
=> ll_schedule: don't run tasks in non atomic context

src/platform/Kconfig, src/platform/baytrail/include/platform/lib/dma.h, src/platform/baytrail/lib/dma.c
The 3rd DMAC that CHT has seems to be causing issues. Since it is not
needed lets make it optional so the platform can be usable.
related to #1847
@lgirdwood I am not sure this is best place to set this config, let me know if I should move it
=> platforms: Enable optional cherrytrail DMA

tools/topology/CMakeLists.txt, tools/topology/sof-cht-src-50khz-pcm512x.m4
This PR provides the topology file required for https://github.com/thesofproject/linux/pull/1240. it's essentially the same topology as for APL, but with SSP2 uses instead of SSP5.
it is also required to check the behavior on CHT reported in https://github.com/thesofproject/sof/issues/1853, but should probably be merged on the issue is resolved.
=> topology: add topology for Up board w/ Hifiberry DAC+ using 50kHz SRC

tools/topology/CMakeLists.txt, tools/topology/get_abi.sh, tools/topology/sof-cml-demux-rt5682-max98357a.m4, tools/topology/sof-cml-rt1011-rt5682.m4, tools/topology/sof-cml-rt5682-max98357a.m4
With m/n divider support, we can now support 24 bit/ 48k
on max98357a.
Signed-off-by: Sathya Prakash M R <sathya.prakash.m.r@intel.com>
=> topology: Update CML topologies

src/audio/dai.c
Fixes freeing of dma channel. It's set during dai configuration,
so we should first check if it exists.
Fixes #1878.
=> dai: fix dma channel free

src/audio/host.c
This patch provides a check for channel existence
before performing any action on it during reset
procedure.
=> host: verify if channel exists before resetting it

src/drivers/imx/interrupt.c, src/drivers/intel/cavs/interrupt.c
Runs interrupt handlers for cascaded interrupts in non atomic
context. Otherwise we are blocking other cores during execution,
which is not needed, since we only need to protect integrity of
the list.
=> interrupt: cavs: run cascaded irq handler in non atomic ctx

src/arch/xtensa/xtos/int-medpri-dispatcher.S, src/arch/xtensa/xtos/xea1/int-lowpri-dispatcher.S, src/arch/xtensa/xtos/xea2/int-lowpri-dispatcher.S
We need to switch stacks before check for spurious interrupt,
because otherwise we will jump and try to restore stack pointer
from the wrong location.
=> arch: xtensa: fix exception in case of spurious interrupt

src/arch/xtensa/include/arch/lib/cpu.h, src/arch/xtensa/xtos/xtos-internal.h, src/platform/haswell/haswell.x.in, src/platform/haswell/include/arch/xtensa/config/core-isa-bdw.h, src/platform/haswell/include/arch/xtensa/config/core-isa-hsw.h, src/platform/haswell/include/platform/lib/memory.h
Provide a virtual threadptr register in the memory map using a linker
area below the stack. This can then be referenced instead of the register
for ISAs that dont support threadptr.
This patch also includes initial support for HSW/BDW platforms.
TODO: This patch now allow BDW to boot on real HW and updated qemu, but it fails on any context switch to IRQ level1 ? i.e. scheduling IRQs seem to work but any IPC (level1) will process and then break next scheduler IRQ invocation (causing a kernel exception). @tlauda any ideas ? 
=> xtensa: add support for platforms with no threadptr register.

src/arch/xtensa/include/arch/lib/wait.h, src/audio/kpb.c, src/audio/pipeline.c, src/audio/volume/volume.c, src/drivers/dw/ssi-spi.c, src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/idc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/sue-ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/drivers/ipc.h, src/include/sof/lib/wait.h, src/include/sof/schedule/schedule.h, src/include/sof/schedule/task.h, src/ipc/handler.c, src/lib/agent.c, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, src/schedule/schedule.c, src/schedule/task.c, src/trace/dma-trace.c, test/cmocka/src/audio/kpb/kpb_mock.c, test/cmocka/src/audio/pipeline/pipeline_connection_mocks.h, test/cmocka/src/audio/pipeline/pipeline_free.c, test/cmocka/src/audio/pipeline/pipeline_mocks.c, tools/testbench/edf_schedule.c, tools/testbench/schedule.c
Changes ipc task implementation, so it accepts new messages from
host in a complete task callback. This way we will avoid the
situation, where host will send another message before we
truly complete current ipc task.
=> ipc: add complete task callback

src/arch/xtensa/include/xtensa/xtruntime-frames.h, src/arch/xtensa/init.c, src/arch/xtensa/xtos/int-medpri-dispatcher.S, src/arch/xtensa/xtos/xea1/int-lowpri-dispatcher.S, src/arch/xtensa/xtos/xea2/int-lowpri-dispatcher.S, src/arch/xtensa/xtos/xtos-internal.h, src/arch/xtensa/xtos/xtos-structs.h
Fixes stack dump procedure for exceptions happening in interrupt
handlers. Stack base and size haven't been set to the interrupt's
one in current task context, so when exception happened during
interrupt processing we've got SOF_IPC_PANIC_STACK cause instead
of the real one.
=> arch: xtensa: fix stack dump for exceptions in irq handlers

src/audio/dai.c
Prevents dai_config while DAI is in active state.
It leads to undefined behavior and DSP exception
in some cases.
=> dai: prevent dai_config while in active state

src/include/ipc/dai-imx.h, src/include/ipc/dai.h, src/include/kernel/abi.h, src/include/kernel/tokens.h, tools/topology/CMakeLists.txt, tools/topology/m4/dai.m4, tools/topology/platform/common/esai.m4, tools/topology/platform/imx/imx8qxp.m4, tools/topology/sof-imx8qxp-nocodec.m4, tools/topology/sof/tokens.m4
i.MX8QXP contains one ESAI0 interface. This patch series adds helper m4 macros for ESAI and creates a simple playback topology with ESAI0 and nocodec.
With this we can test Dummy DMA, EDMA and ESAI drivers.
Corresponding changes for Linux kernel side will be sent right away.
=> Add nocodec pipeline for i.MX8QXP board

src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/idc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/timer.c, src/drivers/intel/haswell/ipc.c, src/drivers/intel/pmc-ipc.c, src/drivers/interrupt.c, src/include/sof/drivers/interrupt.h, src/schedule/dma_multi_chan_domain.c, src/schedule/edf_schedule.c
Removes unmask parameter from interrupt structures and functions.
It's not been used for a long time now.
=> interrupt: remove unmask parameter

tools/topology/CMakeLists.txt, tools/topology/sof-imx8qxp-cs42888.m4
This pipelines adds support for S24_LE, 2 channels, 48KHz playback.
cs42888 codec is connected to i.MX8QXP board on ESAI0 interface
as follows:
i.MX8QXP CPU board <--> i.MX8 base board <-> Audio I/O card
(setup similar with i.MX8QM, so this topology can be used as it is
be i.MX8QM also in the future).
=> topology: Add topology for i.MX8QXP with cs42888 codec

src/platform/imx8/platform.c
We first initialize the interrupts (IRQ_STEER controller) before
initializing the DMA domain because the interrupt numbers/names in the
DMA controller will be queried in the domain initialization.
=> platform: imx: Change the ordering of initializations in platform_init

src/audio/pipeline.c
With new schedulers implementation we don't need to reset
pipeline in atomic context anymore.
=> pipeline: reset pipeline in non-atomic context

src/arch/xtensa/drivers/timer.c, src/drivers/intel/baytrail/timer.c
Fixes return value of platform_timer_set and arch_timer_set functions.
Change was introduced for cAVS platforms, which accidentally broke
these functions for other platforms. The intention of this functions
is to return value of set ticks, so the timer scheduler can check
for delays.
=> timer: fix return values of platform_timer_set and arch_timer_set

src/drivers/imx/edma.c, src/platform/imx8/platform.c
On the i.MX platform the EDMA driver is responsible for scheduling all the
copies inside each pipeline which uses this controller. This patch set allows
this to happen.
@groncarolo This commit actually allows the IRQ numbers from #1931 to
be considered. So you will need both this PR and that one if you want to
test the SAI driver.
=> Add EDMA scheduling domain

src/include/sof/drivers/edma.h, src/platform/imx8/include/platform/lib/dma.h, src/platform/imx8/lib/dma.c
Initially I have hardcoded the specific values required for the ESAI.
That however is highly inflexible.
This commit refactors that to allow a more flexible declaration so that
other DMA clients can also get their proper interrupt numbers.
Only hardware which delivers its DMA interrupts via IRQ_STEER is
supported, however on this platform that is fine (all DMA channels
deliver their interrupts as shared interrupts via IRQ_STEER).
@groncarolo @jlacla I think you can use this and add your corresponding defines in the table so I'll unblock the SAI driver, right?
=> drivers: imx: edma: Remove hardcoding of interrupt numbers

src/drivers/dw/dma.c, src/include/sof/lib/dma.h, src/schedule/dma_multi_chan_domain.c
For DW-DMA without hardware linked list support we need
to manually reload linked list items after every interrupt.
It's very time-sensitive and even the slightest drift can
cause glitches, so this patch moves lli reload routine
to be called from DMA domain as an interrupt callback.
=> dw-dma: reload lli in irq_callback

src/platform/cannonlake/include/platform/lib/shim.h
Macro modified for SRAM segments > 0 fixed by register offset update to a proper value.
Signed-off-by: Lech Betlej <lech.betlej@linux.intel.com>
=> cnl: Access to HPSRAM power gating status register - macro updated

tools/topology/sof-cml-demux-rt5682-max98357a.m4, tools/topology/sof-cml-rt5682-max98357a.m4, tools/topology/sof/pipe-src-volume-playback.m4
Fixes SSP format and used pipeline macro in CML topologies.
Fixes: cfe81f5 ("topology: cml: cnl: use 3 periods for SSP, DMIC and ALH DAIs")
Fixes #1923.
=> topology: cml: fix errors in topologies

tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4
Changes ICL topology to use 3 periods for buffer connected to ALH DAI.
This topology has been forgotten, when such changes were done.
=> topology: sof-icl-rt711-rt1308-rt715-hdmi: use 3 periods for ALH

src/audio/dai.c
Adds new start_position field based on which we assess whether
we should throw an xrun. It fixes rare cases of xruns on release
with timer scheduled pipelines.
=> dai: fix rare case of xrun on release

src/ipc/ipc.c
Returns an error, when there is no DAI component
connected to the DAI index specified by DAI config
IPC.
=> ipc: return an error on dai not found

src/drivers/imx/sai.c
FIFO should be pre-filled with one word as per RM
recommendation after TRCE has been anabled
=> drivers: imx: sai: add one word to FIFO

src/audio/pipeline.c
In case of unsuccessfull scheduler task init, the pipeline
task init should also fail.
=> pipeline: check task init result

src/audio/src/src.c, tools/topology/CMakeLists.txt, tools/topology/sof-apl-src-dmic.m4, tools/topology/sof/pipe-src-capture.m4, tools/topology/sof/pipe-src-volume-capture.m4
This patch set fixes corrupt audio in SRC capture if the pipeline needs to convert PCM format from capture DAI format. Check is added to fail prepare() if pipelines requires SRC to convert between frame formats. The earlier version did not handle correctly 16 bit capture from 32 bit configured DAI. A test topology is added since earlier there was no topology to test capture-SRC.
=> SRC frame format detect logic fix and topology add for testing capture via SRC

src/audio/host.c
This patch fixes the trace message which logs always zero
value.
=> host: fix wrong trace value

src/drivers/imx/edma.c
channel must not be accessed when status *is* INIT
=> drivers: imx: edma: fix accessing register logic

src/platform/imx8/include/platform/lib/memory.h
The introduction of the DMA multi channel domain made it so the cascaded
interrupt handling fails to allocate memory from this heap. Increasing
the size of the system runtime heap will allow the registering of
cascaded interrupts (and in particular the EDMA interrupt within the DMA
scheduling domain) to continue.
=> platform: imx: Increase system runtime heap size

tools/test/audio/src_test.m, tools/test/audio/test_utils/find_test_signal.m
This pull request consists of two patches. The patch that is common for all component tests improves test begin/end marker tones find algorithm to avoid false test cases fails due to mistaking markers as test case output. The second adds a small relaxation into SRC gain test (increase tolerance for mismatch) to allow the current SRC version to pass the tests without fail.
=> Testbench fixes for test markers find and SRC gain test tolerance relax

src/audio/kpb.c, src/schedule/timer_domain.c
This fixes #1980 on the i.MX platform and should fix it on the others.
I cannot check platform specific code in other platforms, and CI doesn't
test this case. @keyonjie Can you please check if the code builds with this PR?
=> sof: Fix compile errors when traces are disabled.

src/audio/kpb.c
This patch slightly modifies draining speed algorithm.
Instead of copying half the buffer each period we
copy two periods. This slightly decreases draining
speed but avoids XRUNs in rare cases.
=> kpb: make draining algorithm more secure

src/drivers/imx/edma.c
burst_size represents the FIFO width in words, translate it
into bytes to have homogeneous quantities
=> drivers: imx: edma: translate burst size in bytes

src/drivers/generic/dummy-dma.c, src/platform/imx8/imx8.x.in
This improves the performance quite significantly -- pipeline_copy on
the simple ESAI pipeline (the cs42888 pipeline) took around 781us before
while with caching I got times of 15us at a minimum (a 50-fold
improvement).
@tlauda Thanks for the suggestion in the mailing list, it helped hugely as you can see.
=> platform: imx: Enable caching on the i.MX platform

src/include/kernel/tokens.h, tools/topology/m4/mixercontrol.m4, tools/topology/sof/pipe-eq-capture.m4, tools/topology/sof/tokens.m4
Add mute switch to capture playback pipeline's volume component. This
will show in user space alsa controls as 1 element with 2 controls
(volume and mute switch). Some user space audio software like this a
lot.
Add also binary data to switch control to enable possible use of acpi
leds with mute switch.
=> [RFC] topology: add capture mute switch and led info

src/platform/cannonlake/include/platform/lib/shim.h
=> cnl: shim: fix typo in CLKCTL bits definition

src/audio/dai.c, src/drivers/imx/esai.c, src/include/sof/drivers/esai.h, src/platform/imx8/lib/dai.c
The ESAI is a hardware DAI on the i.MX platform. This commit brings the
initial support for the ESAI.
Current problems:
-> Hardware FIFO watermark is hardcoded to 32. We must change to an
actual computed value. Total slots: 128. Also, burst_elems must be set
accordingly.
-> IRQ handling causes panics so it's disabled (not needed apparently?)
-> Possibly others?
-> Clock divider is hardcoded for 2 channels, 48000 Hz and MCLK being
at 49152000 Hz. Need to check the clock parameters.
-> ~I still need to understand some things about the clocking of this
system and explain them.~ Explained inline in the code
~Requires a local workaround when compiling with GCC (the generic volume component takes too long to process the 96 samples required in a …
=> drivers: imx: ESAI support

.travis.yml
Use matrix to maintain build job for easy extension.
Add workaroud to QEMU test to avoid accuracy error may cause false
alarm in boot test.
=> CI: travis: update with matrix to hold more platforms

src/arch/xtensa/init.c, src/audio/kpb.c, src/include/sof/lib/agent.h, src/include/sof/schedule/edf_schedule.h, src/include/sof/schedule/task.h, src/lib/agent.c, src/platform/Kconfig, src/platform/apollolake/include/platform/platform.h, src/platform/baytrail/include/platform/platform.h, src/platform/baytrail/platform.c, src/platform/cannonlake/include/platform/platform.h, src/platform/haswell/include/platform/platform.h, src/platform/haswell/platform.c, src/platform/icelake/include/platform/platform.h, src/platform/imx8/include/platform/platform.h, src/platform/imx8/platform.c, src/platform/intel/cavs/platform.c, src/platform/library/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h, src/platform/tigerlake/include/platform/platform.h, src/schedule/edf_schedule.c, src/schedule/task.c, tools/testbench/common_test.c, tools/testbench/edf_schedule.c
Refactors agent's functionality to really verify DSP
responsiveness. Instead of updating last_idle time
on passive level before entering waiti, let's change it
to last_check and update it on actual scheduler task
execution. Task is executed above passive level, so it
should preempt every other long running processing.
Since we don't have any additional precautions to guarantee
that low latency tick will happen exactly at the scheduled time,
let's define warning and panic thresholds to control stability
of the system.
=> agent: refactor agent to be more useful

src/audio/host.c
FW sends stream position message to kernel for its version before
3.11. In kernel, no_stream_position will be set to 1 for FW version
after 3.10, and host_period_bytes will be set to 0 for other versions.
So in host_update_position, the condition is always true for "hd->report_pos
/>= dev->params.host_period_bytes" for FW version before 3.11
Now check the condition dev->params.host_period_bytes != 0 according to
commit: b39b17ddf3e
=>  host: refine stream position update for FW version before 3.11

src/include/sof/lib/agent.h, src/lib/CMakeLists.txt, src/platform/Kconfig
Adds config option to disable system agent. It's helpful
on the still unstable systems, which cannot guarantee that
agent will execute on time.
=> agent: add option to disable system agent

.travis.yml
QEMU boot test will random fail with agent. Disable it to make sure
QEMU boot test will not fail.
Please merge after https://github.com/thesofproject/sof/pull/1998
=> [skip ci]CI: travis: disable agent for QEMU test

scripts/xtensa-build-all.sh
Let's align to use the newer 2017.8 toolchain for CNL building.
=> scripts:xtensa-build-all: update to use 2017.8 toolchain for CNL

src/trace/dma-trace.c
dtrace_event...() is protected by dmatb.addr verification
which may be assigned while other buffer attributes are
not set yet. It results in assert in case the initialization
is pre-empted by a code that attempts to log something.
=> dma-trace: fix race condition during initialization

src/audio/dai.c, src/drivers/dw/dma.c, src/drivers/intel/cavs/hda-dma.c
Refactors code for underrun and overrun detection. We should report
an xrun only if DMA get data size or DMA copy fails. In other case
even 0 available copy bytes doesn't mean anything, because we are always
copying as much as possible. Buffer could potentially be filled up front.
Fixes #2008.
=> dai: refactor xrun checking

tools/topology/sof-apl-wm8804.m4
The topology for UP2 + HiFiBerry Digi+ Pro sound card needs to
use for the pipeline host - volume - DAI the DMA interrupts
synchronized scheduling since the DAI is configured as I2S slave.
The timer based scheduling is applicable for this interface only
with ASRC that is not used by this simple topology.
=> Topology: Use SCHEDULE_TIME_DOMAIN_DMA with the WM8804 default topology

src/audio/pipeline.c
Memory allocated for p->pipe_task should be freed
in pipeline_free() in order to avoid memory leaks.
=> pipeline: add rfree pipe_task in pipeline_free

src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/pipeline.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/tone.c, src/audio/volume/volume.c, src/debug/panic.c, src/drivers/dw/ssi-spi.c, src/drivers/intel/cavs/dmic.c, src/include/sof/debug/debug.h, src/include/sof/lib/mailbox.h, src/ipc/handler.c, src/schedule/task.c, src/trace/dma-trace.c, src/trace/trace.c
If the assert semantics are changed to be the more usual ones, on
disabling asserts the calls that I changed would have also removed the
desirable side effects when the assertion itself passed (no memcpy_s
would have occurred, in particular). I have changed the usage of the
assert() macro so that the code becomes immune to such a change.
Fixes #1761
=> assert: Do not call assert() with side effects in the argument

src/include/sof/debug/debug.h, src/include/sof/spinlock.h, src/include/sof/trace/trace.h
This commit allows code such as:
```c
if (ret < 0)
trace_error("error: %d", ret);
return ret;
```
to work properly.
Fixes #1999
=> sof: trace: Do not have empty trace macros when traces are off

src/ipc/ipc.c
https://github.com/thesofproject/sof/issues/1954
https://github.com/thesofproject/sof/pull/1997
I found some functionality change after refactor, so in this PR it should be repaired.
While at it, also removed additional parenthesis in reference to 
https://github.com/thesofproject/sof/issues/1999
=> ipc: Break ipc_comp_dai_config after first error

src/audio/kpb.c, src/audio/volume/volume.c
PR adds schedule_task_free() in comp_free() functions in order to
avoid memory leaks and if needed moves schedule_task_init()
from comp_prepare() to comp_new()(comp_prepare() could be
invoked several times for one component instance).
=> components: add schedule_task_free() in comp_free() functions

src/arch/xtensa/init.c, src/include/sof/spinlock.h
=> sof: spinlock: Fix several compile errors related to spinlock debug

tools/kmod_scripts/sof_insert.sh, tools/kmod_scripts/sof_remove.sh
Adds support for inserting and removing snd_soc_rt1011 codec
in kmod_scripts.
Fixes #2027.
=> kmod_scripts: add support for snd_soc_rt1011

src/audio/dai.c, src/audio/host.c
Adds missing writebacks and invalidations of DMA buffer in
host and dai components.
=> host: dai: handle dma buffer in cache functions

src/drivers/dw/dma.c
Remove spinlock_init() in dw_dma_probe() function
in order to avoid memory leaks. spinlock_init() is
invoked in dmac_init() platform/*/lib/dma.c
files.
=> dma: remove spinlock_init() in dw_dma_probe()

src/audio/dai.c
This way we won't call get_handshake on DAIs which don't use it (and might not even have it implemented).
I have also added a fix for SAI where we actually use the handshake to select the DMA channel (@groncarolo @jlacla this fix may be of interest to you, can you test?)
=> sof: components: dai: Only get the handshake for DAIs which require it

scripts/checkpatch.pl
Merge kernel's checkpatch with custom features added for SOF.
SOF follows kernel code style, so checkpatch should be also up-to-date.
Fixes #1649 
=> checkpatch: update to match kernel 5.4-rc4

scripts/qemu-check.sh
The cavs platform IPC shm file name in QEMU is changed
from ipc-io to ipc-dsp-io.
Use wildcard to smoothly pass the transition of the QEMU update.
=> scripts: qemu: change ipc shm file name for cavs platform

src/platform/imx8/include/platform/lib/clk.h
Since SOF requires CLK_SSP to be defined and the SSP clock should be
separate from the actual CPU clock increasing the array size to 2 should
fix it.
This is a hack because i.MX doesn't actually have a SSP clock but SOF
unconditionally uses CLK_SSP macro.
Fixes out-of-bounds access revealed by pull request #1950.
=> platform: imx: Fix NUM_CLOCKS being too small

scripts/checkpatch.pl
Add checkpatch setting to make it easier to keep smaller delta with additional checkpatch + disable ints check that is not applicable to SOF.
=> checkpatch: SOF-specific changes

src/arch/host/CMakeLists.txt, src/arch/host/include/arch/string.h, src/arch/xtensa/CMakeLists.txt, src/arch/xtensa/boot_loader.c, src/arch/xtensa/include/arch/string.h, src/arch/xtensa/schedule/task.c, src/audio/buffer.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/kpb.c, src/audio/pipeline_static.c, src/audio/src/src_generic.c, src/audio/src/src_hifi3.c, src/debug/panic.c, src/include/sof/audio/buffer.h, src/include/sof/audio/component.h, src/include/sof/trace/dma-trace.h, src/ipc/handler.c, src/lib/alloc.c, src/lib/dma.c, src/platform/intel/cavs/lib/pm_memory.c, src/platform/intel/cavs/lib/pm_runtime.c, src/trace/dma-trace.c, test/cmocka/src/audio/buffer/buffer_write.c, test/cmocka/src/universal_mocks.c
Void pointer arithmetic isn't supported in Zephyr. This pull request removes it.
~Draft because I only added the flag so I get compile errors, without actually removing anything. I believe I should also add the flag on host?~ (no longer draft, host is also covered)
Fixes: #1913
=> sof: build: Disallow void pointer arithmetic

src/audio/mux/mux.c
Returns current config on COMP_CMD_GET_DATA. It fixes the problem
with wrong demux configuration after suspend. Kernel doesn't cache
initial kcontrol config and overwrites it with configuration returned
from component.
Fixes #1700.
=> demux: return config on COMP_CMD_GET_DATA

scripts/checkpatch.pl
checkpatch is currently checking for changes that need ABI updates
and actual ABI changes in the same loop in process(). So if some
file that needs an ABI change comes first, a WARNING will be issued.
Look for an actual ABI change before starting to crunch the entire
patch line by line.
Signed-off-by: Dragos Tarcatu <dragos_tarcatu@mentor.com>
Fixes: #2052
=> checkpatch: check ABI updates before warning on it

src/drivers/intel/cavs/ipc.c, src/include/ipc/header-intel-cavs.h, src/include/ipc/header.h, src/include/ipc/pm.h, src/ipc/handler.c
Selected cAVS IPC messages are transferred to the DSP using IPC registers and no mailbox located in SRAM which is the only safe way to send a message to the cAVS DSP when the DSP is in a lower power state.
A message is translated by the cavs ipc layer and then passed to the common ipc command handler.
Response always use the mailbox since there is no way to write the *T registers back with the current bi-directional communication implemented using a single *T register set.
Note: This is a proposal, moved from #1720. Intel cAVS specific change, no impact to the common code, no impact to other platforms. Payload byte order changed as suggested.
=> ipc: cavs: read short request directly from ipc registers

src/arch/xtensa/include/arch/lib/cpu.h
Access to vecbase, excsave2/3/4/5 is required for saving
the dsp core context while internal d0/d3 transitions
initiated by the low power sequencer.
=> arch: xtensa: add getters for special registers

src/platform/intel/cavs/include/cavs/mem_window.h, src/platform/intel/cavs/lib/CMakeLists.txt, src/platform/intel/cavs/lib/mem_window.c, src/platform/intel/cavs/platform.c
There might be other flows defined in future, that would
need to reprogram hw registers only while preserving
the content of memory windows.
=> platform: cavs: make windows clear on init optional

src/arch/xtensa/lib/cpu.c, src/platform/cannonlake/include/platform/lib/shim.h, src/platform/icelake/include/platform/lib/shim.h, src/platform/intel/cavs/lib/pm_runtime.c, src/platform/intel/cavs/platform.c, src/platform/suecreek/include/platform/lib/shim.h, src/platform/tigerlake/include/platform/lib/shim.h
Control of power gating for dsp cores implemented as pm-runtime operations for cavs platforms. Replaced direct read/writes of shim registers in the platform code.
=> cavs: pm: cores power gating

src/audio/src/src_hifi2ep.c, src/lib/alloc.c
Fix uninitialized in alloc.
Fix void pointer arithmetic in src hifi2 build
Split simple build fix from #2024
=> simple build fix for warning

src/include/sof/audio/mux.h
Because with current macro definition and enabled CONFIG_TRACEV macro code won't compile
=> trace: Repair tracev_mux_with_ids macro definition

scripts/checkpatch.pl
Traces in SOF are used like ` trace("<func>() info")`,
in that case `__func__` is not convenient, because it is not literal
and it would be needed to use %s everywhere and change
all current traces.
=> checkpatch: disable __func__ warning

scripts/cmake/kconfig.cmake
When there are changes made to Kconfig files it's better
to run olddefconfig automatically to prevent undesired behaviour,
like for example depending on added config that has some default value
that is not present because developer didn't run olddefconfig
after pulling changes.
Usefull f.e. in case like this: #2054 
=> cmake: trigger olddefconfig on kconfig changes

Kconfig, src/arch/xtensa/CMakeLists.txt
Introduces configs for optimization levels.
F.e. Baytrail needs -Os to fit  in IRAM when using XCC (probably tried to inline too much with -O2), as shown in #2024
=>  cmake: optimization levels

src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c
It isn't necessary to do a dai_get this early for the ESAI; the SAI
doesn't even have one.
Calling dai_probe() after dai_get() is pointless since dai_probe() was
already called from a previous dai_get() with CREAT flag (in particular
the one which incremented sref from 0 to 1).
I wonder if the last thing I said above doesn't also apply to other instances
of this that I have noticed (calling dai_probe() after dai_get() ).
=> platform: imx: Do not perform early get/init of the DAI

src/include/ipc/topology.h
We need this in order to match the exact comment from the
similar file in the Linux kernel.
sof_ipc_effect_type was the old name of the component no longer
used now.
=> include: ipc: Update comment for type field of sof_ipc_comp_process

src/drivers/imx/sai.c
The test determinating the current SAI mode (M/S) was buggy.
As a consequence SAI generated bit clock and FS clock when the codec was in
master mode (which is the default configuration for SAI currently with SOF).
This didn't prevent the DAI to function and have good sound, by chance.
Signed-off-by: Jerome Laclavere <jerome.laclavere@nxp.com>
=> drivers: imx: SAI : don't generate clocks in slave mode

zephyr/include/sof/cpu.h
This is accidentally deleted and caused copmilation errors.
Signed-off-by: Daniel Leung <daniel.leung@intel.com>
=> zephyr: restore include/sof/cpu.h

tools/logger/convert.c
Latest GCC does additional checks. This patch fixes the following build
error.
Scanning dependencies of target sof-logger
[  0%] Building C object logger/CMakeFiles/sof-logger.dir/convert.c.o
/home/lrg/work/sof/sof/tools/logger/convert.c: In function ‘serial_read’:
/home/lrg/work/sof/sof/tools/logger/convert.c:311:2: error: converting a packed ‘struct log_entry_header’ pointer (alignment 1) to a ‘uint32_t’ {aka ‘unsigned int’} pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
311 |  for (len = 0, n = (uint32_t *)&dma_log; len < sizeof(dma_log); n++) {
|  ^~~
In file included from /home/lrg/work/sof/sof/tools/logger/convert.c:15:
/home/lrg/work/sof/sof/tools/../src/include/user/trace.h:94:8: note: defined here
94 | struct log_entry_header {
| …
=> logger: fix build errors with gcc 9.1.x

src/drivers/intel/cavs/dmic.c, src/include/sof/spinlock.h
PR fixes 2 bugs with dmic:
1. There should be dmic task cancellation in ```dmic_stop()``` function
2. Sometimes deadlock appears:
In ```dmic_stop()``` function we invoked ```spin_lock(dai->lock)```,
then we had irq from low latency scheduler and run ```dmic_work()```.
At the beginning of ```dmic_work()``` there was spin_lock(dai->lock)
invocation which led to deadlock.
This PR fixes #2044.
=> dmic: change spin_lock to spin_try_lock in dmic_work()

CMakeLists.txt, scripts/cmake/misc.cmake, src/arch/xtensa/CMakeLists.txt, src/audio/CMakeLists.txt, src/include/sof/debug/debug.h, src/include/sof/debug/panic.h, src/include/sof/trace/trace.h, test/cmocka/CMakeLists.txt, test/cmocka/src/audio/mux/CMakeLists.txt, test/cmocka/src/audio/pipeline/CMakeLists.txt, test/cmocka/src/audio/selector/CMakeLists.txt, test/cmocka/src/audio/volume/CMakeLists.txt, test/cmocka/src/debugability/macros.c, tools/testbench/CMakeLists.txt
Because of `__FILE__` macro paths used f.e. in panics are dependent on where project is built.
Also compiler doesn't care about the fact that we use just part of that path and if `__FILE__` is referenced it gets inserted as whole into .rodata of compilation unit.
This PR introduces custom RELATIVE_FILE to overcome this issue and make given sof build has the same size no matter where it's built. (+ it saves some space)
=> sof: make .rodata deterministic

src/audio/eq_iir/CMakeLists.txt, src/audio/eq_iir/eq_iir.c, src/audio/eq_iir/iir.c, src/audio/eq_iir/iir_generic.c, src/audio/eq_iir/iir_hifi3.c, src/include/sof/audio/eq_iir/iir.h
This patch adds capability to equalizer to switch response during
audio playback or capture. The glitches are minimized by check and
apply of the filter configuration before each copy() operation.
The existing only halfway implemented SOF_CTRL_CMD_ENUM for quick
stored presets switching during streaming is removed for now since
there is no driver support.
The internal code cleanup includes extracting two functions from
eq_iir_setup() for check and initialize of coefficients and
initialize of filter delay lines.
To minimize number of duplicated functions in generic and HiFi3 version
a new module iir_generic.c is created for the filter core. After the
change iir.c contains only the common code for both implementations.
Finally, some trace messages are cleaned up to easier to understand …
=> EQ IIR: Add support for response reconfigure during streaming

tools/kmod_scripts/sof_remove.sh
The HDMI codec may also use snd_hda_codec_hdmi
=> kmod_scripts: add support for common hdmi

tools/kmod_scripts/sof_remove.sh
new module added, needs to be listed in sof_remove.sh
=> kmod_scripts: add support for soundwire_generic_allocation

src/include/sof/audio/component.h
Add two parameters to comp_dev struct in order to allow
configuration of the component processing variable frames.
Added parameters are:
- min_sink_bytes - min free sink buffer size measure in bytes
required to run component's processing;
- min_source_bytes - amount of data measured in bytes
available at source buffer required to run component's processing.
Every component could update those parameters in 
comp_params() due to pcm params change.
=> component: add min_sink/source_bytes to comp_dev struct

src/include/sof/audio/src/src.h
The previously used cast of pointer to size_t (unsigned int)
has worked but it's horrible way to do it. Cast to uint8_t *
should be clean portable code.
=> SRC: Fix pointer arithmetic in circular buffer wrap functions

src/drivers/intel/cavs/dmic.c, src/include/sof/spinlock.h
Use block expression instead of do {} while(0) macro
in spin_try_lock in order to return its value in a
safer way.
=> spinlock: spin_try_lock refinement

src/drivers/imx/edma.c, src/drivers/imx/interrupt.c
In order to get XCC to work on this platform I had to resolve two compile errors. These solutions don't change the logic of the code.
=> Fix compile errors for i.MX on XCC

src/audio/pipeline.c, src/drivers/intel/cavs/dmic.c, src/include/sof/audio/pipeline.h, src/include/sof/schedule/ll_schedule_domain.h, src/include/sof/schedule/schedule.h, src/include/sof/schedule/task.h, src/schedule/dma_multi_chan_domain.c, src/schedule/dma_single_chan_domain.c, src/schedule/ll_schedule.c, src/schedule/timer_domain.c, tools/topology/sof-apl-demux-pcm512x.m4, tools/topology/sof-apl-keyword-detect.m4, tools/topology/sof-apl-nocodec.m4, tools/topology/sof-bdw-codec.m4, tools/topology/sof-byt-codec.m4, tools/topology/sof-cht-max98090.m4, tools/topology/sof-cht-nocodec.m4, tools/topology/sof-cml-demux-rt5682.m4, tools/topology/sof-cml-rt5682-kwd.m4, tools/topology/sof-glk-da7219-kwd.m4, tools/topology/sof-hsw-rt5640.m4
This patch enables separate scheduling of connected
pipelines. It allows for different scheduling periods
between connected pipelines and flexible controlling
of such topologies.
Fixes #1502.
=> pipeline: schedule pipelines separately

scripts/xtensa-build-all.sh
The tools version and core must be correctly defined in order to be
able to compile for this platform with XCC.
=> platform: imx: Update build script for compiling with XCC

src/platform/Kconfig
The description of this switch says that any LX6 Xtensa architecture revision DSP
should have this enabled, and the particular DSP in the i.MX8 does fit
this description.
Considering the comment in code:
`src/arch/xtensa/include/arch/lib/wait.h:30` : `        /* LX6 needs a delay */`
=> platform: imx: Enable WAITI_DELAY

src/include/ipc/header.h, src/include/sof/audio/component.h, src/include/sof/lib/pm_memory.h
The changes fix command unbalanced groupings and remove discrepancy
between parameters in function declaration & definition of
set_power_gate_for_memory_address_range() function.
Signed-off-by: Lech Betlej <lech.betlej@linux.intel.com>
=> include: Remove doxygen warnings during documentation generation

src/drivers/intel/cavs/ssp.c, src/include/sof/drivers/ssp.h, src/include/sof/lib/clk.h, src/lib/clk.c, src/platform/apollolake/lib/clk.c, src/platform/baytrail/include/platform/lib/clk.h, src/platform/baytrail/lib/clk.c, src/platform/cannonlake/lib/clk.c, src/platform/haswell/include/platform/lib/clk.h, src/platform/haswell/lib/clk.c, src/platform/icelake/lib/clk.c, src/platform/imx8/include/platform/lib/clk.h, src/platform/imx8/platform.c, src/platform/intel/cavs/include/cavs/lib/clk.h, src/platform/intel/cavs/lib/CMakeLists.txt, src/platform/intel/cavs/lib/clk.c, src/platform/intel/cavs/platform.c, src/platform/suecreek/lib/clk.c, src/platform/tigerlake/lib/clk.c
Create abstract interface for clocks and move platform specific
clocks code to platform folders.
It was also necessary to move SSP clocks declarations to
SSP driver code to decouple clocks logic from mandatory
SSP clocks.
=> clk: platform agnostic clocks

src/arch/xtensa/xtos/xtos-structs.h
~This is required for the vectorial instructions emitted by xcc to not~
~trigger a DSP panic within the DMA multi-channel domain.~
~The stack should normally be already aligned when entering this~
~function, but apparently it isn't so this code does a manual alignment.~
~The compiler assumes the alignment is already there when generating code~
~and preserves it when it is, but the question is what happens when it is~
~only aligned to a multiple of 4.~
~Signed-off-by: Paul Olaru <paul.olaru@nxp.com>~
~How can I study exactly what causes the stack to become unaligned at that point?~
**EDIT**: The original issue was fixed by just aligning the interrupt stacks themselves.
So I just do that and wonder how they weren't already aligned.
=> Align interrupt stacks to 16 bytes

src/arch/xtensa/boot_loader.c
After disabling tracing code have compilation error because of
implicit declaration of platform_trace_point function.
After calling through trace_point it is replaced with empty
define after disabling trace.
=> trace: use trace_point instead of platform_* in boot_loader.c

src/drivers/dw/dma.c, src/platform/apollolake/include/platform/lib/shim.h, src/platform/baytrail/include/platform/drivers/dw-dma.h, src/platform/cannonlake/include/platform/lib/shim.h, src/platform/haswell/include/platform/drivers/dw-dma.h, src/platform/icelake/include/platform/lib/shim.h, src/platform/intel/cavs/include/cavs/drivers/dw-dma.h, src/platform/intel/cavs/platform.c, src/platform/suecreek/include/platform/lib/shim.h, src/platform/tigerlake/include/platform/lib/shim.h
Enables DW-DMA channel linear link position counter based
on the selected peripheral connection. It can be used
to retrieve timestamping information on platforms supporting it.
=> dw-dma: enable channel linear link position

src/include/sof/lib/mailbox.h
It didn't work correctly if multiple cores write to "sw regs"
allocated on the same cache line.
https://github.com/thesofproject/sof/issues/2127#event-2822601594
=> trace: Use uncached memory in trace_point and panic

src/include/sof/lib/notifier.h, src/platform/imx8/include/platform/lib/clk.h, src/platform/imx8/lib/clk.c
The i.MX platform doesn't have an SSP clock so it shouldn't have dummy
defines related to that. This patch set removes said defines.
Here there is also another minor change required for this removal to take
place. I'm waiting on comments on how it can be done better but for now
adding that #if #else guard seems to be the easiest solution.
Fixes #2049
=> platform: imx: Remove all references to SSP clock

src/platform/intel/cavs/include/cavs/lib/asm_memory_management.h, src/platform/intel/cavs/lib/CMakeLists.txt, src/platform/intel/cavs/lib/power_down.S
Compiler options has to be changed in order to compute
the literal block address correctly.
Some literals must be declared explicitly and loaded
indirectly to make sure that compiler does not optimize
the out to another shared region.
=> pm: cavs: fix literal dcache lock in power down

src/audio/CMakeLists.txt, src/audio/dai.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/pcm_converter/CMakeLists.txt, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/volume/volume.c, src/audio/volume/volume_generic.c, src/audio/volume/volume_hifi3.c, src/include/sof/audio/buffer.h, src/include/sof/audio/component.h, src/include/sof/audio/format.h, src/include/sof/audio/pcm_converter.h, src/include/sof/audio/volume.h, src/include/sof/common.h, src/include/sof/lib/dma.h, src/lib/dma.c, test/cmocka/src/audio/volume/volume_process.c, tools/topology/sof/pipe-kfbm-capture.m4
Implements generic and HiFi3 versions of PCM converter library component.
This module provides static functions, which allows to copy
buffer data with frame format conversion.
=> pcm_converter: add implementations

src/include/sof/lib/notifier.h
The previous version changes behavior on the BYT platform.
Fixes: ee9283c1
=> sof: clk: Remove specificity on clock notifier change ID

tools/topology/sof-cml-rt1011-rt5682.m4
This patch fixes DAI_ADD function call for speaker pipeline.
The function call had incorrect number of agruments passed which was causing issues with playback.
=> Topology: Fix DAI_ADD function call in sof-cml-rt1011-rt5682 topology

src/audio/asrc/asrc.c, src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/pipeline.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/switch.c, src/audio/tone.c, src/audio/volume/volume.c, src/audio/volume/volume_generic.c, src/audio/volume/volume_hifi3.c, src/include/sof/audio/buffer.h, src/include/sof/audio/component.h, src/include/sof/audio/volume.h, src/ipc/handler.c, test/cmocka/src/audio/mixer/comp_mock.c, test/cmocka/src/audio/mixer/mixer_test.c, test/cmocka/src/audio/mux/util.h, test/cmocka/src/audio/selector/selector_test.c, test/cmocka/src/audio/volume/volume_process.c, tools/testbench/file.c, tools/testbench/include/testbench/file.h
Moving pcm params from component to buffer is the first
step to improve parameter propagation within pipelines (#1280).
This commit moves several pcm paremeters (framet_fmt, buffer_fmt,
rate, channels, chmap, except direction) to comp_buffer struct.
Some of specific parameters are moved to private host and
kpb data.
=> [RFC]component: move pcm params from component to buffer struct

src/audio/mux/mux.c
There was unintended phrase from trace.
=> mux: Remove artefact from trace in mux_params

src/audio/detect_test.c
The assumption is that load_mips equals MCPS (million cycles per second).
Then only a fraction of MCPS has to be consumed for each processing frame
depending on a frame length and a sampling rate.
Signed-off-by: Lech Betlej <lech.betlej@linux.intel.com>
=> detector: fix bug in synthetic load calculation

src/platform/Kconfig, src/platform/cannonlake/include/platform/lib/clk.h, src/platform/intel/cavs/platform.c
A new config option allows to select between the default
ring oscillator used to clock the dsp core and memory
on Intel Cannonlake platform.
CANNONLAKE_LPRO sets the default clock to 120MHz low power
oscillator, otherwise 400MHz oscillator is used.
=> cnl: clk: add config option to select default ro clock

Kconfig
WAITI_DELAY is selected for LX6 Xtensa platforms one of which being
i.MX8 Hifi4 DSP.
Also, remove the input prompt because the actual WAITI_DELAY cannot
be set at compile time it is automatically selected based on arhitecture.
=> kconfig: Move WAITI_DELAY outside of CAVS menu

src/audio/mixer.c, src/audio/mux/mux.c
Fetches params (for mux and demux) from sink buffer
(sink buffer params are set in pipeline_set_params() before
mixer/mux_params()). For mux and mixer components some
of source buffer can be unset yet in mixer/mux_params(). 
Fixes #2154 
=> comp: fetch params from sink buffer

.gitignore
We don't need to accidentally commit ctags files. The linux kernel
ignores these definitions, let's ignore them too.
=> gitignore: Ignore ctags cache files

tools/sof_ri_info/sof_ri_info.py
This script parses manifests included in sof binary and prints
extracted metadata in readable form.
It is particularly useful to get information about image signature
parameters.
Note: --full_bytes prints complete modulus and signature (by default arrays > 16 bytes are compacted by skipping middle bytes as in the example below)
```bash
$ ./sof_ri_info.py --headers sof-cnl-signed.ri
SOF Binary sof-cnl-signed.ri size 0x46000
CSE Manifest ver 0x101 checksum 0xb7 partition name ADSP
ADSP.man (CSS Manifest) type 0x4 ver 0x10000 date 2019/11/22
Rsvd0 0x0
Modulus size (dwords) 64
41 a0 3e 14 1e 7e 29 72 ... cd 1d fa fd e8 a0 ba 91 (CNL Intel prod key)
Exponent size (dwords) 1
01 00 01 00
Signature
d5 c4 67 89 75 f0 aa 93 ... da 26 06 6a de …
```
=> tools: add sof-ri-info to print fw image manifests content

.gitignore
We don't need to accidentally commit cscope files. The linux kernel
ignores these definitions, let's ignore them too.
This commit was inspired from a similar commit adding ctags cache files.
Signed-off-by: Diana Cretu <diana.cretu@nxp.com>
=> gitignore: Ignore cscope cache files

src/platform/imx8/platform.c
For some reason I omitted to do this when the Dummy DMA (host DMA) driver was usable. Now I have seen that the solution was in fact this simple (the DMA trace init complete call wasn't originally there because that required a working host DMA, which initially didn't exist).
=> platform: imx: Enable DMA trace on the i.MX8 platform

src/lib/alloc.c
Invalidates memory regions, which are requested to be uncached.
This way we can make sure we won't overwrite data by accident.
=> alloc: invalidate uncached memory

src/lib/alloc.c
Fixes modulo bug in get_ptr_from_heap function,
where alignment can potentially be 0. Modulo zero
is undefined operation.
=> alloc: fix modulo zero bug

src/schedule/dma_multi_chan_domain.c, src/schedule/dma_single_chan_domain.c, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, src/schedule/timer_domain.c
Makes schedulers and scheduling domains ops constant and effectively
puts them in rodata segment.
=> schedule: make ops constant

src/arch/xtensa/include/arch/init.h, src/arch/xtensa/init.c, src/include/sof/init.h, src/include/sof/lib/notifier.h, src/init/init.c, src/lib/notifier.c
Moves sof structure initialization to master core to avoid
data being overwritten by slave cores in case of future use.
=> init: remove need to access sof struct on slave cores

tools/kmod_scripts/sof_remove.sh
After Kernel PR [#1565](https://github.com/thesofproject/linux/pull/1565) being merged, correct driver is loaded on CML with rt1011 and rt5682, we got one more module need to be removed in module unload/reload test
this patch add snd_soc_cml_rt1011_rt5682 module removal support for CML platform with rt1011 and rt5682 codecs.
=> kmod_scripts: add support for snd_soc_cml_rt1011_rt5682

src/arch/host/include/arch/spinlock.h, src/arch/xtensa/include/arch/spinlock.h, src/include/sof/drivers/interrupt.h, src/include/sof/lib/wait.h, src/include/sof/spinlock.h, src/include/sof/spinlock_t.h
This refactor allows some extra type checking to happen which was not
permitted by a macro-only approach.
Draft because I believe I may split commits or change approach, dependent
on feedback.
=> sof: spinlock: Refactor spinlock related macros

src/audio/volume/volume.c, src/include/sof/audio/volume.h
This patch fixes the issue of audio left muted after a cycle
of mute and unmute commands. The additional improvements are
applying of gain ramp for mute that helps to avoid annoying click
sounds. Also since the driver issues both volume and switch
commands back to back the duplicate scheduling of ramp update is
prevented if there is already a ramp happening. The old ramp
will operate based on new step and direction if it was changed.
Some variable names were changed in function volume_set_chan()
for better readability. The impacted trace print commands were
also updated to not split strings unnecessarily.
=> Volume: Fix handling of mute and unmute control

src/include/sof/drivers/ssp.h, src/include/sof/lib/clk.h, src/lib/clk.c, src/platform/apollolake/lib/clk.c, src/platform/baytrail/include/platform/lib/clk.h, src/platform/baytrail/lib/clk.c, src/platform/baytrail/platform.c, src/platform/cannonlake/lib/clk.c, src/platform/haswell/include/platform/lib/clk.h, src/platform/haswell/lib/clk.c, src/platform/haswell/platform.c, src/platform/icelake/lib/clk.c, src/platform/imx8/lib/clk.c, src/platform/imx8/platform.c, src/platform/intel/cavs/include/cavs/lib/clk.h, src/platform/intel/cavs/lib/clk.c, src/platform/intel/cavs/platform.c, src/platform/suecreek/lib/clk.c, src/platform/tigerlake/lib/clk.c
Refactors generic clock API to simplify used data structures.
It makes more sense now and spares us a little bit of memory.
=> clk: remove unnecessary additional structures

src/platform/baytrail/platform.c
The firmware may have modified these values to execute features such as
a boot beep. Therefore we cannot assume they are set to their defaults.
Lets write the defaults just to be safe.
Fixes #1847
=> platform: cht: reset ssp clk M/N dividers on boot

src/drivers/intel/baytrail/ipc.c, src/ipc/handler.c, src/schedule/task.c
When entering runtime suspend or system suspend, the host
driver sends a CTX_SAVE IPC. When this IPC is received,
the FW should call wait_for_interrupt from run level 0.
The IPC task is not at run level 0, therefore this
should be done in the main audio task, which runs at level 0.
Additionally, in the case of baytrail, the DSP doesn't
enter D3 in the case of runtime suspend. So, when the host
tried to resume the DSP, the pm_prepare_D3 flag is not reset
to 0. So, we need to explicitly reset it to 0 when the
host sends the CTX_RESTORE IPC.
=> byt: ipc: Move WFI to run level 0

src/audio/Kconfig, src/include/sof/audio/pcm_converter.h
Due to stability issues of hifi3 pcm conversion the
used implementation should be switched to generic.
This is a temporary measure, the hifi3 implementation
should be enabled again once stability issues are resolved.
=> workaround: disable hifi3 pcm conversion

tools/topology/CMakeLists.txt, tools/topology/sof-tgl-max98357a-rt5682.m4
Add TGL topology for the DUT which has the following audio configuration:
Max98357A speaker (I2S)
ALC5682 headset codec (I2S)
DMIC
4 HDMI devices
=> topology: add TGL tplg for max98357a amp and ALC5682 Headset codec

tools/topology/CMakeLists.txt, tools/topology/sof-bdw-codec.m4, tools/topology/sof-bdw-nocodec.m4
Fix sof-bdw-rt286.tplg load
Add HSW/BDW nocodec topology.
=> Enable BDW topology

src/audio/kpb.c, src/include/sof/audio/kpb.h, src/include/user/kpb.h, test/cmocka/src/audio/kpb/kpb_buffer.c
This patch reworks the validation of host params so KPB can make use
of host buffer bigger than internal history buffer.
=> kpb: rework of validation of host params

src/platform/baytrail/include/platform/lib/shim.h
It appears that this definition was copied from the haswell definitions
but this register does not actually exist. Therefore we should use the
correct registers depending on the platform.
=> byt: fix SHIM_SHIM_END copy paste error

src/arch/xtensa/debug/CMakeLists.txt, src/debug/gdb/ringbuffer.c
If `Debug ---> GDB Stub` configuration option is enabled, the build is currently failing because of some pointer arithmetic errors and link-time errors. These patches are fixing those. 
For baytrail, the build still fails as it has no SRAM_DEBUG_BASE:
sof/src/debug/gdb/ringbuffer.c:12:44: error: 'SRAM_DEBUG_BASE' undeclared here (not in a function); did you mean 'MAILBOX_DEBUG_BASE'?
volatile struct ring * const rx = (void *) SRAM_DEBUG_BASE;
^~~~~~~~~~~~~~~
MAILBOX_DEBUG_BASE
=> Fix build failures with CONFIG_GDB_DEBUG

src/audio/pipeline.c, src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/sue-ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/drivers/ipc.h, src/ipc/handler.c, src/ipc/ipc.c, src/schedule/task.c
Refactors IPC notification sending in order to minimize allocated
memory space. Instead of statically allocating the whole queue of
twelve ipc_msg structures, let's do it dynamically if there is the
actual need of sending message to host.
=> ipc: optimize memory usage for IPC notifications

src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c
Sets *_delay pointer to NULL when freed to prevent attempts
to free the buffer multiple times.
Fixes #2176
=> eq_iir: eq_fir: set *_delay pointer to NULL when freed

src/schedule/ll_schedule.c
Fixes low latency task insertion into the priority list.
From now on tasks will be inserted in the right order based
on their priority and time of insertion.
Fixes #2219.
=> ll_schedule: fix task insertion

src/arch/xtensa/include/arch/drivers/interrupt.h, src/drivers/intel/cavs/interrupt.c, src/platform/apollolake/include/platform/drivers/interrupt.h, src/platform/cannonlake/include/platform/drivers/interrupt.h, src/platform/icelake/include/platform/drivers/interrupt.h, src/platform/intel/cavs/include/cavs/drivers/interrupt.h, src/platform/suecreek/include/platform/drivers/interrupt.h, src/platform/tigerlake/include/platform/drivers/interrupt.h
Changes interrupt controller names to const.
They are not supposed to be modified.
=> interrupt: make irq names const

src/audio/asrc/asrc.c
This patch adds the missing freeing of data structures those
were allocated in prepare(). Successive pipeline runs without
suspend in between have consumed more and more RAM every time.
=> ASRC: Fix memory leak in reset()

src/audio/kpb.c, src/ipc/handler.c, src/platform/intel/cavs/lib/pm_runtime.c, test/cmocka/src/audio/kpb/kpb_mock.c
Power Management for DSP Core(s)
================================
DSP cores are managed by providing `PM_RUNTIME_DSP` context id and core
index to the pm-runtime API functions.
Some platforms may provide advanced power management of the DSP cores,
including clock gating in idle, complete power gating in idle, etc.
depending on how the cores are integrated on that platform.
An implementation of platform API may provide customized idle entry
function `platform_wait_for_interrupt()` which may simply call
`arch_wait_for_interrupt()` or perform more sophisticated power
transition in order to get a better power savings when the DSP core is
in idle.
An advanced power transitions may last longer since the DSP core /
platform has to some back from a deeper power state. This additional
latency is …
=> cavs: pm-runtime: enable dsp master core state transitions

scripts/checkpatch.pl
This is an exception similar to the kernel pr_...() family.
Having a log string in a single line is much more readable for
a person who works with the trace output frequently.
Splitting trace strings into multiple lines seems to be a worse
alternative since it generates another warning anyway and encourages
developers to create very long trace entries which are wrapped
on a trace console and less readable.
=> scripts: checkpatch: accept long trace strings (80+ characters)

src/audio/detect_test.c, src/include/sof/math/numbers.h, src/math/numbers.c
This will allow to "continue" crc calculations when data is not a continuous block in memory.
=> math: allow crc32 calculations on non-continuous data blocks

src/audio/buffer.c, src/include/sof/audio/buffer.h
It will be helpful during debugging components
to see correlated pipeline id.
=> trace: Add pipeline id to buffer traces

src/drivers/intel/baytrail/ssp.c, src/drivers/intel/cavs/ssp.c
Hweight32 function can be replaced with builtin popcount
that is more performant.
=> ssp: replace hweight with builtin popcount

src/include/sof/spinlock.h
Enabling CONFIG_LOCK_DEBUG currently breaks the build for APL as
spin_try_lock is undefined.
src/drivers/intel/cavs/dmic.c:167:8:
error: implicit declaration of function 'spin_try_lock';
did you mean 'arch_try_lock'? [-Werror=implicit-function-declaration]
ret = spin_try_lock(dai->lock);
^~~~~~~~~~~~~
Fix that by making sure spin_try_lock gets defined regardless of
either CONFIG_LOCK_DEBUG is enabled or not.
Signed-off-by: Dragos Tarcatu <dragos_tarcatu@mentor.com>
=> sof: spinlock: Fix placement of spin_try_lock

src/platform/apollolake/include/platform/platform.h, src/platform/cannonlake/include/platform/platform.h, src/platform/icelake/include/platform/platform.h, src/platform/suecreek/include/platform/platform.h, src/platform/tigerlake/include/platform/platform.h
These functions are unused and can be deleted.
=> platform: remove unused mn functions

scripts/cmake/version.cmake
Command git describe looks only for annotated tags, but we should
get any tag reachable from master, that's why --tags flag is needed.
=> cmake: version: consider unannotated tags

tools/topology/sof/pipe-eq-volume-playback.m4
This patch increases the max. size to 4 kB. Such size allows
setting up e.g. 8ch 192 tap FIR. The multiple part configuration
IPC support has existed in the EQ component for a while and this
limit in topology has remained not updated.
=> Topology: FIR: Increase maximum size of configuration data blob

tools/topology/CMakeLists.txt, tools/topology/sof-jsl-da7219.m4
Add topology support for max98373 and da7219
codec for JasperLake platform.
=> topology: Add JSL da7219+max98373 support

src/lib/lib.c
Function cmemcpy is unused, there is no need to keep dead code.
Git exists, so if someone really wants that code then it can be recovered from git history.
=> lib: remove unused cmemcpy

src/include/sof/audio/pcm_converter.h
Include config.h in header where this define is used
=> pcm_converter: Properly handle CONFIG_FORMAT_CONVERT_HIFI3

.github/ISSUE_TEMPLATE/bug_report.md
Update bug form to point to new location of the document.
Fixes: #2263
=> github: fix link to bug tracking docs

src/drivers/intel/baytrail/ssp.c, src/drivers/intel/cavs/ssp.c, src/drivers/intel/haswell/ssp.c
Trace macros are already defined in ssp.h.
=> drivers: intel: deduplicate ssp trace macros

src/audio/dai.c, src/platform/cannonlake/include/platform/drivers/alh.h, src/platform/icelake/include/platform/drivers/alh.h, src/platform/intel/cavs/lib/dai.c, src/platform/tigerlake/include/platform/drivers/alh.h
The burst length of GP-DMA should align to DMAT setting
in Audio Link Hub, or XRUN will happen. We don't change
DMAT setting since it is also used by cAVS FW.
Tested on CML.
And this PR doesn't make current kernel failed to work with SDW
=> dai: ALH set burst_elems

src/audio/detect_test.c, src/audio/kpb.c
This patch enables callbacks on IPC message.
This functionality is useful when you want to do extra work on FW side right after IPC to host has been sent.
=> detector: send IPC notification to host before draining starts

src/audio/eq_fir/eq_fir.c, src/audio/eq_fir/fir.c, src/audio/eq_fir/fir_hifi2ep.c, src/audio/eq_fir/fir_hifi3.c, src/include/sof/audio/eq_fir/fir.h, src/include/sof/audio/eq_fir/fir_hifi2ep.h, src/include/sof/audio/eq_fir/fir_hifi3.h
This pull request adds to FIR capability to change the configuration during playback or capture plus other changes to align the features with recent updates to IIR. There are four commits:
- Add support for runtime reconfiguration
- Remove handling of set/get value commands
- Extrapolate channels response map with last valid
- Add trace verbosity and align with IIR trace output
=> EQ FIR: Add support for runtime reconfiguration

src/audio/volume/volume.c
The trace issue is only cosmetic since VOL_MIN is currently defined
to zero. There linear gain value was not altered despite the emitted
trace. With this change the limiting no more happens for input value
zero.
The related trace messages are improved to show the defined limits
for easier adjust the offending topology volume scale if this
happens. The string split style is also updated to current.
=> Volume: Avoid unnecessary error trace about limiting to VOL_MIN

rimage/file_simple.c, rimage/rimage.c, rimage/rimage.h, src/arch/xtensa/CMakeLists.txt, src/arch/xtensa/configs/imx8x_defconfig, src/drivers/CMakeLists.txt, src/drivers/imx/interrupt.c, src/platform/CMakeLists.txt, src/platform/Kconfig
Short explanation for i.MX8 naming.
i.MX8 has 3 major platform sub-families:
* i.MX8
* i.MX8X
* i.MX8M
Looking at the integration of Hifi4 DSP, i.MX8 and i.MX8X are pretty similar. So, for this reason when
I added initial support I referred to both i.MX8 and i.MX8X as i.MX8, but in fact only i.MX8X was supported.
There is one notable difference -  IRQSTEER address is different. The current supported IRQSTEER address is the one in i.MX8X. So, this PR separates i.MX8X/i.MX8 like baytrail is separated from cherrytrail (using basically the same source files) with CONFIG_IMX8 / CONFIG_IMX8X to select the correct code.
Support for i.MX8M is in preparation and a patch will be sent soon.
=> Add support for i.MX8

src/audio/detect_test.c
Revert changes introduced in commit 7003c1f for s32 format.
Moreover explicity declare threshold for s32 on same level as
for s24 to indicate that it is intentional.
=> kpb: Set activation threshold for s32 format

src/audio/detect_test.c
We should get threshold with valid bits rather than sample width. this patch fix  [KWD trigger failure under s16le](https://github.com/thesofproject/sof/issues/2113)
=> kpb: get correct threshold with valid bits

src/drivers/intel/cavs/ipc.c, src/ipc/handler.c
When entering D0ix, we can run FW with either DMA trace on (e.g. the
host system is in S0) or off (e.g. the host system is in S0ix), here
take the NO_TRACE flag passed from host and response to it.
=> ipc: take NO_TRACE flag of SETD0IX IPC from host

src/audio/dai.c, src/audio/host.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/include/sof/audio/buffer.h, src/include/sof/audio/pcm_converter.h, src/include/sof/lib/dma.h, src/lib/dma.c
Input buffer should be explicit marked as const to indicate
that input samples and other comp_buffer fields shouldn't
be modified (especially r_ptr/w_ptr).
=> pcm_converter: buffer: Add const keyword to data source

src/drivers/intel/cavs/CMakeLists.txt, src/drivers/intel/cavs/Kconfig, src/drivers/intel/cavs/mn.c, src/drivers/intel/cavs/ssp.c, src/include/sof/drivers/mn.h, src/include/user/trace.h, src/platform/apollolake/include/platform/lib/dai.h, src/platform/cannonlake/include/platform/lib/dai.h, src/platform/icelake/include/platform/lib/dai.h, src/platform/intel/cavs/lib/dai.c, src/platform/suecreek/include/platform/lib/dai.h, src/platform/tigerlake/include/platform/lib/dai.h, tools/logger/convert.c, tools/testbench/trace.c
Initial MN driver version that should fix 2 major problems:
1) BCLK & MCLK logic was written like there were only 1 SSP port in existence, topologies with more SSPs in use could result in incorrect settings (config 2nd overriding source clock for config 1st etc).
2) ECS bit support was dropped in cAVS 2.0 and M/N is only supported source for BCLKs.
Fixes #2084
=> drivers: intel: M/N initial driver and fixes

tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4, tools/topology/sof-icl-rt711-rt1308-rt715.m4
This patch mitigates the start transient in capture from rt715
codec. The start transient is DC pulse that can be attenuated
significantly with a high-pass filter. The pipeline macro
pipe-highpass-capture.m4 adds a 40 Hz second order IIR filter
into the beginning of pipeline. The volume control in this pipeline
is also set to a longer 400 ms ramp length (normally 250 ms) that
is sufficient to conceal PCM waveform issues before the IIR filter
settles to DC level.
=> Topology: Apply high-pass filter to rt715 capture pipelines

src/audio/component.c
Removes debug trace, which has been merged by accident.
=> component: remove debug trace

src/include/ipc/topology.h, src/include/kernel/abi.h
Adds core id to sof_ipc_comp. The intention of this change
is to incorporate full SMP flow in DSP for IPC handling.
Right now all components and buffers are created on master core
and cache is synchronized between cores, when pipeline is supposed
to run on slave core. With this change we can detect on which core
particular component is supposed to be running and let that core
do the work of handling IPC.
Matching kernel PR: https://github.com/thesofproject/linux/pull/1739
=> ipc: component: add core id to sof_ipc_comp

src/drivers/imx/edma.c, src/include/sof/lib/dma.h, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/intel/cavs/platform.c
Changes sequence of initialization in platform_init(),
so that DMA scheduling domain can be initialized with the DMA
taken through sof context. This allows for removal of another
externed global variable.
=> platform: use dma from sof context for domain initialization

src/audio/pcm_converter/pcm_converter_hifi3.c
In HiFi implementation should be used copy methods with prefix
from audio_stream_* instead buffer_* because of removing this
functionality to audio_stream module.
=> pcm_converter: Use copy method from audio_stream

tools/topology/sof-apl-pcm512x.m4
2 patches to add capture support on Up^2 boards using a DMIC board and an analog input on the HiFiBerry DAC+ADC codec card. Note, that it should be used with https://github.com/thesofproject/linux/pull/1714
=> Pcm512x capture

src/audio/kpb.c
This commit introduces proper calculation of buffered_data,
which should not exceed buffer_size value. Firstly, we calculate
free space in history buffer and we add minimum value from
copy_bytes and hb_free_space.
=> kpb: fix buffered_data calculation

src/audio/eq_fir/eq_fir.c, src/audio/eq_fir/fir.c, src/audio/eq_iir/eq_iir.c, src/audio/eq_iir/iir.c, src/audio/mux/mux.c, src/audio/selector/selector.c, src/drivers/dw/dma.c, src/include/sof/common.h
GCC 9.x introduces checks for packed data alignment when being passed or
cast as different types. Fix these issues.
=> gcc: build fixes for GCC 9.x

src/drivers/dw/dma.c, src/include/sof/lib/mailbox.h, src/platform/baytrail/include/platform/lib/mailbox.h, src/platform/baytrail/include/platform/lib/memory.h, src/platform/haswell/include/platform/lib/mailbox.h, src/platform/haswell/include/platform/lib/memory.h, src/platform/imx8/include/platform/lib/mailbox.h, src/platform/imx8/include/platform/lib/memory.h, src/platform/imx8m/include/platform/lib/mailbox.h, src/platform/imx8m/include/platform/lib/memory.h, src/platform/intel/cavs/include/cavs/drivers/dw-dma.h, src/platform/intel/cavs/include/cavs/lib/mailbox.h, src/platform/library/include/platform/lib/mailbox.h, src/platform/library/include/platform/lib/memory.h
Removes uncache macros from platforms, which don't support
uncached memory region.
=> memory: remove uncache macros from several platforms

src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/audio/src/src.c, src/include/sof/audio/audio_stream.h, src/include/sof/audio/pcm_converter.h, src/include/sof/lib/dma.h, src/lib/dma.c
pcm_converter: audio_stream: Pass offset to first sample to function call
During conversion every available data sample from source stream through
temporary buffer. Size of this buffer may be big enougth to always convert
each data stream in one pass and converter interface doesn't need to be
changed but then capacity of this buffer must be same as source stream
(in samples). In this scenario memory management is very inefficient,
espially with grow of number of components with such a need.
There are also a few solution to use smaller buffers instead.
It can by achieved by:
1) manually moving r_ptr in source stream in component copy() routine,
what shouldn't happen in such a place
2) calling buffer_consume() after each portion of samples, what leads
to data fragmentation and performance …
=> pcm_converter: audio_stream: Pass offset to first sample to function call

src/include/sof/audio/audio_stream.h
Field frame_fmt is treated as sof_ipc_frame in code so data type
in declaration should be same. Update field comment to be more
appropriate with new data type.
=> Audio stream:  use enum data type for frame_fmt field

src/audio/dai.c, src/drivers/intel/cavs/dmic.c, src/include/sof/lib/dai.h, src/ipc/handler.c, src/lib/dai.c
Ssp and other dai traces should follow the dmic example once there is no objection on re-using trace entry id's for dai type and index (instead of sending them sometimes as arguments).
=> Trace: dai unified identification and cleanup

src/drivers/Kconfig, src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/drivers/ipc.h
This PR takes the current IRQ/scheduler implementation for certain IPC operations and reduces them
to simple IPC command and status polling. Useful for GDB and bootloader stub uses cases.
=> IPC: add polling support

tools/topology/sof-imx8qxp-cs42888.m4, tools/topology/sof-imx8qxp-wm8960.m4
1) Change DAI name, to accomdate the name in machine driver. We hope that we will be able to use simple-card in the exact form that it is in our internal tree.
2) Use s32le instead of s24le for wm8960 codec because SAI doesn't have the 24bit limitation that ESAI has.
=> Two topology fixes

src/arch/xtensa/boot_loader.c, src/platform/cannonlake/include/platform/lib/memory.h
The change adds power gating of unused memory banks for cavs 2.0/2.5 hardware on top of previously enabled flow for cavs 1.8.
=> cavs: enable power gating of unused memory banks for cavs 2.x hw

tools/testbench/common_test.c, tools/testbench/file.c, tools/testbench/ll_schedule.c, tools/testbench/schedule.c, tools/testbench/testbench.c, tools/testbench/topology.c, tools/tplg_parser/tplg_parser.c
Testbench has been for a while broken due updates to SOF where is was behind. This PR consists of fixes those I needed to successfully run test pipelines with it.
Note: The EFD scheduler forcing is only a short term fix. The testbench would need a clean non-realtime scheduler for the simulations. Also the core forcing to zero for buffer is strange, I don't know why it happens for buffer but not for normal components like SRC and volume.
=> Testbench: Collection of fixes

src/arch/xtensa/boot_loader.c, src/platform/apollolake/include/platform/lib/shim.h, src/platform/cannonlake/include/platform/lib/shim.h
This patch fixes a bug in LP_SRAM init procedure and
cleans up unused shim offset.
=> registers: fix bug lp_sram init

tools/topology/sof-jsl-da7219.m4
Fix the extra 0 introduced by mistake, while here
also change format from s16le to s32le.
=> topology: jsl: fix the extra parameter for HDMI DAIs

tools/topology/m4/utils.m4
Add the PIPELINE_ID to the graph section name to
make them unique for the platback and capture pipelines
that are associated with the same SSP.
Fixes https://github.com/thesofproject/sof/issues/2201
=> topology: graph: Add PIPELINE_ID to graph name

src/audio/volume/volume.c, src/include/sof/audio/volume.h
Makes volume ramping task dynamic meaning it will be
allocated only when needed. There is no need to have it
allocated statically unless the pipeline will be in fact used.
=> volume: make task dynamic

src/include/sof/drivers/dmic.h, src/include/sof/drivers/ssp.h, src/include/sof/lib/wait.h, src/lib/wait.c
Unused code shouldn't be present in source code, it only makes system
more difficult to understand.
=> wait: Remove unused completion_t with related functions

src/ipc/cc_version.c
Structures with flex array also should have size aligned to 4 bytes
at least to omit misalignment data accec in following data.
As long as CC_DESC is null terminated, padding data doesn't have
any impact on functionality.
=> cc_version: Align up struct size with flex array

src/include/ipc/info.h, src/include/sof/fw-ready-metadata.h, src/ipc/CMakeLists.txt, src/ipc/cc_version.c, src/ipc/probe_support.c, src/platform/apollolake/apollolake.x.in, src/platform/baytrail/baytrail.x.in, src/platform/baytrail/platform.c, src/platform/cannonlake/cannonlake.x.in, src/platform/haswell/haswell.x.in, src/platform/haswell/platform.c, src/platform/icelake/icelake.x.in, src/platform/imx8/imx8.x.in, src/platform/imx8/platform.c, src/platform/imx8m/imx8m.x.in, src/platform/imx8m/platform.c, src/platform/intel/cavs/platform.c, src/platform/suecreek/suecreek.x.in, src/platform/tigerlake/tigerlake.x.in
=> probes: Add extended boot data regarding probes support.

src/audio/volume/volume.c, src/include/sof/audio/component.h
When some function has doxygen description then each argument should
have short description. In anothar situation, doxygen will generate
warning.
=> doxygen: Fill missed argument description in *params functions

tools/testbench/include/testbench/file.h
This patch fixes build fail of testbench. The packed attribute
is added similarly as in IPC structs of other components.
=> Testbench: Add packed attribute to file component IPC struct

src/schedule/ll_schedule.c
Fixes very rare race condition, where one of the cores
finishes its tasks much earlier and is cancelled right away.
num_clients is already set to zero, so there's no need
to subtract.
=> ll_schedule: fix very rare race condition

src/audio/asrc/asrc.c
This patch removes the unnecessary duplicated function call by mistake.
The proper request is done a few lines above the deleted line.
Fortunately this did not cause any issues.
=> ASRC: Remove duplicate timestamp request

src/debug/gdb/gdb.c
This patch adds spaces around arithmetic operators to make the code
easier to read and to silence checkpatch script.
Signed-off-by: Iulian Olaru <iulianolaru249@yahoo.com>
=> gdb: adds spaces around arithmetic operators

src/math/trig.c
This patch adds spaces around arithmetic operator to make code
easier to read and silence checkpatch script.
Signed-off-by: Iulian Olaru <iulianolaru249@yahoo.com>
=> Math/trig: Adds spaces around arithmetic operator

tools/topology/sof-cml-rt5682-kwd.m4
Pipeline PCM0P and PCM0C in sof-cml-rt5682-kwd.m4 is wrongly
configured.   we got a redundent 'SSP' in the pipeline configuration.
=> Topology: fix wrongly configured pipeline for sof-cml-rt5682-kwd.m4

tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4
This reverts commit b90f4dd044a2fef81057414df59e6f438005b88c.
The device id of rt715 and HDMI will be dynamic with this PR. This is
not friendly to UCM design. Let's deal with the id hole in machine
driver.
fixes https://github.com/thesofproject/sof/issues/2385  https://github.com/thesofproject/linux/issues/1788
=> Revert "topology: sof-icl-rt711-rt1308-rt715: refine dai index setting"

src/include/sof/schedule/task.h
Increases default stack size of EDF tasks.
It looks like some of the IPCs can exceed 2048 bytes of stack
and cause random data corruption. For sure it has been observed
when executing DAI config for DMIC.
=> task: increase default stack size

src/audio/asrc/asrc.c
This patch updates the stream sample rate propagation to happen
via source or sink buffer. The params struct can no more be used
for that. Without this change the DAI component reports xrun and
the stream fails.
Author: Tomasz Lauda <tomasz.lauda@linux.intel.com>
=> ASRC: Fix stream parameters passing in params()

test/cmocka/src/audio/kpb/CMakeLists.txt
This patch adds missing spinlock.c file to the build of
KPB component.
=> ut: add missing source file to build of KPB

tools/probes/CMakeLists.txt, tools/probes/probes_main.c, tools/probes/wave.h
This app will be used to parse probes data and extract wave files
Probes will extract data for several probe points in one stream with extra headers. This app will read the resulting file, strip the headers and create wave files for each extracted buffer.
Usage to parse data and create wave files: ./sof-probes -p data.bin
=> probe-app: initial implementation and description

src/audio/asrc/asrc.c, src/audio/buffer.c, src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/pipeline.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/tone.c, src/audio/volume/volume.c, src/include/sof/audio/component.h, src/include/sof/drivers/ipc.h, src/ipc/handler.c, src/ipc/ipc.c, test/cmocka/src/audio/mixer/mixer_test.c, test/cmocka/src/audio/pipeline/pipeline_connect_upstream.c, test/cmocka/src/audio/pipeline/pipeline_connection_mocks.c, test/cmocka/src/audio/pipeline/pipeline_free.c, tools/testbench/file.c
This set of patches brings some tiny improvements to the internal component api. Component implementation may interact with the common generic component data in a better controlled way.
Having the device/component data getters implemented, it will be now much easier to refactor the common data into a single structure comp_base { comp, comp_config } which seems important to avoid issues like the incomplete memcpy and tricky access to the comp_config by assuming that it should follow the comp with no explicit data defines by the implementors. Such a refactor will be proposed on top of those changes (as a separate PR) once they are accepted and merged.
There are some tiny cleanup patches included.
=> Internal component api improvements

src/audio/asrc/asrc.c, src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/switch.c, src/audio/tone.c, src/audio/volume/volume.c, src/include/sof/audio/component.h, test/cmocka/src/audio/kpb/kpb_buffer.c, test/cmocka/src/audio/mixer/comp_mock.c, test/cmocka/src/audio/mixer/mixer_test.c, tools/testbench/file.c
Back pointer must be initialized before any instance
level logging is performed by the new() operation since
the instance identification requires access to the uuid
that will be implemented on the component driver level.
=> Init component's back pointer to its driver early

src/drivers/Kconfig, src/drivers/imx/CMakeLists.txt, src/platform/Kconfig
Not all i.MX platforms have EDMA for DMA controller. So make it a
Kconfig option.
=> platform: imx: Add Kconfig option for i.MX EDMA driver

.gitignore
We don't need to accidentally commit cscope files. The linux kernel
ignores these definitions, let's ignore them too.
This commit was inspired from a similar commit adding ctags cache files.
Signed-off-by: Diana Cretu <diana.cretu@nxp.com>
=> Ignore cscope cache files

src/audio/host.c
src/audio/host.c: In function 'host_dma_cb':
src/audio/host.c:210:46: error: initialization of
'unsigned int' from 'const struct comp_driver *' makes integer from
pointer without a cast [-Werror=int-conversion]
comp_cl_dbg(&comp_host, "host_dma_cb() %p", &comp_host);
This happens because our tracing system is limited to integer types
for parameters.
Fixes: a87b9085058492 ("trace: component: use err,info,dbg macros")
Suggested-by: Paul Olaru <paul.olaru@nxp.com>
=> host: Fix compilation error with verbose traces enabled

src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c
This commit refines eq_fir/irr verify() functions:
1. eq_fir component is not able to change stream format,
so we should invoke comp_verify_function() with flag
equal to 0.
2. In eq_iir component we should check whether we can
support frame_fmt conversion due to source and sink
buffer frame_fmt's. If not, we should overwrite sink (playback)
and source (capture) with pcm frame_fmt and not make any
conversion (sink and source frame_fmt will be equal).
Fixes #2401
=> eq_fir/irr: refine eq_fir/iir verify() functions

tools/fuzzer/topology.c
This patch adds load of ASRC component to successfully build
the Fuzzer. The common topology parser with testbench depends
on load_asrc() function.
=> Fuzzer: Fix build fail for missing ASRC loader

src/CMakeLists.txt, src/audio/detect_test.c, src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/sue-ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/drivers/ipc.h, src/ipc/handler.c, src/ipc/ipc.c, src/platform/library/include/platform/platform.h, src/schedule/task.c
This patch guarantees detection notification message sending
by preallocating message structure and sending this particular
IPC instead of sending first message from the queue.
=> detect_test: guarantee sending detection notification to host

src/audio/dai.c, src/audio/pipeline.c, src/drivers/intel/baytrail/ssp.c, src/drivers/intel/cavs/alh.c, src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/hda.c, src/drivers/intel/cavs/ssp.c, src/drivers/intel/haswell/ssp.c, src/include/sof/audio/component.h, src/include/sof/lib/dai.h
Hardware stream parameters can be different for
PLAYBACK and CAPTURE direction. get_hw_params()
and dai_get_hw_params() function should return 
parameters correctly depending on the stream direction.
=> dai: add dir arg to get_hw_params function in dai_ops

.travis.yml, scripts/qemu-check.sh
Enable checks to i.MX8 platform of QEMU now.
Check both IPC header regs and memory window IPC message header.
Signed-off-by: Diana Cretu <diana.cretu@nxp.com>
=> scripts: qemu: Add qemu check for i.MX8 platform

src/platform/imx8m/lib/dai.c, tools/topology/CMakeLists.txt, tools/topology/sof-imx8mp-wm8960.m4
Topology part should be good enough for merge. I'm now hitting the issue mentioned by Fabio on Linux side where the DAI name is hardcoded. Will try to find a solution.
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-February/163776.html
=> Add topology for i.MX8MP with wm8960 codec

src/audio/asrc/asrc.c, src/audio/buffer.c, src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/pipeline.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/tone.c, src/audio/volume/volume.c, src/drivers/intel/cavs/idc.c, src/include/sof/audio/audio_stream.h, src/include/sof/audio/buffer.h, src/include/sof/audio/component.h, src/include/sof/drivers/idc.h, src/ipc/ipc.c, src/lib/dma.c, test/cmocka/src/audio/component/mock.c, test/cmocka/src/audio/mux/mock.c, test/cmocka/src/common_mocks.c
This set of patches adds possibility of executing single component on other core. Rest of the pipeline can run on different core.
=> component: add possibility of executing single components on other cores

tools/testbench/file.c
There was missing argument in file_get_hw_params, what breaks compilation.
=> testbench: Fix build error

rimage/file_simple.c, src/include/ipc/info.h, src/include/kernel/abi.h, src/include/sof/fw-ready-metadata.h, src/include/user/abi_dbg.h, src/ipc/CMakeLists.txt, src/ipc/user_abi_version.c, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/platform.c, tools/logger/convert.c
The sof-logger and potentially other debug API clients perform ABI
compatibility check using the single FW ABI version. The same one is used
by the primary FW client which is the kernel driver. If there is a change
made to the debug API, the main ABI has to be updated to protect integrity
of the debug tools while such a change may not affect the kernel driver
at all.
This patch introduces new debug ABI version to be increased when changing
user space debug interfaces while the the main ABI is not affected.
Recompilation and installation of the new driver every time the tunneled
debug protocol is upgraded may be avoided.
=> abi: define debug abi version for user space dbg interfaces

rimage/manifest.c
When some error occure during fopen routine, then errno should be
returned instead of success code.
=> rimage: Return error code when problem with file opening

src/drivers/intel/cavs/ssp.c, src/include/sof/drivers/ssp.h
This conversion in source code looks quite magic. It should be described
in header file where are registers bits description.
=> ssp: Move conversion from SSCR3 value to RFL to bit description section

src/include/ipc/info.h
ipc: Remove SOF_IPC_EXT_DMA_BUFFER
This enum code, and whats more important, related structures is
unused in whole source code, so it shouldn't be kept.
=> ipc: Remove SOF_IPC_EXT_DMA_BUFFER

src/drivers/intel/baytrail/ssp.c, src/drivers/intel/cavs/ssp.c, src/drivers/intel/haswell/ssp.c, src/include/sof/drivers/ssp.h
Introduce SSTSA_TXEN and SSRSA_RXEN macro to define bit value in
header file instead of usage raw value in source code.
Moreover use SET_BITS to set Rx/Tx slot value.
=> ssp: Use register name instead of bit value

src/audio/detect_test.c, src/audio/kpb.c, src/drivers/dw/dma.c, src/drivers/dw/gpio.c, src/drivers/dw/ssi-spi.c, src/include/sof/audio/src/src.h
Some obvious warnings should be fixed.
Additional ones were forwarded to the code owners.
cppcheck --platform=unix32 --force --max-configs=1024 --inconclusive --enable=all src -I src/include
=> Fix some cppcheck warnings

src/audio/mux/mux.c, test/cmocka/src/audio/mux/CMakeLists.txt, test/cmocka/src/audio/mux/mux_get_processing_function.c
This commit moves fetching mux/demux processing functions from
mux_prepare() to mux_set_values(). It insures us against
situation when we fetch proc_func in mux_prepare() and
after that comes mux_set_values() with new mux config.
=> mux: move fetching proc function from prepare() to set_values()

scripts/qemu-check.sh
Fix false positive return value for upsupported platforms.
Fix wrong parameter passed in when mutliple platform test.
=> scripts: fix issue in qemu-check.sh

.travis.yml, scripts/qemu-check.sh
imx8x is now supported in qemu up to boot. So, add
it to boottest list.
Signed-off-by: Diana Cretu <diana.cretu@nxp.com>
=> CI: travis: Add boot test for i.MX8X

src/include/sof/bit.h
In such a solution it is possible to assign BIT(31) to
uint32_t register value without any warning.
=> bit: Upgrade BIT macro to use 1UL instead of 1

src/audio/dai.c
Overwrite ```frame_fmt``` hardware parameters with ```DAI``` private ```frame_fmt```
in ```dai_comp_get_hw_params()``` function as ```DAI``` component is able to
convert stream with different frame_fmt's.
e.g.
In following topology:
DAI (DMIC, 32 bit) --> IIR ---> host (16 bit)
We have two components that potentially can make ```frame_fmt``` conversion - 
```DAI``` and ```EQ_IIR```. With above patch we can choose which component will
make this conversion. If we create ```DAI``` component with ```frame_fmt``` equal
to ```SOF_IPC_FRAME_S32_LE``` in ```struct sof_ipc_comp_config```, conversion will
happen on ```IIR``` component, otherwise if we create ```DAI``` component with 
```SOF_IPC_FRAME_S16_LE``` format, conversion will happen on DAI.
Signed-off-by: Bartosz Kokoszko …
=> dai: overwrite hardware frame_fmt parameter with private frame_fmt

src/audio/src/src.c, src/include/sof/audio/component.h
This commit removes unused ```output_rate``` field from
```comp_dev struct```. If needed, component can retrieve rate
parameters from sink/source buffers.
=> comp: remove output_rate field from comp_dev struct

src/include/ipc/dai-imx.h, src/include/ipc/dai-intel.h
We don't use this field, move back to reserved.
=> ipc: dai: remove unused hdr field in params

src/audio/dai.c, src/audio/src/src.c, src/include/sof/audio/audio_stream.h, src/include/sof/audio/format.h
This pull request contains cleanup for SRC component and avoiding local variables shadowing of function in ASRC by renaming better the functions in format.h header. Due to function rename DAI component is edited. The functionality of components is not changed.
=> Fixes for local variables usage in SRC and ASRC components

CMakeLists.txt, scripts/cmake/xtensa-toolchain.cmake, scripts/scan/clang-scan-build-xtensa.sh, scripts/scan/proxy-gcc.sh, src/arch/xtensa/CMakeLists.txt, src/debug/panic.c, src/include/sof/debug/panic.h
Support for running clang's static analyzer for fw build.
I'm probably going to add also checks for rimage and UTs.
After clang's analyzer we may add also few more checkers like ccpcheck or clang-tidy, but I'd prefer to have at least this one CodeChecker in CI up and running and then we may look for more.
=> scan: clang static analyzer

tools/topology/platform/intel/cml-mono.m4, tools/topology/platform/intel/cml.m4, tools/topology/platform/intel/icl.m4, tools/topology/platform/intel/whl.m4, tools/topology/sof-cml-demux-rt5682.m4, tools/topology/sof-cml-rt5682-kwd.m4, tools/topology/sof-cml-rt5682.m4, tools/topology/sof-cml-rt700.m4, tools/topology/sof-cml-src-rt5682.m4, tools/topology/sof-cnl-rt274.m4, tools/topology/sof-icl-dmic-4ch.m4, tools/topology/sof-icl-rt700.m4, tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4, tools/topology/sof-icl-rt711-rt1308-rt715.m4
All platform specific changes are moved to new file, platform/intel/all.m4.
Got a review comment from https://github.com/thesofproject/sof/pull/2444
Compared all conf and tplg files before and after this change.
=> topology: clean up platform specific macro

src/include/ipc/channel_map.h, src/include/sof/audio/channel_map.h, src/include/sof/audio/component.h, src/include/sof/common.h, src/include/sof/compiler_attributes.h, src/include/sof/trace/trace.h, src/ipc/cc_version.c, src/ipc/probe_support.c, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/include/cavs/lib/memory.h, src/platform/intel/cavs/platform.c
Using such a macro is preferred way to define target section
location in used checkpatch version.
=> sof: Add __section macro

src/ipc/ipc-host-ptable.c
Add error trace with buffer size for heap to help debug
the page descriptor issue.
=> ipc: add error trace with size for page descriptors alloc

src/audio/Kconfig
Enables HiFi3 version of PCM converter.
=> [WIP] pcm_converter: enable HiFi3 version by default

src/include/sof/lib/dma.h
Time unit is crucial to properly use this field so it is convenient
to have it written in comment near field declaration.
=> dma: Add time unit in comment in dma_chan_data.period description

src/audio/buffer.c, src/audio/component.c, src/audio/dai.c, src/audio/host.c, src/audio/mixer.c, src/audio/pipeline.c, src/audio/volume/volume.c
Specific component tracepoints are useful for topology bringup phase but later there are just errors interesting, therefore the tracepoints are moved to dbg level while their parent pipeline event traces (when important properties are logged) seems sufficient to observe the ongoing activities. Component 'new' is logged on the infrastructure level using component uuids.
=> Move component tracepoints to dbg level

src/audio/pcm_converter/pcm_converter_hifi3.c
HiFi3 version of PCM converter can corrupt data or go into
endless loop, when called with samples = 0. Make sure
the processing functions return immediately if that happens.
=> pcm_converter: do nothing when there are no samples

src/drivers/intel/cavs/dmic.c
Clears overrun bits in case they're asserted.
=> dmic: clear overrun bits

src/drivers/imx/interrupt.c, src/platform/imx8/include/platform/drivers/interrupt.h, src/platform/imx8m/include/platform/drivers/interrupt.h
On the i.MX8M platform the register map for the IRQ_STEER driver has significant differences from i.MX8/i.MX8X platforms.
This commit separates the register maps into a separate header file for each of the platforms.
=> IRQ_STEER portability fixes

src/platform/apollolake/include/platform/lib/shim.h, src/platform/cannonlake/include/platform/lib/shim.h, src/platform/icelake/include/platform/lib/shim.h, src/platform/tigerlake/include/platform/lib/shim.h
The BIT() macro is used to replace explicit bit shifting in
Apollolake, Cannonlake, Icelake and Tigerlake shim headers.
The headers are slightly modified to include the same registers
/bit definitions (if HW permits).
Signed-off-by: Lech Betlej <lech.betlej@linux.intel.com>
=> cavs: clean up of bit setting macros in shim headers

src/audio/pcm_converter/pcm_converter_hifi3.c
Fixes loops condition in most of the PCM conversion functions.
Number of samples is unsigned, so current condition caused underflow.
Fixes #2491, #2493.
=> pcm_converter: fix loops condition

src/drivers/imx/esai.c, src/drivers/imx/sai.c
Add proper implementation for [e]sai_get_hw_params. This function is
required for all DAI drivers and lacks even assert checks.
Without this implementation we would have a jump to address 0, which
manifested itself as a hang on i.MX8MP (did not test the other platforms
but they are all broken).
Fixes: 55866f28 "comp: dai: implement dai_get_hw_params() function"
=> drivers: imx: sai: esai: Implement get_hw_params

src/audio/asrc/asrc.c, src/audio/buffer.c, src/audio/component.c, src/audio/dai.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/pipeline.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/tone.c, src/audio/volume/volume.c, src/include/sof/audio/buffer.h, src/include/sof/drivers/idc.h
Fixes buffer_lock function. We need to pass flags by pointer
to use it correctly later to restore correct interrupt level.
=> buffer: fix locking

src/include/sof/lib/uuid.h
Data that go to static uuids section should use __section
macro.
=> uuid: use __section macro

src/audio/component.c, src/include/sof/audio/component.h
Removed the diagram duplicated in sof-docs, moved set_state
notes from sof-docs to the header to make it easier accesible
for component developers and added notes for infrastructure
developers to remember about the sof-docs updates.
=> comp: update api documentation for component state

src/include/sof/lib/uuid.h
More detailed uuid documentation should be useful for
component developers and others working on named fw
objects (like tasks).
Another patch to sof-docs that refers this API section
and provides detailed description on UUID use in component
overview section.
=> uuid: doc: add more documentation for macros

src/platform/baytrail/include/platform/lib/mailbox.h, src/platform/haswell/include/platform/lib/mailbox.h, src/platform/imx8/include/platform/lib/mailbox.h, src/platform/imx8m/include/platform/lib/mailbox.h, src/platform/intel/cavs/include/cavs/lib/mailbox.h, src/platform/library/include/platform/lib/mailbox.h
Adds missing header needed for size_t.
=> mailbox: add missing header

tools/CMakeLists.txt
this will allow to build probe app from scripts/build-tools.sh
=> probes-app: build the app with sof tools

src/debug/gdb/ringbuffer.c
Changes ring buffer to use mailbox_get_debug_base() macro.
It points to the same memory region as previously, but it's
defined for all platforms.
Fixes #2248.
=> gdb: use mailbox_get_debug_base() macro

tools/topology/sof-byt-codec.m4, tools/topology/sof/pipe-pcm-media.m4
This patch removes support for over 48 kHz sample rates and changes
scheduling to every 1 ms to save in buffers sizes. In pipe-pcm-media.m4
the buffers in the pipeline are reduced by one period from 4 to 3.
These changes should allow the media PCM to work in BYT platform.
=> Topology: BYT: Adjust SRC pipeline for lower RAM consumption

src/include/sof/drivers/ipc.h
Msg size should use its own structure's size.
Only payload should be allocated using passed one.
=> ipc: allocate correct msg size

src/audio/kpb.c, src/audio/pipeline.c, src/audio/volume/volume.c, src/drivers/dw/ssi-spi.c, src/drivers/imx/ipc.c, src/drivers/intel/baytrail/ipc.c, src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/idc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/cavs/sue-ipc.c, src/drivers/intel/haswell/ipc.c, src/include/sof/schedule/edf_schedule.h, src/include/sof/schedule/ll_schedule.h, src/include/sof/schedule/schedule.h, src/include/sof/schedule/task.h, src/lib/agent.c, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, src/schedule/schedule.c, src/schedule/task.c, src/trace/dma-trace.c, test/cmocka/src/audio/kpb/kpb_mock.c, test/cmocka/src/audio/pipeline/pipeline_mocks.c, tools/testbench/edf_schedule.c, tools/testbench/ll_schedule.c, tools/testbench/schedule.c
Defining tasks as named objects makes tracing of their important activities much easier.
See screenshot below
=> Introduce task uuids

src/audio/component.c, src/audio/dai.c, src/audio/host.c, src/audio/kpb.c, src/audio/pipeline.c, src/drivers/imx/timer.c, src/drivers/intel/baytrail/timer.c, src/drivers/intel/cavs/idc.c, src/drivers/intel/cavs/timer.c, src/drivers/intel/haswell/timer.c, src/include/sof/audio/component.h, src/include/sof/audio/component_ext.h, src/ipc/handler.c, src/ipc/ipc.c, src/schedule/task.c, test/cmocka/src/audio/mux/demux_copy.c, test/cmocka/src/audio/mux/mux_copy.c, test/cmocka/src/audio/mux/mux_get_processing_function.c, tools/testbench/include/testbench/common_test.h
The current content of component.h is a mix of basic api, common
basic helpers for every component developers as well as advanced
functions and macros used by infrastructure and very specialized
components like host, dai, kpb etc.
This patch moves the advanced part to component_ext.h and keeps
only basic part in component.h to avoid overloading effects
component developers with declarations and code they do not use.
=> comp: api: advanced and internal functions separated

tools/topology/m4/dai.m4, tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4, tools/topology/sof/pipe-dai-endpoint.m4, tools/topology/sof/pipe-dai-sched-playback.m4
The PR is to implement a topology for synchronize playback. We use demux to duplicate audio data for two DAIs.
=> [RFC] Topology for synchronize playback

src/probe/probe.c
This will fix probe deinit and free all used memory
=> probe: free extraction task in deinit and properly clear probe ptr

src/include/sof/spinlock.h, src/include/sof/trace/trace.h, src/trace/trace.c
Moves trace struct definition out of header.
It isn't used anywhere besides trace unit.
Fixes #2334.
=> trace: move struct definition out of header

src/arch/xtensa/schedule/task.c, src/include/sof/schedule/task.h, src/platform/baytrail/include/platform/lib/memory.h, src/platform/haswell/include/platform/lib/memory.h, src/platform/imx8/include/platform/lib/memory.h, src/platform/imx8m/include/platform/lib/memory.h, src/platform/intel/cavs/include/cavs/lib/memory.h
Reduces default EDF task's stack size for some platforms,
which have less memory and aren't used for more serious
processing.
Fixes #2532.
=> task: reduce default stack size for some platforms

src/audio/pipeline.c, src/include/sof/audio/pipeline.h, src/include/sof/sof.h, src/platform/apollolake/include/platform/lib/memory.h, src/schedule/task.c
Implements proper position offset retrieval in order to
update current stream position in mailbox. Previous one
was using pipeline_id in calculations, which has been
failing for bigger values. Lack of error handling has
also been a problem. This new solution uses predefined
list of available offsets and picks the first free from
the list. This way it will fail only if we exceed the
maximum number of simultaneously supported offsets.
Fixes #2546.
=> pipeline: implement proper position offset retrieval

src/ipc/ipc.c
=> ipc: buffer: Fix incorrect memory management in ipc_buffer_new()

src/audio/selector/selector.c, src/audio/volume/volume.c, src/include/sof/audio/selector.h, src/include/sof/audio/volume.h, test/cmocka/src/audio/selector/CMakeLists.txt, test/cmocka/src/audio/volume/CMakeLists.txt
We don't support section .shared in unit tests,
so add appropriate flags to make files.
=> cmocka: fix ut building

test/cmocka/src/audio/pipeline/pipeline_free.c, test/cmocka/src/audio/pipeline/pipeline_new.c
Initialize global objects that are required by pipelines
logic - pipeline_posn.
=> test: fix pipeline tests

src/ipc/ipc.c
Our guidelines encourage pasting whole quoted string of trace messages
in one line, rather than splitting it across multiple lines, when it
exceeds the regular 80 chars per line limit.
=> formatting: Reformat trace messages in src/ipc/ipc.c.

src/audio/pipeline.c, src/include/sof/audio/pipeline.h
Like other SHARED_DATA objects, this one should have limited visibility
just to pipeline compilation unit.
=> pipeline: move pipeline_posn shared data

src/audio/mux/mux.c
Currently, after pipeline params propagation, mux/demux processing
function might not be properly set up, if current params mismatch
ones assigned with binary blob during instantiation.
Similar assignment was there originally, but was lost to the history.
Should resolve https://github.com/thesofproject/sof/issues/2533 and https://github.com/thesofproject/sof/issues/2529
=> muxdemux: Properly assign processing function during mux_prepare() call.

tools/logger/convert.c
Error during conversion should be logged to stderr and to
output file by default. Such a approach will speed up debugging
process when some error with conversion occurred in CI.
=> tools: logger: Create log_err function

src/drivers/intel/cavs/dmic.c, src/drivers/intel/cavs/hda.c, src/drivers/intel/cavs/ssp.c
This patch removes the spin_lock() and spin_unlock() calls
from DMIC, HDA, and SSP driver code. The removal avoids a pipeline
stall issue that has been seen to happen in ASRC capture pipelines.
=> DAI: Remove spinlocks for timestamping registers access

src/audio/dai.c
Another type of pop noise.
The pop noise is generated by invalid data in dma buffer.
Since all buffers are cleared by pipeline_comp_prepare except
dma buffer, so clear it to zero to avoid this issue.
=> [RFC] dai: dma_buffer: fix pop noise issue when start playback

test/cmocka/CMakeLists.txt
Add "UPDATE_DISCONNECTED True" property in ExternalProject_Add() so:
- Unit tests can be rebuilt without a network connection
- The code can't change from one build to the next without the developer
being aware.
Found by chance thanks to some network issue.
=> cmocka/cmake: don't re-fetch (and change) cmocka.git on every build

test/cmocka/src/audio/kpb/kpb_buffer.c
As reported by gcc.
Fixes: 0b279e06bc1d. This is a partial, one-line revert of that commit
that decreased the size of this array for no obvious reason.
=> test/kpb: fix tests[1] array out of bounds

src/ipc/handler.c, src/probe/probe.c
Status (error) code in custom Probe responses is now reported properly.
Size of flexible arrays in Probe INFO responses is now reposted properly.
=> probe: Properly report response code and size of arrays in INFO payloads

src/audio/CMakeLists.txt, tools/fuzzer/topology.c, tools/test/audio/asrc_run.sh, tools/test/audio/comp_run.sh, tools/test/audio/eqfir_run.sh, tools/test/audio/eqiir_run.sh, tools/test/audio/volume_run.sh, tools/testbench/file.c, tools/testbench/include/testbench/common_test.h, tools/testbench/testbench.c, tools/testbench/topology.c, tools/topology/sof/pipe-eq-fir-capture.m4, tools/topology/sof/pipe-eq-iir-capture.m4, tools/tplg_parser/CMakeLists.txt, tools/tplg_parser/include/tplg_parser/topology.h, tools/tplg_parser/tplg_parser.c
Here's a cleaned up and more complete version of testbench PR. It consists of these commits:
- Testbench: Add processing component load
- Testbench: Fix possible uninitialized use of variable ret
- Testbench: Build topology parser with debug symbols
- Tools: Test: Cleanup component run scripts
- Topology: Fix in EQ only pipelines with macro PIPELINE_SINK
=> Testbench add process components support

scripts/xtensa-build-all.sh
Disable verbose build by default in build script.
It would be too annoying if we do not need to debug
with make systems.
Use -v option to enable verbose log if need.
This will also reduce CI logs to make us more easy to track down issues.
=> scripts: make verbose build into an option

scripts/qemu-check.sh
Enable checks to i.MX8M platform of QEMU now.
Signed-off-by: Diana Cretu <dianacretu2806@gmail.com>
=> scripts: qemu: Add qemu check for i.MX8M platform

src/drivers/imx/CMakeLists.txt, src/drivers/imx/sdma.c, src/include/sof/drivers/sdma.h, src/platform/imx8m/include/platform/lib/dma.h, src/platform/imx8m/lib/dma.c, src/platform/imx8m/platform.c
This patch set introduces the i.MX SDMA driver and enables it on the i.MX8M platform, where it is used.
The driver is mostly clean and complete however there is one issue that has to be accounted for and I'm asking for advice: The hardware reserves channel 0 for management activities and this channel _cannot_ be used for anything else. Should I tell SOF that there are 32 channels but one is occupied? Should I tell that there are only 31? If the latter, should I also shift the channel numbers so the index 0 is actually channel 1 on hardware?
=> drivers: imx8m: SDMA

src/probe/probe.c
Heap zone was used by mistake instead of flags
=> probe: fix dma buffer init wrong rballoc flags

src/drivers/intel/cavs/timer.c
Increases value of next timer set in case there is
a delay in tasks execution. Value of 1 is too small
to guarantee that the next interrupt will be triggered.
=> timer: increase next timer set in case of delay

.travis.yml
i.MX8M is now supported in qemu up to boot. So, add it to boottest list.
=> Boot test for i.MX8M

tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4, tools/topology/sof-icl-rt711-rt1308-rt715.m4, tools/topology/sof/pipe-highpass-switch-capture.m4, tools/topology/sof/pipe-volume-switch-capture.m4
This patchset add the DMIC and headset MIC LED support on sof-icl-rt711-rt1308-rt715.
=> DMIC and headset MIC LED support on sof-icl-rt711-rt1308-rt715

src/drivers/intel/cavs/dmic.c
Avoid useless parentheses to the right hand side of an assignment.
Change suggested by coccinelle.
Signed-off-by: Payal Kshirsagar <payalskshirsagar1234@gmail.com>
=> DMIC: remove parentheses around the right hand side of assignments

tools/logger/convert.c
When out_fd points standard output then error message shouldn't be
duplicated - duplicated messages only make logger output more messy.
=> tools: logger: Skip double error logs to stdout

tools/topology/sof/pipe-volume-demux-playback.m4
So the volume control will apply to both pipelines.
=> topology: pipe-volume-demux-playback: Move demux after volume

src/lib/alloc.c
Match alignment with open parenthesis to
maitain the coding style.
=> alloc: Match alignment with open parenthesis

scripts/checkpatch.pl
Adjust top_of_kernel_tree() function to SOF so invoking
./scripts/checkpatch.pl works out of the box and doesn't require
figuring what's going on and the existence of the --no-tree option which
sof-ci invokes "behind the scenes".
Compared to --no-tree, this is also enables a couple extra checks like:
`WARNING: use relative pathname instead of absolute in changelog text`
This instead of failing with:
Must be run from the top-level dir. of a kernel tree
PS: the space between check and patch is here to... defeat checkpatch
itself. It apparently doesn't expect any change to itself.
=> check patch: "top_of_sof_tree()" so it works out of the box

tools/topology/sof-apl-demux-pcm512x.m4
The HDMI DAI id changed, update the demux topology.
=> topology: fix apl-demux-pcm512x HDMI dai id

src/drivers/intel/cavs/dmic.c, src/include/sof/math/numbers.h
This pull request fixes a minor issue of very slightly above 0 dB decimation gain. It's not really measurable but it's good to fix it to be pedantic.
Thanks to payalskshirsagar1234@gmail.com for finding the suspicious line with too many brackets without purpose!
=> DMIC: Fix FIR scaling issue

tools/testbench/ll_schedule.c
Remove unneeded temporary local variable, its declaration and newlines.
Signed-off-by: Payal Kshirsagar <payalskshirsagar1234@gmail.com>
=> testbench: remove unneeded variable

src/audio/dai.c, src/drivers/dw/dma.c, src/drivers/intel/cavs/hda-dma.c
Suspend flag should be set regardless of draining mode to stop
draining data from source buffer.
=> dw_dma: Suspend DMA channel in stop function

src/CMakeLists.txt
Cmake files should have consistent directory linkage scheme
where lines duplication should be avoided.
=> cmake: Do not duplicate subdirectory adding for library build

tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4
We only need demux for two speaker dais case.
Fixes: 5e8de9f "topology: sof-icl-rt711-rt1308-rt715-hdmi: Merge two pipeline with demux"
Fixes #2570
=> Topology: sof-icl-rt711-rt1308-rt715-hdmi: Use demux for platforms with multiple speakers

tools/logger/convert.c, tools/logger/convert.h, tools/logger/logger.c
Create dump options for logger to print important information from
LDC file, like DBG_ABI version and UUID with corresponding names.
Output:
```
$./sof-logger -i log/dma_trace_1.bin -l log/sof-cnl.ldc -d
logger ABI Version is   4:2:0
ldc_file ABI Version is 4:2:0
Components uuid dictionary size:        824 bytes
Components uuid base address:           0x1FFFA000
Components uuid entries:
ADDRESS                                    UUID NAME
0x1FFFA000  <8b9d100c-6d78-418f-90a3-e0e805d0852b> host
0x1FFFA01C  <f11818eb-e92e-4082-82a3-dc54c604ebb3> pipe-task
0x1FFFA03C  <34dc0385-fc2f-4f7f-82d2-6cee444533e0> volume-task
0x1FFFA05C  <b77e677e-5ff4-4188-af14-fba8bdbf8682> volume
0x1FFFA078  <c1c5326d-8390-46b4-aa47-95c3beca6550> …
```
=> tools: logger: Add LDC dump option

src/drivers/intel/baytrail/ssp.c, src/platform/intel/cavs/lib/pm_memory.c
Remove unnecessary parentheses around the right hand side of assignments.
=> remove unnecessary parentheses

tools/test/audio/asrc_run.sh, tools/test/audio/comp_run.sh, tools/test/audio/eqfir_run.sh, tools/test/audio/eqiir_run.sh, tools/test/audio/src_run.sh, tools/test/audio/volume_run.sh
This patch adds the double quotes to shell scripts to avoid fails
with arguments or shell variables when there are space characters.
=> Tools: Test: Audio: Add double quotes to shell scripts

src/arch/xtensa/lib/cpu.c, src/audio/pipeline.c, src/include/sof/lib/alloc.h, src/include/sof/lib/mm_heap.h, src/init/init.c, src/lib/alloc.c, src/platform/baytrail/lib/memory.c, src/platform/baytrail/platform.c, src/platform/haswell/lib/memory.c, src/platform/haswell/platform.c, src/platform/imx8/lib/memory.c, src/platform/imx8/platform.c, src/platform/imx8m/lib/memory.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/lib/memory.c, src/platform/intel/cavs/platform.c, test/cmocka/src/audio/pipeline/pipeline_mocks.c, test/cmocka/src/common_mocks.c, test/cmocka/src/lib/alloc/alloc.c, tools/testbench/alloc.c
All clients that just wants to allocate and free memory does not need to know all the heap management API and internals. Again, physical separation seems better than trying to annotate the header with documentation groups etc.
Duplicated heap debug code was removed from the header. Internal trace definitions moved from the header as well.
Now the alloc.h contains just the "alloc" API, a good starting point for dox-ing and linking to sof-docs for application developers.
=> mm: clean alloc api up

scripts/xtensa-build-all.sh
CMAKE_VERBOSE_MAKE was sometimes "hardcoding" the decision in CMake's
cache. Move that decision to the make invocation.
After running xtensa-build-all.sh [-v], it's now possible to choose
again whether "make -C build_apl_gcc/" should be VERBOSE or not without
starting from scratch and with the exact same configuration.
Before this commit it was possible for make to decide again after a
non-verbose xtensa-build-all.sh but not possible to decide again after a
verbose xtensa-build-all.sh... very confusing.
=> scripts: build-all: postpone VERBOSE decision to "make" time

src/math/numbers.c, test/cmocka/src/math/numbers/gcd.c
This patch replaces the former gcd algorithm which was implemented with
repetitive divisions with Stein's algorithm, whitch is a faster gcd
algorithm. All operations are arithmetic shifts, comparisons and
subtractions.
Signed-off-by: Iulian Olaru <iulianolaru249@yahoo.com>
=> Math: replaces the gcd algorithm

src/drivers/intel/baytrail/interrupt.c
Change suggested by coccinelle.
Replace bit shifting on 1 with the BIT(x) macro.
Signed-off-by: Payal Kshirsagar <payalskshirsagar1234@gmail.com>
=> src: drivers: intel: baytrail: replace bit shifting with BIT macro

scripts/xtensa-build-all.sh
Example:
```
$ ./scripts/xtensa-build-all.sh -j3
./scripts/xtensa-build-all.sh: WARN: ignoring arg -j3
```
=> scripts: build-all: warn when ignoring unknown arguments

tools/tplg_parser/tplg_parser.c
Fixes:
```
tplg_parser.c: In function ‘tplg_load_graph’:
tplg_parser.c:979:2: error: ‘sink’ may be used uninitialized
in this function [-Werror=maybe-uninitialized]
979 |  printf("loading route %s -> %s\n", source, sink);
|  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> tplg_parser: fix -Werror=maybe-uninitialized source, sink

src/include/sof/debug/panic.h, tools/testbench/panic.c
Commit 9e1a2b251a3e9d added ((analyzer_noreturn)) but only for clang.
Fixes at least these two -Werr build failures and probably similar
others with a different .config or in the future:
```
sof/src/probe/probe.c: In function 'probe_cb_produce':
sof/src/probe/probe.c:635:11: error: 'valid_bytes' and
'container_bytes' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
```
Build failure reproduced with xtensa-apl-elf-gcc (crosstool-NG
1.23.0.440-3b8c) 7.3.0
=> panic: add __attribute__((noreturn)) #if __GNUC__

tools/testbench/common_test.c, tools/testbench/topology.c
This patch fixes the crash by adding initialize of sof->pipeline_posn
into pipeline initialization code.
Also the in load_pipeline() function the pipeline is initialized
to zeros to prevent random values to be passed in not set
struct fields. It didn't fix anything but makes debugging of crash
easier.
=> Testbench: Fix segfault in pipeline_new() in topology parsing

src/include/sof/audio/component.h, src/include/sof/lib/alloc.h, src/lib/alloc.c, test/cmocka/src/audio/component/mock.c, test/cmocka/src/common_mocks.c, tools/testbench/alloc.c
This is the documentation of alloc.h, including a small final cleanup of the header (transparent to client code) in the first patch.
=> Document alloc.h

src/drivers/imx/sdma.c
Two fixes allowing us to progress on enabling SDMA.
First propagates some config fields to channel.\
Second enhances the state machine taking into consideration that channel 0 is special.
=> Imx8m fixes

src/audio/dcblock/dcblock.c
This patch fixes an issue with address-of-packed-member warning. The warning was introduced in GCC-9, and was not raised by previous compiler versions.
this it the issue shown by the compiler:
```
error: taking address of packed member of ‘struct sof_abi_hdr’ may
result in an unaligned pointer value [-Werror=address-of-packed-member]
225 |   request = (int32_t *)cdata->data->data;
|                        ^~~~~
```
Signed-off-by: Sebastiano Carlucci <scarlucci@google.com>
=> sof: dcblock: Fix unaligned pointer value issue

src/audio/asrc/asrc.c, src/audio/src/src.c
This can happen with HDA and ALH and avoids a firmware crash.
=> ASRC: SRC: Fail params() when DAI does not provide sink stream format information

CODEOWNERS
Add Google owners as owners of imported code
Signed-off-by: Curtis Malainey <curtis@malainey.com>
=> Add CODEOWNERS for DCBlocker

test/cmocka/src/audio/mixer/mixer_test.c
Fixes:
```
error: 'err' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
if (err)
^
```
As I found nothing in the entire code base checking the return value of
comp_register() (the real function seems to always succeed), I also
simplify the main path and pass through the value returned by
memcpy_s().
=> test: fix mixer_test.c:comp_register() 'uninitialized err' -Werror

tools/topology/CMakeLists.txt
Successfully tested with both Make and Ninja on Linux.
Non-portable but approved by @jajanusz in former PR #2626
With this commit:
```
$                  make -C tools/build_tools/ | wc -l
770
$ VERBOSE=anything make -C tools/build_tools/ | wc -l
10387
```
=> topology: cmake: silence super chatty alsatplg unless VERBOSE=1

src/audio/kpb.c, src/drivers/intel/cavs/hda-dma.c, test/cmocka/src/math/numbers/find_max_abs_int32.c, test/cmocka/src/math/numbers/find_min_int16.c
1. Use ARRAY_SIZE:
ARRAY_SIZE macro in <sof/common.h> is better used when computing array size.
2. Remove unneeded ret variable:
Return immediately in case of having a ret variable that's always 0.
=> Clear small issues found by Coccinelle and Checkpatch.pl

scripts/gen-doc.sh
Use getopt to parse the arguments instead of manual parsing to leave no
room for errors, bugs, and inconsistent conventions introduced by custom
implementation.
=> gen-doc.sh: Use getopts for parsing arguments

src/lib/alloc.c
Simplify function returns by merging assignment and return into
one command line.
Signed-off-by: Simran Singhal <singhalsimran0@gmail.com>
=> alloc: Simplify function return logic

src/include/ipc/info.h, src/include/kernel/abi.h, src/ipc/cc_version.c
Fix ABI version to 3.15.0 on master first.
There is a bug in the Cadence XCC compiler that give us different
linkage section sizes for flex length struct sof_ipc_ext_data in
ELF file compared to GCC version. And there are appending struct
in the same ELF section, this will bring wrong offset for those
struct binary in ELF file.
Example:
When the CC_DESC is " RG-2017.8-linux", we should have struct
length for 0x50 in header size, but the binary length in ELF file
is 0x4c. When the CC_DESC is " RG-2017.8-win", size are both 0x4c
All existing compiler description has length less than
24 bytes. So use a fixed length 24 in this structure.
ABI version 3.16.0
fix https://github.com/thesofproject/sof/issues/2507
=> cc_version: use fixed length for CC_DESC

tools/topology/CMakeLists.txt, tools/topology/sof-glk-da7219.m4
glk da7119 bobba platform has DMIC already installed. It is good platform
to test DMIC with and without EQ.
With this PR, sof-glk-eq-da7219 tplg will be generated.
=> topology: glk: add eq capture for DMIC

scripts/build-tools.sh
Use getopts to parse the arguments instead of manual parsing to leave no
room for errors, bugs, and inconsistent conventions introduced by custom
implementation.
=> scripts: build-tools.sh: Use getopts, breakdown script to functions

src/include/sof/audio/audio_stream.h
This change is required before dereference is applied,
to make the macros callable with arguments that have address-of
operator, e.g.
&source->stream
=> audio-buffer: use parentheses around parameters in rw-frag macros

src/audio/mux/mux.c, src/audio/mux/mux_generic.c, src/include/sof/audio/mux.h, test/cmocka/src/audio/mux/demux_copy.c, test/cmocka/src/audio/mux/mux_copy.c, test/cmocka/src/audio/mux/mux_generic_calc_sample_s16le.c, test/cmocka/src/audio/mux/mux_generic_calc_sample_s24le.c, test/cmocka/src/audio/mux/mux_generic_calc_sample_s32le.c, test/cmocka/src/audio/mux/mux_get_processing_function.c
Remove legacy dependency on config parameters which are no longer necessary and/or can be determined at runtime.
Also obsolete fields in the external API were renamed to 'reserved'. These fields might be removed, although that would cause backward incompatibility.
@lgirdwood @plbossart If you find it beneficial to remove these fields altogether, please let me know, I'll add such change to this PR.
=> muxdemux: Optimize and cleanup mux/demux internal and external interface.

src/include/ipc/topology.h, src/include/kernel/abi.h
2 flags have been added for use during buffer instantiation:
SOF_BUF_OVERRUN_PERMITTED and SOF_BUF_UNDERRUN_PERMITTED,
along with struct sof_ipc_buffer member fields flags and reserved.
Flags field is supposed to hold the above-mentioned flags to allow
some control over XRUN behaviour, i.e. prevent XRUN on buffers which
are allowed to under/overrun by design.
Also added reserved field to the structure in case it comes in handy
some time in the future.
Relates to https://github.com/thesofproject/sof/issues/2478
=> topology: buffer: Add XRUN flags field to struct sof_ipc_buffer.

src/lib/agent.c
Non-critical drifts should be traced as warnings (WARN,
yellow color), not errors since the system is expected
to recover in this scenario.
=> agent: trace drift message as warning, not error

.travis.yml, scripts/host-testbench.sh, tools/test/audio/comp_run.sh
Update the host-testbench scripts to test 3 simple testbench
volume, src and eqiir.
Enable Travis CI test for the testbench with this script.
=> Enable test bench test in simple scripts and test in Travis CI

CODEOWNERS
... as reported by
https://github.com/zephyrproject-rtos/ci-tools/blob/cf55a47d52d/scripts/check_compliance.py
-m Codeowners
Thanks @jajanusz for the help.
For src/[include]/host, I tried some tig blame and git log to find
potential renames, but I gave up when I found that commits
e20217abc747 and f081a20de9e5 (for instance) added or moved some
patterns that already did not match anything at the time.
=> CODEOWNERS: updates patterns, remove src/[include]/host/

scripts/cmake/defconfigs.cmake
Add targets that are meant to be used after defconfig,
to apply configs from <arch>/configs/override on top of defconfigs.
Follow up to #2641
=> cmake: add *_overridedefconfig targets

src/drivers/intel/cavs/alh.c, src/include/ipc/dai-intel.h, src/include/sof/drivers/alh.h, src/include/sof/lib/dai.h
This allows the firmware to become aware of the programmed format on ALH DAIs.
The change is backwards compatible, in-case of ABI mismatch, the data will be filled with 0s,
which is consistent with previous values.
This change is required in the case of pipelines, that contain components capable
of modifying the parameters of a stream, for example (de)mux.
=> alh: obtain hw params from ipc config

src/include/sof/trace/trace.h
Introduce dummy trace functions for when CONFIG_TRACE
is not set to avoid undefined reference to function error.
src/ipc/handler.c.o: In function `ipc_glb_tplg_buffer_new':
src/ipc/handler.c:1094: undefined reference to `trace_on'
=> trace: Fix compilation error when CONFIG_TRACE not set

src/include/ipc/probe.h, tools/probes/probes_main.c
This reverts and replaces PR #2559 / commit 2765b2204962 ("probe-app: assume probe
packet aligned"). That commit applied a `__builtin_assume_aligned(4)` to
every pointer assignment of the following type:
```
uint32_t *ptr = struct probe_data_packet *packet;
```
Instead of using `__builtin_assume_aligned(4)` every time a
probe_data_packet is used like this, the probe_data_packet type
definition is now 32 bits aligned in only one place thanks to `(packed,
aligned(4))`.
struct probe_data_packet is made entirely of uint32_t members. It
is `(packed)` to avoid a 64 bits compiler hypothetically padding and
aligning these 32 bits members to 64 bits. However, (packed) alone is
roughly equivalent to `aligned(1)` ([neither is part of the C standard](https://groups.google.com/forum/#!msg/x86-64-abi/IT …
=> Revert __builtin_assume_aligned(4) probe packet, replace with aligned(4)

src/audio/dcblock/dcblock.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/volume/volume.c, src/include/sof/audio/component.h
Grouping the operations in a function simplifies the components code. It also
guarantees correct double lock with dedicated flags and helps avoid a common bug
in client code where single flags variable is used for both locks. When both
buffers are shared between cores, and single variable is used, the rsil in
second lock returns int level 5 set by the first lock. Later, during unlocking
the original level returned by the first lock is not restored, the dsp stays on
level 5.
Note: it might not be visible on a system which runs the pipeline_copy on level 5 (which is the case for current xtensa arch configuration in sof as ll-scheduler disables local ints by setting 5 into PS.INTLEVEL, so inner spin_lock_irq-s have no real effect).
=> Fix copy limits lock

src/include/sof/audio/kpb.h
As reported by PR #2741:
```
sof/src/include/sof/audio/kpb.h:46: warning: explicit link request to 'kpbm' could not be resolved
```
Fixes: 36d4c9f ("kpb: add new state")
=> kpb: fix broken doxygen link to kpbm-state-diagram

tools/test/topology/tplg-build.sh
With this commit:
```
./scripts/build-tools.sh -t -f | wc -l
525
VERBOSE=anything  ./scripts/build-tools.sh -t -f | wc -l
137030
```
This a followup to commit aa6c0f2ad11f ("topology: cmake: silence super
chatty alsatplg unless VERBOSE=1")
=> tools/test: silence alsatplg in tlpg-build.sh unless VERBOSE=1

src/audio/buffer.c, src/audio/component.c, src/include/sof/lib/alloc.h, src/lib/alloc.c, test/cmocka/src/audio/component/mock.c, test/cmocka/src/common_mocks.c, tools/testbench/alloc.c
Previous memcpy of bytes is unsafe if new object is larger
then old one (which is probably most popular realloc use).
Typically realloc retrieves the old size internally and does
not need this information passed as argument but sof heap
implementation does not store the exact size of the allocated
memory buffer.
=> alloc: fix potential oob in rrealloc, rbrealloc

.travis.yml
Before this new stage, doxygen was run only in a completely different
repo (sof-docs). So it was possible to submit totally broken doxygen
changes and get no doxygen feedback at all from CI before merge.
=> CI: travis: add doxygen stage

src/audio/pipeline.c, src/include/sof/audio/pipeline.h
Implements atomic scheduling of connected pipelines that
supposed to be triggered at the same time. If the trigger
is propagated to the connected pipelines, then the expectation
is that they should be started at the same system tick.
Otherwise it might potentially lead to losing some samples
at the beginning for one of the pipes.
Fixes #2736.
=> pipeline: atomic schedule of connected pipelines

src/audio/component.c, src/include/sof/list.h
Realloc seems very expensive if platforms offer simple, quick method.
Fixed scenario for buffer lists described in commit message.
=> Make comp_shared simpler and fix data re-initialization

src/include/sof/audio/dcblock/dcblock.h
This commit fixes a doxygen issue caused by a mismatch between
dcblock_find_func()'s declaration and its corresponding comment block.
Signed-off-by: Sebastiano Carlucci <scarlucci@google.com>
=> audio: dcblock: Fix doxygen error for dcblock.h

.travis.yml
Looking at any recent Travis build log:
1. more than half the time is spent in the exact same "docker pull"
command,
2. The qemuboottest stage rebuilds again the exact same thing than the
previous test stage.
Fix 1. by re-using the same docker instance for multiple platforms.
Fix 2. by dropping from the test stage builds performed again in
the qemuboottest stage.
Random sample before:
```
Total (VM) time  1 hr 15 min
Real time             25 min (depends on current Travis load)
```
After:
```
Total (VM) time       30 min
Real time             10 min (depends on current Travis load)
```
The price to pay for this matrix reduction and speed up is coarser
reports in case of failure. Considering these tests are the most basic
possible one expects them to be rarely ever broken.
Remove the …
=> CI: Travis: less VM isolation for speed-up. Remove matrix.

src/drivers/imx/interrupt.c, src/platform/imx8m/include/platform/drivers/interrupt.h
This is a couple of fixes after we got the correct documentation. Major modification is that on i.MX8MP
we have only 32 x 5 = 160 input irqs steered through 3 x 64 output interrupts. 
It seems to work fine, will keep it RFC for a while to allow @paulstelian97 to do some more testing.
=> irqsteer fixes for i.MX8MP

src/audio/dcblock/dcblock_generic.c
This patch fixes an integer overflow issue that can occur in the
dcblocker. The overflow happened when doing x - x_prev. If x_prev
was sufficiently large (positive or negative), it caused an overflow.
Casting x to a 64 bit int first fixes this issue.
Signed-off-by: Sebastiano Carlucci <scarlucci@google.com>
=> audio: dcblock: Fix int overflow issue in dcblocker

.travis.yml
See https://github.com/thesofproject/sof/issues/2752
host-testbench.sh exits with success 0 when tests fail. Random, recent, all
green example in PR #2751:
https://travis-ci.org/github/thesofproject/sof/jobs/672996210 is green but:
```
eqiir test failed!
```
I didn't even have to spend time to search for this example, I only
looked at the most recent PR.
Ignoring failures is the very worst type of validation issue because it
makes everyone think everything is OK when it's not. Hides regressions.
=> CI: Travis: disable host-testbench as long as it ignores errors

src/audio/asrc/asrc.c, src/audio/buffer.c, src/audio/dai.c, src/audio/src/src.c, src/audio/tone.c, src/include/sof/audio/audio_stream.h, src/include/sof/audio/component.h
This is follow-up to recently merged PR https://github.com/thesofproject/sof/pull/2580
underrun_permitted and overrun_permitted fields have been added to audio_stream structure and initialized during buffer instantiation.
audio_stream_get_<free/avail>_<bytes/samples/frames> functions have been added to audio stream interface, and all occurrences of old API usage have been replaced with the new one.
=> audio stream: Implement XRUN-permitted behaviour

src/include/sof/schedule/schedule.h, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, test/cmocka/src/audio/pipeline/pipeline_connection_mocks.h, tools/testbench/edf_schedule.c
Cleans up existing documentation and adds missing one.
=> schedule: dox: complete api documentation

src/audio/src/src.c, src/include/sof/debug/debug.h
@singalsu Please check one related to src, because maybe you missed something that's why there was left dead assignment.
=> clang: fix 2 issues reported by scan-build

src/include/sof/lib/alloc.h, src/lib/alloc.c, test/cmocka/src/audio/component/mock.c, tools/testbench/alloc.c
rrealloc function is no longer in use, so it is better
to remove it. Unused code is no longer tested so its
quality is unknown.
The current implementation is simple but expensive since
extra calls to malloc/free requires time and risky since
at some point requires double allocation of potentially
large object. Please consider re-implementation instead
of restoring.
=> alloc: remove unused rrealloc

.travis.yml
Travis stages are designed not to run after the first that fails. We
never used them for that, only for nicer presentation of
results. Running all tests independently of each other (e.g.: qemu and
doxygen) even when one fails is more important than presentation, so
reduce the number of stages to just two: "buildonly" and "tests"
Travis job `name:` doesn't look as good alone as when combined
with a stage name but it's enough to identify jobs.
Reducing to just one stage is tempting but it would require a lot more
naming surgery so let's start with this small diff and two stages for
now.
=> CI: Travis: reduce the number of stages to two

src/audio/eq_fir/eq_fir.c, src/audio/volume/volume.c, src/include/sof/audio/component.h, src/include/sof/audio/component_ext.h, test/cmocka/src/audio/pipeline/pipeline_mocks.c
Unification of activities performed in params vs. prepare in other components could be considered and reviewed/simplified to make sure their behavior is consistent, e.g.
- mixer's verification inside params is done in prepare in other components (params cannot be completely removed in this case since custom flags to comp_verify_params() is provided),
- mux probably does not need another inner function,
etc.
=> Call default comp_verify_params() from comp_params() if no handler defined in comp_ops

src/audio/tone.c
Remove extra blank lines before and after curly braces. Problem
reported by checkpatch script.
Signed-off-by: Deepak R Varma <mh12gx2825@gmail.com>
=> audio: remove extra blank lines

src/include/sof/common.h
This commit fixes the warning generated by clang-tidy due to
bugprone macro parentheses. It is recommended to surround macro
arguments in the replacement list with parentheses. This ensures
that the argument value is calculated properly.
Name of the warning generated: bugprone-macro-parentheses
=> include: common: surround macro argument with parantheses

src/audio/buffer.c, src/audio/component.c, src/audio/pipeline.c, src/include/sof/drivers/ipc.h, src/ipc/handler.c, src/ipc/ipc.c
They are useful while debugging the stack while target (pipeline, component, buffer) traces are sufficient to investigate sequences of events.
PR contains also a cleanup of incomplete ipc data copies to avoid false positive ABI incompatibility alarms.
=> Move low level trace messages to dbg level

tools/test/audio/dcblock_run.sh, tools/test/audio/process_test.m, tools/test/audio/src_test.m, tools/test/audio/test_utils/print_fr.m, tools/test/audio/test_utils/print_pf.m, tools/test/audio/test_utils/print_val.m, tools/tune/eq/eq_blob_plot.m, tools/tune/eq/eq_blob_read.m, tools/tune/eq/eq_fir_blob_decode.m, tools/tune/eq/eq_get_abi.m, tools/tune/eq/eq_iir_blob_decode.m
This patch adds Octave scripts for objective quality parameters checks for processing components. The standard tests include chirp spectrogram, gain, dynamic range, THD+N over frequency, and frequency response. 
There's still minor general issues/limitations (currently only test for flat response FIR/IIR, failure when testing volume), and need for more test topologies (will use @fredoh9  topology work). But since I feel this is generally useful for processing developers I'd like to share this early.
=> Tools: Add tests for processing components

src/include/sof/lib/dma.h
Name clash reported by sphinx/breathe:
sof-docs/api/dma-drivers-api.rst:6: WARNING: Duplicate declaration, dma_copy
Before this commit:
- all "dma_copy" links in doxygen pointed to the struct, never to the
function,
- there was no "dma_copy" link of any kind in sphinx.
With this commit:
- most "dma_copy" links in doxygen are disambiguited and fixed, see
html/dma_8h_source.html for instance,
- there are dma_copy links to the struct in sphinx.
Once this is a merged, a commit in sof-docs will add the new subgroup
and re-add the function to sof-docs/api/dma-drivers-api.rst
Fixes: fa8abe145c0d ("core: dma: Add DMA copy API.")
Reference:
http://www.doxygen.nl/manual/grouping.html
=> doxygen: subgroup dma_copy() to solve conflict with struct dma_copy {}

src/drivers/intel/cavs/alh.c, src/drivers/intel/cavs/hda.c, src/include/ipc/dai-intel.h, src/include/kernel/abi.h, src/include/sof/drivers/hda.h
This is an analogous change to what's been done for ALH DAIs.
Similarly, HDA is set up on the host side.
As a result, the firmware normally has no knowledge
of the hardware configuration, which leads to failures
in components, that may modify stream parameters, such as
(de)mux or asrc.
Kernel side PR: https://github.com/thesofproject/linux/pull/2007
=> hda: retrieve hda hardware params from ipc

tools/topology/sof-glk-da7219.m4
In order to allow record s16_le/s24_le/s32_le format this
commit changes DAI component's and DMIC's format to s32_le
on PCM99.
In case recording s16_le/s24_le DAI component makes pcm
conversion from s16_le/s24_le to s32_le.
fixes #2638 
=> apl: change dmic format to s32_le in sof-glk-da7219.tplg

src/include/sof/audio/component.h, src/include/sof/lib/perf_cnt.h, src/lib/agent.c, src/schedule/ll_schedule.c
Logger doesn't have possibility to dircetly send 64b arguments
to host, so this arguments should be explicit cast to shorten
data type.
Moreover after putting 64b value to va_arg list in function call
and reading it as 32b will lead to arguments misalignment with
formatting string.
=> logger: per_cnt: Explicit cast arguments to uint32_t

src/audio/component.c, src/include/sof/list.h
Fixes comp_make_shared function by flushing data from cache
before accessing it using shared interface. Also additional
invalidation is no longer needed. It should be handled
automatically by platform_shared_get.
=> component: fix comp_make_shared

src/include/sof/schedule/ll_schedule_domain.h, src/schedule/ll_schedule.c
This fixes a recently reported and discussed xrun on slave cores.
=> ll-schedule: fix scheduling start on slave cores

src/audio/asrc/asrc.c
This patch fixes a minor issue when handling the fail to allocate a
samples buffer. The goto err_free_buf jumps to code "rfree(cd->buf);"
that would attempt free null pointer that is confusing and just
overhead. Only the successive operations of comp_set_state() and
returning -ENOMEM are needed.
=> ASRC: Fix memory allocation fail handling in prepare()

src/ipc/cc_version.c
In old method, when input string is to long by one char, then
complation pass what doesn't happen in new method.
=> cc_version: Improve string length check

src/drivers/dw/dma.c
Bug was caused because sdw controller is stopped first,
then DSP is stopped, so DW FIFO will never be consumed,
so timeout occurs, and watch dog will reset hardware.
Moreover polling for FIFO emty in duch a place should have positive
result only when pause take shorten than 1ms what is not
reasonable value.
=> DMA: Fix fw panic after release on SdW platforms

tools/topology/sof-hda-generic.m4
in bxt.m4 and sof-hda-generic.m4, they both define the
PIPE_VOLUME_PLAYBACK, this will cause wrong tplg result.
Refine the them in sof-hda-generic.m4 to PIPE_HEADSET_PLAYBACK
to fix the issue.
Fix https://github.com/thesofproject/sof/issues/2810
=> topology: fix conflict PIPE_VOLUME_PLAYBACK defination

src/audio/kpb.c
Memory allocated for new KPB component should be released before
returning NULL in when one of sampling width or number of channels or
sampling frequency are set to unexpected values.
Signed-off-by: Deepak R Varma <mh12gx2825@gmail.com>
=> sof: audio: free memory before returning in error

.travis.yml, scripts/xtensa-build-all.sh
- Use getopts for simpler, robust argument parsing
- Exit if an unknown platform is specified
- Derive $ROOT from $HOST instead of explicit assignment
- Use switch case instead of if else for testing string
=> scripts: xtensa-build-all.sh: Refactor and improve script

src/ipc/handler.c, zephyr/CMakeLists.txt, zephyr/README, zephyr/wrapper.c
More updates to use Zephyr RTOS. Code now links and boots. SOF code is executed, but stops due to missing API implementations for bridging code.
=> Zephyr API bridge

src/audio/kpb.c
This patch fixes the race condition in the draining
task in which KPB was waiting for sink component to
free space in its input buffer while this component
was waiting for KPB to call its .copy() method
again. This problem has deeper underlying cause,
namely the lack of DMA IRQ which should signal the
end of transaction.
=> kpb: fix race condition in draining task

src/platform/apollolake/include/platform/lib/memory.h, src/platform/cannonlake/include/platform/lib/memory.h, src/platform/icelake/include/platform/lib/memory.h, src/platform/suecreek/include/platform/lib/memory.h, src/platform/tigerlake/include/platform/lib/memory.h
This patch enables a single 1 - 2 kB allocation for component
runtime. The disabled 2 kB pool entry caused ASRC component
to fail in some cases.
=> Memory: Enable 2 kB module pool for APL, CNL, ICL, TGL, Sue Creek

src/audio/pipeline.c, src/include/sof/lib/agent.h, src/lib/agent.c
Disables panic emitted by system agent on timer delay, when there
are DMA driven pipelines scheduled on the DSP. With such pipelines
running, timer interrupts can be delayed pretty often, so just
emit warning instead of full panic.
Fixes #2696.
=> pipeline: disable system agent panic for DMA driven pipelines

src/drivers/imx/sdma.c
This is the second series of refactoring SDMA. It fixes some bugs and makes code easier to read by breaking sdma_set_config into smaller functions.
CC: @paulstelian97
=> Sdma fixes take2

src/audio/dai.c, src/audio/host.c, src/audio/kpb.c, src/drivers/dw/dma.c, src/drivers/intel/cavs/hda-dma.c, src/include/sof/lib/notifier.h, src/lib/notifier.c, src/platform/intel/cavs/include/cavs/lib/pm_runtime.h, src/platform/intel/cavs/lib/pm_runtime.c, src/probe/probe.c, src/schedule/dma_single_chan_domain.c, src/schedule/ll_schedule.c, test/cmocka/src/notifier_mocks.c
Improves host component performance by extracting DMA L1 exit
to be executed commonly for all active DMA channels as registered
callback in low latency scheduler for timer domain. There is no
need to wait so many cycles for every channel separately.
=> hda-dma: exit L1 only once for all DMA channels

src/include/kernel/ext_manifest.h, src/init/CMakeLists.txt, src/init/ext_manifest.c, src/platform/apollolake/apollolake.x.in, src/platform/apollolake/include/platform/lib/memory.h, src/platform/baytrail/baytrail.x.in, src/platform/baytrail/include/platform/lib/memory.h, src/platform/cannonlake/cannonlake.x.in, src/platform/cannonlake/include/platform/lib/memory.h, src/platform/haswell/haswell.x.in, src/platform/haswell/include/platform/lib/memory.h, src/platform/icelake/icelake.x.in, src/platform/icelake/include/platform/lib/memory.h, src/platform/imx8/imx8.x.in, src/platform/imx8/include/platform/lib/memory.h, src/platform/imx8m/imx8m.x.in, src/platform/imx8m/include/platform/lib/memory.h, src/platform/suecreek/include/platform/lib/memory.h, src/platform/suecreek/suecreek.x.in, src/platform/tigerlake/include/platform/lib/memory.h, src/platform/tigerlake/tigerlake.x.in
Extended manifest is a place to store metadata about firmware, known during
compilation time - for example firmware version or used compiler.
Given information are read on host side before firmware startup.
This part of output binary is not signed.
Related with https://github.com/thesofproject/linux/pull/1818/commits
=>  Create extended manifest

src/audio/dai.c, src/audio/host.c, src/drivers/dw/dma.c
This patch limits number of bytes copied from DMA source
to maximum of one period size per one copy. This does not
change anything for DMA driven pipelines, but only for
timer driven. This limitation is to avoid high peak of MCPS
during copy, especially first one, where we usually have
two periods of data ready. Having some demanding processing
component on the pipe can end up in xrun if the MCPS limit
is exceeded.
=> host: dai: limit number of bytes copied to one period

LICENCE
This is the standard recommended NXP license copyright.
=> licence: Include NXP Copyright

tools/topology/sof/pipe-kfbm-capture.m4
With define for W_PCM_CAPTURE only need 5 arguments
W_PCM_CAPTURE(pcm, stream, periods_sink, periods_source, core)
Fix the wrong parameter in pipe-kfbm-capture.m4
Root cause to be typo from https://github.com/thesofproject/sof/pull/2513
Fix https://github.com/thesofproject/linux/issues/2042
=> topology: fix a typo for SCHEDULE_CORE

src/audio/volume/volume.c, src/include/sof/audio/volume.h
We should not be scheduling ramping as a separate task.
This patch makes it a part of copy function, which allows
for removal of entire schedule related code.
=> volume: do not schedule ramping as separate task

src/audio/pipeline.c
We should not explicitly cancel pipeline task on xrun.
Xrun is handled by different functions and task state
flow will be handled by START and STOP commands.
=> pipeline: do not cancel task on xrun

src/platform/imx8m/include/platform/lib/dma.h, src/platform/imx8m/lib/dma.c
Both SDMA2/SDMA3 can move data from SDRAM to Peripherals. Anyhow, SDMA2
is traditionally used by non-DSP use case, so switch to SDMA3 to allow
for future use cases where we could have a scenario with multiple Audio
perhipherals running in parallel.
This also aligns the code with legacy firmware.
=> lib: imx8m: Switch to SDMA3

tools/test/audio/process_test.m, tools/test/audio/src_test.m, tools/test/audio/std_utils/fr_test_input.m, tools/test/audio/std_utils/fr_test_measure.m, tools/test/audio/std_utils/g_test_input.m, tools/test/audio/std_utils/g_test_measure.m, tools/test/audio/std_utils/thdnf_test_input.m, tools/test/audio/std_utils/thdnf_test_measure.m, tools/test/audio/test_utils/chirp_test_analyze.m, tools/test/audio/test_utils/chirp_test_input.m, tools/test/audio/test_utils/print_pf.m, tools/test/topology/test-playback.m4, tools/tune/eq/eq_blob_plot.m
The detailed description is in the commits. Essentially this allows now getting CSV format results tables and characteristics plots this way. It's useful in automatic validation of existing components in simulation environment and tool for new component developers to catch mistakes those impact objective audio quality:
```
process_test('dcblock');
process_test('eqiir');
process_test('eqfir');
process_test('volume');
```
=> Tools: Test: Various improvements for process components tests

src/include/kernel/tokens.h, tools/testbench/topology.c, tools/tplg_parser/include/tplg_parser/topology.h, tools/tplg_parser/tplg_parser.c
This first commit adds define for the SOF_TKN_CORE_ID token that is present in some topologies for buffer widget, e.g. pipe-volume-playback.m4. 
The second commit for buffer widget load changes is now changed to quite similar to PCM widget so all the arrays get parsed.
The third commit addresses error codes return. The manually set error code is replaced by -errno with malloc() and fseek() calls.
The fourth commit adds return value checks to tplg_read_array() calls.
=> Testbench: Fix topology parse error with volume playback topology

src/platform/intel/cavs/platform.c
Fixes debug region size passed in FW ready message.
=> cavs: platform: fix debug region size in FW ready

tools/topology/m4/pcm.m4
This allows PCM card to support compressed data API. In order
to do this we need to set "compress" property to true. Thus,
the .conf topology file should look like this:
SectionPCM {
/* ... */
compress "true"
}
=> topology: Introduce PCM_PLAYBACK_COMPR_ADD

scripts/docker_build/sof_builder/Dockerfile, scripts/docker_build/sof_qemu/Dockerfile
We don't need history for building qemu or sof. Using shallow clones
will save time spent on downloading unnecessary history which is
significant for bigger repos like qemu.
=> docker_build: Use shallow clones

.travis.yml, scripts/host-testbench.sh
Add status check and fix type size check.
re-enable the test bench check in Travis
fix https://github.com/thesofproject/sof/issues/2752
=> Fix test bench scripts

src/arch/xtensa/CMakeLists.txt
Add MEU_NO_SIGN cmake flag that can be used to build unsigned FW binary,
that may be later used with MEU for signing.
It's for use cases when you have to build on one OS and sign on another.
To use just add f.e. on TGL `-DMEU_NO_SIGN=ON -DMEU_OFFSET=1344` while executing cmake command.
Edit:
Commit 'Add possibility to specify MEU offset.' is also needed because when there is no meu on local machine buildsystem cannot find correct offset for given version, so it has to be provided manually.
=>  cmake: add option to build unsigned FW

src/audio/src/src.c
The SOF supported formats options are configurable via Kconfig. The
build can fail to this error when the data formats are changed from
default:
sof/src/audio/src/src.c: In function 'src_copy_s32':
sof/src/audio/src/src.c:431:2: error: implicit declaration of function 'audio_stream_copy_s32'; did you mean 'audio_stream_copy_s16'? [-Werror=implicit-function-declaration]
audio_stream_copy_s32(source, 0, sink, 0, frames * source->channels);
^~~~~~~~~~~~~~~~~~~~~
audio_stream_copy_s16
The common same rate copy function for S16/S24/S32 formats also
simplifies the code.
=> Audio: SRC: Fix build fail when only CONFIG_FORMAT_S16LE is set

tools/logger/convert.c, tools/logger/convert.h, tools/logger/logger.c
Add option to set timestamp precision and second one to cutout trace location
Original output:
```
$ ./sof-logger -l sof-cnl.ldc -i dma_trace_1.bin
TIMESTAMP              DELTA C# COMPONENT          LOCATION                      CONTENT
[   497588.489583] (   497588.500000) c0 DMA                .../intel/cavs/hda-dma.c:407  hda-dmac: 4 channel 6 -> get
[   497816.250000] (      227.760422) c0 DMA                .../intel/cavs/hda-dma.c:589  hda-dmac: 4 channel 6 -> config
[   497899.270833] (       83.020836) c0 DMA                .../intel/cavs/hda-dma.c:464  hda-dmac: 4 channel 6 -> start
[   497913.906250] (       14.635417) c0 DMA                .../intel/cavs/hda-dma.c:329  hda-dmac: 4 channel 6 -> enable
[   498012.083333] (       98.177086) c0 SA …
```
=> Logger add possibility to make logs output more compact

src/include/sof/lib/uuid.h, src/include/user/abi_dbg.h, tools/logger/convert.c
It make code dealing with entries simpler, and allow to create
UUID entries dictionary with constant access time to any entry.
As long as struct definition is fixed, then can passed as pointer
with correct type to function call, instead of void pointer.
UUID entries aren't storred in flash memory, so entry size is not
important.
Explicit add zero at the end of entity_name to trigger string overflow
warning for shortest incorrect string length.
=> uuid: Make entries monosized

CMakeLists.txt, src/CMakeLists.txt, src/arch/host/CMakeLists.txt, src/arch/xtensa/CMakeLists.txt, src/audio/CMakeLists.txt, src/include/sof/trace/trace.h, src/ipc/CMakeLists.txt, src/lib/CMakeLists.txt, tools/testbench/CMakeLists.txt
Both patches will allow to build FW with traces disabled
=> cmake: fix build without traces

src/audio/eq_iir/eq_iir.c, tools/topology/sof/pipe-eq-fir-volume-playback.m4, tools/topology/sof/pipe-eq-iir-eq-fir-volume-playback.m4, tools/topology/sof/pipe-eq-iir-volume-capture-16khz.m4, tools/topology/sof/pipe-eq-iir-volume-capture.m4, tools/topology/sof/pipe-eq-iir-volume-playback.m4, tools/topology/sof/pipe-highpass-capture.m4, tools/topology/sof/pipe-highpass-switch-capture.m4
The main change in this pull request is to handle multi-part configuration IPC. The other changes are align of bytes control max. size in topologies to 1024 bytes to IIR and 4096 bytes to FIR. Also a mistake fix for macro name clear is included. It didn't seem cause any issues though.
=> Audio: EQ IIR: Add support for large configuration blobs plus EQ topology fixes

scripts/host-testbench.sh, scripts/xtensa-build-all.sh, tools/test/audio/comp_run.sh, tools/test/audio/eqiir_run.sh, tools/test/audio/src_run.sh, tools/test/audio/volume_run.sh
Let's stop ignoring build and test failures. Start gradually with the
scripts involved in testbench, more files later.
Follow-up to to bug #2752 "host-testbench.sh ignores errors" and commit
ab421466aff826 ("CI: Travis: enable host testbnech again") and
ab421466aff826~1
=> scripts/testbench: add set -e

scripts/build-tools.sh
When there's a failure like for instance SOF issue #2543, fixed in
alsa-utils commit caf77a93cef5 ("topology: add back asrc to widget_map
in dapm.c"), it's finally possible to remove all the noise around the
failure and see the failed command:
NO_PROCESSORS=1 VEBOSE=1 ./scripts/build-tools.sh
=> scripts/build-tools.sh: let user override NO_PROCESSORS

scripts/cmake/git-submodules.cmake, tools/CMakeLists.txt
Fix submodule missing issue in tools build by add submodule cmake function into tools build.
=> Fix tool build without submodule setup

zephyr/include/sof/schedule/task.h, zephyr/wrapper.c
This function would be called from Zephyr sample which does not need
to include SOF headers for sof_get(), etc.
=> zephyr: Change task_main_start() to not require sof argument

src/include/ipc/topology.h, src/include/kernel/abi.h
Add ```SOF_COMP_SMART_AMP``` type for smart amp component.
Basic topology using smart amplifier component
could be as follows:
+--------------------------------------------+
+------+    | +---+  +---------------+  +---+  +-------+ |
| Host |----->|Buf|->|   Smart Amp   |->|Buf|->|SSP Dai|----------+
+------+    | +---+  +---------------+  +---+  +-------+ |        |
+----------------^---------------------------+        |
|                                    |
+---+                                  |
|Buf|                                  | 
+---+                                  |
^                                    |
+----------------|-----------------------------+      |
+------+    | +---+  +-------|---------+  +---+  +-------+ |      |
| Host |<-----|Buf|<-|      Demux …
=> topology: add ipc for smart amplifier component

src/drivers/imx/sai.c
We run TX in asynchronous mode and RX in synchronous mode with
transmitter. Anyhow, in this mode when starting RX we also need
to enable TX (if it wasn't previously enabled).
=> drivers: imx: sai: Fix standalone capture

tools/topology/CMakeLists.txt, tools/topology/sof-cnl-rt5682-sdw2.m4
The UpExtreme provides access to link2 in 2 of the 3 modes. This is
useful to test rt5682 configurations.
=> topology: add support for rt5682 on link2 in SoundWire mode

tools/topology/CMakeLists.txt
No one seems to be using this topology or they would have seen the
error below that DMICs are required on this platform.
[  8%] Generating sof-tgl-rt711-i2s-rt1308-nohdmi.conf
m4:tools/topology/sof/pipe-volume-capture-16khz.m4:54: bad expression
in eval (bad input): 2 * 2 * CHANNELS * 16
m4:tools/topology/sof/pipe-volume-capture-16khz.m4:57: bad expression
in eval (bad input): 2 * 2 * CHANNELS * 16
=> topology: remove sof-tgl-rt711-i2s-rt1308-nohdmi.conf

tools/topology/CMakeLists.txt
As seen in PR #2954, no one ever notices m4 warnings. As PR #2954 will
remove sof-tgl-rt711-i2s-rt1308-nohdmi.conf and the only m4 warning
currently, this is a great opportunity to upgrade m4 warnings to
errors.
Note neither Travis nor github have the concept of a "warning", they can
only report success or failure.
This fix can be considered part of the "green failures" family.
=> topology: invoke with m4 --fatal-warnings

README.md
This will help people reach #sof IRC channel easier.
Clicking on the badge will allow people to join IRC
chat via irccloud webclient or prompt for their local
IRC client.
=> README: Add IRC badge

src/arch/xtensa/CMakeLists.txt
This flag should be in sof_options as it is needed for
supporting standard C features.
Thanks to this symbols needed for supporting features
guaranteed by C standard, but not directly supported by platform
ASM will be available in static libraries, without explicitly
specifying -lgcc dependency.
Most of people don't know that they may need this dependency to
support f.e. for float to int conversion on Xtensa.
They expect it to work because it's part of basic C syntax and
they will complain, that they have undefined references to __* symbols.
This patch helps preventing problems like these.
=> xtensa: move -lgcc to sof_options

zephyr/CMakeLists.txt
Remove duplicates from zephyr and use original versions instead.
=> zephyr: Use SOF file versions when possible

src/include/sof/drivers/sai.h
On i.MX8M watermark can be up to 128 and we must adjust
the T/RFW mask register in order for values greater than 64 to be
correctly set.
Now capture works fine!
Fixes: 29414aa25e56a1 ("platform: imx8m: Fix FIFO depth for i.MX8M")
=> drivers: sai: Fix watermark mask size

tools/logger/convert.c
Name should be aligned with address.
=> logger: Increment uuid name during ldc dump

tools/logger/logger.c
Such a change is provoked by getting close to maximal line length
in line with getopt line call. Moving format string to separate
variable is more logical solution than splitting function arguments
on separate lines.
=> logger: Move optstring from getopt function to separate variable

src/audio/buffer.c, src/include/sof/audio/buffer.h, test/cmocka/src/audio/component/mock.c, test/cmocka/src/audio/mux/mock.c, test/cmocka/src/audio/pipeline/pipeline_mocks.c
Each trace function should refer to trace context, where are
stored information like uuid and runtime editable logs level,
to unify trace API and allow trace filtering in future.
Remove buf_cl_* functions, as no longer supported.
=> trace: buffer: Use trace context in buffer logs

tools/logger/logger.c
Before this patch output message was misaligned and one flag
description start from small letter:
```
sof-logger:      -L                     Hide log location in source code
sof-logger:      -f precision                   set timestamp precision
sof-logger:      -d                     Dump ldc information
```
After change, it's fixed:
```
sof-logger:      -L                     Hide log location in source code
sof-logger:      -f precision           Set timestamp precision
sof-logger:      -d                     Dump ldc information
```
=> logger: Fix help message consistency

tools/logger/logger.c
Input file is not needed for these functionalities, so shouldn't be
opened.
=> logger: Do not open input file for ldc_dump

src/platform/baytrail/baytrail.x.in, src/platform/baytrail/platform.c
Section of this section should be aligned to EXT_MAN_ALIGN,
proper way of doing this with ALIGN() function inside linker
script didn't work, because of removing READONLY attribute
for this segment, what leads to error in rimage.
This solution introduce changes only for platforms, where problem
exists, so generic tools like rimage are kept clean of such a hacks.
=> ext_manifest: byt: fix .fw_metadata section alignment

src/include/sof/trace/trace.h, src/trace/trace.c, test/cmocka/src/common_mocks.c
UUID key is too detailed information for logging function to allow
easy functionality extension in future. Trace context structure is
designed to work directly with logging function, so there is no
reason to unpack values from this struct in trace macro-functions
and pass them as separate arguments to trace_log().
=> trace: Pass trace context to logging function

src/drivers/intel/ssp/ssp.c
Fixes invalid sequence of log parameters.
=> ssp: fix log

tools/sof_ri_info/sof_ri_info.py
There are a couple of improvements that handle more corner cases while parsing sof binaries (see individual commit messages).
One output improvement, more compact module information:
```
BRNGUP    2b79e4f3-4675-f649-89df-3bc194a91aeb
entry point 0xb0038000 type 0x21 ( loadable LL )
cfg offset 0 count 0 affinity 0x3 instance max count 1 stack size 0x1
.text   0xb0038000 file offset 0x8000 flags 0x1001f ( contents alloc load readonly code type=0 pages=1 )
.rodata 0xb0039000 file offset 0x9000 flags 0x1012f ( contents alloc load readonly data type=1 pages=1 )
.bss    0x0 file offset 0x0 flags 0xf00 ( type=15 pages=0 )
BASEFW    0e398c32-5ade-ba4b-93b1-c50432280ee4
entry point 0xbe00c400 type 0x21 ( loadable LL )
cfg offset 0 count 0 affinity 0x3 instance max count 1 stack size 0x1
.text …
```
=> tools: improve sof-ri-info parsing and add memory layout info

src/audio/mux/mux_generic.c, zephyr/wrapper.c
Fixes errors when loading topology due to:
...
COMP comp_new(): driver not found, comp->type = 13
...
=> zephyr: Enable IIR init also for CAVS 1.5

CMakeLists.txt, smex/CMakeLists.txt, smex/ldc.h, src/include/kernel/ext_manifest.h, src/platform/apollolake/base_module.c, src/platform/apollolake/boot_module.c, src/platform/cannonlake/base_module.c, src/platform/cannonlake/boot_module.c, src/platform/icelake/base_module.c, src/platform/icelake/boot_module.c, src/platform/intel/cavs/boot_loader.c, src/platform/suecreek/base_module.c, src/platform/suecreek/boot_module.c, src/platform/tigerlake/base_module.c, src/platform/tigerlake/boot_module.c, tools/logger/CMakeLists.txt
In new version of rimage software, headers are located in
rimage/src/include/rimage directory to make it easily accessible
from another source code without include path collision.
=> rimage: Update to version with changed headers location

src/audio/dai.c
Error messages should deliver as much information as possible
to speed up the debug process. Otherwise it relies on presence
of other info-level information in the log and requires scrolling
back to find out things that could be discovered immediately.
=> dai: add more info to err messages

src/audio/dai.c, src/drivers/intel/alh.c, src/drivers/intel/dmic.c, src/drivers/intel/hda/hda.c, src/drivers/intel/ssp/mn.c, src/ipc/handler.c
Prevents DAI config to be executed double for SSP.
Along with this change we need to share dai private data.
From now on master core will be always responsible for setting
dai config on dai and it may happen that private data is allocated
by slave core.
=> ipc: prevent SSP dai config double execution

src/platform/intel/cavs/include/cavs/lib/memory.h
Increases default stack size for EDF tasks. Some of the
IPC operations are very stack heavy, so let's make sure
they won't exceed stack.
Fixes #2921 & #2693.
=> task: increase default stack size for EDF tasks

src/drivers/imx/sai.c
FIFO warning flag signals if SAI FIFO is empty (for transmitter)
or full (for receiver) and it is cleared automatically if the condition
is removed.
We already use FIFO request flag to signal DMA for data availability
so there is no need to enable FIFO warning DMA flag.
This aligns SAI firmware driver with SAI Linux kernel driver.
Also, this mitigates a problem in the SDMA driver where multiple
starting and stopping aplay in a loop results in an I/O error
after some time.
Investigation should continue to fix the SDMA driver.
=> drivers: imx: Disable FIFO warning DMA flag

src/audio/buffer.c, src/audio/pipeline.c, src/include/sof/audio/buffer.h, src/include/sof/audio/component.h, src/include/sof/audio/pipeline.h
To allow setting individual trace level per component, it's necessary to hold such and information in each component.
It's a part of https://github.com/thesofproject/sof/pull/2965
=> trace: Use trace context in each instance of topology components

src/CMakeLists.txt, src/arch/xtensa/include/arch/drivers/idc.h, src/drivers/intel/cavs/idc.c, src/idc/CMakeLists.txt, src/idc/idc.c, src/include/sof/drivers/idc.h
Extracts IDC protocol related code to common file.
Platform specific driver has just the implementations
for hardware specific operations.
=> idc: extract common protocol functions

tools/topology/sof/pipe-eq-iir-volume-capture-16khz.m4, tools/topology/sof/pipe-eq-iir-volume-capture.m4
We broke the upstream UCM configs by introducing pipeline id's to dmic
names. This differentiation is mandatory for reasons in alsaconf parsing
and ASoC layer combining the control names to pga's. However, the
differentiator can't be pipeline id as it can change depending on the
topology. So let Dmic0 have the old "Capture Volume" control name and
prefix Dmic1 control name with "2nd". This should not break the UCM's as
Dmic1 is not currently referenced.
=> topology: fix dmic names (again)

src/ipc/ipc.c
This will prevent removing the component if not in a proper state
as required in our security requirements
=> ipc: check state in comp_free

zephyr/CMakeLists.txt
Helps to de-duplicate headers from Zephyr.
=> zephyr: Use directly headers from SOF

zephyr/CMakeLists.txt
This expands and normalizes the .config before using it.
This makes zero difference to the[sof-]config.h and object
files (verified). This is purely to align closer to how the Zephyr
project uses KConfig and prepare the incoming, unified .config by
helping comparison of the multiple .config files involved for now.
=> zephyr/cmake: run olddefconfig.py on _defconfig before genconfig.py

Kconfig, src/Kconfig, src/arch/Kconfig, src/drivers/Kconfig
As documented in https://docs.zephyrproject.org/2.2.0/guides/modules.html,
Zephyr and Kconfiglib support merging Kconfig menus across multiple git
repos. This requires relative inclusion paths.
=> Kconfig: use relative 'rsource' paths so SOF can be a Zephyr module

.gitignore
That's too extreme and was probably accidental because the rest of
commit d721347ad945 ("gitignore: ignore boot loaders and binaries.")
seems not related at all.
=> .gitignore: don't ignore all .* hidden files in every subdirectory

src/include/sof/trace/trace.h, src/platform/apollolake/apollolake.x.in, src/platform/baytrail/baytrail.x.in, src/platform/cannonlake/cannonlake.x.in, src/platform/haswell/haswell.x.in, src/platform/icelake/icelake.x.in, src/platform/imx8/imx8.x.in, src/platform/imx8m/imx8m.x.in, src/platform/suecreek/suecreek.x.in, src/platform/tigerlake/tigerlake.x.in
It is the first step to allow iterating over the trace context
entries and of search for the right one.
It's a part of https://github.com/thesofproject/sof/pull/2965
=> trace: Put global trace context entries to separate section

src/include/sof/lib/alloc.h
=> alloc: Correct path for the memory.h

tools/topology/sof-ehl-rt5660.m4
The stream parameters set in the pipeline were mismatched with
the DMIC hardware configuration, which resulted in failures.
=> topology: align pipeline parameters with hardware configuration

src/drivers/intel/dmic.c, src/include/sof/drivers/dmic.h
Implements new DMIC_HW_VERSION 3. It requires to set ipm values
no matter how many controllers are implemented.
=> dmic: add DMIC_HW_VERSION 3

src/drivers/intel/ssp/ssp.c
Uses default SSP source clock for platforms without support
for M/N dividers.
=> ssp: use default clock for platforms without M/N dividers

src/schedule/dma_single_chan_domain.c
Check if re-register failed in dma_domain_unregister_owner.
Error was reported by clang static analyzer as potential null dereference.
=>  schedule: dma: check irq register result

src/audio/asrc/asrc.c, src/audio/buffer.c, src/audio/component.c, src/audio/dai.c, src/audio/dcblock/dcblock.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/audio/pipeline.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/switch.c, src/audio/tone.c, src/audio/volume/volume.c, src/include/sof/audio/component.h, src/include/sof/lib/uuid.h, tools/testbench/file.c
A few UUID entries, related with components from topology,
should be loaded into SRAM to allow runtime comparison with
value in IPC message during component creation. UUID of the
components whose are not created by IPC message are not needed
in runtime, so there should not be there to reduce memory
consumtion.
It's a part of https://github.com/thesofproject/sof/pull/2920
@keyonjie please check if I choose 'RT` UUID for all needed components.
=> sof: Define possible UUID entries usage in IPC during declaration

src/include/sof/lib/io.h
Adds additional variations of register access functions:
- 64 bit register write,
- 8 bit register read,
- 8 bit register write,
- 8 bit register update.
=> io: add additional variations of reg access functions

src/init/init.c
Adds misssing inclusion of drivers\interrupt.h.
=> init: add missing inclusion

src/ipc/handler.c
This patch will deny IPC headers with size 0
Fixes #3028
=> ipc: header size validation fix

src/include/sof/drivers/ipc.h, src/ipc/handler.c
Currently, in the ipc_schedule_process function, when we call
schedule_task to schedule an ipc task, we use magic number to
indicate the time kernel waits before calling timeout on an
IPC. This makes it difficult to search for the timeout period
using grep and other utilities. Replacing it with a macro makes
it easier to search and change only at one place.
=> ipc: use macro instead of a magic number for timeout period

Kconfig, src/platform/Kconfig
Removes cAVS menu and moves all platform specific things
to platform menu.
=> kconfig: remove cAVS menu

README.md
As discussed in PR #2964, the Travis badge shows the status of the
master branch but it links to the random PR of the moment. Fix that link
to point to the more useful "branches" page which has the master branch
at the top.
=> README.md: fix Travis badge not to show the random PR of the moment

src/audio/pcm_converter/pcm_converter.c
Output sample size is unrelated wit input one. To calculate
write pointer address, correct value should be use.
Without this path, output data will be placed in wrong memory
area, what results in corrupted output stream when output offset
differ from zero.
=> pcm_converter: Fix first output sample pointer calculation

src/include/sof/trace/trace.h, src/trace/trace.c, test/cmocka/src/common_mocks.c
Ability to change log level per UUID component improve user
experience during debugging firmware. Threshold trace level
defined in log message with value from trace context, where
trece context is related with component instance (local or
global instance).
Part of https://github.com/thesofproject/sof/pull/2965
=> trace: Filter messages in runtime

src/audio/volume/volume.c, src/include/sof/audio/volume.h
This patch replaces the fixed step increment/decrement linear ramp
update with a time since transition start calculated direct line point
value. It does not suffer from accumulated rounding errors.
The new ramp_coef[] vector (that replaced ramp_increment[]) defines
per channel the slope coefficient as Q16.16 units per millisecond. The
slope points calculation needs a new counter variable that counts
frames since ramp start. Also the volumes vector at time of ramp start
need to be stored. The old fixed increment calculation related macros
are removed.
The zero crossings timed volume mode suffered from fixed step the most
since depending on signal the fixed step could update the value too
much or too little.
=> Audio: Improve volume gain ramp length accuracy

tools/topology/CMakeLists.txt, tools/topology/sof-jsl-rt5682.m4
The topology is cloned from sof-tgl-max98357a-rt5682.m4 with
changes on ssp config, iDisp number and DMIC pipeline pcm # etc.
The dai_index matches the order defined in sof-rt5682.c machine driver.
=> topology: Add jsl+ tplg for RT1015 amp and ALC5682 Headset codec

.travis.yml
SOF has #sof dedicated channel on irc.freenode.net server.
This will enable travis ci to send notifications to the IRC
channel each time a build is finished (either successful or not).
We will see how this works and refine it later if it is too spammy.
=> .travis.yml: add IRC notifications

tools/topology/CMakeLists.txt, tools/topology/platform/intel/jsl-rt1015.m4, tools/topology/sof-jsl-rt5682.m4
Added support for ma98360a codec on existing jsl-rt5682 topology. 
Separated topology build configuration for sof-jsl-rt5682-rt1015 & sof-jsl-rt5682-mx98360a
=> Jsl mx98360a

src/include/ipc/info.h, src/include/kernel/abi.h, src/include/kernel/ext_manifest.h, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/platform.c
This information known at build time does not need to be
provided in a mailbox.
https://github.com/thesofproject/linux/pull/2087
=> ext_man: Port SOF_IPC_EXT_WINDOW to extended manifest

zephyr/CMakeLists.txt
Use correct SOC_NAME for byt and bdw.
Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>
=> zephyr: Correct SOC_NAME

scripts/cmake/git-submodules.cmake
- Add a simple test in cmake to download submodules only when rimage is
missing. This stops randomly changing the source code from one build
to the next and overwriting any submodule work in progress.
- Remove the GIT_SUBMODULE option which is now useless because rimage is
not optional for sof
- Add a --merge option for safety. It makes zero difference right now
but could save work in progress if we ever add more
submodules (hopefully not) and someone struggles with submodules and
ends up in a partially initialized state.
Git submodules are rarely ever the answer; these few changes make them a
bit more usable.
=> cmake/git-submodules: don't throw away work in progress at build time

zephyr/CMakeLists.txt
Fixes build issues on byt platform.
=> zephyr: Include agent.c only when CONFIG_HAVE_AGENT

scripts/xtensa-build-all.sh
"Configure defconfig" misses the most important, interactive difference.
=> scripts/xtensa-build-all.sh: clarify help of -c option

src/drivers/intel/cavs/timer.c
All timers should have logical_irq properly set up.
In case of arch timers logical_irq is equal to irq.
=> cavs: timer: set logical_irq for arch timers

src/audio/mux/mux_generic.c
Demux should select proc func based on source buffer,
because sink can be not set yet (e.g. this can be observed
in smart amplifier topology scenario where there is
buffer between playback and capture pipeline).
=> mux: select demux proc function based on source buffer

zephyr/CMakeLists.txt, zephyr/wrapper.c
These patches are needed to build byt and bdw.
=> zephyr: Update for byt and bdw SOCs

src/audio/host.c
The pipeline is in active state so pipeline_prepare() always fail and
the pipeline_task() stops the pipeline. A stop trigger could move the
pipeline to prepare state for pipeline_prepare() to run successfully.
=> pipeline: fail to recover from xrun in pipeline_task
