src/arch/xtensa/init.c, src/arch/xtensa/lib/cpu.c
This will fix cache handling for shared_vecbase and allow to
boot slave cores in a proper way.
=> arch: shared_vecbase cache fix

src/ipc/ipc.c
`pipe` should refer to `pipeline_id`, using `comp_id` is misleading.
=> ipc: pipe: Fix pipe id value in log message

zephyr/CMakeLists.txt, zephyr/wrapper.c
Fixes build for boards with disabled MUX.
=> zephyr: Include MUX sources only when enabled

.travis.yml, scripts/xtensa-build-all.sh, src/arch/xtensa/lib/cpu.c
See commit messages.
The build with this toolchain has NOT been tested, however the -g0 -Wno-err binaries produced by gcc are identical before and after this change. The purpose of is purely to add the gcc build to CI, avoid future gcc bitrot and catc  more warnings and bugs.
=> add tgl with xtensa-cnl-elf. No rimage yet.

src/audio/mux/mux.c
Sink buffer should be locked and invalidated (inside lock function)
before reading, to acheve consistent data between multiple cores.
Otherwise readed data may be outdated.
=> demux: Fix buffer lock in copy function

src/arch/xtensa/include/arch/init.h, src/debug/panic.c, src/include/sof/debug/panic.h
this will restore functional backtrace for exception stack dump because stack rewind
is not implemented correctly
Example log from coredump (full backtrace):
```
$2 = "backtrace"
```
the idea of stack rewind was to hide first #0-4 entries but it was problematic and in most cases backtrace was not working at all.
In my opinion full backtrace is clear enough and there is no need to modify it.
=> debug: disable stack rewind in exception

.travis.yml
No obvious reason not to build ROM for "buildonly" platforms too.
=> .travis.yml: build ROM for "buildonly" platforms too

tools/topology/sof-jsl-da7219.m4
Remove the wrong one more 0 in the DAI config for HDMI.
=> topology: fix wrong parameter for HDMI in sof-jsl-da7219

src/audio/pipeline.c
Whenever it is possible, trace function with reference to pipe
component should be used instead of class less method. It allows
to print pipeline id in output logs and filter logs by this value.
In pipeline_new() moved trace context and ipc_pipe copy, to allow
tracing with context in earlier stages of this function.
=> pipe: Trace with pipe component instead of class less method

src/audio/dai.c
It easier to compare number of copied frames between dai and
process components than copied bytes.
=> dai: Log number of frames in copy function

tools/logger/convert.c, tools/logger/convert.h, tools/logger/logger.c
After removing timestamps it is possible to compare output logs
with tools like diff or similar. Moreover then output logs are
in more compact form.
=> logger: Add possibility to hide timestamps

src/include/sof/audio/pipeline.h, src/include/sof/drivers/ipc.h, src/ipc/ipc.c, test/cmocka/src/audio/pipeline/pipeline_mocks.h
Mechanism of comparison pipe_id from ipc_comp_dev will be used in
trace filtering, so this part should be moved to separate function
and allow code reusability.
Moreover function usage is compact and descriptive method to define
what given block of code should do, so after such a refactor code
readability is improved.
This is part of https://github.com/thesofproject/sof/pull/2965
=> ipc: Extract pipeline id dereference from ipc_comp_dev structure

src/arch/host/CMakeLists.txt, src/arch/xtensa/CMakeLists.txt, tools/testbench/CMakeLists.txt
This is not needed yet as we use only one -imacros at a time but could
save someone a lot of time in the future; including the author of this
patch who will have forgotten about it in a few weeks.
For more details see
https://github.com/zephyrproject-rtos/zephyr/commit/e53c0d0ec7640b
and links from there.
=> cmake: no space after -imacros to avoid de-duplication

tools/topology/sof-tgl-sdw-max98373-rt5682.m4
For original design, there are 4 channels 24bit stream for playback
and 8 channels 24bit IV feedback for capture. This requirement exhausts
all resource on single link. Now adjust it to 2ch stream for playback
and 4ch stream for capture
=> topology: tgl-max98373-rt5682: adjust channel usage for sdw DSM support

tools/topology/sof-smart-amplifier.m4, tools/topology/sof-tgl-max98373-rt5682.m4
make sure the SMART_SSP_QUIRK is configured, and use the unify mclk among SSPs.
This will fix https://github.com/thesofproject/linux/issues/2190
=> Smart amp tplg fixes

.gitignore
When sof source code is edited in Eclipse, the project
metadata files should be ignored by git.
=> gitignore: add Eclipse project metadata

src/include/sof/lib/perf_cnt.h
For simple performance measurement and optimization in development stage,
tic-toc api is provided. Performance data are traced at each tok call,
to allow fast clocks usage deviation estimation.
=> perf_cnt: Add tic-toc api for single component performance optimization

src/audio/component.c
In comp_get_model() function we should return warning in
case not allocated model->data.
fixes #3068 
=> comp: return warning instead of error in comp_get_model()

src/audio/smart_amp_test.c
Number of available frames from feedback and passthrough buffers
should be in the same format and close together for easily compare.
Moreover reducing number of logs, especially from copy function is
important in terms of logs readability and FW performance - adding
one more parameter have much less impact on FW than adding one more
log message.
=> smart_amp: Merge dbg logs from copy function

src/audio/buffer.c
Buffer flags is important field and should be accessible in logs
output.
=> buffer: Describe buffer flags in init log

src/audio/mixer.c
Limits additional check in mixer_reset to playback streams only.
For mixer in capture streams the request will always come from downstream,
which means that source components will always be in state >
COMP_STATE_READY. Checking sink component also doesn't make,
because it's the source of the request. The logic is now similar
to the mixer_trigger, where for capture streams we also don't require
additional checks.
=> mixer: reset additional check is only needed for playback

scripts/checkpatch.pl
Yes, staying withing 80 columns is certainly still _preferred_.  But
it's not the hard limit that the checkpatch warnings imply, and other
concerns can most certainly dominate.
Increase the default limit to 100 characters.  Not because 100
characters is some hard limit either, but that's certainly a "what are
you doing" kind of value and less likely to be about the occasional
slightly longer lines.
Miscellanea:
- to avoid unnecessary whitespace changes in files, checkpatch will no
longer emit a warning about line length when scanning files unless
--strict is also used
- Add a bit to coding-style about alignment to open parenthesis
dbaluta: This patch is taken and manually applied from Linux kernel
tree. See commit, in Linux kernel tree:
bdc48fa11e46 ("checkpatch/coding-style: deprecate …
=> scripts: checkpatch: deprecate 80-column warning

src/audio/volume/volume.c, src/include/sof/audio/volume.h, tools/topology/sof/pipe-asrc-volume-playback.m4, tools/topology/sof/pipe-dcblock-volume-playback.m4, tools/topology/sof/pipe-eq-fir-volume-playback.m4, tools/topology/sof/pipe-eq-iir-eq-fir-volume-playback.m4, tools/topology/sof/pipe-eq-iir-volume-playback.m4, tools/topology/sof/pipe-src-volume-playback.m4, tools/topology/sof/pipe-volume-playback.m4
This pull request contains changes:
- Tools: Topology: Change playback volume ramp duration to 20 ms
- Audio: Improve volume ramp time calculation precision
- Audio: Make volume gain ramp update rate variable
The shortening from 250 ms to 20 ms was made to get short notification tones better audible. The long ramp suppresses quite a lot the beginning. The two other changes are are improvements to volume component to sound better with fast ramp and optimize ramp rate for needed ramp time.
=> [RFC] Audio: Shorten volume playback ramp length to 20 ms including other improvements 

src/audio/kpb.c
Parameter validation should give detailed information about wrong
settings to speed up the troubleshooting.
=> kpb: add detailed info to error messages

src/drivers/intel/ssp/mn.c, src/platform/intel/cavs/include/cavs/drivers/mn.h
We should clear MNDSS and MCDSS bits before setting
new mclk and bclks source clocks. This commit is
going to fix case when driver want to reconfigure
the same SSP (e.g. index = 0).
1. Driver sends ssp_config() and FW configures ssp
(index = 0) with MCDSS bits set to e.g. 1.
2. Driver wants to reconfigure the same ssp (index = 0)
by sending new ssp_config() and FW tries to configure
ssp 0 once again, but firstly it reads MDIVCTRL
register:
```mdivc = mn_reg_read(MN_MDIVCTRL, mclk_id)```
and then tries to set MCDSS(0):
``` mdivc |= MCDSS(0);```
, but there is "or" function here - after it MCDSS bits
still will be set to 1. That's why we should clear this
bits earlier.
=> mn: clear mclk and bclk source clks in MDIVCTRL

tools/topology/sof-hda-generic-kwd.m4
We need PGA to tune the volume for the KWD pipeline, switch to use
vol-kfbm mode to get it done.
=> topology: sof-hda-generic-kwd: switch to use vol-kfbm mode

scripts/qemu-check.sh
See commit messages
Fixes 428804e ("scripts/qemu-check.sh: add set -e") which failed to consider the case of an empty $IPC_REG or $IPC_MSG.
Address two shellcheck warnings
=> Restore qemu error messages

zephyr/ll_schedule.c, zephyr/wrapper.c
Since we change Zephyr allocation it is better to use SOF API which
would use the latest Zephyr allocator method.
=> zephyr: Use right SOF allocator API

zephyr/wrapper.c
Use Zephyr support for aligned alloc in SOF instead of wrapper for
k_malloc().
=> zephyr: Use sys_heap_aligned_alloc() for aligned alloc

tools/topology/sof-tgl-sdw-max98373-rt5682.m4
For original DMIC16k only S16_LE is supported in pcm capability.
Now this patch enables S24_LE and S32_LE for applications like
DMIC01.
fixes https://github.com/thesofproject/sof/issues/3102
=> topology: tgl-sdw-max98373: change DMIC16k format to 32LE

src/audio/volume/volume.c
Required sink size and actual size should be available
in the log file.
=> volume: add details to sink size error message

src/audio/detect_test.c
This is submitted to fix the issue #3112 
Refine to use the consistent activation threshold for different formats,
use a unified divider 0.05, and update the threshold at .params() stage.
These refinement will fix the KWD trigger volume inconsistent for
different sample format issue.
=> detect_test: refine the activation threshold to fix trigger issue

src/audio/asrc/asrc.c, src/audio/asrc/asrc_farrow.c, src/include/sof/audio/asrc/asrc_farrow.h
This pull request addresses issue #2981 . The fixes add to frame count calculation the effect of skew factor. Though no errors found the same add is done for push mode that is used in playback. The control loop is also slowed down since it reacted too fast with small amount of samples flow per copy() with low rates like 8 kHz.
=> Audio: ASRC: Fix for random glitches in capture

src/platform/apollolake/include/platform/lib/shim.h, src/platform/cannonlake/include/platform/lib/shim.h, src/platform/icelake/include/platform/lib/shim.h, src/platform/intel/cavs/include/cavs/lib/shim.h, src/platform/suecreek/include/platform/lib/shim.h, src/platform/tigerlake/include/platform/lib/shim.h
Moves register helper functions to common cavs header.
=> cavs: shim: make register functions common

src/audio/pcm_converter/pcm_converter_generic.c
Usage of pcm_convert_as_linear() function speed up conversion
and make core convert function easier to implement.
=> pcm_converter: Convert linear memory regions

scripts/cmake/dist.cmake
A "tarbomb" is an archive file that has more than one directory at the
top level, which is (fortunately) unusual for .tar files. By default,
tar extracts archive members "as is" in the current directory. If the
archive has many top level members then it becomes very hard to make the
difference between what was just extracted versus what was already
there. As extraction is recursive this gets much worse because the
problem can repeat itself in subdirectories. As the last but not least
nail in the coffin, tar silently overwrites existing files by default.
This commit is admittedly an "incompatible build API change" meaning any
higher level build or packaging script that was consuming source release
tarballs (as opposed to git cloning the source) will require a small
change. Consumers of …
=> dist.cmake: add --prefix to git archive to stop creating a "tarbomb"

scripts/xtensa-build-all.sh
The main build script has a fairly verbose output by default but not the
most important things it does yet. These commands are useful to "peel"
the layer of indirection and debug cmake issues; either locally or when
wondering what CI does.
=> xtensa-build-all.sh: log the main cmake and defconfig commands

tools/topology/platform/intel/jsl-rt1015.m4
The new recommended settings at 48Khz rate are:
PLL input       SSP bclk
------------------------
64fs            3.073Mhz
100fs           4.8Mhz
Modifying topology to 100fs
=> PLL input at 50fs is no longer supported

src/arch/host/include/arch/lib/cpu.h, src/arch/xtensa/include/arch/lib/cpu.h, src/arch/xtensa/lib/cpu.c, src/include/sof/lib/clk.h, src/include/sof/lib/cpu.h, src/include/sof/lib/pm_runtime.h, src/lib/clk.c, src/platform/intel/cavs/include/cavs/lib/pm_runtime.h, src/platform/intel/cavs/lib/clk.c, src/platform/intel/cavs/lib/pm_runtime.c
There was race condition in situation with multicore environment:
1. One core saves active `current_freq_idx`  to `active_freq_idx` (HPRO) and then change `current_freq_idx` to LPRO
1. Another core saves active `current_freq_idx`  to `active_freq_idx` (LPRO) and then change `current_freq_idx` to LPRO
1. After wake-up system restore  `active_freq_idx` - LPRO instead HPRO
Moreover `sleep_core_mask` must be introduced because in a case with multiple cores connected to single clock source, then clock rate may be reduced only when each of them is in wait state.
=> Fix clock change in waiti for multicore access

scripts/cmake/version.cmake
Before this fix, any random, later git tag like for instance
"releases/jsl/v3.0-rc1" would be picked up and then immediately
discarded and replaced with v0000 because it didn't start with 'v*'
Also log all the versions always and not just when there is already a
.tarball-version file.
Increase --abbrev=12 because --abbrev=4 doesn't seem to make sense.
=> version.cmake: add "--match v*" to fix git describe

src/lib/pm_runtime.c
It's important to know which pm_runtime_context is related with
given call to pm_runtime* function.
=> pm_runtime: Log context and index value in verbose traces

src/arch/xtensa/include/arch/atomic.h, src/schedule/ll_schedule.c
Return value should be aligned with compiler builtins implementations,
see https://gcc.gnu.org/onlinedocs/gcc-4.1.1/gcc/Atomic-Builtins.html
=> atomic: ll_scheduler: Fix atomic implementation, return old value

src/audio/pcm_converter/pcm_converter_generic.c
https://github.com/thesofproject/sof/pull/3156 does not work, so if we can't get a quick fix let's revert and redo. Nothing personal, just that we can't break CI for a month and keep going this way.
This reverts commit 1f092df4012def1c541bf7c627ecffd51584093b.
=> Revert "pcm_converter: Convert linear memory regions"

.gitignore, scripts/cmake/dist.cmake
dist.cmake is (for now) the only .cmake file that uses GIT_TAG at _cmake
configure time_. This means even "make clean" is not enough for
dist.cmake to take into account some git tag or version change. It's
very confusing because on the other hand "make check_version_h" and
everything else always shows up-to-date git information.
"make rebuild_cache" addresses this situation so mention it in a
warning.
=> dist.cmake: add 'rebuild_cache' warning.

src/include/ipc/header.h, src/ipc/handler.c
Collect key IPC documentation to header.h and ensure it is
included in public API documentation in the doxygen output.
Specifically move the IPC compatibility rules documented in ipc/handler.c.
This is important information to all IPC implementers for host
and DSP, so should be part of API documentation.
=> ipc: add IPC documentation to header.h

src/include/sof/common.h
This is effectively the same patch that the Zephyr integration branch has.  IMHO it's a little bit cleaner as we have a standard symbol to test for Zephyr compilation, and this way we don't have to unconditionally disable a macro inside of Zephyr's headers.
I've been carrying this locally while working on the andyross/zephyr/sof-upstreaming branch because I've removed that change there (for obvious reasons the existing change has no chance of merging).
=> sof/common.h: Disable ARRAY_SIZE() & IS_ENABLED() under Zephyr

scripts/checkpatch.pl
Stop drowning and missing other warnings.
Example:
./scripts/checkpatch.pl -g eaf49e26b4bb~0
- 40 "Please update ABI..." warnings
- 2 other warnings including a spelling mistake that were missed.
=> check patch: ABI warning only once per file, not once per line

scripts/xtensa-build-all.sh
Fixes most shellcheck warnings, now down to just 4.
=> xtensa-build-all.sh: add missing double quotes

scripts/xtensa-build-all.sh
In renaming of $j -> $platform one instance of variable was missed which
has led to wrong configs being used.
=> xtensa-build-all: Fix missed $j -> $platform renaming

src/include/sof/schedule/schedule.h, src/include/sof/schedule/task.h, src/schedule/edf_schedule.c
This patch removes not used code from edf_scheduler header
file and code which is setting edf scheduler tasks start
time while this is not supported by this scheduler.
=> edf_scheduler: cleanup

src/audio/kpb.c
This patch decreases history buffer free size during
real time copies therefore we avoid history data overwrite
when draining is delayed.
=> kpb: update kpb HB free size during RT copies

tools/topology/sof-smart-amplifier.m4
This commit changes SSP bclk rate from 9600000 to
12288000 ind ssp container to 32 bits order to fix
glitch issue.
fixes #3092 
=> smart_amp: fix smart amplifier tplg

src/arch/xtensa/lib/cpu.c
This was missed changes after commit
"fedec980: cpu: Export mask with enabled cores".
Without it, edited condition is always false.
=> platform: intel: cpu: Fix slave cores objects allocation

src/audio/kpb.c
Move the switch check out of the loop, to optimize the
kpb_drain_samples() and speed up the draining itself.
=> kpb: move the switch check out of the loop to optimize the draining

src/ipc/handler.c
Make sure we see hex message in the log.
=> ipc: handler: Message trace data is hex not decimal.

src/audio/dai.c
This value is one of audio_stream property, so should be
saved in this place to keep data synchronised, and allow
to usage generic function working on audio_stream, like
stream converters.
=> dai: Remove frame_fmt from private data

src/drivers/intel/dmic.c
irq_enable/disable should be doing the unmasking and masking so no need to manually do this.
=> dmic: irq: removed unneeded code.

tools/testbench/common_test.c
tb_pipeline_params() function takes an argument called ipc_pipe,
which is a pointer and is derefernced in the function to access
a member of structure that pointer is pointing to.
If this pointer is NULL, this leads to Segmentation fault. A
null pointer check is added before the argument is dereferenced.
This error was found when testbench was fuzzed with AFL fuzzer.
=> testbench: add null pointer check for function argument

src/audio/asrc/asrc.c, src/audio/dai.c, src/audio/dcblock/dcblock.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/src/src.c, src/audio/switch.c, src/audio/tone.c, src/include/sof/audio/component.h, src/include/sof/ut.h
Zephyr build fails without this atm, but also needed for testbench.
=> components: ut: all components should be declared UT_STATIC

src/include/sof/math/numbers.h
Some macros are duplicated between SOF and Zephyr meaning we need
to undefine them in the short term until Zephyr and SOF can align
fully.
=> zephyr: numbers:  MIN/MAX INT already defined in Zephyr

Kconfig, scripts/xtensa-build-all.sh, src/CMakeLists.txt, src/arch/xtensa/Kconfig, src/arch/xtensa/include/arch/init.h, src/arch/xtensa/include/arch/lib/cpu.h, src/arch/xtensa/init.c, src/arch/xtensa/lib/CMakeLists.txt, src/arch/xtensa/schedule/task.c, src/arch/xtensa/xtos/crt1-boards.S, src/arch/xtensa/xtos/int-highpri-dispatcher.S, src/arch/xtensa/xtos/int-medpri-dispatcher.S, src/arch/xtensa/xtos/int-sethandler.c, src/arch/xtensa/xtos/interrupt-table.S, src/arch/xtensa/xtos/ints-off.S, src/arch/xtensa/xtos/ints-on.S, src/arch/xtensa/xtos/user-vector.S, src/arch/xtensa/xtos/xea1/int-lowpri-dispatcher.S, src/arch/xtensa/xtos/xea1/intlevel-restore.S, src/arch/xtensa/xtos/xea1/intlevel-set.S, src/arch/xtensa/xtos/xea1/intlevel-setmin.S, src/arch/xtensa/xtos/xea2/int-lowpri-dispatcher.S, src/arch/xtensa/xtos/xea2/intlevel-restore.S, src/arch/xtensa/xtos/xtos-internal.h, src/arch/xtensa/xtos/xtos-structs.h, src/drivers/intel/cavs/CMakeLists.txt, src/platform/intel/cavs/include/cavs/drivers/idc.h, src/platform/tigerlake/include/platform/lib/memory.h, test/cmocka/src/audio/mux/mock.c, test/cmocka/src/audio/pipeline/CMakeLists.txt
This kconfig collides with one of the same name in Zephyr.  Rename it
for clarity ("MULTICORE" was picked for symmetry with the existing
"CORE_COUNT", though it's admittedly a little long...).
Signed-off-by: Andy Ross <andrew.j.ross@intel.com>
=> zephyr: kconfig: rename CONFIG_SMP -> CONFIG_MULTICORE

src/init/init.c, src/ipc/handler.c, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/intel/cavs/platform.c
Modify the SOF init sequence to avoid the areas where Zephyr has performed initialisation. 
@dbaluta same will need done for IMX once Zephyr core is fully upstreamed.
=> zephyr: intel: make sure we do not perform init twice in SOF and Zephyr

src/arch/xtensa/include/arch/drivers/idc.h
Zephyr will provide it's own per core data in place of the xtos data. XTOS not used by Zephyr.
=> arch: xtensa: idc: dont use xtos structs for zephyr.

src/audio/component.c, src/audio/pipeline.c, src/audio/smart_amp_test.c, src/include/sof/audio/component.h
Smart amp is quite specific component because of feedback buffer between pipelines, so memory handling must be performed with care to use valid data. This PR have a series of fixes which allows smart amp to work on the another core. Feedback buffer from smart_amp must allow overrun to omit start-up race between pipelines.
=> Smart amp: prepare for multi core processing

src/drivers/imx/sdma.c
When compiling with Xtensa Tools xt-xcc, fixes the compilation error:
sof/src/drivers/imx/sdma.c: In function ‘sdma_register_init’:
sof/src/drivers/imx/sdma.c:192: error: ‘for’ loop initial declaration used outside C99 mode
sof/src/drivers/imx/sdma.c:195: error: redefinition of ‘i’
sof/src/drivers/imx/sdma.c:192: error: previous definition of ‘i’ was here
sof/src/drivers/imx/sdma.c:195: error: ‘for’ loop initial declaration used outside C99 mode
This patch simply rewrite loops as C90 "for" loops declaring "int i"
outside the loop.
Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
=> drivers: imx: sdma: rewrite C99 for loops as C90

Kconfig, src/drivers/intel/Kconfig, src/drivers/intel/cavs/ipc.c, src/idc/idc.c, src/include/sof/schedule/edf_schedule.h, src/schedule/edf_schedule.c
Baytrail + Cherrytrail have been plagued by instability issues for several weeks, and the trace is no longer functional.
By bisecting to restore the trace functionality, I came across this report pointing at e003afe582e41c / PR #3057 
````
e003afe582e41c4a8a52b21d45dbc83c166021a5 is the first bad commit
commit e003afe582e41c4a8a52b21d45dbc83c166021a5
Author: Janusz Jankowski <janusz.jankowski@linux.intel.com>
Date:   Fri Jun 5 20:33:47 2020 +0200
schedule: edf: cycles budget
Add possibility to set budget for EDF tasks.
It's needed to ensure that some long running task will
not stall other tasks.
src/include/sof/schedule/edf_schedule.h | 10 ++++++
src/schedule/edf_schedule.c             | 56 …
```
=> Revert scheduler changes  - restore BYT/CHT functionality

src/platform/intel/cavs/include/cavs/lib/pm_runtime.h, src/platform/intel/cavs/lib/pm_runtime.c
Remove the usage of refcount dsp_d0_sref, and use bool flag dsp_d0 to
denote is the DSP target state is D0 or D0ix (Low power mode).
This will simplify the logic of use of LPS and clock switching.
=> cAVS: pm_runtime: change to use bool flag to denote the DSP target state

src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/host.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/audio/src/src.c, src/include/sof/audio/audio_stream.h
audio_stream: Calculate sample size inside audio_stream_copy function
Sample size is related with frame format, which is saved inside
audio_stream, so this value can be easily calculated inside
audio_stream_copy function. This approach allows to delete
functions like audio_stream_copy_s16/s32 and functions related
to them, then code will be shorter and cleaner.
Moreover in future, during compressed stream implementation, there
won't be need to add new copy function implementation for compressed
streams, it will be sufficient to return 1 in audio_stream_sample_bytes()
for non-pcm formats, then sample calculation will be equal to number
of bytes and generic function like copy shoudn't have any trouble to
handle such a data type.
=> Unify audio_stream_copy

tools/topology/CMakeLists.txt
tgl-rt711-rt1316-rt715 is almost the same as tgl-rt711-rt1308-rt715 and
can use the same topology file.
=> topology: add tgl-rt711-rt1316-rt715 support

src/audio/buffer.c, src/audio/detect_test.c, src/audio/host.c, src/audio/kpb.c, src/audio/smart_amp_test.c, src/audio/src/src.c, src/include/sof/audio/audio_stream.h, test/cmocka/src/audio/buffer/buffer_copy.c, test/cmocka/src/audio/buffer/buffer_new.c, test/cmocka/src/audio/buffer/buffer_wrap.c, test/cmocka/src/audio/buffer/buffer_write.c, test/cmocka/src/audio/mixer/mixer_test.c, test/cmocka/src/audio/mux/CMakeLists.txt, test/cmocka/src/audio/mux/demux_copy.c, test/cmocka/src/audio/mux/mock.c, test/cmocka/src/audio/mux/mux_copy.c, test/cmocka/src/audio/mux/mux_get_processing_function.c, test/cmocka/src/audio/mux/util.h, tools/testbench/file.c
All audio_stream clients should use provided audio_stream_get_avail*/free*
API, instead of directly accessing .avail and .free member fields.
=> Remove references to .free and .avail members of audio_stream.

tools/topology/sof-tgl-max98357a-rt5682.m4
topology: fix playback & capture pipelines to be timer driven
This patch fixes several pipelines which are DMA driven by default
but should be driven in timer domain.
=> topology: fix TGL topology

src/drivers/intel/ssp/ssp.c, src/include/sof/drivers/ssp.h
This function should wait to transmission last element from FIFO,
what is indicated in SSSR and SSCR3 registers.
=> ssp: Debug ssp_empty_tx_fifo()

tools/testbench/testbench.c, tools/testbench/topology.c, tools/tplg_parser/tplg_parser.c
First patch:
When we try to free a pointer which is not initialized, we are
using a value in the program which is undefined. So, initialize
the pointer variable, so that in future, when we free the pointer
it won't cause a problem.
Second patch:
When an error is occurred when loading the widget, the memory
allocated is not freed properly. This results in memory leaks.
Avoid these memory leaks by freeing the allocated memory before
exiting the function by returning error value.
Third patch:
When we are about to access a pointer for its contents, check if
the pointer is NULL before doing so. Else, it may lead to segmentation
faults.
This error was found when testbench was fuzzed with AFL fuzzer.
=> tools: fix memory leaks or errors found when fuzzing using AFL

tools/tplg_parser/include/tplg_parser/topology.h, tools/tplg_parser/tplg_parser.c
This patch adds check for sane num_elems value. If the calculated
array size exceeds the value size and error is returned and topology
parsing is aborted.
=> Testbench: Check num_elems in tokens parsing

tools/logger/logger.c
Help message, near -g flags looks like:
```
sof-logger:      -f precision           Set timestamp precision
sof-logger:      -g             Hide timestamp
sof-logger:      -d *.ldc_file          Dump ldc_file information
```
before changes, and after apply this patch, descriptions are aligned.
=> logger: Align g flag description in help message

tools/topology/sof-byt-codec.m4, tools/topology/sof-cht-nocodec.m4
Somehow a 10ms buffer for the deep-buffer pipe generates write errors
on the kernel side with S24 and S32_LE.
Reducing the memory footprint seems to fix the problem.
This may hide a more fundamental problem with either scheduling or
memory allocation, but for now let's solve CI and daily tests.
BugLink: https://github.com/thesofproject/sof/issues/3171
=> topology: bytcht: reduce deep-buffer to 5ms

src/schedule/ll_schedule.c
Value for 'num_clients' has to be set, otherwise it may
have undefined value in later ifs.
Issue reported by KW that `if (!num_clients)` may use uninitialized value.
=> ll: set initial value for num_clients

tools/tplg_parser/tplg_parser.c
Before accessing the contents of the parameter pointer of the
function, check if the pointer is NULL. Else, it may lead to
segmentation fault.
This error was found when fuzzing testbench with AFL fuzzer.
=> tools: tplg_parser: check if parameter is valid before using it

src/audio/smart_amp_test.c
Fix GGC warning on aligned packed data.
Fixes #3244
=> smart amp: fix alignment warning of data passesed in

src/trace/trace.c
For trace message with LOG_LEVEL_CRITICAL, we should always show
them into mailbox.
Fix https://github.com/thesofproject/sof/issues/3265
=> trace: fix error trace missing issue

tools/test/topology/test-playback.m4, tools/test/topology/tplg-build.sh, tools/testbench/include/testbench/common_test.h, tools/testbench/testbench.c, tools/testbench/topology.c, tools/tplg_parser/tplg_parser.c
**Note:** this patch is currently followed on top of crossover component PR: #2802
This patch supports testbench playback testing for single-input-multi-output component, e.g. crossover. Test playback m4 file (tools/test/topology/test-playback.m4) is extended to generate up to 4 output pipelines test topologies, where argument "TEST_PIPE_AMOUNT" is provided for identifying the number of pipelines.
While building test topologies, 2way, 3way, and 4way crossover playback topology files will be generated under build_tools/test/topology/ with names as follows:
`test-playback-ssp5-mclk-0-I2S-2way-crossover-s16le-s16le-48k-24576k-codec.*`
`test-playback-ssp5-mclk-0-I2S-3way-crossover-s16le-s16le-48k-24576k-codec.*`
`test-playback-ssp5-mclk-0-I2S-4way-crossover-s16le-s16le-48k-24576k-codec.*`
and …
=> tools: Support multi-output component playback testing on testbench

src/audio/asrc/asrc.c
This patch fixes the regression that happened in a previous fix
for stress test gitches issue. Since the passed 7th argument
(write_index) was set to output frames limit the ASRC copy()
terminated too early when converting from higher to lower sample
rate. It has caused issues at least in sof-diagnostic-driver based
validation for capture direction.
Fixes: f63adb42d93521b0bb25c670fd457122857badef
=> Audio: ASRC: Fix pull mode copy frames consume limit

src/audio/pipeline.c
This commit allows propagating pipeline reset to adjacent pipelines
assuming that they have the same schedule component.
fixes #3096 
=> pipeline: change pipe reset propagation condition

src/drivers/intel/ssp/mn.c
In order to get SHARED_DATA we should not use cache_to_uncache
macro directly, but platform_shared_get() function. Otherwise,
it can lead to situation, in which in one section there will
be cached and uncached variables not aligned to cache line
(as a result cache invalidation and writebacks could lead to
unexpexted memory overwrite).
=> mn: get mn struct pointer using platform_shared_get() function

src/include/sof/debug/panic.h
Use the zephyr issue/panic reporting APIs when Zephyr RTOS is used.
=> zephyr: panic: use zephyr panic APIs when Zephyr is enabled.

tools/testbench/topology.c
When the realloc() function fails, a NULL pointer is returned. But,
if the size argument is zero, then also NULL is returned. So, to
differentiate that, we also check if size is non zero. Only if
pointer is NULL and size is non-zero, we come to the conclusion that
realloc() failed and the allocated memory till now is freed and
appropriate error is returned.
This error was found when fuzzing the testbench code using AFL.
=> tools: testbench:add null pointer variable check before accessing it

scripts/docker_build/sof_builder/Dockerfile
Bump GCC to 9.3 and Keep ALSA source in the container to permit ALSA development.
@xiulipan I think I screwed up my container when testing this, I can build it manually but not with the build script (maybe I need to force clean it?) Can you check. Thanks.
=> docker GCC and ALSA updates

src/platform/imx8/include/platform/platform.h
This patch adds logic for the platform_panic() function, called in case
of a DSP Oops.
This is important because it add a panic code in the debug box so the
application processor can understand why the Oops happened. Also in
notifies the application processor about the Oops generating an interrupt.
Signed-off-by: Iulian Olaru <iulianolaru249@yahoo.com>
=> platform: imx: Implement panic routine

src/audio/asrc/asrc_farrow.c, src/include/sof/audio/asrc/asrc_farrow.h
This pull request consists of two commits, see invidual descriptions
- Fix for illegal and failed pointer arithmetic
- Improve error codes enums documentation readability with longer lines
=> Audio: Fix pointer arithmetic mistake in ASRC initialize

src/include/kernel/ext_manifest.h, src/init/ext_manifest.c
This information known at build time does not need to be
provided in a mailbox.
=> ext_manifest: Add sof_ipc_user_abi_version content

src/lib/agent.c, src/platform/Kconfig
System agent as a debug feature has very strict timing verification,
if the timing is not met it will result in a panic.
Such drastic measures are not suitable for release builds,
as a single scheduling delay has the potential to render the DSP FW
completely dead until reboot, due to lack of a FW recovery mechanism.
=> config: disable sa panic by default

src/drivers/dw/dma.c
Usually this error has no run-time effect, so this fix is mostly
theoretical.
=> zephyr: dw-dma: fix a copy-paste error

src/lib/lib.c
=> zephyr: lib: memcpy should use zephyr version.

tools/topology/sof-apl-pcm512x.m4
The conditional definition in sof-apl-pcm512x.m4 is supposed to
select the DMA scheduler if the codec is the bclk source and the
timer scheduler otherwise, but the conditional definition is
broken which leads to the DMA scheduler being selected always.
Fix the definition.
This fixes https://github.com/thesofproject/sof/issues/3256 but only when the PCM512x codec is the bclk slave. More work is needed to also fix the codec-master configuration.
=> topology: apl-pcm512x: fix scheduler domain

src/ipc/handler.c
Dont use the SOF API's, use Zephyr APIs when ready.
=> zephyr: ipc: handler: dont use SOF APIs for D3 entry

tools/test/topology/test-all.m4, tools/test/topology/test-capture.m4, tools/test/topology/test-playback.m4, tools/topology/m4/asrc.m4, tools/topology/m4/ch_sel.m4, tools/topology/m4/dai.m4, tools/topology/m4/dcblock.m4, tools/topology/m4/detect.m4, tools/topology/m4/eq_fir.m4, tools/topology/m4/eq_iir.m4, tools/topology/m4/kpbm.m4, tools/topology/m4/mixer.m4, tools/topology/m4/muxdemux.m4, tools/topology/m4/pcm.m4, tools/topology/m4/pga.m4, tools/topology/m4/smart_amp.m4, tools/topology/m4/src.m4, tools/topology/m4/tone.m4, tools/topology/m4/utils.m4, tools/topology/sof/tokens.m4
This is the series for UUID support -- tplg part, it should be used together with the FW part and kernel part.
=> UUID tplg support

src/include/sof/schedule/task.h, src/schedule/timer_domain.c
Create a high priority zephyr work Q on each core for LL timer domain
tasks. This cannot be prempted by other tasks.
=> zephyr: ll scheduler: run ll scheduler as Zephyr work Q

zephyr/CMakeLists.txt, zephyr/edf_schedule.c, zephyr/include/sof/atomic.h, zephyr/include/sof/trace/trace.h, zephyr/schedule.c, zephyr/wrapper.c
This patch finalises the wrapper to allow LL scheduling of
timer domain audio, EDF sccheduling of IPC, trace re-direction
and kconfig build support.
There are still many items that are WIP and have been marked with
TODO: comments.
=> zephyr: wrapper: complete zephyr support for working audio

tools/testbench/topology.c, tools/tplg_parser/include/tplg_parser/topology.h, tools/tplg_parser/tplg_parser.c
This patch uses the functionality added by the c9e090c commit
to check for array size mismatch in various components.
Not doing so may result in cases, where we try to write into the
space not allocated leading to segmentation fault.
=> testbench: topology: check array size mismatch in various components

src/audio/host.c
After commit 048145fe6006f8 ("pipeline: remove code related to preload")
buffers are no longer preloaded so we don't need to manually
update first period transfer.
Taking playback as an example, without this patch first period bytes
weren't copied downstream to DAIs removing typically first 0.1 seconds
from the input file.
With PCM streams this is not really noticeable. Anyhow, this becomes
a problem with compressed streams where we need every byte for
decompression.
=> [PATCH RFC] host: Fix first period not being copied to/from host

scripts/cmake/version.cmake
GIT_LOG_HASH can be more than 8 digits. Limit hash value up to
first 8 digits.
fixes: #3322
=> cmake: set git hash to 8 digit

zephyr/CMakeLists.txt
Git hashes need exported for Zephyr build.
=> zephyr: fix build for new sof git hashes.

src/include/sof/schedule/ll_schedule_domain.h, src/schedule/dma_multi_chan_domain.c, src/schedule/dma_single_chan_domain.c, src/schedule/ll_schedule.c, src/schedule/timer_domain.c
When streaming audio data on multiple DMA channels simultaneously cases
with 3 tasks (A, B, and C), scheduled on 2 DMA channels (X and Y), have
been observed, when one of the tasks wasn't scheduled. Usually when
scanning tasks in schedule_ll_is_pending() the following sequence would
take place:
channel    task    interrupt status
X          A       1
X          B       1
Y          C       1
where the interrupt would be cleared in lines 2 and 3 above. However,
sometimes the following sequence takes place:
channel    task    interrupt status
X          A       0
X          B       1
Y          C       1
which then leaves task A not scheduled, because similar to the first case,
the interrupt on channel X will be cleared in line 2. To fix this modify
schedule_ll_is_pending() to handle DMA …
=> schedule: dma_multi_chan: fix a DMA channel interrupt race

tools/logger/CMakeLists.txt, tools/logger/convert.c, tools/logger/convert.h, tools/logger/filter.c, tools/logger/filter.h, tools/logger/logger.c, tools/logger/misc.c, tools/logger/misc.h
Why:
To improve debugging process.
How:
Config file with list of new trace level for particular UUID components will be translated and send to FW in runtime (logger->driver->IPC->FW). In FW current log level threshold should be overwritten with value from IPC message. Config file is given as logger runtime argument.
Implements:
https://github.com/thesofproject/sof/issues/2172
=> Add logger runtime trace level change possibility

tools/testbench/testbench.c
If user fails to provide a topology file, the tplg_file member
of structure tp is left uninitialized. This member is used to
check again if the file was provided, which won't be possible
unless this has been initialized to NULL and checked for NULL
after parsing arguments.
=> tools: testbench: initialize local variable before accessing it

src/platform/baytrail/platform.c
Using the same hardware timer for both "cpu_timer" and
"platform_timer" doesn't work, switch the "cpu_timer" to use
TIMER1 on Baytrail. This also fixes performance counters on
the platform.
Fixes #3274
=> byt: use an internal timer for "cpu_timer"

src/audio/asrc/asrc.c, src/audio/dcblock/dcblock.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/mixer.c, src/audio/selector/selector.c, src/audio/src/src.c, tools/topology/sof-cht-max98090.m4
Kernel CI reports issues with S24/S32_LE support [1], since we don't have a good solution for now limit the format to S16_LE. This error was always present but was only caught by a new test added a bit prematurely to the CI list.
We definitively want the code to support these two cases but if CI keeps complaining it makes the job of maintainers more complicated than it needs to be.
[1] https://sof-ci.01.org/softestpr/PR349/build106/devicetest/
=> BSW_MAX98090 (Cyan) temporary fix

src/audio/volume/volume.c
If in a topology the volume component ramp length (milliseconds) and
from it derived ramp update period is longer than pipeline copy()
schedule period the dev->frames (frames to process per per period) is
divided by zero. This error is not triggered by any of current
topologies.
The fix is to use dev->frames count as gain ramp update rate for
situations where the integer divider would round to zero. There is no
harm to update the gain at higher rate than suggested by topology.
Returning an error for such topologies also is not necessary since the
service is in such case done at better quality than requested. Finer
update grid results to less zipper noise.
Fixes commit 1b57609a1ef9 ("volume: do not schedule ramping as separate task")
Fixes #3334
Signed-off-by: Seppo Ingalsuo …
=> Audio: Volume: Avoid possible divide by zero trap

src/arch/xtensa/lib/cpu.c, src/platform/intel/cavs/include/cavs/lib/pm_runtime.h, src/platform/intel/cavs/lib/clk.c, src/platform/intel/cavs/lib/pm_runtime.c, src/platform/intel/cavs/platform.c
This will will save a lot of time if quick changes are needed
=> tgl: iccmax use pm_runtime core power up instead of full init

src/include/kernel/tokens.h, tools/ctl/ctl.c, tools/topology/get_abi.sh, tools/topology/m4/bytecontrol.m4, tools/topology/sof/pipe-smart-amplifier-playback.m4
This patch set creates a Read only byte kcontrol with access type as read & volatile. Reading values from DSM audio component is very important for speaker calibration & diagnosis.Temperature, DC resistance, Fc and Q of the speaker are always changing, and every speaker has its own unique value. DSM requires Rdc calibration for each speaker in the factory line to match speaker coil resistance with actual ambient temperature. Customer also monitors above speaker parameters to make sure if there is any temperature/excursion violation. This mandates the need for a kcontrol interface to read the "actual" data from DSP. Today we already have the read/write kcontrol, where read always returns the cached data, that was set during write, as the kcontrol read need not wake up DSP everytime. But …
=> Read only byte kcontrol with access type as read & volatile

src/lib/CMakeLists.txt, tools/testbench/common_test.c
This patch fixes a segfault with null sof->sa pointer in
pipeline_schedule_copy() function. The bug has not been observed
with test topologies for processing pipelines but with other
topologies with fuzzer varied parameters.
The sa_init() is added to tb_pipeline_setup(). The scheduler_init_edf()
is a dependency. The two dummy functions platform_timer_get() and
clock_ms_to_ticks() are also added as dependency. The CMakelist for
library is edited to include agent.c build for testbench.
Fixes #3247
=> Tools: Testbench: Add system agent initialization

src/trace/dma-trace.c
This log should be added just after buffer initialization,
to make it the first one in the output file - for easy identyfication.
=> trace: Move FW description log location

src/audio/pcm_converter/pcm_converter_hifi3.c
Module is expensive operation, so usage them in processing code
should be reduced.
Issue found in https://github.com/thesofproject/sof/pull/3251
=> pcm_converter: Reduce modulo operations

scripts/rebuild-testbench.sh
Currently, the testbench is built using the script named
'host-build-all.sh' under scripts directory. But the name of
the script, it's git history doesn't refer to what the script
is currently doing now.
The newly written script adds option to build the testbench.
This script was written in mind to remove the old script
used to build the testbench (i.e host-build-all.sh).
The script also adds an option to build the testbench with
AFL instrumentation. AFL fuzzer works well when the code
it's trying to fuzz is instrumented properly. The instrumentation
helps the fuzzer in generating unique inputs which cover
different paths in the code graph. When the option is set,
testbench is built using a compiler AFL provides, which does
the instrumentation work.
Signed-off-by: Mohana Datta Yelugoti …
=> scripts: Add a new script to rebuild testbench

src/audio/smart_amp_test.c
Kcontrol interface is needed to set the smart_amplifier algorithm
parameters at runtime for tuning purpose. This patch allows the
user to set parameters using byte kcontrol.
Signed-off-by: Dharageswari R <dharageswari.r@intel.com>
=> topology: Allow set parameters at runtime in smart_amplifier component

src/platform/Kconfig
TGL have hardware requirement that DSP should use LPRO as clock source in waiti.
=> kconfig: select CAVS_USE_LPRO_IN_WAITI for TGL

tools/fuzzer/CMakeLists.txt
This patch removes the incorrect usage of BUILD_COMMAND. Having it set
to "cmake" caused the cmake usage help text output to be shown only and
caused the ExternalProject_Add command to believe the
libsof_tplg_parser.so was built. The build for the library happened only
because the next install step performed the compilation. With this fix
the default build command is used instead. There's no need to define
it here.
Fixes #2656
=> Tools: Fuzzer: Do not use illegal BUILD_COMMAND in CMakeLists.txt

src/audio/dai.c, src/audio/host.c, src/audio/pcm_converter/pcm_converter.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/include/sof/audio/audio_stream.h, src/include/sof/audio/pcm_converter.h, src/include/sof/lib/dma.h, src/lib/dma.c
Assertion may be replaced with error code return, then error won't be so fatal and error log may be traced in client component context.
=> Pcm converter: return error code

scripts/build-tools.sh
2 commits
Seriously, use shellcheck.
The only reason it's not in this travis yet is because I hate copy/paste
https://github.com/marc-hb/sof-test/commit/faadb20a854834
=> build-tools.sh: fix wrong variable names as reported by shellcheck

tools/logger/convert.c, tools/logger/convert.h, tools/logger/filter.c, tools/logger/filter.h, tools/logger/misc.c, tools/logger/misc.h
Most functions in logger depend on values stored in conver_config struct
which are passed to almost all function calls. This patch moves pointer
to the config to global context and allows each function to derive
necessary values from there. This reduces needless parameters passed
to function calls and allows for more flexible access to data in nested
functions.
=> logger: Create global convert_config variable to avoid spaghetti code.

src/audio/dai.c, src/include/ipc/dai.h, src/include/sof/lib/dai.h, src/include/sof/lib/notifier.h, src/lib/dai.c
This change adds support for atomic trigger operations,
by grouping DAIs together with a common 'group_id' in
the configuration of each DAI.
When DAIs are in the same group and in the same DSP core,
they will process triggers atomically, i.e. wait for all
the other DAIs to receive the trigger command and pospone
the final, actual trigger operation.
=> dai: atomic trigger operations

scripts/host-testbench.sh, scripts/rebuild-testbench.sh
2 commits, see commit messages
Default is verbose enough. VERBOSE=1 can still be used later at make
time.
Also change nproc to nproc --all because we don't care about offline
processors.
=> rebuild-testbench.sh: remove CMAKE_VERBOSE_MAKEFILE

src/audio/smart_amp_test.c, src/include/sof/audio/component.h
This commit adds comp_get_status() helper function, which
takes two arguments: requesting component and component from
which user wants to read status. In case when both components
are on the different cores function additionally invokes
comp_invalidate().
This commit also fixes issue in smart_amp_copy() function, where
we always invoke comp_invalidate(sad->feedback_buf->source) whether
or not both components (smart amp and sad->feedback_buf->source)
are on different cores. In case when both components are on
the same core, we can invalidate data not previously writebacked.
=> comp: add comp_get_status() helper function

src/audio/smart_amp/smart_amp.c
Updated new UUID for the Maxim DSM component.
New component UUID : 0cd84e80-ebd3-11ea-adc1-0242ac120002
DSM component used same UUID with smart amp test component and now assign unique ID for the DSM Component.
Signed-off-by: Ryan Lee <ryans.lee@maximintegrated.com>
=> smart amp: modified UUID for the Maxim DSM component

src/platform/intel/cavs/include/cavs/lib/memory.h, src/platform/intel/cavs/lib/pm_runtime.c
temporary stubs for features, missing in Zephyr
=> Zephyr tmp

CODEOWNERS
@tlauda is no longer a maintainer in SOF project.
=> github: remove @tlauda from CODEOWNERS

src/lib/dai.c
=> dai: fix an uninitialized variable

src/audio/component.c, src/audio/detect_test.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/smart_amp/smart_amp.c, src/audio/smart_amp_test.c, src/include/sof/audio/component.h, src/include/sof/audio/smart_amp_test.h
This PR refines component model functions in order to allow
component reconfiguration during the streaming (implementation
is based on equalizer set and get methods).
=> comp: update model functions with more generic implementation

test/cmocka/src/audio/buffer/buffer_wrap.c, test/cmocka/src/audio/mux/demux_copy.c, test/cmocka/src/audio/mux/mux_copy.c, test/cmocka/src/audio/mux/mux_get_processing_function.c, test/cmocka/src/audio/selector/CMakeLists.txt, test/cmocka/src/audio/selector/selector_test.c, test/cmocka/src/audio/volume/CMakeLists.txt, test/cmocka/src/audio/volume/volume_process.c, test/cmocka/src/util.h
Currently unit tests utilize mock-up comp_buffer/audio_stream implementations, which would introduce overhead in upcoming buffer implementation changes, and are also obsolete in the tests themselves.
In this PR I've replaced mocked-up implementations in Volume and Selector unit tests with actual comp_buffer implementation.
Also Buffer UTs were modified to read/write byte by byte, to better imitate actual component behaviour.
=> test: Replace mockup buffer implementations with real ones.

tools/topology/m4/smart_amp.m4, tools/topology/sof-tgl-max98373-rt5682.m4, tools/topology/sof/pipe-smart-amplifier-playback.m4
This patch set adds the uuid argument to smart_amp widget, uuid parameter can be configured by the topology files while integrating any new component. If not configured, uuid will be assigned with the UUID of the smart_amp_test component as default value.
It also includes the changes to sof-tgl-max98373-rt5682, to add the UUID of Maxim DSM component
=>  Pass uuid token to the smart_amp widget

src/drivers/imx/sai.c, src/drivers/imx/sdma.c
Issue was that multiple consecutive playbacks would bring us in a weird state where the second/third/etc playback wouldn't actually consume data (no DMA interrupts)
These fixes both contribute to work around the state left after the first stop, so the second playback would start on a clean slate.
The root cause that was fixed by the patch "drivers: imx: sai: Add a small amount of silence on start trigger" was that the SAI would send no further DMA requests if it has already sent one and it isn't satisfied. The other patch improves the handling of hardware event triggers (DMA request based trigger) as well as that of SDMA buffer descriptors (now two descriptors ahead of the current one have the DONE bit set instead of just one, to counter for the fact that it is possible that the DMA might …
=> Fix playback issue on i.MX8MP

src/audio/pipeline.c, src/include/sof/audio/buffer.h
pipeline: add negotiation before propagating params
For different connected pipelines, they are usually connected via a
component with >1 source or sink buffers, as most of those components
don't have ability to converse frame format or sample rate, we need add
a params negotiation mechanism between those pipelines.
If all buffers are iterated in the params propagation direction, no
negotiation needed, otherwise we need to iterate all other buffers in
the opposite direction, to make sure all connected buffers have chance
to take part in the negotiation.
The negotiation should happen before we can propagate the params
further, when doing negotiation in a branch/buffer, we should check:
If a branch is active, check if params is matched, return error to
reject the whole .params() requirement …
=> pipeline param negotiation

src/platform/intel/cavs/include/cavs/lib/memory.h
Disable use of uncache region on Zephyr until it's ready.
=> zephyr: dont use uncache region for zephyr yet

scripts/build-tools.sh, tools/CMakeLists.txt
To produce the exact same binaries than before this commit:
```
CMAKE_BUILD_TYPE='  ' ./scripts/build-tools.sh
```
To observe which CFLAGS are being used:
```
CMAKE_BUILD_TYPE=Release VERBOSE=1 ./scripts/build-tools.sh
```
Off topic: the logger fails to build with: `-O3 -DNDEBUG -Wall -Werror`
(all other tools build fine with these flags)
=> tools: support standard CMAKE_BUILD_TYPE and default to Debug

tools/logger/convert.c, tools/logger/logger.c, tools/logger/misc.h
Failing silently is not nice. Now prints instead:
```
TIMESTAMP   DELTA C# COMPONENT   LOCATION   CONTENT
error: in logger_read(), fread(..., /sys/kernel/debug/sof/etrace) \
failed: Invalid argument(22)
```
Also make logger_read() and the process return [-]errno which can have
different values and some information instead of -ferror() which has
only one value (non-zero in theory, 1 in practice) hence no information.
=> logger: add error message when reading sof/etrace instead of sof/trace

src/audio/smart_amp/dsm_api/inc/dsm_api_public.h, src/audio/smart_amp/smart_amp.c, src/audio/smart_amp/smart_amp_maxim_dsm.c, src/include/sof/audio/smart_amp/smart_amp.h
Added functions to read/write DSM parameters.
Removed component model data handler and related code
by next reason.
- The size of DSM tuning bin file is always smaller than
the size of actual parameter structure. The bin file do not
include parameter values if it is same to library default to
keep minimum binary size. The size of bin file is variable.
Read size was limited to the bin size before modification.
- Support parameter read even bin data is not set.
Model data buffer was allocated only when bin data is set
before modification.
Signed-off-by: Ryan Lee <ryans.lee@maximintegrated.com>
=> smart amp: support parameter read/write

src/include/ipc/info.h, src/include/ipc/topology.h, src/include/kernel/ext_manifest.h
Add a "ABImajor.minor" note to inline documentation of all
ABI interfaces that have been added or modified as part of
3.17 interface changes.
This is patch serves as an example for proposed new policy on this topic, making the annotations mandatory for any new change:
https://github.com/thesofproject/sof-docs/pull/283
=> doc: annotate all ABI fields added/changed in 3.17 ABI

src/audio/smart_amp_test.c
In order to allow stream different audio formats,
the hardcodec frame fmt value should be removed.
=> smart_amp: remove hardcoded frame_fmt value

src/audio/host.c, src/audio/kpb.c, src/audio/smart_amp/smart_amp.c, src/audio/smart_amp/smart_amp_maxim_dsm.c, src/drivers/imx/interrupt.c, src/include/sof/trace/preproc-private.h, src/include/sof/trace/preproc.h, src/include/sof/trace/trace.h, src/lib/agent.c, src/lib/alloc.c, src/lib/dma.c, src/schedule/dma_single_chan_domain.c, src/schedule/ll_schedule.c, src/schedule/timer_domain.c
Extracted from https://github.com/thesofproject/sof/pull/3376.
Here META_MAP functionality has been used, so it's more flexible solution in case of `_TRACE_EVENT_MAX_ARGUMENT_COUNT` change.
=> trace: verify argument size

src/include/sof/lib/dai.h, src/include/sof/lib/uuid.h, src/include/sof/schedule/edf_schedule.h, src/include/sof/schedule/ll_schedule.h, src/include/sof/schedule/schedule.h, src/include/sof/schedule/task.h, src/include/sof/trace/trace.h, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, src/schedule/schedule.c, src/trace/trace.c, test/cmocka/src/audio/pipeline/pipeline_mocks.c, tools/testbench/edf_schedule.c, tools/testbench/ll_schedule.c, tools/testbench/schedule.c, zephyr/edf_schedule.c
UUID objects are represented by struct sof_uuid_entry instances in SOF. Instead of casting pointers to them to integers for passing around, carry them as pointers until they have to be cast to integers for packing into data structures. This also fixes printing UUID, using a "%pU" format.
with this patch, applied together with all other zephyr upstreaming patches, I can actually build zephyr+sof with no warnings
=> uuid: use a pointer instead of casting it to an integer

zephyr/CMakeLists.txt
Two recent commits moved and renamed some of eq-iir and eq-fir files,
without updating zephyr cmake files.
fixes ab4a608198dc ("Audio: Move FIR core to math library")
fixes baa43558f663 ("sof: math: move iir_df2t function to src/math")
=> zephyr: fix iir and fir file renaming

test/cmocka/src/audio/pcm_converter/CMakeLists.txt, test/cmocka/src/audio/pcm_converter/pcm_float.c, test/cmocka/src/util.h
Currently pcm converter unit tests use mocked-up audio_stream
implementation which should be replaced with real FW implementation.
=> test: pcm converter: Utilize comp_buffer implementation instead of mocking

tools/logger/convert.c, tools/logger/filter.c
3 commits, see commit messages below.
~All~ 2 out the 3 warnings fixed by this are shown in https://travis-ci.org/github/thesofproject/sof/jobs/727258703 (for other PR #3411 )
After this,  `CMAKE_BUILD_TYPE=Release ./build-tools.sh` builds everything successfully.
=> logger: fix CMAKE_BUILD_TYPE=Release build

tools/logger/logger.c
For first run, allocated memory pointer has been written twice to
config->filter_config but freed only once - memory leak.
=> logger: Fix memory leak at first filter append

tools/topology/CMakeLists.txt
Changed the tplg file name in kernel driver according to Maintainers
feedback. So, topology file name here needs the corresponding change.
As part of the below PR, Pierre suggested us to change the name:
https://github.com/thesofproject/linux/pull/2345
=> topology: Update tplg file name for tgl system with max98373-rt5682

.travis.yml, scripts/docker-run.sh
For some reason gcc prints more warnings this way and of course CI is
meant to catch warnings as soon as possible.
=> travis: run build-tools.sh with CMAKE_BUILD_TYPE=Release

.travis.yml
Sue Creek support was never completed, stop building it as it may give a
wrong impression.
=> travis: remove sue creek

scripts/build-tools.sh
This gets rid of about 600 lines of noisy "Entering directory..."
messages which cuts the size of the output of the script in half leaving
only useful stuff on the screen. This (and other changes before it) may
finally avoid bugs like 'commit f430addec752 ("Tools: Fuzzer: Do not use
illegal BUILD_COMMAND in CMakeLists.txt") evading scrutiny for months.
After so many years enjoying the convenience of make's '-C' option, I
finally did some research and realized it is the cause of this very
serious noise issue with no other easy way out :-(
=> build-tools.sh: remove all the "Entering directory..." noise

src/include/sof/audio/kpb.h
Due to memory constraints, the keyphrase buffer cannot be too long.
As a consequence of reducing the buffer,
platform wakeup margin check has to be removed as well,
otherwise the maximum draining request will be very short.
This is a temporary measure,
ultimately the buffer length and wakeup time settings
should be moved to the topology.
=> kpb: reduce buffer length on non-TGL platforms

tools/topology/platform/intel/intel-generic-dmic-kwd.m4
KWD pipeline only supports S16_LE and S24_LE formats, S32_LE also
need to be included.
=> topology: add s32_le format support to kwd pipeline

.travis.yml
travis: remove duplicate and deprecated host-build-all.sh
We already build _and_ run the testbench in the next stage, with the
newer script. No need to build the same thing twice.
=> travis: remove duplicate and deprecated host-build-all.sh

src/arch/xtensa/CMakeLists.txt
This allow to add new platform with old version of rimage tool.
Test for https://github.com/thesofproject/rimage/pull/21
Linked to private rimage repo for testing purpose.
=> rimage: Update to version with toml devices description

src/audio/dai.c
This patch logs warning message when we skip dai .copy() method.
Also the condition has been changed, there is no need to compare
positions - if there is nothing to copy we should terminate this
procedure regardless of positions.
=> dai: add warning when we skip .copy

CODEOWNERS
Fixes commit f545e3e832ec ("dmic: move dmic driver out of the cavs
specific directory")'
=> CODEOWNERS: fix path to dmic.

CODEOWNERS
Fixes commit 757b13c123b1 ("CODEOWNERS: scripts/ += marc-hb")
Also add *.bash which we don't use yet but should considering how
not portable is the vast majority of our scripts.
=> CODEOWNERS: really add marc-hb to scripts

tools/topology/development/sof-tgl-nocodec-ci.m4
We can't test KWD on nocodec machines due to the DAPM issues reported
here: https://github.com/thesofproject/linux/issues/1987
Remove KWD pipelines from sof-tgl-nocodec-ci to avoid performing invalid
test on it.
=> topology: sof-tgl-nocodec-ci: remove KWD pipelines as not available

tools/topology/sof-jsl-rt5682.m4
The patch fixes two SSP pipelines to be scheduled in timer domain.
=> topology: fix playback & capture pipelines to be timer driven

src/audio/volume/volume.c
The volume component works correct when all channels receive the same
gain value in volume set command.
This patch fixes a bug that is triggered by applying different
gain values for the channels. The logic with setting cd->ramp_finished
to true caused the check in volume copy() to no more call volume_ramp()
when one of the channel reached their target volume. When the ramp
updating was stopped all other channels remain in intermediate gain
value.
In the fix the logic is set to opposite. Whenever a channel needs a ramp
update it sets a temporary flag. The ramp finish is set only when
no channels needed gain update.
Fixes #3455
=> Audio: Continue volume ramp until all channels are complete

src/drivers/imx/esai.c, src/drivers/imx/sai.c, src/drivers/intel/baytrail/ssp.c, src/drivers/intel/haswell/ssp.c, src/drivers/intel/ssp/mn.c, src/drivers/intel/ssp/ssp.c, src/include/ipc/dai.h, src/include/sof/drivers/mn.h, src/include/sof/drivers/sai.h
The consensus in Linux/ALSA circles is to use clock provider/consumer, instead of the legacy master/slave.
This PR mirrors this consensus and follows the work already done for DSP cores in https://github.com/thesofproject/sof/pull/3381
There should be no functional changes, if there is one it's an error.
=> [RFC] Use inclusive language for DAI

src/audio/pipeline.c
Use current->pipeline instead of ppl_data->p as a
pipe_dbg() and pipe_err() arguments. ppl_data->p
is not set at that point and can cause unexpected
errors.
=> pipeline: fix logs in pipeline_comp_params_neg()

src/platform/intel/cavs/ext_manifest.c
Config name is CONFIG_CAVS_LPRO_ONLY.
There was a problem, CONFIG_LPRO information is not read from linux driver.
=> ext_manifest: fix config name to LPRO_ONLY for cavs

scripts/docker-run.sh
Pass PRIVATE_KEY_OPTION environment variable to docker to be able to
define external key for signing.
Suggested-by: Marc Herbert <marc.herbert@intel.com>
=> docker-run.sh: pass-through PRIVATE_KEY_OPTION

src/audio/pipeline.c
In case of changing specific values in buffer structure,
we should use buffer locks an unlocks macros in order
to retain multicore coherence.
fixes #3429
=> pipeline: add missing buffer locks/unlocks

tools/logger/convert.c
fread may return 0 when some error occurred or nothig has been reded.
Fixes: 337afc4f3809: ("logger: add error message when reading sof/etrace instead of sof/trace")
=> logger: Log fread error only when it happened

src/arch/host/CMakeLists.txt, src/audio/CMakeLists.txt, tools/testbench/CMakeLists.txt, tools/tplg_parser/CMakeLists.txt
We need clang support for the testbench therefore the following changes
are needed
remove -ftree-vectorizer-verbose when building with clang
remove =3 from -Wimplicit-fallthrough=3 since 3 is the default level
anyways
=> cmake: allow testbench to build with clang

src/platform/apollolake/apollolake.x.in, src/platform/cannonlake/cannonlake.x.in, src/platform/icelake/icelake.x.in, src/platform/suecreek/suecreek.x.in, src/platform/tigerlake/tigerlake.x.in
This patch will allow to keep cavs-specific elements
=> ext_man: prevent removal of cavs-specific element

scripts/cmake/git-submodules.cmake
As incredible as it sounds, some people run neither "git status" nor
"git diff" every few minutes and not even when their build fails. There
has been reports that they're puzzled when they miss a required
submodule update. This is an attempt to draw their attention based on
the assumption that they pay more attention to the CMake logs.
=> cmake: add warning when git submodule changes are found

tools/sof_ri_info/sof_ri_info.py
Add jsl entry to DSP_MEM_SPACE_EXT[].
=> tools: sof-ri-info: define memory layout for JSL platform

tools/topology/CMakeLists.txt, tools/topology/sof-tgl-rt715-rt711-rt1308-hdmi.m4
Add tgl rt715-rt711-rt1308 support. But keep the PCM order as
Headphone, Headset mic, Speakers, Microphones.
=> topoplgy: add tgl rt715-rt711-rt1308 support

tools/test/audio/std_utils/level_dbfs.m
The log() function returns -Inf for level measure for stream of
digital zeros. It is correct but requires extra handling in the
upper level functions to avoid unnecessary tests fails. Adding of
offset 1e-20 results to -196.99 dBFS be the smallest possible
reported value. The function remains sufficient for all audio
measurements with 16 - 32 bit formats.
The license text is also updated to current version.
=> Tools: Test: Fix for dBFS level measure for muted audio

src/trace/trace.c
Commit 0e1176d9434a ("trace: Update trace level after ipc message")
broke building under Zephyr. Fix the breakage by effectively disabling
functionality, to be properly fixed later.
=> zephyr: fix build after a recent trace filter PR

src/schedule/timer_domain.c, zephyr/wrapper.c
Fixes corrupted HDMI audio with underruns on Up2 with Zephyr
=> Zephyr sched

tools/logger/convert.c
'p + 2' should be smaller than end pointer, bigger value may leads
to undefined memory region read.
Memmove should include last '\0' char.
Without this fix output looks like:
`task add 0xbe070600 pipe-task 0x1fffa0f0U`
After changes:
`task add 0xbe070600 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3>`
Fixes: 12f2d9b2c822 logger: Refactor UUID parsing
Related with #3472
=> logger: Fix uuid formatting

src/arch/xtensa/drivers/timer.c
This commit adds check whether timer handler is set
in order to avoid unexpected errors.
=> timer: check whether handler is set before its invocation

src/drivers/intel/ssp/ssp.c, src/include/sof/drivers/ssp.h
To make sure all the RX FIFO entries are read out for the flushing, we
need wait until the SSSR_RNE is cleared after the SSP is disabled (the
SSSR_BSY is cleared, otherwise, there might be obsoleted entry remained
in the FIFO which will impact the next run with the SSP RX and lead to
sample mismatched issue.
BugLink: https://github.com/thesofproject/sof/issues/3428
Cc: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>
=> ssp: fix the RX FIFO flushing logic

src/audio/dai.c
DMA should be loaded at least with data for one period
otherwise glitches are supposed to appear. Such a kind of
problem is quite difficult to track, because it may be related
with scheduling in runtime, DSP load, or used buffers size,
so log message pointing possible source of glitch is useful.
=> dai: Add warning about possible glitch

tools/test/audio/test_utils/multitone.m
The generation of multiple tone frequencies failed due accidental
square matrix generation when mixed row and column vectors were added.
The new version uses only vectors in first dimension and avoids the
problem.
The license text format also is changed to current.
=> Tools: Test: Fix for sine vector orientations mismatch

src/arch/xtensa/CMakeLists.txt
Introduced changes add extended manifest at the begin of firmware
image, as a firmware metadata description.
This PR shouldn't be merged before a flag day.
Added as PR to make it easy to cherry-pick for development purposes.
=> ext_manifest: Use ext manifest by default in output image

src/arch/xtensa/include/arch/compiler_info.h, src/init/CMakeLists.txt, src/ipc/CMakeLists.txt
Properly retrieve gcc version values and unify the optimisation flag with Zephyr to always include a '-' in the string. Before this patch the kernel reports the firmware, built with gcc as 
Firmware info: used compiler XCC 12:0:8 xtensa-cnl-elf used optimization flags O2
With this patch it reports
Firmware info: used compiler GCC 8:1:0 xtensa-cnl-elf used optimization flags -O2
=> compile: fix reporting compiler version when built with gcc

src/include/sof/lib/dai.h, src/platform/haswell/include/platform/lib/pm_runtime.h
In prepping for fuzzing I noticed some missing headers that would cause builds to fail randomly, adding them so this can be fixed.
=> Fixup missing headers

tools/topology/platform/intel/intel-generic-dmic-kwd.m4
Add DMICPROC option so that DMIC01 can use EQ IIR etc.
=> Topology: intel-generic-dmic-kwd Add DMIC PROC option

src/audio/drc/drc.c, src/audio/mux/mux.c, src/audio/tdfb/tdfb.c, src/include/sof/audio/component.h
As per component graph we start devices in INIT state. Since most
components don't use this state anyways lets just init the struct to
this state and remove it where it is used correctly.
=> component: initialize new devices to INIT state

src/trace/trace.c
Possible null pointer dereference was possible here.
=> trace: Compare pointer with NULL before use

src/arch/xtensa/drivers/timer.c
In case when new timeout requires timer rollover
we should set ccompare value to 1 in order to
increment timer->hitime properly in timer_64_handler().
=> arch_timer: check for rollover in arch_timer_set

scripts/xtensa-build-all.sh
Following commit 88b69cc2e5ca ("scripts: xtensa-build-all: Add support
for building TGL and signing with MEU") we now have an unified and
flexible PRIVATE_KEY_OPTION that can do anything with very little code.
The -k option was never a good idea in the first place because it
already required an environment variable anyway (RIMAGE_PRIVATE_KEY)
instead of a command line argument so the code should have just checked
whether RIMAGE_PRIVATE_KEY was defined, that would have been
enough. Requiring the user to "double-confirm" with -k has been adding
extra complication for both the user interface and the implementation.
xtensa-build-all is effectively a "CMake configuration convenience"
script, however it shouldn't become an additional layer of indirection
and complexity and its interface should …
=> xtensa-build-all: document PRIVATE_KEY_OPTION and deprecate -k

src/include/sof/lib/perf_cnt.h
In order to get proper perf counters peaks values
we should cast arch timer value to uint32_t.
Arch timers API allows user to get uint64_t value.
In fact arch timer consits two parts. 32 bits (MSB)
software part and 32 bits (LSB) hardware timer.
The 32 bits (MSB) software part is incremented only
during hardware timer rollover when timer interrupts
are enabled. If interrupts are not enabled (perf_cnt
case), incrementation will never appear.
=> perf_cnt: cast timer value to uint32_t type

tools/logger/misc.c
This function could fail when called before convert()
=> logger: Fix log_err usage at early stages of sof-logger run

tools/logger/logger.c
The -F filter option has argument, we should use
F: instead of F in the optstring.
Change the misleading usage info for filter.
Add format as tips for filter string.
Fix https://github.com/thesofproject/sof/issues/3530
=> Fix filter for logger

src/drivers/imx/sai.c
TE/RE bit will remain set until the end of current frame. So,
for example, even if we set TE to 0 the transmitter will still be
enabled until the end of current frame.
This can have unexpected results when quickly restarting a channel.
=> drivers: imx: sai: Make sure Tx/Rx is disabled at stop

tools/logger/logger.c
There is no place for unused arguments, their are consequence of invalid
argument list as usual.
Such an situation is highly possible especially during defining trace
filters, eg `-Fv=mux 4.1` instead `-F"v=mux 4.1"` or `-Fv=mux4.1`.
=> logger: Check for unused arguments

src/audio/smart_amp/smart_amp.c, src/audio/smart_amp/smart_amp_maxim_dsm.c
There have been several patches applied to [smart_amp_test.c](https://github.com/thesofproject/sof/blob/master/src/audio/smart_amp_test.c) which is smart amp reference code.
Applied same changes to smart_amp.c[](https://github.com/thesofproject/sof/blob/master/src/audio/smart_amp/smart_amp.c)
which is for Maxim DSM(Dynamic Speaker Management) component.
=> smart amp: Update smart amp test changes to maxim dsm component.

.gitignore
This file is generate by checkpatch run, any temporary file shouldn't
be tracked by git. It was added to git by:
538eb6a: ("host: stub about required functions")
Moreover file is problematic for developers working on Windows,
now try to pull changes from remote repository ends up with:
```
$ git pull
error: invalid path '.checkpatch-camelcase.git.'
Updating 6e85152..7709924`
```
cloning repository ends up with:
```
$ git clone https://github.com/thesofproject/sof.git
Cloning into 'sof'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 67251 (delta 49), reused 4 (delta 1), pack-reused 67154
Receiving objects: 100% (67251/67251), 13.41 MiB | 2.62 MiB/s, done.
Resolving deltas: 100% …
```
=> git: Remove temporary checkpatch file from repository

src/include/ipc/header.h, src/include/kernel/abi.h
ubsan found the following bug via oss-fuzz
/src/sof/src/ipc/handler.c:1385:9: runtime error: left shift of 15 by 28 places cannot be represented in type 'int'
This is caused by SOF_GLB_TYPE_MASK which has an implicit length of 15
(int16_t)
=> abi: fix macro size overflow

src/audio/dcblock/dcblock.c
Reset state when reset trigger happens and use memset to do it
=> dcblock: fix reset handler

src/arch/xtensa/include/arch/compiler_info.h
Previously, the __GNUC__ flag was used to differentiate between GCC and XCC.
However, that flag is defined by XCC as well,
as a result, __XCC__ flag should be checked instead.
Fixes: https://github.com/thesofproject/sof/issues/3551
=> compile: check for __XCC__ flag when defining FW build info

tools/oss-fuzz/fuzz_ipc.c
The memory sanitzer catches uninitialized value errors on the size check
for small data sizes. Therefore lets us calloc so we can assume the
whole region exists without having the sanitizer get upset.
=> fuzz_ipc: use calloc instead of malloc for ipc region

CODEOWNERS
Add myself as the code owner for the fuzzer
=> oss-fuzz: add code owner

src/arch/host/lib/notifier.c
Both the fuzzer and the testbench call init_system_notifier which
initializes the struct so there is no need for this check (which causes
a double alloc) in the get function.
=> host: don't alloc notifier

src/ipc/ipc.c
A few error paths through ipc_pipeline_complete() didn't send
any error log. Each silent error path is some kind of firmware
malfunction.
=> trace: ipc: pipeline: Add logs about ipc_pipeline_complete() errors

src/drivers/imx/sdma.c
Our SDMA drivers has problems when running stress tests. What happens is that channels are not scheduled when running subsequent aplay/arecord commands.
This patch series aims to simplify to code and take a new approach on scheduling the channels. RM says that a condition for a channel to be runnable is      (HE[i] or HO[i]) and (EP[i] or EO[i])
So, foar we have overriden the manual starting of the channel by setting HO[i] = 0, but this creates problems. In order to have a better control on scheduling the channels we use both conditions to schedule the channel:
* make HO[i] =  0
* make EO[i] =  0
With this patchseires and also changing sdma_watermark to half is current value stress test work fine for 1000 iterations.
This means that a channel will run when both the channel was manually …
=> Refactor and fix SDMA driver

src/audio/buffer.c, src/include/sof/audio/buffer.h, test/cmocka/src/audio/component/mock.c, test/cmocka/src/audio/pipeline/pipeline_mocks.c
After change there is proper location in assert and trace message.
=> buffer: Move code with tracing/assertions from headers to .c files

scripts/rebuild-testbench.sh
"make + make install" duplicates many steps, probably because of the
fatal combination of build timestamps + source hash, see PR #3353 for a
similar example.
A single, combined "make install" generates the exact same binary
outputs 30% faster and prints 30% shorter build logs.
=> rebuild-testbench.sh: don't build twice with combined "make install"

src/audio/pipeline.c
Changed `coomponents` to `components`
=> pipeline: Fix spelling error

tools/testbench/include/testbench/common_test.h, tools/testbench/testbench.c, tools/testbench/topology.c
This fixes compilation with:
```shell
CFLAGS=-fno-common ./scripts/rebuild-testbench.sh
sof/tools/testbench/topology.c:24: multiple definition of `lib_table';
sof/tools/testbench/testbench.c:39: first defined here
```
This was detected by Gentoo 10 which uses -fno-common by default, thanks
Guennadi for the report and investigation.
Commit 03067c6c7709 ("host: set up shared library table") introduced a
strange "lib_table" symbol that was apparently meant to be global but
was not really because of some confusion between arrays and pointers and
needed to be passed around and "initialized to itself" (!) at run time
as seen in the sample trace below:
```C
topology.c
struct shared_lib_table *lib_table;
parse_topology(..., library_table,...)
{
printf("DEBUG1 ----- %p, %p, %p\n",
&lib_table, …
```
=> testbench: make lib_table actually global and stop passing it around

src/drivers/intel/hda/hda-dma.c
Modified traces are quite verbose so should be done
with tr_dbg() function to reduce messaging noise in
non-verbose scenario.
=> trace: hda-dma: Lower trace level

src/platform/apollolake/lib/power_down.S, src/platform/intel/cavs/lib/power_down.S
Before switching off memory, IPC_HOST_BASE literal value should
be moved to register, in order to avoid accessing to disabled
memory.
fixes #3538 
=> power_down: move IPC_HOST_BASE literal into register

scripts/host-testbench.sh
The host-build-all.sh is deprecated, update to the recommended
'rebuild-testbench.sh'.
=> host-testbench.sh: update comment for testbench building

tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4
sof-icl-rt711-rt1308-rt715-hdmi.m4 has all 8 channels set to 1 in demux
matrix definitions even though all streams use only 2 channels. This
confuses the demux component to make extra copies, consume more cpu and
causing extra distortion every now and then.
The real fix is to limit the demux operation at runtime to stream
channel count, so not using all channels defined in matrix. However,
this fix is orthogonal and can be used together with the real demux fix.
=> topology: remove extra demux channel definitions

src/audio/mux/mux.c
This commit adds channel parameter checking in demux/mux_prepare_active_look_up() functions.
Look up table should not include elements referring to channels higher than those actually set in
source/sink buffers. 
fixes #3499
=> mux: add channels checking in *_prepare_active_look_up() functions

tools/README.md
The host-build-all.sh is deprecated, update to the recommended
'rebuild-testbench.sh'.
=> tools/README: update comment for testbench building

src/drivers/intel/ssp/ssp.c, src/include/sof/drivers/ssp.h, src/include/sof/lib/clk.h, src/lib/clk.c
ssp: refine the RX FIFO flushing logic
The SSSR_BSY is not necessary for flushing, we need to read out entries
every time the FIFO is not empty. This flushing may need take place
several rounds, and we need to wait 1 sample time between 2 flushing
rounds.
Fixes #3525
=> Ssp rx flush

src/trace/dma-trace.c
If we are fuzzing we can get the trace system into a state where it
tries flush dma and overshoot the mailbox boundary.
=> trace: enforce mailbox size

src/platform/imx8/include/platform/lib/memory.h, src/platform/imx8m/include/platform/lib/memory.h
At this point PLATFORM_DCACHE_ALIGN is equal with DCACHE_LINE_SIZE
which on i.MX boards is 128.
Functions like rmalloc and rzalloc are allocating memory aligned at
PLATFORM_DCACHE_ALIGN bytes. This means that blocks under 128 bytes
are not really used and blocks sized > 128 are preffered for small
allocations.
This seems to be an unnecessary overhead which results in SOF not
being abel to allocate memory for simple pipelines (e.g simple
pipeline with a mixer).
For this reason, we set PLATFORM_DCACHE_ALIGN to a smaller value
(sizeof(void*)) but keep HEAP_BUF_ALIGNMENT unchanged.
=> platform: imx: Fix PLATFORM_DCACHE_ALIGN

src/audio/mixer.c
This function isn't called anywhere, time to do some cleaning
=> mixer: delete unused function

src/audio/dai.c, src/drivers/intel/baytrail/ssp.c, src/drivers/intel/haswell/ssp.c, src/drivers/intel/ssp/ssp.c
When a DAI_CONFIG IPC is sent from the driver for a particular
DAI type and index, all DAI components that match the type and index
are configured. When all components are set up during topology
loading, this isn't really much of a problem as all DAI_CONFIG
IPCs will be sent at that time as well ie there is no active
playback/capture. But with dynamic pipeline loading, the playback
and capture DAIs will be individually configured whenever the
respective pipeline is started. This will end up with errors both
when configuring the SSP and when configuring the DAI comp itself.
So, ignore the request to configure the SSP and the DAI comp
that is already active so that the other DAI comp can be
configured successfully when its pipeline is set up.
Signed-off-by: Ranjani Sridharan …
=> ssp/dai: Dont treat dai_config during active audio as an error

src/arch/xtensa/Kconfig, src/audio/dai.c, src/audio/kpb.c, src/drivers/dw/dma.c, src/include/sof/lib/dai.h, src/ipc/dma-copy.c, src/ipc/ipc-host-ptable.c, src/platform/Kconfig, src/trace/trace.c, zephyr/CMakeLists.txt, zephyr/wrapper.c
This overrides #3578 upon request from @lgirdwood 
This enables building SOF for arbitrary non-xtensa architectures. It uses CONFIG_LIBRARY for that purpose.
=> SOF build on arbitrary architectures

scripts/xtensa-build-all.sh
Currently xtensa-build-all.sh has restriction to use rimage for tgl
signing, because rimage didn't support tgl. As rimage now has support
for tgl signing let's remove this limitation.
=> scripts: remove restriction for tgl rimage signing

src/audio/kpb.c
Storing the address of a know existing address space will always result
to be true. Therefore this variable is actually doing nothing. Remove
reference to fix this.
=> kpb: fix logic bug

src/audio/codec_adapter/codec/generic.c
This patch moves memory list initialization from .prepare() to .init()
as we need that memory list be already initialized on codec
initialization otherwise we will lose track of memory allocated
prior to .prepare()
=> codec_adepter: fix for memory list initialization

tools/tune/dmic/dmic_batch.m, tools/tune/dmic/dmic_fir.m, tools/tune/dmic/dmic_fir_export.m, tools/tune/dmic/dmic_init.m
This patch adds the the Matlab script dmic_init() that simulates
initialization of the Intel PDM digital microphones decimation
block. The tool computes the needed FIR filters and exports
them as C header files. The script dmic_batch computes all the
currently used decimation settings.
The generated header files from subdirectory include need to be
manually copied to src/include/sof/audio/coefficients/pdm_decim/
and the header file pdm_decim_table.h edited manually if the
header file names were changed due to different filter characteristic
(band frequencies, stop-band attenuation).
=> Tools: Tune: Add tool for DMIC FIR filters setup

tools/topology/platform/imx/imx8qxp.m4
This adds memory capabilities macros for different buffer
types on i.MX8.
Once we started to enable more complex pipelines
on i.MX8 we found out that we need these caps defined.
=> topology: imx8: Add memory caps for i.MX8 platforms

src/arch/xtensa/hal/CMakeLists.txt
Prevent unused Xtensa XTOS files from building but keep them in the tree until migration to Zephyr completes. This is a replacement of #3557 which I damaged beyond repair, sorry about that
=> hal: remove unused files

src/drivers/imx/sai.c, src/include/ipc/dai-imx.h, src/include/sof/drivers/sai.h
This patch series helps reading the SAI parmeters from topology. So far we didn't care about this for two reasons:
- SAI is always used in provider mode
- all our pipelines used 48000 constant rate.
This prepares our KWD pipelines.
=> Fix sai params

CODEOWNERS
Add google code owners for google contributed processing code
=> codeowners: add codeowners for dcblock/drc/crossover

src/platform/intel/cavs/lps_wait.c, zephyr/CMakeLists.txt
Use a correct path to the cAVS memory.h header, build cAVS LPS only when the respective Kconfig option is selected.
=> zephyr: fix a path to a header, build LPS conditionally

zephyr/include/sof/trace/trace.h
Commit fee7d9c66026 ("trace: Introduce adaptive rate-limiting/suppression of repeated messages") broke Zephyr build. Add the missing parameter.
=> zephyr: fix breakage after a recent logging extention

tools/topology/sof-smart-amplifier.m4
[TGL] [THD] Speaker amp THD issue
DUT: TGL chrome DUT with Max98373-**I2S**
Kernel: Chrome 5.4
SOF topology: branch-tgl-010-hot-fix-1
Issue:  ODM observed high THD during speaker playback. 
**Fixes for this are spread in:**
a) kernel fix to update tdm/slot_width (https://github.com/thesofproject/linux/pull/2590)
b) topology: update DAI config to s32_le (this PR)
c) Maxim DSM tuning blob - will be submitted to private branch
=> topology: sof-smart-amplifier: update speaker amp ssp DAI configuration

src/ipc/ipc-host-ptable.c
This corrects the minimum transfer size calculation for the ptable and uses the relevant DMA attribute.
Fixes #3492, fixes  #3503
=> ipc: Fix page table DMA transfer size

src/trace/trace.c
This patch adds missing trace variable for CONFIG_TRACEM.
=> trace: fix missing trace variable for CONFIG_TRACEM

tools/test/audio/process_test.m
The set of figure property in figure() command is not supported
in Matlab. The separate set() property works for both Octave and
Matlab.
=> Tools: Test: Fix Matlab compatibility in process_test.m

src/drivers/dw/dma.c
ILL entries in the DW DMA driver are accessed both by the controller, using DMA and by the DSP. For this to work the DSP has to force cache synchronisation appropriately. Therefore the ILL area has to be allocated with cache-line size alignment. This patch switches allocation from rmalloc() to rballoc() to force such alignment.
=> dw-dma: align ILL allocations

tools/topology/sof/pipe-amp-ref-capture.m4, tools/topology/sof/pipe-smart-amplifier-playback.m4
Both the playback and capture PCMs should be restricted to the
corresponding SMART_PB_CH_NUM and SMART_REF_CH_NUM, as running them with
other channel numbers will not work correctly.
=> topology: smart_amp: restrict channel number of PCM capabilities

CODEOWNERS, src/audio/CMakeLists.txt, src/audio/Kconfig, src/audio/crossover/crossover.c, src/audio/drc/drc.c, src/audio/drc/drc_generic.c, src/audio/multiband_drc/CMakeLists.txt, src/audio/multiband_drc/multiband_drc.c, src/include/sof/audio/crossover/crossover_algorithm.h, src/include/sof/audio/drc/drc_algorithm.h, src/include/sof/audio/multiband_drc/multiband_drc.h, src/include/user/multiband_drc.h
Multiband DRC is a single-source-single-sink compound component which consists of 4 stages: Emphasis Equalizer, Crossover Filter (from 1-band to 4-band), DRC (per band), and Deemphasis Equalizer of summed stream.
The following graph illustrates a 3-band Multiband DRC component:
```
low
o----> DRC0 ----o
|               |
3-WAY     |mid            |
x(n) --> EQ EMP --> CROSSOVER --o----> DRC1 ---(+)--> EQ DEEMP --> y(n)
|               |
|high           |
o----> DRC2 ----o
```
=> sof: multiband_drc: Add Multiband DRC component

tools/topology/m4/enumcontrol.m4
Add m4 macros to generate enumerated control. Usage is similar to mixer
and bytes control except enumerated values are specified using separate
text section.
=> topology: add enum control

tools/tune/eq/eq_blob_plot.m
This fix adds initialization and declaration of variable f_single
to avoid a previously overlooked error when accessing it in the
end of script. It produces the plot but with a warning print.
=> Tools: Tune: Add variable initialize to EQ blobs plotter

src/audio/dai.c, src/include/sof/compiler_attributes.h
for some reason the clang version with oss-fuzz doesn't recognize the
comments so lets add this attributes in the meantime. xtensa-gcc doesn't
seem to mind them.
=> dai: add fall through markers for clang

src/math/iir_df2t_generic.c
With coefficients scaling that creates above 1.0 absolute value
internal biquad output before scaling gain and shift there's
overflow in variable tmp calculation that is used for output
and for recursive a1, a2 coefficients multiplication.
Fixes: #3678
=> Math: IIR: Fix overflow in DF2T generic C version biquad output

src/include/sof/common.h, src/lib/alloc.c
We're taking a new approach to this. Let's merge these 4 patches first, then we'll deal with the two more complex remaining patches from #3607 separately in PRs #3646 and #2647 and #3607 can be closed then.
=> Align base

src/audio/codec_adapter/codec_adapter.c
This patch fixes the issue with premature free of runtime
parameters memory. Such situation occurs when runtime
params are send in few parts, then after the first packet
has been copied the memory is freed so the consecutive one
no longer has a copy destination.
=> codec_adapter: fix premature free of memory

tools/topology/m4/muxdemux.m4
Currently the mux/demux uuid setting doesn't work and uuid is always set
to "demux". Fix this by quoting the ifelse in 1 line.
=> topology: fix setting mux uuid in m4

src/drivers/intel/ssp/mn.c, src/drivers/intel/ssp/ssp.c
This is a small series to refine the SSP bclk request/release sequence,
to reduce the power consumption when SSP is inactive.
To reduce the power consumption, we should request the clock source for
bclk only when SSP is active. This means we need to postpone the clock
request from ssp_set_config() to ssp_start() and release it at
ssp_stop().
Create ssp_pre_start/stop() helpers to do this kind of runtime
configuration, and do the bclk request/release inside them.
=> SSP bclk refining series

src/schedule/dma_multi_chan_domain.c
When scanning all channels for a certain task we end up comparing
with a null task.
That's because we have multiple channels (e.g. 32 for i.MX) but only
some of them are used in certain scenarios. For example, for simultaneous
playback/capture we use only 2 DMA channels.
To fix this, validate task before using it.
Fixes #3690
Fixes: 647390f75 ("schedule: dma_multi_chan: fix a DMA channel interrupt race")
=> schedule: dma_multi_chan: fix null pointer when scanning for tasks

src/audio/kpb.c
This patch will prevent from enabling pm_runtime dsp at the end of draining
to avoid enabling it when already received disable ipc during draining
=> kpb: check pm_is_active and dont enable it at the end of draining

src/audio/codec_adapter/codec/cadence.c, src/audio/codec_adapter/codec/generic.c, src/audio/codec_adapter/codec_adapter.c, src/include/sof/audio/codec_adapter/codec/generic.h, tools/topology/sof/pipe-processing-playback.m4
This patch sets improves codec_adapter in several ways:
- introduces additional local buffer -  we can store several periods internally in CA before we actually start producing samples out.
- introduces deep buffering - this feature is needed in cases when the codec buffer is different (in terms of size) than the pipeline sink&source buffers. In such cases we need to gather enough samples so after certain periods we will be able to produce output constantly 
- add missing CONRTROL bytes structure for real time parameters in the topology
- increase buffer sizes of all component on CA pipeline
- slight code refactor
=> codec_adapter: improvements

src/lib/alloc.c
alloc_heap_buffer() is trying to allocate memory from a single heap,
no need to check its size on each iteration of an internal loop over
maps.
=> alloc: no need to check the same condition repeatedly

src/init/init.c
lp_sram_unpack() is currently only built for Tigerlake targets, it contains a wrong type cast from "uintptr_t *" to "uint32_t *" and a superfluous cast from "uint32_t" to itself. Fix both.
=> tgl: fix a compilation warning

tools/topology/sof/pipe-volume-demux-playback.m4
The earlier length 250 ms is quite long and makes very short UI
tones etc. quite silent. The 20 ms long ramp with zero crossings
detect is used in rest of this topology for playback so this is
changed to similar.
The topologies those use the changed macro are: sof-icl-rt711-rt1308-rt715-hdmi.m4, sof-apl-demux-pcm512x.m4, sof-tgl-max98357a-rt5682.m4, sof-cml-demux-rt5682.m4, and sof-tgl-nocodec-ci.m4.
Fixes: #3707
=> Tools: Topology: Change volume demux playback ramp length to 20 ms

src/platform/intel/cavs/include/cavs/lib/pm_memory.h
cavs_pm_memory_hp_sram_mask_get() checks starting and ending bank indices against the requested segment range incompletely. Add the missing end segment check.
=> cavs: add a missing sanity check in a mask calculation

tools/logger/convert.c
There is one extra level of identation for all the
code inside format_file_name function.
Remove that to enhance readability.
=> logger: Reduce one level of indentation

tools/scripts/cross-arch64.cmake
We need this to cross-compile sof-logger for arm64.
Steps:
* download and install cross-compiler
* (e.g on Ubuntu: sudo apt-get install gcc-aarch64-linux-gnu)
* mkdir tools/build/
* cd tools/build/
* cmake .. -DCMAKE_TOOLCHAIN_FILE=../scripts//cross-arch64.cmake
* make sof-logger
=> tools: Add cmake toolchain file for cross compilation on arm64

src/audio/smart_amp/smart_amp_maxim_dsm.c
Change to comp_warn() when zero fram is copied, which really requires
attention on.
=> smart_amp_maxim_dsm: log warning for zero frame copy

src/lib/alloc.c
Simplify the align_ptr() function by re-using an existing ALIGN() macro.
=> alloc: simplify align_ptr()

src/include/kernel/ext_manifest.h, src/init/ext_manifest.c, src/platform/intel/cavs/ext_manifest.c, src/platform/intel/cavs/include/cavs/ext_manifest.h
Solution extracted from discussion from https://github.com/thesofproject/sof/pull/3527
=> Pretend unused slots presence in dictionaries from extended manifest

tools/topology/sof-tgl-max98373-rt5682.m4
To align with maxim 98373 12.288MHz bclk requirement, change rt5682 to
32bit with BCLK 3.072MHz.
To follow the rule that the MCLK should use the same clock source with
BCLK, change the mclk to 24.576MHz.
=> topology: sof-tgl-max98373-rt5682: use 32bit dai and 24.576MHz mclk

src/include/sof/common.h, src/init/ext_manifest.c, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/ext_manifest.c, src/platform/intel/cavs/platform.c
Alignment should always be done on powers of 2. Enforcing this rule also allows the use of binary AND for alignment instead of much slower division. Also add compile-time checks where possible.
=> [RFC] core: assure alignment is only done on power of 2 values

zephyr/CMakeLists.txt
zephyr needs a path to rimage configuration files, add it to cmake cache. As suggested by @mbolivar-nordic in https://github.com/zephyrproject-rtos/zephyr/pull/31127#discussion_r552916260
=> zephyr: add a cache variable with a rimage configuration path

src/audio/Kconfig, src/audio/codec_adapter/CMakeLists.txt, src/audio/codec_adapter/codec/dummy.c, src/include/sof/audio/codec_adapter/codec/dummy.h, src/include/sof/audio/codec_adapter/interfaces.h
This is useful to test codec adapter component and generic codec code.
Also, this is useful for testing compress API patches without the need to compile in the Cadence proprietary binaries.
=> codec: Add dummy codec implementation

src/lib/alloc.c
When allocating multiple buffers the first free buffer might not contain a suitably aligned start address. Skip it instead of allocating it with the others. Also don't add alignment to the allocation size, but find a suitably aligned start address instead.
=> alloc: pick up allocation start correctly

zephyr/CMakeLists.txt, zephyr/wrapper.c
Add some files from src/platform/library/ to generic arch builds with Zephyr.
=> zephyr: update for unsupported arch builds

src/drivers/intel/ssp/mn.c
This is recommended flow to avoid glitches.
find_bclk_source() will try to use the same clock source as for MCLK and go standard way if it was not possible.
=> ssp: try to use the same source clock for BCLK and MCLK

tools/topology/CMakeLists.txt
Add a topology file for Cherry Trail boards with a NAU8824 codec.
These setups work with the standard settings from sof-byt-codec.m4.
This has been tested on the following devices:
Medion E2215T:   stereo speakers, analog mic
Medion E2228T:   stereo speakers, stereo digital mics
Cube iWork8 Air: mono speaker, analog mic
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
=> topology: Add sof-cht-nau8824 topology file

src/audio/drc/drc_math_generic.c
drc_sin_fixed() utilized sin_fixed() while its input range is
non-negative. This commit fixes drc_siz_fixed() for negative input by
using ABS(input) to sin_fixed() and then inverting the output sign.
=> sof: drc: fix drc_sin_fixed function

src/audio/Kconfig, src/audio/codec_adapter/Kconfig
The codec config of codec adapter should be placed under
src/audio/codec_adapter since we may have more and more codecs in the
future.
Any thought?
=> codec_adapter: Used nested Kconfig of codec adapter codecs

src/lib/alloc.c
**Note** this has to wait for #3642 to be merged first to then get rebased on top of it.
The condition "size + alignment <= block_size" for allocating memory from a signle buffer is sufficient but not precise enough. For example if we want to allocate 20 bytes with 64-byte alignment, a 32-byte buffer *might* be sufficient if it's suitably aligned. Fix the algorithm to account for such cases.
=> alloc: fix the general one-buffer memory allocation case

src/include/sof/common.h, src/lib/alloc.c, src/platform/intel/cavs/lib/pm_memory.c
commit 39266cac81f4 ("core: assure alignment is only done on power of 2
values") changed the alignment macros, they now use C code to perform a
sanity check. This broke ALIGN() usage in
platform/suecreek/include/platform/lib/memory.h in two different ways:
1. it broke static initializers in platform/suecreek/base_module.c
because these can't use statement-expressions. This could have been
fixed by simply switching to ALIGN_UP_COMPILE(), BUT:
2. memory.h files are also included in assembly.
Also note memory.h values are copied unprocessed to linker scripts that
require the ALIGN() spelling.
For these reasons ALIGN() needs to be switched back to a "dumb" macro.
Preserve the sanity checks just added in alloc.c and pm_memory.c by
switching them to the new and smarter ALIGN_UP() macro. …
=> common.h: restore basic ALIGN() macro compatible with assembly

.travis.yml
Sue Creek is the only platform using the ALIGN() macro in assembly. If
it had been built in CI then we would have avoided the ALIGN()
regression in commit 39266cac81f4 ("core: assure alignment is only done
on power of 2 values"). Building Sue Creek is practically free and finds
bugs so let's build it.
I'm aware Travis isn't the future but it's still running for now and
this is a tiny and totally trivial change that took 1/100 of the time
spent writing this commit message. It's also a reminder not to forget
Sue Creek in whatever will replace Travis.
=> .travis.yml: build Sue Creek

src/drivers/intel/dmic.c
Once an Xrun happens, only clearing the interrupt can't recover it, stop
the dmic to avoid interrupt flooding.
This will lead to subsequent pipeline Xrun and eventually the pipeline
will be stopped.
=> dmic: stop dmic at xrun to avoid interrupt flooding

zephyr/CMakeLists.txt
Fix the cached rimage path to the temporary cloned rimage location.
=> zephyr: fix cached rimage path

src/audio/pipeline.c, src/include/sof/audio/pipeline.h
Minor fixes for component/pipeline comparison, we should use the unique IDs, not the pointers.
=> Pipeline fixes

tools/test/audio/std_utils/stdnotch_get.m, tools/test/audio/test_utils/delete_check.m, tools/test/audio/test_utils/load_test_output.m, tools/test/audio/test_utils/mkdir_check.m, tools/test/audio/test_utils/test_run.m, tools/tune/eq/mls_freq_resp.m, tools/tune/src/src_generate.m
Running the  matlab script from 
```
\tool\tune\src\src_std_int32.m
\tool\tune\src\src_tiny_int16.m
\tool\tune\src\src_small_int32.m
```
is showing error in the command window
```
Error message 
Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.
Error in src_generate (line 171)
fprintf(fh,'\n');
Error in src_std_int32 (line 55)
src_generate(fs1, fs2, fs_matrix, cfg);
```
`Line fh = fopen(fn,'w')  - This is not executing , fh is -1`
=> Tools:tune:src scripts does not execute with Matlab

tools/topology/m4/smart_amp.m4, tools/topology/sof-smart-amplifier.m4, tools/topology/sof/pipe-amp-ref-capture.m4, tools/topology/sof/pipe-smart-amplifier-playback.m4
Define SMART_AMP_CORE configurable, configure to run DSM pipelines on
DSP core0 if it is not set.
=> topology: smart_amp: make the DSP core configurable

src/audio/smart_amp/smart_amp_maxim_dsm.c
When overrun happens for maxim_dsm_ff_proc() or maxim_dsm_fb_proc(), it
is not fatal, change the logging level to warning to avoid flooding the
memory windows.
=> smart_amp_maxim_dsm: change logging level for xrun

src/drivers/intel/baytrail/ssp.c
Commit 05e1c26166 ("byt-ssp: fixes for DSP modes") removed a work-around for known hardware bugs, causing channel swapping in I2S mode. Restore the work-around but make sure it's only enabled in I2S and LEFT_J modes.
Fixes: #3699, #3520
=> byt: fix sporadic channel swap

doc/sof.doxygen.in
Makes it possible to place the build directory anywhere.
This directory does not seem in use any more; fixing it does not change
the doxygen output. However this does silence a doxygen error message
when the build directory is not in the usual place.
=> [skip ci] sof.doxygen.in: change ../test to @top_srcdir@/test

src/drivers/intel/cavs/ipc.c, src/platform/intel/cavs/lib/pm_runtime.c, src/platform/intel/cavs/platform.c
polling the IPC_DIPCIDR_BUSY to be cleared to show no IPC is sending to HOST before power off hpsram.
RFC created from discussion in https://github.com/thesofproject/linux/pull/2663
=> [RFC] polling for DSP to HOST IPC free before power off hpsram

src/Kconfig, src/platform/Kconfig, src/schedule/CMakeLists.txt, src/schedule/Kconfig
Only cAVS platforms use the single-channel DMA scheduler, all other platforms use the multi-channel one. Add Kconfig options to only build one of them.
=> [RFC] schedule: build only one of single- and multi-channel DMA schedulers

src/include/sof/audio/component.h
Add some more usage context around prepare() and reset() for developers.
=> component: doxygen: add more content around prepare() and reset().

src/audio/pipeline.c
=> pipeline: fix log message

tools/topology/sof/pipe-codec-adapter-capture.m4, tools/topology/sof/pipe-codec-adapter-playback.m4, tools/topology/sof/pipe-processing-playback.m4
pipe-codec-adapter-playback.m4 and pipe-codec-adapter-capture.m4 is implemented as a common pipeline module of a playback/capture codec w/ Codec Adapter API.
For codec developers, a upper-layer tplg file should be provided for the specified codec with the information of control bytes, schedule core, and byte-control names.
=> tools: topology: Add common Codec Adapter pipeline tplg

.github/workflows/pull-request.yml, README.md
The singular "Action" makes it look like our workflow is an action. The
plural "Github Actions" is at least the name of the product; so it's
vague enough.
A technically acccurate name would be "Main workflow" but we have only
one so it would be useless plus we're next to "Jenkins" and others and
want to stay consistent with them.
=> [skip ci] .github: rename workflow from "Github Action CI" to "Github Actions"

src/platform/intel/cavs/lib/pm_runtime.c
In current kernel logs the CTX_SAVE IPC will always take more than 10ms,
but before 0b2876b2794 it only need less than 1ms. This patch fix the
wrong usage of always timeout for poll_for_register_delay.
IPC_DIPCIDR_MSG_MASK is the mask for msg from BIT 0 to 30 while
we want to check if BIT 31 is 0. now change the MASK and VAL to correct
values to make the poll and delay will return when there is no DSP sent
IPC.
Also make some optimization to timeout value:
After checking the kernel log the HOST will always handle
and replay DSP sent IPC GLB_TRACE_MSG in about 40us.
set the FW side wait timeout to 100us to improve the performance
of DSP power switch by a proper poll period.
fix some issues find in tests with https://github.com/thesofproject/sof/pull/3786
@lgirdwood Please help to check if …
=> fix wrong usage of poll_for_register_delay in CTX_SAVE power down hpsram

CODEOWNERS
=> [skip ci] CODEOWNERS += /.github/

tools/topology/CMakeLists.txt, tools/topology/sof-cml-rt700.m4, tools/topology/sof-icl-rt700.m4, tools/topology/sof-tgl-rt711-rt1308.m4
Somehow we use different configurations for the DMIC, remove
everything in this file and rely on the same macros.
The only difference with HDaudio is the pipeline and PCM device numbers
=> topology: sof-tgl-rt711-rt1308: align DMIC support with HDaudio

CODEOWNERS
As discussed in latest PR #3791
=> [skip ci] CODEOWNERS: /.github/ += @zrombel

src/platform/intel/cavs/lib/pm_runtime.c
With a recent test result:
[ 9435.941365] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 9435.941392] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 9435.942023] sof-audio-pci 0000:00:1f.3: error: DSP trace buffer overflow 4294967295 bytes. Total messages -1
[ 9435.942030] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 9435.942118] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
IF a DSP sent IPC just arrived before IPC CTX_SAVE sent, the HOST IPC
handler may be delayed anda use about 1ms. Change the timeout value
to 2ms will be safer
=> cavs: pm: change the timeout value to 2ms for HOST IPC handler

src/drivers/intel/cavs/timer.c
This optimises the recovery time and reuses the same value
for overhead. Maybe optimised further, but value seems good
for all DSP clocks on cavs.
Also removes unused code.
=> cavs: timer: make timer recovery 10uS

src/audio/mux/mux_generic.c, test/cmocka/src/audio/mux/demux_copy.c, test/cmocka/src/audio/mux/mux_copy.c
Input and output channel settings from matrix row and column
are in reverse order, so they should be swapped.
=> mux: fix input and output channel setting

tools/topology/development/sof-tgl-nocodec-ci.m4
Define to use 38.4MHz MCLK for DSM, to align with other SSP ports.
=> topology: sof-tgl-nocodec-ci: use 38.4MHz MCLK

src/arch/host/include/arch/string.h, src/arch/xtensa/include/arch/string.h, src/lib/lib.c
3rd party libraries need __vec_memcpy / __vec_memset
which are not provided by xtensa gcc.
Add open coded versions of these functions by using
memcpy and memset.
=> lib: Add __vec_memcpy / __vec_memset

src/samples/audio/smart_amp_test.c
With dynamic pipelines, the widgets in the feedback path are set
up only when the capture PCM is opened. Check if the
feedback_buf exists before accessing it to prevent DSP panic
when only the playback pipeline is open.
=> smart_amp_test: check if feedback_buf exists before accessing it

src/audio/mux/mux.c
Currently you can't play multiple simultaneous streams at the same time
into mux. Fix this by copying the trigger and reset mechanism from audio
mixer.
=> mux: enable playback of multiple simultaneous streams

src/include/sof/schedule/ll_schedule.h, src/include/sof/schedule/ll_schedule_domain.h, src/include/sof/schedule/task.h, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/schedule/dma_multi_chan_domain.c, src/schedule/ll_schedule.c
Add a full_sync attribute to ll_schdule domain.
This is set to true, for a full synchronous dma_domain
scheduler, which is not time dependent.
By default, it is false.
In full_sync case we use the ratio between the task period
and the registrable task period to do the scheduling, not
the task.start time.
We do this because for the DMA_DOMAIN there are no guarantees
for the accuracy of the period of the registrable task
which drives the entire scheduling.
The second commit sets the full_sync attribute to true for imx platforms.
Fixes: #3802
=> schedule: dma_multi_chan: do not skip tasks for dma_domain scheduler

scripts/xtensa-build-all.sh
The script already logs the full CMake command that is re-usable outside
this script... except for the PATH change. Expose that sneaky PATH
change.
Debugging every build issue starts with peeling the too many layers of
indirection.
Also fix some minor issue in the help message.
=> xtensa-build-all.sh: add PATH to build log

tools/oss-fuzz/CMakeLists.txt, tools/oss-fuzz/README.md
=> oss-fuzz: add error for incorrect build env and readme

src/schedule/timer_domain.c
In the case of scheduling irregularities the drift may accumulate in the
scheduling reference value. By ensuring we always refer to the previous
requested time the drift can be prevented.
=> timer_domain: set last_tick to ticks_req in order to avoid drift

tools/topology/CMakeLists.txt
Add a topology file for Bay Trail boards with a WM5102 codec
connected to SSP0.
These setups works with the standard settings from sof-byt-codec.m4.
This has been tested on a Lenovo Yoga Tablet 2 1015L.
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Note this also should be chery-picked as a fix into the stable-v1.7 branch.
=> topology: Add sof-byt-wm5102-ssp0 topology file

src/audio/kpb.c, src/include/sof/trace/trace.h, src/trace/trace.c, zephyr/CMakeLists.txt, zephyr/Kconfig, zephyr/module.yml
- Reference local Kconfig to avoid inclusion of SOF Kconfig when SOF is not enabled from Zephyr
- Fix few formatting issues resulting in warning
- Revert reference to local copy of rimage which is now removed.
=> Zephyr integration changes

installer/.gitignore, installer/GNUmakefile, installer/README.md, installer/sample-config.mk, src/arch/xtensa/CMakeLists.txt
_[To see the README.md file with rendered markdown go to Files changed->README.md->three dots in the upper right corner-> View File]_
More specifically replacing sof-bin/go.sh and sof-bin/publish.sh and
also sof/scripts/sof-target-install.sh eventually.
"make install" code has always belonged to source repositories because
developers need to install too and we want everyone to use the same
installers. It's also easier to have all the information in a single
place.
Once the layout in sof-bin mirrors the /lib/firmware/intel layout
exactly, sof-bin does not need any installation code any more.
Mixing source and binaries in the same repo is also a "code smell",
notably because it forces branching them together.
Using a higher level build tool for installation instead of plain
scripts has a …
=> New installer/GNUmakefile to gradually replace scripts in sof-bin.git - take 2

src/audio/mux/mux_generic.c, test/cmocka/src/audio/mux/demux_copy.c
Array streams represents streams on "many" side i.e. input
for MUX and output for DEMUX.
For DEMUX each stream has masks array - 1 mask per output
channel. Each mask shows, from which input channel data
should be taken.
This commit reverts "demux" part of commit:
b1b31e7154a5c159d81459634eabd8013b434181
=> demux: fix demux look up table preparation

src/include/sof/audio/mux.h
This commit adds description of mux/demux config structure
and format.
=> mux/demux: update mux/demux documentation.

scripts/docker_build/sof_builder/Dockerfile
=> docker: toolchain: update docker to GCC 10.2 and GDB 9.2

tools/topology/sof-apl-nocodec.m4, tools/topology/sof-bdw-nocodec.m4, tools/topology/sof-cht-nocodec.m4, tools/topology/sof-cnl-nocodec.m4, tools/topology/sof-icl-nocodec.m4, tools/topology/sof-tgl-nocodec.m4
This patch replaces use of pipe-volume-capture macro or
pipe-low-latency-capture to pipe-volume-switch-capture in nocodec
topologies for APL, BDW, CHT, CNL, ICL, and TGL based platforms. It
allows to test of volume component mute switch control in SSP loopback
that is used by default in nocodec topologies. The testing of mute
switch feature is simplest to do with loopback topologies. Nocodec
topologies are not in mainstream usage so this is the safest option to
enable testing.
The mute switch add should be possible to all capture topologies but
it can be done later once it is confirmed it is safe to do (avoid
accidental muted audio or problems with UCM).
=> Topology: Use pipe-volume-switch-capture in nocodec topologies

src/audio/drc/drc_math_generic.c, src/include/sof/audio/drc/drc_math.h
Used ABS(x) instead of x for comparing to ONE_OVERT_SQRT2(~0.707)
because x could be a negative value and here we want to transfrom x
from range (-1, -0.5];[0.5, 1) to (-1, -0.707];[0.707, 1)
Revised code line 237~241 to be easier to understand.
Refined some comments to prevent confusion of function usage.
=> sof: drc: fix drc_inv_fixed function and refine comments

src/audio/codec_adapter/codec/generic.c
libc doesn't return a type, so it just no-ops silently on null, lets to
the same having this error makes walk back patterns more annoying
=> codec_adapter: don't error on free(NULL)

src/include/sof/audio/codec_adapter/codec/generic.h
For the documentation fix I personally don't agree with the design but the documentation needs to match the code. **Begin rant** I think the adapter should **never** reject a config push to a valid adapter. This makes it hard for things like audio servers to push config's on boot as its past init so too late for setup but too early for runtime. The library should be allowed to make the choice when it wants to use the config but it should always be notified of when it is loaded. Also I don't think we should be limiting the types, why not make the id generic and let the adapter decide what types of configs it wants and pass that as an argument in the callback? Right now the cadence adapter uses the same function for both setup and runtime config which suggests that we should be something …
=> Codec adapter fixups

scripts/xtensa-build-all.sh
Lets use the same version of Xtensa toolchain as Intel in order
to avoid compilation problems.
It is difficult to support multiple toolchain versions because specific
headers needs to be updated, so lets have the same version supported
between IMX and Intel.
=> xtensa-build-all.sh: Bump IMX xtensa toolchain version

tools/topology/platform/intel/intel-generic-dmic-kwd.m4, tools/topology/platform/intel/intel-generic-dmic.m4, tools/topology/sof-cml-rt5682.m4, tools/topology/sof/pipe-eq-iir-volume-capture-16khz.m4, tools/topology/sof/pipe-eq-iir-volume-capture.m4, tools/topology/sof/pipe-tdfb-eq-iir-volume-capture-16khz.m4, tools/topology/sof/pipe-tdfb-eq-iir-volume-capture.m4, tools/topology/sof/pipe-tdfb-volume-capture-16khz.m4, tools/topology/sof/pipe-tdfb-volume-capture.m4
This patch fixes the error that happens with the hard-coded PGA
names Dmic0 and Dmic1 in pipelines pipe-eq-iir-volume-capture.m4
and pipe-eq-iir-volume-capture-16khz.m4. Pipelines for beamformer
TDFB have the same hard-coded PGA names and are fixed too.
If impacted pipelines are used for any other purpose than DMIC endpoints
the topology graph gets messed up. With this change the caller macro,
e.g. intel-generic-dmic.m4 needs to set the PGA_NAME macro when the
respective pipeline is instantiated. If it is not set the default
name via N_PGA() macro is used.
The macro intel-generic-dmic-kwd.m4 is updated to set the Dmic0
PGA name as well as the earlier missed PIPELINE_FILTER1 and
PIPELINE_FILTER2 definitions for passing filter coefficients.
Fixes: #3378
Signed-off-by: Seppo Ingalsuo …
=> Topology: Get PGA_NAME from pipeline caller macro

src/drivers/imx/esai.c, src/include/ipc/dai-imx.h
So far we only used topologies with rate set
to 48000Hz. This might change in the future.
So use rate from parameters passed from kernel.
While here, align sof_ipc_dai_esai_params struct
with the one from kernel.
=> drivers: imx: esai: use rate from topology

src/include/sof/schedule/ll_schedule_domain.h, src/platform/Kconfig, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/platform.c, src/schedule/dma_single_chan_domain.c, src/schedule/ll_schedule.c, src/schedule/timer_domain.c
ll_schedule: refining the scheduling policy to optimize it
For low latency scheduler, we should schedule a task at the as accurate
as possible point, and set timer interrupt only at needed point.
Also, if we schedule a periodic task at a delayed point, it will be good
to catch up it in the next period, to avoid accumulated delay which will
eventually lead to Xrun.
Here is what the commit does for the LL scheduler refining:
1. at the point of domain_set():
previously: set when the first task over all cores being added, set tick
to the current point (ASAP).
new: set when needed. e.g. the first task over all cores being added, or
a task asking for earlier timer being added.
2. at interrupt handling & tasks_run(): run each pending task of the core,
e.g. for period tasks:
previously: update …
=> ll_schedule: refining the scheduling policy to on demand

tools/topology/sof/pipe-processing-playback.m4
This was a copy paste error in the initial commit.
=> tools: topology: Fix runtime controlbytes name

src/audio/codec_adapter/codec/cadence.c, src/include/sof/audio/codec_adapter/codec/cadence.h
When setting parameters some API calls might not be fatal, so there
is no need to fail the apply config phase in this case.
For example, in case of Cadence MP3 codec the only supported PCM
output word size is 16 and 24. Trying to set a PCM word size of 32
will result in a non-fatal error and the word size would be adjusted to
24.
=> RFC: codec_adapter: Bail out only on fatal errors

src/audio/drc/drc_generic.c, src/audio/drc/drc_math_generic.c
Q_SHIFT_LEFT doesn't check overflow itself. We should do saturation
after left shifts to avoid erroreous value after left shifts.
=> sof: drc: sat_int32 after left-shift to avoid overflow

src/platform/intel/cavs/lib/clk.c
This will fix https://github.com/thesofproject/sof/issues/3823
We need to follow TGL specific HW recommended flow to get/put
PM_RUNTIME_DSP, even for not release_unused clocks requirement.
This will address the PM_GATE IPC failure issue:
https://github.com/thesofproject/sof/issues/3823
=> cavs: clk: do TGL specific HW recommended flow unconditionally

src/math/numbers.c
New implementation does not rely on left shift of signed value and
has no code duplication.
Output is the same as original.
Signed-off-by: Oleksandr Strelchenko <oleksandr.strelchenko@waves.com>
=> fix norm_int32 implementation

src/audio/pipeline.c, src/include/sof/audio/pipeline.h, src/ipc/ipc.c
A buffer should be prevented from being freed only
if both the sink and the source widgets are active.
In the case of dynamic pipeline loading, a buffer
belonging to a pipeline will need to freed when that
pipeline is no longer active but the other end of the
buffer might still be active. So, change the logic
to check if both the sink and source widget states
are invalid to prevent the buffer from being freed.
=> ipc: fix logic for buffer free

installer/README.md
Doc update missing from the most recent pull request.
Also warn against `make -jN stage rsync`
=> [skip ci] installer/README.md: no need to build manually anymore

CMakeLists.txt, scripts/cmake/defconfigs.cmake, scripts/cmake/kconfig.cmake, scripts/cmake/misc.cmake, scripts/xtensa-build-all.sh, src/arch/xtensa/CMakeLists.txt, tools/oss-fuzz/CMakeLists.txt, tools/testbench/CMakeLists.txt
Add cmake -DINIT_CONFIG= option that can point at any initial file.
"make clean" does not delete .config any more.
Note reconfiguration does NOT causes recompilation because -imacros
hides the generated .h from CMake's dependency scan. This is not a
regression, that problems exists since -imacros was introduced. At least
it's now possible to "make clean" and rebuild without losing the .config
file.
Fix for #3617
=> cmake: generate the complete .config at configuration time.

src/audio/host.c
In buffer_size calculation period_bytes should be aligned with dma
before multiplying with period_count. This is an issue for example when
period_bytes could be smaller than the dma alignment size like with 8khz
16 bit mono stream.
=> host: fix buffer size alignment

src/audio/codec_adapter/codec/cadence.c
Existing code returns everytimethe API function at index 0, which works
now because we support only a single API function. But, this will break
when patches adding multiple Cadence codec types will be merged.
=> codec_adapter: cadence: Fix API func search

scripts/xtensa-build-all.sh
There is no such compiler as RF-2017.8 that is in use. The correct
compiler is RG-2017.8 for all i.MX platforms.
=> scripts: xtensa-build-all: imx: Fixup Xtensa compiler

tools/topology/sof-hda-generic.m4, tools/topology/sof/pipe-eq-iir-volume-capture-16khz.m4
This set of two patches fixes two potentially severe bugs. The first potentially can cause undesired processing for DMIC capture pipeline and the second causes topologies build fail if triggered.
Based on before and after diff of topology .conf files the bugs did not cause issues because there's only white space changes with this patch.
=> Topology: Fix two mistakes with HSPROC/DMICPROC and IIR pipeline include

installer/GNUmakefile
In the future we should probably extract the array of XTENSA_SYSTEM
values out of xtensa-build-all.sh
=> installer: disable incremental builds with XCC due to $XTENSA_SYSTEM

tools/topology/m4/dai.m4, tools/topology/m4/pipeline.m4, tools/topology/sof/tokens.m4
Add a new token in scheduler tokens to flag a pipeline
as dynamic. Modify the DAI_ADD ans PIPLINE_PCM_ADD macros
to indicate if the pipeline should be dynamic or now. It is
also possible to make all pipelines in a topology dynamic
by defining the macro DYNAMIC during build.
=> topology: add new token for dynamic pipelines

scripts/xtensa-build-all.sh
commit e31afb36519f ("xtensa-build-all.sh: make it runnable from
anywhere") missed this.
=> xtensa-buid-all.sh: prepends $OVERRIDE_CONFIG with $SOF_TOP

scripts/xtensa-build-all.sh
Add this to the -h usage message:
This script supports XtensaTools but only when installed in a specific
directory structure, example:
```
myXtensa/
└── install/
├── builds/
│   ├── RD-2012.5-linux/
│   │   └── Intel_HiFiEP/
│   └── RG-2017.8-linux/
│       ├── LX4_langwell_audio_17_8/
│       └── X4H3I16w2D48w3a_2017_8/
└── tools/
├── RD-2012.5-linux/
│   └── XtensaTools/
└── RG-2017.8-linux/
└── XtensaTools/
$ XTENSA_TOOLS_ROOT=/path/to/myXtensa ./scripts/xtensa-build-all.sh ...
```
=> xtensa-build-all.sh: show supported XtensaTools installation in usage

installer/GNUmakefile
XTENSA_TOOLS_ROOT is required by xtensa-build-all.sh anyway, so don't
force the user to say twice that they want xcc.
=> installer: TOOLCHAIN default value depends on XTENSA_TOOLS_ROOT

.github/workflows/shallow_checkpatch.yml, .github/workflows/shallowfetchPRcommits.sh
Let's try to run checkpatch in an open-source and fast way while
leveraging Github's very good user interface.
Run checkpatch both with and without --strict; this has been a source of
confusion in the past, see
https://github.com/thesofproject/linux/pull/1988
Note this attempt does not rely on git merge-bases which has been found
to be not compatible with shallow cloning:
https://github.com/thesofproject/linux/issues/2556
=> .github: add shallow checkpatch to Github Actions

src/platform/intel/cavs/lib/clk.c
Bringing back HPRO active for waiti. It was disabled for both transitions (waiti enter and wakeup) in recent commits but actually one of them is very important in tight timing scenarios.
=> clk: do not release clock only for LPRO->HPRO transition

scripts/cmake/xtensa-toolchain.cmake
Notably: xt-xcc --show-config failed with: No such file or directory
... when the directory exists but is wrong.
=> cmake: print some error messages when XTENSA_TOOLS_ROOT is wrong

installer/GNUmakefile
Fixes:
```
rm -rf staging ; make aliases
ln: failed to create symbolic link 'staging/sof/sof-glk.ri': No such
file or directory
```
This also happens on a brand new checkout when building in parallel with
`make -j` because symbolic links don't have any dependency. Example at:
https://github.com/marc-hb/sof/runs/2036288013
=> installer: add missing mkdir staging/* dep. for symlinks

tools/topology/development/CMakeLists.txt, tools/topology/development/sof-cml-rt1011-rt5682-nokwd.m4
This patch is based on sof-cml-rt1011-rt5682.m4 but omits the
hard coded keyword pipeline and resplaces it with a generic
16 kHz capture pipeline. The use of intel-generic-dmic.m4 to
set up the capture pipeline simplifies the topology a lot. This
change makes the topology for CML I2S quite similar to sof-hda-generic
to add audio processing.
All endpoint processing can be defined from top level CMakeLists.txt
with macros HSMICPROC, HSEARPROC, SPKPROC, DMICPROC, DMIC16KPROC.
A sample topology with equalizers in headset and speaker paths is
added.
=> Topology: Add simple topologies (no KWD) for CML RT1011 RT5682

tools/topology/m4/dai.m4, tools/topology/platform/common/ssp.m4
In some cases we need to change dai configuration in firmware. ASoC
supports already setting multiple hw_configs, but sof M4 scripts lack
the mechanism to do this. Thus enable defining multiple config items in
the dai. Enable now support only for SSP by defining new
SSP_MULTI_CONFIG macros that should not clash with the single dai config.
=> topology: enable setting multiple configs for dai

src/audio/codec_adapter/Kconfig, src/audio/codec_adapter/codec/cadence.c, src/include/sof/audio/codec_adapter/codec/cadence.h
Cadence library comes with various codecs. In order to support one
codec we need to initialize the API member of cadence_api with exported
library function.
This patch adds Cadence exported functions for aac, bsac, dabplus, drm
and mp3 codecs.
=> RFC: codec: cadence: Add codec API functions symbols

scripts/xtensa-build-all.sh, src/arch/xtensa/CMakeLists.txt
Notably:
- Log error and default MEU_OFFSET when meu -ver is not found.
- Explain rimage -s option
=> cmake: add some MEU-related comments

scripts/xtensa-build-all.sh
As CMake forks one compiler process for each source file, the XTensa
compiler spends much more time idle waiting for the license server over
the network than actually using CPU or disk.
On my VM with 16 virtual cores, rebuilding one platform from scratch
with this commit goes down from 12s to less than 9s: more than 25%
faster. With Ninja it goes down from 11s to less than 8s. My license
server is 25ms away: a closer server does not need as many threads while
a more distant server would obviously benefit for even more
threads... while already getting an even better improvement than 25%
from just 3 times more threads! It's complicated and we probably don't
want to start the build by measuring latency to the license server.
The entire, purely local _gcc_ build is so fast (~ 1s) that …
=> xtensa-build-all.sh: 3 times more xcc threads than gcc threads

.github/workflows/shallow_checkpatch.yml, scripts/xtensa-build-all.sh
2 commit messages with plenty of git archeology.
I got tired of seeing these warnings every time I ran shellcheck, xtensa-build-all.sh is now shellcheck-clean.
=> xtensa-build-all: remove unused $ARCH, $XTOBJCPY and $XTOBJDUMP

installer/GNUmakefile
2 commits
Building "sof" does not rebuild the .ri firmware file. Switch to the
"bin" target which is what ./scripts/xtensa-build-all.sh builds.
Fixes: 4798096 ("installer: (re)build firmware, topologies and user
space tools)
=> installer: fix incremental builds

src/audio/kpb.c, src/include/sof/audio/component.h
In kpb force_copy_type is declared as enum comp_copy_type,
but later on is initialized and compared with an integer
constant.
We should use everywhere only enum comp_copy_type.
Therefore add an invalid copy_type, COMP_COPY_INVALID in
enum comp_copy_type.
Use this one to initialize and compare force_copy_type.
Fixes: 7e46996c967e ("kpb: Introduce force_copy_type")
=> kpb: fix type for force_copy_type

src/audio/dai.c, src/drivers/imx/sai.c
This pull request fixes #3809.
The first commit updates the correct order for DAI and DMA start/stop.
Before this update, on multiple start/stop runs for playback or record or combined,
we get an underrun/overflow.
That's because the DAI makes a DMA request, before the DMA channel is
enabled.
The second commit updates the start/stop operations for SAI.
Please see a more detailed explanation in the commit message.
After the first 3 commits, after multiple playback/capture runs (~700, ~1000)
everything seems ok. 
But, sometimes, when running a second/third time, the same 700 loop I get an "ipc timed out for 0x60050000 size 12".
Here's a log:
```
Playing raw data '16/j16.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Playing raw data '16/j16.wav' : Signed 16 bit Little Endian, …
```
=> Fix playback and capture multiple runs which occasionally fails with Input/output error

scripts/docker_build/sof_builder/Dockerfile
Required to remove the copy hack introduced in
commit eb4373cb6143 (".github: new installer.yml")
=> [skip ci] Dockerfile: apt-get install tree

src/samples/audio/Kconfig, tools/topology/CMakeLists.txt, tools/topology/sof-imx8mp-wm8960-kwd.m4, tools/topology/sof/pipe-kfbm-no-lp-capture.m4
- Created KWD topology for iMX8M (adapting the KWD topology from APL arch)
- Enabled detect_test component default compilation for iMX arch (by enabling CONFIG_SAMPLE_KEYPHRASE in defconfig file)
=> Enabled KWD demo on iMX8M arch

src/platform/imx8/include/platform/lib/clk.h, src/platform/imx8/lib/clk.c
Looking at the timestamps from sof-logger it looks like
the DSP core frequency on i.MX8X is wrong.
Documentation confirms this. It should be 640Mhz.
=> platform: imx8: Fix clock frequency for i.MX8X

src/audio/codec_adapter/codec/cadence.c, src/audio/codec_adapter/codec/generic.c, src/audio/codec_adapter/codec_adapter.c, src/include/sof/audio/codec_adapter/codec/cadence.h, src/include/sof/audio/codec_adapter/codec/generic.h
This is the first PR in the series of preparing support for compressed streams decoding. Mainly, this takes care of adding the codec initialization phase during copy() function.
Initializaton phase for decoders needs to process input frames in order to get a valid header, parse it and figure out the codec parameters. It then also initalizes codec internal state and data structures.
=> Prepare for Cadence decoder support

src/audio/dai.c, src/drivers/imx/sai.c
Cherry-pick some fixes from DAI and IMX for v1.7 final release.
Original pull request was #3867
Fixes: #3809
=> [Stable v1.7] Backport some fixes for v1.7 final release

installer/.gitignore, installer/GNUmakefile, installer/README.md, installer/sample-config.mk, installer/tests/staging_sof_ref.txt, scripts/build-tools.sh, scripts/cmake/xtensa-toolchain.cmake, scripts/xtensa-build-all.sh, src/arch/xtensa/CMakeLists.txt
Straight cherry-pick -x, no conflict.
=> backport installer/ to stable-v1.7

src/arch/xtensa/CMakeLists.txt, src/arch/xtensa/include/arch/compiler_info.h, src/lib/lib.c
GCC configuration for ct-NG uses newlibc libc versions of common
memcpy() and memset(). Check this in makefile and lib.c so we can use
the correct versions.
=> compiler: use libc versions of memset, memcpy for GCC10 onwards

src/include/sof/samples/audio/detect_test.h, src/include/sof/samples/audio/kwd_nn/kwd_nn_config.h, src/include/sof/samples/audio/kwd_nn/kwd_nn_preprocess.h, src/include/sof/samples/audio/kwd_nn/kwd_nn_process.h, src/include/sof/samples/audio/kwd_nn_detect_test.h, src/samples/audio/CMakeLists.txt, src/samples/audio/Kconfig, src/samples/audio/detect_test.c, src/samples/audio/kwd_nn_detect_test.c
Extend kwd functionality by using a neural network for detection. 
Implemented a kwd detection functionality able to recognize some keywords by using a neural network (neural network is implemented in a lib linked with sof; this lib provide the preprocess & inference functions necessary in recognizing the keywords). Kwd functionality based on neural network is implemented in separate file (nxp_detect_test.c) and represents an alternative to the default kwd functionality (default_detect_test function). At this moment switch will be done by using the DEFAULT_DETECT macro found in detect_test.c source file.
=> Extend kwd functionality by using a neural network for detection

scripts/xtensa-build-all.sh
The configuration names with _2017 are a consequence of the way I did
the internal configuration update. To keep it simple I update these
build scripts.
With this change as well as the internal ones all i.MX platforms should be able to build on the Xtensa toolchain.
=> scripts: xtensa_build_all: Fix configuration names for i.MX

src/include/sof/audio/buffer.h, src/include/sof/spinlock.h
buffer_unlock() does not use flags.
=>  buffer.h: silences warning "flags may be used uninitialized"

src/drivers/imx/esai.c
ESAI allocates private data and retrieves this data using
dai_get_drvdata().
But this is never set using dai_set_drvdata() and sometimes
dai_get_drvdata() returns NULL.
So, after private data is allocated, set it using dai_set_drvdata().
Without this fix, on i.MX8QM, on playback we get:
root@imx8qmmek:~# aplay -Dhw:1,0 -f S16_LE -c 2 -r 48000 -d 5 -t raw /dev/urandom
Playing raw data '/dev/urandom' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
[  197.478128] sof-audio-of 556e8000.dsp: error : DSP panic!
[  197.483547] sof-audio-of 556e8000.dsp: error: runtime exception
[  197.489473] sof-audio-of 556e8000.dsp: error: trace point 0dead006
[  197.495658] sof-audio-of 556e8000.dsp: error: panic at :0
[  197.501064] sof-audio-of 556e8000.dsp: error: DSP Firmware Oops
[...]
Fixes: …
=> drivers: imx: esai: set private data after allocation

.github/workflows/pull-request.yml, .travis.yml, scripts/cmake/version.cmake
For at least two reasons:
- exposes sneaky change(s) performed by automation if/when any
- solves the mystery of the Source content hash (printed on the next line)
changing while the git version does not.
Example, at https://sof-ci.01.org/sofpr/PR3941/build8429/build/bdw_gcc.txt
-- Found Git: /usr/bin/git (found version "2.17.1")
-- GIT_TAG / GIT_LOG_HASH : v1.7-rc1-151-g023c4abacde1 / 023c4abac
-- Source content hash: 91f261ea
whereas at https://github.com/thesofproject/sof/runs/2166298087, xtensa-build-all
-- Found Git: /usr/bin/git (found version "2.17.1")
-- GIT_TAG / GIT_LOG_HASH : v1.7-rc1-151-g023c4abacde1 / 023c4abac
-- Source content hash: 67f31697
> solves the mystery of the Source content hash (printed on the next line)  changing while the git version does not.
Little -dirty …
=> version.cmake: add --dirty to git describe command

scripts/build-tools.sh, tools/topology/CMakeLists.txt, tools/topology/get_abi.sh
There was no [MAIN_]DEPENDS on the .m4 source file, so changes were not
triggering any rebuild.
=> topology/cmake: add missing .m4 dependency, fixes incremental build

CODEOWNERS
Request for owner has gone unacknowledged, ToT adapter is broken
suggesting we likely need additional reviewers given we have no existing
code owner.
=> owners: add cujomalainey as owner of codec adapter

.github/workflows/pull-request.yml
Will hopefully fix mysterious CI hangs.
=> .github/pull-request.yml: watch "main" branch instead of master

src/schedule/ll_schedule.c
Add some useful information logs about the task scheduling point with
ll_scheduler, which will help to capture logs once we hit scheduling
issue on some specific task.
=> ll_schedule: add logs about the scheduling point

scripts/docker_build/sof_builder/Dockerfile
Required by #3459 / #3975 "elfsize" proof of concept and probably by
other things too in the future - we use both ELF and Python
everywhere; it's surprising they haven't met each other yet.
=> [skip ci] docker: apt-get install python3-elftools

src/arch/xtensa/include/arch/string.h
Local string.h already includes C library string.h.
=> memcpy: remove duplicate memcpy and meset definitions in local string.h

src/include/sof/trace/trace.h, src/schedule/ll_schedule.c, src/trace/Kconfig
2 separate commits now.
See previous review in master branch PR #3944
=> ll_schedule.c: fix "uninitialized task_take" warning in CONFIG_TRACEV

.gitmodules
2 commits, see commit messages
=> Un-harcode rimage master branch and URL

scripts/cmake/version.cmake
In an ideal world, every CI engine records and shares the most important
CI information:
- current date and time in a well identified timezone
- git version of the pull request
- git version of the moving branch the PR is being merged with
In the real world we have multiple CI solutions and they unfortunately
cannot not all be trusted to perform their most basic job
correctly. Fortunately, they all make at least build logs available so
these very few lines of code adding very few lines of output cost near
zero extra build time and solve the problem once for all. I feel stupid
I didn't do this sooner, this would have saved me hours and hours in
vain requests and discussions and in trying to puzzle that information
together.
Sample outputs
```
-- Preparing Xtensa toolchain
version.cmake …
```
=> cmake: don't trust CI to record time and versions and log ourselves

src/audio/codec_adapter/codec_adapter.c
We are only setting the parameters on the allocation of the local buffer
which means if the params change on the next run it will not change and
break things.
=> codec_adapter: fix local buffer prepare

tools/logger/logger.c
Useful error messages when forgetting to use "sudo" or to change
permissions in udev.
Some places were printing the errno decimal. Others no specific error
at all.
Sample outputs:
```
error: Unable to open version file /sys/kernel/debug/sof/fw_version: Permission denied
error: Unable to open version file /sys/kernel/debug/sof/fw_version: No such file or directory
```
=> logger: use strerror()

CODEOWNERS
This patch adds two more code owners of codec_adapter.
=> codec_adapter: add mrajwa & dbaluta as code owners

tools/logger/convert.c, tools/logger/convert.h, tools/logger/logger.c
Add a new sof-logger -e 0/1 relative timestamps option where the
TIMESTAMP column is relative to the first entry seen.
Removes many digits and makes the TIMESTAMP column much more readable in
short logs.
Also stop showing "NaN" as the first DELTA like something went
wrong. Show zero instead.
The new option is off by default when using -r(aw) and on otherwise.
The first entry is kept always absolute.
Before:
```
TIMESTAMP              DELTA C# COMPONENT     LOCATION                      CONTENT
[6653843012.343750] (             NaN) c0 dma-trace    src/trace/dma-trace.c:339     ERROR FW ...
[6653843111.510417] (       99.166664) c0 ll-schedule  ./schedule/ll_schedule.c:229  perf ll_work
[6653843309.010417] (      197.500000) c0 ll-schedule  ./schedule/ll_schedule.c:399  task add …
```
=> logger: new relative timestamps option, relative to first entry seen

tools/topology/CMakeLists.txt, tools/topology/sof-glk-da7219-kwd.m4
codec chip playback loopback to capture stream.
=> Topology: Add support for MAX98390 echo reference capture

zephyr/CMakeLists.txt
Fixes commit 093589899a2e ("pipeline: remove legacy static pipeline
support") that broke zephyr compilation.
=> zephyr/cmake: stop trying to build removed pipeline_static.c

src/audio/codec_adapter/codec_adapter.c
This PR contains some fixes from @cujomalainey in order to prepare https://github.com/thesofproject/sof/pull/3999 and also 
2 fixes discovered while debugging cadence codecs.
=> Codec adapter cleanups and fixes

tools/topology/CMakeLists.txt, tools/topology/sof-tgl-max98373-rt5682.m4
This patch adds IIR support in the tgl-max98373-rt5682 topology to allow
the frequency response of the headset output to be tuned.
Signed-off-by: Ross Chisholm <ross.chisholm@xperi.com>
=> topology: adding support for IIR component

src/audio/codec_adapter/CMakeLists.txt, src/include/sof/audio/codec_adapter/codec/MaxxEffect/Control/Direct/MaxxEffect_Revision.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/Control/RPC/MaxxEffect_RPC_Server.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/Initialize/MaxxEffect_Initialize.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/MaxxEffect.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/MaxxStatus.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/MaxxStream.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/Process/MaxxEffect_Process.h, src/include/sof/audio/codec_adapter/codec/MaxxEffect/Process/MaxxEffect_Reset.h
add Waves MaxxEffect API definition.
API is required to build SOF with Waves codec.
Signed-off-by: Oleksandr Strelchenko <oleksandr.strelchenko@waves.com>
=> audio: codec_adapter: add Waves api

src/drivers/intel/cavs/ipc.c
The IPC handler does this for us already on any IPC failure.
Redundant code so remove it.
=> ipc: cavs: dont send IPC ABI reply specific en IPC driver

src/drivers/Kconfig, src/drivers/imx/Kconfig
This will be the home of IMX drivers config option
definitions.
This moves IMX_DMA config option to imx/Kconfig.
=> drivers: Create imx drivers Kconfig file

doc/sof.doxygen.in
Lets try and keep 3rd party codec headers as-is without any modifications.
This include doxygen as some references may be in closed headers.
Signed-off-by: Liam R Girdwood <liam.r.girdwood@intel.com>
=> doxygen: codecs: exclude 3rd part codec headers from Doxygen

installer/GNUmakefile, installer/sample-config.mk
Kudos to Pierre-Louis for advertising this cool feature
=> installer: change default destination to /lib/firmware/updates

src/audio/codec_adapter/codec_adapter.c
First, fixes for compress audio when even there hasn't been anything produced local buffer still has some valid data which needs to be sent to the sink.
Second, fixes processing loop were we need to update source/local_buffer bytes inside the loop. Otherwise, there are problems when the loop takes more than 1 iteration.
=> Codec adapter processing fixes

LICENCE, src/include/sof/audio/cadence/aac_dec/xa_aac_dec_api.h, src/include/sof/audio/cadence/mp3_dec/xa_mp3_dec_api.h
This files provide the interface for interacting with
Cadence binaries in order to set specific parameters
or decode API errors.
These files were received from Cadence after they kindly agreed
to release them with a permissive license.
Do not edit this by hand! Only update this when Cadence
releases a new version!
=> cadence: Add Cadence mp3/aac headers

src/audio/codec_adapter/codec/generic.c
This fixes the following checkpatch.pl warning:
WARNING: braces {} are not necessary for single statement blocks
172: FILE: src/audio/codec_adapter/codec/generic.c:172:
=> codec_adapter: Remove braces around single statement

tools/fuzzer/fuzzer.h, tools/fuzzer/topology.c
ARRAY_SIZE was being redefined, simplest option is to remove, but I think
this code has to additionally be compiled with external Fuzzer. Fix build.
=> fuzzer: fix build as with header order and ARRAY_SIZE redefinition

tools/topology/development/sof-tgl-nocodec-ci.m4
Change to run smart_amp pipelines on DSP core 1, this will help reduce
the core 0 usage and add multi-core to the CI coverage.
=> topology: sof-tgl-nocodec-ci: change to run smart_amp on core 1

smex/ldc.c
Logging versions like "3:18:1" deceive Emacs (and maybe others) because
they look like an error location produced by a compiler. When compiling
Emacs wrongly believes this an error location and offers to jump to it.
The colon ':' is also a reserved character in most filesystems and an
unusual version separator.
Before:
fw abi main version:	3:18:1
fw abi main version:	3:18:1
After:
fw abi main version:	3.18.1
fw abi main version:	3.18.1
=> smex: log versions with a dot (3.18.1) instead of a colon (3:18:1)

src/arch/xtensa/CMakeLists.txt
Will also make git commands (blame, merge, revert, rebase,
cherry-pick,...) much less likely to fail.
Also more readable and more obvious that -imacros is not nested.
=> xtensa/CMakeLists.txt: split very long CFLAGS line

tools/testbench/include/testbench/file.h
IPC is aligned on at least 4 bytes, removes compiler warning about packed
data being aligned on 1 bytes.
In file included from /home/lrg/work/sof/sof/tools/testbench/file.c:23:
/home/lrg/work/sof/sof/tools/testbench/include/testbench/file.h:59:1: error: alignment 1 of ‘struct sof_ipc_comp_file’ is less than 4 [-Werror=packed-not-aligned]
59 | } __attribute__((packed));
| ^
=> testbench: align IPC structures on 4 bytes.

installer/GNUmakefile, installer/sample-config.mk
This reverts the main change in commit
65ade5a4f973f021918955fefb16e95943e7a66f.
There are too many test changes required first, see a tentative list in
https://github.com/thesofproject/sof-test/pull/645
=> Revert "installer: change default destination to /lib/firmware/updates"

tools/topology/platform/common/ssp.m4
The m4 ifelse check on macro parameters is not working as expected.
If optional parameters are not passed, an empty string is written
to output conf file, instead of the "0" string specified in
the ifelse statement.
This has not caused functional errors as the empty string has
been interpreted as zero. Fix the logic despite this so that this
is not copied to other macros.
=> topology: ssp: fix a bug in passing SSP_CONFIG_DATA args

tools/topology/platform/common/ssp.m4
The m4 ifelse parameters using defn() are not working as expected.
If more than 3 parameters are passed to SSP_MULTI_CONFIG_DATA(),
the values are not correctly passed.
Fix this by removing defn() and correctly quoting the whole
ifelse section.
=> topology: ssp: fix a bug in passing SSP_MULTI_CONFIG_DATA args

zephyr/CMakeLists.txt
Align the Zephyr build to recent file name changes.
=> zephyr: fix build with recent file name changes.

src/audio/dai.c
We need to support calling to dai_config multiple times for a dai, as
the components and pipelines could be created/destroyed dynamically.
To support this, we should free the allocated DMA channel and
re-allocate it when needed, for all DAI types.
=> dai: dai_config refinement

tools/logger/logger.c
Add missing "break" so the -e option stops spilling on the -f precision
option. Fixes commit 53ce8b9d9f82 ("logger: new relative timestamps
option, relative to first entry seen"). Since that commit the -e option
was wrongly assigned to the precision too.
=> logger: fix precision bug introduced by new -e option

CMakeLists.txt, scripts/run-mocks.sh, src/arch/host/CMakeLists.txt, src/platform/library/include/platform/lib/memory.h, test/cmocka/CMakeLists.txt, test/cmocka/cmocka-host-gcc-toolchain.cmake, test/cmocka/cmocka-xtensa-gcc-toolchain.cmake, test/cmocka/src/CMakeLists.txt, test/cmocka/src/audio/pcm_converter/pcm_float.c, test/cmocka/src/audio/pipeline/CMakeLists.txt, test/cmocka/src/common_mocks.c, test/cmocka/src/lib/CMakeLists.txt, test/cmocka/src/math/CMakeLists.txt
This PR allows the tests to be run on the host (i.e. build all mocks as local command line tests) and also to build on xtensa GCC. The xtensa GCC support is build only, as there require more work to run on qemu.
=> cmocka updates for host tests and GCC xtensa

src/schedule/timer_domain.c
Allow building SOF with Zephyr with Xtensa platforms other than cAVS.
BugLink: https://github.com/thesofproject/sof/issues/4046
=> zephyr: CONFIG_CAVS_TIMER is only required on cAVS platforms

tools/topology/CMakeLists.txt, tools/topology/sof-jsl-rt5682.m4
Allows the IIR component to be added to the jsl-rt015 topology allowing tuning
Signed-off-by: Ross Chisholm <ross.chisholm@xperi.com>
=> topology: adding optional support for IIR component on jsl-rt015 topology

src/audio/dai.c, src/include/sof/lib/dai.h
Add "hw_params" callback in order to provide the
stream information like stream rate, number of channels
and format to DAI IP driver.
Signed-off-by: Viorel Suman <viorel.suman@nxp.com>
=> dai: add DAI driver "hw_params" callback

src/probe/probe.c
Use the right header file to fix the compilation
error when building with probes enabled.
=> probe: fix compilation error

src/platform/apollolake/include/platform/lib/memory.h
Increase the count of the runtime heap 256 Bytes block on apollolake to
satisfy the buffer requirement of the new implemented dynamic DAI config
feature.
Fixes: 6c2cdffd0239 ("dai: dai_config refinement")
This should fix issue https://github.com/thesofproject/sof/issues/4069
=> platform: apollolake: increase runtime heap 256B count

src/include/ipc4/pipeline.h
Add invalid state to pipeline enum for completeness.
=> ipc4: add pipeline state invalid

zephyr/CMakeLists.txt
Commit b3f195e92a71 ("zephyr: fix build with recent file name changes.") partially fixed a regression, caused by 4e436f8570be ("ipc: split out ipc functions into separate files.") partially. This patch completes the fix.
=> zephyr: fix build: add a missing IPC file

zephyr/wrapper.c
SOF registers IRQ handlers dynamically, therefore disabling support for dynamic interrupts for SOF builds doesn't make much sense. However, this can be used to at least increase compile-time testing coverage and potentially enable applications, not using dynamic interrupt registration.
=> zephyr: allow building with dynamic interrupts disabled

tools/topology/development/sof-tgl-nocodec-ci.m4
This reverts commit cd2444adbf8821d33e098b071b40dab2931d6a8e.
Reverting this to unblock the CI runningon tgl-nocodec-ci platform, multi-core support
is not ready yet in the Linux side.
=> Revert "topology: sof-tgl-nocodec-ci: change to run smart_amp on core 1"

src/audio/pcm_converter/pcm_converter_hifi3.c
XT_ROUND_S is available only when you include option of
"Xtensa's single precision FPU option (scalar)".
IF current DSP includes optional vector FPU (single precision).
FIROUND.S (with appropriate RoundMode state set) followed by
TRUNC.S can be used to emulate Xtensa scalar FPU’s ROUND.S, CEIL.S and
FLOOR.S instructions."FIROUND.S", does round, but no scaling.Result
still in float format.Use TRUNC.S to scale it and truncate as necessary.
Fix :https://github.com/thesofproject/sof/issues/4042
Signed-off-by: Yang XiaoHua <yangxiaohuamail@gmail.com>
=> pcm_converter: Fix architectures not supporting XT_ROUND_S

tools/logger/convert.c
This makes the display of the mailbox ring buffer log much less
confusing. It should not happen with the DMA trace but will behave the
same in case something goes wrong.
Before this commit the only clue that wrapping had happened was a NaN in
the delta column (instead of the negative value).
The "other?" is because the start of the mailbox is sometimes corrupted,
or the timestamp goes sometimes back at boot for no obvious reason. In
other words this new separator is useful to highlight bugs too.
Absolute mode -e 0 with this commit:
```
TIMESTAMP         DELTA C# COMPONENT          LOCATION
[22598174808] (        11) c0 ipc                  src/ipc/....
[22598174824] (        15) c0 ipc                  src/ipc/....
[22598443257] (    268433) c0 dma-trace             src/trace/.... …
```
=> logger: print a separator when the timestamp goes back in time

src/platform/imx8m/include/platform/lib/dma.h, src/platform/imx8m/lib/dma.c
With SDMA2 in place now it is shared by both A and HiFi cores
- this breaks 8MP EVK + WM8960 topology. Remove SDMA2 so that
SDMA2 remains assigned to A core and SDMA3 assigned to HiFi core
as it was initially planned.
Suggested-by: Paul Olaru <paul.olaru@nxp.com>
Signed-off-by: Viorel Suman <viorel.suman@nxp.com>
=> imx8m: remove SDMA2

src/schedule/ll_schedule.c
In some situations the domain clear routine might encounter
a case, when the number of clients is decremented and 0,
as such, a subsequent subdivision will result in an integer underflow.
Fixes #3950 
Fixes #3949 
Fixes #3947
=> scheduler: guard against subdivision underflow on domain clear

src/include/sof/atomic.h
fix https://github.com/thesofproject/sof/issues/4049
Signed-off-by: yxh yangxiaohuamail@gmail.com
=> fix zephyr conflicting types atomic

zephyr/wrapper.c
The use of Zephyr LOG_*() API in SOF is breaking compilation. Replace it with with the native trace logging until a proper fix is available.
Fixes https://github.com/zephyrproject-rtos/zephyr/pull/33963
=> zephyr: fix logging build breakage

src/include/ipc4/alh.h
=> ipc4: add alh header file for ipc4

src/math/trig.c
math.h is an external header, provided by libc, whereas SOF is a stand-alone executable, that must not depend on any system headers. Particularly math.h isn't available when building with Zephyr. The only inclusion of math.h in SOF currently is only needed for the M_PI definition. Define it locally with a slightly different name to eliminate the dependency and fix Zephyr builds.
=> math: remove math.h dependency

src/include/sof/audio/pipeline.h, src/include/sof/ipc/topology.h, src/ipc/helper-ipc4.c
we probably need to revisit the mapping when running in real life...
This is an initial "guess".
=> ipc4: add pipeline get status function

src/audio/asrc/asrc.c, src/audio/dai.c
The start sequence has changed to ASRC prepare before DAI, so there was as a null pointer access issue. The first patch adds check for null and the second patch moves setup to trigger start.
=> Audio: DAI: ASRC: Fix DSP panic due to timestamping setup request in asrc_prepare()

installer/GNUmakefile
After commit 5ca0e9bba3e6d ("topology: Use generic name for 8qxp/8qm")
installer test is broken as we also need to update the check tree
topologies to the new naming.
So, fix this by replacing imx8qxp naming with imx8. But while we are at
it choose a better random topology, sof-imx8-wm8960.tplg instead of
sof-imx8-nodec.tplg
=> installer: Fix installer test

tools/logger/convert.c
Every log file should have a date.
ktime can be related to the TIMESTAMP column. It is especially useful to
spot logs delayed or stuck.
Some logs use ktime while others use a date and it can be sometimes
difficult to connect them with one another. This header can help.
Before:
```
TIMESTAMP (us) DELTA C# COMPONENT CONTENT
[  5120116529] (  0) c0 dma-trace ERROR FW ABI 0x3012001 ...
```
After:
```
TIMESTAMP (us) DELTA C# COMPONENT  CONTENT ktime=5132.663s @ 2021-04-27 14:36:09 -0700 PDT
[  5120116529] (  0) c0 dma-trace ERROR FW ABI 0x3012001 ...
```
=> logger: add ktime and date in header

src/include/ipc4/error_status.h, src/include/ipc4/module.h, src/ipc/handler-ipc4.c, src/ipc/helper-ipc4.c
Translate module initialization to component new. Current
problem is the interface of create can't pass module
config in host box. Another solution is to read host box in
component directly so we don't need to change current interface.
Also add error code for IPC4. All IPC4 functions should
use these error code.
=> ipc4: add basic module init support

scripts/xtensa-build-all.sh
... because the latter does not print on stderr when not found; so IDEs
and CIs don't display this as a warning.
Also remove the "... and ignore set -e" comment that made sense at the
time of commit cad86dc ("scripts: xtensa-build: fix alias detection
for bxt/apl gcc") but not anymore.
=> xtensa-build-all.sh: replace "type xtensa-bxt-elf-gcc" with "command -v"

.github/workflows/zephyr.yml, scripts/xtensa-build-zephyr.sh, zephyr/docker-build.sh
3 commits, see messages, especially: `xtensa-build-zephyr: do not clone a second version of sof.git`
Related rimage.h background info: https://github.com/zephyrproject-rtos/sof/pull/7#issuecomment-814539846
=> [SKIP CI] .github: add zephyr build

tools/oss-fuzz/fuzz_ipc.c
looks like with the new ipc mechanisms we changed the function signature
and moved casting the message from platform code to ipc code.
=> oss-fuzz: fix build

src/audio/codec_adapter/codec/cadence.c, src/audio/codec_adapter/codec/generic.c, src/audio/codec_adapter/codec_adapter.c, src/include/sof/audio/codec_adapter/codec/generic.h
This patchset includes:
- state machine rework (simplify + add additional states IDLE + PROCESSING + RESETTING)
- improve resetting procedure (don't reset codec right away while in PROCESSING state)
- allow runtime config to be applied earlier
=> codec_adapter: allow apply config earlier + state machine rework 

src/audio/codec_adapter/CMakeLists.txt, src/audio/codec_adapter/Kconfig
This will be statically linked with sof when Cadence specific
config options are set.
=> codec_adapter: Add config options to specifify Cadence libraries location

.github/workflows/scant_fuzzer.yml
This is NOT how to properly compile the fuzzer, this is only to detect
earlier and faster problems like
https://github.com/thesofproject/sof/pull/3824 (288e228) and
https://github.com/thesofproject/sof/pull/4118 (758e7be)
In other words, when reverting the oss-fuzz parts of either of these
commits this build fails as desired.
=> [SKIP CI] .github: add scant_fuzzer.yml build

src/audio/codec_adapter/codec_adapter.c, src/audio/dai.c, src/audio/drc/drc_generic.c, src/audio/host.c, src/audio/kpb.c, src/audio/mixer.c, src/audio/mux/mux.c, src/include/sof/math/numbers.h, src/schedule/timer_domain.c
_[#4002 was a completely different and rejected solution to this problem , please start the review there]_ 
For compatibility with Zephyr, MIN and MAX macros are downgraded to the
basic, compile-time, standard compliant and unsafe implementation.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/33567
See much longer commit messages.
=> numbers.h: downgrade MIN() and MAX() to unsafe versions

src/audio/dai.c
If processing format is restricted from Kconfig there's a possibility of
pcm_converter not having proper conversion function. Thus check for NULL
in dai to avoid crashes.
=> dai: add check for NULL pcm converter function

src/include/sof/math/numbers.h
Undefining and re-defining MIN/MAX when already defined is
convoluted. Simply define them if not `__ZEPHYR__` instead.
=> numbers.h: simplify #ifndef ZEPHYR for MIN and MAX

tools/topology/development/CMakeLists.txt
This patch adds development topology to run ASRC playback and
capture via SSP port to headset plug. We don't have many topologies
to test ASRC in current development devices so this is useful
=> Topology: Add build of topology to run ASRC in cml-rt1011-rt5682

scripts/xtensa-build-zephyr.sh
Fixes 33c5f5d38e ("xtensa-build-zephyr: do not clone a second version of
sof.git")
The very first version of this test was checking whether the rimage/
directory exists, which proves nothing. So I switched to
rimage/CMakelists.txt but forgot change the `test` flag.
=> [SKIP CI] build-zephyr.sh: don't update rimage every time we run

scripts/xtensa-build-zephyr.sh
By default, the Zephyr build does not log its version. The fix has
already been submitted at
https://github.com/zephyrproject-rtos/zephyr/pull/34842 however:
- 34842 may take some time. Zephyr reviewers are even busier than the
SOF reviewer.
- 34842 could even be rejected
- 34842 will at best log the SHA1 and no context. This is more verbose
and future-proof because it supports more complex situations like
testing a pull/12345/merge
As seen in (unrelated) PR #4123, we need Zephyr git versions NOW.
=> xtensa-build-zephyr.sh: show zephyr short git log / version after clone

src/idc/idc.c, src/include/sof/drivers/idc.h, src/init/init.c, src/platform/Kconfig, src/schedule/timer_domain.c, src/schedule/zephyr.c, zephyr/CMakeLists.txt, zephyr/edf_schedule.c, zephyr/schedule.c, zephyr/wrapper.c
The first (IIRC) batch of SOF Zephyr multicore patches. Limited functionality: on APL and CNL booting, secondary core can be powered on and initialised, topology can be loaded, but DMIC isn't working even on core 0, actual audio streaming on core 1, e.g. to HDMI isn't working yet either.
=> Zephyr multicore batch 1

src/audio/CMakeLists.txt, src/audio/Kconfig, src/audio/igo_nr/CMakeLists.txt, src/audio/igo_nr/igo_nr.c, src/include/sof/audio/igo_nr/igo_lib.h, src/include/sof/audio/igo_nr/igo_nr_comp.h, src/include/user/igo_nr.h, tools/topology/m4/igo_nr.m4, tools/topology/platform/intel/intel-generic-dmic-kwd.m4, tools/topology/sof-smart-amplifier.m4, tools/topology/sof-tgl-max98373-rt5682.m4, tools/topology/sof/pipe-igonr-capture.m4
Added intelliGo noise reduction wrapper codes and topology.
The proprietary static library shall be released by intelliGo via private channel upon request.
=> audio: igo_nr: added igo_nr component

scripts/xtensa-build-zephyr.sh
More robust support for "manual" installations.
Also rephrase usage string to remove a single quote breaking
the shell parser in one editor I use (sorry).
=> [SKIP CI] xtensa-build-zephyr: add mkdir -p modules/audio

src/samples/audio/smart_amp_test.c, zephyr/CMakeLists.txt, zephyr/wrapper.c
Properly include these components in Zephyr based builds (if enabled in kconfig).
=> zephyr: fixes to kpb and sample-smart-amp components

tools/topology/CMakeLists.txt
Builds a configuration of the max98373-rt5682 topology with AMP_SSP=2
defined and includes the IIR component
Signed-off-by: Ross Chisholm <ross.chisholm@xperi.com>
=> topology: adding IIR component on max98373-rt5682 topology

src/audio/crossover/crossover.c, src/audio/smart_amp/smart_amp.c
Still a few component in main without UT_STATIC.
=> audio: add UT_STATIC to crossover and smart_amp

src/arch/xtensa/include/arch/lib/cache.h, src/platform/intel/cavs/include/cavs/lib/memory.h, src/schedule/ll_schedule.c, src/schedule/timer_domain.c
This set of patches allows execution of audio pipelines on secondary cores. A modified pipeline was used to test HDMI playback on core 1 on UP-squared, playback worked correctly.
=> Zephyr scheduling fixes

src/audio/pipeline/pipeline-graph.c, src/include/sof/audio/pipeline.h, src/ipc/helper-ipc3.c, test/cmocka/src/audio/pipeline/pipeline_new.c
Move the code that sets the scheduling comp for
a pipeline to ipc_pipeline_complete(). This removes the
restriction that the scheduling comp must be set up
before the pipeline widget and provides the
flexibility in the kernel to set up the widgets
in any order while parsing topology.
=> pipeline: set scheduling comp during complete

src/audio/igo_nr/LICENSE, src/audio/igo_nr/igo_nr.c, src/include/user/igo_nr.h
This PR resolved the issues in #4017 and added license file.
1. Removed NULL assignment of cd `(L223: igo_nr.c)`
2. Removed ENUM in `igo_nr_cmd_get_value` and `igo_nr_cmd_set_value`
3. Added new line in L556:igo_nr.c
4. Moved `struct IGO_PARAMS` from `igo_nr.c` to `igo_nr.h` since `sof_igo_nr_config` needs it.
5. Added license file.
Signed-off-by: fy.tsuo <fy.tsuo@intelli-go.com>
=> audio: fix igo_nr wrapper code issues.

tools/topology/CMakeLists.txt
Somehow we only support this configuration for BYT, but there are
Baytrail devices using the same codec.
BugLink: https://github.com/thesofproject/sof/issues/4160
=> topology: add missing configuration for byt-max98080

src/audio/Kconfig
Without this patch codec adapter submenu is displayed after IGO NR
component resulting in something like this:
[*] Codec adapter
[*] IGO NR components
Codec adapter codecs
After this patch is applied the display will be as expected:
[*] Codec adapter
Codec adapter codecs
[*] IGO NR components
=> audio: Fix codec adapter submenu display

scripts/docker-run.sh, scripts/docker_build/sof_builder/Dockerfile, scripts/docker_build/sof_builder/docker-build.sh, scripts/docker_build/sof_qemu/Dockerfile, scripts/docker_build/sof_qemu/docker-build.sh
fixes: https://github.com/thesofproject/sof/issues/3831
=> [skip-ci] Remove proxy setting and upgrade to Ubuntu 20.04 for SOF docker images

.github/workflows/zephyr.yml, zephyr/docker-build.sh
zephyr/docker-build.sh: remove apt update / install libssl-dev
The Zephyr image has been updated in
zephyrproject-rtos/docker-image#58
This will save some time and even better avoid llvm.org
glitches like this one:
https://github.com/thesofproject/sof/pull/4089/checks?check_run_id=2554961695
=> [SKIP CI] zephyr/docker-build.sh: remove apt update / install libssl-dev

src/drivers/intel/cavs/timer.c, src/include/sof/schedule/ll_schedule_domain.h, src/include/sof/schedule/schedule.h, src/schedule/dma_multi_chan_domain.c, src/schedule/dma_single_chan_domain.c, src/schedule/ll_schedule.c, src/schedule/schedule.c, src/schedule/timer_domain.c
clean up of the ll_scheduler domain clients/tasks management.
ll_schedule: domain client/task refinement
Refinement to make the domain client/task management more clear:
a. update the total_num_tasks and num_clients in the helper pair
domain_register/unregister().
b. update the enabled[core] and enabled_clients in the helper pair
domain_enable/disable().
c. for the completed task, do the domain client/task update in the new
created helper schedule_ll_task_done().
d. cleanup and remove the client/task management from the ll_schedule
helpers schedule_ll_clients_enable(), schedule_ll_tasks_run(),
schedule_ll_domain_set() and schedule_ll_domain_clear().
This is aim to fix #3947 #3949 #3950.
Without those refinement, the num_clients was not …
=> LL scheduler domain refinement

src/audio/mux/mux.c
A wrong error message was added in helper get_stream_index(), remove to
fix it.
Fixes: 80666b7cc7a9 ("ipc: component: abstract the component creation API")
=> mux: remove the wrong error message

src/arch/xtensa/include/arch/lib/cache.h, src/platform/imx8/imx8.x.in, src/platform/imx8m/imx8m.x.in
The _memmap_cacheattr_reset linker script variable has
dedicate cache attribute for every 512M in 4GB space
1: write through
2: cache bypass
4: write back
F: invalid access
For imx, implement is_cached() based on
_memmap_cacheattr_reset.
Without this fix, when loading a topology we get:
sof-audio-of 556e8000.dsp: error: reply expected 20 got 12 bytes
sof-audio-of 556e8000.dsp: error: ipc error for 0x30010000 size 20
sof-audio-of 556e8000.dsp: error: DSP failed to add widget id 0 type 23 name : PCM0P stream Passthrough Playback 0 reply 0
sof-audio-of 556e8000.dsp: ASoC: failed to load widget PCM0P
sof-audio-of 556e8000.dsp: ASoC: topology: could not load header: -22
sof-audio-of 556e8000.dsp: error: tplg component load failed -22
sof-audio-of 556e8000.dsp: error: failed to load DSP …
=> imx: invalidate cache for specific address range only

src/audio/dai.c
This is similar with:
commit 761bbac5aca6 ("host: dai: limit number of bytes copied to one
period") which limits the number of copied bytes for CAPTURE direction.
This patch does the same thing for PLAYBACK direction.
We need this with codec adapter component that most of the time
will produce more than period_bytes in a period.
DAI will copy more than on period_bytes at a time and this
affects sound quality.
=> dai: limit number of bytes copied to one period for all directions

tools/topology/sof-tgl-sdw-max98373-rt5682.m4
Add BT offload support for ADL platform:
PCM14  playback Bluetooth
PCM15  capture Bluetooth
=> topology: adl-sdw-max98373-rt5682: Add BT offload support

tools/topology/development/sof-tgl-nocodec-ci.m4
This patch moves DMIC pipeline to run on DSP core 2,
and SSP1 pipelines to run on DSP core 3 for multi-core
verification.
=> topology: sof-tgl-nocodec-ci: run pipelines on different cores

.github/workflows/codestyle.yml, .github/workflows/installer.yml, .github/workflows/ipc_fuzzer.yml, .github/workflows/pull-request.yml, .github/workflows/scant_fuzzer.yml, .github/workflows/zephyr.yml
Do full fuzzer build as part of the CI
Also consolidate all yamlint actions into a single job
=> Update fuzzer build in CI to use oss-fuzz tooling

src/include/sof/lib/agent.h, src/ipc/handler-ipc3.c, src/lib/agent.c, src/platform/intel/cavs/include/cavs/lib/memory.h, src/platform/intel/cavs/lib/dai.c, src/platform/intel/cavs/lib/dma.c, src/platform/intel/cavs/lib/memory.c, src/platform/intel/cavs/lib/pm_runtime.c
this addresses one of the reasons of https://github.com/zephyrproject-rtos/zephyr/issues/35299 but doesn't fix it completely.
=> zephyr: fix a power-down exception

.github/workflows/ipc_fuzzer.yml
... because it has definitely helped reproduce compilation issues in the
past in just two lines without going through the whole setup process,
see a list of examples in #4126.
=> [SKIP CI] .github/ipc_fuzzer: add back local compilation hack as a comment

src/ipc/helper-ipc3.c
ASRC new() receives incorrect topology tokens values before this
fix. It occurred as pipeline DAI find fail for capture direction
ASRC.
Fixes #4193
=> IPC: Handle ASRC as ASoC component type and not as process type

Kconfig, src/drivers/dw/Kconfig, src/drivers/dw/dma.c, src/platform/Kconfig
Add namespace to DMA related Kconfig options at the top-level Kconfig and move (one) driver-specific options into a more appropriate driver-specific Kconfig.
=> kconfig: clean up DMA related entries at top-level

src/audio/dai.c, src/audio/kpb.c, src/drivers/imx/esai.c, src/drivers/imx/sai.c, src/drivers/intel/alh.c, src/drivers/intel/baytrail/ssp.c, src/drivers/intel/dmic.c, src/drivers/intel/haswell/ssp.c, src/drivers/intel/hda/hda.c, src/drivers/intel/ssp/ssp.c, src/include/sof/audio/component.h, src/include/sof/audio/component_ext.h, src/include/sof/audio/ipc-config.h, src/include/sof/ipc/common.h, src/include/sof/ipc/topology.h, src/include/sof/lib/dai.h, src/ipc/CMakeLists.txt, src/ipc/dai-ipc3.c, src/ipc/handler-ipc3.c, src/ipc/helper-ipc3.c, src/platform/library/lib/dai.c, src/platform/library/platform.c, tools/testbench/common_test.c, zephyr/CMakeLists.txt
Currently the IPC DAI configuration is tightly bound to the IPC major version. This PR abstracts this interface so that other IPC majors can be used to configure DAIs. The DAI drivers themselves still use IPC major 3, but this opens up the ability to send NHLT configuration blobs.
=> Abstraction of IPC DAI configuration

src/include/sof/math/trig.h, src/math/trig.c
Introduce static inline function for sin() and cos()
function
=> Math: Trignometry: Cordic sine() and cos()

src/platform/intel/cavs/include/cavs/lib/memory.h
The Zephyr linker scripts for cavs20/25 do not map sections
on uncached RAM, so the memory accesses to uncached memory will
fail. This shows up as a DSP panic while loading initial topology.
=> cavs: memory: fix panic on tplg load for zephyr on cavs20/25

src/audio/igo_nr/igo_nr.c, src/include/sof/audio/igo_nr/igo_nr_comp.h, tools/topology/platform/intel/intel-generic-dmic-kwd.m4, tools/topology/sof-tgl-max98373-rt5682.m4
1. Roll back SSP setting from 16K sampling rate to 48K. Meanwhile igo_nr supports 48K-in-48K-out now.
2. Offload igo_nr to core 1.
=> audio: igo_nr: max98373-rt5682: roll back SSP clock setting

zephyr/include/sof/trace/trace.h
Use the Zephyr sys/printk.h when Zephyr RTOS is used.
Suggested-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
=> zephyr: trace: use zephyr utilities when enabled

src/audio/kpb.c, src/idc/idc.c, src/include/sof/lib/clk.h, src/ipc/handler-ipc3.c, src/lib/agent.c, src/lib/clk.c, src/lib/wait.c, src/platform/library/lib/clk.c, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, test/cmocka/src/common_mocks.c, zephyr/edf_schedule.c
The compiler warning only triggers in Zephyr builds, others are all cosmetic improvements
=> A compiler warning and cosmetic improvements

zephyr/include/sof/trace/trace.h
Commit 8357dcf793f4 ("zephyr: trace: use zephyr utilities when enabled")
added Zephyr's sys/printk.h in order to fix:
warning: implicit declaration of function 'printk'.
Remove #ifdef __ZEPHYR__ macro since this is not needed, because
the whole file is for Zephyr only.
Fixes: 8357dcf793f4 ("zephyr: trace: use zephyr utilities when enabled")
=> zephyr: trace: remove useless #ifdef __ZEPHYR__ macro

tools/topology/m4/utils.m4
Remove definition of s24_4le from COMP_SAMPLE_SIZE macro as it is not
used anywhere. Instead all pipelines are using s24le definition and the
COMP_SAMPLE_SIZE macro works only because it defaults to 4 bytes.
=> topology: remove obsolete s24_4le from COMP_SAMPLE_SIZE

tools/topology/platform/common/ssp.m4
Add all same tokens to SSP_CONFIG_DATA that we have in
SSP_MULTI_CONFIG_DATA.
=> topology: add missing tokens in SSP_CONFIG_DATA

.github/workflows/tools.yml, scripts/build-tools.sh, tools/CMakeLists.txt, tools/fuzzer/README.md, tools/logger/convert.c
2 commits related to recent #4141
=> add build-tools.sh ALL to github actions, lost with Travis

src/audio/dai.c, src/drivers/dw/dma.c, src/ipc/dai-ipc3.c
For dw dma controllers and channels, they are shared to multiple pipelines and cores.
For dai config and ssp config, the configuration may happen on different core with the one on the active time.
Add cache invalidate and writeback to ensure the consistency, to address issue https://github.com/thesofproject/sof/issues/3953
=> Multi core series -- cache & consistency

src/audio/codec_adapter/codec/cadence.c
This patch fixes the reset procedure of cadence codecs.
Potential fix for https://github.com/thesofproject/sof/issues/4104, not tested.
=> [WIP] codec_adapter: cadence: rework of reset & free procedures

Kconfig, Kconfig.xtos-build, Kconfig.xtos-dbg
Some of the top-level Kconfig options are not used at all when SOF is built with another RTOS like the SOF Zephyr module build. 
To make this more explicit at Kconfig level, move these options out from the top-level Kconfig file and exclude when needed.
=> kconfig: move more XTOS-only options out from top-level Kconfig

src/audio/copier.c, src/ipc/handler-ipc4.c
In current IPC3 path, we always first create host and dai last,
and our pipeline trigger, param, prepare are also designed to
follow this sequence. But for IPC4, source component is always
created first and sink component is last. For capture case dai
is source component and will be created first which is different
from IPC3.
This patch refine IPC4 path to make it compatible with current
pipeline design
=> ipc4: fix XRUN in capture path

src/drivers/dw/dma.c, src/drivers/imx/sai.c, src/lib/wait.c
Print register and its values if poll_for_register_delay fails. Also
check the return value and print warning in sai.c
=> wait: print register values if poll_for_register_delay fails

src/init/init.c
Define function secondary_core_init() only on MULTICORE.
This fixes:
warning: 'secondary_core_init' defined but not used
while building SOF with Zephyr for i.MX which has only one
DSP core.
=> init: define secondary_core_init() only on MULTICORE

tools/topology/CMakeLists.txt, tools/topology/platform/intel/intel-generic-dmic-kwd.m4
There are TGL devices using either PDM0 or PDM1 port for the DMIC16k
DAI for hotword detection. This patch adds the DMIC_DAI_LINK_16k_PDM
parameter and builds both versions.
Signed-off-by: Ben Zhang <benzh@chromium.org>
=> topology: Add a tgl-max98357a-rt5682 tplg with DMIC16k on PDM1

tools/topology/platform/intel/intel-generic-dmic-kwd.m4, tools/topology/sof-tgl-max98373-rt5682.m4
Define DMIC_PIPELINE_48k_CORE to assign dmic 48k pipeline core id and avoid impact to other platforms.
Signed-off-by: fy.tsuo <fy.tsuo@intelli-go.com>
=> topology: max98373-rt5682: define dmic 48k core id

src/schedule/timer_domain.c, src/schedule/zephyr_domain.c
Fixes a regression introduced by #3768
=> zephyr: ll_scheduler: fix a recent regression

src/trace/trace.c, tools/logger/convert.c
2 cosmetic commits + this "atomic" one:
Fixes bad commit b284ac3 ("debugability: Macro Metaprogramming
Refactor") that accidentally swapped mtrace_event() and
mtrace_event_atomic()
Before that accidental inversion, _trace_event_mboxN() functions invoked
spin_lock_irq() whereas _trace_even_mbox_atomicN() did NOT take
locks. That was consistent with the non-mbox, DMA variants of these
functions. As explained in the message of commit 3dca7b7 ("trace:
dma: Add atomic and nowait DMA tracing support."), functions with the
`_atomic()` suffix,, are meant to be used in atomic contexts where the
lock is _already_ taken.
Searching for spin_lock_irq() in the code after the bad commit shows
that the logic was inverted for the _mbox variants: the lock became used
for the _atomic() variants.
The reasons …
=> Restore original, 2018 mtrace_event(atomic) spin lock logic

tools/topology/sof-cnl-rt5682-sdw2.m4
HDMI PCM id should be 5, 6, 7 as described in the
sof-cnl-rt5682-sdw2.m4.
Let's use 5, 6, 7 as the HDMI PCM ID to match the UCM setting.
=> topology: fix hdmi pcm id for cnl-rt5682-sdw2

src/lib/alloc.c, src/platform/baytrail/include/platform/lib/memory.h, src/platform/haswell/include/platform/lib/memory.h, src/platform/imx8/include/platform/lib/memory.h, src/platform/imx8m/include/platform/lib/memory.h
This is aim to fix https://github.com/thesofproject/sof/issues/4237
For shared comp_dev, the address is modified to the uncached one, when
trying to free it, we need to change it back to the allocated cached one,
otherwise, we will free a wrong address with error log like below:
src/lib/alloc.c:462  ERROR free_block(): invalid heap = 0x9e062080, cpu = 1
=> alloc: add handle to free a buffer with uncached pointer

src/drivers/intel/hda/hda-dma.c
The DMA channels need to be shared among pipelines and DSP cores,
allocate buffer for it in RUNTIME_SHARED area.
=> hda-dma: allocate RUNTIME_SHARED for hda_chan

src/platform/apollolake/include/platform/lib/memory.h
This fixes https://github.com/thesofproject/sof/issues/4274
Increase the count of the 64 Bytes block to 160 to address the heap
runtime memory used up issue.
=> memory: apollolake: enlarge the heap runtime size

src/include/ipc4/gateway.h, src/include/ipc4/header.h, src/include/ipc4/module.h, src/include/ipc4/pipeline.h, src/include/sof/ipc/topology.h, src/ipc/ipc3/handler.c, src/ipc/ipc3/helper.c, tools/testbench/topology.c
This PR introduces the IPC4 interface that is used today on some devices. The IPC4 ABI cant be changed since it's not possible to change the middleware on devices that use the IPC4 ABI. This PR introduces the interfaces used to load topology.
This PR also further adds abstraction around the IPC based client APIs so that any IPC ABI major can be used to construct pipelines. Further PRs will follow that add logic around the interface.
=> ipc4: introduce initial IPC4 interface

tools/topology/CMakeLists.txt, tools/topology/sof-imx8-wm8960-kwd.m4
Add KWD topology for imx8: SAI1 and wm8960 codec
used for recording.
Signed-off-by: Viorel Suman <viorel.suman@nxp.com>
=> topology: imx8: add kwd component with wm8960 codec

src/include/sof/bit.h
These macros are useful for decoding bit fields.
=> Add GET_BIT() and GET_BITS() macros to bit.h

src/ipc/ipc3/helper.c
Pipelines can be shared between multiple PCM's. For example,
in the case of the sof-apl-nocodec, a part of pipeline 1
(mixer1.0 ->BUF1.2 ->PGA1.1-> BUF1.3 -> SSP0.OUT)
is shared between PCM0 and PCM7. Setting the source_comp for
pipeline 1 to NULL when PCM0 is stopped results in a panic.
So, hold off resetting the pipeline until the scheduler widget
is freed.
Fixes #4199
=> ipc: ipc3: Do not reset pipeline components during comp_free

CMakeLists.txt, installer/GNUmakefile, installer/sample-config.mk, src/init/ext_manifest.c, src/platform/baytrail/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/intel/cavs/platform.c
Makes even CONFIG_DEBUG builds (locally) deterministic by
default: (re)building twice produces the same binaries. Also a partial
fix for incremental builds: running "make" twice in a row now recompiles
fewer files because version.h does not keep changing.
Also makes sure non-debug builds can't use uninitialized strings in some
future security accident.
Fixes:
./scripts/checkpatch.pl -g aa85e2c0e956c
```
ERROR: Use of the '__DATE__' macro makes the build non-deterministic
+		.date = __DATE__,
ERROR: Use of the '__TIME__' macro makes the build non-deterministic
+		.time = __TIME__,
```
The previous behavior can be restored using any standard CMake
configuration method, example:
```
./scripts/xtensa-build-all.sh apl
cmake -B build_apl_gcc/ -DBUILD_COUNTERS=1
make -C build_apl_gcc
``` …
=> Disable __TIME__ and the non-reproducible build counter by default

src/audio/copier.c, src/drivers/intel/ssp/ssp.c, src/ipc/ipc4/handler.c
Sof FW doesn't use reset cmd in pipeline_trigger function now,
and resource is also not released by this cmd. Call pipeline_reset to
free resource.
=> ipc4: refine pipeline for I2S

installer/GNUmakefile, installer/tests/staging_sof_ref.txt
In other words:
```
├── intel-signed
│   ├── sof-cfl.ri -> sof-cnl.ri
│   ├── sof-cml.ri -> sof-cnl.ri
│   ├── sof-glk.ri -> sof-apl.ri
```
Doing this manually is time-consuming and error-prone.
Not for ehl because it has a different key.
=> [SKIP CI] installer: automate the creation of symlinks inside intel-signed/

src/drivers/intel/dmic.c
The 'in_active' parameter of dmic_stop() is used to control whether
the fifo should be released or not. In case of COMP_TRIGGER_PAUSE,
this should be false and the 'dmic_active_fifos' count should not
be modified.
Without this fix:
PAUSED -> RELEASE -> dmic_start() -> no change on dmic_active_fifos
ACTIVE -> PAUSE   -> dmic_stop()  -> dmic_active_fifos--
If a test case repeatedly pauses and releases, 'dmic_active_fifos'
will go out-of-sync.
Fix the issue that dmic_stop for PAUSE does not release the fifo
reference.
Fixes: 22731744cb04 ("dmic: don't decrement active FIFO count below 0")
=> dmic: fix pause/release error leading to invalid dmic_active_fifos

src/drivers/intel/dmic.c
When the dmic driver is instantiated multiple times (e.g. for fifo-A and
fifo-B), the interrupt gets registered also twice.
While supported usage of interrupt interface, there is no guarantee that
the interrupt context data is for the expected dai instance. It is thus
not safe to modify the dai state directly or call dai_stop().
Modify the interrupt handler not to make any assumptions on which dai
instance is passed as 'data' matches a specific fifo instance.
=> drivers: dmic: fix multi-fifo logic in interrupt handler

src/drivers/intel/dmic.c
The counter dmic_active_fifos has been a source of many issues. The
use of bits to track active FIFOs is simpler and avoids the risk
of counting to negative or over the actual FIFOs count in various
control scenarios. The incorrect counter value has caused resources
allocate and free and start/stop sequences fails.
=> Drivers: Intel: DMIC: Track fifos activity with mask bits

tools/topology/sof-glk-da7219.m4
By changing bclk to 2.4MHz, we can use XTAL as clock source and reduce
power consumption.
The codec driver does not support bclk running at 2.4MHz when we implemented the machine driver. Since the setting is ready now, we change the bclk to 2.4MHz for power optimization.
=> topology: sof-glk-cs42l42: using 2.4MHz bclk

src/include/sof/schedule/ll_schedule_domain.h, src/schedule/ll_schedule.c
When the last LL task in a domain completes, the domain should be unregistered. This is currently missing.
=> add a missing domain unregister call

tools/topology/development/sof-tgl-nocodec-ci.m4
created to fix https://github.com/thesofproject/sof/issues/4317
Correct the wrong PCM name and pipeline number.
Fixes: 7c62a65ac6aa ("topology: sof-tgl-nocodec-ci: add dmic16k coverage")
=> topology: sof-tgl-nocodec-ci: fix DMIC16KHz PCM

tools/topology/CMakeLists.txt
Dynamic pipelines will fail with the sof-apl-nocodec topology
due to issues with the memory allocator. Revert back to
use static pipelines until we have a more flexible memory
allocatory available with Zephyr.
Fixes https://github.com/thesofproject/sof/issues/4305
=> topology: sof-apl-nocodec: revert to static pipelines

src/debug/panic.c, src/include/sof/trace/dma-trace.h, src/include/sof/trace/trace.h, src/trace/dma-trace.c, src/trace/trace.c, test/cmocka/src/common_mocks.c, tools/logger/convert.c
Various fixes and some comments. Main changes:
`dma-trace.c: remove misunderstood trace_flush() after FW ABI banner`
`trace: initialize DMA trace _after_ mailbox`
=> Tracing fixes

src/audio/buffer.c
Move to dbg since having zero bytes to produce/consume is not
necessarily a problem.
Fixes: https://github.com/thesofproject/sof/issues/3308
=> buffer: demote info messages to dbg

tools/topology2/include/common/tokens.conf, tools/topology2/include/common/vendor-token.conf, tools/topology2/include/components/buffer.conf, tools/topology2/include/components/dai.conf, tools/topology2/include/components/host.conf, tools/topology2/include/components/volume.conf, tools/topology2/include/components/widget-common.conf
This PR introduces Topology2.0 and adds the preparatory commits for a few widget classes that will form the basis for creating simple topologies with the 2.0 compiler.
There are no machine topologies included yet.
=> Introduction and preparation for Topology2.0 - Part 1

src/ipc/ipc4/handler.c
Ipc_msg_process should be replaced by ipc_prepare_to_send
=> ipc4: fix build error

tools/topology/sof-tgl-max98357a-rt5682.m4, tools/topology/sof-tgl-max98373-rt5682.m4, tools/topology/sof-tgl-sdw-max98373-rt5682.m4
hotword is not public and therefore should not be on by default
Signed-off-by: Curtis Malainey <curtis@malainey.com>
=> topology: remove default google hotword

tools/topology/sof/pipe-eq-iir-volume-capture-16khz.m4, tools/topology/sof/pipe-eq-iir-volume-capture.m4, tools/topology/sof/pipe-highpass-capture.m4, tools/topology/sof/pipe-highpass-switch-capture.m4
Remove the duplicate SectionData when multiple EQ's use the
same filter coefficients. There is no change in the topology
binary generated with just one SectionData instead of multiple
ones.
But this will help clean up the conf file so that converting to
topology2.0 will become easier as the name tells me which
coefficients to include.
=> topology: eq pipelines: remove duplicate SectionData

src/drivers/intel/dmic.c, src/include/sof/drivers/dmic.h
This patch separates the component data to private and global
parts and cleans up the explicit un-cache code from previous
version.
Since the dmic_prm[] struct is fixed length it does not need to
be allocated dynamically. It simplifies a lot the parameters
handling and sharing.
=> Drivers: Intel: DMIC: Re-arrange DMIC DAI component data

src/audio/CMakeLists.txt, src/audio/Kconfig, src/audio/peak_volume.c, src/include/ipc4/peak_vol.h
Now current peak volume only support volume change and does't
support curve type, curve duration.
=> ipc4: add limited support for peak volume module

tools/topology/sof-imx8-wm8960-kwd.m4
Use s32le format instead of s16le.
Signed-off-by: Viorel Suman <viorel.suman@nxp.com>
=> topology: imx8: kwd: use s32le format instead of s16le

tools/topology/CMakeLists.txt, tools/topology/sof-tgl-max98357a-rt5682.m4
For speaker pipeline, we want to deploy DRC/EQ for partial TGL device
like Eldrid. The definition flag DRC_EQ is added to make the choice of
adopting the playback pipeline with DRC/EQ.
=> topology: Add DRC_EQ def for adopting DRC/EQ pipeline

tools/topology/topology2/include/pipelines/eq-iir-volume-capture.conf, tools/topology/topology2/include/pipelines/passthrough-capture.conf, tools/topology/topology2/include/pipelines/pipeline-common.conf, tools/topology/topology2/include/pipelines/volume-capture.conf, tools/topology/topology2/include/pipelines/volume-demux-playback.conf, tools/topology/topology2/include/pipelines/volume-playback.conf
Add some pipeline classes for volume playback/capture, passthrough
capture and eq capture.
Each of these classes include the pipeline widget objects, connections
between pipeline widgets and pipeline attribute definitions
For ex: A volume playback pipeline can be instanted as follows:
Object.Pipeline.pipeline-volume-playback."2" {
channels	2
rate		48000
index		5
format		"s32le"
}
=> topology2: Add pipeline classes

src/ipc/ipc3/handler.c
Check if the enable core mask is valid before trying
to enable it.
=> ipc: ip3: handler: check if enable core mask is valid

tools/topology/topology1/sof-cnl-nocodec.m4
The UpExtreme HAT connector with the SoundWire,
I2S, DMIC mixed mode exposes the following pins
DMIC_DATA0: input: HAT PIN 8
DMIC_CLK: output: HAT PIN 26
IS2_MCLK: output: HAT PIN 16
I2S1_SCLK: output: HAT PIN 32
I2S1_SFRM: output: HAT PIN 10
I2S1_TXD: output: HAT PIN 24
I2S1_RXD: input: HAT PIN 18
Let's use core3 for DMIC, core2 for SSP0, core1 for SSP1 and core0 for
SSP2.
=> topology: sof-cnl-nocodec: use different core for each DAI

src/audio/pipeline/pipeline-schedule.c
The walk context is passed in by the caller and not shared. The pipeline
states are locked by IPC.
=> pipeline: dont disable IRQs around pipeline scheduling.

src/include/sof/lib/notifier.h, src/lib/notifier.c
Use a spinlock for locking the list instead.
=> notifier: no need to disable IRQs during registration

tools/topology/topology1/m4/utils.m4
These are not really required to suppress the machine driver errors.
=> topology: hda: remove virtual DAPM routes

tools/topology/topology1/CMakeLists.txt
There is no rt1308 on the TGL-H-RVP platform, need to add a topology
file with only rt711 to enable soundwire on the TGL-H-RVP platform.
The patch of enable soundwire on the TGL-H-RVP platform has been
merged into the thesofproject/linux.
Signed-off-by: Gongjun Song <gongjun.song@intel.com>
=> Topology: Add sof-tgl-rt711-4ch topology

src/audio/codec_adapter/codec/cadence.c
After first compress play run init_done is initialized with 1 and it
keeps this value as no one resets it.
This causes subsequent compress play to miss codec process init phase
and this causes decoding to fail.
With this change multiple cplay runs work fine!
Notice that cadence_codec_reset calls cadence_codec_init and thus resets
init_done flag.
=> codec_adapter: cadence: Reset init_done at init time

src/audio/copier.c, src/drivers/intel/hda/hda.c
Blob data only includes lp memory support for hda
=> ipc4: hda: enable blob support for hda

src/idc/idc.c
Print out the target_core value when timed out during
idc_wait_in_blocking_mode(), which is useful for debugging.
=> idc: print out the target_core when timed out

scripts/xtensa-build-zephyr.sh
TGL-H should be used the 3k otc private key for build.
Signed-off-by: Zhang Keqiao <keqiao.zhang@intel.com>
=> zephyr: switch to use 3k private key for tgl-h

src/arch/xtensa/include/arch/debug/panic.h, src/debug/panic.c, src/include/ipc/trace.h, src/include/sof/debug/panic.h
Zero functional change.
These comments would have saved me at least a day.
=> panic: add comments, especially link to dump corruption bug #1346

src/trace/trace.c
This memory is already owned and initialized by the OS under Zephyr
(and in many cases already holds live output!), don't touch it.
Signed-off-by: Andy Ross <andrew.j.ross@intel.com>
=> trace: Don't initialize trace buffer under Zephyr

src/arch/xtensa/lib/cpu.c, src/audio/buffer.c, src/audio/pipeline/pipeline-graph.c, src/ipc/ipc3/dai.c, src/ipc/ipc3/handler.c, src/schedule/edf_schedule.c, src/schedule/ll_schedule.c, test/cmocka/src/audio/pipeline/pipeline_free.c
This fixes a few issues with multi-core and dynamic pipelines. Still got a few more to tackle.
=> Miscellaneous fixes for dynamic pipelines and multicore

src/audio/buffer.c
Buffer lists were being deleted twice, at first by the
pipeline_disconnect() (the correct place) and then by buffer_free().
Fix this so buffer_free() only frees the buffer.
==426365== Invalid write of size 8
==426365==    at 0x49CB47B: list_item_del (list.h:57)
==426365==    by 0x49CB47B: buffer_free (buffer.c:179)
==426365==    by 0x49C8C7B: ipc_buffer_free (helper.c:697)
==426365==    by 0x10C1E6: free_comps (testbench.c:165)
==426365==    by 0x10C1E6: main (testbench.c:415)
==426365==  Address 0x4bdce48 is 152 bytes inside a block of size 168 free'd
==426365==    at 0x484521F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==426365==    by 0x49C9163: comp_free (component_ext.h:55)
==426365==    by 0x49C9163: ipc_comp_free (helper.c:866)
==426365==    by 0x10C200: …
=> buffer: fix double list deletion detected by valgrind.

src/drivers/intel/dmic.c
free the dai drvdata (same as the variable struct dmic_pdata *dmic)
after using it to disable and unregistering interrupts.
=> drivers: intel: dmic: fix dmic_remove()

src/ipc/ipc3/dai.c
If the core is not up, the comp exist in the comp_list.
So no need to check if the core is up.
This reverts commit bccecb1a8eed84a0737fdf2878204adfb6cf845d.
=> Revert "dai: only process DAI config for comps on cores that enabled"

src/platform/apollolake/include/platform/lib/memory.h, src/platform/intel/cavs/include/cavs/lib/mailbox.h
This makes it possible to match the table with the definitions.
Pure comment change, no code change.
=> [SKIP CI] apollolake/memory.h: sort regions table comment by address

scripts/run-mocks.sh, src/audio/pipeline/pipeline-graph.c, src/include/sof/lib/mm_heap.h, src/lib/alloc.c, src/platform/library/include/platform/lib/memory.h, src/platform/library/lib/CMakeLists.txt, src/platform/library/lib/memory.c, test/cmocka/src/lib/CMakeLists.txt, test/cmocka/src/lib/alloc/CMakeLists.txt, test/cmocka/src/lib/alloc/alloc.c
Add support for valgrind to run on the mocks to detect memory errors.
Reported memory errors still have to be fixed, most are leaks in the mock code.
=> debug: add support for valgrind in the mocks

tools/testbench/common_test.c, tools/testbench/file.c, tools/testbench/include/testbench/common_test.h, tools/testbench/testbench.c, tools/testbench/topology.c
Add some improvements to support valgrind and eliminate all valgrind errors. Also allow users to specify number of copies.
=> testbench: improvements for valgrind and debug

tools/topology/sof-tgl-max98373-rt5682.m4
Optimal load-balancing depends on multiple factors, so let's condition
it for igo_nr only based on its high MCPS needs and benchmark score.
=> topology: sof-tgl-max98373-rt5682: move DMIC to core 1 for IGO only

tools/topology/topology1/sof-glk-da7219.m4
Changing SSP2 configuration to use 24-bit sample bitwidth.
=> topology: sof-glk-cs42l42: using 24-bit sample on SSP2

src/include/sof/lib/pm_runtime.h, src/platform/intel/cavs/lib/pm_runtime.c
Reword doxygen comments and change the private helper function
names to better reflect the actual implementation. No functional
change.
The PM_RUNTIME_HOST_DMA_L1 resource is used to coordinate host DMA
users, so that DMI link is kept in L1 until all users are ready to
activate the link. This is a bit unusual usage of runtime-pm interface
in that a 'put on a resource' triggers transition to higher power state,
so this deserves some more documentation.
=> cavs: pm: improve PM_RUNTIME_HOST_DMA_L1 documentation

tools/topology/topology1/CMakeLists.txt
add the TGL-H nocodec topology for zephyr test.
Signed-off-by: Zhang Keqiao <keqiao.zhang@intel.com>
=> topology: add tgl-h nocodec topology build

src/include/sof/lib/notifier.h, zephyr/wrapper.c
Fixes the zephyr part of #4356
In XTOS SOF, ipc_send_queued_msg() is run by task_main_primary_core(),
the initialization of which has a hard and circular dependency with the
initialization of the EDF scheduler. This EDF scheduler is not part of
Zephyr. Because of the circular dependency it does not seem
possible (nor desirable?) to refactor this code and make it compatible
with Zephyr. So schedule ipc_send_queued_msg() differently in Zephyr:
using a notifier triggered by the periodic Low Latency scheduler.
Not related to this PR but if you're curious about `NOTIFIER_ID_LL_POST_RUN` find information in #4430
=> zephyr: add notifier_register(ipc_send_queued_msg) in task_main_start()

scripts/checkpatch.pl, src/include/sof/drivers/timer.h, src/include/sof/trace/trace.h, src/ipc/ipc3/handler.c, src/trace/dma-trace.c, src/trace/trace.c, zephyr/include/sof/trace/trace.h
5 commits, per-commit review is recommended.
This is a re-submission/recycling of 85% of the earlier "restore early tracing" PR previously reviewed in #4334: everything except the actual and final restoration of early tracing which is currently failing on BDW and BYT which I have no time to debug right now. Maybe later.
=> Add new mtrace_printf() and use it for DMA init error handling and demoting banner to INFO level

src/platform/intel/cavs/include/cavs/lib/memory.h
Once following Zephyr PRs are merged, this can proceed:
- https://github.com/zephyrproject-rtos/zephyr/pull/36055
- https://github.com/zephyrproject-rtos/zephyr/pull/35490
Marking as draft until dependencies met.
With Zephyr linker scripts updated on all cAVS platforms, we can now
unify uncache_to_cache() and cached_to_uncache() implementation in
Zephyr builds.
=> cavs: memory: unify access macros on Zephyr

src/audio/buffer.c, src/audio/pipeline/pipeline-graph.c
Revert these for now. Will be fixed with other multi-core fixes.
This reverts commit 928dba0853efa4cd0d79aa66b1e9c221b8813a8f.
=> Revert "pipeline/buffer: alloc them in the runtime shared zone"

tools/topology/topology1/sof-cavs-nocodec.m4
For some reason s32le does not work on JSL-NOCODEC platforms. alsa-bat
tests fail, but they work fine on APL, CNL, TGL. This is likely to be
an ICL platform issue. The root cause is still TBD
Use s24le for now to unlock Intel daily tests.
BugLink: https://github.com/thesofproject/sof/issues/4427
=> topology: cavs-nocodec: temporarily fix jsl-nocodec issues with s24le

src/audio/codec_adapter/codec/cadence.c, src/audio/codec_adapter/codec/generic.c
This patch set:
- improves prepare procedure by adding INIT_PROCESS and INIT_DONE API calls
- fixes the reset procedure to address https://github.com/thesofproject/sof/issues/4104
Cadence documentation doesn't document reset procedure at all so for a long time we were just freeing all the memory codec allocated and start over. However this is very inefficient way of performing simple reset of parameters. Hence this patch  https://github.com/thesofproject/sof/pull/4162/files tried to simplify it and while it does reset parameters it also breaks the flow since XA_CMD_TYPE_INIT_API_PRE_CONFIG_PARAMS is only allowed during INIT phase. After code inspection of the codec library XA_CMD_TYPE_INIT_PROCESS seems to do what we need to perform the reset and hence this patch relies on that API call. …
=> codec_adapter: cadence: fix reset procedure + improve prepare

src/platform/imx8/lib/clk.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, zephyr/CMakeLists.txt, zephyr/wrapper.c
Add support for i.MX to build Sound Open Firmware with Zephyr OS.
Please check each commit message.
With these commits I have a successful build. 
I obtain the zephyr.ri image which boots the DSP and loads the topology.
```
root@imx8qmmek:~# ./loadSof.sh 
[  166.405965] sof-audio-of 556e8000.dsp: DT DSP detected
[  166.416971] imx-dsp imx-dsp: NXP i.MX DSP IPC initialized
[  166.430784] sof-audio-of 556e8000.dsp: warning: unknown sof_ext_man header type 5 size 0x20
[  166.439213] sof-audio-of 556e8000.dsp: warning: unknown sof_ext_man header type 3 size 0x30
[  166.447885] sof-audio-of 556e8000.dsp: Firmware info: version 1:8:0-cf919
[  166.454703] sof-audio-of 556e8000.dsp: Firmware: ABI 3:19:0 Kernel ABI 3:17:0
[  166.461862] sof-audio-of 556e8000.dsp: warn: FW ABI is more recent than …
```
=> Build SOF with Zephyr on i.MX

smex/CMakeLists.txt, smex/elf.c
3 commits, main one:
smex: fix crash in elf_free_module() when input file not found
fclose() seems to require a valid argument.
=> smex: fix crash in elf_free_module() when input file not found

src/include/sof/trace/trace.h
Fixes commit 50eb5c9ca22b ("trace.c: add mtrace_printf() low-level
shortcut")
=> Fix !CONFIG_TRACE again, broken when adding mtrace_printf()

src/audio/pipeline/pipeline-schedule.c, src/schedule/ll_schedule.c, src/schedule/zephyr_domain.c, src/schedule/zephyr_ll.c
The series fixes a recent regression by reverting commit af6655e7fac3c56847251553699f354df74bf6a9 and then switches the SOF Zephyr-based LL scheduler implementation to using the native Zephyr time-keeping API.
=> zephyr: ll-scheduler: switch to the native time-keeping API

src/drivers/intel/ssp/ssp.c, src/include/ipc/dai-intel.h, src/include/ipc/dai.h, src/include/sof/drivers/ssp.h, tools/topology/topology1/platform/common/ssp.m4, tools/topology/topology1/sof-cavs-nocodec.m4, tools/topology/topology1/sof-glk-da7219.m4
The PR is an update of https://github.com/thesofproject/sof/pull/4288.  I didn't change anything except removing [ABI: bump level to 3.19](https://github.com/thesofproject/sof/pull/4288/commits/2c061639a1cefc77bd8a4fc809bf15f640c2e47c).
=> SSP BLCK and MCLK early start - take 4

tools/topology/topology1/sof-cavs-nocodec.m4
The use of s32le did not expose any problems on APL, but alsa-bat was
previously reported as failing on JSL. Now that this test was extended
to CML_NOCODEC, we see the same issue. Manual tests with s24le show no
issues.
Let's just use s24le across the board and move on.
=> topology: cavs-nocodec: use s24le for DAIs for all platforms

src/drivers/imx/sdma.c
gcc10.2 does not see that config->elem_array.count is greater than zero
and complains. This happens only at the -O1 optimization level that is
rarely tested.
```
error: 'bd' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
758 |  bd->config &= ~SDMA_BD_CONT;
error: 'width' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
786 |  watermark = (config->burst_elems * width) / 8;
|              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
```
This is preferred over initialization at the top of the function
that hides _all_ warnings including valid ones.
Of course the even better fix would to BOTH declare and initialization
just before the loop, as late as possible just like in any other modern
and safer programming language. However C99 declarations are not …
=> imx/sdma.c: silence "may be uninitialized" warnings with gcc10.2 -O1

src/include/sof/audio/buffer.h, src/include/sof/common.h, src/include/sof/ipc/topology.h, src/ipc/ipc3/helper.c, src/lib/pm_runtime.c, zephyr/wrapper.c
=> Power management and other comments + constify ipc_buffer_new

src/schedule/ll_schedule.c
ll_schedule: refine to remove the dependency among DSP COREs
We don't need to wait until tasks on all DSP COREs finished, before we
can configure the next interrupt to trigger the next scheduling. Imagine
scenarios that one of the CORE is taking long time to finish a high MCPS
task, we should keep tasks on other COREs freed to be scheduled during
that period.
Calculate and re-configure the interrupt at finish of each CORE, and
re-enable domain on each CORE separately.
=> LL refinement to remove dependency among COREs

src/drivers/intel/ssp/ssp.c
When two streams are started one after the other, 2 DAI_CONFIG
IPC's will be sent before the START trigger. This ends up
configuring the SSP when the first one has already just
configured it and ends up with xruns. Avoid this by checking
if the current state is > COMP_STATE_READY before configuring the
SSP.
Fixes https://github.com/thesofproject/sof/issues/4457
=> drivers: Intel: SSP: ignore config when SSP is already configured

src/audio/copier.c, src/include/ipc4/copier.h, src/include/ipc4/module.h, src/include/sof/audio/component.h, src/include/sof/audio/component_ext.h, src/include/sof/ipc/topology.h, src/ipc/ipc4/handler.c, src/ipc/ipc4/helper.c
Each module may connect to different queue of another module. This patch add first version of queue support
=> Ipc4:  add queue support 

src/include/sof/lib/dma.h, src/trace/dma-trace.c
These proved useful when debugging Zephyr but they're not Zephyr specific.
Use mtrace_printf() because if we're having DMA issues we probably want
to avoid the DMA trace
=> dma: add some NULL pointer checks

tools/topology/topology1/development/sof-tgl-nocodec-ci.m4
Fixes #4461
S32_LE without PGA is not supported in alsabat, switch to use
pipe-volume-capture and unblock the CI alsabat test case.
Signed-off-by: Iris Wu <xiaoyun.wu@intel.com>
=> topology1: sof-tgl-nocodec-ci: use volume capture for PCM0

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/include/common/fe_dai.conf, tools/topology/topology2/include/common/manifest.conf, tools/topology/topology2/include/common/pcm.conf, tools/topology/topology2/include/common/pcm_caps.conf, tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/components/copier.conf, tools/topology/topology2/include/dais/hw_config.conf, tools/topology/topology2/include/dais/ssp.conf, tools/topology/topology2/include/pipelines/cavs/passthrough-capture.conf, tools/topology/topology2/include/pipelines/cavs/passthrough-playback.conf
This patch adds cavs-nocodec topology, and classes used by this topology.
Note that, only a playback and a capture pipelines on SSP0 are added.
This topology is verified with CAVS firmware on a TGLU nocodec device. 
special thanks to @RanderWang for topology verification and integration debug.
To compile this topology, take the upstream alsa-utils and Ranjani's PR https://github.com/alsa-project/alsa-utils/pull/97. run command 
```
export ALSA_CONFIG_DIR=path-to-topology2 # E.g. export ALSA_CONFIG_DIR=~/sof/tools/topology/topology2
alsatplg -p -c tools/topology/topology2/cavs-nocodec.conf -o cavs-nocodec.tplg
```
=> topology2: Add cavs-nocodec topology

zephyr/wrapper.c
Commit 34bb9b728268 ("zephyr: wrapper: build SOF with Zephyr for imx") broke coherent memory allocations on Intel DSP platforms. Restore the original code.
=> zephyr: fix memory allocation coherency

.github/workflows/installer.yml
The docker image has it now thanks to Fred.
=> [SKIP CI] .github/installer.yml: remove cp -a /usr/bin/tree hack

scripts/xtensa-build-zephyr.sh, smex/smex.c, zephyr/CMakeLists.txt, zephyr/docker-build.sh, zephyr/module.yml, zephyr/wrapper.c
See commit messages.  This is temporary until the switch to Zephyr logging.
Sample output from https://github.com/thesofproject/sof/pull/4474/checks?check_run_id=3043998310
```
zephyr-project/build-sof-staging
├── sof
│   ├── community
│   │   ├── sof-apl.ri
│   │   ├── sof-cnl.ri
│   │   ├── sof-icl.ri
│   │   └── sof-tgl-h.ri
│   ├── sof-apl.ldc
│   ├── sof-cnl.ldc
│   ├── sof-icl.ldc
│   └── sof-tgl-h.ldc
└── tools
└── sof-logger
```
=> zephyr: build and run smex. New staging area for easy deployment

tools/topology/topology1/sof-cavs-nocodec.m4
Add a deepbuffer pipeline connected to the the mixer-dai
pipeline. The pipeline deadline is left at 1ms for now
and will be changed later after the mixer pipeline
is validated.
=> topology: cavs-nocodec: Add deepbuffer pipeline to SSP0

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/include/components/copier.conf
Copier widget may be used as a dai component in ipc4 path,
so we need to add dai token in copier, including dai_index,
dai_type and direction. They are optional attributes and can
be set only for dai type.
=> topology2: add dai token support in copier

test/cmocka/src/common_mocks.c
This change avoids build error:
```
cc1: warnings being treated as errors
sof/test/cmocka/src/common_mocks.c: In function ‘__panic’:
sof/test/cmocka/src/common_mocks.c:100: warning: ‘noreturn’ function does return
```
=> test: cmocka: Add exit to function __panic()

tools/topology/topology1/development/CMakeLists.txt, tools/topology/topology1/sof-tgl-rt711-rt1308.m4
The Volteer topology is complicated with SmartAmp and Hotwording.
The topology used on TGL_RVP_SDW can be re-used almost as-is, just with a minor reshuffling of dailink indices.
Tested on Volteer successfully, this also shows the same problems suspend/resume reported on TGL_RVP_SDW with https://github.com/thesofproject/linux/pull/3006
The topology needs to be copied as from 
development/sof-tgl-sdw-max98373-rt5682-dmic4ch-ampref.tplg
to sof-tgl-sdw-max98373-rt5682.tplg on the target device
@ranj063 @RanderWang @bardliao if you can help test that would be good!
NO MERGE until we've root-caused the suspend-resume issues.
=> topology: reuse sof-tplg-rt711-rt1308 on Google Volteer

src/audio/codec_adapter/codec/passthrough.c, src/audio/host.c
logging as process in prepare step
=> codec_adapter: passthrough: fix typo

src/include/sof/audio/component.h, src/include/sof/audio/component_ext.h
In ipc4 each module will be bound to its sink module by pipeline.
This patch add new ops bind & unbind to dispatch these events to
related modules.
=> ipc4: add bind & unbind ops for ipc4 module

src/drivers/intel/alh.c, src/drivers/intel/ssp/mn.c, src/drivers/intel/ssp/ssp.c, src/include/ipc4/alh.h, src/include/ipc4/ssp.h, src/include/sof/drivers/mn.h, src/include/sof/drivers/ssp.h, src/ipc/CMakeLists.txt, src/ipc/ipc4/CMakeLists.txt, src/ipc/ipc4/dai.c
This PR adds support of alh & i2s blob support for IPC4.  IPC4 is a next ipc version of intel platforms.
=> Ipc4 : add alh & i2s blob support

tools/test/audio/process_test.m, tools/tune/crossover/example_crossover.m, tools/tune/dcblock/example_dcblock.m, tools/tune/drc/example_drc.m, tools/tune/eq/example_fir_eq.m, tools/tune/eq/example_iir_eq.m, tools/tune/eq/example_spk_eq.m, tools/tune/multiband_drc/example_multiband_drc.m
The change for topology1 was missing from various tuning
and testing scripts those access binary blob data from
topology m4 directories.
=> Tools: Fix topology1 path in Matlab language scripts

src/include/ipc4/base-config.h, src/include/ipc4/error_status.h, src/include/ipc4/fw_reg.h, src/include/ipc4/module.h, src/include/ipc4/notification.h, src/include/ipc4/pipeline.h
IPC4 is another ipc version for intel next platforms. Compared to current ipc3,  the key difference are:
(1) pipeline is composed of module, not component. And also pipeline will manage memory allocation including buffer
(2) there is no buffer defined in topology and FW will create buffer on demand
The pipeline in ipc4 has different operations and states but it can be converted to current ipc3 straight forward. Module interface can also be supported by current component interface.
This patch adds support of ipc4 message and basic pass-though pipeline support on HDA, I2S and ALH.
=> Add basic ipc4 headers

src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/src/src.c, src/audio/tdfb/tdfb.c
The components FIR, IIR, SRC, TDFB, and volume have some state variables those were not treated as required in reset operation description in component.h. This pull request removes some unnecessary state variables from component by converting them to local or adds reset code.
This contributes to issue #4488 .
Edit: I've removed volume component from this PR. The volume state can't be reset in reset() comp op without causing volume levels test to fail.
=> Reset handler cleanup fixes for audio processing components

tools/topology/topology2/include/components/copier.conf
ALH is a valid type of copier.
=> topology2: copier: add ALH type

tools/ctl/ctl.c
getopt() returns an int, which in our implementation is assigned to a
char type var.
On some platforms char is unsigned thus making getopt() return value
always > 0.
Use int instead of char here to fix the stop condition for parameter
parsing.
This makes sof-ctl work on ARM platforms.
=> tools: ctl: Fix getopt() stop condition

src/audio/Kconfig, src/audio/pcm_converter/pcm_converter_generic.c, src/include/sof/audio/pcm_converter.h
Ipc4 pcm converter will check container size and valid sample
size to do format conversion. This patch add general support for
valid sample / container size s16c16 <-> s16c32, s32c32 <-> s16c32
s16c32 <-> s24c32 s24c32 <->s16c32, which are not supported
by sof now.
=> pcm_converter: add ipc4 converter support

src/include/sof/schedule/task.h, src/schedule/zephyr_ll.c
Add a lightweight layer to track execution time of ll tasks to the
zephyr-ll scheduler. Use k_cycle_get_32() timestamps for minimal
overhead. A trace is printed with a period size of 2^10 task executions
(roughly once per second in typical configuration with 1ms timer tick).
Average and maximum observed execution time is printed out for each
task.
=> zephyr: add per-ll-task tracking of execution time

src/audio/drc/drc.c, src/audio/multiband_drc/multiband_drc.c
To make sure we have cleaned up all contents in component data on reset().
This PR contributes to issue #4488 fixes.
=> Audio: clean up source_format in component data of drc and multiband_drc

src/drivers/intel/cavs/ipc.c, src/idc/idc.c, src/include/sof/ipc/common.h, src/ipc/ipc-common.c, src/ipc/ipc3/dai.c, src/ipc/ipc3/handler.c, src/ipc/ipc3/helper.c
Currently when an IPC message arrives, the primary core receives the interrupt, schedules a task and begins processing the message. If it identifies, that the message is for another core, it sends an IDC message to it and waits in a busy loop until the other core completes processing the message and writes a response into the mailbox. After that the primary core notifies the host about completing the processing. This patch lets the processing secondary core notify the host directly, which also frees the primary core to handle other tasks instead of waiting in a busy loop.
@lgirdwood This is a prerequisite for the "trigger from thread" #4471
=> ipc: let secondary cores acknowledge IPC messages

src/include/sof/trace/trace.h, src/ipc/ipc3/handler.c, src/platform/intel/cavs/platform.c, src/schedule/zephyr_ll.c, src/trace/trace.c, test/cmocka/src/common_mocks.c, zephyr/include/sof/trace/trace.h
Reviewing commits one by one is highly recommended.
This is a superset of #4452
=> zephyr: sof-logger

scripts/xtensa-build-zephyr.sh, src/drivers/imx/interrupt-irqsteer.c, src/drivers/interrupt.c, src/include/sof/drivers/interrupt.h, src/include/sof/schedule/ll_schedule.h, src/platform/imx8/platform.c, src/schedule/dma_multi_chan_domain.c, zephyr/CMakeLists.txt, zephyr/wrapper.c
This pull request fixes some issues we have on i.MX.
Please check each commit, but here's a summary of these fixes:
- i.MX uses dma_domain, so keep the ll_schedule from SOF, until we extend the zephyr_ll for DMA_IRQ
- on i.MX the DMA interrupts are routed via IRQ_STEER.  In order for this to work we need to make any second level interrupts handling go through interrupt-irqsteer.c
- for i.MX we need to use [this ](https://github.com/iuliana-prodan/sof/commit/c194125b83c21d82243bc9eaa18701d87deba468) temporary fix for SOF_SCHEDULE_LL_DMA
With this pull request we can now run successfully, on i.MX, playback and record scenarios with Zephyr.
=> Fixes for SOF with Zephyr on i.MX

src/audio/pipeline/pipeline-graph.c, src/audio/pipeline/pipeline-schedule.c, src/audio/pipeline/pipeline-stream.c, src/audio/pipeline/pipeline-xrun.c, src/drivers/intel/cavs/ipc.c, src/include/sof/audio/pipeline.h, src/include/sof/ipc/common.h, src/ipc/ipc-common.c, src/ipc/ipc3/handler.c
Run trigger START and RELEASE in the pipeline task context
=> Pipeline scheduling

src/schedule/zephyr_domain.c
.next_tick is updated on each timer run to the time of the next run. Instead the current version sometimes only updates it to the current time. Fix the update condition.
=> zephyr: ll-domain: set .next_tick into the future

tools/topology/topology1/development/CMakeLists.txt, tools/topology/topology1/development/sof-imx8-compr-aac-wm8960.m4, tools/topology/topology1/development/sof-imx8-compr-mp3-wm8960.m4, tools/topology/topology1/development/sof-imx8mp-compr-aac-wm8960.m4, tools/topology/topology1/development/sof-imx8mp-compr-mp3-wm8960.m4
I was keeping this in our imx stable branch for too long. I think they are upstream quality although we need to rework compress parameters passing. We now use compress like parameters piggybacked on PCM params.
=> Add compress topologies

src/audio/pipeline/pipeline-graph.c, src/audio/pipeline/pipeline-schedule.c, src/audio/pipeline/pipeline-stream.c, src/audio/pipeline/pipeline-xrun.c, src/drivers/intel/cavs/ipc.c, src/include/sof/audio/pipeline.h, src/include/sof/ipc/common.h, src/include/sof/trace/trace.h, src/ipc/ipc-common.c, src/ipc/ipc3/handler.c, src/trace/trace.c, test/cmocka/src/common_mocks.c, zephyr/include/sof/trace/trace.h
It makes no sense to continue if we have two problems impacting the same platform.
=> Revert all patches affecting CML

src/platform/apollolake/lib/clk.c, src/platform/baytrail/lib/clk.c, src/platform/cannonlake/lib/clk.c, src/platform/haswell/lib/clk.c, src/platform/icelake/lib/clk.c, src/platform/suecreek/lib/clk.c, src/platform/tigerlake/lib/clk.c
Make platform_cpu_freq[], platform_ssp_freq[] and platform_ssp_freq_sources[] arrays constant on multiple platforms.
=> clock: (cosmetic) make frequency tables and sources const

tools/topology/topology1/sof-imx8ulp-btsco.m4
On i.MX8ULP SAI5 is connected to BT interface that only supports 1
channel.
=> topology1: imx8ulp: Set min_channels to 1

src/drivers/imx/edma.c
No need to write to register MUX when it already has value. Second
write option can't set value and clear register to zero.
Signed-off-by: Zhang Peng <peng.zhang_8@nxp.com>
=> drivers: imx: edma: Fix play error in second time

src/include/sof/compiler_attributes.h
2 my PRs need this: #4559 and #4562 - would be good to merge this ASAP...
Fix compiler warning by using the "fallthrough" attribute with GCC as well.
=> compile: use __attribute__((fallthrough)) with GCC

src/platform/imx8ulp/lib/dai.c
Change capture offset to "SAI_5_BASE + REG_SAI_RDR3" to match rx3
used in sai module.
Signed-off-by: Zhang Peng <peng.zhang_8@nxp.com>
=> platform: imx8ulp: dai: Change capture offset

src/platform/intel/cavs/include/cavs/lib/memory.h
Aligns all SHARED data on cache line size to ensure we dont clobber
data.
=> cache: make sure all shared data is cache line size aligned.

src/drivers/intel/cavs/idc.c, src/drivers/intel/ssp/ssp.c
Tell users which IDC is failing and only delay in SSP clock consumer modes.
=> ssp and idc minor updates.

tools/topology/topology1/sof/pipe-passthrough-capture.m4
The patch to fix CHANNELS_MIN side effects had a bug in which caused
LOCAL_CHANNELS_MIN to slip into conf output. Example from
sof-adl-sdw-max98373-rt5682:
---cut--
SectionPCMCapabilities."Passthrough Capture 14" {
»       formats "S16_LE"
»       rate_min "8000"
»       rate_max "16000"
»       channels_min "LOCAL_CHANNELS_MIN"
--cut--
Fixes: 659266685b43 ("topology: remove side effects from macro definitions")
BugLink: https://github.com/thesofproject/sof/issues/4621
=> topology1: fix error in LOCAL_CHANNELS_MIN definition

.github/workflows/zephyr.yml
The recent zephyr code add restriction to the SDK,
and requires the SDK version >= 0.13, we have to
update the docker image for zephyr SOF building.
As the default SDK version in docker image 0.18.1
is still 0.12.4, and the alternative SDK is 0.13.0,
we need to specify the SDK location with env.
=> [SKIP CI] github actions: update zephyr docker image to 0.18.1

src/arch/xtensa/lib/cpu.c, src/drivers/intel/cavs/idc.c, src/include/sof/drivers/idc.h
Make sure to clock the power down IDC block until the core is idled
Fixes https://github.com/thesofproject/sof/issues/4602
=> Make cpu power down IDC blocking

src/ipc/ipc3/handler.c, zephyr/wrapper.c
Clean up the ifdefs for ipc_pm_context_save(). By implementing
platform_timer_stop() in the Zephyr wrapper, the original context
save sequence can be used also for Zephyr builds.
By doing this, we can fix issues with IPC timeout on CTX_SAVE.
Disabling all interrupts before the IPC reply is needed also on
Zephyr.
BugLink: https://github.com/thesofproject/sof/issues/4507
=> zephyr: unify CTX_SAVE handling for Zephyr

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
Enclose ENDPOINT_NAME with `' to avoid side effects.
=> topology1: tgl-max98357a-rt5682 fix ENDPOINT_NAME macro

scripts/xtensa-build-zephyr.sh
Remove the unnecessary assumption that Xtensa tools are installed under
'XtDevTools'.
Align indentation to use tabs as is used elsewhere in this file.
=> xtensa-build-zephyr: clean up XTENSA_TOOLS_ROOT parsing

src/include/sof/drivers/dw-dma.h, src/platform/tigerlake/include/platform/drivers/dw-dma.h
It is observed that on different platforms, the LLI need to be aligned
different, e.g. it is 128 Bytes on TGL, otherwise, the LLI struct might
be clobbered and the DMA channel might get unexpected stopped, which
will eventually lead to Xrun.
Here make the LLI alignment to platform specific and use 128 Bytes for
TGL.
=> dw-dma: set LLI alignment to platform specific

tools/topology/topology1/sof-tgl-max98373-rt5682.m4
1st commit to use a mockup of the smart amp
for 2nd commit, BT offload is not working on TGL Voxel I2S. I don't think BT offload is ready for TGL.
sof-tgl-sdw-max98373-rt5682.m4 uses BT offload when platform is ADL.
https://github.com/thesofproject/sof/blob/6713cace3586115c82dd18a111b63d6f4cd4b435/tools/topology/topology1/sof-tgl-sdw-max98373-rt5682.m4#L57
This is error message when I tested on TGL Voxel.
```
2021-08-13 20:08:39 UTC [COMMAND] aplay   -Dhw:0,6 -r 8000 -c 1 -f S16_LE -d 5 /dev/zero -v -q
aplay: set_params:1432: Unable to install hw params:
[  116.834656] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  116.835013] sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60010000 size 20
[  116.835115] sof-audio-pci-intel-tgl …
```
=> sof-tgl-sdw-max98373-rt5682: remove 3rd party smart amp dependency

scripts/xtensa-build-zephyr.sh
The BSS usage exceeds available memory when building for
APL/cavs15 hardware with XCC, so disable it for now. Issue
tracked as https://github.com/thesofproject/sof/issues/4645
=> xtensa-build-zephyr: disable XCC build for Intel APL

tools/topology/CMakeLists.txt, tools/topology/sof-jsl-rt5682.m4
Backport 3 patches from stable-v1.8 to jsl-004-drop-stable for IIR support.
=> topology: Add IIR support for jsl topology

.github/workflows/zephyr.yml
The latest zephyr requires CMake version >= 3.20,
we have to update the docker image to meet the
requirement.
=> .github/zephyr.yml: update docker for cmake requirement

src/ipc/ipc3/handler.c
Fuzzer found a way to try and access a buffer as a component which
results in a UAF crash.
=> ipcv3: fix memory access bug

src/audio/crossover/crossover.c, src/audio/dcblock/dcblock.c, src/audio/drc/drc.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/mixer.c, src/audio/multiband_drc/multiband_drc.c, src/audio/selector/selector.c, src/audio/volume/volume.c
This patch fixes the check in crossover, dcblock, drc, eq, mixer,
multiband drc, selector, and volume components. The check should
be for 1 period of data.
=> Audio: Fix sink buffer size check in several processing components

tools/topology/topology1/CMakeLists.txt, tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
This Pull Request integrates RTNR component into sof-tgl-max98357a-rt5682.m4. DMIC16KPROC will be defined as rtnr if RTNR is defined. Both sink and source need to be 2 channels for RTNR.
=> Integrate RTNR into sof-tgl-max98357a-rt5682.m4

src/audio/drc/drc_math_generic.c, src/audio/drc/drc_math_hifi3.c, src/include/sof/audio/drc/drc_math.h
This patch optimizes for speed of DRC with cordic sine function usage in both HiFi3 and generic manners.
=> drc: Optimize with cordic sine function

src/init/init.c, src/trace/dma-trace.c, src/trace/trace.c
If the log tracing (e.g. tr_err()) is called before the trace itself is
available, the FW will crash and FW boot fail happen.
Enable the trace after it is ready, and don't try to perform tracing
when it is unavailable.
=> trace: enable trace after it is ready

src/ipc/dma-copy.c, src/platform/intel/cavs/platform.c, src/trace/dma-trace.c, src/trace/trace.c
The DMA trace is not necessary enabled so the trace_data could be NULL,
add check to avoid dereference from NULL pointer and panics.
=> dma-trace: add check to avoid dereference from NULL

src/drivers/intel/ssp/mn.c
The mdivctrl register is corrupted when disabling MCLK divider in
mn_release_mclk() function. It could overwrite bclk's source clock and
stop the clock running.
=> ssp: mn: mdivctrl corruption in mn_release_mclk()

src/audio/google_hotword_detect.c
Unused values, save a bit of text and data space by cleaning this up.
Suggested-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
=> audio: ghd: remove superfluous initializations

scripts/xtensa-build-zephyr.sh
Add imx8 platform to be tested with Zephyr.
=> xtensa-build-zephyr: add imx8 as supported platform

src/audio/dai.c, src/drivers/intel/baytrail/ssp.c, src/drivers/intel/haswell/ssp.c, src/drivers/intel/ssp/ssp.c, src/include/ipc/dai-intel.h, src/include/ipc/dai.h, src/include/kernel/abi.h, src/include/sof/drivers/ssp.h, tools/topology/CMakeLists.txt, tools/topology/platform/common/ssp.m4, tools/topology/sof-jsl-rt5682.m4
Backport the PR to JSL branch to support cs42l42 headphone codec on JSL Chromebooks.
https://github.com/thesofproject/sof/pull/4391
=> Backport bclk clock control to JSL branch

src/drivers/dw/dma.c, src/include/sof/drivers/dw-dma.h, src/platform/intel/cavs/include/cavs/drivers/dw-dma.h, src/platform/intel/cavs/lib/memory.c, src/platform/tigerlake/include/platform/drivers/dw-dma.h
dw-dma: change to use runtime_shared heap for lli buffer
The lli structs are used by both DSP and DMAC, allocate them from the
runtime_shared heap to avoid being corrupted by cache writing back.
This helps to fix a lot of DMA xrun issue according to the validation.
=> dw-dma: fix the lli corruption issue

src/audio/buffer.c
Buffers can be shared between cores and it is crucial to have access
to not only proper buffer data but also description data of this buffer
Fixes #4648 
Signed-off-by: Adrian Bonislawski <adrian.bonislawski@intel.com>
=> buffer: alloc main buffer struct in the runtime shared zone

src/arch/xtensa/include/xtensa/coreasm.h, src/arch/xtensa/include/xtensa/tie/xt_virtualops.h
This patch updates XTENSA toolschain from version RG-2017.7 to RI-2020.5.
=> toolschain: update header files to support newer toolschain

src/drivers/intel/ssp/ssp.c
Two issues ware identified when we test early bclk feature on JSL Chromebooks.
1. bclk/mclk control is ignored
2. mdivctrl corruption
=> ssp: bclk/mclk control is ignored

scripts/xtensa-build-zephyr.sh
Recently merged rework of multicore support in Zephyr has
broken builds with XCC. Disable XCC based builds in CI until
issue is resolved in Zephyr mainline. Issue tracked as:
https://github.com/zephyrproject-rtos/zephyr/issues/38349
=> xtensa-build-zephyr: disable XCC build for Intel cAVS hw

src/drivers/imx/ipc.c, src/drivers/intel/cavs/ipc.c, src/drivers/intel/haswell/ipc.c, src/idc/idc.c, src/include/sof/ipc/common.h, src/ipc/ipc-common.c, src/ipc/ipc3/handler.c
A race currently exists in IPC completion code. When processing the
pipeline TRIG_START command on timer-domain pipelines, processing is
postponed to the pipeline task. Usually the IPC task continues and
completes before the pipeline task. The IPC task notes, that the
command is processed in the pipeline context and doesn't send a
reply to the host. Then the pipeline task executes the command and
notifies the host.
However, occasionally the timer interrupt occurs while the IPC task
is still active. It will start processing the IPC command in the
pipeline context and reply to the host. The host then can send the
next IPC command before the IPC task in the firmware has completed.
This then produces an error trace:
ERROR schedule_edf_task(), task already queued or running 3
and the IPC is …
=> ipc: fix an IPC completion race

src/audio/host.c, src/audio/pipeline/pipeline-schedule.c, src/audio/pipeline/pipeline-stream.c, src/audio/pipeline/pipeline-xrun.c, src/include/sof/audio/component_ext.h, zephyr/edf_schedule.c
with connected pipelines, if an XRUN occurs on one of them, all of them should be stopped
=> stop all connected pipelines on XRUNs

src/platform/amd/renoir/platform.c, src/platform/haswell/platform.c, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, src/platform/imx8ulp/platform.c, src/platform/intel/cavs/platform.c, src/platform/library/platform.c
All platform.c files contain timer objects, and some also arch_timers and most platforms define those objects as global. Make them static.
=> platform: (cosmetic) make all timer objects static

scripts/xtensa-build-zephyr.sh
RIMAGE_KEY was global and leaking from one platform to the next
=> xtensa-build-zephyr: fix RIMAGE_KEY when building multiple platforms
