thesofproject/sof

src/drivers/intel/ssp/ssp.c

~2 commits~ 1 commit
- ssp.c: fix recent arg count regression in dai_info()
- ~xtensa-build-zephyr: add ~-DCMAKE_C_FLAGS='-Werror'~ -DEXTRA_CFLAGS='-Werror'~
Because we can. fixes regression from
commit 287a5f9 ("ssp: mclk/bclk turned off unexpectedly")
```
sof/src/drivers/intel/ssp/ssp.c: In function 'ssp_set_config_tplg':
sof/zephyr/include/sof/trace/trace.h:44:11: warning:
too many arguments for format [-Wformat-extra-args]
44 |    printk("%llu: " format "\n", platform_timer_get(NULL), \
|           ^~~~~~~~
...
sof/src/drivers/intel/ssp/ssp.c:763:4: note: in expansion of macro 'dai_info'
763 |    dai_info(dai, "ssp_set_config(): hw_free stage:
ignore since there is still user", dai->index);
```

ssp.c: fix recent arg count regression in dai_info()

---

src/lib/alloc.c

The calculation 'heap - memmap->buffer + 1' is wrong and may lead to
index overflow when we have multiple buffer mm_heap, it should be
'(heap - memmap->buffer) / sizeof(struct mm_heap) + 1'.
Move the calculation to the end of the brace and make the logic simpler.

alloc: fix a wrong index calculation in heap buffer

---

scripts/xtensa-build-zephyr.sh

The regression in Zephyr mainline is fixed with
https://github.com/zephyrproject-rtos/zephyr/pull/38374 , so
the XCC build can be renabled for cAVS targets.

xtensa-build-zephyr: re-enable XCC build for Intel cAVS hw

---

src/audio/buffer.c
zephyr/wrapper.c

This is the prerequisites of the Heap refinement PR.

Heap refinement Part1 -- prerequisites

---

.github/workflows/zephyr.yml
scripts/xtensa-build-zephyr.sh
zephyr/docker-build.sh

4 commits. Main ones:
- support CMake arguments
- Add -Werror in CI

zephyr: Support cmake args. Add -Werror in CI

---

src/lib/alloc.c

This reverts commit ffff0b061019d3ac02cf038bcc5c746cbb0e83d8. Both heap and memmap->buffer are of type struct mm_heap so their difference is already a number of struct mm_heap sized elements between them. Dividing by sizeof(struct mm_heap) again is wrong.

Revert "alloc: fix a wrong index calculation in heap buffer"

---

scripts/xtensa-build-zephyr.sh

2 commits, main one:
xtensa-build-zephyr: add option to stop after cloning Zephyr
This is needed by CI to clone only once and then take control of the
iteration over platform builds. CI already does all that but by
copy/paste/diverge of this clone() function.
Once cloning Zephyr in CI code is de-duplicated and uses this new
clone-only feature instead, it will be possible to submit any Zephyr
commit to SOF testing.  In other words it will make failed attempt
#4728 possible

xtensa-build-zephyr: add option to stop after cloning Zephyr

---

src/arch/xtensa/exc-dump.S
src/arch/xtensa/include/arch/atomic.h
src/arch/xtensa/include/arch/spinlock.h
src/arch/xtensa/xtos/crt1-boards.S
src/arch/xtensa/xtos/reset-vector.S
src/platform/Kconfig
src/platform/mt8195/platform.c

Hi sirs,
This is Allen Cheng from MediaTek.
There are some commits I don't put in the previous pull request.
Most of them will modify the common code in sof.
Some are hw restriction (compile error) and feature(mpu) when we develop mt8195 in chromebook.
If there is any comments, please let me know.
Thanks.

Add mt8195 platform specific changes

---

scripts/xtensa-build-all.sh
src/arch/xtensa/CMakeLists.txt
src/drivers/mediatek/mt8195/CMakeLists.txt
src/drivers/mediatek/mt8195/afe-memif.c
src/platform/Kconfig
src/platform/mt8195/CMakeLists.txt

Hi, this is Allen Cheng from MTK.
Those patches are for the support mt8195 build option of fw image in sof.
If there is any comments, please let me know.
Thanks.

Add mt8195 build to script

---

src/platform/Kconfig

there is no s32c1i instructions in mt8195.
it will use exclusive instructions.
(XCHAL_HAVE_EXCLUSIVE is defined in core-isa.h)
Select CONFIG_XTENSA_EXCLUSIVE  by default.
Signed-off-by: Allen-KH Cheng <allen-kh.cheng@mediatek.com>

kconfig: select XTENSA_EXCLUSIVE for mt8195

---

tools/topology/topology1/development/CMakeLists.txt

We plan to test the CI test topology on ADL-P nocodec device, so
add the topology build support in cmake list.
Signed-off-by: Zhang Keqiao <keqiao.zhang@intel.com>

topology1: add a test topology sof-adl-nocodec-ci build support

---

scripts/xtensa-build-zephyr.sh

"tree" is very useful but it's not critical, so don't fail the build
when it's missing.
Also remove a single quote from the help message as it breaks parsing
in one simple editor I use (jed) and possibly others.

xtensa-build-zephyr: make "tree" optional

---

scripts/docker_build/sof_builder/Dockerfile

In order to support AMD as part of the docker image and CI we need to
include it in the build list as the overlays are already added to the
overlay repo.

docker: add renoir to docker build

---

src/audio/host.c

Sometime, we could hear some noise after recording.
In host_prepare, reset dma buffer would be good
in general case to prevent reading uninitialized memory.
Add reset dma buffer zero to avoid unexpected noise
Signed-off-by: YC Hung yc.hung@mediatek.com
Signed-off-by: Allen-KH Cheng allen-kh.cheng@mediatek.com

host: add dma buffer clear

---

src/arch/xtensa/CMakeLists.txt

This patch removes the unnecessary and unscalable -x option.
This option aims to add an offset to the .data section of
its parent .module section. This is horrible idea because this
offset will vary depend on the compiler used. It is better and
much easier to just store only the .data section so the offset
is always 0.
Rimage side change -> https://github.com/thesofproject/rimage/pull/68

build system: remove -x option from rimage invocation

---

src/init/init.c
src/ipc/dma-copy.c
src/lib/alloc.c
src/platform/intel/cavs/platform.c
src/trace/dma-trace.c
src/trace/trace.c

This reverts commit 7df3674 + reverts its followup commit + 1 line fix  for DEBUG_TRACE_PTR()
It has been successfully tested in TEST PR #4758 
See commit messages, the main one copied here:
This restores the ability to use CONFIG_TRACEM (copy everything to
mailbox) without crashing, in other words it fixes #4699
This also fixes the other DSP panic #4676 and removes the need for
logical changes in #4678, which can be reverted too.
commit 7df3674 ("trace: enable trace after it is ready") was meant
to fix a crash when tr_xxx() was used early. However I've used very
early tracing for months and it never caused any crash (see #4334)
I tried adding a tr_err() statement immediately after trace_init(sof) in
primary_core_init() and it works just fine. primary_core_init() runs
extremely early so I …

Revert trace enable commits, fix DEBUG_TRACE_PTR() macro so it can be used early

---

tools/topology/topology1/CMakeLists.txt

sof-adl-rt1316-l2-mono-rt714-link0 should be
sof-adl-rt1316-l2-mono-rt714-l0

topology1: fix a typo of a tplg name in CMakefile

---

src/audio/mixer.c
src/ipc/ipc-common.c
src/ipc/ipc-helper.c
src/ipc/ipc3/helper.c
src/ipc/ipc4/dai.c
src/ipc/ipc4/handler.c

Recently new pipeline status PRE_START and PRE_RELEASE are introduced to SOF and also msg reply method change. This patch apply it to ipc4.
And also enable multiple pipeline for mixin & mixout.

IPC4: pipeline:  apply new pipeline status change to IPC4

---

tools/testbench/file.c
tools/testbench/testbench.c

Previously the file component stored component data to device
private data similarly as processing components. However the
pipeline treats file as DAI. Without this patch the missing driver
and DAI operation get_init_delay_ms() causes a segfault in pipeline
parameters walk. It is sufficient for the walk to pass to have just
rzalloc() cleared pointers in driver structure.
The file component data is now placed into DAI private data.

Tools: Testbench: File write DAI needs data structures of DAI

---

src/lib/alloc.c
src/trace/Kconfig

This small series perform fixes to help for heap allocation debugging:
1. No matter if CONFIG_DEBUG_HEAP selected or not, we need to print out
error message when allocation failed.
2. trace: Kconfig: disable filtering by default

trace: fixes to help for heap allocation debugging

---

src/ipc/dma-copy.c
src/trace/dma-trace.c

When I use logger to trace the sof message, there some left data in dma buffer.
I find trace_work updates host pointer after dma_copy_to_host_nowait.
but dma_copy_to_host_nowait will send ipc msg before updating the new host offset.
I think the ipc_msg_send (send the host_offset information) should be after update host pointer.
If there is anything I don't well considered, please let me know.
Thanks.

dma-trace: send ipc msg after update host pointer

---

.github/workflows/pull-request.yml
CMakeLists.txt
scripts/cmake/git-submodules.cmake
src/arch/xtensa/CMakeLists.txt

Faster CI, no dependency accidentally sneaking in

cmake: do not download submodules when BUILD_UNIT_TESTS or CONFIG_LIBRARY

---

src/drivers/dw/dma.c
src/platform/baytrail/lib/dma.c
src/platform/haswell/lib/dma.c

Align the DMAC usage and channel mappings with the closed source firmware.
This may help with DMA stability when trace is disabled.
Compile tested only as I have no working BYT/CHT HW.

byt: align DMA mapping with closed source FW

---

CODEOWNERS
src/drivers/amd/renoir/ipc.c
src/platform/amd/renoir/include/platform/lib/mailbox.h
src/platform/amd/renoir/include/platform/platform.h

This pull request enables the support to dump panic info during any firmware exceptions on renoir platform.
Fix for IPC timeouts during firmware boot up time.
Add code owners for AMD platforms.

Add panic dump debug support for renoir

---

src/ipc/ipc-helper.c
src/ipc/ipc3/helper.c

When freeing we currently implicitly are trusting the ID to match the
type specified in the message. From a security standpoint this is wrong,
never trust the other side. This is the likely cause of how the fuzzer
is leaking memory in pipelines since they have additional allocations
that are not freed when they are treated as a buffer or a component.

ipc: check type before freeing

---

src/trace/Kconfig

This reverts commit 9fadef789e80b586c64cb963dad24f909d579afd.
After multiple trials on a CometLake SoundWire device, this revert to
bring the trace back to what it was seems to be the only solution, the
suggested PR https://github.com/thesofproject/linux/pull/3166 does not
help on this SoundWire device.
We had similar issues with SD offset timeouts and a similar revert
with https://github.com/thesofproject/sof/pull/4578 at the end of
July, there's something that we are missing on what the trace does and
how it impacts the DMA handling.
BugLink: https://github.com/thesofproject/sof/issues/4779

Revert "trace: Kconfig: disable filtering by default"

---

.github/workflows/pull-request.yml

Because it's not needed.
Also add a comment explaining why it's still needed to build topologies
so we can remove it some day and test much faster.

[SKIP CI] .github: testbench: don't use docker to build the testbench

---

src/drivers/mediatek/mt8195/timer.c
src/platform/mt8195/include/platform/drivers/interrupt.h
src/platform/mt8195/include/platform/drivers/timer.h
src/platform/mt8195/lib/clk.c
src/platform/mt8195/platform.c

For driver timer,
use mtk systimer instead of xtensa internal timer.
(xtensa timer clk will affect by dsp clock rate.)
In some test case, we need to sync time in ap and dsp for some debug tools of mtk. 
In our hw design, the architecture of mtk systimer in dsp is the same with AP.

timer: mtk: use mtk systimer for mt8195

---

src/platform/apollolake/include/platform/lib/memory.h
src/platform/library/include/platform/lib/memory.h
test/cmocka/src/lib/alloc/alloc.c

Minor incremental fixes for the merged PR: "the Heap refinement Part 2 -- make full use of HPSRAM in buffer zone
#4735"

Minor fixes

---

src/include/sof/audio/component.h

Get/set large config are natively supported by ipc4 component,
so add these two ops.

ipc4: add get/set large config support in component ops

---

.github/workflows/pull-request.yml
tools/test/audio/comp_run.sh

The run with valgrind will error if memory leaks are detected.

Tools: Test: Audio: Run testbench tests with valgrind

---

.github/workflows/zephyr.yml

The upstream zephyr adds new SDK requirement for APL,
upgrade zephyr SDK version to 0.13.1 for APL build.

[skip ci].github: zephyr: upgrade zephyr SDK for APL

---

src/debug/panic.c

When the length of the path/file name surpass 32, there is no '\0'
anymore in the panicinfo.filename[] array, which will lead to file name
printing errors on the host side like this:
.../include/cavs/lib/pm_memory.h\xd8:472
Here keep the last character in the array as '\0' to fix the issue and
eventually got correct output like this:
.../include/cavs/lib/pm_memory.h:472

debug: panic: fix log file name error

---

tools/topology/topology1/CMakeLists.txt

Same as before but with newer SDCA codecs.
Matching kernel PR: https://github.com/thesofproject/linux/pull/3162
BugLink: https://github.com/thesofproject/linux/issues/3161

topology1: add missing Dell SKU 0A45 topology

---

scripts/xtensa-build-zephyr.sh

Add imx8x platform to be tested with Zephyr.
This refers to i.MX8QXP target.
The support in Zephyr was merged: https://github.com/zephyrproject-rtos/zephyr/pull/38684

Build SOF with Zephyr for imx8x

---

Kconfig.xtos-dbg
src/include/sof/lib/alloc.h
src/lib/alloc.c
src/platform/intel/cavs/lib/memory.c

alloc: add support of coherent buffer allocation
Ask for coherent/uncached pointer while allocating buffer from the
buffer zone with flag SOF_MEM_FLAG_COHERENT specified.
When freeing buffer blocks, try both cached and uncached address if
needed, to make sure the freeing will succeed.

 Heap refinement Part 3 -- Buffer coherent support

---

zephyr/docker-build.sh

It's apparently not stale but "stable".

[SKIP CI] zephyr/docker-build: fix "stale" ZEPHYR_SDK_INSTALL_DIR comment

---

tools/topology/topology1/sof/pipe-codec-adapter-playback.m4

This adds 'codec_adapter' pipeline configuration  allowing this
pipeline to be part of a more complex topology.
Important configuration here is the 'scheduler' widget. Without this,
'codec_adapter' would work in a more complex topology. This is because
each individual pipeline needs to have a 'scheduling' component.

topology1: codec_adapter: Add 'codec_adapter' pipeline configuration

---

src/drivers/amd/renoir/acp_dmic_dai.c
src/drivers/amd/renoir/acp_dmic_dma.c
src/include/sof/drivers/acp_dai_dma.h

Fix dmic sample rate to 16000 as default sample rate.
Signed-off-by: balapati <balakishore.pati@amd.com>

drivers: amd: renoir: Fix 16K sample rate for dmic

---

src/audio/copier.c
src/audio/pipeline/pipeline-schedule.c
src/audio/smart_amp/smart_amp.c
src/drivers/mediatek/mt8195/afe-drv.c
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c
src/platform/amd/renoir/lib/clk.c
src/platform/amd/renoir/platform.c

Somehow developers don't seem to like static analysis. Come on people, use tools!
cppcheck --platform=unix64 --force --max-configs=1024 --inconclusive --enable=all --suppress=variableScope --suppress=shiftTooManyBitsSigned --suppress=arithOperationsOnVoidPointer --suppress=bitwiseOnBoolean src
The findings are rather spectacular this time! I also filed issues #4817 and #4816 when I didn't know how to fix the code.

Cppcheck fixes

---

src/drivers/intel/ssp/mn.c
src/drivers/intel/ssp/ssp.c
src/include/ipc/dai-intel.h
src/include/ipc/dai.h
src/include/sof/drivers/ssp.h
tools/topology/CMakeLists.txt
tools/topology/platform/common/ssp.m4
tools/topology/sof-jsl-rt5682.m4

1. PR4391 for mclk/bclk control
4c2492a50 intel: ssp: fix missing return code on bclk configuration issue
0295d7b7d ipc: dai: add flags for DAI_CONFIG IPC
d4392b7ac ipc: dai-intel: add SOF_DAI_INTEL_SSP_CLKCTRL_MCLK/BCLK_ES bits
2106a7fc1 intel: ssp: introduce ssp_set/release_mclk/bclk helpers to set/release mclk/bclk
455eccab2 intel: ssp: handle MCLK/BCLK early start
f0c81d487 intel: ssp: handle TSRE and RSRE along with SSE
4b4235966 topology: ssp: mclk/bclk clock control
2. topology for  cs42l42
f678c88f9 topology: sof-jsl-rt5682: add support for cs42l42 with max98360a
3. fixes for the clock control feature
b06f7e5f0 drivers: Intel: SSP: ignore config when SSP is already configured
0c57c2602 ssp: mn: mdivctrl corruption in mn_release_mclk()
3e68d2fcf ssp: bclk/mclk control is ignored …

Backport cs42l42 support to jsl-005-drop-stable

---

src/audio/pipeline/pipeline-schedule.c

the logic was just wrong as discussed in
https://github.com/thesofproject/sof/pull/4818#discussion_r719091909
remove test on cmd and flip logic for first_pipe
Fixes: 107b60ea6 ('pipeline: simplify handling of first pipeline')

pipeline: fix handling of first pipeline

---

src/platform/imx8m/lib/clk.c
src/platform/imx8m/platform.c
zephyr/CMakeLists.txt

Add support for i.MX8MP to build Sound Open Firmware with Zephyr OS.
Pull requests were also opened on:
- Zephyr repo - see [#39050](https://github.com/zephyrproject-rtos/zephyr/pull/39050)
- xtensa_hal - see [#13](https://github.com/zephyrproject-rtos/hal_xtensa/pull/13)

Build SOF with Zephyr on i.MX8MP

---

src/platform/mt8195/platform.c

change prefix windows name from
NUM_IMX_WINDOWS
to
NUM_MTK_WINDOWS
Signed-off-by: Allen-KH Cheng <allen-kh.cheng@mediatek.com>

platform: mtk: fix wrong prefix windows name

---

CODEOWNERS

Add code owners of mt8195 for mediatek platform.
Signed-off-by: Allen-KH Cheng <allen-kh.cheng@mediatek.com>

CODEOWNERS: add code owners for mt8195

---

src/drivers/imx/sdma.c

Fix the following warning when building SOF with zephyr:
"warning: format '%x' expects argument of type 'unsigned int',
but argument 3 has type 'long unsigned int'".

drivers: imx: sdma: fix warning

---

src/audio/codec_adapter/CMakeLists.txt
src/audio/codec_adapter/Kconfig
src/audio/codec_adapter/codec/cadence.c
src/include/sof/audio/cadence/src_pp/xa_src_pp_api.h
src/include/sof/audio/codec_adapter/codec/cadence.h

This includes the basic declarations for SRC from Xtensa
support.
It adds the codec id, initializes the API member of
cadence_api with exported library function for SRC and
enables support for linking in the binary codec from Cadence.
All these for the purpose of using Sample Rate Converter
from Xtensa.

codecs: cadence: src: Add support for SRC from Xtensa

---

.github/workflows/installer.yml
installer/GNUmakefile
installer/tests/staging_sof_ref.txt

Clean cherry-picks, zero conflict

Cherry-pick installer updates  to stable-v1.9, especially ADL links and new tarball target

---

tools/topology/CMakeLists.txt
tools/topology/sof-tgl-max98357a-rt5682.m4

topology: add max98390 2/4 speakers support
1. add 2ch/4ch playback configuration
2. add 98390 echo reference support
3. add bt_offload support

topology: add max98390 2/4 speakers support

---

tools/topology/topology1/sof-imx8-compr-wm8960-mixer.m4
tools/topology/topology1/sof-imx8mp-compr-wm8960-mixer.m4
tools/topology/topology1/sof/pipe-codec-adapter-playback.m4
tools/topology/topology1/sof/pipe-host-codec-adapter-playback.m4

This fixes commit 771db86de29 which broke simple codec adapter pipelines. We introduce a new pipeline configuration named pipe-host-codec-adapter.m4 and use it for mixer pipeline. And getting back to using pipe-codec-adapter.m4 for simple codec adapter pipelines.

Codec adapter fixes

---

src/init/init.c
src/ipc/dma-copy.c
src/lib/alloc.c
src/platform/intel/cavs/platform.c
src/trace/dma-trace.c
src/trace/trace.c

100% clean cherry-pick of #4760

stable-1.9: cherry-pick "Revert trace enable commits, fix DEBUG_TRACE_PTR() macro so it can be used early #4760"

---

scripts/cmake/version.cmake

When compiling with Zephyr, SOF_ROOT_SOURCE_DIRECTORY is changed to
sof/zephyr/ and sof/zephyr/.git does not exist. Change error message to
show SOF_ROOT_SOURCE_DIRECTORY/.git

version.cmake: fix message to show why source hash fails with Zephyr

---

scripts/xtensa-build-zephyr.sh

Add imx8m platform to be tested with Zephyr.
imx8m refers to i.MX8MP target.

xtensa-build-zephyr: add imx8m as supported platform

---

tools/topology/CMakeLists.txt
tools/topology/sof-tgl-max98357a-rt5682.m4

This patch adds support for three configurations:
SSP1 connects max98390 2/4 speakers
SSP2 connects max98390 2 speakers
The SSP TDM configuration uses 4 slots for playback and
4 slots for the echo reference capture - regardless of the number of speakers.
UCM files in userspace specify which channels needs to be used on the specific platform.
There is no information reported by the topology/firmware related to valid channels.
Max98390 uses following channels mapping for playback and EchoRef capture
Chan 0 = Left
Chan 1 = Right
Chan 2 = Tweeter Left
Chan 3 = Tweeter Right
(Chan 0 and 1 with regular speakers;Chan 2 and 3 with tweeter speakers)
Adds SSP2 BT_OFFLOAD support in sof-adl-max98390-rt5682.tplg
sof-adl-max98390-ssp2-rt5682-ssp0.tplg doesn't due to ssp2 be used for speakers.
The …

topology: add max98390 2/4 codecs support

---

src/drivers/intel/hda/hda-dma.c

When an older kernel is used, we use the immediate stop. On some
platforms, we see an -EBUSY error that prevents the trigger stop from
working.
This patch adds a check to be 'bug-compatible' with previous releases
and older kernels. An additional fix would be to insert a poll timeout
to make sure the BUSY bit is cleared.
BugLink: https://github.com/thesofproject/sof/issues/4919
Fixes: 7e54f456e ('drivers: Intel: hda-dma: ensure DMA channel is idle after stop')
Suggested-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

drivers: Intel: hda-dma: only check DGCS_BUSY with delayed stop

---

src/drivers/intel/ssp/mn.c
src/drivers/intel/ssp/ssp.c
src/include/ipc/dai-intel.h
src/include/ipc/dai.h
src/include/sof/drivers/ssp.h
tools/topology/platform/common/ssp.m4

Backport mclk/bclk early start feature to adl-003-drop-stable branch for Nuvoton codec on ADL platform enabling.

Backport mclk/bclk early start feature

---

tools/topology/topology2/cavs-nocodec.conf

The DMIC DAI does not have index attribute, so remove it.

topology2: nocodec: remove index initialization from DMIC instance

---

tools/topology/topology2/include/dais/mic_config.conf
tools/topology/topology2/include/dais/mic_extension.conf

Add two classes to be used with dmic for nhlt conformance. Mic extension
includes snr and sensitivity values. Mic vendor config has multiple
values for defining the mic array geometry and mic positions.
Do not add tokens as these values are used currently only with nhlt
generation. Defining these classes in dmic is optional.

[RFC] topology2: add mic extension and vendor mic config classes

---

src/arch/host/include/arch/lib/cpu.h
src/arch/xtensa/include/arch/lib/cpu.h
src/arch/xtensa/lib/cpu.c
src/drivers/intel/cavs/idc.c
src/idc/idc.c
src/include/sof/drivers/idc.h
src/include/sof/lib/cpu.h
src/include/sof/schedule/schedule.h
src/init/init.c
src/ipc/ipc3/handler.c
src/platform/apollolake/include/platform/lib/pm_runtime.h
src/platform/cannonlake/include/platform/lib/pm_runtime.h
src/platform/icelake/include/platform/lib/pm_runtime.h
src/platform/intel/cavs/include/cavs/drivers/idc.h
src/platform/intel/cavs/include/cavs/lib/pm_runtime.h
src/platform/intel/cavs/lib/pm_runtime.c
src/platform/intel/cavs/platform.c
src/platform/library/include/platform/drivers/idc.h
src/platform/library/schedule/edf_schedule.c
src/platform/suecreek/include/platform/lib/pm_runtime.h
src/platform/tigerlake/include/platform/lib/pm_runtime.h
src/schedule/edf_schedule.c
src/schedule/ll_schedule.c
src/schedule/zephyr_ll.c
tools/testbench/common_test.c
zephyr/wrapper.c

Primary core disables all secondary cores in platform_pg_int_handler() function when going to D0ix state. During coming out from D0ix state (D0ix -> D0), we are not able to restore secondary cores properly. This PR add commits that allow us to enable LPS flow to be used in multicore scenario properly. This PR:
- adds secondary cores data writeback before disabling them;
- adds secondary cores restore during D0->D0ix transition (pm_runtime_get, enable idc interrupt and send power up idc message);
- adds separate booting path in secondary_core_init() function i.e. in case when we have basic firmware structures already allocated (i.e. schedulers, notifier  etc.), which means we are not during cold boot process (memory has not been powered off), we just register and enable required …

lps: restore secondary cores on wake up

---

src/audio/eq_iir/eq_iir.c
src/include/sof/math/iir_df2t.h
src/include/sof/math/iir_df2t_generic.h
src/include/sof/math/iir_df2t_hifi3.h

This patch optimizes the buffer copying and output scaling to
other format than int32_t. The main saving is from not using
read/write frag buffer access functions for every sample.
The saving of processing cycles consumption varies per platform
but a second order IIR stereo EQ on TGL shows 43% improvement for
average copy() duration.

Audio: Optimize IIR performance

---

tools/ctl/CMakeLists.txt
tools/ctl/ctl.c

These flags are required in order to ensure that ctl doesn't have any obvious bugs, for example undefined behaviour related bugs.
Also fix some of the things pointed out by these flags. One of them, the lack of a return value on a non-void function, had been reported as an actual internal bug due to a confusing error message showing up because of it.

tools: ctl: CMakeLists: Add -Wall and -Werror flags 

---

src/schedule/zephyr_ll.c

Tasks in the INIT state aren't on the queue, calling schedule_task_free() for them causes a panic due to the task counter underrun. Don't try to dequeue such tasks.

zephyr: ll_schedule: tasks in INIT state aren't on the task queue

---

src/audio/tdfb/tdfb.c

The tdfb is sending the direction information via the ctrl_data->chanv[]
which is valid in case of SOF_CTRL_TYPE_VALUE_CHAN_GET type.
Correct the message initialization to make sure that the message is
correctly parsed by the receiver.

Audio: TDFB: Use correct type for the IPC message sent on change

---

src/audio/mixer.c

- The first commit just fixes the issue with S24_LE mixing
- The second commit replaces the buffer read/write frag loop with block processing until next circular wrap
- The mixer saturation optimize is handled by PR #4978 that adds to format.h inline functions with intrinsics versions

Audio: Mixer: Optimize sources and sink buffers access

---

tools/topology/topology2/cavs-gain-hda.conf
tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/cavs-windows-simple-pipeline.conf
tools/topology/topology2/include/common/pcm.conf
tools/topology/topology2/include/pipelines/cavs/gain-capture.conf
tools/topology/topology2/include/pipelines/cavs/gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixin-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-capture.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-playback.conf
tools/topology/topology2/include/pipelines/eq-iir-volume-capture.conf
tools/topology/topology2/include/pipelines/passthrough-capture.conf
tools/topology/topology2/include/pipelines/pipeline-common.conf
tools/topology/topology2/include/pipelines/volume-capture.conf
tools/topology/topology2/include/pipelines/volume-demux-playback.conf
tools/topology/topology2/include/pipelines/volume-playback.conf

Add an instance attribute for all pipeline class definitions and the pcm
class. This will be used to instantiate unquir PCM/pipeline instances.
The ID attribute for PCM and the index attribute for pipeline may be the
same as the instance attribute in most cases. But in some cases, the
pipeline ID or the PCM index will be passed from the CMakeLists.txt file
as pre-processor definitions and they will be replaced as needed.

topology2: pcm/pipeline: add instance attribute

---

.github/workflows/codestyle.yml
scripts/checkpatch.pl

The standard location of dictionary.txt is under codespell's package, on
my machine atm (codespell 2.1, Artix Linux):
/usr/lib/python3.9/site-packages/codespell_lib/data/dictionary.txt
Since we enable the codespell by default for SOF I have constant:
No codespell typos will be found - file '/usr/share/codespell/dictionary.txt': No such file or directory
The patch proposes to try to fix up the path following the recommendation
found here:
https://github.com/codespell-project/codespell/issues/1540

scripts: checkpatch: get codespell dictionary path from package location

---

src/lib/wait.c

The parameter for wait_delay() is in ticks, not in usec.
If the calculated delta (in ticks) is 0 then we should set the delta to the
number of tick the requested usec is translated and not the usec value
itself.

lib: wait: Fix poll_for_register_delay() if delay is less then 8 ticks

---

src/drivers/intel/dmic/dmic_computed.c
src/drivers/intel/dmic/dmic_nhlt.c
src/include/sof/drivers/dmic.h
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c

- Fixes error in check of cic_control register
- Fixes xrun errors when BFTH in blob is not 3 that is the hard-coded burst_elems size in dai
- Add check for too large non-supported BFTH value
- Fixes handling of more unusual blobs with single FIFO or single PDM defined

Drivers: Intel: DMIC: Blob configuration related fixes

---

src/lib/dma.c
src/schedule/ll_schedule.c
src/schedule/zephyr_ll.c

Atomics will use `long` rather than `int` so that they are 64-bit on 64-bit builds and 32-bit on 32-bit builds.
Required by zephyrproject-rtos/zephyr#39531
Originally at zephyrproject-rtos/sof#14
cc @lgirdwood @lyakh @kv2019i

zephyr: update print messages for 64-bit atomics

---

src/include/sof/ipc/common.h
src/schedule/zephyr.c

Recently SOF IPC processing has been modified on multicore systems to let secondary cores reply to IPCs if the primary core has already left the IPC forwarding context. This hasn't been implemented for Zephyr which led to unanswered IPCs and IPC timeouts on the host. This patch lets secondary cores reply to IPCs under Zephyr.

zephyr: fix secondary core IPC completion

---

tools/topology/topology2/cavs-nocodec.conf

With dmic definition already in, add pipeline to make use of the pcm.

topology2: add dmic pipeline to nocodec topology

---

src/drivers/dw/dma.c
src/include/sof/drivers/dw-dma.h
src/platform/tigerlake/include/platform/drivers/dw-dma.h

The lli structs are used by both DSP and DMAC, allocate them from the
runtime_shared heap to avoid being corrupted by cache writing back.
This helps to fix a lot of DMA xrun issue according to the validation.

dw-dma: change to use runtime_shared heap for lli buffer

---

src/include/sof/audio/format.h
src/include/sof/audio/format_generic.h
src/include/sof/audio/format_hifi3.h

This patch adds two included header files format_generic.h and
format_hifi3.h. The latter contains intrinsics operations
optimized versions of 16, 24, and 32 bit saturations. Generic
header contains the previous C versions those will be used
for anything else but xt-xcc HiFi3 compatible build.

Audio: Optimize saturation inline functions in format.h

---

tools/topology/topology1/sof-tgl-max98373-rt5682.m4

This patch adds flag to choose Bluetooth audio offload support from the CMake list.
Signed-off-by: Jairaj Arava <jairaj.arava@intel.com>

topology: sof-tgl-max98373-rt5682: add flag for Bluetooth audio offload

---

tools/topology/topology2/cavs-nocodec.conf

The current topology2 requires to set id in PCM.pcm and to set index in Pipeline.

topology2: cavs-nocodec: fix dmic compile failure

---

src/include/sof/audio/component.h

Allocate comp_dev on runtime_shared zone to use uncached address to fix
cache coherency issue, this should not impact performance too much as it
is not frequently used buffer.

component: allocate comp_dev on runtime_shared zone

---

src/drivers/intel/cavs/ipc.c

cavs-ipc: hold ipc->lock in ipc handler to avoid race
For secondary core target IPC, the IPC handling could be completed on a
secondary DSP core, while the primary core may be in handling an reply
message from the host and touching the IPC_DIPCCTL at the same time, so
there is race condition from different DSP cores in this scenario, and
that actually lead to kinds of IPC timeout as setting of bit
IPC_DIPCCTL_IPCTBIE could be ignore and busy interrupt will be disabled
after that.
Simply holding of ipc-lock in the irq handler fixes the issue, according
to stress test with multi-core scenarios.

Ipc fix for multi-core scenarios

---

tools/topology/topology1/CMakeLists.txt

1. change the sof-adl-nocodec.m4 to assign pipelines on all 4 DSP cores, this will enable "PR multi-core + dynamic pipeline" validation coverage.
2. change the sof-tgl-nocodec.m4 to assign pipelines on all DSP cores for tgl-nocodec, which will be run on daily test as comparison with ADL one.

Add multi-core coverage to CI

---

tools/topology/CMakeLists.txt
tools/topology/sof-tgl-max98357a-rt5682.m4

Backport topology to adl-003-drop-stable branch by request from Waves. Same topology is already on adl-002-drop-stable.

topology: sof-adl-max98360a-rt5682: backport to adl-003-drop-stable branch

---

src/audio/copier.c
src/audio/dai.c
src/drivers/dw/dma.c
src/include/ipc4/copier.h
src/include/ipc4/fw_reg.h
src/include/sof/lib/dai.h
src/include/sof/lib/dma.h
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c
src/ipc/ipc4/handler.c
src/platform/apollolake/include/platform/lib/shim.h
src/platform/baytrail/include/platform/drivers/dw-dma.h
src/platform/cannonlake/include/platform/lib/shim.h
src/platform/haswell/include/platform/drivers/dw-dma.h
src/platform/icelake/include/platform/lib/shim.h
src/platform/intel/cavs/include/cavs/drivers/dw-dma.h
src/platform/suecreek/include/platform/lib/shim.h
src/platform/tigerlake/include/platform/lib/shim.h

Linear link position (llp) is updated in llp register by GP-DMA hardware. Now it is enabled by SOF FW but not used.
This patch set up a path to read it and update it to host driver.

IPC4: add llp reading support

---

scripts/xtensa-build-zephyr.sh

Because ICL fails to build, .noinit/.cached section overlap since
revert zephyrproject-rtos/zephyr#40319

xtensa-build-zephyr: temporarily exclude ICL 

---

src/audio/tdfb/tdfb.c

This patch adds method tdfb_params() where comp_verify_params() is
called with BUFF_PARAMS_CHANNELS. With it the TDFB can get the
different channels count buffers for source and sink and initialize
correctly.

Audio: TDFB: Fix issue with different input and output channels count

---

src/schedule/ll_schedule.c

In schedule_ll_client_reschedule(), we only need to check those tasks
who ask for rescheduling, for others (e.g. _COMPLETED ones), we should
not take them into account for next_tick calculation.

ll_schedule: only check tasks asked for rescheduling

---

zephyr/include/sof/atomic.h

Zephyr commit 174cb7f9f183 switched 'atomic_t' from 'int' to
'long' and broke SOF compilation as shown below.
Recent SOF commit 970d7d61ece9 ("zephyr: update print messages for
64-bit atomics") switched all atomic_read() logs to "%ld" instead of
"%d" which fixed compilation with Zephyr after the switch but broke it
with Zephyr _before_ the switch.
This no-op (long) cast makes SOF compatible with Zephyr both before and
after the switch.
Note the sof-logger does not make any difference between %ld and %d and
does not care.
Sample failure:
```
src/lib/dma.c: In function 'dma_get': sof/src/include/sof/trace/trace.h:290
error: format '%d' expects argument of type 'int', but
argument 5 has type 'atomic_val_t' {aka 'long int'} [-Werror=format=]
290 |   printk("%llu " format "\n", …
```

zephyr/atomic.h: add a no-op cast: (long)atomic_read()

---

src/audio/dai.c
src/include/sof/lib/dai.h
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c

Host driver checks llp register data in memory window 0
to update stream position to audio framework.
This patch update this memory location when dma channel
is allocated and dma copy is done.

ipc4: update llp register in memory window 0

---

scripts/xtensa-build-zephyr.sh

Recent commit b9fcc4156e5e ("xtensa-build-zephyr: fix incremental build,
pass CMAKE_ARGS only once") fixed incremental builds. For this it first
needs to guess whether the most recent CMake configuration step failed
or succeeded so it knows what is the current "checkpoint" and what is
the next west command to run. Merely testing whether the build directory
already exists is a very bad guess because that directory could have
been created by some other person or script, or - much worse - it could
have been created by a failed CMake configuration step!
The latter situation makes debugging CMake failures very tedious because
it requires manually deleting the build directory after each CMake
configuration failure.
Fix this by not merely looking for a build directory but by looking
whether …

xtensa-build-zephyr: guess CMake successes and failures better

---

src/Kconfig
src/audio/Kconfig
src/drivers/intel/Kconfig
src/include/sof/math/trig.h
src/math/CMakeLists.txt
src/math/Kconfig
src/math/numbers.c
src/math/trig.c
test/cmocka/CMakeLists.txt

This patch adds src/math/Kconfig with items CORDIC_TRIGONOMETRY_FIXED,
NUMBERS_GCD, NUMBERS_NORM, NUMBERS_VECTOR_FIND, MATH_DECIBELS, MATH_FFT,
MATH_FIR, and MATH_IIR_DF2T.
Configuration FIR and FFT were previously in src/audio/Kconfig but they
were moved to new math location for simplicity.
The CORDIRC_FIXED was removed and replaced by CORDIC_TRINONOMETRY_FIXED
that was used in the actual trig.c module.

Math: Build library functions if enabled from Kconfig

---

tools/topology/topology1/platform/intel/intel-generic-dmic-kwd.m4

This PR adds RTNR support for generic dmic with kwd.

Add RTNR support in intel-generic-dmic-kwd.m4.

---

src/audio/host.c

Some DMA's like the HD-Audio DMA need to be stopped ater the pipeline
has been reset. So call dma_stop op in host reset so that the DMA
can be stopped during the PCM_FREE IPC when the host gets reset.
sof main brnach addresses this issue in this PR:
https://github.com/thesofproject/sof/pull/4922
Signed-off-by: Sathyanarayana Nujella <sathyanarayana.nujella@intel.com>

audio: host: call dma_stop during host reset

---

scripts/xtensa-build-zephyr.sh

ICL linking overlap issue has been fixed by
zephyrproject-rtos/zephyr#39603
This is a logical revert of commit d4b8a01 ("xtensa-build-zephyr:
temporarily exclude ICL")

xtensa-build-zephyr: build ICL by default again

---

src/audio/pipeline/pipeline-schedule.c

PPL_STATUS_PATH_STOP is not necessarily an indication of an xrun, it can also be returned by pipeline_trigger_run() in other perfectly normal cases. Remove the misleading left-over warning.

pipeline: remove a wrong warning

---

src/audio/pipeline/pipeline-schedule.c
src/audio/pipeline/pipeline-stream.c
src/include/sof/audio/pipeline.h
src/include/sof/schedule/schedule.h
src/include/sof/schedule/task.h
src/schedule/ll_schedule.c
src/schedule/schedule.c

Pipeline tasks are scheduled in the order in which they're submitted to the scheduler. When audio streams cross several pipelines it makes sense to begin scheduling from the data source. I.e. for playback pipelines from the host pipeline, for capture pipelines from the DAI pipeline. Currently the DAI pipeline gets scheduled first for both playback and captuure, which for playback always results in a
```
WARN dai_copy(): nothing to copy
```
warning being printed for the first copy attempt. Also, this results in delayed scheduling: the first cycle will then only copy data from the host, so the first real DAI copying will only happen on the second tick.
On the contrary, when stopping to stream, the sink should be stopped first.
This patch takes the streaming direction and the command into …

pipeline: always begin scheduling from the source

---

src/audio/host.c
src/platform/Kconfig

Host component stops copying bytes at element's end and resumes
copying the remaining bytes in the next round. This leads to jitter
between components of the same pipeline. Such jitter might cause
buffer overwrite for component which processes block by block.
Triggering extra DMA copy until all the copy_bytes are copied can
eliminate the jitter and hence no more buffer overwrite occurs.
Signed-off-by: fy.tsuo <fy.tsuo@intelli-go.com>

Host component DMA copy the whole copy_bytes.

---

src/schedule/edf_schedule.c

There could be no more EDF task to be run if the last one in the list is
finished, we don't need to assert in this case.
If the next EDF task gonna be scheduled, interrupt will be generated
again by calling to schedule_edf() in schedule_edf_task(), so it should
be safe to remove the schedule_edf_task_running() in no pending task
scenarios.

edf_schedule: don't assert if there is no extra task to run

---

src/audio/pipeline/pipeline-schedule.c

This fixes a problem with pipelines, connected over a demultiplexer. In such cases one of pipelines keeps an inactive status and terminates during the next scheduler run after a START or a RELEASE.

pipeline: set status to ACTIVE on all connected triggered pipelines

---

tools/topology/platform/intel/intel-generic-dmic-kwd.m4

This PR is to cherry-pick commit that adds RTNR support in intel-generic-dmic-kwd.m4 for adl-003-drop-stable branch.

Add RTNR support in intel-generic-dmic-kwd.m4 for adl-003-drop-stable branch

---

tools/logger/convert.c
tools/logger/logger.c
tools/logger/misc.c
tools/logger/misc.h

Rename asprintf and vasprintf into log_asprintf and log_vasprintf as the
names could clash with the standard libc ones. These functions are there
originally done because of windows compatibility, but the naming was not
thought through carefully.

logger: rename asprintf and vasprintf

---

zephyr/CMakeLists.txt

Discovered the hard way that the Zephyr build assumes sof-logger is
always up to date when present. It's not clear from cmake's
ExternalProject documentation why that is the case. In any case
BUILD_ALWAYS fixes the issue and takes very little time because it does
not rebuild sof-logger from scratch. BUILD_ALWAYS is already used for
XTOS.
Fixes commit f6c71c21d03b8 ("zephyr/CMakeLists.txt: build smex and
sof-logger")

zephyr/cmake: BUILD_ALWAYS for smex and sof-logger

---

tools/topology/topology1/m4/bytecontrol.m4

When the string fields left empty, the alsa topology parser treats
SND_CONFIG_TYPE_STRING type config as -EINVAL, so set default values.

topology: set default values for C_CONTROLBYTES string members

---

scripts/xtensa-build-zephyr.sh

Use a fixed Zephyr mainline commit to build binaries in the SOF2.0
release branch. This Zephyr commit was tested in 2021-12-03 daily
test plans.

scrips: xtensa-build-zephyr: fix Zephyr commit for release

---

src/audio/copier.c
src/audio/mixer.c
src/include/ipc/stream.h
src/include/sof/audio/audio_stream.h
src/ipc/ipc4/helper.c
test/cmocka/src/audio/eq_iir/eq_iir_process.c
test/cmocka/src/audio/mux/demux_copy.c
test/cmocka/src/audio/mux/mux_copy.c
test/cmocka/src/audio/selector/selector_test.c
test/cmocka/src/audio/volume/volume_process.c

Ipc4 stream have container size and valid sample size.
In windows system, container size is normally 32bit
and valid sample size is 16bit or 24bit rely on system
setting. Currently host and dai component are included
by copier module to manage gateway. These two components
doesn't support container size and all the code is designed
for the case that container size is always equal to valid
sample size.
With this patch HDA playback works with default windows audio player in format of 16bit/48000HZ/2CH.  24bit will be added later and it is a little tricky since it is really S24_3LE

Ipc4: container size support in format conversion

---

.github/workflows/codestyle.yml
scripts/sof-post-commit-hook.sh

This is a logical revert of eb45907
Based on recently merged #4941, C99 comments are now OK. I never found
any rationale or even written down coding style for excluding them in
the first place.

check patch: allow C99 comments

---

src/include/ipc4/module.h
src/ipc/ipc4/handler.c

There are two types of power setting ops: set_d0ix and
set_dx. set_d0ix will disable power gating on core 0 and
set_dx will power up the specific core.

ipc4: handler: add module power setting support

---

src/audio/Kconfig

DRC needs some math functions brought in by CONFIG_NUMBERS_NORM and
CONFIG_MATH_DECIBELS.

audio: drc: Select DRC dependencies

---

src/include/sof/drivers/sai.h
tools/topology/topology1/sof-imx8ulp-btsco.m4

Cause BT is not supporting the 16Khz sample rate anymore, we need to match this.

IMX8ULP: Change default sample rate support

---

tools/sof_ri_info/sof_ri_info.py

As reported by @bkokoszx , Python 3.5.2 fails with the relatively cryptic
TypeError: invalid file: PosixPath('sof-tgl.ri'). Make this failure much
less cryptic.
As of December 2021 Python 3.5 is completely out of support and 3.6 will
be soon https://www.python.org/downloads/

sof_ri_info: assert Python version is 3.6 or above.

---

src/audio/mux/mux_generic.c

uint8_t iterator does not work for period size above 256 frames.
Signed-off-by: Lionel <lionelk@google.com>

mux: Change iterator type to uint32_t

---

tools/topology/topology2/cavs-gain-hdmi.conf
tools/topology/topology2/cavs-passthrough-hdmi.conf

The Define block replaces the use of @args for topology2 in the alsatplg
compiler. So replace all users.

topology2: cavs-*-hdmi: replace the use of @args with Define

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/production/CMakeLists.txt

Move generated *.conf and *.tplg v1 files down from:
```
build_tools/topology/topology1/*.{conf,tplg}
```
_to:
```
build_tools/topology/topology1/production/*.{conf,tplg}
```
... then copy/"install" the production/* subdirectory two levels up.
This fixes the race condition #5067 that also copied a random number of
development/ and dsp_enhancement/ topologies, sometimes even truncating
these.
In other words, this commit REMOVES the following two copies:
```
build_tools/topology/development/       # randomly corrupted copy, removed
build_tools/topology/dsp_enhancement/   # randomly corrupted copy, removed
build_tools/topology/topology1/development/    # real build dir, unchanged
build_tools/topology/topology1/dsp_enhancement # real build dir, unchanged
```
Production topologies are copied …

topology1: build the production topologies one level down

---

src/audio/volume/volume.c
src/include/sof/audio/volume.h

The cd->hvol always remain NULL, there is no code path which would
configure it which makes the mapped volume unusable and unused.
The kernel does not use this feature either.
Remove all related code to this non supported feature.

Audio: Volume: Drop unused hvol support (host mmap volume)

---

tools/topology/topology2/cavs-gain-hda.conf
tools/topology/topology2/cavs-gain-hdmi.conf
tools/topology/topology2/cavs-passthrough-hda.conf
tools/topology/topology2/cavs-passthrough-hdmi.conf
tools/topology/topology2/cavs/common_definitions.conf
tools/topology/topology2/include/common/audio_format.conf
tools/topology/topology2/include/common/tokens.conf
tools/topology/topology2/include/components/copier.conf
tools/topology/topology2/include/components/gain.conf
tools/topology/topology2/include/components/mixin.conf
tools/topology/topology2/include/components/mixout.conf
tools/topology/topology2/include/pipelines/cavs/gain-capture.conf
tools/topology/topology2/include/pipelines/cavs/gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixin-capture.conf
tools/topology/topology2/include/pipelines/cavs/mixin-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-capture.conf
tools/topology/topology2/include/pipelines/cavs/mixout-playback.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-capture.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-playback.conf

Requires https://github.com/alsa-project/alsa-utils/pull/127 for compiling.

Add audio formats and other attributes for cavs modules

---

src/audio/selector/selector.c
src/audio/selector/selector_generic.c

This patch replaces the per sample done circular copies with
audio_stream_read/write_frag_s16/32() functions calls with
max. length linear copies.
The original copy function for >1ch sink is just 1:1 copy
from source to sink without controllable channel select. This
patch preserves the functionality and implements the copy with
memcpy().

Audio: Select: Optimize data copy operations

---

src/include/ipc4/fw_reg.h
src/platform/amd/renoir/include/platform/lib/cpu.h
src/platform/apollolake/include/platform/lib/cpu.h
src/platform/apollolake/include/platform/trace/trace.h
src/platform/cannonlake/include/platform/lib/cpu.h
src/platform/cannonlake/include/platform/trace/trace.h
src/platform/icelake/include/platform/lib/cpu.h
src/platform/icelake/include/platform/trace/trace.h
src/platform/intel/cavs/include/cavs/trace/trace.h
src/platform/suecreek/include/platform/lib/cpu.h
src/platform/tigerlake/include/platform/lib/cpu.h
src/platform/tigerlake/include/platform/trace/trace.h

contents of trace.h and cpu.h on all cAVS platforms (except trace.h on Sue Creek) is identical, unify them.

Platform: eliminate common code from trace.h and cpu.h

---

test/test-all-defconfigs.sh

Make test-all-defconfigs.h runnable from anywhere by merely adding a
cmake -S option.

cmocka: make test-all-defconfigs.h runnable from anywhere 

---

scripts/xtensa-build-zephyr.sh

Checksumming the final binary is useful to compare before/after some
configuration change or to compare builds across different people /
systems.
Because rimage is not deterministic, ask sof_ri_info to do this.
Sample output below or at https://github.com/thesofproject/sof/runs/4455053202
```
Firmware file size 0x55000 page count 79
pkcs_v1_5_sign_man_v1_8: signing with key
'modules/audio/sof/keys/otc_private_key.pem'
pkcs: RSA private key is valid.
pkcs: digest for manifest is 5b52ac0b8809503c817a96dac7c5124dba5a90d...
Firmware manifest and signing completed !
Extended manifest found module, type: 0x0001 size: 0x01A0 ( 416) offset:
Extended manifest found module, type: 0x0005 size: 0x0020 (  32) offset:
Extended manifest found module, type: 0x0004 size: 0x0020 (  32) offset:
Extended …
```

xtensa-build-zephyr: add deterministic sha256sum of final .ri file

---

zephyr/CMakeLists.txt

Two directories for cAVS 2.0 and 2.5 in Zephyr CMakeLists.txt don't exist. They're safely ignored, but remove them to avoid confusion.

zephyr: remove non-existent directories from CMakeLists.txt

---

src/platform/mt8195/include/platform/lib/memory.h

For some test case, we adjust share buffer for sof and legacy audio driver.
Signed-off-by: Allen-kh Cheng <allen-kh.cheng@mediatek.corp-partner.google.com>

platform: mt8195: adjust dram audio shared size

---

src/arch/xtensa/hal/CMakeLists.txt
src/arch/xtensa/hal/atomics.c

Add compare_exchange atomic for better support of std::atomic when using
c++.

hal: Add compare_exchange atomics for xtensa.

---

tools/topology/topology2/include/components/gain.conf

It is not intuitive for the end-ser to set linear values for
minimum gain. Set the dB gain min value to -90dB and steps to 2dB.
Also, modify the max to 45 to allow the volume gain range -90dB to 0dB.

topology2: gain: fix dB scale min and step values

---

src/math/trig.c

Fixes warnings:
```
sof/src/math/trig.c:42: warning: Found unknown command '\CORDIC'
sof/src/math/trig.c:103: warning: Found unknown command '\CORDIC'
sof/src/math/trig.c:183: warning: Found unknown command '\CORDIC'
sof/src/math/trig.c:42: warning: Found unknown command '\CORDIC'
sof/src/math/trig.c:103: warning: Found unknown command '\CORDIC'
sof/src/math/trig.c:183: warning: Found unknown command '\CORDIC'
```
etc.

[SKIP CI] math/trig.c: remove bogus \CORDIC doxygen command

---

src/lib/alloc.c

rballoc() doesn't guarantee zero-initialised memory, besides it's often enough called at run-time and for relatively large buffers, so performance losses aren't negligible. Remove the bzero() call.

alloc: don't initialise rballoc() memory

---

src/audio/codec_adapter/codec/cadence.c
src/audio/codec_adapter/codec/dts.c
src/audio/codec_adapter/codec/generic.c
src/audio/codec_adapter/codec/passthrough.c
src/audio/codec_adapter/codec/waves.c
src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/cadence.h
src/include/sof/audio/codec_adapter/codec/dts.h
src/include/sof/audio/codec_adapter/codec/generic.h
src/include/sof/audio/codec_adapter/codec/passthrough.h
src/include/sof/audio/codec_adapter/codec/waves.h

In preparation for introducing a generic module interface API for 3rd party module interface, clean up the codec_adapter interface to remove the get_samples and init_process API's. The new API is still WIP but the idea is shown here: 
https://github.com/thesofproject/sof/commit/8cddb8f51cbfd5bfe691c571c2298c164b91f986

Preparation for introducing a generic module interface API

---

src/platform/apollolake/include/platform/lib/pm_runtime.h
src/platform/cannonlake/include/platform/lib/pm_runtime.h
src/platform/icelake/include/platform/lib/pm_runtime.h
src/platform/intel/cavs/include/cavs/lib/pm_runtime.h
src/platform/suecreek/include/platform/lib/pm_runtime.h
src/platform/tigerlake/include/platform/lib/pm_runtime.h

All cAVS platforms use the same pm_runtime.c implementation, no need for separate headers, repeating the same function declarations.

pm_runtime: unify function prototypes for cAVS platforms

---

src/audio/dai.c
src/audio/selector/selector.c
src/include/sof/audio/component.h
src/ipc/ipc-helper.c

Dma buffer size should align with 32bytes which can't be compatible
with current 45K adjustment. 48K is a suitable adjustment.
Tested 44.1khz music on both Linux & windows

ipc4: refine frame size calculation for 44.1khz

---

tools/topology/topology1/m4/buffer.m4

Pass the core number to the buffer instanciation so buffers can be
allocated on the same core the pipeline is scheduled.

topology: Ensure buffers get allocated on core 0

---

src/audio/component.c
src/audio/kpb.c
src/include/sof/audio/audio_stream.h
src/include/sof/audio/kpb.h
test/cmocka/src/audio/pcm_converter/CMakeLists.txt

The three commits contain the optimizations for the three copy functions. The optimizations are the same for the slightly different functions.

Audio: KPB: Optimize drain, buffer and copy functions

---

src/schedule/ll_schedule.c

scheduler_free_ll() function should invoke domain_unregister()
in case when SOF_SCHEDULER_FREE_IRQ_ONLY flag is used, beacause
in timer domain case, timer_domain_unregister() function
unregisters timer interrupts.
fixes #5114 

ll_schedule: unregister domain in free function with IRQ_ONLY_FLAG

---

scripts/cmake/version.cmake

Fixes old (Aug 2020) and untested commit b2a325a3b7e66 ("cmake: Handle
empty SOF_SRC_HASH_LONG") which tried to use GIT_LOG_HASH as a fallback
for the SOF_SRC_HASH .ldc checksum but always fell back on "0" instead
because of a misunderstanding of cmake's surprisingly complex "if"
operator.
Before Zephyr this was not an issue in practice because GIT_LOG_HASH was
empty anyway when SOURCE_DIRECTORY/.git was missing, so there was
nothing to lose.
For the Zephyr builds this will now use the SOF SHA1 as the .ldc checksum
for now. Probably not ideal yet but far better than the current constant
"0" which means no check at all.
Also log the SOF_SRC_HASH fallback value now and change the second
fallback (when GIT_LOG_HASH is also missing) from "0" to the
searchable hexspeak "baadf00d". …

cmake: fix .ldc chksum fallback when no SOURCE_DIRECTORY/.git

---

test/cmocka/src/audio/mixer/comp_mock.c
test/cmocka/src/audio/mixer/mixer_test.c
test/cmocka/src/audio/pcm_converter/pcm_float.c
test/cmocka/src/audio/pipeline/pipeline_connection_mocks.h
test/cmocka/src/audio/pipeline/pipeline_free.c
test/cmocka/src/audio/pipeline/pipeline_new.c
test/cmocka/src/debugability/macros.c
test/cmocka/src/lib/lib/strcheck.c

The C header file malloc.h does not exist on
some Xtensa processor configurations or host OSes,
include stdlib.h instead because they both provide
the prototype for 'malloc' function.
Fixes: #5102

test: improve compatibility for malloc.h

---

tools/logger/convert.c

Make DMA trace corruption #5120 a bit more visible in the logs.

logger: move "log_entry_address x not in dictionary range" to stderr

---

src/include/sof/trace/trace.h
src/trace/trace.c

Fixes #5032.
Hard-dependency on zephyrproject-rtos/zephyr/pull/40975, Zephyr will fail to build until then.

Zephyr: fix log filtering

---

tools/topology/CMakeLists.txt

This reverts commit eb344375228b15529838d6e4992bc7572650ab5e.
Fixes #5113
The `alsatplg -o -` feature is incompatible with `-v` and basically
buggy because it happily sends .tplg output and debug statements to
the same place without a care. To reproduce the bug, simply run:
```
VERBOSE=1 ./scripts/build-tools.sh -T
```
... then observe .tplg output files like this:
```
B0x003d3b/015675 - pcm 'DMIC': write 912 bytes
B0x0040cb/016587 - pcm 'HDMI1': write 912 bytes
B0x00445b/017499 - pcm 'HDMI2': write 912 bytes
B0x0047eb/018411 - pcm 'HDMI3': write 912 bytes
B0x004b7b/019323 - pcm 'DMIC16kHz': write 912 bytes
B0x004f0b/020235 - block size for type be (11:10) is 0x2ad4/10964
B0x004f0b/020235 - header index 0CoSA^E^@^@^@^@^@^@^@^H^@^@^@$^@^@
^@^@^@^@^@s^@^@^@^@^@^@^@^A^@^@^@p^@^@^@ …
```

Revert "topology: redirection to workaround hardcoded alsatplg permissions"

---

tools/topology/topology1/CMakeLists.txt

Add support for four max98357a speaker amplifiers running in TDM mode
which format is 8 slots with 32 bit slot/sample width on ADL boards.
The only difference between this one and sof-adl-max98360a-rt5682-4ch
is the SSP port for speaker amplifiers; this one is using SSP2 while
max98360a's topology is using SSP1.
This topology implements a 4-channel pipeline directly to speaker
amplifiers so audio effects need to be done in user space.

topology: sof-adl-max98357a-rt5682-4ch: add new topology

---

tools/topology/CMakeLists.txt

Backport topology to adl-003-drop-stable branch for chrome devices. Pending on ODM validation.

topology: sof-adl-max98357a-rt5682-4ch: backport to adl-003-drop-stable branch

---

tools/topology/topology1/sof-mt8195-mt6359-rt1019-rt5682.m4

Default support 1ms period playback pipeline to update host position
more precisely.

topology1: mt8195: support 1ms pipeline playback period

---

src/audio/CMakeLists.txt
src/audio/Kconfig
src/audio/google_rtc_audio_processing.c
src/audio/google_rtc_audio_processing_mock.c
third_party/include/google_rtc_audio_processing.h
third_party/include/google_rtc_audio_processing_platform.h
tools/topology/topology1/m4/google_rtc_audio_processing.m4

Introduce a new component to perform acoustic echo cancellation on capture
path using a buffer from the playback as a reference.
1. Put the google_rtc_audio_processing at
$SOF_REPO/third_party_libraries
- libgoogle_rtc_audio_processing.a
- libgoogle_rtc_audio_processing_tuning.a
- libc++.a (Corresponding stdlibc++)
- libc++abi.a
2. Put the header in $SOF_REPO/third_party_includes
- google_rtc_audio_processing.h
3. Build firmware and tool with xcc
4. To verify it works:
- aplay some speech
- At the same time arecord the mic which uses AEC
The mic signal shoul dnot exhibit any echo from the playback.

comp: Add initial Google AEC

---

scripts/xtensa-build-zephyr.sh

Align with xtensa-build-all.sh and add a "-v" option to toggle
verbose build log ("west -v build").

xtensa-build-zephyr: add -v option for verbose build

---

tools/coredumper/sof-coredump-reader.py

The gdb script created by coredump-reader has a fixed reset
vector address. This address only works on a subset of supported
SOF platforms and for other platforms, user has to manually fix
the reset address in the gdb script before use.
Modify the script to emit breakpoint for "_MemErrorVector"
symbol. This is not the reset vector, but the simulation will
still be trapped early. The symbol is part of the firmware
binary, so its address can be looked up at runtime.
Also add a second breakpoint for "_MemoryExceptionVector_text_start".
This will cover SOF binaries built with Zephyr as the RTOS.
BugLink: https://github.com/thesofproject/sof/issues/5125

coredump-reader: do not hardcode reset vector address

---

tools/test/topology/test-all.m4

Remove the extra space to make the topology build with upstream
alsa-lib.

test: topology: fix build with latest alsa-lib

---

scripts/docker-run.sh

It's super annoying and time-consuming to update the image and wonder
why the previous one is still used. Shortcuts are nice in interactive
use but pointless in scripts.

docker-run.sh: switch from "sof" shortcut to full "thesoftproject/sof" 

---

CODEOWNERS

I am working on ipc interface for IPC4 and will
focus on ipc interface for both IPC3 & IPC4.

codeowner: add rander to review ipc changes

---

tools/topology/topology1/sof-mt8195-mt6359-rt1019-rt5682.m4

Default support 1ms period capture pipeline to update host position
more precisely.

topology1: mt8195: support 1ms pipeline capture period

---

src/include/sof/lib/perf_cnt.h
src/lib/agent.c
src/schedule/ll_schedule.c
src/trace/Kconfig
src/trace/trace.c

\+ other cleanups, comments and clarifications, see commit messages.
Zero functional change.

Log and document "hidden" feature to turn off adaptive trace at run-time

---

scripts/docker_build/sof_builder/Dockerfile

We should gradually switch to ninja as a default.
ninja-build is apparently missing from build-essential

[SKIP CI] Docker: sof: add ninja-build

---

src/arch/xtensa/xtos/CMakeLists.txt
src/arch/xtensa/xtos/stub.c

In order to ease porting algorithm to SOF, it is convenient to have
stubs for some operating system function.
Those stubs are not meant to be called.

xtos: Add stub for some missing OS function

---

CODEOWNERS

Marcin is responsible for ipc4 enabling in SOF and integration with Windows drivers.

codeowner: add Marcin to review ipc changes

---

src/platform/Kconfig

Let's enable this capability, with ApolloLake left out for now since there
are known issues with suspend-resume on Up2 board that were never
root-caused.
Enabling this at the firmware level is not enough, this capability
need to be enabled by kernel patches in
https://github.com/thesofproject/linux/pull/3340

platform: cavs: make IMR restore feature default - except APL

---

src/include/sof/common.h
src/lib/lib.c
src/platform/apollolake/CMakeLists.txt
src/platform/cannonlake/CMakeLists.txt
src/platform/icelake/CMakeLists.txt
src/platform/suecreek/CMakeLists.txt
src/platform/tigerlake/CMakeLists.txt

SOF loves `memset()`. It takes great care to 0-initialise buffers and objects. And its `memset()` routine only sets one byte at a time. Optimise it to use 32-bit assignments where possible.
In fact it's weird. We have a SIMD-optimised version of `memset()`, accessible via `bzero()` and `memset_s()`, but that's only available to XCC builds (this is logical, gcc doesn't support Xtensa SIMD) **and** there are still a lot of locations, where the plain `memset()` is called. Since the plain `memset()` is anyway all, that's available to gcc, it's good to optimise it anyway. And we should move all plain `memset()` calls to `memset_s()` or `bzero()`. What about `memcmp()`, `memcpy()` etc.?

lib: use 32-bit assignments for memset()

---

src/audio/CMakeLists.txt
src/audio/Kconfig
src/audio/google_rtc_audio_processing.c
src/audio/google_rtc_audio_processing_mock.c
third_party/include/google_rtc_audio_processing.h
third_party/include/google_rtc_audio_processing_platform.h
tools/topology/m4/google_rtc_audio_processing.m4

This backports Google Initial AEC to alderlake branch
The differences with the original PR are:
the buffer locking API which have changed (due to API change in SOF)
create function signature.
Original PR: #5090

comp:Add initial Google AEC (adl-003-drop-stable)

---

src/audio/mux/mux_generic.c

This backports bugfix in mux component (PR #5060)  allowing processing bigger buffer in pipelines.

mux: Change iterator type to uint32_t (adl-003-drop-stable)

---

src/audio/mux/mux_generic.c

This backport PR #5060 to tgl-013-stable branch
uint8_t iterator does not work for period size above 256 frames.
Using large buffers (>5ms @ 48kHz) without this patch results
in the copy being an infinite loop.

mux: Change iterator type to uint32_t (tgl-013-drop-stable)

---

src/arch/xtensa/hal/CMakeLists.txt
src/arch/xtensa/hal/atomics.c

Backports PR #5089  to adl-003-drop-stable.
Add compare_exchange atomic for better support of std::atomic when using
c++.

hal: Add compare_exchange atomics for xtensa. (adl-003-drop-stable)

---

src/arch/xtensa/xtos/CMakeLists.txt
src/arch/xtensa/xtos/stub.c

Backports PR #5092 to adl-003-drop-stable
In order to ease porting algorithm to SOF, it is convenient to have
stubs for some operating system function.
Those stubs are not meant to be called.

xtos: Add stub for some missing OS function (adl-003-drop-stable)

---

src/arch/xtensa/hal/CMakeLists.txt
src/arch/xtensa/hal/atomics.c

Backport PR #5089 to tgl-013-drop-stable
Add compare_exchange atomic for better support of std::atomic when using
c++.

hal: Add compare_exchange atomics for xtensa. (tgl-013-drop-stable)

---

src/arch/xtensa/xtos/CMakeLists.txt
src/arch/xtensa/xtos/stub.c

Backports PR #5092 to tgl-013-drop-stable
In order to ease porting algorithm to SOF, it is convenient to have
stubs for some operating system function.
Those stubs are not meant to be called.

xtos: Add stub for some missing OS function (tgl-013-drop-stable)

---

tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/cavs/cavs-sdw.conf

Add audio format tokens for cavs-sdw.conf

topology2: cavs-sdw: add audio format tokens

---

scripts/xtensa-build-zephyr.sh

Include DEFAULT_PLATFORMS in SUPPORTED_PLATFORMS instead of the other
way round. SUPPORTED_PLATFORMS will always be bigger than
DEFAULT_PLATFORMS and it's easier to add a platform than remove one.

xtensa-build-zephyr: include DEFAULT_PLATFORMS in SUPPORTED_PLATFORMS

---

src/drivers/imx/sai.c
src/drivers/imx/sdma.c

This PR contains two small fixes related to pause/resume for SAI  + SDMA related to wrong state handling and not calling sai_start() on release.
pause/resume feature still needs to be reviewed.

SDMA suspend/resume fixes

---

tools/topology/topology1/m4/dai.m4
tools/topology/topology1/platform/intel/intel-generic-dmic-kwd.m4
tools/topology/topology1/sof-apl-keyword-detect.m4
tools/topology/topology1/sof-cml-rt5682-kwd.m4
tools/topology/topology1/sof-glk-da7219-kwd.m4
tools/topology/topology1/sof-imx8-wm8960-kwd.m4
tools/topology/topology1/sof-imx8mp-wm8960-kwd.m4

Pipeline extects PIPELINE_FORMAT to be defined. When including a
pipeline using DAI_ADD, DAI_FORMAT is defined but no PIPELINE_FORMAT.
Prior c687815, the last previously defined PIPELINE_FORMAT was used.
This change ensure the requested DAI_FORMAT is used in the pipeline.
This resolve #5193.

topology: define PIPELINE_FORMAT from DAI_ADD

---

src/audio/base_fw.c

MAX_CORE_COUNT was removed in commit 2bd41aaf265e ("platform: remove MAX_CORE_COUNT")
to fix ipc4 build it needs to use CONFIG_ version
but anyway CONFIG_CORE_COUNT should be used here instead of CONFIG_MAX_CORE_COUNT, 
like in recently added dsp_properties

ipc4: report correct value for hw core count

---

src/audio/copier.c
src/audio/mixer.c
src/ipc/ipc4/helper.c

This will allow to remove invalidate calls for each component init

ipc4: invalidate HOSTBOX for comp_new

---

src/drivers/mediatek/mt8195/afe-memif.c

Fix log to Show sgen_id in mt8195_afe_sinegen_enable function.

platform: mt8195: fix afe-memif sinegen log error

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4

Add support for boards without speaker amplifier. Just simply remove
all speaker related components and configuration.

topology: sof-adl-rt5682: add new topology

---

src/trace/dma-trace.c

Add Zephyr git version in the initial FW ABI banner. Sample output:
```
SHM: FW ABI 0x3014000 DBG ABI 0x5003000 \
SOF:v2.0-rc1-245-g4be53bca4ab5-dirty zephyr:v2.7.99-3167-g8a8abd69228d \
src hash 0xb8098c48 (ldc hash 0xb8098c48)
```
Progress for #5093

trace: add Zephyr git version to the initial FW ABI banner

---

src/audio/CMakeLists.txt
src/audio/Kconfig
src/audio/aria/CMakeLists.txt
src/audio/aria/aria.c
src/audio/aria/aria_hifi3.c
src/include/ipc4/aria.h
src/include/sof/audio/aria/aria.h

Automatic Regressive Input Amplifier Module
At initial release only hifi3 version is supported

ipc4: add Aria module support for ipc4

---

src/audio/copier.c

The issue was found when testing 44.1khz stream on windows.
We should use input format of copier to set source buffer fmt,
not output fmt which may be dai output fmt and different from
source fmt.
According to spec, copier only support one input source and
four output sinks, so we don't need to check source list.
Tested on windows.

ipc4: fix a regression issue on windows

---

zephyr/CMakeLists.txt

Select correct IPC implementation depending on the selected version.
Note, that the current SOF IPC4 implementation has its own internal problems yet, so enabling `CONFIG_IPC_MAJOR_4` with Zephyr might generate compilation issues, etc. Those have to be addressed separately.

zephyr: add support for IPC4

---

tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/cavs/cavs-nocodec.conf

Add audio format tokens for I2S + DMIC.

topology2: cavs-nocodec: add audio format tokens

---

.github/workflows/pull-request.yml
scripts/xtensa-build-all.sh

4 commits. Main one below. Also: fix toolchain coverage in CI
The -a option has been broken by the addition of platform(s) that don't
have a toolchain available in the Docker image. Every platform can be
built by someone but no one can built -a(ll) platforms right now.
Fix the -a option by changing its definition: make it build what
everyone can build using the public Docker image.

xtensa-build-all.sh: distinguish default/working platform and WIP. Fix toolchain coverage

---

tools/topology/CMakeLists.txt
tools/topology/topology2/cavs/CMakeLists.txt

If there are not command line definitions, the build fails because the
4th argument to the add_alsatplg2_command macro is NULL.
Fix this by using named arguments for the macro and checking for the
optional argument for command line definitions.

topology2: fix build issues with no command line definitions

---

src/audio/Kconfig
src/audio/copier.c
src/audio/pcm_converter/pcm_converter_generic.c
src/drivers/intel/hda/hda-dma.c
src/include/ipc4/gateway.h
src/include/sof/audio/audio_stream.h
src/include/sof/audio/format.h
src/include/sof/audio/pcm_converter.h

S24_3LE is not a native supported format for hda dma. Driver
treats it as 16bit stream or 8bit stream, .e.g. 24bit 3LE
2ch stream will be set as 16bit 3ch stream. In FW side,
24bit stream will be converted to S24LE.
Currently HIFI3 optimization is not supported now and also
S24_LE unit test is not implemented. These will be supported
later.
Tested on windows platform.

ipc4: add S24_3LE for ipc4

---

src/audio/buffer.c
src/include/sof/audio/buffer.h

This patch leaves out low value debug traces with CONFIG_LIBRARY for
comp_update_buffer_produce() and comp_update_buffer_consume(). They
are too far too verbose and slow down testbench runs, and cause
massive size data files if traces are captured to files.

Audio: Buffer: Remove too verbose buffer debug traces for CONFIG_LIBRARY

---

tools/topology/topology2/cavs/cavs-nocodec.conf
tools/topology/topology2/cavs/cavs-sdw.conf

We do support 32 bit format. So add S32 to pcm_caps.

topology2: cavs-sdw: cavs-nocodec: add S32 format

---

src/audio/pipeline/pipeline-stream.c

When pipeline_get_timestamp() fails it prints a warning message without context. Replace it with a more informative one.

pipeline: improve timestamp failure reporting

---

tools/test/audio/comp_run.sh
tools/test/audio/test_utils/test_run.m

The first patch fixes a regression with valgrind execution for quality tests. The second and third patch fix the massive trace flood from verbose trace from making tests run very slow.

Tools: Audio: Test: Fixes for Matlab audio quality test scripts run

---

src/audio/asrc/asrc.c
src/audio/asrc/asrc_farrow.c
src/include/ipc4/asrc.h
src/include/sof/audio/asrc/asrc_farrow.h

Add support for IPC4 in ASRC module.
Changed buffers allocation method. Each buffer is allocated separately instead of one big blok, exceeding the maximum block size for the memory allocation. This allows to use a ASRC module with more than 2 channels.

ASRC: add IPC4 support

---

tools/topology/topology1/CMakeLists.txt

Add CMake build definition for
sof-mt8195-mt6359-rt1019-rt5682-dts.tplg.

topology1: mt8195: Add topology with DTS

---

src/arch/xtensa/hal/CMakeLists.txt
src/arch/xtensa/hal/atomics.c

Add compare_exchange atomic for better support of std::atomic when using
c++.
This backports #5089  into adl-004-drop-stable

hal: Add compare_exchange atomics for xtensa [adl-004-drop-stable]

---

src/audio/mux/mux_generic.c

uint8_t iterator does not work for period size above 256 frames.
Using large buffers (>5ms @ 48kHz) without this patch results
in the copy being an infinite loop.
Cherry-pick #5060 into adl-004-drop-stable

mux: Change iterator type to uint32_t [adl-004-drop-stable]

---

src/audio/CMakeLists.txt
src/audio/Kconfig
src/audio/google_rtc_audio_processing.c
src/audio/google_rtc_audio_processing_mock.c
third_party/include/google_rtc_audio_processing.h
third_party/include/google_rtc_audio_processing_platform.h
tools/topology/topology1/m4/google_rtc_audio_processing.m4

This backports Google Initial AEC to latest tigerlake branch
Original PR: #5090

comp:google rtc audio processing for adl-004-drop-stable

---

src/audio/copier.c
src/drivers/intel/alh.c
src/ipc/ipc4/dai.c

The node id in copier config is built with group id
and codec id, we need to convert it to sof dai id.
Validated on windows. Now sdw playback can work on windows platform.

ipc4: enabling SDW on windows

---

src/audio/Kconfig
src/audio/pcm_converter/pcm_converter_generic.c

In nocodec ipc4 test we have a new format
conversion : 32 bits container 16 bits valid sample bit
to itself. Just copy the source buffer to sink buffer.

ipc4: add pcm conversion function for new format pattern

---

tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/cavs/cavs-nocodec.conf

Different platform uses different SSP MCLK frequency,
this patch applies different MCLK for different platform
for cavs-nocodec topology.
The MCLK frequencies are aligned with topology1.

topology2: use different SSP MCLK for different platforms

---

src/audio/google_hotword_detect.c
src/audio/smart_amp/smart_amp_maxim_dsm.c
src/schedule/ll_schedule.c

ll_schedule: unregister domain in free function with IRQ_ONLY_FLAG
ghd: update creation process
Above 2 patches are merged in main , we need them in adl004 branch.
smart amp: fix set param build warning
https://github.com/thesofproject/sof/pull/5283
This is a fix in dsm , above PR posted to main branch.

Adl004 backport patches

---

zephyr/wrapper.c

This reverts commit 079ce95b988384225d3f1dc2013811d4c41b3d82.
As explained in the comment that it modified, predicted in the #5159
discussion and reproduced in test #5290 /
https://github.com/thesofproject/sof/runs/4988844402, this commit broke
`CONFIG_TRACE=n`. Simple reproduction steps:
```
$ rm -rf zephyrproject/build-apl
$ echo 'CONFIG_TRACE=n' >> \
boards/xtensa/intel_adsp_cavs15/intel_adsp_cavs15_defconfig
$ sof/scripts/xtensa-build-zephyr.sh [ -p /path/to/zephyrproject ]  apl
fw abi main version:	3.20.1
fw abi dbg version:	5.3.0
warning: can't find section .static_log_entries in zephyr/zephyr.elf
error: section .static_log_entries can't be found
error: unable to write dictionaries, -22
```

Revert "zephyr: (cosmetic) make a needlessly global variable static"

---

src/audio/crossover/crossover.c
src/audio/eq_iir/iir.c
src/audio/mux/mux.c
src/audio/selector/selector.c
src/audio/smart_amp/smart_amp.c
src/audio/smart_amp/smart_amp_maxim_dsm.c
src/audio/tone.c
src/include/ipc/control.h
src/include/sof/common.h
src/samples/audio/smart_amp_test.c

2 commits, please see commit messages.
Prompted by #5283

Use typeof() to make ASSUME_ALIGNED() type safe

---

src/audio/CMakeLists.txt
src/include/sof/trace/trace.h
src/ipc/ipc-helper.c
src/platform/library/include/platform/lib/mailbox.h
src/platform/library/lib/alloc.c
src/platform/library/schedule/edf_schedule.c
src/platform/library/schedule/ll_schedule.c
src/platform/library/schedule/schedule.c
tools/fuzzer/fuzzer.h
tools/fuzzer/main.c
tools/fuzzer/topology.c
tools/testbench/CMakeLists.txt
tools/testbench/common_test.c
tools/testbench/file.c
tools/testbench/include/testbench/common_test.h
tools/testbench/include/testbench/file.h
tools/testbench/testbench.c
tools/testbench/topology.c
tools/tplg_parser/include/tplg_parser/topology.h
tools/tplg_parser/tplg_parser.c

This is rebased version of #4653 with commits 12 (testbench: cache: add support for initial testbench cache checker) and 13 (arch: host: Add host locking via pthread mutexes dropped). 
Commit 17 fix approach is changed because the first way broke pipeline HW parameters get from file DAI. In this version mimicking of DAI is improved to not segfault from missing init delay function access.

Tools: Testbench: Add multi-core

---

zephyr/wrapper.c

Add implementation of secondary core disable with a call
to SOF runtime-PM framework.

zephyr: implement arch_cpu_disable_core()

---

src/audio/codec_adapter/codec/cadence.c
src/audio/codec_adapter/codec/dts.c
src/audio/codec_adapter/codec/generic.c
src/audio/codec_adapter/codec/passthrough.c
src/audio/codec_adapter/codec/waves.c
src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/generic.h

This PR is Part 1 of the proposal to update then module_interface to add new API's and modify existing API's.
**The process() API will be modified in a follow up PR as it requires the codec_adapter to be modified to handle more than just 1 input/output buffer**
```
struct module_interface {
/**
* Module specific initialization procedure, called as part of
* codec_adapter component creation in .new()
*/
int (*init)(struct processing_module *mod);
/**
* Module specific prepare procedure, called as part of codec_adapter
* component preparation in .prepare()
*/
int (*prepare)(struct processing_module *mod);
/**
* Module specific processing procedure, called as part of codec_adapter
* component copy in .copy(). This procedure is responsible to consume
* samples provided by the codec_adapter …
```

Introducing the new 3rd Party Module API - Part 1

---

src/audio/copier.c
src/include/sof/audio/audio_stream.h

Corrected component id printed in tr_err.
Added some important comments.
Added asserts witch helped me debug the code.

ipc4: Correction of component id printed in tr_err

---

src/audio/codec_adapter/codec_adapter.c

Fix the deep_buffer_bytes calculation to use the out_buff_size instead
of in_buff_size. Remove the default periods for the local buffer as the
calculation should work out to 2 when period bytes and out_buff_size are
equal.

codec_adapter: fix deep_buffer_bytes calculation

---

src/platform/intel/cavs/lib/pm_runtime.c
zephyr/wrapper.c

Currently both Zephyr architecture hooks in wrapper.c and
SOF runtime-PM for DSP cores, have code to power up and down
the cores.
Some of this is necessary overlap until full replacement of
SOF runtime-PM is available. But for secondary core power up,
we can already clean up the flow and hook the Zephyr core
enable code to runtime-PM driver directly. This ensure if
other drivers (like the cAVS clock driver) use runtime-PM
framework to power up a secondary core, this will now also
go through Zephyr as it should be.
Currently there is only on runtime-PM driver in the tree,
so changes are limited to the the cAVS runtime-PM driver.

zephyr: always use Zephyr interface to power up secondary cores

---

src/include/sof/coherent.h

This patch adds documentation to the coherent API header and cleans up several potentially harmful operations. Specifically, it isn't a good idea to modify memory via uncached addresses and then write back caches, because the latter can overwrite uncached writes. It works because there is no data in cache at that point, which also makes that call redundant. Similarly, we are sure not to have any data in caches when obtaining access to the memory, because otherwise our spinlock-acquisition operation could be overwritten by a speculative write back.

coherent: tighten up the API

---

src/audio/volume/volume_generic.c
src/include/sof/audio/volume.h

This patch replaces the non efficient per sample fragment functions
with audio_stream_bytes_without_wrap() aided block processing.
The volume component MCPS is optimized from 24 MCPS to 8 MCPS. The
saving is similar in all s16, s24, s32 volume copy() functions.
The test was done in TGL-H platform with HiFi3 code version disabled
and with xt-xcc compiler.

Audio: Volume: Replace read/write frag buffers in generic C version

---

zephyr/wrapper.c

To align with Zephyr smp.c:smp_init_top(), add the missing call to
smp_timer_init() in secondary_init() of the SOF wrapper. Also
add inline documentation why we are open-coding the function on
SOF side.

zephyr: add missing call to smp_timer_init to secondary core init

---

src/arch/xtensa/xtos/CMakeLists.txt
src/arch/xtensa/xtos/stub.c

In order to ease porting algorithm to SOF, it is convenient to have
stubs for some operating system function.
Those stubs are not meant to be called.
This backports PR #5092  into adl-004-drop-stable

xtos: Add stub for some missing OS function [adl-004-drop-stable]

---

tools/testbench/testbench.c

This patch changes the help function. The print is improved and
executable behavior with option -h is improved. Previously the
help test was printed twice.

Tools: Testbench: Clean up help text and missing help items

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-imx8mp-wm8904.m4

Tested to work on Variscite Symphony-Board v1.3 with VAR-SOM-MX8M-PLUS
Sample device tree: https://gitlab.com/autogramma_multimedia_a/vendor/variscite/kernel_imx/-/commit/0e922e526bafe919fac9e89cf949e85c7b36b972

topology1: Add sample topology for i.MX8MP boards with wm8904 codec

---

zephyr/README

Replaced with
https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html

[SKIP CI] zephyr: replace obsolete README section with link to sof-docs

---

src/drivers/mediatek/mt8186/interrupt.c

Fix the build error by using the new SOF spinlock API.

drivers: mediatek: interrupt: fix build error of spinlock API

---

tools/topology/topology2/cavs/cavs-gain-hda.conf

Add 32-bit support in PCM capabilities.

topology2: cavs-gain-hda: Add 32-bit support

---

src/drivers/amd/renoir/ipc.c
src/platform/amd/renoir/include/platform/chip_offset_byte.h
src/platform/amd/renoir/platform.c

Add hardware semaphore lock before accessing trigger
bits to acheive proper sychronization between host and
DSP during IPC communication.
Note: Same hardware lock is implemented in amd host driver.
Signed-off-by: balapati <balakishore.pati@amd.com>

amd: renoir: Add lock for synchronization b/w host and DSP

---

src/audio/component.c

After moving component to a new memory location, not only source and
sink lists need to re-link but also the buffers which already been
connected to this component.

comp: re-link buffers in make_shared

---

tools/test/audio/tdfb_direction_test.m
tools/test/topology/test-capture.m4
tools/test/topology/test-playback.m4
tools/test/topology/test_pipeline_filters.m4
tools/test/topology/tplg-build.sh

This patch adds Matlab script tdfb_direction_test.m. The test
simulates acoustical microphone array capture with 360 degrees
rotated noise source. The test topologies build adds an array
identifier to component name in topology file name. That
allows the scripts to simulate with several arrays. Now a
basic 2 mic array (no array suffix, just tdfb), 4 mic line,
and 8 mic circular are tested. Test pass/fail is so far only
visual check from plot.
The existing tdfb_test.c is extended to perform test with the
three test array configurations.

Tools: Test: Audio: Add sound direction test for TDFB

---

src/platform/library/schedule/ll_schedule.c
tools/testbench/testbench.c

Add option to override how a core id, specified in SOF topology, is
mapped to host core. This allows to map a multithreaded pipeline
execution to specific range of host CPUs.
Implement the option via environment variable "SOF_HOST_CORE0", which is
understood by the CONFIG_LIBRARY implementation of ll-scheduler.
Document the usage to testbench help. mapping of DSP core ids specified
SOF_HOST_CORE

testbench: add option to override CPU core mapping

---

src/drivers/intel/hda/hda-dma.c
src/include/sof/lib/dma.h
src/ipc/dma-copy.c
src/probe/probe.c
src/trace/dma-trace.c

The first commit should be the the only one needed to fix https://github.com/thesofproject/sof/issues/5120 .
The second commit should make sure the same problem does not bite us again. The third commit is pretty much optional, but I think the fix is correct and it is also cleaning up the code a bit.

dma-trace: Align dma trace buffer correctly, fixed Zephyr dtrace issue

---

src/audio/eq_fir/eq_fir_generic.c
src/include/sof/audio/eq_fir/eq_fir.h

This patch replaces the audio stream read/write frag based
access to source and sink by block processing based on
audio_stream_bytes_without_wrap() bytes count.

Audio: EQFIR: Optimize source and sink buffers use in generic C version

---

src/probe/probe.c

Fixes commit 443b21de4b3f ("dma-trace: Fix potential race issue by using
blocking DMA copy")
Chrome build can pass now

probe: update dma copy method to dma_copy_to_host()

---

src/platform/amd/renoir/lib/clk.c

Fix ACP clocks to default clock during boot up time.
Signed-off-by: balapati <balakishore.pati@amd.com>

amd: renoir: clk: Fix ACP clock to default clock

---

tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/cavs/cavs-mixin-mixout-hda.conf
tools/topology/topology2/cavs/cavs-passthrough-hda.conf
tools/topology/topology2/cavs/cavs-passthrough-hdmi.conf
tools/topology/topology2/include/components/gain.conf
tools/topology/topology2/include/pipelines/cavs/gain-capture.conf
tools/topology/topology2/include/pipelines/cavs/gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixin-capture.conf
tools/topology/topology2/include/pipelines/cavs/mixin-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-capture.conf
tools/topology/topology2/include/pipelines/cavs/mixout-playback.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-be.conf

The main change is to split up pipelines into FE and BE parts and add a deep buffer PCM to the mixin-mixout topology.
The mixin-mixout tplg looks like this:

Change CAVS passthrough and mixin/mixout topologies

---

src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

Regularly used flow when removing pipeline:
1. Set ppl state PAUSED,
2. Unbinding modules,
2. Set ppl state RESET,
3. Deleting Pipeline
Changes made:
- allowing to unbind modules under the same pipeline. It should be ignored under ipc4, but not cause an error.
- changing modules state during pipe reset, without this FW reports error at pipeline deletion.

IPC4: fix for pipaline cleanup

---

tools/topology/development/sof-tgl-nocodec-ci.m4
tools/topology/m4/bytecontrol.m4
tools/topology/m4/utils.m4
tools/topology/sof-apl-demux-pcm512x.m4
tools/topology/sof-cml-demux-rt5682.m4
tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4
tools/topology/sof-tgl-max98357a-rt5682.m4

A change introduces in https://github.com/alsa-project/alsa-lib/issues/187 breaks topology on tgl-013-drop-stable.
This PR backports the relavant changes from main.

topology: Fix topologies to accomodate Alsa lib changes.

---

tools/topology/topology2/include/pipelines/cavs/gain-capture.conf
tools/topology/topology2/include/pipelines/cavs/gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixin-capture.conf
tools/topology/topology2/include/pipelines/cavs/mixin-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-capture.conf
tools/topology/topology2/include/pipelines/cavs/mixout-gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-playback.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-capture.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-playback.conf

Set all pipelines to be dynamic by default.

topology2: cavs: all pipelines should be dynamic by default

---

src/audio/asrc/asrc.c

Don't change sink rate if value from IPC is 0 (auto detect)
This is fix for issue [5294](https://github.com/thesofproject/sof/issues/5294).
Signed-off-by: Adrian Warecki <adrianx.warecki@intel.com>

asrc: Fixed sink rate selection

---

tools/topology/topology1/sof/pipe-codec-adapter-capture.m4
tools/topology/topology1/sof/pipe-codec-adapter-playback.m4
tools/topology/topology1/sof/pipe-waves-codec-playback.m4

There's only one config for the codec adapter component now. So drop the
redundant kcontrol and keep only one for sending the config data.

topology: remove the redundant kcontrol for codec adapter comp

---

tools/topology/topology1/sof-glk-es8336.m4

Rookie mistake, the clock can't possibly be 19.2 MHz
Reported-by: Nikolai Kostrigin <nickel@altlinux.org>

topology1: sof-cml-es8336: use correct 24MHz MCLK

---

scripts/xtensa-build-zephyr.py
src/include/sof/compiler_attributes.h
tools/logger/CMakeLists.txt
tools/logger/misc.c

Four commits:
1. Fixed warning in sof-logger issued from compilers newer than GCC 9.1 "char-subscripts" by adding (int) cast to isspace functions.
2. To enable Windows build, added additional include path to sof logger so required system standard POSIX headers could be found in MSYS2 environment. Unfortunately there are macros redefinitions between standard GCC headers and src\include\sof\compiler_attributes.h. Could not find the way around it, also GCC does not provide any policy to silence this particular warning, so had add #ifndef guards in the compiler_attributes.h header.
3. Added \#ifndef guards to macros to avoid redefinitions with GCC standard headers on MSYS2.
4. Added xtensa-build-zephyr.py script that allows to build SOF with Zephyr on both Windows and Linux.
Signed-off-by: …

Resurrect windows build - rewrite xtensa-build-zephyr.sh to Python

---

src/audio/src/src_hifi4.c

SRC_HIFI4 compilation is not in a scope of sof upstream compilation check. Compilation fix is needed.

SRC: compilation fix for src_hifi4.c. This fixes dcb9aeb308a9

---

src/include/sof/trace/dma-trace.h
src/ipc/ipc3/handler.c
src/trace/dma-trace.c

Hi,
This PR is replacing #4879.
Since last time I have noticed another path for a memory leak which was a hard one to crack:
Within dma_trace_start() when CONFIG_DMA_GW is set we were allocating a dma_sg (to SOF_MEM_ZONE_SYS) and we would do that for every start. The config is only used in that function to configure the DMA channel, but the dma_sg can not be freed up as it is allocated to SOF_MEM_ZONE_SYS. Other zone allocation failed on my tgl-h laptop.
The solution is to make dmatb and this dma_sg persistent from the point they are allocated.
This comes with a bonus that we can still collect dtrace logs to SOF firmware for some extent (if the would be dtrace client is removed we would still have some memory of the events).
The other change compared to #4879 is that I don't reset the …

dma-trace: Full support for re-configuration and make dmatb persistent from the time it is allocated

---

scripts/xtensa-build-zephyr.py

Single commit, fixes [Rewritten xtensa-build-zephyr.sh to python](https://github.com/thesofproject/sof/pull/5299/commits/5897bbeec94de06521a6df2bf4a3a65de872116e) commit from [PR5299](https://github.com/thesofproject/sof/pull/5299).
Existing xtensa-build-zephyr.py failed to copy sof logger
executable to staging directory on Windows OS due to missing '.exe' file extension.
This fixes the script.
Quick-tested sof-logger.exe on Windows with help of @marc-hb .
Most features are not working correctly since the tool tries to resolve /sys/kernel/debug/sof directory
which obviously do not exist on Windows. Command `sof-logger.exe -d some.ldc` works dumping ldc file information to stdout.

Fix xtensa-build-zephyr.py on windows

---

src/audio/google_rtc_audio_processing.c
src/audio/smart_amp/smart_amp.c

It appears in the conversion of the IPC API the copy in the smart amp
code was missed and as a result the component loses its ID which results
in the graph being broken and a crash on trigger.

smart_amp: copy ipc config

---

.github/workflows/pull-request.yml

We don't want one failure to cancel other platforms.
See unwanted cancellation example in https://github.com/thesofproject/sof/pull/5386 /
https://github.com/thesofproject/sof/runs/5241344411

[SKIP CI] .github: add fail-fast: false to gcc builds and qemu boot tests

---

src/audio/copier.c
src/audio/dai.c
src/audio/pipeline/pipeline-graph.c
src/drivers/dw/dma.c
src/include/sof/audio/pipeline.h
src/include/sof/lib/dai.h
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c
src/platform/intel/cavs/include/cavs/drivers/dw-dma.h

The progress bar of windows audio player is out of order after pause-resume operation. It is caused by stream position calculation. audio driver uses stream_start  | end offset to build a stream position which are missed in SOF FW.
This patch adds support of stream_start  | end offset
Validated on windows

ipc4: fix progress bar issue with windows audio player

---

src/audio/codec_adapter/codec/generic.c
src/include/sof/audio/codec_adapter/codec/generic.h
zephyr/CMakeLists.txt
zephyr/wrapper.c

This is the first part on preparing codec adapter to work with zephyr.
This does:
- fix some build warnings / errors (given the fact that zephyr uses prink which has stronger params checks)
- fix DECLARE_CODEC_ADAPTER macro. this was generic same symbols names for init functions().
- add codec adapter components to zephyr/wrapper.c

Prepare codec adapter to work with zephyr (1)

---

tools/test/audio/process_test.m
tools/tune/eq/eq_blob_plot.m
tools/tune/eq/eq_fir_blob_decode.m
tools/tune/eq/eq_iir_blob_decode.m

The test scripts missed test component keyword change from e.g.
eqiir to eq-iir. Due to this the process_test() failed for IIR and
FIR for gain and frequency response due to wrong result expect.
The expected result is retrieved with the blob decode function. It
can be also used manually to check the filters defined in the
blob. The help texts in the decode functions needed fix. Also some
usage examples were added.

Tools: Test, Tune: Improve Matlab scripts for EQ testing

---

src/drivers/intel/ssp/ssp.c

The checks added in commit fc73578be774 ("drivers: Intel: SSP: ignore
config when SSP is already configured") also filter out cases where the
SSP parameters actually are modified in prepare state. This will happen
e.g. with a topology that has multiple configs for SSP and uses static
topology loading.
Modify the checks such that if the config is modified, proceed
with the hardware programming unless state actually is ACTIVE.
BugLink: https://github.com/thesofproject/sof/issues/5375

drivers: Intel: SSP: fix update of DAI config in prepared state

---

scripts/xtensa-build-zephyr.py

Two commits, best reviewed separately
1. pure string reformatting, zero change
2. the real thing:
Make it possible to invoke -C multiple times which is required to
support whitespace as in:
```
-C=--warn-uninitialized  -C '-DEXTRA_FLAGS=-Werror -g0'
```
Restores feature parity with the shell script.
Note this is not backward compatible (but the whole script was merged only this week)

xtensa-build-zephyr.py: fix -C option so it can support whitespace

---

src/trace/dma-trace.c

The dictionary does not support character strings.
Fixes commit c11562b00a29 ("dma-trace: Align DMA buffer correctly to fix
dma tracing issues")
Take the opportunity to log more pointers (which _are_ supported).
Fixes the following error message:
```
TIMESTAMP         (us)              DELTA  C# COMPONENT          LOCATION                      CONTENT
error: String printing is not supported
[           2.604167] (           0.000000) c0 dma-trace             src/trace/dma-trace.c:266  ERROR <String @ 0xbe035e60> failed: no DMAC
```

dma-trace.c: fix unsupported mtrace_printf("%s", ...) string specifier

---

src/audio/eq_iir/eq_iir.c
src/include/sof/audio/eq_iir/eq_iir.h

This patch optimizes the remaining EQ functions eq_iir_s32_s16_pass()
and eq_iir_s32_s24_pass() to not use audio stream read/write
frag functions.

Audio: EQIIR: Optimize pass-through mode read/write frags

---

src/include/sof/trace/dma-trace.h
src/trace/dma-trace.c

Removed redundant host notification about a log position from function dma_trace_get_avail_data. Function trace_work already send it.

dma-trace: Remove duplicated notify message

---

src/drivers/amd/renoir/ipc.c
src/drivers/imx/ipc.c
src/drivers/intel/baytrail/ipc.c
src/drivers/intel/cavs/ipc.c
src/drivers/intel/cavs/sue-ipc.c
src/drivers/intel/haswell/ipc.c
src/drivers/mediatek/mt8186/ipc.c
src/drivers/mediatek/mt8195/ipc.c
src/include/sof/ipc/common.h
src/include/sof/ipc/driver.h
src/ipc/ipc-common.c
src/ipc/ipc3/handler.c
src/ipc/ipc4/handler.c
src/platform/library/include/platform/platform.h
test/cmocka/src/common_mocks.c

While activating the dma-trace mechanism for ipc4, I discovered a problem in the ipc message send function. 
Log position notification are allocated once, and the same message is send multiple times. Sending function in ipc4 decrease data length, which leads to the corruption of subsequent notifications, and firmware crash on overflow. Additionally, the function frees the ipc response buffer without checking if the sent message is the ipc response.
To protect us from similar problems in the future, I added the const specifier to protect the message contents passed to
ipc_platform_send_msg and ipc_prepare_to_send functions. The deletion of the message from the list has been moved to ipc_send_queued_msg function.

ipc: Don't modify IPC message content in sending functions. 

---

src/audio/google_rtc_audio_processing.c
src/audio/smart_amp/smart_amp.c

This backports PR #5382 to adl-004-drop-stable
Original description:
```
It appears in the conversion of the IPC API the copy in the smart amp
code was missed and as a result the component loses its ID which results
in the graph being broken and a crash on trigger. 
```

Backport "copy ipc config" to adl-004-drop-stable

---

src/drivers/intel/ssp/ssp.c

The checks added in commit fc73578be774 ("drivers: Intel: SSP: ignore
config when SSP is already configured") also filter out cases where the
SSP parameters actually are modified in prepare state. This will happen
e.g. with a topology that has multiple configs for SSP and uses static
topology loading.
Modify the checks such that reconfiguration is done if:
- the config is actually modified,
- early MCLK/BCLK is not running.
BugLink: https://github.com/thesofproject/sof/issues/5375
(cherry picked from commit bcc789f981c908a3f1f68247ba4ff71ef6e7c227)

[Intel ADL-003 backport] drivers: Intel: SSP: fix update of DAI config in prepared state

---

.github/workflows/zephyr.yml
zephyr/docker-build.sh

Switch Github Actions away from older shell script.

[SKIP CI] .github: switch to new xtensa-build-zephyr.py

---

tools/topology/topology2/include/pipelines/cavs/gain-capture.conf
tools/topology/topology2/include/pipelines/cavs/gain-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixin-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-capture.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-capture.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-playback.conf

We declare that S24_LE is supported by a HDA PCM, but 24 bit audio
format is not included in the available audio format list.
Fixes: thesofproject/linux#3449 

topology2: HDA: add 24 bit audio format

---

src/include/ipc4/base_fw.h
src/include/ipc4/module.h
src/ipc/ipc4/handler.c

Complementing the implementation of SetDX ipc message handling:
- adding support and validation of message payload,
- enabling/disabling cores according to the DX state mask,
- unblocking the path for primary core power down.

ipc4: SetDx

---

src/trace/dma-trace.c

This fixes the banner which was recently added by SOF commit
a053e04d7ee1 ("trace: add Zephyr git version to the initial FW ABI
banner")
```
SHM: FW ABI ... tags SOF:v1.2.3 zephyr:zephyr-v3.0.0-346-g1470228eb10
```
... but was broken very soon after by Zephyr commit [91709778a487](https://github.com/zephyrproject-rtos/zephyr/commits/91709778a487) ("cmake:
version.h generation performed at build time")
```
SHM: FW ABI ... tags SOF:v1.2.3 zephyr:BUILD_VERSION
```

Restore Zephyr version in banner, fix 'zephyr:BUILD_VERSION'

---

tools/topology/topology1/sof-adl-nau8825.m4
tools/topology/topology1/sof-apl-demux-pcm512x.m4
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof/pipe-echo-ref-dai-capture.m4

Two commits:
- Fix existing macro call to W_DAI_IN, which requires 7 parameters , but only 6 are given.
- Move virtual dai on echo ref pipeline to another pipeline, to avoid it's bad impact on pipeline walking in the kernel, which make echo reference cannot work. 
Special thanks to @ranj063 
Fixes: https://github.com/thesofproject/sof/issues/5395

topology: fix echo reference topologies.

---

src/drivers/imx/esai.c
src/drivers/imx/sai.c

With dynamic pipeline feature, pipelines are destroyed
when SOF device enters suspend and .remove callback is called in order
to free memory.
SAI/ESAI are missing this callback and the FW crashes. Fix this by
adding .remove callback.

drivers: imx: esai/sai: Add .remove callback

---

src/audio/codec_adapter/codec/dts.c
src/audio/codec_adapter/codec/waves.c
src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/generic.h

In preparation for modifying the process API to pass pointers to the input/output buffers and their counts, make some prelimiary changes to avoid using the ca_source/ca_sink pointers in teh codec implementations. Also, modify the copy functions to be reusable for multiple buffers by passing the buffer pointers and the bytes available.

Preparation for modifying the module process API - Part 1

---

platforms/tgl/tgl_ipc4_overlay.conf
scripts/xtensa-build-zephyr.py

Add ipc4 build support for tgl with OVERLAY_CONFIG.
if any other IPC4 config should be added, please comment.
similar implementation in xtensa-build-zephyr.sh will not be done, because it is going to be deprecated, use xtensa-build-zephyr.py instead.

xtensa-build-zephyr: add ipc4 build support for tgl

---

src/audio/buffer.c

mod->local_buff is only allocated when the module is prepared.
With dynamic pipelines we could have the situation where the pipeline
is created then SOF device enters suspend and pipeline is destroyed.
Thus we try to free unallocated mod->local_buf. Fix this by only
freeing local_buff if it is allocated.

codec_adapter: Fix crash in codec_adapter_free

---

src/ipc/ipc4/handler.c

FW should not enter D0 when there are still active pipelines.
Additionally, this pull request fixes infinity loop case in ipc SetDx handler.

ipc4: setdx: prevent d0 when ppl are active

---

src/ipc/ipc4/handler.c

Fix a regression issue on windows. Need to invalidate dcache
for host message or FW will get garbage data.

ipc4: invalidate dcache for host mailbox

---

src/trace/dma-trace.c

This reverts commit 58ce6e68608fdbec49a9835dfb8b76e0fa848187.
This commit has caused the DMA trace to be frequently empty on a number
of ADL and TGL in daily runs for two days in a row (test runs 10429 and
10459).
The DMA trace could be completely empty in the past but that was on
different platforms and a very long time ago, this had been fixed in
bug #4333 and had not happened for many months.
The _only_ commit difference between the last successful test
run (10402) and the first failing one (10459) is this commit.

Revert "dma-trace: Preserve logs while dtrace is disabled"

---

zephyr/wrapper.c

z_wrapper_cpu_enable_secondary_core() may be called
repeatedly on a core that is already running. Add a check
to ensure we do not try to restart a core that is already
running.
Also add a check for ready_flag as done in upstream Zephyr
kernel/smp.c to ensure z_wrapper_cpu_enable_secondary_core()
does not return until the target core has finished its
startup and arch_cpu_active() returns true.
BugLink: https://github.com/thesofproject/sof/issues/5446

zephyr: fix race in secondary core power-up

---

scripts/xtensa-build-zephyr.py
scripts/xtensa-build-zephyr.sh

Zephyr recently added support for separate configs for 2-core and 4-core
variants of cAVS2.5. Use the new "tgph" configuration for when building
SOF for TigerLake-H variant.
BugLink: https://github.com/thesofproject/sof/issues/5018

xtensa-build-zephyr: use separate Zephyr config for TGPH builds

---

zephyr/wrapper.c

Fix issue of ipc4 pipeline initialization with zephyr enabled.
Need to initialize these two components.

ipc4: init gain & mixin components for zephyr

---

src/audio/google_rtc_audio_processing.c

I ommited to change the field name on the dev object.
On this branch it should be named comp instead of ipc_config.
This change corrects this mistake.

google_aec: Fix wrong member call when copying IPC

---

src/audio/host.c
src/include/ipc/stream.h
src/include/kernel/abi.h
src/ipc/ipc3/handler.c

Hi,
I modify host position in every period not only larger than host period bytes. Host position will be updated more precisely. When linux side use pcm pointer callback to get host position data then the position will be updated based on pipeline period.
I also reset host position value as zero before replay ipc_stream_pcm_params to avoid unexpected value. I saw this invalid value when I run alsa conformance test and I implement PCM pointer function to get host position value but see invalid value at the beginning. After I provide this code, the invalid value will be replaced with zero.  Please help to review this PR and any feedback are welcome. Thanks.

Update host position value in every period to improve precision

---

tools/topology/topology1/sof-glk-es8336.m4

It's not clear why the initial contribution used mclk ID1, mclk ID0 is
used by 99% of devices - and a manual inspection of NHLT supports that
claim. We will have to deal with the MCLK ID1 case with quirks.

topology1: sof-glk-es8336: use mclk ID0

---

tools/topology/topology1/sof-mt8195-mt6359-rt1019-rt5682.m4

Hi,
This PR changes the capture pipeline period to 2ms.
When host is more heavy loading(e.g. camera recoding case),
the size of dai buffer is 4ms and not enough. Increase 2ms
period capture pipeline to buffer more data to avoid overrun.
Please help to review it. Thanks

topology1: mt8195: support 2ms pipeline capture period

---

src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/generic.h

Add 2 fields for input_buffers and output_buffers to struct
processing_module. Move the memory allocation for input/output
buffers for the module to the prepare op from the copy op.

codec_adapter: Move input/output buffer allocation to prepare

---

scripts/xtensa-build-all.sh

Private key file passed by user is stored in PRIVATE_KEY_OPTION variable. When building for many platforms, if user not pass path to key file, default value will be set in PRIVATE_KEY_OPTION. During building second platform, default key from the first one are treated as key passed by user and default key will not be applied.
I introduced the new variable PLATFORM_PRIVATE_KEY, which holds default signing key for current platform. If user passed own key, this value is later set in this variable. The xtensa-build-zephyr script works the same way. Changed DEFAULT_PLATFORMS and moved TGL platform to the middle of the list to make sure any future leakage like this one is detected immediately.

xtensa-build-all.sh: Default private key leaking between platforms

---

tools/topology/topology1/platform/intel/intel-generic-dmic-kwd.m4
tools/topology/topology1/platform/intel/intel-generic-dmic.m4
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof-tgl-max98373-rt5682.m4

This should make sure to surface pipeline period and microphone
processing in the top topology file so incoherence are easier to spot
and correct.
I compared topology1/production/*.conf outputs prior and after the
change: except some new line and comment change introduced by the
simplification, there are no changes.

topology1: Simplify the DMICPROC selection

---

src/platform/amd/renoir/lib/dma.c
src/platform/baytrail/lib/dma.c
src/platform/haswell/lib/dma.c
src/platform/imx8/lib/dma.c
src/platform/imx8m/lib/dma.c
src/platform/imx8ulp/lib/dma.c
src/platform/intel/cavs/lib/dma.c
src/platform/mt8186/lib/dma.c
src/platform/mt8195/lib/dma.c

Each platform defines a list of DMA controllers and related objects in their lib/dma.c files. All of them are needlessly defined as global. Make them all static.

dma: make DMA platform data static

---

scripts/cmake/version.cmake
zephyr/CMakeLists.txt

5 commits. The main one:
[version.cmake: make XTOS and Zephyr .ldc file different from each other](https://github.com/thesofproject/sof/commit/dced4400f9e8e062e6de97d59b0af56c04e625c8) 
This is especially important considering some sof-bin releases are now
"hybrid": with a mix of XTOS and Zephyr.

version.cmake: make XTOS and Zephyr .ldc file different from each other + other cleanups.

---

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4

Due to m4 peculiarities it is require to escape the content of an
ifdef. I forgot to add those escaping for around the `SPK_MIC_PERIOD_US`
defition leading to erroneous value if GOOGLE_RTC_AUDIO_PROCESSING was
defined.

topology1: Fix m4 issue in conditional definition

---

src/audio/volume/volume_hifi3.c

This patch replaces the audio stream read/write frag based
access to source and sink by block processing based on
audio_stream_bytes_without_wrap() bytes count.
Test all platform first.

Audio: volume: Optimize source and sink buffers usage

---

tools/topology/topology1/development/sof-cml-src-rt5682.m4

The string parser in alsa-lib is sensitive to these now. So fix it.
(cherry picked from commit db041556ce48b0535d5fa4d77d19d166e2938c05)

topology1: sof-cml-src-rt5682: remove extra space after values

---

tools/test/audio/test_utils/test_run.m

Remove the extra argument for fprintf(). For some reason there was
no harm seen but this should trigger an error when run in Octave or
Matlab.

Tools: Test: Fix mistake in script test_run.m

---

scripts/xtensa-build-all.sh

Recent combination of tgl and tgl-h building resulted in use of an invalid defconfig file for tgl-h platform. This PR reverts that change.
Fixes #5493

xtensa-build-all.sh: Use appropriate defconfig for tgl-h platform

---

zephyr/CMakeLists.txt

We add support for linking with Cadence AAC/MP3 libs.
Cadence lib MP3 support is enabled via CONFIG_CADENCE_CODEC_MP3_DEC config
symbol. Path to library file needs to be set via CONFIG_CADENCE_CODEC_MP3_DEC_LIB
Similar for AAC.

zephyr/cmake: Add support for linking with cadence libs

---

scripts/xtensa-build-zephyr.py

xtensa-build-zephyr.py: small de-duplication

---

tools/topology/topology2/cavs/cavs-sdw.conf

Use two separated pipelines for BE and FE.

topology2: add be pipeline for sdw

---

src/drivers/amd/renoir/acp_dmic_dai.c
src/drivers/amd/renoir/acp_dmic_dma.c
src/include/sof/drivers/acp_dai_dma.h
tools/topology/topology1/sof-acp-renoir.m4
tools/topology/topology1/sof-rn-rt5682-max98360.m4
tools/topology/topology1/sof-rn-rt5682-rt1019.m4

Set default samplerate for DMIC to 48000Hz for
amd platforms.

topology1: Set Dmic samplerate to 48000Hz

---

scripts/xtensa-build-zephyr.py

git submodule update is a potentially destructive operation. It won't affect automation but it would really hurt developers debugging some rimage-related issue in 2.1

backport to stable-2.1: removal of "git submodule update" from xtensa-build-zephyr.py

---

scripts/xtensa-build-zephyr.py
scripts/xtensa-build-zephyr.sh

Depends-on: https://github.com/zephyrproject-rtos/zephyr/pull/43611
Keeping as draft until the Zephyr PR is merged.
Use intel_adsp_cavs20_jsl Zephyr board when building for
Intel Jasper Lake.
BugLink: https://github.com/thesofproject/sof/issues/4539

xtensa-build-all: add a separate target for JSL

---

scripts/xtensa-build-zephyr.sh

In scripts/xtensa-build-zephyr.sh line 199:
if test $platform = tgl-h ; then
^-------^ SC2086: Double quote to prevent globbing
and word splitting.

xtensa-build-zephyr.sh: fix shellsheck warning

---

scripts/xtensa-build-all.sh

Recent combination of tgl and tgl-h building resulted in use of an invalid
defconfig file for tgl-h platform. This commit reverts that change.
Fixes: f1e6e1fdd3b7ede771d1babd4106301639015091
Signed-off-by: Adrian Warecki <adrianx.warecki@intel.com>
(cherry picked from commit b9d971920e3032c8dbbe87483349df1e5155da2c)

stable-2.1: xtensa-build-all.sh: Use appropriate defconfig for tgl-h platform

---

scripts/xtensa-build-zephyr.py

Duplicating all parameters of subprocess.run() is not just tedious and
error-prone, it makes the script compatible only with a range of
specific Python versions.

xtensa-build-zephyr.py: un-hardcode execute_command() wrapper

---

src/audio/volume/volume.c

rballoc() is used for buffer allocations, no need to use it for volume internal control structures.

volume: use rmalloc() for an internal allocation

---

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4

Due to m4 peculiarities it is require to escape the content of an
ifdef. I forgot to add those escaping for around the `SPK_MIC_PERIOD_US`
definition leading to erroneous value if GOOGLE_RTC_AUDIO_PROCESSING was
defined.
(cherry picked from commit 980a5b25b3d97654e2583a12fcc165b47f3a717f)
This backports #5466 to adl-004-drop-stable

topology1: Fix m4 issue in conditional definition [adl-004-drop-stable]

---

tools/topology/topology1/platform/intel/intel-generic-dmic-kwd.m4
tools/topology/topology1/platform/intel/intel-generic-dmic.m4
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof-tgl-max98373-rt5682.m4

This should make sure to surface pipeline period and microphone
processing in the top topology file so incoherence are easier to spot
and correct.
I compared topology1/production/*.conf outputs prior and after the
change: except some new line and comment change introduced by the
simplification, there are no changes.
(cherry picked from commit 21a1ee1d167bfc7df6646cd571df4387d7668d05)
This backports #5468  to adl-004-drop-stable

topology1: Simplify the DMICPROC selection [adl-004-drop-stable]

---

src/drivers/mediatek/mt8195/afe-drv.c

This patch defines fs as signed integer in afe_irq_config to fix cppcheck warning which is discussed in https://github.com/thesofproject/sof/issues/4816
Please help to review it. Thanks.

mediatek: mt8195: afe-drv: fix fs cppcheck warning

---

src/ipc/ipc4/handler.c

This reverts commit 819c023d236ada6adbb8bc1610466e754c15f2ff.
Fix a regression issue on windows.
Component is set to reset status in pipeline_reset, so no
need to propagate reset status to each component.
Discussed with @tmleman  and fixed it. https://github.com/thesofproject/sof/pull/5342#issuecomment-1063813209

ipc4: revert "ipc4: fix pipeline reset"

---

src/audio/google_rtc_audio_processing.c
src/audio/google_rtc_audio_processing_mock.c

To provide echo cancelling effect while a stereo signal is played out,
the RTC Audio processing component required to have both left and right
channel as reference.
This CL ensure this is the case.

google-rtc-audio: Make AEC reference stereo

---

src/audio/google_rtc_audio_processing.c
src/audio/google_rtc_audio_processing_mock.c

To provide echo cancelling effect while a stereo signal is played out,
the RTC Audio processing component required to have both left and right
channel as reference.
This CL ensure this is the case.
Backport of #5500 to adl-004-drop-stable
(cherry picked from commit d792b0602dcfdd83d8adc1bced650586b8329aa6)

google-rtc-audio: Make AEC reference stereo [adl-004-drop-stable]

---

src/schedule/zephyr_ll.c

When the ll-scheduler is initialised and its private data is allocated, all fields of that data have to be initialised. Add a missing n_tasks initialisation.

zephyr: ll-schedule: initialise n_tasks

---

src/audio/codec_adapter/codec/cadence.c
src/audio/codec_adapter/codec/dts.c
src/audio/codec_adapter/codec/generic.c
src/audio/codec_adapter/codec/passthrough.c
src/audio/codec_adapter/codec/waves.c
src/audio/codec_adapter/codec_adapter.c

Use the passed input buffers and move the initialization call within the first process callback for each codec.

Codec Adapter: Use the passed input buffers

---

scripts/xtensa-build-zephyr.py
scripts/xtensa-build-zephyr.sh

Use intel_adsp_cavs20_jsl Zephyr board when building for
Intel Jasper Lake.
BugLink: https://github.com/thesofproject/sof/issues/4539
(cherry picked from commit 6d0ecc37cc282a6c9df991168931697ba2213138)

[SOF-2.1 BACKPORT] xtensa-build-all: add a separate target for JSL

---

src/ipc/ipc4/handler.c

The number of retries is too small to successfully handle some
compound IPC messages (in particular setting pipeline state to running
in case of multi-core distributed pipeline).
Signed-off-by: Rafal Redzimski <rafal.f.redzimski@intel.com>

ipc4: fix the compound ipc wait timeout

---

src/audio/pipeline/pipeline-params.c

pipeline_comp_hw_params does 2 things, it fetches the hw_params from the
DAI and writes those parameters to buffers. The issue here is that we
walk from host to DAI, so any buffer we see along the way gets set with
uninitialized hw_params as we don't get the params till the end of the
walk. Typically this is not an issue in most pipelines that are linear
as the following call to pipeline_comp_params will overwrite any bad
values in the buffer params. Not good practice but not harmful. The
problem arises when components such as the demux or SRC which pass flags
into comp_verify_params receive these bad values. There are edge cases
as a result where the values are not cleared and the buffers end up with
bad data. The result is usually an xrun, in the case of identifying this
bug, the …

pipeline: params: don't use uninitialized hw_params

---

src/ipc/ipc4/dai.c

Fix FW error when changing progress bar in windows auido player.
For this case, pipeline is paused and reset and then paused and
started.  FW reports a error that dma is still running when pipeline
is started.

ipc4: stop dma when dai is reset

---

src/ipc/ipc4/dai.c

The original code was copied from ipc3 path but the wallclock usage
is different. In ipc4 path fw needs update it for each position update.

ipc4: dai: update wallclock for position update

---

src/audio/google_rtc_audio_processing.c

Due to a mistake, I was using the read API to get a pointer to the
place to write data. This commit corrects it.

google_aec: Use frag_write to write data.

---

src/idc/idc.c
src/include/sof/drivers/idc.h

Remove the dynamic allocation of per-core idc elements since these
are already statically allocated in a form of idc array in zephyr/wrapper.c.
The payload pointer initialization need to use idc entries which are returned by
get_idc() call.
Signed-off-by: Rafal Redzimski <rafal.f.redzimski@intel.com>

zephyr: correct the idc payload initialization

---

Kconfig.sof
src/include/sof/schedule/task.h
src/schedule/ll_schedule.c

Add a lightweight load calculatio to ll_tasks_execute() and prints out
the average every 2^10 runs (roughly once per second on most systems).
Example log output:
--cut--
[     6950848.421715] (      809129.187500) c0 ll-schedule        ./schedule/ll_schedule.c:139  INFO ll avg 19720/38400
[     8868838.449667] (      679100.000000) c0 ll-schedule        ./schedule/ll_schedule.c:139  INFO ll avg 19658/38400
[    10802857.643650] (      565147.187500) c0 ll-schedule        ./schedule/ll_schedule.c:139  INFO ll avg 19822/38400
--cut--

ll_schedule: add a DSP load tracker to ll_tasks_execute

---

src/audio/dcblock/dcblock_generic.c

to fix the mistakes of using audio_stream_read_frag*
while geeting output sink buffer pointer.

audio: dcblock: fix mistakes of sink stream pointer

---

src/audio/base_fw.c

The firmware version numbers should use u16 type, not u32.

ipc4: base_fw: Fix firmware version type in basefw_config IPC

---

src/audio/component.c
src/audio/copier.c
src/audio/mixer.c
src/audio/pcm_converter/pcm_converter_generic.c
src/audio/pipeline/pipeline-graph.c
src/include/ipc4/gateway.h
src/include/sof/audio/pcm_converter.h
src/ipc/ipc4/handler.c

Voice recorder can capture voice and save it to hard disk. This patch fixes some bugs and add support of format conversion used by it.

ipc4: add support for voice recorder in windows 10

---

src/audio/google_rtc_audio_processing.c

Userspace may write the config control repeatedly in quick succession.
Accept the new config in cmd callback to avoid -EBUSY error and ensure
the last successful control write before prepare/copy is applied.
This patch also fixes an edge case during init where the first non-empty
control write happens after prepare. This patch ensures the config is
applied during copy.
Tested:
1) Writes in quick succession
for i in $(seq 1 100); do
./sof-ctl -n 92 -t 0 -b -r -s /root/test_blob0.txt &
./sof-ctl -n 92 -t 0 -b -r -s /root/test_blob1.txt &
done
2) Large config requiring multiple ipcs
for i in $(seq 1 1000); do
./sof-ctl -n 92 -t 0 -b -r -s /root/large_blob.txt
./sof-ctl -n 92 -t 0 -b -r -s /root/test_blob1.txt
done
3) Reboot, write before and after arecord starts
4) Suspend/resume …

google_rtc_audio_processing: Make control write reliable

---

tools/topology/topology1/sof-adl-nau8825.m4
tools/topology/topology1/sof-apl-demux-pcm512x.m4
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof/pipe-echo-ref-dai-capture.m4

The explanation takes sof-adl-max98357a-rt5682 as an example:
During pipeline_complete(), we search for the source widget
for a pipeline from a list and the ipc_get_ppl_comp() returns
the first widget from the list of source widgets for a pipeline.
With SSP2.IN on pipeline 1, which is the same pipeline ID as the
ECHO_REF playback pipeline for PCM0P, pipeline_complete() for
pipeline 1 ends up not walking the rest of widgets in pipeline 1.
This Echo Ref feature works in chrome kernel today by accident,
because we set up the widgets in the reverse order after resuming
from runtime suspend and the source widget happens to be PCM0P.
To fix this, create a new pipeline for the capture dai widget SSP2.IN,
so that it doesn't pollute the widget list for pipeline 1.
Fixes: #5395
Signed-off-by: Chao …

topology1: move capture dai to another pipeline for echo ref

---

src/audio/codec_adapter/codec/dts.c

Enables dts codec to compile cleanly
Signed-off-by: Mark Barton <mark.barton@xperi.com>

audio: codec adapter: remove unused variable from dts codec

---

src/ipc/ipc4/handler.c

gcc fails with the following warning (treated as error):
sof/src/ipc/ipc4/handler.c: In function 'ipc_cmd':
sof/src/ipc/ipc4/handler.c:471:5: error: 'status' may be used uninitialized in this function [-Werror=maybe-uninitialized]
471 |  if (status == COMP_STATE_READY)
|     ^
sof/src/ipc/ipc4/handler.c:439:11: note: 'status' was declared here
439 |  uint32_t status;
|           ^~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/sof.dir/build.make:380: CMakeFiles/sof.dir/src/ipc/ipc4/handler.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2042: CMakeFiles/sof.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Based on the code, this is a false warning since ppl_count should never be
0 (unless ppl_data->pipelines_count is 0), but never the less, the firmware
does …

ipc4: handler: Fix compilation with gcc in ipc4_set_pipeline_state()

---

src/drivers/intel/cavs/dmic.c
src/include/sof/spinlock.h

Backport the fix from main branch:
https://github.com/thesofproject/sof/pull/2078
The target CML device passes record test which has 2000 loops.

IPC command timeout in record test

---

tools/test/topology/test-all.m4
tools/topology/topology1/development/sof-apl-nocodec-demux-eq-2ch4ch.m4
tools/topology/topology1/development/sof-apl-nocodec-demux-eq-4ch4ch.m4
tools/topology/topology1/development/sof-cml-src-rt5682.m4
tools/topology/topology1/development/sof-tgl-nocodec-ci.m4
tools/topology/topology1/m4/bytecontrol.m4
tools/topology/topology1/m4/utils.m4
tools/topology/topology1/sof-apl-demux-pcm512x.m4
tools/topology/topology1/sof-cml-demux-rt5682.m4
tools/topology/topology1/sof-icl-rt711-rt1308-rt715-hdmi.m4
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof/pipe-demux-eq-iir-playback.m4

Cherry-picks with almost no conflict, just a minor conflict for 3e1c160e5053ea caused by the lack of 113a49d253434

Fix topologies build with latest ALSA in stable-v1.9

---

scripts/build-tools.sh
tools/test/topology/tplg-build.sh

This removes two layers of indirection when trying to find what fails.
The lack of this proved especially painful when working on #5632 and
similar backports.
Also move outputs to a subdirectory by default. No change when invoked
from CMake which does not use the default output directory.
Also show the exact m4 and alsatplg commands run when not using XARGS
parallelization. Again this is critical when something fails.

test/topology: make tplg-build.sh callable from anywhere

---

src/audio/pipeline/pipeline-schedule.c

When processing a trigger action in pipeline_task_cmd(), do
not return SOF_TASK_STATE_RESCHEDULE if the pipeline is already
in requested ACTIVE state.
The unnecessary reschedule can cause scheduling bubbles in
topologies with mixer fed by multiple source pipelines. When
the frontend pipelines are released from pause or started,
the connected pipelines that are already running, need to keep
running. A reschedule will cause a gap in scheduling in
of the downstream pipeline(s) mixer feeds.
This fix is not sufficient on its own, but is part of the fixes
to address: https://github.com/thesofproject/sof/issues/5469

pipeline: do not reschedule pipe task if already in target state

---

src/ipc/ipc3/helper.c

BUFFER_FREE IPC returns an error if buffer is connected to
two active components.
However it is allowed to free a buffer in the case where either the sink
or the source is no longer active. This happens for example with buffers
that connect two pipelines. If one pipeline is stopped and freed,
the connecting buffer will be also freed.
This does mean pipeline_disconnect() may be run in context
of a pipeline that is running on a different core. This is
fundamentally unsafe and can lead to undefined behaviour
when two cores access the pipeline bsource_list/bsink_list
at the same time on two different cores.
Fix this issue by checking for this case, and running
the BUFFER_FREE on the active core.
The change is not sufficient on its own, but is part of the fixes
to address: …

ipc: run buffer free in context of active pipeline

---

src/audio/mixer.c

Function returns "ret" in any case, so the additional
check on direction is not needed.

mixer: remove unused code from mixer_trigger_common()

---

tools/topology/topology2/CMakeLists.txt
tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/get_abi.sh

The major/minor/patch values are represented with u16 in the FW. So,
adjust the numbers of bytes when adding the ABI to the topology
manifest. This only applies to IPC4. For IPC3, we still only use 3
bytes as there's no clean way to increase the number of bytes without
breaking backwards compatibility with the older kernel.

topology2: abi: fix size of ABI bytes

---

tools/test/topology/test-all.m4
tools/topology/topology1/development/sof-apl-nocodec-demux-eq-2ch4ch.m4
tools/topology/topology1/development/sof-apl-nocodec-demux-eq-4ch4ch.m4
tools/topology/topology1/development/sof-cml-src-rt5682.m4
tools/topology/topology1/development/sof-tgl-nocodec-ci.m4
tools/topology/topology1/m4/utils.m4
tools/topology/topology1/sof-adl-nau8825.m4
tools/topology/topology1/sof-apl-demux-pcm512x.m4
tools/topology/topology1/sof-cml-demux-rt5682.m4
tools/topology/topology1/sof-icl-rt711-rt1308-rt715-hdmi.m4
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof/pipe-demux-eq-iir-playback.m4

Same as #5632 but for stable-v2.0
Cherry-picks with almost no conflict, just a minor conflict for https://github.com/thesofproject/sof/commit/3e1c160e5053eae66769ad19955df83a08218270 caused by the lack of f41010d3868d5

Fix building stable-v2.0 topologies with latest ALSA

---

src/audio/volume/volume_hifi3.c

initialize variables before using and finalize the
output align register to sink address for aligned
store.

audio: volume: initialize variables before using

---

src/audio/buffer.c

This will fix null dereference issue reported by KW

buffer: fix dereference before null check

---

scripts/xtensa-build-zephyr.py

xtensa-build-zephyr.py: add cavstool.py to staging directory
This is required to read Zephyr logs.

xtensa-build-zephyr.py: add cavstool.py to staging directory

---

.github/workflows/zephyr.yml

The container v0.22.0 changed the toolchain locations, for instance
for APL it changed from
`/opt/toolchains/zephyr-sdk-0.13.1/xtensa/intel_apl_adsp/...`
to
`/opt/toolchains/zephyr-sdk-0.14.0/xtensa-intel_apl_adsp_zephyr-elf/...`
The new location is not found by the old Zephyr version fd089b361d8aebbc
that is currently hardcoded for this branch by previous SOF commit
b678a4dcaa1e. This causes the failure shown below, see real build
failure example in #5641.
The docker image v0.21.0 is the last one that has the old location.
https://hub.docker.com/r/zephyrprojectrtos/zephyr-build/tags
I suspect the name change happened in this commit:
https://github.com/zephyrproject-rtos/sdk-ng/commit/c701e23bcce86f27f3a7
```
-- Using toolchain: zephyr 0.14.0 (/opt/toolchains/zephyr-sdk-0.14.0)
-- Found …
```

stable-v2.0: .github/zephyr: hardcode zephyr container version to v0.21.0

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4

for amplifier rt1019 SSP1 link is used
for headset rt5682 SSP0 link is used
Signed-off-by: Vamshi Krishna <vamshi.krishna.gopal@intel.com>

topology1: sof-adl-rt1019-rt5682: add new topology

---

src/ipc/ipc4/handler.c

When pipeline reset was called from paused state, it was not stopped
beforehand. This resulted in improper device turn-off sequence.
This implementation fits IPC4 pipeline state transitions
```
Ipc4 pipeline message <------> ipc3 pipeline message
RUNNING     <-------> TRIGGER START
INIT + PAUSED  <-------> PIPELINE COMPLETE
INIT + RESET <-------> PIPELINE COMPLETE
PAUSED      <-------> TRIGER_PAUSE
RESET       <-------> TRIGER_STOP + RESET
EOS(end of stream) <-------> NOT SUPPORT NOW
```

ipc4: fix pipeline reset trigger from paused state

---

src/include/sof/audio/component_ext.h

Multiple use of static inline functions across different C
files will result in same symbol names defined in all of the
corresponding object files, because XCC compiler emits the
same symbol names based on the source file for those static
variables inside functions.
If Zephyr logging is used in SOF, we will have log context
redefinition issue with XCC due to above reason.
This patch workarounds the issue by removing the log calls
in static inline functions that are used across multiple C
files.
BugLink: https://github.com/zephyrproject-rtos/zephyr/issues/43786

audio: comp_ext: workaround XCC compatibility with zephyr logging

---

tools/topology/topology1/development/CMakeLists.txt
tools/topology/topology1/development/sof-apl-src-pcm512x.m4

Add this topology to be able to test SRC playback and capture.

Tools: Topology: Add a development topology to RUN SRC on UP2

---

src/audio/base_fw.c

Base FW is lacking implementation for large config set. Returning 0 is
hiding the existing problem and will lead to false success reports. Tests
using this functionality will fail in later steps, making it difficult to
debug.
However, IPC4_FW_CONFIG have to be exception. All existing tests used by
FW team are using this IPC. Its required to maintain unity of tests for
all platforms.

ipc4: base_fw: return fail for not supported ipc

---

LICENCE
src/include/ipc/compress_params.h

This file is copied 'as is' from the Linux kernel repo
and will be used to have a common interface for passing
compressed stream params.

include: ipc: Add compress_params interface file

---

src/audio/codec_adapter/codec/cadence.c

This patch series only move around in order to prepare for sending the codec_adapter ID at runtime from Linux kernel side.
We move all Cadence API calls from init() to prepare() because codec_id will not be available at init(). Earliest case where we could get the codec_id from Linux kernel is at set_params(). the call to prepare() is done later so at the point the codec_id will be know.

Support for dynamic codec adapter id - Part 1

---

src/audio/codec_adapter/codec/waves.c

gcc implements COMPILER_FALLTHROUGH with an __attribute__ so there must be a semicolon after it. Also remove unused variables.

waves: fix building with gcc

---

src/audio/copier.c

The copier component receiving data from the host has an empty bsource_list. The copier_params function references the first item in the list without checking its size. In some cases, this leads to memory corruption.

copier: copier_params: Check the bsource_list size before reference to the first element.

---

zephyr/wrapper.c

`_end` and `_heap_sentry` linker symbols are used to infer heap size. In
Zephyr, `_end` is referenced as `char []` while in SOF as `uint8_t`.
This may "conflicting types", should those declarations be built
together.
This patch changes the Zephyr wrapper to also use `char []`, thus
avoiding this issue.
Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>

zephyr: Use type compatible with Zephyr linker declarations

---

src/audio/copier.c
src/ipc/ipc4/helper.c

When two modules in different pipeline are unbind, the buffer used
by them is free. The buffer is not free if they are in the same
pipeline. So we need to free buffer when pipeline is free

ipc4: free buffer when pipeline is free

---

src/audio/pipeline/pipeline-params.c

Currently we stop preparing when a component in another
pipeline only for some conditions. For passthrough
pipeline host & dai are in different pipelines, these conditions
can't cover it. Actually we should only prepare component in its
parent pipeline, not in other pipeline.
This patch make sure that component is prepared in its own pipeline.
fixes https://github.com/thesofproject/sof/issues/5661

ipc4: pipeline: stop preparing component in another pipeline

---

src/platform/tigerlake/tigerlake.x.in

All TGL-based ADSPs are multicore, but it should also be possible to build SOF with CONFIG_CORE_COUNT=1.
Without this currently linking fails with 1 core enabled in Kconfig

tgl: fix single-core building

---

tools/topology/topology1/m4/bytecontrol.m4

Sometimes we want to load a binary block of data without letting
userspace interact with the underlying control. An RO control will do
this exactly by loading the data and providing no write access.

m4: add RO bytecontrol

---

scripts/xtensa-build-zephyr.py

2 commits, see commit messages.

xtensa-build-zephyr.py:  default to subprocess.run(check=True) . Disable some pylint warnings.

---

src/lib/alloc.c

This Patch to help easily understand available heap from the trace dump.
Current dump:
src/lib/alloc.c:567  heap: 0xbe206000 size 12288 blocks 3 caps 0x65
src/lib/alloc.c:569   used 448 free 11840
src/lib/alloc.c:577   block 0 base 0xbe206000 size 64
src/lib/alloc.c:580    count 64 free 57
Dump with this patch:
src/lib/alloc.c:567  INFO  heap: 0xbe206000 size 12288 blocks 3 caps 0x65
src/lib/alloc.c:569  INFO   (In Bytes) used 0 free 12288
src/lib/alloc.c:576  INFO  64 Bytes blocks ID:0 base 0xbe206000
src/lib/alloc.c:580  INFO    Number of Blocks: total 64 used 0 free 64

alloc: Making heap trace dump more readable

---

src/lib/notifier.c

The notifier struct contains a spin lock which was located in
incoherent memory. This caused an assert on startup when enabling the
build with CONFIG_ASSERT in Zephyr.
At the very least this fix enables building and running with
SPIN_VALIDATE and ASSERT which could help diagnosing issues such
as the panic_dump being garbled.
Signed-off-by: Tom Burdick <thomas.burdick@intel.com>

notifier: Use coherent memory allocation

---

src/audio/google_rtc_audio_processing_mock.c

When doing low mem testing with the mock we should still check our
allocs

google_rtc_audio_processing: add alloc guards

---

tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/cavs/cavs-nocodec.conf
tools/topology/topology2/cavs/platform/intel/mtl.conf

The key difference is the DMIC HW IP version.

topology2: cavs-nocodec: Add support for MTL nocodec topology

---

scripts/xtensa-build-all.sh

Add ipc4 build support for tgl with IPC4_CONFIG_OVERLAY.
If IPC_VERSION is chosen as IPC4, then overlay configuration file for different platforms will be used automatically without assigning the configuration file with options.
Different configuration files will be used according to what platformis building firmware for.
Signed-off-by: Xiaoyun Wu(Iris) <xiaoyun.wu@intel.com>

xtensa-build-all.sh: add ipc4 build support for tgl

---

scripts/docker_build/sof_qemu/Dockerfile

There are warnings about bison and flex not available.
Interestingly these were not fatal errors but time to fix them.
related issues: https://github.com/thesofproject/sof/issues/4186
This is NOT the fix for https://github.com/thesofproject/sof/issues/4186, When the fix is available, I will re-build the docker image for QEMU.

[skip-ci] docker_build: add bison and flex to apt install list

---

scripts/xtensa-build-zephyr.sh

2 clean cherry-picks from main + unhardcoding the Zephyr commit. Review commits separately.
Zero functional change when you don't (try to) pass a zephyr commit on the command line.

stable-v2.0: set default value instead of hardcoding Zephyr commit 

---

src/ipc/ipc4/handler.c

This reverts commit 9b3715fc168aa547495917001735a3ced76b3419.
The commit causes the following error:
[  146.052617] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[  146.556588] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc timed out for 0x47000000|0x0
[  146.556596] sof-audio-pci-intel-tgl 0000:00:1f.3: ctx_save IPC error: -110, proceeding with suspend
The reason is that for IPC4 the reply format is different compared to what
IPC3 is using and also the signaling is different.
If we skip sending the reply, there will be no reply going to be sent to
the host.

Revert "ipc4: setdx: skip sending ipc response"

---

scripts/xtensa-build-zephyr.py

Commit 475e09f17dc3 ("xtensa-build-zephyr.py: default to
subprocess.run(check=True)") switched the default value of the
execute_command() function to "True". Remove all the "check=True"
arguments that are now redundant.
Zero functional change.

xtensa-build-zephyr.py: drop check=True, now the default

---

src/include/sof/audio/component.h
src/platform/amd/renoir/renoir.x.in
src/platform/apollolake/apollolake.x.in
src/platform/baytrail/baytrail.x.in
src/platform/cannonlake/cannonlake.x.in
src/platform/haswell/haswell.x.in
src/platform/icelake/icelake.x.in
src/platform/imx8/imx8.x.in
src/platform/imx8m/imx8m.x.in
src/platform/imx8ulp/imx8ulp.x.in
src/platform/mt8186/mt8186.x.in
src/platform/mt8195/mt8195.x.in
src/platform/suecreek/suecreek.x.in
src/platform/tigerlake/tigerlake.x.in

.module_init sections is used to keep all components constructor
functions.
Zephyr uses -ffunction-sections option which will create a section for
each function. Unfortunately, this creates a section named .module_init
for the function module_init() used to initialize the processing module
generic layer.
Thus, places module_init() in the constructor area named .module_init
which is wrong.
To avoid this we rename .module_init section for constructors to
.initcall.
Fixes: https://github.com/thesofproject/sof/issues/5662

platform: Rename module_init section

---

src/audio/mixer.c

Audio: Clean up mixer processing function on component reset

---

src/audio/crossover/crossover.c

This PR contributes to issue #4488

Audio: clean up stream data and processing functions in crossover on reset.

---

src/audio/mixer.c
src/ipc/ipc4/handler.c

This issue is found by CI capture test with Linux ipc4 driver.
For a pipeline like module A <-> mixin <-> mixout, mixin is
first bound to mixout then bound to module A in CI test. The
original code assume that moudle A is first bound to mixin
since windows driver always bind module from data source to
data sink.
Also need to update direction in each module

IPC4: fix capture issue in CI test

---

src/audio/mux/mux.c

This PR contributes to issue #4488

Audio: Clean up mux/demux processing functions on reset.

---

tools/topology/topology1/sof-hda-generic.m4

These paths are not well supported on all devices and lead to errors such as
17:06:06 kernel: HDA Digital: ASoC: dpcm_be_dai_startup() failed at Digital Playback and Capture (-22)
17:06:06 kernel: Digital Playback and Capture: __soc_pcm_open() failed (-22)
17:06:06 kernel: snd_hda_codec_conexant ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
17:06:06 kernel: snd_hda_codec_conexant ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
17:06:06 kernel: snd_hda_codec_conexant ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
We've already removed this digital path for IPC4/topology2, let's also remove this for topology1.

topology1: sof-hda-generic: remove digital paths

---

src/ipc/ipc4/handler.c

This PR fixes handling of memory allocation error in ipc4_get_large_config_module_instance function. The value returned by the rballoc function is stored in the global variable msg_reply.tx_data. If an allocation error occurs, the function returns an error, but tx_data is overwritten with null. This value is then used in the ipc_msg_send function which leads to null pointer reference.

ipc4: handler: ipc4_get_large_config_module_instance: Fixed handling of memory allocation error

---

src/audio/pcm_converter/pcm_converter_generic.c

This conversion is required by 24LE test in CI
fixes https://github.com/thesofproject/sof/issues/5690

ipc4: add format conversion of 24LE to 32LE

---

installer/GNUmakefile
tools/topology/topology1/CMakeLists.txt
tools/topology/topology2/CMakeLists.txt
tools/topology/topology2/cavs/CMakeLists.txt

See the long and detailed commit message. See also deep buffer #4611 for more context.

tools: stop copying v2 topologies to the v1 directory

---

src/audio/codec_adapter/codec/cadence.c
src/audio/codec_adapter/codec_adapter.c
src/include/ipc/stream.h
src/include/kernel/abi.h
src/include/sof/audio/codec_adapter/codec/generic.h
src/ipc/ipc3/handler.c

This is a follow up of: https://github.com/thesofproject/sof/pull/5591
In this PR we expand `sof_ipc_stream_params` with the capability of holding extra data appended at the end. We take 2 bytes from `sof_ipc_stream_params` reserved bytes and use it to keep hold of the extended data.
Most of the patches are for this. Also bump ABI minor. 
This will also require a kernel PR which will posted soon.

Support for dynamic codec adapter id - Part 2

---

src/drivers/amd/renoir/acp_dmic_dai.c
src/drivers/amd/renoir/acp_dmic_dma.c
src/include/ipc/dai-amd.h
src/include/ipc/dai.h
src/include/kernel/abi.h
src/include/sof/drivers/acp_dai_dma.h

So far we only support 48000Hz as default sample rate.
Now introduce acp_params structure to pass configuration
from topology via AP to DSP.
Only Sample rate param for now to configure dmic clk.
While here, align sof_ipc_dai_acp_params struct
with the one from kernel.
Increment only ABI MINOR version which makes the
SOF FW backward compatible with older kernel versions

drivers: amd: renoir: use sample rate from topology

---

src/audio/src/src.c

Fix src issue on windows. Need to update sink format before
src_verify_params which uses it to generate dev->frame.

ipc4: set sink sample rate before verifying params

---

src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

This patch fixes errors:
```
src/ipc/ipc4/handler.c: In function 'ipc_cmd':
src/ipc/ipc4/handler.c:204:23: error: 'host' may be used uninitialized
in this function [-Werror=maybe-uninitialized]
struct ipc_comp_dev *host;
^~~~
src/ipc/ipc4/helper.c: In function 'ipc4_trigger_chain_dma':
src/ipc/ipc4/helper.c:667:6: error: 'ret' may be used uninitialized
in this function [-Werror=maybe-uninitialized]
int ret;
^~~
src/ipc/ipc4/helper.c: In function 'ipc4_create_chain_dma':
src/ipc/ipc4/helper.c:507:13: error: 'frame_size' may be
used uninitialized in this function [-Werror=maybe-uninitialized]
frame_size >>= 1;
~~~~~~~~~~~^~~~~
src/ipc/ipc4/helper.c:482:11: note: 'frame_size' was declared here
uint32_t frame_size;
^~~~~~~~~~
```

IPC: IPC4: Fix GCC build errors

---

scripts/docker-run.sh
zephyr/docker-build.sh

This fixes SOF version.cmake which was just broken by a recent git
security update and started to fail like this:
```
-- SOF version.cmake starting at 2022-04-25T18:14:56Z UTC
-- /workdir/zephyr/.. is at git commit with parent(s):
fatal: unsafe repository ('/workdir' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /workdir
```
(example at https://github.com/thesofproject/sof/runs/6162885265)
chgrp -R was always an ugly hack because it was messing with
(persistent) file permissions on the host, outside the container. This
new adduser solution is unfortunately much more code but it does not
leak any side effect outside the container.
Do not fix scripts/docker-run.sh yet because there is still no UID
mismatch between Github …

zephyr/docker-build.sh: match UID with 'adduser' instead of 'chgrp -R'

---

.github/workflows/zephyr.yml
scripts/xtensa-build-zephyr.sh

2 commits, see commit messages.

stable-v2.0: un-hardcode Zephyr container and SDK

---

.github/workflows/zephyr.yml

These are Github Actions, so let's use the Github server to increase
performance and reduce external dependencies.
According to https://github.com/zephyrproject-rtos/docker-image there is
no primary or secondary server for that image, they're both equivalent.

[SKIP CI] .github/zephyr: download docker image from ghcr.io instead of docker.io

---

.github/workflows/installer.yml

When the build fails we don't want to waste time wondering whether TGL
is affected or not. Other, unsupported platforms are only providing some
nice to have "randconfig" coverage (#5364), they're not important.

[SKIP CI] .github: IPC4: build supported TGL platforms first

---

src/audio/codec_adapter/codec/cadence.c

This is final part of series supporting dynamic codec id. 
Codec id will be sent from the Linux host via sof_ipc_stream_params and kept in the extended data
structure. 
First two series were previously sent for review at:
https://github.com/thesofproject/sof/pull/5591 (1)
https://github.com/thesofproject/sof/pull/5592 (2)
Current PR contains (1) and (2) above. Only last two patches are actually new in this PR.

Support for dynamic codec adapter id - Part 3

---

scripts/docker-run.sh
zephyr/docker-build.sh

We need the SOF version in stable branches too; 2 cherry-picks from main.
Backport of
- #5730
Minor git conflicts because this branch does not have the new
xtensa-build-zephyr.py, it still uses xtensa-build-zephyr.sh

stable-v2.0 backport: zephyr/docker-build.sh: match UID with 'adduser' instead of 'chgrp -R'

---

src/audio/dcblock/dcblock.c

Audio: Clean up processing function and coefficients of dcblock on reset.

---

tools/ctl/ctl.c

* Use %z specifier for size types to avoid format
specifier warnings on arm32
* in ctl_dump(), size_t n may be used uninitialized
if ctl_data->out_fd > 0 and !ctl_data->binary.

sof-ctl: Fix -Wformat,-Wsometimes-uninitialized

---

src/drivers/amd/renoir/acp_bt_dai.c
src/drivers/amd/renoir/acp_sp_dai.c

Add remove callback function for SP and BT dai
drivers in dai ops.
This callbacks definition will resolve the firmware
NULL pointer access during remove sequence from sof core.

drivers: amd: renoir: add remove call back function

---

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4

rt1019 in auto mode is compatible with rt1015p driver.
By keeping the SSP configuration same as rt1015 will have fewer
configuration.
Signed-off-by: Vamshi Krishna <vamshi.krishna.gopal@intel.com>

topology1: Change SSP_Config for rt1019

---

src/audio/copier.c
src/include/sof/ipc/topology.h
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

Fix a capture issue on windows. Currently we use SOF_COMP_HOST
or SOF_COMP_DAI for copier with host or dai included. But There
are some functions process copier as host or dai since its type
is that type. This will result to unexpect error.
This patch introduce SOF_COMP_COPIER for copier so that it can
be indentified in ipc4 framework.

ipc4: use SOF_COMP_COPIER for copier module

---

src/drivers/amd/renoir/acp_dma.c
src/drivers/amd/renoir/acp_sp_dma.c

Flush i2s fifo buffers before stream start.
Re-arrange host buffer DMA operations.

drivers: amd: renoir: fix for Bo noise during stream start

---

Kconfig.sof
src/include/sof/audio/component.h
src/include/sof/audio/component_ext.h
src/include/sof/lib/perf_cnt.h
src/lib/agent.c
src/schedule/ll_schedule.c

The average number of cpu cycles/ticks spent could be provided per 1024
scheduled tasks by the performance counter. It would be more accurate for
MCPS measurement than the peak number. Even so, the tracing macro will log
both of them to provide more insights.
This is enabled by CONFIG_PERFORMANCE_COUNTERS_RUN_AVERAGE, which depends
on CONFIG_PERFORMANCE_COUNTERS.

perf_cnt: add the tracing of window-based average calculation

---

src/drivers/imx/esai.c
src/drivers/imx/sai.c
src/drivers/intel/alh.c
src/drivers/intel/dmic/dmic.c
src/include/sof/lib/dai.h
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c

Add function to fetch dai fifo depth from driver platform data, as for
some reason it is missing. Update all drivers that are actually using
it.

dai: add op to fetch dai fifo depth

---

scripts/xtensa-build-all.sh

Update xtensa core to RI-2019.1 for AMD platform Renoir

[AMD] scripts: update xtensa core name and version for renoir

---

scripts/xtensa-build-zephyr.py
zephyr/docker-build.sh

This can fail for various reasons listed in a comment.
Remove now redundant `west topdir` check.
Without this check, a not found SOF fails with very cryptic Kconfig
errors:
```
zephyr/samples/subsys/audio/sof/prj.conf:5:
warning: attempt to assign the value 'n' to undefined symbol HAVE_AGENT
zephyr/samples/subsys/audio/sof/prj.conf:8:
warning: attempt to assign the value 'n' to undefined symbol
DEBUG_MEMORY_USAGE_SCAN
zephyr/samples/subsys/audio/sof/boards/intel_adsp_cavs15.conf:1:
warning: attempt to assign the value 'y' to undefined symbol APOLLOLAKE
```
etc.

xtensa-build-zephyr.py: make sure that west can find SOF

---

src/arch/xtos-wrapper/include/kernel.h
src/audio/pipeline/pipeline-stream.c

I left out the k_sleep() for cycles alone, to avoid k_timeout_t definition for XTOS. It did not look like that was needed.

k_usleep() and k_msleep() wrappers for xtos

---

src/audio/rtnr/CMakeLists.txt
src/audio/rtnr/rtklib/mt8195/CMakeLists.txt
src/audio/rtnr/rtklib/mt8195/README.txt
src/audio/rtnr/rtklib/tgl/CMakeLists.txt

This PR separates RTNR library path for multiple platforms including MT8195.

Add RTNR library path for MT8195

---

src/arch/xtensa/CMakeLists.txt

To fix https://github.com/thesofproject/sof/issues/5693
This PR depends on https://github.com/thesofproject/rimage/pull/91 . The rimage PR needs to be merged at first.
SOF CMake defines SOF_MAJOR, SOF_MINOR and SOF_MICRO for 3 fields of
firmware file version major.minor.micro. But CMake only passes the major
and minor version to rimage.
Now CMake will also pass the mirco version to rimage, so that rimage can
write it to different firmware manifest headers for cAVS platforms and
then sof_ri_info.py will be able to dump entire file version info from
the firmware binary.

[RFC] CMake: pass firmware file micro version to rimage

---

src/audio/mux/mux.c
src/audio/src/src.c
src/idc/idc.c
src/idc/zephyr_idc.c
src/include/sof/audio/component.h
src/include/sof/debug/panic.h
src/include/sof/lib/mailbox.h
src/platform/intel/cavs/include/cavs/lib/mailbox.h

2 commits
----
Break down buggy assert(!memcpy_s(...)) into two statements
assert() semantics are very clear: because asserts are optional, the
argument should never have side-effect, period. assert arguments should
be treated exactly the same as logging arguments. So
`assert(!memcpy_s())` is an obvious bug. Use variable to break that down
into two statements.
Fixes commit 0b7fd030b391 ("demux: return config on COMP_CMD_GET_DATA")
Fixes commit 385586a5f664 ("zephyr: implement IDC using P4WQ")
----
Make Zephyr build compatible with optional assert() with __unused
For some legacy reason(s), SOF assert() is not optional. This is unlike
any other assert() anywhere else. This hasn't been a problem yet because
until now SOF assert() has been mapped to a non-optional and limited
Zephyr k_oops() …

Make Zephyr build compatible with optional assert()

---

src/audio/buffer.c
src/include/sof/audio/buffer.h

comp_update_buffer_produce() and comp_update_buffer_consume() acquire and release buffers internally. We need versions of those functions, that take already acquired cached buffer objects as arguments, we will switch over to them completely gradually. This patch adds such functions.

buffer: add cached consume and produce update versions

---

src/audio/google_hotword_detect.c
src/audio/host.c
src/audio/mixer.c
src/audio/pipeline/pipeline-graph.c
src/drivers/amd/renoir/ipc.c
src/drivers/host/ipc.c
src/drivers/imx/ipc.c
src/drivers/intel/baytrail/ipc.c
src/drivers/intel/cavs/ipc.c
src/drivers/intel/cavs/sue-ipc.c
src/drivers/intel/haswell/ipc.c
src/include/ipc/header.h
src/include/ipc3/header.h
src/include/ipc4/header.h
src/include/ipc4/module.h
src/include/ipc4/notification.h
src/include/ipc4/pipeline.h
src/include/kernel/abi.h
src/include/sof/ipc/common.h
src/include/sof/ipc/driver.h
src/include/sof/ipc/msg.h
src/ipc/ipc3/handler.c
src/ipc/ipc4/dai.c
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c
src/platform/intel/cavs/platform.c
tools/oss-fuzz/fuzz_ipc.c

Refactor of code related to IPC handling.
PR Includes:
- fix the parameters passed to ipc_msg_init
- update of common ipc4 structures to reflect primary/extension contents of ipc4 header
- update of ipc4 command specific structures to reflect primary/extension contents of ipc4 header
- remove the special treatment of the extension dword which had been part of payload data
- update the ipc_cmd_hdr to be used safely for ipc3 and ipc4

SOF IPC header cleanup

---

scripts/xtensa-build-zephyr.py

Add a new -d option to support SOF debug build. This
option will add CONFIG_DEBUG=y to SOF configuration,
which is aligned with xtensa-build-all.sh script.

xtensa-build-zephyr.py: add -d option for debug build

---

src/include/sof/audio/mux.h

If PLATFORM_MAX_CHANNELS < 8 the mux_stream_data becomes
smaller, however there is no easy to way
supply a smaller ROUTE_MATRIX in m4/muxdemux.m4.
Instead, pad the mux_stream_data so the sizes from firmware
and topology match.

mux: Use a fixed size for mux_stream_data

---

src/ipc/ipc4/handler.c
src/platform/intel/cavs/include/cavs/lib/power_down.h
src/platform/intel/cavs/lib/clk.c
zephyr/wrapper.c

These two patches fix sparse warnings about address space mismatches. These patches do not depend on #5782 and can be merged independently

cache coherency: 2 correctness patches

---

src/ipc/ipc4/helper.c

Convert posix error to ipc4 error and return ipc4 error for
functions in ipc4 directory.
fixes https://github.com/thesofproject/sof/issues/5737

ipc4: return ipc4 error status instead of posix error

---

zephyr/CMakeLists.txt

There are few left paths and config names after switching from
codec_adapter to module_adapter.
Without this building codec modules fails

zephyr: Fix compile error after switching to module_adapter naming

---

src/audio/pipeline/pipeline-params.c

Fixed fw panic in ci test. Fw checks sink component in another
incomplete pipeline but the sink component is not set at this time.
Stop pipeline check for ipc4 component in another pipeline and return immediately.
fixes https://github.com/thesofproject/sof/issues/5777

ipc4: avoid pipeline sink component check in different pipeline

---

src/audio/copier.c

Only a cosmetic change. use "unable" instead of "unenable"

(Cosmetic)copier: fix spelling mistake

---

scripts/checkpatch.pl

Among a gazillion of features and fixes, notably fixes the super annoying:
```
./scripts/checkpatch.pl -g 2ebf92f2793 --codespell
WARNING: 'ba' may be misspelled - perhaps 'by'?
#7: 
There was no need to copy/paste; fixes commit02c21c25ba33 ("dma-trace.c:
```

Update checkpatch version to Linux' v5.17

---

overlays/common/debug_overlay.conf

The debug_overlay.conf is somehow missing from #5792,
add it in this patch.
My bad that I didn't notice that this file is missing from #5792 in new push before, until I want to add CI support now

overlays: add common/debug_overlay.conf for debug build

---

src/audio/module_adapter/module_adapter.c

We need to use UUID in order to identify a component. For now
we only support module_adapter components so just skip checking
config->type.

module_adapter: Don't use config->type to identify component

---

src/audio/copier.c
src/drivers/intel/alh.c
src/include/ipc4/alh.h
src/include/ipc4/copier.h

There are some usage cases that multiple gateways are
used, such as two alh dais to support single stream on
some productions with two codecs to support two speakers.
In this case two dais config are included by one copier.
This patch enables multiple gateway support in one
copier and creates corresponding dai for these gateways.

ipc4: copier: add multiple gateway support

---

tools/topology/topology1/sof-icl-rt711-rt1308-rt715-hdmi.m4

This is useful for debug and tests.

topology1: soundwire: add macro to remove HDMI

---

scripts/docker-run.sh
scripts/xtensa-build-zephyr.sh
zephyr/docker-build.sh

Clean cherry--picks, same as https://github.com/thesofproject/sof/commits/stable-v2.0/scripts
See longer story in review https://github.com/thesofproject/sof/pull/5654 for commit https://github.com/thesofproject/sof/commit/7ec25f16af9ea557aaf0a4bbef6ab7ffc5505a0b
IMPORTANT: this "unharcodes" the Zephyr version, switches to an SOF branch. See commit message of "[xtensa-build-zephyr.sh: switch to new Zephyr branch sof/stable-v2.0](https://github.com/thesofproject/sof/pull/5831/commits/1fbd2e3f541e8b683647ada49929efb2a08fae29)"

Backport zephyr and SOF.version fixes to adl-004-drop-stable, same as stable-v2.0

---

src/audio/pipeline/pipeline-graph.c
src/ipc/ipc4/helper.c

Fixed random error issue on both windows and Linux.
In ipc4 path ipc_build_stream_posn does nothing so
the posn.rhdr.hdr.size has a random value and sometimes
is very big. This result to memory allocation failure at here
or else in the following allocation.
This patch doesn't create ipc->msg when posn.rhdr.hdr.size
is zero for ipc4 case.

ipc4: don't create pipeline msg for ipc4

---

src/audio/component.c
src/audio/volume/volume.c
src/include/sof/audio/audio_stream.h
src/include/sof/audio/component.h
src/math/Kconfig
src/math/numbers.c

add comp_get_copy_limits_with_lock_aligned API to meet requirement
of some xtensa intrinsics.

audio: add aligned limits for component copy function

---

src/audio/copier.c

Fix memory leak in stress test. Buffer_release is for cache
operation not for memory free. And buffer_free can free memory
and also release buffer.

ipc4: use buffer_free to free buffer

---

src/ipc/ipc4/handler.c
src/platform/intel/cavs/lib/power_down.S

Skip sending reply message to a SET_DX if pm_prepare_D3 is set and do it
in power down time in a same way as it is done with IPC3.

ipc4: cavs: power_down: Send SET_DX reply on power down

---

src/audio/rtnr/rtnr.c
src/include/sof/audio/rtnr/rtnr.h
tools/topology/topology1/m4/rtnr.m4
tools/topology/topology1/sof/pipe-rtnr-capture-16khz.m4
tools/topology/topology1/sof/pipe-rtnr-capture.m4

This PR is based on https://github.com/thesofproject/sof/pull/5616
It decouples the switch-typed control for enabling/disabling from the control bytes.
Previously, control blobs should be sent from userspace to to toggle RTNR on/off.
With this PR, RTNR can be toggled by setting the UCM switch value.
cset "name='RTNR10.0 rtnr_enable_10' off"
cset "name='RTNR10.0 rtnr_enable_10' on"
or from command line
amixer -c0 cset name='RTNR10.0 rtnr_enable_10' 1
amixer -c0 cget name='RTNR10.0 rtnr_enable_10' 0
Signed-off-by: Pin-chih Lin [johnylin@google.com](mailto:johnylin@google.com)
Signed-off-by: Ming Jen Tai [mingjen_tai@realtek.com](mailto:mingjen_tai@realtek.com)
Cherry-picked from 2e6bfbec1ccc069129b3f91212fc8e6af04284bb

RTNR: Decouple switch-enable control from params blob

---

src/platform/intel/cavs/lib/dai.c

This never happens in practice, but statis analysis tools are right complaining about potential NULL dereference here.

dai: fix potential NULL dereference

---

src/audio/copier.c
src/include/sof/ipc/topology.h
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

FW doesn't set component direction if the component is
for gateway. Now check the component direction and
skip set it if it is set. Only the direction of gateway
module is figured out based on gateway type so
only copier module supports get_attribute of direction.
The original method can't deal with a corner case that
gateway module has both input & output.

ipc4: set component direction if it is not set

---

tools/topology/topology2/cavs/cavs-nocodec.conf
tools/topology/topology2/cavs/platform/intel/dmic-default.conf
tools/topology/topology2/cavs/platform/intel/dmic-generic.conf

Add the second 16kHz dmic1 dai to topology2 dmic config. This dai
doesn't yet have a pipeline, but it will be used in nhlt blob
calculation. Internal testing showed that some firmware variants need
the 16kHz dai to be defined in nhlt blob even though it is not used. The
pipeline for this dai will be added later.

topology: add dmic1 dai for topology2 default dmic

---

CODEOWNERS

Now we won't need code changes to update reviewers when we have
additions or departures.

OWNERS: move google files to team reference

---

src/drivers/intel/dmic/dmic_nhlt.c

This patch sets plat_data fifo depth for SOF_IPC_STREAM_CAPTURE instead
of a SOF_IPC_STREAM_PLAYBACK. The value is later read with
get_fifo_depth().
Without this patch the driver sets the value to fifo[0].depth and then
reads from fifo[1].depth.

intel: dmic: set plat_data fifo depth for capture

---

src/include/sof/audio/component.h

fix the unsymmetrical order of lock and unlock issue in
function comp_get_copy_limits_with_lock to avoid IPC
tiime out risk.

audio: fix the unsymmetrical order of lock and unlock.

---

scripts/xtensa-build-zephyr.py

This is to fix https://github.com/thesofproject/sof/issues/5775. It depends on rimage PR https://github.com/thesofproject/rimage/pull/95
Extract SOF firmware file version string (x.y or x.y.z) from latst git tag
by 'git describe --tags' and python regex, and pass it to rimage in
signing phase. So rimage can write the version info to the firmware
manifest headers for cAVS platforms.
Signed-off-by: mengdonglin <mengdong.lin@intel.com>

xtensa-build-zephyr.py: pass SOF firmware file version string to rimage

---

src/audio/dcblock/dcblock_generic.c

Optimize the read/write frags of dcblock processingg functions.
By using audio_stream_bytes_without_wrap, this optimization can
decrease about 14% MCPS.

Audio: Dcblock: Optimize dcblock read/write frags

---

src/audio/mixer.c

Only generate period bytes worth of zeroes when all the mixer sources are
paused so as to not cause overruns in the components that follow
downstream.

mixer: produce only period bytes when paused

---

tools/testbench/file.c

Use DECLARE_SOF_RT_UUID and fix the uuid name in the comp_drv for the
file component.

testbench: fix UUID declaration for file

---

scripts/xtensa-build-zephyr.py

This is only for SOF v2.2 release branch stable-v2.2
This PR includes 2 commits:
- The release branch is created for SOF v2.2 in the cloned Zephyr repo:  
https://github.com/thesofproject/zephyr/tree/sof/stable-v2.2
This points to unmodified Zephyr upstream tag v3.1.0-rc3
Set default Zephyr URL to this cloned repo and switch default branch to sof/stable-v2.2
- Cherry pick commit [xtensa-build-zephyr.py: pass SOF firmware file version string to rimage](https://github.com/thesofproject/sof/pull/5893/commits/317b6da2cb586902287cd37efe6871b1d6e84949) from main branch.

xtensa-build-zephyr.py: switch default to sof/stable-v2.2

---

scripts/xtensa-build-zephyr.py

Do not fail when there's only an empty directory left over
because of some early interruption of this script or proxy
misconfiguration, wrong fetch location, etc.

xtensa-build-zephyr.py: try to rmdir zephyrproject before cloning

---

.github/workflows/codestyle.yml

This makes the difference between "strict" and regular failures very
clear.
Stopping after non-strict failures is misleading, it can give the wrong
impression that there are very few warnings left.

[SKIP CI] .github: independent strict and non-strict runs of check patch

---

src/audio/rtnr/rtnr.c

This PR passthrough multi channels audio from microphone using stream copy outside RTNR, instead of using the bypass function provided by RTNR.

rtnr: passthrough audio by stream copy

---

src/math/Kconfig

This avoids need to know that both log functions depend on
base2log.c module.

Math: Select BINARY_LOGARITHM_FIXED if log() or log10() is enabled

---

src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c

This patch will extend Zephyr native drivers api usage
to ipc dai files and full flow with dma release will be supported

ipc: dai: extend Zephyr native drivers api to ipc/dai.c

---

src/include/sof/lib/perf_cnt.h

A regression bug was introduced by gh-5393 pull request.
SOF can support two timestamp sources: platform timer and
system timer. Zephyr only supports one timer. This fix
restores usage of two timers (platform and system) on
SOF without Zephyr and uses the only one available timer
on SOF with Zephyr.

Fix performance counter regression

---

src/audio/copier.c
src/drivers/intel/alh.c
src/drivers/intel/ssp/ssp.c
src/include/sof/audio/ipc-config.h

For some of the dai devices, sampling frequency is not passed as a part
of IPC4 blob. Added this value to ipc_config_dai, so during
configuration devices can access it through their common_config
argument.
This fixes ALH and SSP not working with other sampling frequencies than default ones when using IPC4.

IPC4: DAI: Add sampling frequency to ipc_config_dai

---

scripts/xtensa-build-zephyr.py

This series include 3 patches:
- xtensa-build-zephyr.py: add option to specify name of non-default signing key
- xtensa-build-zephyr.py: add option to create an output directory for each platform
- xtensa-build-zephyr.py: avoid showing wrong layout of installed files  (a bug fixing)
Users can make xtensa-build-zephyr.py to generate output layout like this:
```
sof/<platform_name>/<key_name>/sof-<platform_name>.ri
/sof-<platform_name>.ldc
```
And this layout will comply with that in Linux distribution for firmware supporting IPC4 of new Intel platforms.
**Updates of v2:**
- Use option `--key-type-subdir` to choose the output subdirectory name for signing key type. Define the list 'community', 'dbgkey' and 'none' for valid key types.
- use option '--use-platform-subdir' to create output …

xtensa-build-zephyr.py: add option to change output file layout for different platforms and keys

---

scripts/xtensa-build-zephyr.py

When neither -c nor -p is passed, the script defaults to '-p
SOF_TOP/zephyrproject', initializing the `west_top` global with
that. When everything is already cloned, this becomes
zephyrproject/modules/audio/sof/zephyrproject which is really not a
`west topdir`. Then west is pointed at:
real_west_top/modules/audio/sof/zephyrproject/zephyr/samples/subsys/audio/sof
which obviously fails.
This was found while testing
https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html
and trying (and failing) to switch away from the older .sh script.
Fix find_west_workspace() to return the output of `west topdir` and use
that to update the `west_top` global.
This bug was introduced from the very start when the script was
converted from shell to python. The shell script …

xtensa-build-zephyr.py: fix find_west_workspace() to return west topdir

---

src/audio/copier.c
src/include/sof/audio/component.h
src/include/sof/ipc/topology.h
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

The get_attribute op for copier is used to determine whether the
direction has already been set or not so that the handler can skip
resetting the direction for host/dai components. Remove the op and use
the new fieldm direction_set in struct comp_dev to determine whether the
direction should be updated or not. Also, set the direction_set flag for
host/dai copier when it is created.
This change is in preparation to convert the copier module to use the
module interface instead of the comp_drv ops.

copier: remove get_attribute op

---

src/include/sof/ipc/common.h
src/ipc/ipc4/handler.c
src/platform/intel/cavs/platform.c

During transition from D0 to D3, IPC processing completion is done
during power down procedure (file power_down.S).
FW build based on XTOS never exit from ipc_do_cmd() and will not enter
ipc_complete_cmd(). Zephyr based FW on other hand will execute power
down procedure after enering idle,  when IPC processing task is
completed. Therefore it should be skipped here.

ipc4: setdx: message completion delay

---

src/audio/dai-legacy.c
src/audio/dai-zephyr.c
src/drivers/intel/dmic/dmic.c
src/include/sof/drivers/dmic.h
src/include/sof/lib/dai.h
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c

The DMIC driver currently uses a separate task to perform gain ramping on start up. This can be achieved from the `.copy()` context avoiding an additional asynchronous context and races associated with it.

DMIC: eliminate the gain ramping task

---

src/include/sof/coherent.h
src/ipc/ipc-helper.c

When connecting a buffer to a component, if the buffer is shared it has to be configured as such. This is done by calling coherent_shared() for coherent objects, protected by a spin-lock. However, buffers under Zephyr are protected by a mutex, therefore coherent_shared_thread() has to be used.

buffer: fix wrong coherent_shared() call with Zephyr

---

src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module_adapter.c

Add zephyr logging declares to module_adapter as it doesn't
compile otherwise when zephyr logging is enabled.

module_adapter: add zephyr logging support

---

src/audio/module_adapter/module_adapter.c

module_adapter_copy() is typically called every millisecond for each copy. Issuing an "info"-level log statement with that frequency floods the log. Replace it with a "comp_dbg()."

module-adapter: fix prohibitively verbose log message

---

src/audio/host-zephyr.c

Add zephyr logging register to host as it doesn't compile otherwise when
zephyr logging is enabled.

host-zephyr: add zephyr logging support

---

src/ipc/ipc4/dai.c

ipc4 dai is missing the group ifdef, thus add it there.

dai: groups: Add group ifdef also to ipc4 dai

---

scripts/cmake/version.cmake

Local filters in ~/gitconfig, such as
[core]
autocrlf = input
can impact the result of git hash-object. Make sure no filters are
used so that the hash value remains unmodified across user setups.
BugLink: https://github.com/thesofproject/sof/issues/5917

cmake: make sure sha1 is computed without filters

---

src/include/sof/debug/panic.h

Continue the changes done in commit bc39c0e91284 ("Make Zephyr build
compatible with optional assert() with __unused") and switch
to use __ASSERT_NO_MSG() as implementation of assert() when SOF
is build with Zephyr.
This allows for build time control of asserts with standard
CONFIG_ASSERT option(s) and ensures same policy is used for asserts in
both Zephyr and SOF code.
This effectively disables assert checks in the default build for Zephyr,
improves performance of a typical single ll scheduled audio component by
0.08 MCPS. Performance was tested with the Intel Tiger Lake system,
build with XCC 12.0.8 as defined in sof/scripts/xtensa-build-zephyr.py.

zephyr: panic: switch to __ASSERT_NO_MSG() for assert()

---

src/audio/module_adapter/module/volume/volume.c

Free the memory allocated for volume config data in the free op.

volume: free volume config data during free

---

tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/cavs/cavs-sdw-src-gain-mixin.conf
tools/topology/topology2/include/common/audio_format.conf
tools/topology/topology2/include/components/cavs/src.conf
tools/topology/topology2/include/components/cavs/src_format.conf
tools/topology/topology2/include/components/cavs/src_passthrough_format.conf
tools/topology/topology2/include/components/gain.conf
tools/topology/topology2/include/components/mixin.conf
tools/topology/topology2/include/components/mixout.conf
tools/topology/topology2/include/pipelines/cavs/mixout-gain-dai-copier-playback.conf
tools/topology/topology2/include/pipelines/cavs/mixout-gain-host-copier-capture.conf
tools/topology/topology2/include/pipelines/cavs/passthrough-be.conf
tools/topology/topology2/include/pipelines/cavs/src-gain-mixin-playback.conf

This PR add ipc src support in topology2.

topology2: add src support

---

tools/topology/topology1/sof-tgl-rt711-rt1308.m4

For some reason we never added the switch in this topology, with leads
to a missing control when parsing UCM files
BugLink: https://github.com/thesofproject/sof/issues/5950
BugLink: https://github.com/alsa-project/alsa-ucm-conf/issues/179

topology1: sof-tgl-rt711-rt1308: add missing switch

---

src/schedule/zephyr_ll.c

when call pause and then call stop, it will cause next triger start failed
Signed-off-by: honglin leng <a909204013@gmail.com>

zephyr_ll: add task_cancel function state judgement

---

src/platform/mt8195/mt8195.x.in

Support clib data and rodata for mt8195.

platform: mtk: add clib memory layout for mt8195

---

src/audio/aria/aria.c
src/audio/crossover/crossover.c
src/audio/crossover/crossover_generic.c
src/audio/drc/drc.c
src/audio/drc/drc_generic.c
src/audio/multiband_drc/multiband_drc.c
src/audio/multiband_drc/multiband_drc_generic.c
src/audio/smart_amp/smart_amp.c
src/audio/smart_amp/smart_amp_generic.c
src/audio/smart_amp/smart_amp_maxim_dsm.c
src/audio/tone.c
src/include/sof/audio/crossover/crossover.h
src/include/sof/audio/drc/drc.h
src/include/sof/audio/multiband_drc/multiband_drc.h
src/include/sof/audio/smart_amp/smart_amp.h
src/include/sof/samples/audio/smart_amp_test.h
src/samples/audio/detect_test.c
src/samples/audio/kwd_nn_detect_test.c
src/samples/audio/smart_amp_test.c
zephyr/CMakeLists.txt
zephyr/wrapper.c

next 7 commits from the cache / coherency / sparse work

cache / sparse: next lot

---

.github/workflows/pull-request.yml

From time to time sof-docs regressions are introduced in sof.git. This
introduces a random and sometimes long delay between when the regression
is introduced and when it is found. A recent example is
https://github.com/thesofproject/sof/pull/5731#issuecomment-1175630147
where the doxygen comments were duplicated. Doxygen alone did not mind,
then the sof-docs build failed much later which took multiple people a
lot of time to understand and bisect.

[SKIP CI] .github: add sof-docs build to Github Actions

---

src/include/sof/lib/dai-legacy.h

This fixes the sof-docs build and stops producing a dai-drivers-api.html
garbage that randomly mixed the two .h files.
```
Warning: Duplicate target detected:
group__sof__dai__drivers_1ga8c720c310f408b2f97ce014562d6a910
sof-docs/api/dai-drivers-api.rst:4: WARNING: Duplicate ID:
"group__sof__dai__drivers_1ga8c720c310f408b2f97ce014562d6a910".
sof-docs/api/dai-drivers-api.rst:4: WARNING: Duplicate explicit target name:
"group__sof__dai__drivers_1ga8c720c310f408b2f97ce014562d6a910".
sof/sof-docs/api/dai-drivers-api.rst:6: WARNING:
Duplicate declaration, const struct device* dai::drv
```
(Temporarily?) fixes commit 015ec63c4dad7d5bf ("zephyr: add glue code to
use zephyr dai drivers") that introduced a lot of duplication with
dai-zephyr.h. See more details at …

[SKIP CI] Exclude dai-legacy.h from doxygen to avoid clashes with dai-zephyr.h

---

scripts/docker_build/sof_builder/Dockerfile

No functionality change. Minor clean up.
Plan to add HASH loggings for each repo before deleting them.

[SKIP CI] docker: log git hashes for each projects

---

src/audio/google_rtc_audio_processing.c

Remove the assumption that the AEC reference was coming from a DEMUX.
It now uses the fact that the AEC reference comes from another pipeline
in order to detect it is the reference signal.

google_rtc: Do not rely on component type.

---

scripts/xtensa-build-zephyr.py

This will significantly speed up CI in some cases.
Fixes commit ffdf001eeeba ("xtensa-build-zephyr.py: clone zephyr with
--depth 5")
When I added --depth 5 to git clone in that commit I naively assumed git
fetch would "inherit" that. I think it does but only when fetching an
_existing_ (and shallow) branch, not when fetching something new.

xtensa-build-zephyr.py: speed up thanks to an _actually_ shallow clone

---

src/audio/asrc/asrc.c
src/audio/copier.c
src/audio/dai-legacy.c
src/audio/dai-zephyr.c
src/audio/host-legacy.c
src/audio/host-zephyr.c
src/audio/mixer.c
src/audio/pipeline/pipeline-graph.c
src/audio/src/src.c
src/include/ipc4/copier.h
src/include/sof/audio/aria/aria.h
src/include/sof/audio/component.h
src/include/sof/audio/component_ext.h
src/include/sof/audio/pipeline.h
src/include/sof/audio/up_down_mixer/up_down_mixer.h
src/include/sof/lib/dai-legacy.h
src/include/sof/lib/dai-zephyr.h
src/ipc/ipc-common.c
src/ipc/ipc3/dai.c
src/ipc/ipc4/dai.c
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

The main goal of this PR is to update the algorithm of pipeline latency calculation. It is based on the number of buffered data blocks between the first and last component.
For this purpose, I have added a new function to the component's api that allows to read the total number of processed data by it. Then, I introduced total_data_processed counter in dai_data and host_data structure. The counters of processed data has been moved from a component device structure to the components private data. Finally I removed the position field from comp_dev structure which become unused. This field was ambiguous - it was not known whether it mean consumed or produced data. I added a similar processed data counters to the Copier module.
In the future, the stamping of start and stop of the pipe will be …

dai: host: copier: component: New pipeline latency calculation algorithm

---

src/audio/module_adapter/module/volume/volume.c

With the module conversion the parameter 'dev' of most function changed to
'mod', update the doxygen comment to generate correct information.

volume: Update outdated function parameter documentation

---

src/audio/CMakeLists.txt
src/audio/copier/CMakeLists.txt
src/audio/copier/copier.c
src/audio/copier/copier_generic.c
src/audio/copier/copier_hifi.c
src/include/ipc4/copier.h
zephyr/CMakeLists.txt

add hifi version implementation of apply_attenuation, using xtensa
instructions can save about 74% cycles than the original one.

Audio: copier: add hifi version implementation of apply_attenuation

---

tools/topology/topology2/cavs/CMakeLists.txt

This is cavs-passthrough-hda-4ch-mtl.tplg, which is already in the CMakLists.txt
This is new topology from this PR, cavs-mixin-mixout-hda-4ch-mtl.tplg
I tested with Realtek AIOC40, ALC256 HDA codec.

Add mixer based hda topology for MTL

---

src/drivers/intel/ssp/ssp.c
src/include/ipc/dai-intel.h
src/include/kernel/abi.h
src/include/sof/drivers/ssp.h
tools/topology/topology1/platform/common/ssp.m4
tools/topology/topology1/sof-jsl-rt5682.m4

We've got an issue report that there is pop noise when audio is paused on Chrome JSL chromebooks. After triage, the root cause is the commit d5840a920 ("ssp: move mclk request/release to pre_start and post_stop"). In the earliest design, mclk is enabled in set_config() function and not disabled. The commit changed the behavior and turns on the mclk only when there is audio playback/capture running.
I tried to enable the early mclk feature but it doesn't work. Codec vendor says "MCLK need turned on before power on codec function and turned off after power off codec function." which means the mclk needs to keep toggling when there is I2C activity. The early mclk disables the clock at hw_free which seems to be still too early.
In this PR I add the always-on function back as a feature. In …

Implement mclk always on feature

---

src/audio/codec_adapter/codec/waves.c

Change the buffer size of waves_codec from 2ms to SCHEDULE_PERIOD
(Please refer to https://github.com/thesofproject/sof/pull/5851)

codec_adpater: change the buffer size of waves_codec

---

src/ipc/ipc4/handler.c

The condition statement is wrong in set_pipeline_state() when handling
SOF_IPC4_PIPELINE_STATE_RESET cmd.

ipc4: Fix wrong condition statement in set_pipeline_state

---

src/audio/aria/aria.c
src/audio/asrc/asrc.c
src/audio/copier/copier.c
src/audio/mixin_mixout.c
src/audio/module_adapter/module_adapter.c
src/audio/pipeline/pipeline-graph.c
src/audio/src/src.c
src/audio/up_down_mixer/up_down_mixer.c
src/include/ipc4/copier.h
src/include/sof/audio/aria/aria.h
src/include/sof/audio/component.h
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/audio/up_down_mixer/up_down_mixer.h
src/include/sof/audio/volume.h
src/ipc/ipc4/helper.c

Just copy the entire mailbox into the confid data for IPC4.

module_adapter: Add support for IPC4 in module_adapter_new

---

src/audio/module_adapter/iadk/iadk_module_adapter.cpp
src/audio/module_adapter/iadk/module_initial_settings_concrete.cpp
src/audio/module_adapter/iadk/system_agent.cpp
src/audio/module_adapter/iadk/system_service.c
src/audio/module_adapter/module/iadk_modules.c
src/include/sof/audio/module_adapter/iadk/adsp_error_code.h
src/include/sof/audio/module_adapter/iadk/adsp_stddef.h
src/include/sof/audio/module_adapter/iadk/fixed_array.h
src/include/sof/audio/module_adapter/iadk/iadk_module_adapter.h
src/include/sof/audio/module_adapter/iadk/logger.h
src/include/sof/audio/module_adapter/iadk/module_initial_settings.h
src/include/sof/audio/module_adapter/iadk/module_initial_settings_concrete.h
src/include/sof/audio/module_adapter/iadk/processing_module_factory_interface.h
src/include/sof/audio/module_adapter/iadk/processing_module_interface.h
src/include/sof/audio/module_adapter/iadk/processing_module_prerequisites.h
src/include/sof/audio/module_adapter/iadk/system_agent.h
src/include/sof/audio/module_adapter/iadk/system_agent_interface.h
src/include/sof/audio/module_adapter/iadk/system_error.h
src/include/sof/audio/module_adapter/iadk/system_service.h
src/include/sof/audio/module_adapter/iadk/utilities/array.h
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/audio/module_adapter/module/iadk_modules.h
src/include/sof/audio/module_adapter/module/module_interface.h

Intel module adapter is an extension to SOF module adapter component that allows to integrate
modules developed under IADK (Intel Audio Development Kit) Framework. IADK modules uses uniform
set of interfaces and are linked into separate library. These modules are loaded in runtime
through library_manager and then after registration into SOF component infrastructure are
interfaced through module adapter API.
There is variety of modules developed under IADK Framework by 3rd party vendors. The assumption
here is to integrate these modules with SOF infrastructure without modules code modifications.
Another assumption is that the 3rd party modules should be loaded in runtime without need
of rebuild the base firmware.
Therefore C++ function, structures and variables definition are here kept …

Intel modules adapter implementation

---

src/audio/dai-zephyr.c

Fill in cfg.rate to be used by zephyr native drivers as rate is not
always present in ipc config. 
Needed for zephyr-side pr: https://github.com/zephyrproject-rtos/zephyr/pull/48254

dai-zephyr: Set dai rate in config

---

src/audio/pcm_converter/pcm_converter_hifi3.c

Deprecated the usage of circular buffer check while doing convert, and
use 2-way and 4-way xtensa instructions to optimize the converter
functions. Here are the results:
Optimize pcm_convert_s16_to_s24 and save about 38% cycles;
Optimize pcm_convert_s24_to_s16 and save about 23% cycles;
Optimize pcm_convert_s16_to_s32 and save about 39% cycles;
Optimize pcm_convert_s32_to_s16 and save about 36% cycles;
Optimize pcm_convert_s32_to_s24 and save about 38% cycles;
Optimize pcm_convert_s24_to_s32 and save about 47% cycles;

Audio: Pcm_converter: Optimize the signed type converter functions

---

src/audio/Kconfig
src/audio/module_adapter/Kconfig

Some config options are not correctly grouped up, instead showing up later than intended.
Old code:
```
[*] Module adapter
[ ] Use legacy component driver interface
Processing modules  --->
```
New code:
```
[*] Module adapter
Processing modules  --->
[ ] Use legacy component driver interface
```
Also, old code:
```
[*] Cadence codec
[*] Volume component
[ ]     Windows Fade shape volume transitions support
[*]     Linear ramp volume transitions support
[ ] Cadence codec wrapper (NEW)
[ ] Cadence AAC decoder (NEW)
[ ] Cadence BSAC decoder (NEW)
[ ] Cadence DAB decoder (NEW)
[ ] Cadence DRM decoder (NEW)
[ ] Cadence MP3 decoder (NEW)
[ ] Cadence SBC decoder (NEW)
[ ] Cadence VORBIS decoder (NEW)
[ ] Cadence SRC polyphase (NEW)
[ ] Passthrough codec
```
New code:
```
[*] Cadence codec
[ ] …
```

Kconfig visual fixes

---

src/audio/src/src_hifi4.c
zephyr/CMakeLists.txt

Add src_hifi4.c to sources when building with zephyr.
include util.h from zephyr for `MIN` macro

src: enable hifi4 optimized src build with zephyr

---

src/arch/xtos-wrapper/include/sof/drivers/timer.h
src/audio/kpb.c
src/drivers/dw/dma.c
src/drivers/generic/dummy-dma.c
src/drivers/imx/edma.c
src/drivers/imx/sdma.c
src/drivers/intel/baytrail/timer.c
src/drivers/intel/cavs/timer.c
src/drivers/intel/haswell/timer.c
src/drivers/intel/hda/hda-dma.c
src/idc/idc.c
src/include/sof/lib/perf_cnt.h
src/ipc/ipc3/handler.c
src/lib/agent.c
src/lib/pm_runtime.c
src/lib/wait.c
src/probe/probe.c
src/samples/audio/kwd_nn_detect_test.c
src/schedule/dma_multi_chan_domain.c
src/schedule/dma_single_chan_domain.c
src/schedule/ll_schedule.c
src/trace/trace.c
zephyr/include/sof/drivers/timer.h
zephyr/wrapper.c

With Zephyr, SOF uses k_cycle_get_64() API in order to
count clock cycles.
Not all platforms have a 64bit counter (e.g i.MX dsp integration
only has xtensa timer which is limited to 32 bits).
So, instead of using k_cycle_get_64 introduce new API sof_cycle_get_64
which keeps the existing behavior for platforms which define
CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER, otherwise use k_uptime_ticks().
See comments from @andyross at
https://github.com/zephyrproject-rtos/zephyr/pull/48318
Suggested-by: Andy Ross <andrew.j.ross@intel.com>

timer: Introduce sof_cycle_get_64

---

submanifests/sof-ci-jenkins/zephyr-override-template.yml

This file provides the flexibility to test any Zephyr commit in Linux
CI without any pollution of `git -C sof describe --dirty`. See (too)
long discussion in #6005 for details.
This new file will have no effect until #6005 is merged. However it can
and SHOULD be merged before #6005 because #6005 is backwards
incompatible and requires a "flag day" and the synchronization of
several moving parts. So merging this commit earlier means having one
less moving part to synchronize and it will simplify "flag day"
rehearsals.

Add new submanifests/sof-ci-jenkins/zephyr-override.yml

---

src/audio/rtnr/rtnr.c

Commit b832e96b664c ("rtnr: fix buffer acquisition") got damaged during a rebase, re-add the dropped part, fixing buffer acquisition in rtnr_prepare().
This should also replace #6057

rtnr: fix a bad commit

---

src/audio/pipeline/pipeline-graph.c
src/audio/pipeline/pipeline-stream.c
src/include/sof/audio/pipeline.h

**Description of the problem**
We would like to get the number of decompressed frames using `dai_posn`. At the moment, adding the following code to
`sof_compr_pointer` (found at `sound/soc/sof/compress.c`):
```
tstamp->pcm_io_frames = spcm->stream[cstream->direction].posn.dai_posn / 8;
```
will not work because `dai_posn` is not updated (it's always 0). This is because of the way `pipeline_for_each_comp` (found at
`src/audio/pipeline/pipeline-graph.c`) and `host_dma_cb` (found at `src/audio/host-legacy.c`) work.
`pipeline_for_each_comp` sets the `walking` flag of each of the component buffers to `true` as it traverses them and then sets it back to `false` when the traversal is done.
`host_dma_cb` calls `host_update_position` which in turn calls `pipeline_get_timestamp` after some host …

Get updated dai posn

---

src/audio/mixin_mixout.c
src/include/ipc4/mixin_mixout.h

Add possibility to apply gain to mixed sources to avoid
mixed output saturation. Gain (attenuation) is configurable
per source and comes from host via IPC4 large config set.

ipc4: add mixin gain support

---

src/ipc/ipc4/handler.c

If operation of disabling secondary core fails at any of the steps, host
will only learn about it after checking the SPA/CPA bits.
This patch adds checking core state after it disabling. If core will be
still active ipc response will report error.
Additionally, it removes an outdated comment.

ipc4: setdx: error checking on core disabling

---

tools/logger/logger.c

See commit messages.
Fixes a small part of thesofproject/linux#3275
~Draft until it's been tested more.~ I used this for months

logger: allow starting before the driver is loaded

---

src/audio/rtnr/rtklib/tgl/CMakeLists.txt
src/audio/rtnr/rtklib/tgl/README.txt

With the version released in 20220728, some libraries are removed or renamed.

RTNR: Modify used static libraries

---

.github/workflows/zephyr.yml
scripts/xtensa-build-zephyr.py
submanifests/README.txt
west.yml
zephyr/docker-build.sh

To use it please install: `pip3 install --user -U west`
- You may now clone SOF project without git using west init <SOF_URL> command (well... after this PR is merged).
- If you already cloned SOF using git, run command `west init -l <SOF_DIR>` to use west
- You may also use xtensa-build-zephyr.py convenience script that will do this for you
- Executing command `west update` will cause to download SOF dependencies (previously submodules) and zephyr along with dependencies required for SOF platforms building and testing (except modules/audio/sof - we don't need another SOF copy!)
- If you are **not** using xtensa-build-zephyr.py when building with Zephyr, you need to manually create a symlink for Zephyr:
`ln -s ./modules/audio/sof ./sof ` (run in _~/workspace/my_sof_workspace_ see …

[SKIP CI] Use west manifest in SOF

---

installer/GNUmakefile
installer/tests/staging_sofIPC4_ref.txt
installer/tests/staging_sof_ref.txt

rpl firmware is tgl but signed with a different key
This commit adds the following files and links below
```
$ tree installer/staging/sof |
grep -e tgl  -e rpl -e community |
grep -v -e adl -e ehl
├── community
│   ├── sof-rpl.ri -> sof-tgl.ri
│   ├── sof-rpl-s.ri -> sof-tgl-h.ri
│   ├── sof-tgl-h.ri
│   └── sof-tgl.ri
├── sof-rpl.ldc -> sof-tgl.ldc
├── sof-rpl.ri -> intel-signed/sof-rpl.ri
├── sof-rpl-s.ldc -> sof-tgl-h.ldc
├── sof-rpl-s.ri -> intel-signed/sof-rpl-s.ri
├── sof-tgl-h.ldc
├── sof-tgl-h.ri -> intel-signed/sof-tgl-h.ri
├── sof-tgl.ldc
└── sof-tgl.ri -> intel-signed/sof-tgl.ri
```

installer: add rpl and rpl-s aliases to tgl and tgl-h

---

west.yml
zephyr/docker-build.sh

2 commits, main one:
Restore ability to use (and test!) zephyr/docker-build.sh locally
without overwriting work in progress.
Fixes commit https://github.com/thesofproject/sof/commit/b371373f7d7486014ea7d80a5836d8958f3d93a9 ("scripts: docker-build.sh updated with
changes from xtensa-build-zephyr.py")

docker-build.sh: don't switch versions when already initialized

---

src/audio/src/src.c

This reverts commit 3aff4598f7ebd79d8cfb0398d85a85bbf4ba37e1.
This commit causes i.MX pipelines that convert from 44.1khz to 48khz to
freeze, when the firmware is compiled with Xtensa toolchain.

Revert "Audio: SRC: Increase length of internal buffer"

---

.github/workflows/zephyr.yml

It's faster like this and we also want platform-specific failures to be
identify as such and not block compilation of other platforms.
Also removed obsolete comment that sneaked in previous commit by
mistake and remove duplicate "zephyr" in the job name

[SKIP CI] .github/zephyr.yml: separate platforms a bit

---

src/audio/pcm_converter/pcm_converter_hifi3.c
src/include/sof/audio/pcm_converter.h

Use hifi3 instructions implement new format conversion functions
of pcm_func_vc_map. Keep pcm_convert_s24_c32_to_s24_c24_link_gtw
as C version, since there are still some bugs. Will implement this
function after those bugs fixed as the original assumption of author.

Audio: Pcm_converter: add hifi3 version new functions

---

src/platform/imx8/lib/clk.c
src/platform/imx8m/lib/clk.c

After Zephyr commit:
855216f582d2 ("kconfig: default to LEGACY_INCLUDE_PATH=n")
we get a compile time error because legacy include paths are not
supported by default.
Fix this by adding 'zephyr/' prefix in proper places.

imx: clk: Fix zephyr header include

---

west.yml

Update zephyr to commit 8e55e59c5917 ('arch: introduce config DCLS').
Fixes build errors due to missing core-isa.h with tgl Intel target with
gcc build chain.

west: update to newer Zephyr baseline

---

.github/workflows/zephyr.yml

No functional change, this is a pure re-ordering of the matrix
parameters to put the shorter ones first which helps see more in narrow
columns like when looking as build logs on github.

[SKIP CI] .github/zephyr.yml: cosmetic matrix re-ordering

---

tools/topology/topology1/sof/pipe-codec-adapter-capture.m4
tools/topology/topology1/sof/pipe-codec-adapter-playback.m4
tools/topology/topology1/sof/pipe-eq-iir-codec-adapter-playback.m4
tools/topology/topology1/sof/pipe-host-codec-adapter-playback.m4

setup config data was removed with commit
5763c74bf408d ("codec_adapter: Remove setup config from module data")
update documentation to reflect this.

topology: Fix setup control bytes comments

---

src/probe/probe.c

Register logging module for probe.

probe: support Zephyr logging subsystem

---

src/probe/probe.c

probe: fix compiler warning on uninitialized data in probe_gen_format()
Compiler emits a warning about possibly uninitialized use of valid_bytes
and container_bytes. Add an explicit return that covers this case.
The code has a "assert(false)" statement already, but this is not
sufficient and the compiler rightly warns about this.

 probe: fix compiler warning on uninitialized data in probe_gen_format()

---

src/audio/host-legacy.c
src/audio/host-zephyr.c
src/audio/src/src.c
src/drivers/intel/hda/hda-dma.c
src/include/sof/lib/dma.h
src/ipc/ipc-helper.c
src/ipc/ipc4/helper.c

1 memory allocation optimisation, some list manipulation improvements and misc. minor improvements

several cosmetic, simplification and optimisation patches

---

src/drivers/intel/Kconfig
test/cmocka/CMakeLists.txt

NUMBERS_GCD was removed in commit 9611d126ba5. We should not be
selecting or buildign with an undefined Kconfig.

kconfig: remove undefined kconfig NUMBERS_GCD

---

tools/topology/topology1/sof-apl-pcm512x.m4

This patch allows to test SRC with all 16/24/32 bit formats
in UP-squared device. Without this patch only 16 bit is
supported.

Topology1: Allow S24_4LE and S32_LE playback with PCM4

---

src/audio/src/src.c

The stream format info is useful for debugging SRC issues so it
is added to comp_info() trace print.
The blk_in and blk_out are at this code location always zeros so
the comp_info() to trace them is unnecessary.

Audio: SRC: Cleanup traces in src_params()

---

src/drivers/amd/renoir/acp_dmic_dma.c

(cherry-picked from amd_rn_dts branch, which is maintained by AMD)
while simultaneous playback and internal mic capture usecases
are running, there is a case where dmic driver was clearing the
playback interrupt.This might cause noise in playback or no audio
in speaker.Done changes to clear only dmic interrupt status only
in dmic irq handler.

drivers: amd: renoir: Fix no audio issue.

---

scripts/docker_build/sof_builder/Dockerfile

Add AMD/Rembrandt (rmb) gcc toolchain to thesofproject/sof docker image.

[SKIP CI] docker: add AMD/Rembrandt gcc toolchain

---

.github/workflows/pull-request.yml

SOF Docker image supports AMD/Rembrandt gcc toolchain from tag 20220809,
which is latest as of now.

[SKIP CI] .github: add rmb to gcc build only platform

---

src/ipc/ipc-common.c

No reason for ipc_get_ppl_comp() to only look for components on the same core as where it is running, same pipeline components can run on different cores too.
With this I was able to modify a playback pipeline with a PGA as its sink, connecting to a mixer in another pipeline, to run that PGA on a different core.

[RFC] ipc: find components on other cores too

---

src/audio/mixin_mixout.c

find_mixout_source_info() can return NULL, always check return value before dereferencing.
Partially fixes #6118 - no more firmware crash, but the error has to be fixed too.

mixin-mixout: fix a firmware exception

---

scripts/xtensa-build-zephyr.py

West tool returns on windows OS different white characters
than on Linux OS. Paths outputted from west tool had been
stripped for any trailing whitespaces.

scripts: xtensa-build-zephyr.py fix for windows

---

src/audio/buffer.c
src/include/sof/audio/buffer.h
src/probe/probe.c

Avoid deadlocks by passing locked buffers to probes

Probes: pass locked buffers

---

src/audio/mixin_mixout.c

.bind() is called twice, in the order this is currently done in SOF, the second call overwrites with 0 the valid configuration from the first call. Remove that overwrite.

Mixin: fix binding

---

tools/probes/probes_main.c

Series of patches to add non-audio probe buffer support (and few minor fixes).

probe-app: add support for non-audio probe buffers

---

src/include/ipc/probe.h
src/include/kernel/abi.h
src/include/sof/probe/probe.h
src/logging/Kconfig
src/logging/log_backend_probe.c
src/probe/probe.c
src/trace/Kconfig
zephyr/CMakeLists.txt

probe logging: add backend for logging via probes
Work in progress code that routes Zephyr logs via the logging
subsystem to SOF probe extraction point.
Lot of hardcodes still in this version, but this is tested to work
with Linux SOF driver, crecord and sof/tools/probes for decoding.
Example usage in Linux:
term1# crecord -c3 -d0 -b8192 -f4 -FS32_LE -R48000 -C4 /tmp/extract.dat
term2# echo 0,3,0 > /sys/kernel/debug/sof/probe_points
term1# <terminate crecord>
term1# sof-probes -p /tmp/extract.dat
term1# cat buffer_999999.wav

probe: add backend for logging via probes

---

src/audio/module_adapter/module/waves.c

The scheduling period should be acquired from dev->pipeline->period

module_adpater: correct the way to get the scheduling period

---

tools/topology/topology1/development/CMakeLists.txt
tools/topology/topology1/development/sof-imx8-compr-pcm-cap-wm8960.m4
tools/topology/topology1/development/sof-imx8-compr-pcm-wm8960.m4
tools/topology/topology1/development/sof-imx8mp-compr-pcm-cap-wm8960.m4
tools/topology/topology1/development/sof-imx8mp-compr-pcm-wm8960.m4
tools/topology/topology1/m4/pcm.m4

The purpose of this series of patches is to introduce new topologies that make use of the compress API in order to play/capture using the PCM format. This is mostly used to test the compress API.

Add new topologies for PCM capture/playback using compress API

---

src/audio/rtnr/rtnr.c

This PR enables RTNR processing by default and keeps its value while the recording is finished.
Since rtnr_reset() will be called once recording is finished, the value of process_enabled should not be changed in this function. 
Otherwise every new recording will start with the value set in rtnr_reset() and it should be an incorrect behavior.

rtnr: Set process_enabled by default and keep its value in rtnr_reset() 

---

src/audio/mixin_mixout.c
src/include/sof/audio/buffer.h
src/include/sof/coherent.h

buffer_release() and coherent_release() don't need to return any value, make them return void

make buffer_release() and coherent_release() return void

---

src/audio/kpb.c
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module/iadk_modules.c
src/audio/module_adapter/module/volume/volume.c
src/audio/module_adapter/module_adapter.c
src/include/sof/audio/component.h
src/include/sof/ipc/topology.h
src/platform/imx8ulp/include/platform/lib/cpu.h

2 commits, main one:
Disable some invalid doxygen comment blocks
Simply replace `/**` with `/*`. This can be very easily reverted if
someone ever fixes the corresponding comment.
We don't build doxygen for .C files in continuous integration, only for
.H files. We don't build doxygen for .C files in continuous integration
because there are way too many errors and no one has time to fix
them. Because we never build doxygen for .C files, people keep adding
untested and invalid doxygen comments or they change the code while
leaving the doxygen out of sync.
I build doxygen for .C files locally. The call graphs are especially
useful (they don't need doxygen comments). I have local hacks to filter
out the most common doxygen errors. The broken doxygen comments disabled
by this commit escaped my …

Disable some invalid doxygen

---

tools/topology/topology2/CMakeLists.txt

Fixes: #5323
The v1.2.6 requirement was a lie the whole time because alsatplg v1.2.6
does not have any `-I` option. The truth was: un-released alsa-utils
from git was required. The check for v1.2.6 was an approximation good
enough for many users but not for everyone, see for instance #5323.
Now that alsa-utils v1.2.7 has been released we can stop lying:
https://github.com/alsa-project/alsa-utils/commit/7d934f3142549

topology2: build only when alsatplg is v1.2.7 or greater

---

src/audio/dai-zephyr.c
src/include/sof/lib/dai-zephyr.h
src/lib/dai.c

Fix a confusion between device and driver.

dai-zephyr: rename a device pointer to "dev"

---

src/audio/codec_adapter/codec/waves.c

Scheduling period should be acquired from dev->pipeline->period

codec_adapter: correct the way to get the scheduling period

---

src/audio/rtnr/CMakeLists.txt
src/audio/rtnr/rtklib/mt8195/CMakeLists.txt
src/audio/rtnr/rtklib/mt8195/README.txt
src/audio/rtnr/rtklib/tgl/CMakeLists.txt
src/audio/rtnr/rtklib/tgl/README.txt
src/audio/rtnr/rtnr.c

This PR merges back following RTNR related commits from main to adl-004-drop-stable
39e99ac69734002b9cc3d36c03913a4b5f06dd21 [Rtnr: Clean up state on component reset](https://github.com/thesofproject/sof/commit/39e99ac69734002b9cc3d36c03913a4b5f06dd21)
605c6662712655adc2ca417b639c1a1523468920 [rtnr: passthrough audio by stream copy](https://github.com/thesofproject/sof/commit/605c6662712655adc2ca417b639c1a1523468920)
5c3594afe8b99aeed6dd845099408655130f8b0f [rtnr: Set process_enabled by default and keep its value in rtnr_reset()](https://github.com/thesofproject/sof/commit/5c3594afe8b99aeed6dd845099408655130f8b0f)
05bd87da37092e8db0d741b6595a6eb9e7a29ffb [Add RTNR library path for MT8195](https://github.com/thesofproject/sof/commit/05bd87da37092e8db0d741b6595a6eb9e7a29ffb) …

rtnr: cherry-pick to sync with latest version on main branch

---

scripts/xtensa-build-zephyr.py

xtensa-build-zephyr.py: require python 3.8

---

src/audio/copier/copier_hifi.c

Add log definition for Zephyr allowing to build this module
for Zephyr when logging is enabled.

copier_hifi: fix Zephyr logging

---

src/audio/module_adapter/module_adapter.c

At present module_adapter, period_bytes is calculated assuming the schedule period is 1ms, which could be arbitrary in practice determined by the topology.
This commit replaces the present calculation by audio_stream_period_bytes(). In addition, the timing for getting period_bytes is moved to the beginning of prepare() (prior to the module prepare). At that moment it is guaranteed that all parameters in components/buffers are settled through the pipeline.

module_adapter: get the actual period_bytes

---

src/lib/alloc.c

This causes problems when displaying heap traces.
Fixes: b67c2bf0d9732 ("alloc: Making heap trace dump more readable")

lib: alloc: Add missing format specifier

---

src/audio/copier/copier.c

The parameters audio_fmt.depth and audio_fmt.valid_bit_depth are
expressed in bits. Therefore should be divided by 8 when set for params:
params->sample_container_bytes
params->sample_valid_bytes

Audio: copier: Fix copier params setting

---

src/audio/CMakeLists.txt
src/audio/mixer/CMakeLists.txt
src/audio/mixer/mixer.c
src/audio/mixer/mixer_generic.c
src/audio/mixer/mixer_hifi3.c
src/include/sof/audio/mixer.h
test/cmocka/src/audio/mixer/CMakeLists.txt
zephyr/CMakeLists.txt

Add hifi3 & hifi4 version implementation of mixer processing functions.
The hifi version functions can save at least 47% cycles than C version.

Audio: Mixer: Add hifi version processing functions for mixer

---

src/drivers/imx/edma.c
src/drivers/imx/sai.c
src/drivers/imx/sdma.c

Currently, when we're trying to pause and then resume a stream we get an error message from the FW saying that a `comp_trigger()` operation failed. This was caused by the fact that `edma_release` would set the channel state to COMP_STATE_ACTIVE and `edma_start` would not allow the transition from that state.
In order to fix this, `edma_release` now changes the state to COMP_STATE_PRE_ACTIVE and `edma_start` allow the transition from COMP_STATE_PRE_ACTIVE to COMP_STATE_ACTIVE. This way, the EDMA states will be consistent with the comp state diagram found at https://thesofproject.github.io/latest/architectures/firmware/components/component-overview.html.
Another problem with `edma_start` was the fact that it was allowing the transition from COMP_STATE_SUSPEND to COMP_STATE_ACTIVE which is …

Fix pause-release not working on i.MX

---

src/audio/codec_adapter/codec/waves.c

Fixed by removing invalid characters.

codec_adpater: fix stray errors

---

src/audio/rtnr/rtklib/mt8195/CMakeLists.txt
src/audio/rtnr/rtklib/mt8195/README.txt

With the version released in 20220809, some libraries are removed or renamed.
This PR modifies the used libraries for MT8195 platform.

rtnr: Modify used static libraries for MT8195

---

src/audio/selector/selector.c
src/audio/selector/selector_generic.c
src/include/sof/audio/selector.h
test/cmocka/src/audio/selector/selector_test.c
zephyr/wrapper.c

Although this patch doesn't support large_config_set|get and
corresponding per-channel process, it can support simple usage
of selector and support capture applications like voice recoder,
zoom on windows platform. It will be used for WOV development
in recently.

ipc4: add basic ipc4 support in selector

---

src/platform/imx8/include/platform/lib/memory.h
src/platform/imx8m/include/platform/lib/memory.h
src/platform/imx8ulp/include/platform/lib/memory.h

Ideally PLATFORM_DCACHE_ALIGN should be equal with DCACHE_LINE_SIZE,
but on i.MX dcache line size is 128 and it is too big for XTOS based
memory allocator.
See commit 8354454b4df0 ("platform: imx: Fix PLATFORM_DCACHE_ALIGN")
On the other hand the current value which is 4 doesn't work well with
Zephyr.
So, increase the PLATFORM_DCACHE_ALIGN to 32 which works well for XTOS /
Zephyr.

platform: imx: Set PLATFORM_DCACHE_ALIGN to 32

---

.github/workflows/pull-request.yml

Upgrade to Ubuntu 22 VM.
Stop building test topologies in docker, not required anymore.
Add ALSA headers to help with topology re-org #6009

[SKIP CI] .github actions: testbench clean up

---

src/audio/module_adapter/module_adapter.c
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

IPC4 SOF_IPC4_MOD_INIT_INSTANCE provides size of the configuration
blob for the module. This size should be passed down to module adapter
and forwarded to module.
There are several reasons for using it:
- consistency with IPC3 flow;
- need for passing the size to IADK loadable modules;
- possibility to graceful failure in case of configuration inconsistency.

module adapter: pass config size to module for ipc4

---

src/audio/base_fw.c
src/include/ipc4/base_fw.h

The ADSP properties are obsolete and not using by host driver so can be removed.
Signed-off-by: Damian Nikodem <damian.nikodem@intel.com>

ipc4: remove report dsp properties to host driver

---

tools/topology/topology1/CMakeLists.txt

Remove mt8186 unused topologies.
We use sof-mt8186 on our demo board, sof-mt8186-mt6366-rt1019-rt5682s
and sof-mt8186-mt6366-da7219-max98357 will no be used anymore.
Signed-off-by: Chunxu Li <chunxu.li@mediatek.com>

topology1: remove mt8186 unused topologies

---

src/audio/mixin_mixout.c

In mixout_prepare() mixin->pipeline can be NULL, check it before dereferencing.
Fixes the second part of #6118

mixin: fix a NULL dereference

---

src/audio/copier/copier_hifi.c

This reverts commit a0b832686cfdacb5b2d61f7002aa41b210d215db.
There was a PR merge "conflict" as the log defines we're in different
place in the file. This same log define was already added in commit:
2c4e403d4d680ecfb31aaa493b88b12389125584
So remove the duplicate.

Revert "copier_hifi: copier logging fix"

---

src/audio/pipeline/pipeline-stream.c
src/audio/selector/selector.c
src/include/sof/audio/pipeline.h

Usually when processing COMP_TRIGGER_PAUSE or COMP_TRIGGER_STOP if a component returns PPL_STATUS_PATH_STOP it means, that the trigger propagation should stop and the pipeline should be kept alive. However, in some cases propagation should be stopped, but the pipeline should be terminated. This is the case with the selector component, when used in a keyword detection pipeline. Add a new PPL_STATUS_PATH_TERMINATE return value for such cases.

pipeline: let selector terminate the pipeline when stopping

---

tools/topology/topology2/include/common/sink_pin_binding.conf
tools/topology/topology2/include/common/src_pin_binding.conf
tools/topology/topology2/include/common/tokens.conf
tools/topology/topology2/include/components/cavs/src.conf
tools/topology/topology2/include/components/copier.conf
tools/topology/topology2/include/components/gain.conf
tools/topology/topology2/include/components/mixin.conf
tools/topology/topology2/include/components/mixout.conf
tools/topology/topology2/include/components/widget-common.conf

- This PR adds the special pin binding support for multiple I/O queue.
- This PR is the official version of https://github.com/thesofproject/sof/pull/6000, which removes the test code.
- This PR has no impact on IPC3/IPC4 test.
- This PR should be merged before https://github.com/thesofproject/linux/pull/3757 to not break the IPC4 test.

topology2: add special pin binding support for multiple IO queue

---

src/audio/copier/copier.c

Fix compiler error related to endpoint field:
src/audio/copier/copier.c:662:13: error: the comparison will always
evaluate as 'true' for the address of 'endpoint' will never be
NULL [-Werror=address]
662 |         if (cd->endpoint) {
|             ^~
src/include/ipc4/copier.h:325:26: note: 'endpoint' declared here
325 |         struct comp_dev *endpoint[IPC4_COPIER_MODULE_OUTPUT_PINS_COUNT];

audio: copier: fix always-true comparison in copier_comp_trigger

---

src/arch/xtensa/Kconfig
src/platform/Kconfig

At the moment `CONFIG_INCOHERENT` is automatically enabled when `CONFIG_TIMERLAKE` is set and cannot be switched from menuconfig. Enable that to make debugging with limited cache use possible.
To debug with cached access only enabled for stack and read-only data, unselect `CONFIG_INCOHERENT` and `CONFIG__SOF_ZEPHYR_HEAP_CACHED`

coherent: make CONFIG_INCOHERENT selectable from menuconfig

---

src/audio/selector/selector.c

comp_dbg() statements may be compiled out, so having a 'dev'
variable just for debugs is not useful and just ends up with
compiler warnings on unused variables.

selector: fix compiler warnings on unused 'dev'

---

CMakeLists.txt
scripts/checkpatch.pl
scripts/cmake/git-submodules.cmake

Note this change does NOT affect Zephyr builds in any shape or form as
Zephyr builds simply don't use the CMake files changed by this commit.
Downloading missing submodules at build time was never a good idea;
always a hack. Downloading and building should always be kept separate
from each other for version control and bill of materials reasons and to
support "off-line" builds; build inputs should always be available.
Now that Zephyr builds have just moved away from git submodules
(replaced by west), stop sneakily downloading missing submodules at
build time while the user cannot notice, overwhelmed by the volume of
build logs. Someone building XTOS first and Zephyr second could
unknowningly end up in a "hybrid" and undesired situation where git
submodules and west would be BOTH pointing …

cmake: stop sneakily downloading missing submodules at build time

---

src/audio/mixin_mixout.c
src/include/ipc4/mixin_mixout.h

Adds channel remapping feature support to mixin/mixout.

ipc4: add mixin/mixout channel remapping support

---

src/audio/rtnr/rtklib/mt8195/CMakeLists.txt
src/audio/rtnr/rtklib/mt8195/README.txt
src/audio/rtnr/rtklib/tgl/CMakeLists.txt
src/audio/rtnr/rtklib/tgl/README.txt
src/audio/rtnr/rtnr.c

This PR merges back following RTNR related commits from main to mt8195/v0.4
f781a0b554be2d81511db02ee835f5c325ad3253 [Modify used static libraries](https://github.com/thesofproject/sof/commit/f781a0b554be2d81511db02ee835f5c325ad3253)
39e99ac69734002b9cc3d36c03913a4b5f06dd21 [Rtnr: Clean up state on component reset](https://github.com/thesofproject/sof/commit/39e99ac69734002b9cc3d36c03913a4b5f06dd21)
5c3594afe8b99aeed6dd845099408655130f8b0f [rtnr: Set process_enabled by default and keep its value in rtnr_reset()](https://github.com/thesofproject/sof/commit/5c3594afe8b99aeed6dd845099408655130f8b0f)
0b18ca82ac0b13f49701b5f47d9b12d974a7ddc9 [rtnr: Modify used static libraries for MT8195](https://github.com/thesofproject/sof/commit/0b18ca82ac0b13f49701b5f47d9b12d974a7ddc9) …

rtnr: cherry pick to sync mt8195/v0.4 branch with latest version on main

---

src/include/ipc4/module.h
src/include/ipc4/notification.h
src/include/sof/lib_manager.h
src/include/sof/sof.h
src/ipc/ipc-common.c
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c
src/library_manager/CMakeLists.txt
src/library_manager/Kconfig
src/library_manager/lib_manager.c
src/library_manager/lib_notification.c

Library manager is part of loading external libraries responsible of
handling data and placing it in proper order and places.
After receiving IPC4 load library command
- reads manifest
- after module_id choses module to load and verify it (WIP)
- loads manifest
- allocs propper memory size
- transfer module from IMR to HPSRAM (WIP)
Signed-off-by: Stelter, Jaroslaw <jaroslaw.stelter@intel.com>
Signed-off-by: Dobrowolski, PawelX <pawelx.dobrowolski@intel.com>

library manager: initial implementation

---

src/audio/module_adapter/module/volume/volume.c

The parameters px and py in
Q_MULTSR_32X32(px, py, qx, qy, qp) function
must be cast to (int64_t) if other type.
Signed-off-by: Arsen Eloglian <ArsenX.Eloglian@intel.com>

volume: cast function parameters to (int64_t)

---

tools/test/topology/tplg-build.sh

The xargs option `-I/--replace` hardcodes max lines `-L 1`. In other
words, it always splits the input line by line and ignores whitespace
delimiters inside each line. Initial xargs commit
d0f4aba9340d9 ("topology: speed up topology build") used `--replace`
after `-n/--max-args=1` which was silently ignored by xargs version
4.7.0. Now xargs 4.8.0 prints the following warning:
xargs: warning: options --max-args and --replace/-I/-i are mutually
exclusive, ignoring previous --max-args value
Remove the ignored `-n 1` to remove the warning.
I compared the outputs before and after this commit and they're exactly
the same.
There's an extra twist. The same xargs command also uses the
`-d/--delimiter=,` option which makes xargs ignore newlines and
"translates" any max-line `-L` option to …

test/tplg-build.sh: remove spurious xargs -n1 option

---

src/library_manager/lib_manager.c

Fix spinlock.h include path as in 1629a1f72c7b4c9f203dabbb83d361fbf2b5b9c5

library manager: fix outdated include path

---

scripts/docker-run.sh
zephyr/docker-run.sh

See commit messages.
Fixes recent #6232

[SKIP CI] Minor docker-run.sh fixes

---

scripts/test-repro-build.sh

Other platforms are not supported anymore in the main branch.

[SKIP CI] scripts/test-repro-build.sh: leave only TGL

---

src/audio/copier/copier.c

(1) ipc4: fix copier crash
Buffer params (like stream format) are usually setup by component's
params() handler. params() is called before pipeline start. When copier
is binded with component on another pipeline, it might happen that
copier copy() is already running while other component params() was not
yet executed (by other pipiline).
Processing buffer with uninitialized params usually leads to crash:
division by 0 channels when calculating frames.
(2) ipc4: fix copier set sink format handling
When gateway is copier's source, this should not prevent
from calling "set sink format" for sink pin 0.

ipc4: fix copier crash, fix copier set sink format handling

---

app/src/main.c
src/logging/log_backend_probe.c

The zephyr header zephyr.h should be only used with
CONFIG_LEGACY_INCLUDE_PATH, which is deprecate by both
Zephyr and SOF.
The latest zephyr main will complain if zephyr.h is
used but CONFIG_LEGACY_INCLUDE_PATH disabled.
This patch deprecates zephyr.h and uses kernel.h instead,
so that we don't break with latest zephyr.
```
In file included from /zep_workspace/sof/app/src/main.c:7:
/zep_workspace/zephyr/include/zephyr/zephyr.h:13:2: error: #warning "<zephyr/zephyr.h> is deprecated, include <zephyr/kernel.h> instead" [-Werror=cpp]
13 | #warning "<zephyr/zephyr.h> is deprecated, include <zephyr/kernel.h> instead"
|  ^~~~~~~
cc1: all warnings being treated as errors
```

zephyr: deprecate zephyr.h and use kernel.h header

---

src/ipc/ipc4/handler.c

Add logs for all inbound and outbound IPC messages using a similar
logging style as used by Linux SOF driver.

ipc4: add debug logs for RX/TX messages

---

src/audio/tdfb/tdfb.c
src/audio/tdfb/tdfb_direction.c
src/include/sof/audio/format.h

This patch adds to header file sof/audio/format.h two new macros
for 16 * 16 fractional multiply. It's identical to 32 bit but the
name suggests that operands are 16 bit where case to int32_t is
sufficient for the product.
- The calculation of cd->max_frames is changed use Q_MULTSR_16X16()
- Max_lag calculation is added type cast to int64_t though it does
not overflow with 48 kHz. But it could overflow with 96 kHz rate.
- A comment about 64 bit type is added to calculation of thr
- src_x and src_y calculation is done with Q_MULTSR_16X16()
- az_slow calculation is done with Q_MULTSR_16X16
- deg calculation is done with Q_MULTSR_16X16

Audio: TDFB: Fix suspicious looking Q_MULTSR_32X32 macro usage

---

src/include/sof/drivers/dmic.h

This patch adds cast to int64_t for the multiplication and adds 32 bit
saturation to ensure overflow of the product is not possible.
This function is used to calculate ramp time in IPC4 NHLT blob mode
where the time is not passed from topology. Currently rates up to
48 kHz remain under product int32_t range, so normally there is no
issue. However 96 kHz rate would always result to incorrect
LOGRAMP_TIME_MIN_MS (10 ms).

Drivers: DMIC: Fix risk for overflow in unmute ramp calculation

---

zephyr/CMakeLists.txt

Add DRC files to Zephyr compilation to avoid failures like this:
sof/src/audio/drc/drc_generic.c:188: undefined reference to
`drc_lin2db_fixed'

zephyr: Fix DRC module compilation

---

src/ipc/ipc4/handler.c
src/ipc/ipc4/logging.c

Subset of https://github.com/thesofproject/sof/pull/6243 with fixes that only affect IPC4 and Zephyr builds. If CI is clean, this can go in first and I'll rebase 6243 once the issues with XTOS is solved.

IPC4: mtrace fixes

---

src/audio/module_adapter/module/cadence.c
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module/passthrough.c
src/include/sof/audio/module_adapter/module/module_interface.h

Modify the definition of the reset API in the module adapter interface
to make sure that it should reset the module state back to
MODULE_INITIALIZED and free all memory that was allocated during the
prepare() callback. With this change, stopping and restarting streams
will always be guaranteed to invoke the module's prepare() callback.
Also, fix the passthrough and cadence codec implementation to follow the
new definition.
Fixes #6034

module_adapter: Modify reset API

---

src/audio/copier/copier.c
src/audio/mixin_mixout.c
src/ipc/ipc4/handler.c

This will fix cache issue when several messages were sent one after another

ipc4: invalidate cache for set large config message

---

src/audio/google_hotword_detect.c

Size parameter is moved from struct sof_ipc_reply to struct sof_ipc_cmd_hdr. Added changes accordingly.
Signed-off-by: Vamshi Krishna Gopal <vamshi.krishna.gopal@intel.com>

ghd: Fix build error for ghd

---

scripts/xtensa-build-zephyr.py

we will switch to using this new logging tool, copy it to the tools
folder, then it will be uploaded to CI storage after building.
Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

xtensa-build-zephyr.py: copy mtrace-reader.py to tools folder

---

src/audio/copier/copier.c

Running a pipeline with unbinded copier leads to memory corruption. Normally pipeline should not be started with unbinded components, however, this still can happen due to a bug in test or driver.

ipc4: fix memory corruption when running unbinded copier

---

src/audio/mixin_mixout.c

Fix two bugs with cache handling, this fixes the check-capture test on UP-Xtreme-i11

Mixin-mixout: fix cache handling

---

.github/workflows/installer.yml
installer/GNUmakefile
installer/tests/staging_sofIPC4_ref.txt
installer/tests/staging_sof_ref.txt
scripts/xtensa-build-all.sh

Clean cherry-picks.
Required for 2.3 release.

[stable-v2.3] scripts: remove byt-jsl from default builds

---

src/schedule/zephyr_ll.c

SOF always tries to register both scheduling domains - timer and DMA, even though the DMA domain isn't used in current topologies on newer architectures and isn't supported under Zephyr. Degrade the error message printed upon each boot due to this lack of support to a warning.

ll-schedule: degrade an error message to a warning

---

src/include/sof/coherent.h

arch_is_in_isr() is not an exported function. Use k_is_in_isr() instead.

coherent: fix building with CONFIG_ASSERT=y

---

src/audio/module_adapter/module/volume/volume.c

With IPC4 volume_set_config() is called from module_set_large_config() with the host mailbox used as a configuration source. Data there is written by the host, therefore any DSP cache contents for that area is invalid. volume_set_config() does invalidate local cache for that area but it's doing it too late - after calling module_set_configuration() which already reads the data. This leads to sporadic wrong configuration readings. Move cache invalidation before module_set_configuration() to fix that.

volume: fix cache invalidation in volume_set_config()

---

src/audio/dai-zephyr.c
src/lib/dai.c

This patch will add support for DAI_INTEL_HDA
in dai-zephyr like in legacy dai

dai-zephyr: add support for DAI_INTEL_HDA

---

app/prj.conf
src/include/sof/ipc/common.h
src/ipc/ipc-common.c
zephyr/wrapper.c

After realizing we have a competing "TX sender" in zephyr/wrapper.c, I've modified the approach in #6243 . This takes benefit of the Zephyr CONFIG_SCHED_CPU_MASK_PIN_ONLY feature which allows to pin systems threads to specific cores of the system. In practise we can simply use the Zephyr system work queue, instead of using a LL-scheduler task, or a LL_POST_RUN notifier, to flush out pending IPC messages.
This fixes the issues with current codebase (Zephyr builds) where IPC TX messages were not flushed out if no LL task was running.
This also cleans up code from zephyr/wrapper.c.

IPC4: Improve TX resend logic on Zephyr

---

src/audio/buffer.c

Buffer notifier events are registered with buffer's uncached address as a key, so notifier events must use the same.
Fixes: 95485f05b5c0 ("buffer: pass locked buffers to notification recipients")

buffer: fix notifier events

---

scripts/xtensa-build-zephyr.py

Rimage expects to receive fw_ver_build to prepare the manifest.
Signed-off-by: Damian Nikodem <damian.nikodem@intel.com>

xtensa-build-zephyr: pass sof build version to rimage

---

west.yml

Update Zephyr to 0956647aaf6bd2b1e840adcc86db503f274d84a9 (3.2.0-rc1 plus a few fixes merged to upstreamed after the tag).

west.yml: upgrade Zephyr to 3.2.0-rc1 level

---

tools/topology/topology2/include/components/pipeline.conf

Currently lp_mode setting is not included by topology binary since lp_mode is not defined as a attribute. This patch adds it in pipeline.

topology2: add lp_mode as a attribute in pipeline

---

src/arch/xtensa/CMakeLists.txt

Fix build fail of mt8195/v0.4 with rimage repo having commit 9d453321f892b7ec3f0 merged at 2022/5/4.
Build fail message:
error: cannot parse firmware version major.minor.micro
src/arch/xtensa/CMakeFiles/run_rimage.dir/build.make:57: recipe for target 'src/arch/xtensa/CMakeFiles/run_rimage' failed
make[3]: *** [src/arch/xtensa/CMakeFiles/run_rimage] Error 234
CMakeFiles/Makefile2:1898: recipe for target 'src/arch/xtensa/CMakeFiles/run_rimage.dir/all' failed
--
SOF CMake defines SOF_MAJOR, SOF_MINOR and SOF_MICRO for 3 fields of firmware file version major.minor.micro. But CMake only passes the major and minor version to rimage.
Now CMake will also pass the mirco version to rimage, so that rimage can write it to different firmware manifest headers for cAVS platforms and then sof_ri_info.py …

CMake: pass firmware file micro version to rimage

---

zephyr/CMakeLists.txt
zephyr/include/rtos/interrupt.h

Both Broadwell and Baytrail are not supported in zephyr and those
Kconfigs are not defined anywhere, neither in SOF nor in zephyr.

zephyr: both BDW and BYT are not supported in zephyr

---

src/audio/module_adapter/module/generic.c

During module_reset and module_free Calls, pointers are not getting reset to NULL which causes dangling pointer exceptions. Initialize pointers to NULL after deallocating the memory.

module_adapter:Fix dangling pointer issue in module reset

---

src/drivers/amd/rembrandt/acp_bt_dma.c
src/drivers/amd/rembrandt/acp_dmic_dma.c
src/drivers/amd/rembrandt/acp_hs_dma.c
src/drivers/amd/rembrandt/acp_sp_dma.c
src/drivers/amd/rembrandt/interrupt.c
src/drivers/amd/renoir/acp_bt_dma.c
src/drivers/amd/renoir/acp_dmic_dma.c
src/drivers/amd/renoir/acp_sp_dma.c
src/drivers/amd/renoir/interrupt.c

Change aclk to max or minimum during playback,capture usecases start and stop based on dmic status.

drivers:amd: Fix aclk issue in standalone dmic usecase

---

.github/workflows/zephyr.yml
scripts/xtensa-build-zephyr.py

`./xtensa-build-zephyr.py -i IPC3 mtl` builds the MTL default: IPC4.
This is wrong, remove the misleading "IPC3" option which never did
anything at all.
Fix the --help string to describe what actually happens. This is a build
script, no need for fancy abstractions and indirections that don't even
match reality. Just tell it like it is.

xtensa-build-zephyr.py: remove misleading -i IPC3 option

---

src/audio/mixin_mixout.c

In case mixin pipeline is running but mixout pipeline is not -- do not discard source data but block source pipeline until at least one sink (mixout) started.
A typical topology is to have mixin and mixout in separate pipelines. Often, mixout pipeline is started a few milliseconds later after mixin pipeline. In such case mixin pipeline should be blocked until mixout pipeline started to do not loose any audio periods.

ipc4: block mixin pipeline if no active sink

---

tools/topology/topology1/sof-rn-rt5682-rt1019.m4

Period has to be 1ms to avoid playback noise issue on Renoir when SOF EQ + DTS are both enabled.
Signed-off-by: Joe.Cheng <joe.cheng@xperi.com>

topology1:enable SOF EQ + DTS on AMD renoir

---

.github/workflows/codestyle.yml
.github/workflows/zephyr.yml
scripts/xtensa-build-all.sh
scripts/xtensa-build-zephyr.py
west.yml
zephyr/docker-build.sh
zephyr/docker-run.sh

4 commits.
Main one:
The next step is to find how to extract the (too many?) errors.
In the mean time this already makes sure the build process never bitrots
and that it will always possible to use sparse. It also "documents" how
to use sparse: just copy/paste the commands run by CI.

[SKIP CI] Add sparse build to Github Actions

---

west.yml

tgl-h zephyr build is broken due to outdated rimage revision.

west: update to newer rimage baseline

---

src/audio/codec_adapter/codec/generic.c
src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/generic.h

https://github.com/thesofproject/sof/commit/b3106c396e540c260bba3b08c218f6598ea74726 module_adapter: get the actual period_bytes
https://github.com/thesofproject/sof/commit/b9889d52d0e1b6002ee016b55fa0487544fc0593 module_adapter: Modify reset API
https://github.com/thesofproject/sof/commit/53b3bc6a956ae5957966336f88980438f1f85a88 module_adapter:Fix dangling pointer issue in module reset
Note that commits were modified to be rollback-applied to codec_adapter instead.

cherry pick module_adapter changes from main to adl-004-drop-stable

---

src/audio/codec_adapter/codec/generic.c
src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/generic.h

https://github.com/thesofproject/sof/commit/b3106c396e540c260bba3b08c218f6598ea74726 module_adapter: get the actual period_bytes
https://github.com/thesofproject/sof/commit/b9889d52d0e1b6002ee016b55fa0487544fc0593 module_adapter: Modify reset API
https://github.com/thesofproject/sof/commit/53b3bc6a956ae5957966336f88980438f1f85a88 module_adapter:Fix dangling pointer issue in module reset
Note that commits were modified to be rollback-applied to codec_adapter instead.

cherry pick module_adapter changes from main to tgl-012-drop-stable

---

src/math/iir_df2t_generic.c
src/math/iir_df2t_hifi3.c

As for our previous design, if we have parallel EQs like filters bank, they get the same input and outputs are summed. There is a mistake of the input assignment in our current code, this commit will fix it.

Audio: EQ-IIR: Fix the bug of parallel EQ calculation

---

tools/topology/topology2/cavs/cavs-nocodec.conf

This reverts commit e31c7abeeb59051c4bc529f77488feaa9585a7d5.
This caused most tests to fail on sh-tglu-rvp-nocodec-ci-02 in daily run 15919, see some more errors in logs shared in initial PR #6318 and new issue #6367
```
FW reported error: 113 - Invalid destination queue (pin) ID provided
ipc error for msg 0x45000004|0x6
sof_ipc4_route_setup: failed to bind modules copier.SSP.8.1 -> gain.7.1
```
I don't know why this failed and I did NOT test this revert, however:
- This topology change is apparently the only thing that changed compared to the day before.
- The error message seems very much related.
- Other people seem to agree.
- According to Ranjani, this feature is not urgent.

Revert "topology2: nocodec: add volume and mixer support"

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-imx8-wm8960-cs42888.m4

This topology is used for i.MX8QXP/i.MX8QM with baseboard to enable both cs42888 and wm8960 codecs.

topology1: Add topology with wm8960/cs42888 for imx8qxp/imx8qm

---

.github/workflows/pull-request.yml
scripts/build-tools.sh
tools/topology/CMakeLists.txt
tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/development/CMakeLists.txt
tools/topology/topology1/dsp_enhancement/CMakeLists.txt
tools/topology/topology1/kernel_dependent/v5.19/CMakeLists.txt
tools/topology/topology2/cavs/CMakeLists.txt
tools/topology/topology2/get_abi.sh

Faster and no more noise. Run `./scripts/build-tools.sh` twice: the second time builds the minimum required and prints almost nothing when nothing changed.
You really want to review these commits separately from each other.

tools: fix incremental build of topologies. Make incremental build the default.

---

src/audio/rtnr/rtnr.c
src/include/sof/audio/rtnr/rtnr.h
tools/topology/topology1/sof/pipe-rtnr-capture-16khz.m4
tools/topology/topology1/sof/pipe-rtnr-capture.m4

This PR merges the following modifications of blob setting feature from main branch to adl-004-drop-stable branch:
21d8948e730ca5e77e5fb7b1c7b3bcce1ab8f1e7 [rtnr: Support setting data blob](https://github.com/thesofproject/sof/commit/21d8948e730ca5e77e5fb7b1c7b3bcce1ab8f1e7)
This commit lets user to set  data blob from host.
For example:
$ amixer -Dhw:0 controls | grep RTNR
numid=47,iface=MIXER,name='RTNR10.0 rtnr_bytes_10'
numid=48,iface=MIXER,name='RTNR10.0 rtnr_data_10'
numid=49,iface=MIXER,name='RTNR10.0 rtnr_enable_10'
$ sof-ctl -Dhw:0 -n 48 -b -s ./preset.bin
A new empty data control added to the topology will be used to send the
blob.
Model handler is now used for transferring the blob data.

rtnr: merge blob setting feature for rtnr back to adl-004-drop-stable branch

---

tools/sof_ri_info/sof_ri_info.py

2 small changes required:
- Stop calling sys.exit(1) in case of error not to exit the importer
- Change EraseVars() to return the checksum value instead of printing it. Move the print() to the main() function
This is required by the new sof-bin tests that compare signed with unsigned binaries; submitted in
https://github.com/thesofproject/sof-bin/pull/105

tools: make sof_ri_info.py a usable library that can be imported

---

west.yml

west.yml: upgrade Zephyr to ed661a6c6909
Upgrade Zephyr from 0956647aaf6bd2b1e840adcc86db503f274d84a9 to
ed661a6c6909b338035b026cfc101ddda65ab8eb (1020 commits, including
441 since v3.2.0 tag).

 west.yml: upgrade Zephyr to ed661a6c6909

---

west.yml

Fixes commit https://github.com/thesofproject/sof/commit/a3b3c525d1e0a98bca5fcc10adb6b40181a06cc7 ("west: update to newer rimage baseline")
See commit messages and new warning in west.yml

rimage: update submodule to 542924d70c17, back in sync with west.yml (fixes -dirty)

---

tools/topology/topology2/cavs/cavs-nocodec.conf

Duplicated dai index result to module initialization faiure in multi-stream test. Dai 2 should be used by stream nocodec-2.
passed failed cases in CI daily test.

topology2: fix multi-stream test issue in ci

---

src/include/sof/schedule/task.h
src/schedule/zephyr_ll.c
xtos/include/sof/lib/perf_cnt.h

This patch is used to make sure profiling code only can be run with performance profiling build, and unify all performance profiling with same format and usage.
Signed-off-by: Baofeng Tian <baofeng.tian@intel.com>

profiling task: modify task profiling with performance counter macro

---

src/ipc/ipc4/dai.c

The "get_llp_reg_info(): gpdma id 32 out of array bounds." message is hit constantly with current mainline topologies with no apparent impact to functinality.
The log is printed at a very high rate, which causes CPU and SRAM traffic pressure that affects test execution.

ipc4: dai: reduce get_llp_reg_info log verbosity

---

tools/topology/topology2/cavs/cavs-nocodec.conf

The mixer is not mature enough to be enabled in nocdec topology and the fix today did not help.
A potential issue found with reset() handling, work in progress in https://github.com/thesofproject/sof/pull/6414
Submitting this to prepare for plan-B. If the fix is delayed or does not help, we need to merge this and come back to mixer enabling when code is more mature.

Revert mixer and volume addition from cavs-nocodec

---

tools/sof_ri_info/sof_ri_info.py

Fixes this error:
```
No platform found in name "sof-rpl.ri"; unknown memory layout.
```
... and shows the Memory Layout.

sof_ri_info: add platform aliases to DSP_MEM_SPACE_EXT

---

src/ipc/ipc4/handler.c

No need to proceed if the pipeline is already active.

ipc4: handler: skip setting state when pipeline is already active

---

zephyr/include/rtos/wait.h
zephyr/include/sof/trace/trace.h
zephyr/wrapper.c

On i.MX8 k_cycle_get_64 always returns 0 so use sof_cycle_get_64 instead.
There is no better solution to support 64bit cycle counting for i.MX and will have to stick with this implementation.
Fixes: c3c94fc515188 ("header: rtos: use rtos specific version of wait.h")

zephyr: Fix cycle counting on i.MX

---

src/include/sof/audio/buffer.h
src/include/sof/audio/component.h
src/include/sof/audio/pipeline-trace.h

The component and pipeline identifiers were direct part of the older
SOF dictionary format. This information was added directly to encoded
output and was not part of the log message. When using Zephyr logging
subsystem, this type of audio specific information has be to put
as part of the log messages like any other log content.
Modify the various audio specific logging macros to add pipeline and component
identifiers to all printed log messages.

add pipeline and component ids to audio specifics logs in output for Zephyr

---

src/audio/codec_adapter/codec/generic.c
src/audio/codec_adapter/codec_adapter.c
src/include/sof/audio/codec_adapter/codec/generic.h

https://github.com/thesofproject/sof/commit/b3106c396e540c260bba3b08c218f6598ea74726 module_adapter: get the actual period_bytes
https://github.com/thesofproject/sof/commit/b9889d52d0e1b6002ee016b55fa0487544fc0593 module_adapter: Modify reset API
https://github.com/thesofproject/sof/commit/53b3bc6a956ae5957966336f88980438f1f85a88 module_adapter:Fix dangling pointer issue in module reset
Note that commits were modified to be rollback-applied to codec_adapter instead.

cherry pick module_adapter changes from main to mt8195/v0.4

---

src/audio/selector/selector.c
src/audio/selector/selector_generic.c
src/include/sof/audio/selector.h

Add mixing-based processing in channel selector to implement capabilities resulting from IPC4 configuration.
Signed-off-by: Tomasz Lissowski <tomasz.lissowski@intel.com>

ipc4: add mixing-based processing in channel selector

---

src/audio/rtnr/rtnr.c
src/include/sof/audio/rtnr/rtnr.h
tools/topology/topology1/sof/pipe-google-rtc-audio-processing-rtnr-capture.m4
tools/topology/topology1/sof/pipe-rtnr-capture-16khz.m4
tools/topology/topology1/sof/pipe-rtnr-capture.m4

This commit lets user to set  data blob from host.
For example:
$ amixer -Dhw:0 controls | grep RTNR
numid=47,iface=MIXER,name='RTNR10.0 rtnr_bytes_10' numid=48,iface=MIXER,name='RTNR10.0 rtnr_data_10'
numid=49,iface=MIXER,name='RTNR10.0 rtnr_enable_10'
$ sof-ctl -Dhw:0 -n 48 -b -s ./preset.bin
A new empty data control added to the topology will be used to send the blob.
Model handler is now used for transferring the blob data.
Code Refine
(cherry picked from commit 21d8948e730ca5e77e5fb7b1c7b3bcce1ab8f1e7)

rtnr: merge blob setting feature for rtnr back to mt8195/v0.4 branch

---

src/library_manager/lib_manager.c

Fix one local variable that may be uninitialized and string formatting for buffer addresses (uintptr_t is long unsigned type).
Tested with gcc 12.1.0 (Zephyr SDK 0.15.0).

library_manager: fix compiler warnings with gcc 12.1.0

---

src/audio/mixin_mixout.c

Fixes a bug in mixout_reset(): mixin pointers in mixed data info should not be cleared on reset. They should only be set on bind and cleared on unbind.

ipc4: fix for mixout not working after reset

---

src/audio/module_adapter/module/passthrough.c

After commit e101aadcd1dc98 ("module_adapter: drop the comp_get_module_data() macro") API prototype was changed to accept a `processing_module` instead of a `comp_dev` but `dev` was still used inside passthrough_codec_free which generates a compile time error:
src/audio/module_adapter/module/passthrough.c:110:12: error: 'dev' undeclared (first use in this function)
comp_info(dev, "passthrough_codec_free()");

module_adapter: Fix compile time error

---

.github/workflows/zephyr.yml

Add the wrong compiler currently expected by the Zephyr build system, very easy one-line change later, get sparse results for MTL NOW!

[SKIP CI] .github/sparse: add MTL

---

tools/test/audio/process_test.m

The test is treated passed if there were no failed cases. The fix in this patch is to force one failed case if both failed and passed counts are zeros. Then the upper level test scripts/host-testbench.sh reports correctly the test fail.

Tools: Test: Fix false success if no processing happened

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/platform/intel/intel-hdmi-ssp.m4
tools/topology/topology1/sof-glk-es8336.m4

Stable-v2.2 is the recommended branch for Intel released platforms till RPL. So cherry pick these 2 topology commits from main to stable-v2.2: 
586716e1b93037e06b6ba6dbd05c7fe7ac7c9ce4 topology1: CMakeLists: add ADL support for ES83x6 & HDMI_In Capture
187c845ddcd8d010212d0e6602f89d80f22e75db topology1: CMakeLists: add ADL support for ES83x6

stable v2.2: cherry pick ADL topology support for ES83x6 and HDMI_In Capture

---

src/audio/copier/copier.c
src/audio/mux/mux.c
src/include/sof/audio/mux.h
west.yml

mux module does not support ipc4
A change is needed to work properly: https://github.com/thesofproject/rimage/pull/112

mux: implement ipc4 support

---

src/audio/module_adapter/module/cadence.c
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module/passthrough.c
src/audio/module_adapter/module_adapter.c
src/include/sof/audio/module_adapter/module/generic.h

b3106c396e540c260bba3b08c218f6598ea74726 module_adapter: get the actual period_bytes
b9889d52d0e1b6002ee016b55fa0487544fc0593 module_adapter: Modify reset API
53b3bc6a956ae5957966336f88980438f1f85a88 module_adapter:Fix dangling pointer issue in module reset

cherry pick module_adapter changes from main to amd_rn_dts

---

tools/topology/topology1/sof-mt8195-mt6359-rt1019-rt5682.m4

With the  release of RTNR version 20220728, period for capturing pipeline requires at least 5ms.
This PR set 5ms period for RTNR in MT8195 topology.

topology: mt8195: rtnr: Set 5ms period for RTNR on MT8195

---

src/audio/buffer.c

A null dereference is hit when comp_update_buffer_produce() or comp_update_buffer_consume() is called with either a NULL buffer->sink or buffer->source. This condition happens regularly in IPC4 builds.
Issue is limited to SOF builds with logging at DEBUG level.

audio: buffer: fix crash with IPC4 build and DBG log level

---

tools/test/audio/std_utils/stdlpf.m
tools/test/audio/std_utils/stdlpf_get.m

Fix a confusing mistake high-pass -> low_pass and typo. It's only a user help text change for "help stdlpf".

[SKIP CI] Tools: Test: Audio: Fix standard low-pass help text

---

tools/topology/topology2/cavs/cavs-mixin-mixout-hda.conf
tools/topology/topology2/cavs/cavs-passthrough-hdmi.conf

mixin/mixout can only be used for playback. So remove it from the HDA capture pipeline and use the passthrough instead.

Fix cavs-mixin-mixout-hda.conf

---

scripts/xtensa-build-zephyr.py

This is preparing the addition of zephyr.elf, zephyr.lst and possibly other files to `build-sof-staging`. For now this PR should make no difference, the purpose is to make the actual addition much smaller and easier to review and to find any bugs in this one _before_ the actual change.
No difference except maybe one small bugfix in the final "tree" listing - depending on whether pathlib.glob(**/*) was ever random and where.
This also makes `pylint xtensa-build-zephyr.py` finally usable.

xtensa-build-zephyr.py: cleanup and re-organize to prepare for installing more files

---

src/audio/module_adapter/module_adapter.c
src/include/sof/audio/module_adapter/module/module_interface.h

Force all module-adapter API users to use cached data

Module adapter: make the .data pointer cached

---

src/ipc/ipc4/handler.c

This will avoid the pipeline walk and all the NOP's in each module trigger when the pipeline is already paused.

ipc4: handler: skip trigger if pipeline is already paused

---

src/audio/base_fw.c
src/include/ipc4/base_fw.h

Base firmware functionality for setting and getting system time. This is for passing the information about host system time. It is then used by FW to translate event timestamps e.g. logs to host system time domain
Signed-off-by: Piotr Kmiecik <piotrx.kmiecik@intel.com>

ace_v1x: host system time set and get

---

scripts/xtensa-build-zephyr.py

This is especially useful when compiling each C file requires a network round-trip to a license server
Also stop overriding the ninja default when building rimage.

xtensa-build-zephyr.py: pass -j option to west -> ninja

---

src/ipc/ipc4/handler.c

<err> ipc: ipc4: 0 failed err 12
The above error isn't so informative.
Replace the target number with the actual IPC message names.

ipc4: handler: make error message more informative

---

.github/workflows/pull-request.yml
.github/workflows/testbench.yml

Among other benefits this will make it possible to enable and disable testbench from the Github web interface:
https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

[SKIP CI] .github: extract standalone testbench.yml from Main Actions

---

scripts/xtensa-build-zephyr.py
tools/sof_ri_info/sof_ri_info.py

At the end of the build, parse the .ri file and print a reproducible
checksum of the its content.
This feature was in xtensa-build-zephyr.sh but never made it to the .py
conversion. It was lost when the .sh file was deleted in commit
https://github.com/thesofproject/sof/commit/ef028f634a0607d7706149b9248824b43664f9fc ("Removed obsolete xtensa-build-zephyr.sh")

xtensa-build-zephyr.py: restore lost reproducible .ri checksum

---

src/audio/data_blob.c
src/include/ipc4/detect_test.h
src/include/sof/audio/data_blob.h
src/include/sof/samples/audio/detect_test.h
src/samples/audio/detect_test.c

Add ipc4 support for KD module keeping ipc3
backward compatibility. Add ipc4 model blob
handler based on large_config_set architecture
Signed-off-by: Ievgen Ganakov <ievgen.ganakov@intel.com>

detect_test: add ipc4 support

---

src/audio/rtnr/rtnr.c

This PR refines the following procedures to make it more stable on different platforms.
1.  The initial data( not config ) defined in the topology is empty. On some platforms rtnr_get_comp_data
might be called with the size equals 0 during initialization. We only do the memcpy_s when the size is valid.
2. There are 3 control widgets in RTNR topology. During initialization, the initial data could be received via IPC in the form of config+data+switch or config only. In either case we now just copy the preceding portion of the data since it has the required config.

rtnr: refine set/get component data procedure

---

src/audio/eq_fir/eq_fir_hifi3.c

Fix the shift round bugs caused by not suitable
xtensa intrinsics.

Audio: EQ-FIR: fix the shift round bugs

---

src/idc/idc.c
src/lib-zephyr/cpu.c
src/platform/Kconfig
src/platform/intel/cavs/lib/pm_runtime.c
xtos/include/sof/lib/cpu.h
zephyr/CMakeLists.txt
zephyr/include/sof/lib/cpu.h
zephyr/wrapper.c

Adding implementation of cpu cores disabling function with usage of a zephyr power manager.
Refactorization of a existing code and moving it to the target location (out of the zephyr wrapper).

zephyr: secondary cores power down

---

src/audio/src/src_generic.c
src/audio/src/src_hifi2ep.c
src/audio/src/src_hifi3.c
src/audio/src/src_hifi4.c

This patch fixes the pointer arithmetic to start FIR calculation from latest written PCM frame pointer. The rewind step was too small and caused the first FIR coefficient to be multiplied with the eldest frame in delay line while it should have pointed to youngest. The second coefficient multiplied with youngest, etc.
The time shift for FIR coefficient caused a difference to filter response vs. designed. Since especially in longer filters the first tap value is near zero the impact was hard to notice.
The "easy" conversions such as 8 kHz to 48 kHz with short filters and larger first tap values suffered most of this.
With this change THD+N for 8 kHz to 48 kHz improves:
```
16 bits		24 bits		32 bits
Before		-60.59 dB		-63.98 dB		-63.98 dB
After		-62.35 dB		-80.39 dB		-80.40 dB
44.1 kHz to …
```

Audio: SRC: Fix SRC FIR off-by-one frame issue (generic, HiFi 2EP/3/4)

---

src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

Simplify the direction setting for components to assign the direction for components during module binding. Copier components always have their direction set during init, so use that to set the direction for the other modules.

ipc4: Set comp direction during module binding

---

src/audio/pipeline/pipeline-graph.c
src/ipc/ipc4/helper.c

When 2 modules are bound together, they are bound with a buffer between them with the connection like this : source_module->buffer->sink_module.
So, what this means is that there is only one connection going from a module to the buffer. So, calling pipeline_disconnect() from the same module to the same buffer in both directions makes no sense.
The right way to free a module would be first disconnect the module from the sink buffer, then check if the sink buffer has been disconnected from its sink module. If so, the buffer should be freed. Otherwise the buffer will be freed whenever the sink module is disconnected from it. The same thing must be repeated for the module's source buffer as well.

ipc4: helper: Fix module unbinding 

---

src/audio/mixin_mixout.c

IPC4 requires that the sink pipeline be started first before the source pipeline starts. So, generate silence if there are no source frames available.

mixin_mixout: generate 0s when mixout pipeline starts first

---

scripts/xtensa-build-zephyr.py

These hardcoded 511 permissions came with the initial commit 1de3ef367584 ("Rewritten xtensa-build-zephyr.sh to python") without any particular explanation.
On Unix, permissions of new files and directories are a user preference set with the `umask`, different applications are not supposed to create directories differently.
On Windows/NTFS it's not clear what 511 maps to.

xtensa-build-zephyr.py: de-hardcode mode=511 in mkdir()

---

tools/topology/topology2/cavs/cavs-nocodec.conf

Mixer and volume (gain) are used in nocodec topology.
It reverts https://github.com/thesofproject/sof/pull/6425

topology2: nocodec: add volume and mixer support

---

src/audio/crossover/crossover.c
src/audio/eq_iir/eq_iir.c
src/audio/multiband_drc/multiband_drc.c
src/audio/tdfb/tdfb_direction.c
src/include/sof/audio/crossover/crossover_algorithm.h
src/include/sof/math/iir_df1.h
src/include/sof/math/iir_df1_generic.h
src/include/sof/math/iir_df1_hifi3.h
src/include/sof/math/iir_df2t.h
src/include/user/crossover.h
src/include/user/eq.h
src/include/user/multiband_drc.h
src/math/CMakeLists.txt
src/math/Kconfig
src/math/iir_df1.c
src/math/iir_df1_generic.c
src/math/iir_df1_hifi3.c
src/math/iir_df2t.c
src/math/iir_df2t_generic.c
src/math/iir_df2t_hifi3.c
test/cmocka/src/audio/eq_iir/CMakeLists.txt
zephyr/CMakeLists.txt

Add C version Direct-1 format implementation for IIR. Compared with the original Direct-2 transport format, Direct-1 has better performance on low frequency since lower quantization noise.

Audio: EQ-IIR: add Direct-1 format implementation

---

.github/workflows/zephyr.yml
scripts/parse_sparse_output.sh

sparse does not have a useful exit status so let's use 'grep' instead.
Fixes: #6317

[SKIP CI] .github: fail on errors and address space warnings in sparse output

---

src/include/sof/audio/module_adapter/module/iadk_modules.h
src/ipc/ipc-common.c

An IADK compilation fix and a cosmetic empty-line clean-up

IADK: fix a wrong assignment

---

src/audio/module_adapter/module/volume/volume_generic.c
src/drivers/intel/dmic/dmic_computed.c
src/include/sof/math/numbers.h

The macro names in sof/math/numbers.h conflict with C library so they must be renamed. New macro names are
INT_MAX_FOR_NUMBER_OF_BITS() and INT_MIN_FOR_NUMBER_OF_BITS().

Math: Rename macros INT_MAX and INT_MIN

---

src/audio/dai-zephyr.c

Check for NULL in init_delay and fifo functions. These are called in very early stage when dai might not be set. Thus fix it and align with legacy.

dai-zephyr: check for NULL in functions
