src/audio/Kconfig, src/audio/eq_iir/eq_iir.c, src/audio/tdfb/tdfb_direction.c, src/include/sof/audio/tdfb/tdfb_comp.h, src/include/sof/math/iir_df1_generic.h
Compared with DF2T, the DF1 has better performance on low frequency and saves about 9.9% cycles on HiFi3 version, so select DF1 instead of DF2T as the default IIR lib for component EQ and TDFB.
=> Audio: replace the IIR lib used by EQ and TDFB with DF1

src/audio/eq_fir/eq_fir.c, src/audio/module_adapter/module_adapter.c
Fix sparse warnings in module adapter and fir eq.
=> sparse: fix warnings

src/audio/src/src.c
PR to change the error into a warning
is a good quick compromise
until a better limit is figured out
Signed-off-by: Kwasowiec, Fabiola <fabiola.kwasowiec@intel.com>
=> mtl upstream: src:change error to warning when checking buffer

src/audio/up_down_mixer/up_down_mixer.c
Fix compiler warnings on discarding const when passing arguments to init_up_down_mixer [-Werror=discarded-qualifiers].
=> audio: up_down_mixer: fix build warnings on discarding const

src/audio/up_down_mixer/up_down_mixer.c, src/audio/up_down_mixer/up_down_mixer_hifi3.c
The up_down_mixer currently depends on Hifi3 intrinsics and there is no generic ANSI C version provides. This leads to CI build errors with Zephyr SDK toolchain version, which doesn't support Hifi/XCC extensions.
Add stubs for the generic implementation to allow the CI build checks to pass. Code will raise a panic if execution is attempted as the implementation is missing.
=> audio: up_down_mixer: add stubs for generic ANSI C version

src/init/init.c
Fixing crash on secondary core initialization.
There is an attempt to initialize DMA scheduler on secondary core, assuming it is already registered on primary core, resulting in a call to NULL pointer.
For MTL, DMA scheduler is not used at the moment.
=> mtl: init: check dma domain ptr before use

src/audio/dai-zephyr.c, src/lib/dma.c
Free the memory allocated for DMA channels when the ref count is 0 and the DMA block config during DAI reset when using natize zephyr drivers to prevent memory leaks seen during stress tests
Fixes https://github.com/thesofproject/sof/issues/6535
=> Fix memory leaks with zephyr native drivers

src/platform/mt8186/include/platform/lib/clk.h, src/platform/mt8186/lib/clk.c, src/platform/mt8186/platform.c
The mt8186 ADSP clock driver should initialize ADSP PLL after boot up before lift core frequency.
The flow of entering/leaving S3 state is also revised to prevent undefined behavior.
The patches were reviewed at https://github.com/thesofproject/sof/pull/6488
The PR was closed because we found a regression issue. 
The regression issue is fixed at this PR.
=> Revise mt8186 ADSP clock driver

tools/topology/topology2/cavs/CMakeLists.txt, tools/topology/topology2/cavs/cavs-passthrough-hdmi.conf, tools/topology/topology2/cavs/cavs-sdw.conf, tools/topology/topology2/cavs/platform/intel/hdmi-4th.conf, tools/topology/topology2/cavs/platform/intel/hdmi-generic.conf, tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/components/pipeline.conf, tools/topology/topology2/include/pipelines/pipeline-common.conf
Add support for chaind DMA pipelines in the HDMI passthrough topology. This version should work even if the kernel does not support chained DMA as yet.
=> topology2: cavs-passthrough-hdmi: Add support for chained DMA

tools/topology/topology1/CMakeLists.txt
This needs to be added in sof-bin.
Link: https://github.com/thesofproject/linux/issues/3873
=> topology1: add missing ES8336 topologies for ICL

src/ipc/ipc4/handler.c
pm_runtime_disable | enable can't be called by ipc msg directly. According to ipc3 implementation,
pm_runtime_get | put are fit for d0i3 msg. Now
only primary core is supported and need to add
secondary core support in future.
=> ipc4: fix fw timeout in d0i3 test

src/platform/intel/cavs/lib/dma.c
Add the device nodes for HDA link DMA when using the native zephyr drivers.
=> cavs: dma: Add device nodes for link DMA

src/audio/module_adapter/module/iadk_modules.c, src/include/sof/audio/module_adapter/module/iadk_modules.h
This PR introduced two fixes:
1. Adds get_attribute, set_large_config and get_large config to IADK module adapter initialization.
2. Since IADK modules could require proprietary configuration. Therefore during module creation whole IPC4 configuration buffer is required, not only  ipc4_base_module_cfg structure.
=> iadk_modules: Fixes to pass correct configuration

src/ipc/ipc-zephyr.c
When entering D3, call the platform_pm_runtime_power_off to prevent the IPC timeouts seen with the CTX_SAVE IPC seen on the host.
=> zephyr-ipc: Invoke platform_pm_runtime_power_off during D3

src/audio/pipeline/pipeline-xrun.c
When a pipeline runs into an xrun, the state of the pipeline will be left as COMP_STATE_ACTIVE. Following this, when the application detects the xrun, it will try and stop the pipeline. This will result in a failure because the pipeline task has already completed and the state is ACTIVE. This will lead to the PIPELINE_DELETE IPC fail as well and the MOD_DX IPC fail because there are pipelines that are in the active state. To prevent this, reset the pipeline when an xrun occurs to leave in a READY state for pipeline stop, delete and DSP D3 entry to succeed.
=> pipeline-xrun: Reset pipeline when xrun occurs

src/audio/mux/mux.c
Newer Xtensa toolchain replaces xt-xcc with xt-clang. For some reason xt-clang fails to build SOF when uint8_t type is used as index of for() loop. This change unblocks building of SOF with xt-clang.
=> mtl upstream: mux: fix FW build with xt-clang

scripts/xtensa-build-zephyr.py, west.yml
3 commits. Main one:
xtensa-build-zephyr.py: detect multiple rimage checkouts and abort
When cloning sof under a different directory name like
sof-experiment1 ((which is bad but we can't stop it unfortunately and it
keeps happening), it's common to end up with two rimage git checkouts:
sof/rimage and sof-experiment1/rimage. Detect this and fail immediately.
=> Detect double rimage git checkout

tools/topology/topology2/cavs/cavs-nocodec.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-module-copier-capture.conf
This PR added multi stream capture support on SSP.
=> Topology2: add ssp multi stream capture

src/platform/mt8186/include/platform/lib/clk.h, src/platform/mt8186/lib/clk.c, src/platform/mt8186/platform.c
Backport patches reviewed at https://github.com/thesofproject/sof/pull/6555 to fix mt8186 suspend/resume issues
=> Backport mt8186 clock driver patches to mt8186/v0.2

src/audio/dai-zephyr.c
Free all the allocated memory in all error paths during dai_params().
=> dai-zephyr: free allocated memory in error paths

src/audio/copier/copier.c
When an xrun happens, the pipeline is reset to allow for a clean D3 entry. So remove the check for state in copier_reset() to allow the copier component to be reset during xruns.
=> copier: Don't block reset during xruns

zephyr/CMakeLists.txt, zephyr/include/rtos/string.h, zephyr/lib.c
We need this in order to export symbols to external libraries.
E.g Cadence library needs __vec_memset / __vec_memcpy.
Previous commit d9aed376d59b ("zephyr: rtos: Add __vec_memcpy / __vec_memset") is not enough in the case of external libs.
=> zephyr: Add zephyr lib.c standalone file

src/audio/kpb.c, src/include/ipc4/kpb.h
Add IPC4 support to KPB module keeping 
backward compatibility with IPC3.
=> kpb: add ipc4 support

src/audio/rtnr/rtnr.c
This PR fixes the format for logging unsigned parameters.
=> rtnr: Fix log formatting for unsigned parameters

src/platform/mt8186/platform.c
The ADSPPLL clock is expected to be disabled in S3 stage. Fail to disable it may have premature wakeup in S3 stage.
=> platform: mt8186: Disable ADSPPLL in S3 stage

src/platform/mt8186/platform.c
platform: mt8186: Disable ADSPPLL in S3 stage
The ADSPPLL clock is expected to be disabled in S3 stage. 
Fail to disable it may have premature wakeup in S3 stage.
=> Backport mt8186 ADSP patches to branch mt8186/v0.2

src/lib/pm_runtime.c
Adding pm_runtime_is_active implementation for ACE.
The functions only allows you to check if the DSP can enter d0i3 state.
=> ace: power: add platform_pm_runtime_is_active

src/audio/pipeline/pipeline-graph.c, src/ipc/ipc4/helper.c
the wrapper checks if the ops exist, and call the ops only if it exists, which is safer
=> Use ops wrapper instead of calling the ops directly for get_attribute

src/audio/rtnr/rtnr.c
This PR cherry-picks the following commit from main to adl-004-drop-stable branch to fix the formatting for unsigned parameters.
ef29d38ec2ff35adbb57d7dfac70ae6ab5fef250 [rtnr: Fix log formatting for unsigned parameters](https://github.com/thesofproject/sof/commit/ef29d38ec2ff35adbb57d7dfac70ae6ab5fef250)
=> rtnr: cherry-pick formatting fix from main to adl-004-drop-stable

src/ipc/ipc4/handler.c
Fix header data passed via idc_ipc command to ipc_cmd on secondary core.
In IPC3 handler, IPC msg header is stored in ipc->comp_data. ipc->comp_data passed to ipc_cmd() is valid for both cases:
- when calling ipc_cmd from ipc_platform_do_cmd for IPC handling
- when calling ipc_cmd from idc_ipc for IDC handling
In IPC4 handler, ipc->comp_data is not used to store IPC msg header. There is global structure msg_data instead. For IPC4, ipc_cmd() may be called in two cases:
- from ipc_platform_do_cmd for IPC handling: in this case, msg_data.msg_in is passed via ipc_compact_read_msg to handle IPC. This path is correct.
- from idc_ipc to handle IDC: in this case, still ipc->comp_data is passed, which does not contain valid IPC header. It passes invalid data to secondary core.
idc_ipc function is …
=> ipc4: idc: fix hdr data passed to idc_ipc msg

scripts/xtensa-build-zephyr.py
Copy the entire list of `UNSIGNED_RI` platforms from src/arch/xtensa/CMakeLists.txt, adding the ones that don't use Zephyr yet.
Also rename NO_RIMAGE_PLATFORMS to RI_INFO_UNSUPPORTED not to give the wrong impression that `imx8*` don't use rimage.
Fixes commit 3a9413eebd82 ("xtensa-build-zephyr.py: restore lost reproducible .ri checksum")
=> xtensa-build-zephyr.py: add missing RI_INFO_UNSUPPORTED platforms.

src/audio/selector/selector.c
We are using cfg->init_data for the modules initialization and cfg->data is not ready when selector_init() is called. Using cfg->data in selector_init() will cause fw crash.
=> selector: use cfg->init_data in selector_init()

src/audio/dai-zephyr.c
Do not free the config->elem_array when there's no error.
Fixes: faf2bd1067a3 ('dai-zephyr: free allocated memory in error paths')
=> dai-zephyr: Fix an erroneous free

src/ipc/ipc4/handler.c
The pcm params argument for ipc4_pipeline_params() is never used, remove it for simplicity.
=> ipc4: removed unused argument for ipc4_pipeline_params

.github/workflows/sparse-zephyr.yml, scripts/parse_sparse_output.sh, zephyr/docker-build.sh, zephyr/docker-run.sh
Use our own sparse branch, we cannot wait for critical sparse fixes like @lyakh's
`xtensa: switch to little endianness` https://marc.info/?l=linux-sparse&m=166861736724543
and others to be merged
=> Fix sparse build by using our own sparse branch

zephyr/CMakeLists.txt
Option -std=gnu99 applied to C++ files trigerrs warning for xcc compiler however throws error for xt-clang.
This patch limits usage of this flag to C, ASM code only.
=> xt-clang: Do not use -std=gnu99 for C++

src/include/sof/ipc/topology.h, src/ipc/ipc4/handler.c, src/ipc/ipc4/helper.c
We need to pass the pipeline_trigger() return value through in ipc4_trigger_chain_dma() for the possibly delayed reply message sending to work correctly.
Signed-off-by: Jyri Sarha <jyri.sarha@intel.com>
=> ipc4: Fix chain DMA trigger handling

src/audio/CMakeLists.txt, src/audio/mixin_mixout/CMakeLists.txt, src/audio/mixin_mixout/mixin_mixout.c, src/audio/mixin_mixout/mixin_mixout_generic.c, src/audio/mixin_mixout/mixin_mixout_hifi3.c, src/include/ipc4/mixin_mixout.h, zephyr/CMakeLists.txt
Use audio_stream_samples_without_wrap_sx to replace the complicated boundary detection can save at least 4.4% MCPS. Separate the mix function to normal mode and remap mode for better performance of optimization, and add HiFi3 version of mix processing functions
=> Audio: Mixin_mixout: Optimize the mixin processing function

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
Commit 265ab371 removed the implication for setting SPK_MIC_PERIOD_US to 10000 while GOOGLE_RTC_AUDIO_PROCESSING is defined (google-aec is integrated).
This commit retrieves the implication.
=> topology: retrieve SPK_MIC_PERIOD_US=10000 config for google-aec

src/include/ipc4/pipeline.h, src/include/sof/ipc/topology.h, src/ipc/ipc-common.c, src/ipc/ipc3/helper.c, src/ipc/ipc4/handler.c, src/ipc/ipc4/helper.c
This PR implements SOF logic in IPC4 handler to enable multicore LL pipelines.
This is first draft or changes, that allows to use basic multicore scenarios.
Main assumptions:
- Pipeline and Module related IPC's forwarded to target core. Their data accessed only by this core, to avoid cache coherency problems.
- To allow pipeline allocation by target core, adding core_id field into CreatePipeline IPC struct for IPC4
- IPC's are forwarded to secondary core by IDC in non-blocking mode. Secondary core processes command and put response into IPC uplink queue.
- MultiPipelineSetState IPC currently supports only cases when all pipelines in command are allocated on the same target core 
This design is consistent with IPC3 handler implementation.
Future work to be done:
- Pipeline and Module data …
=> IPC4: Enable multicore LL pipelines scenario logic

tools/topology/topology1/platform/intel/intel-generic-dmic.m4, tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
Adds fatal assertion in intel-generic-dmic.m4 for DMICPROC is not defined in upper m4, and fixes a potential risk of assertion by sof-tgl-max98357a-rt5682.m4.
=> topology: fix DMICPROC undefined issue for intel-generic-dmic

.github/workflows/codestyle.yml
--subjective is strictly (pun intended) equivalent to --strict but it makes it more obvious that "checkpatch is not always right" (c) https://www.kernel.org/doc/html/latest/dev-tools/checkpatch.html
This should save some time in situations where some warnings conflict with each other like for instance
https://github.com/thesofproject/sof/pull/6655#discussion_r1031572596
or https://github.com/thesofproject/sof/pull/6613#issuecomment-1331532315
=> [SKIP CI] .github/checkpatch: rename --strict to --subjective

zephyr/CMakeLists.txt
Add reference to -fno-inline-functions issue
https://github.com/thesofproject/sof/issues/5212
Add examples of compilation failures without gnu99.
Fixes commit e430629a1e9e ("xt-clang: Do not use -std=gnu99 for C++") that separated the comment from its code.
=> [SKIP CI] zephyr/cmake: fix target_compile_options() comments. No code change

src/ipc/ipc4/logging.c
When firmware is executing a use-case sequence where system moves from:
a) pipelines established and running with low rate of logs
emitted
and moves to
b) one or more pipelines change state and flurry of IPC
activity occurs
The IPC notification throttling may be too slow to react, leading to many lost log messages that cover activity around system moving to (b) state.
Add logic to notice this situation and alert the host if available space in the SRAM log buffer gets low, even if throttling would otherwise block the IPC notification.
Link: https://github.com/thesofproject/sof/issues/6669
=> ipc4: logging: mtrace: stop throttling if running out of space

west.yml
Update rimage to
65f345a52e06a084192124364c563d8133d834c2v
65f345a rimage: add src support
fe5b959 rimage: correct module type
f51ff46 rimage: remove incorrect module order check 
6623073 config: mtl: add kpb module
85a2d1e config: mtl: add kd module
Signed-off-by: Ievgen Ganakov <ievgen.ganakov@intel.com>
=> west.yml: update rimage to 65f345a52

app/prj.conf, scripts/xtensa-build-zephyr.py
4 commits = 3 refactorings with no effect + 1 last commit adding the feature. Separate reviews recommended. See commit messages.
Sample new output below. The sha256 is computed on the _uncompressed_
files and _not_ affected by gzip metadata.
```
build-sof-staging
├── sof
│   ├── community
│   │   ├── sof-imx8.ri         sha256=50c5423d2355ef3ed91...
│   │   └── sof-tgl.ri          sha256=6b1d26c12a63de5dfc8...
│   ├── sof-imx8.ldc    sha256=520d365d188d5ef4e907d3dd8c9...
│   └── sof-tgl.ldc     sha256=cdce6ad340d4dc047e71e738eb0...
├── sof-info
│   ├── imx8
│   │   ├── config.gz
│   │   ├── zephyr.elf.gz
│   │   ├── zephyr.lst.gz       sha256=8c83c3fc92df0a871dd...
│   │   ├── zephyr.map.gz
│   │   └── zephyr.strip.gz     sha256=d3ce3d3450c67bb3580...
│   └── tgl
│       ├── boot.mod.gz …
```
=> xtensa-build-zephyr.py: install and checksum .elf, .lst and other files

west.yml
Upgrade Zephyr to stable2.4 branch in thesofproject, which has cherry-picked hda dai now from zephyr upstream. Don't update anything else from Zephyr upstream.
6c98251bf0fe1 hda dai upstream Zephyr version
79e212e515e29 revert hda dai PR version
bd60b9289a635 hda dai PR version
063984d0b8dec zephyr upstream main
=> west.yaml: move Zephyr to stable2.4 update

.github/workflows/daily-tests.yml, .github/workflows/pull-request.yml, .github/workflows/zephyr.yml
Daily tests workflow triggers "Main Actions" workflow from ./.github/workflows/pull-requests.yml on the main branch
in the time interval defined in schedule/cron node.
Cron value may be set to run in some desired time intervals.
Cron values online configurator: https://crontab.guru
Github references:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
https://docs.github.com/en/actions/using-workflows/reusing-workflows
=> [SKIP CI] Added daily tests workflow

tools/topology/topology1/development/CMakeLists.txt, tools/topology/topology1/sof-hda-generic.m4, tools/topology/topology1/sof/pipe-host-src-volume-playback.m4
This patch adds to sof-hda-generic.m4 macros HSSFX, HSSFX_FILTER1, and HSSFX_FILTER2 those can be used to customize stream effect for PCM 30. The macro defaults to volume so the default topology build is not impacted.
The CMakeLists.txt in development is updated to build topologies sof-hda-generic-src.tplg, sof-hda-generic-2ch-src.tplg, and sof-hda-generic-4ch-src.tplg. The stream effect is set with HSSFX to src-volume.
The pipeline pipe-host-src-volume-playback.m4 is added. It is similar as pipe-host-volume-playback.m4 but a sample rate converter (SRC) is added after PCM, before volume. The PCM capability is changed to min 8000, max 192000 Hz.
=> Tools: Topology1: Add sof-hda-generic topology with SRC

.github/workflows/zephyr.yml
Removing old CAVS SOF RTOS platforms from being built with Zephyr in CI.
=> Remove legacy RTOS platforms from Zephyr build

src/audio/src/src_generic.c
This patch compacts the FIR code a bit per discussion in other SRC
refine patch review where the current pointer arithmetic and code
style was not liked. There is no measurable MCPS impact in the 2ch
and Nch versions of core. It's not slower than original, but possibly
one perf comp_copy trace unit faster (0.03%).
=> Audio: SRC: Generic C SRC FIR core improvement

tools/topology/topology2/cavs-rt5682.conf, tools/topology/topology2/sof-ace-tplg/CMakeLists.txt
make topology2_sof-mtl-max98357a-rt5682
localhost ~ # aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofrt5682 [sof-rt5682], device 0: Headset (*) []
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 1: dummy-spk (*) []
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 5: HDMI1 (*) []
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 6: HDMI2 (*) []
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 7: HDMI3 (*) []
Subdevices: 1/1
Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 8: HDMI4 (*) []
Subdevices: 1/1
Subdevice #0: subdevice #0
localhost ~ # arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofrt5682 …
=> topology2: Add rt5682+max98357a support

src/audio/src/src.c, src/audio/src/src_generic.c, tools/test/audio/src_test.m, tools/test/audio/std_utils/aap_test_measure.m, tools/test/audio/std_utils/aip_test_measure.m, tools/test/audio/std_utils/fr_test_measure.m, tools/test/audio/std_utils/thdnf_test_measure.m, tools/test/audio/test_utils/mix_sweep.m
The main changes are commits 1 and 2 to SRC code. First prevents a pipeline freeze. The second fixes an overflow with 16 bit audio data.
The rest of changes are improvements to src_test.m script. E.g. call testbench with copy limit of 5 min to stop frozen SRC and minor issues fixes and speedup with reduce of printing and plot window opening.
=> Audio: SRC: Increase stage buffer size and change copy() run condition

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-module-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/gain-capture.conf
Add a multi capture stream on SSP port. This will cause IO error with "~/sof-test/test-case/multiple-pause-resume.sh -r 50" test.
Creating this PR for people who want to reproduce the issue.
=> topology2: add ssp multi stream capture 

scripts/qemu-check.sh
Update READY_IPC value based on changes regarding MU reset. READY_IPC value comes from:
- clear GP pending interrupt # 0 and # 1 from MU's xSR register;
- enable GP # 0 and # 1 for Host -> DSP and DSP -> Host message notification from MU's xCR register;
- now interrupt host to tell it we are done booting by setting GIRn bit in MU's xCR register.
So, "00 00 00 c0 00 00 04 c0" is the MU's xSR and xCR registers: xSR: c0000000 and xCR: c0040000
=> scripts: qemu-check.sh: update READY_IPC for imx8

src/drivers/imx/ipc.c
Clear general purpose pending interrupt
before enabling interrupts between host and DSP.
The GIPn bit, from MU Status Register is cleared
by writing it as “1” in order to de-assert the
interrupt request source at the interrupt controller.
This fixes a fw loading failure after a soft reboot caused by GIP bit that was 1.
The problem was the MU which triggered endless interrupts causing timeout on Kernel side, which was waiting for FW_READY message.
=> imx: clear general purpose pending interrupt

src/audio/module_adapter/iadk/system_agent.cpp, src/library_manager/lib_manager.c
This PR contains data initialization fixes in library manager and IADK modules.
=> lib_manager: iadk: Fix variable initialization issues

src/audio/copier/copier.c
Removes variable cd->converter[i] assigning to self. This fixes error reported by static code analyzer.
=> ipc4: copier: remove redundant assignment

.github/workflows/pull-request.yml, .github/workflows/zephyr.yml
This should get rid of most warnings in daily tests
```
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/
2022-09-22-github-actions-all-actions-will-begin-running-on-node16...
Please update the following actions to use Node.js 16: actions/checkout@v2
```
Example at
https://github.com/thesofproject/sof/actions/runs/3597808171
v3 seems backward compatible. Upgrade only the most used instances for now (most used because of the `matrix` of platforms), upgrade everything in a few days if no issue is spotted.
=> [SKIP CI] .github/workflows: upgrade actions/checkout@v2 -> v3

src/ipc/ipc4/handler.c
This makes the D3 sequence for IPC3 and IPC4 identical for TGL and fixes https://github.com/thesofproject/sof/issues/6679 on TGL
=> Fix D3 sequence for TGL

src/audio/src/src.c, src/include/sof/audio/src/src.h, zephyr/wrapper.c
Adopt module interface for src component.
Signed-off-by: Gongjun Song <gongjun.song@intel.com>
=> Convert the SRC component to use the module interface

west.yml
move rimge and zephyr commits to newest
commits from mtl-002-drop-stable branches
Signed-off-by: Marcin Szkudlinski <marcin.szkudlinski@intel.com>
=> west: update rimage and zephyr commits

scripts/xtensa-build-zephyr.py
2 commits
Very small change saves a couple seconds when building from scratch on Linux
=> xtensa-build-zephyr.py: build rimage with -GNinja by default

src/ipc/ipc4/handler.c
Stop platform timer and disable interrupts before D3 entry for CAVS platforms.
(cherry picked from commit 76c85091bf61cdcb3238c1d1aa0b3a56a8fdfcec)
=> ipc4: handler: Fix D3 entry sequence

west.yml
west.yml: move Zephyr to 1941003c6f16b in sof/stable-v2.4
Upgrade Zephyr to newer sof/stable-v2.4 bringing in following changes:
1941003c6f16b dma: hda: calculate correct size if block_count > 1
28de2d1c4cd59 dts: xtensa: intel: update cavs25_tgph to match cavs25
=> [stable-v2.4] west.yml: move Zephyr to 1941003c6f16b in sof/stable-v2.4

src/audio/google_rtc_audio_processing.c
Correct a typo causing a build error in the GoogleRtcAudioProcessing component
=> Correct build error in GoogleRtcAudioProcessing component

src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/include/ipc4/gateway.h, src/include/sof/lib/dai-legacy.h, src/include/sof/lib/dai-zephyr.h, src/include/sof/sof.h, src/init/init.c, src/ipc/ipc3/dai.c, src/ipc/ipc4/dai.c
Current llp slot is allocated based on virtual index
in node id which is incorrect since different dai may
use the same virtual index. It should be allocated
according to allocated dma engine and channel id.
ref: https://github.com/thesofproject/sof/issues/6424
=> ipc4: rework llp slot allocation

src/library_manager/lib_manager.c
Fixes commit f90f5f9a142d
dma ptr should be checked before dma->z_dev
=> library_manager: fix dma_deinit order

west.yml
Zepych update: total of 40 commits.
Update needed before enabling power domains.
=> west.yml: upgrade zephyr to 56284d7017

tools/topology/topology2/avs-tplg/CMakeLists.txt, tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/platform/intel/alh-2nd-spk.conf, tools/topology/topology2/platform/intel/dmic-generic.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf, tools/topology/topology2/platform/intel/sdw-dmic-generic.conf
Add Speaker PCM to cavs-sdw topology. The default is for no aggregated speaker and AGGREGATED=1 should be set in CMakeLists.txt for aggregated speaker.
The 2nd ALH copier stream name should be the same as the 1st ALH copier, and no need to connect to the route.
The 2nd ALH copier data will be set to the 1st ALH copier's gateway config in the aggregated mode.
=> topology2: cavs-sdw: add Speaker and Microphone pcm

src/platform/intel/cavs/include/cavs/lib/memory.h
Larger stack context stack size is required for RTNR and GOOGLE_RTC_AUDIO integration on Intel platforms.
=> memory: intel: increase task stack size for specific modules

src/audio/google_rtc_audio_processing.c, src/audio/rtnr/rtnr.c
At present codes of rtnr and google-rtc-audio-processing, a reconfigure() function is called per copy() routine to dynamically update config blob in COMP_STATE_ACTIVE state. The logic has no problem in practice.
However, if there are cases that config blob is always empty or arrived late, hundreds of warning message lines per second will be produced by comp_get_data_blob() called from reconfigure(), restlessly complaining that [data blob is not set](https://github.com/thesofproject/sof/blob/main/src/audio/data_blob.c#L84).
This commit adds a pre-check for early-return under such cases to skip comp_get_data_blob() calls with warn messages.
=> src: avoid restless warn messages from comp_get_data_blob()

src/audio/Kconfig, src/audio/google_rtc_audio_processing.c, src/audio/google_rtc_audio_processing_mock.c, third_party/include/google_rtc_audio_processing.h, third_party/include/google_rtc_audio_processing_sof_message_reader.h
Changes in the GoogleRtcAudioProcessing component to
-Allow sample rate and number of channels to explicitly be specified.  
-Update the memory management.
-Allow parameters to be passed.
=> Parameterize google rtc audio processing

.github/workflows/sparse-zephyr.yml, scripts/parse_sparse_output.sh
Zero functional change, pure cleanups / minor refactor.
This PR is a subset of rejected #6722, it's the subset that does nothing and only re-organizes the code.
cc:
- #6722
=> [SKIP CI] .github: cosmetic sparse fixes

src/include/ipc/dai.h
The addition of AMD_HS breaks Mediatek platforms by using an index previously allocated to Mediatek. This is a backwards-compatibility issue and needs to be fixed. All firmware released by AMD needs to be re-generated and re-distributed.
Fixes: 83ee5b49a987 ("dai: support for amd specific hs dai id")
Link: https://github.com/thesofproject/sof/issues/6615
Link: https://lore.kernel.org/alsa-devel/36a45c7a-820a-7675-d740-c0e83ae2c417@collabora.com/
Reported-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>
=> backport: dai: move AMD_HS to end of list to restore backwards-compatibility

src/audio/module_adapter/module_adapter.c
comp_update might point to NULL in certain situations.
Signed-off-by: Dobrowolski, PawelX <pawelx.dobrowolski@intel.com>
=> buffer: NULL pointer protection

src/audio/kpb.c, src/include/sof/audio/kpb.h, src/ipc/ipc4/helper.c, src/platform/meteorlake/include/platform/lib/memory.h
[mtl-003-stable-only] Need to make a version without HiFi.
FW infrastructure shall support buffering of historic data from 1ch up to 6 channels 24bit samples in 24bit container.
KPB module shall support on input 3 to 6 channels (1-4 mics + 2ch reference), 16kHz, 16/24bit . Output pins shall support:
For buffered pin same number of channels as on input, 16kHz, bit depth same as on input.
=> kpb: add support 24/24bit buffering for 1-6 channels [mtl-003-stable-only] 

src/platform/intel/cavs/include/cavs/lib/memory.h
Larger stack context stack size is required for RTNR and GOOGLE_RTC_AUDIO integration on Intel platforms.
Signed-off-by: Pin-chih Lin <johnylin@google.com>
(cherry picked from commit e9dfeab7af7c788009f4cb1658120e388a2799bb)
=> cherry-pick: memory: intel: increase task stack size for specific modules

src/audio/module_adapter/module/volume/volume.c
The module operates on arrays whose size is based on SOF_IPC_MAX_CHANNELS. Added check if the number of channels given in the configuration does not exceed the number of maximum supported channels.
=> [MTL 002 stable only] mtl: module adapter: volume: Validation of channels count

tools/topology/topology1/CMakeLists.txt, tools/topology/topology1/kernel_dependent/v5.19/CMakeLists.txt
Amplifier is on link 2, not 3, in this platform
Fixes: https://github.com/thesofproject/linux/issues/4088
=> topology1: add ADL Rooks County laptop LAPRC710

src/audio/buffer.c, src/audio/mixin_mixout/mixin_mixout.c, src/audio/pipeline/pipeline-graph.c
1. Objects, handled using the coherent API, must be allocated as cached.
2. Make sure data-cache prefetch doesn't race against buffer linking and unlinking
=> Cache: fix allocation and address prefetch

tools/topology/topology1/sof-mt8186-mt6366.m4
Default support 1ms period capture pipeline to update host position more precisely.
Signed-off-by: Chunxu Li <chunxu.li@mediatek.com>
=> topology1: mt8186: support 1ms pipeline capture period

src/ipc/ipc4/dai.c
dma_buffer is not yet created when ipc_dai_data_config() is called. Accessing dma_buffer->stream leads to crash.
Anyway, there is no need to set dd->dma_buffer->stream.frame_fmt = SOF_IPC_FRAME_S32_LE as this is done just after ipc_dai_data_config() in dai_params() by calling buffer_set_params().
Somewhat similar fix for IPC3 was done some time ago: 0ba90d8e2a.
=> ipc4: fix crash when using ALH DAI

tools/topology/topology2/cavs-sdw.conf
mixout-gain-dai-copier-playback.2 pipeline id has been changed to 1. Need to change mixout.2.1 to mixout.1.1 as well.
Fixes: https://github.com/thesofproject/sof/commit/f0a010052bd0216348e0906c7f84c5798bb8351d ("topology2: cavs-sdw: group route and pipeline index")
Fixes: #6778
=> topology2: cavs-sdw: fix DEEP_BUFFER_PIPELINE_SINK

src/ipc/ipc4/helper.c
Current ipc_comp_connect() connects the source first, then calls comp_bind
and only then connects the sink. This leads to errors with modules that
assume sink to be connected at bind. This is a valid assumption, so fix
the order in ipc_comp_connect().
=> comp: fix binding modules

src/audio/module_adapter/module_adapter.c
Use correct IPC4 mailbox size. Fix `fragment_size`
calculation for the first and middle config chunks.
Signed-off-by: Ievgen Ganakov <ievgen.ganakov@intel.com>
=> module_adapter: fix large blob processing

west.yml
Total of 440 commits, including following related to intel_adsp/sparse/dmic/xtensa:
603cc2704579 dma: Add max block count attribute
2c162449eb4c xtensa: linker: Fix #52539 by updating the linker scripts 2dd4cbc75592 dts: xtensa: intel: update cavs25_tgph to match cavs25
Link: https://github.com/thesofproject/sof/issues/6710
=> west.yml: upgrade Zephyr to c5b270e7b003

tools/topology/topology2/cavs-rt5682.conf, tools/topology/topology2/sof-ace-tplg/CMakeLists.txt
Deep buffer is mixed with ssp1 stream.
Override mixout copier audio_format.1 from 32/24 to 32/32 for I2S.
=> topology2: cavs-rt5682: add deep buffer support on headsets

src/audio/module_adapter/module/waves.c
Since module-specific prepare API will be called every time on prepare
of module_adapter (stream start trigger), the reset API should
free all memory that was allocated during the prepare API.
Signed-off-by: barry.jan <barry.jan@waves.com>
=> module_adapter: free memory resource

src/audio/buffer.c, src/audio/module_adapter/module_adapter.c, src/audio/pipeline/pipeline-graph.c, src/include/sof/audio/buffer.h
A followup to #6730 - moving cache synchronisation when attaching and detaching buffers in separate functions
=> Buffer-attach

.github/workflows/zephyr.yml
Add build check for Intel 'tgl-h' IPC4 build.
Link: https://github.com/thesofproject/sof/issues/6710
=> [SKIP CI] .github/workflows: add tgl-h IPC4 build

scripts/xtensa-build-zephyr.py
xtensa-build-zephyr.py: checksum deterministic configs.c
.config is not deterministic because it has absolute paths in comments
and its order seems hard to predict. configs.c has the same information
generated in a determistic way.
=> xtensa-build-zephyr.py: checksum deterministic configs.c

tools/topology/topology1/CMakeLists.txt, tools/topology/topology1/sof-adl-nau8825.m4
Adding support for nau8318 Amplifier.
sof-adl-nau8318-nau8825:
nau8825 headphone connects SSP0 link.
nau8318 Amp speakers connects SSP1 link.
bluetooth offload uses SSP2 link.
Signed-off-by: Ajye Huang <ajye_huang@compal.corp-partner.google.com>
=> topology: sof-adl-nau8825: add variant with nau8318 amplifier

src/platform/mt8188/include/platform/lib/mailbox.h
Add back the mailbox_sw_reg_write inline function
to fix build error of mt8188.
sof/src/platform/mt8188/include/platform/platform.h: In function ‘platform_panic’: sof/src/platform/mt8188/include/platform/platform.h:69: warning: implicit declaration of function ‘mailbox_sw_reg_write’
--
I'm so sorry for introduce this build fail when update the mt8188 PR (https://github.com/thesofproject/sof/pull/6796).
=> platform: mt8188: Fix build error

src/audio/src/src.c, src/audio/src/src_generic.c
After changing this per review feedback the three commits are
- Audio: SRC: Optimize generic C fir data pointer wrap
- Audio: SRC: Refine input and output blocks count calculation
- Audio: SRC: Delete unused function parameter fir_delay_length
Only the first commit improves performance. The latter two have no measurable impact.
This PR saves in CML gcc build 2%, or 2.0 MCPS from 46.2 to 45.3
MCPS in stereo 44.1 kHz to 48 kHz conversion.
=> Audio: SRC: Refinements for common 2-stage and generic C FIR

.github/workflows/zephyr.yml
Partial revert of commit 687c6f305e46 (".github: workflow: removed legacy RTOS platforms from Zephyr build") that was a bit too "enthusiastic".
When someone breaks the Zephyr+IPC3 build we'd like to: 1. notice, 2. tell whether it's Intel-specific, IMX-specific or not specific.
This is a one-line change and unlike testing, building is "free". It can be removed in a second when/if that becomes a burden.
=> [SKIP CI] .github/zephyr: re-add TGL IPC3 build for now

scripts/sudo-cwd.sh, zephyr/docker-build.sh, zephyr/docker-run.sh
CMake 3.21 changed the order object files are passed the linker. This
breaks build reproducibility.
=> zephyr/docker-build.sh: upgrade CMake to 3.21 or above

src/audio/copier/copier.c
The PR contains two commits
- Audio: Copier: Add missing DMIC DAI index mapping to create_dai()
- Tools: Topology2: Add DMIC16k capture to cavs-nocodec topologies
Edit - I removed the second topology2 commit. Now this is only a FW patch.
=> Audio: Copier: Add missing DMIC DAI index mapping to create_dai()

.github/workflows/pull-request.yml
This upgrade was already performed for other jobs in commit f71eb15818fd (".github/workflows: upgrade actions/checkout@v2 -> v3") and everything went fine. Finish the job and get rid of the last warnings in the daily tests (example:
https://github.com/thesofproject/sof/actions/runs/3709176785)
=> [SKIP CI] .github/pull-request.yml: upgrade checkout v2 -> v3

src/audio/mixin_mixout/mixin_mixout.c, src/audio/selector/selector.c, src/library_manager/lib_manager.c, src/platform/intel/ace/include/ace/lib/mailbox.h, src/platform/intel/ace/include/ace/lib/memory.h, zephyr/lib/alloc.c
cache_to_uncache() and uncache_to_cache() must be inline functions with proper argument annotations. Fix ACE definitions by alanogy with cAVS.
=> ace: fix cache-uncache conversion macros for sparse

src/audio/selector/selector.c
A pipeline that contains a selector cannot be run before the pipeline that is connected to the selector because an error is returned. The order of the run pipelines should not matter for functionality.
=> selector: remove return error when input buffer is 0

tools/logger/logger.c
In user-space tools, memory allocations can reasonably be expected to always succeed. Make this assumption explicit by adding error handling after malloc.
=> sof-logger: exit with error if malloc fails

tools/logger/convert.c
In user-space tools, memory allocations can reasonably be expected to always succeed. Make this assumption explicit by adding error handling after calloc.
=> logger: exit with error if calloc fails

src/audio/component.c
When dev->state == requested_state in comp_set_state then COMP_STATUS_STATE_ALREADY_SET (status 1) is returned. Then the pipeline trigger is aborted and status 1 is returned to the pipeline_task_cmd function (status 1 in this function means PPL_STATUS_PATH_STOP). Finally, the status of the pipeline does not change and the IPC response returns success. which causes errors with subsequent changes in the pipeline state (INVALID_IPC_REQUEST)
=> module_adapter: return 0 when component state is equal to requested state

src/audio/copier/copier.c
Removes variable cd->converter[i] assigning to self. This fixes error reported by static code analyzer.
(cherry picked from commit e06e1f0a441f2c3b3ed57ea801f35fc7b1b37c7c)
=> [SOF2.4] ipc4: copier: remove redundant assignment

tools/logger/logger.c
sof-logger -u 115200 -d /lib/firmware/sof-foo.ldc
Leads to silent failure as a NULL is passed to open(). Add explicit error handling for this case.
=> sof-logger: print error if -u uart option is given with no infile

tools/logger/convert.c, tools/logger/convert.h, tools/logger/filter.c, tools/logger/logger.c, tools/logger/misc.c
Finish the job that commit 5b29dae9c870 ("logger: Create global convert_config variable to avoid spaghetti code.") started but did not finish, leaving behind a supposedly "global" variable that is actually a confusing global pointer to a struct local to the main() function.
This confuses some static analyzer complaining that stack values are being returned, see #6858 and #6738. This is a false positive because the main()'s stack lifespan is the same as a global but let's simplify things anyway.
Also stop using 'extern' in .c files, use a proper .h file instead.
=> logger: make "global_config" truly global

src/audio/copier/copier.c, src/audio/data_blob.c, src/audio/module_adapter/iadk/system_agent.cpp, src/ipc/ipc4/handler.c, src/library_manager/lib_manager.c, src/probe/probe.c, tools/logger/convert.c, tools/logger/logger.c
Backport following fixes to 2.4:
- https://github.com/thesofproject/sof/pull/6847
- https://github.com/thesofproject/sof/pull/6844
- https://github.com/thesofproject/sof/pull/6839
- https://github.com/thesofproject/sof/pull/6856
- https://github.com/thesofproject/sof/pull/6846
=> [SOF2.4] Backport fixes PR6839, PR6844, PR6846, PR6847 and PR6859

src/audio/copier/copier.c, src/audio/module_adapter/module/volume/volume.c, src/audio/selector/selector_generic.c, src/ipc/ipc4/handler.c, tools/logger/convert.c
=> Static code analysis

.github/workflows/zephyr.yml, scripts/xtensa-build-zephyr.py
**Content**
Five commits:
1. Changed anytree.RenderTree style to ASCII style in the `xtensa-build-zephyr.py`. Github action console was failing to print fancy lines used in the previous style.
2. Added build-windows job to existing Zephyr workflow.
This builds SOF with Zephyr on Windows using Zephyr SDK and MSYS2.
"Manual environment setup" is done when comparing to linux build step (that uses Zephyr Docker container with ready-to-go environment). Windows build uses Github cache system to speed up the job and avoid excessive downloads from external servers.
3. Renamed Zephyr "build" job to "build-linux" job.
4. Added concurrency group to Zephyr workflow so the previous actions are stopped when new push to "similar context" is done. Eg. pushing fast to pull request will now stop previous …
=> Happy new year SOF - Windows CI is coming to town!

src/audio/dai-zephyr.c, src/audio/host-zephyr.c, src/ipc/ipc4/dai.c
Until now, one dma channel could be stopped multiple times without any problems. From commit af6d827b64 on zephyr it is required that the start and stop calls be perfectly balanced.
Zephyr device power manager stores an internal counter. Counter is incremented if device is used and decremented on device release. In this case when we call dma_start() and dma_stop().
If dma_stop() is called more times than dma_start() power manager will reaport a error -EALREADY.
=> audio: dai-zephyr/host-zephyr: stop dma only once

tools/logger/convert.c
Due to allocation failures, or invalid content in dictionary,
"params" entries in "struct proc_ldc_entry" may be NULL.
In print_entry_params(), the NULL entries may be passed
as arguments to fprintf(). While e.g. glibc handles these without
error, this is not guaranteed behaviour and may result in segfault
on some platforms.
Fix the issue by replacing any NULL entries in process_params()
and separately handling the NULL case in dump_ldc_info().
=> sof-logger: ensure NULL is not passed to printf/fprintf

src/ipc/ipc-zephyr.c, src/platform/intel/ace/lib/pm_runtime.c
Preventing d0i3 state during IPC processing in case if a host previously allowed for power state transitions. Transition can occur only in the Idle thread and this lock acts as a safeguard in case of the remaining threads to be non active (e.g. waiting for a semaphore).
The advantage of this solution is that we do not risk bypassing the prevent. PM state lock (get and put) require that their calls be balanced. One more put or get will result with hard to debug error. For example we can end up with permanent prevent on power gating.
Original code introduced here: ae4e037b0
=> zephyr: ipc: refactor of pg prevent

src/platform/intel/ace/lib/dma.c
Double the dma buffer period count as it
should be 128 for 1 channel, 256 for 2, etc.
Signed-off-by: Arsen Eloglian <ArsenX.Eloglian@intel.com>
=> platform: ace: dma: update buffer period count

src/library_manager/lib_manager.c
Fixes commit f90f5f9a142d
dma ptr should be checked before dma->z_dev
Signed-off-by: Adrian Bonislawski <adrian.bonislawski@intel.com>
(cherry picked from commit 7c623256cba190ceb2153b87da170d63ce59ba21)
=> [SOF2.4] Backport "library_manager: fix dma_deinit order" (PR6869)

west.yml
Zepych update: total of 73 commits.
Changes include adding power domains to DMA interfaces and allowing to skip context save during d3.
Dependencies:
=> west.yml: upgrade zephyr to af6d827b64

src/ipc/ipc-zephyr.c, src/ipc/ipc4/handler.c
**Fist commit**
Patch fixes D3 issue - now platform enters and wakes up from D3 correctly. 
It had been achieved using Zephyr cpu function call that redirects D3 flow to power down assembly code
sending IPC response to host just before powering down.
~**Second commit**~
~Adds pm notifiers to Zephyr power manager to allocate IMR memory inside SOF code in order to save LPSRAM and HPSRAM memory before powering down.~
Edit: dropped for now due to missing implementation of devices context restore.
https://github.com/zephyrproject-rtos/zephyr/pull/53105 will be used instead to skip context restore for now.
It will be implemented soon<sup>tm</sup>.
Requires:
Signed-off-by: Marcin Szkudlinski <marcin.szkudlinski@intel.com> …
=> soc: ace: fix IPC D3 power state entry

src/audio/mixin_mixout/mixin_mixout.c, src/include/sof/audio/module_adapter/module/generic.h
Fix two new address space regressions
=> sparse: fix address space mismatches

src/audio/copier/copier.c
This reverts commit 8d166a432f68ccd9ee657a58f379ed4f0f22b888.
This restores working DMIC functionality on Windows platform broken by #6668.
ATTENTION: This will break DMIC1 (DMIC with DAI index 1) functionality on Linux platform, DMIC0 should still work fine!
Non working DMIC1 should be fixed on Linux driver side, not this firmware.
=> Revert Audio: Copier: Add missing DMIC DAI index mapping to create_dai()

src/audio/copier/copier.c, src/include/ipc4/alh.h, src/include/ipc4/copier.h
Adds ALH multi-gateway feature: functionality to mux/demux data from/into multiple gateways.
=> ipc4: copier: Add support for ALH multi-gateways

.github/workflows/zephyr.yml
This saves a lot of scrolling in the next, most popular build step.
=> [SKIP CI] .github/zephyr: docker pull in a separate step

scripts/xtensa-build-zephyr.py
Building on Windows generates CRLF text files. Standardize checksums to
LF files.
As usual, files in the build directory are left untouched.
=> xtensa-build-zephyr.py: convert sof-info/ text files from CRLF to LF

tools/topology/topology1/CMakeLists.txt, tools/topology/topology1/sof-jsl-rt5682.m4
This topology supports JSL boards which implement ALC5682I-VD/VS on SSP0 port without speaker amplifier.
=> topology: sof-jsl-rt5682: add sof-jsl-rt5682.tplg

.github/workflows/zephyr.yml
From
https://github.com/actions/upload-artifact#uploading-to-the-same-artifact
> Warning: Be careful when uploading to the same artifact via multiple
> jobs as artifacts may become corrupted.
Fix bug where IPC3 and IPC4 builds were randomly overwriting each other and the same bug with different Zephyr revisions.
=> [SKIP CI] .github/zephyr: fix uploads overwriting each other

src/audio/Kconfig
Linker fails to link iir_df2t() function when COMP_CROSSOVER is enabled. Need to select MATH_IIR_DF2T in Kconfig to build the iir_df2t() function as well.
=> Audio: fix compile error for COMP_CROSSOVER

src/audio/dai-zephyr.c, src/audio/host-zephyr.c, src/audio/module_adapter/module/generic.c, src/audio/module_adapter/module/volume/volume.c, src/audio/mux/mux.c, src/audio/pipeline/pipeline-graph.c, src/audio/pipeline/pipeline-params.c, src/audio/selector/selector.c, src/idc/idc.c, src/ipc/ipc-common.c, src/ipc/ipc4/dai.c
Change some log level from info to dbg, those changed place are not reporting errors, just information, so no risk and can be change back when debugging.
From performance perspective, before and after:
Before: [11.86] ll_schedule: ll timer avg 2329, max 2887, overruns 0
After:   [11.52] ll_schedule: ll timer avg 2226, max 2789, overruns 0
Signed-off-by: Baofeng Tian <baofeng.tian@intel.com>
=> sof debug and trace: change sof log level for some modules

src/audio/dai-zephyr.c
check max block count supported by DMA to prepare a correct config for DMA
Fixes: https://github.com/thesofproject/sof/issues/6709
OPEN: currently it is recalculating block count to max supported but it could also return error and recalculate to 1 only for HDA
=> dai-zephyr: check max block count supported by DMA

tools/topology/topology1/CMakeLists.txt
The ADL integration was botched with missing topologies and errors in topology names in the kernel.
Link: https://github.com/thesofproject/linux/issues/4111
=> topology1: add missing ADL-es8336 topologies.

installer/GNUmakefile, scripts/build-tools.sh
To test whether CMake configuration can be skipped, look for either a ninja.build or Makefile.
An existing build directory is NOT proof that CMake configuration succeeded. When CMake configuration failed, trying to build again fails with a super confusing "Makefile not found" error message.
=> scripts: fix check whether CMake configuration succeeded

src/audio/dai-zephyr.c
Add error check in dai_get_hw_params() for the case where dai_config_get() returns an error.
=> dai-zephyr: handle dai_config_get() errors properly

src/audio/copier/copier.c
This reverts commit 8d166a432f68ccd9ee657a58f379ed4f0f22b888.
This restores working DMIC functionality on Windows platform broken by #6668.
**_ATTENTION: This will break DMIC1 (DMIC with DAI index 1) functionality on Linux platform, DMIC0 should still work fine!_** Non working DMIC1 should be fixed on Linux driver side, not this firmware.
=> Revert "Audio: Copier: Add missing DMIC DAI index mapping to create_dai()"

west.yml
upgrade rimage to
ba8534bb237881beb281c56f5d03d92fa67eb0ec
ba8534bb2378 Fix bitmap according to the IMR type
f3eef3cfb6ff Fix IMR type parsing
bdba8259fe3c Add a command line option to set an Intel-specific PV bit 1c48208850c9 config: tgl-cavs: add smart amp test module config 082b6261c9dc config: Add mt8188.toml
=> west.yml: upgrade rimage to ba8534bb2378

scripts/sudo-cwd.sh
Copying a file that does not exist obviously fails.
This bug was found when trying to switch from the current "Developer Image" to the smaller "CI Image":
https://github.com/zephyrproject-rtos/docker-image/pkgs/container/zephyr-build
=> scripts/sudo-cwd.sh: don't try to copy missing sudoers.d/ permissions

west.yml
Updates Zephyr to current top: e4fcb32451c587a3e4ba7f8bf3fc602b16f9652b.
This is to enable ALH multi-gateway feature. The required Zephyr commit for Intel ADSP MTL is:
https://github.com/zephyrproject-rtos/zephyr/pull/53066
=> west.yml: Update Zephyr

tools/topology/topology2/platform/intel/alh-2nd-spk.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf
Assume an amplifier will provide 2 channels feedback.
=> topology2: set sdw amp feedback pcm channel number

src/audio/base_fw.c, src/include/ipc4/base_fw.h, src/include/sof/lib/cpu-clk-manager.h, src/lib/CMakeLists.txt, src/lib/cpu-clk-manager.c, zephyr/CMakeLists.txt
Add initial implementation of mcps budget management.
Ideally it should be used to control cpu clock, so that it runs on the lowest frequency suitable for performed tasks.
Different parts of FW can request/free some budget using `core_cps_adjust` and clock should be changed accordingly. (i.e. when setting pipeline to run we should request budget required by its modules).
Currently there is no proper performance data to be used, so it's advised to request some artificial, high budget on platform init to keep the clock running fast and avoid performance issues.
Requires https://github.com/zephyrproject-rtos/zephyr/pull/52205 to work on mtl
=> lib: MCPS budget manager

scripts/xtensa-build-zephyr.py
Temporary solution until the `west sign` situation is finalized upstream, see zephyrproject-rtos/zephyr/pull/52942 and others.
Use shlex.split() that supports both some quoting and empty strings nicely.
=> [STABLE 2.4] xtensa-build-zephyr.py: add --extra-rimage-args option

src/audio/module_adapter/module/volume/volume.c, src/include/sof/audio/volume.h
24/32 function is never selected due to the fact that only the size of the container determines the selection of the function. It should be selected based on valid_bit_depth.
Signed-off-by: Kwasowiec, Fabiola <fabiola.kwasowiec@intel.com>
=> peakvol: select correct processing function

CODEOWNERS
Forgot to update this after moving our components to a folder
=> [Skip CI] owners: fix google audio component path

tools/coredumper/sof-coredump-reader.py
The undefined function may cause the debugger not able to run properly. Print a "set confirm off" instruction to the beginning of output file to solve this problem.
(xt-gdb) break _MemErrorVector
Breakpoint 1 at 0x9f180400
(xt-gdb) break _MemoryExceptionVector_text_start
Function "_MemoryExceptionVector_text_start" not defined. Make breakpoint pending on future shared library load? (y or [n]) run Please answer y or [n].
...
=> coredump-reader: set confirmation off

.github/workflows/SPDX-README.md, .github/workflows/checkpatch_list.sh
Pleasing checkpatch is hard when adding new files.
This is tricky and comes up every time someone adds new files, examples in #6284, #6796, #6931 , etc.
=> [SKIP CI] github: add new SPDX-README.md and show it when checkpatch fails

src/audio/mux/mux.c
The change of mux component codes from PR#6762 added the condition on capture to propagate prepare/reset command to upstream only if there are no active sinks. The purpose is to support multiple endpoints sourced from one capture device.
However, the regression is observed with audio malfunction on DSP for some specific brya devices. After triage, we found that the regression only affects devices applying smart_amp on DSP.  
For topologies integrated with smart_amp component (as figured below), a demux is placed on echo reference (capture) pipeline, providing sink linkages to both PCMC and smart_amp. smart_amp is located on playback pipeline whose direction is opposite from demux.
```
PCMP ----> smart_amp ----> SSP(A)  # playback ppl
^
|
PCMC <---- demux <----- SSP(B)     # echo reference …
```
=> mux: consider sinks on same direction only for prepare/reset propagation

src/platform/intel/ace/lib/pm_runtime.c, west.yml
Some registers have been renamed in Zephyrs commit https://github.com/zephyrproject-rtos/zephyr/commit/21f278c04bc258eb344ac5b2123b49d760b5b71d. This PR changes the references from old to new names and update zephyr revision in west.
=> mtl: Update zephyr and use new register name

tools/topology/topology2/avs-tplg/CMakeLists.txt, tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/development/CMakeLists.txt
Somehow some SoundWire topologies don't have PREPROCESS_PLUGINS=nhlt definition. It leads to nhlt is not included in those topologies.
Fixes: #6955
=> topology2: add missing nhlt

zephyr/CMakeLists.txt, zephyr/include/sof/lib/regions_mm.h, zephyr/lib/regions_mm.c
Add virtual memory regions info gathering from zephyr and introduce structs agregating this information.
Add proper defines for memory managment.
Signed-off-by: Jakub Dabek <jakub.dabek@intel.com>
=> memory: Add virtual memory regions gathering and structs

tools/topology/topology2/development/CMakeLists.txt, tools/topology/topology2/sof-ace-tplg/CMakeLists.txt
There is no HDMI support on MTL RVP for now.
=> topology2: remove HDMI from topologies for MTL

src/platform/meteorlake/include/platform/lib/memory.h
The heap mem size is not large enough. Enlarge the size to 0x600000.
=> mtl: enlarge HEAPMEM_SIZE to 0x60000

.github/workflows/sparse-zephyr.yml, .github/workflows/zephyr.yml
Other jobs typically use `west update --narrow` which is faster but also
able to fetch "wild" SHA1s from any random place!  It is useful for
testing unmerged Zephyr commits but risks accepting "invalid" zephyr
commits; this will not.
=> [SKIP CI] .github/zephyr: add new manifest-check

CODEOWNERS
I don't want to be spammed any more every time someone adds or renames a source file.
=> [SKIP CI] CODEOWNERS: be more selective when matching CMakeLists.txt files

src/audio/copier/copier.c, src/audio/dai-zephyr.c, src/audio/pipeline/pipeline-stream.c, src/include/ipc4/copier.h, src/include/sof/audio/component_ext.h, src/include/sof/lib/dai-zephyr.h
Copier configuration size must include the variable size array in struct ipc4_copier_gateway_cfg.
=> copier: fix allocation and configuration size

tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/sof-ace-tplg/CMakeLists.txt
It worked because we defined DMIC_DRIVER_VERSION 3 as the default value. We have to specify PLATFORM=mtl when the default value was removed.
Fixes: #6968
=> topology2: sof-mtl-rt711-4ch: specify PLATFORM=mtl

tools/topology/topology2/avs-tplg/CMakeLists.txt
The pipeline-free chain DMA implementation has multiple issues, so disable it by default in Intel cAVS topologies.
=> topology2: avs-tplg: disable USE_CHAIN_DMA

src/include/ipc4/base_fw.h
Now each stream is built with at least two pipelines and this can't support more than 8 streams, 6 streams in normal. This results to CI test failure since it will tests all streams simultaneously although current topology is simple.
Now increase it to 32 for future enhancement.
=> ipc4: increase max pipeline count to 32

src/audio/dai-zephyr.c
It is not guaranteed that 'dd->z_config' is set when dai_reset() is called. E.g. if the requested runtime parameters are not supported by the hardware, the parameter setup will not be completed. When dai_reset() is called in this state, a FW crash is hit due to NULL dereference.
Fix the issue by checking dd->z_config value before use.
=> dai-zephyr: fix crash in dai_reset

src/audio/up_down_mixer/up_down_mixer.c, src/include/sof/audio/up_down_mixer/up_down_mixer.h, zephyr/wrapper.c
Use the module_adapter interface instead of comp_drv ops.
=> up_down_mixer: Convert module to use the module interface

.github/workflows/zephyr.yml, scripts/xtensa-build-zephyr.py, zephyr/scripts/clean-expected-release-differences.sh
The End.
This makes sure Windows builds and Linux builds produce identical binaries.
=> [SKIP CI] .github/zephyr: compare Windows and Linux builds

src/ipc/ipc4/dai.c
The limitation that SSP sample format is always S32_LE does not hold. There can be I2S codecs where 16bit sample width is used and SSP FIFO will expect 16bit samples from DMA.
=> ipc4: dai: remove S32_LE hardcode for SSP DAIs

src/platform/intel/ace/platform.c
Init IDC on primary core to enable receiving IDCs from secondary cores.
=> platform: ace: enable IDC on primary core

src/audio/module_adapter/module_adapter.c
Refactor the module_adapter_copy() function to split the simple_copy case into a separate helper function.
=> module_adapter: refactor the copy function

tools/topology/topology2/cavs-mixin-mixout-hda.conf, tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/cavs-rt5682.conf, tools/topology/topology2/cavs-sdw-src-gain-mixin.conf, tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/get_abi.sh, tools/topology/topology2/include/common/data.conf, tools/topology/topology2/include/common/fe_dai.conf, tools/topology/topology2/include/common/manifest.conf, tools/topology/topology2/include/common/pcm_caps.conf, tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/common/vendor-token.conf, tools/topology/topology2/include/components/gain.conf, tools/topology/topology2/include/components/pipeline.conf, tools/topology/topology2/include/components/virtual.conf, tools/topology/topology2/include/components/volume.conf, tools/topology/topology2/include/components/widget-common.conf, tools/topology/topology2/include/controls/common.conf, tools/topology/topology2/include/controls/mixer.conf, tools/topology/topology2/include/dais/pdm_config.conf, tools/topology/topology2/platform/intel/deep-buffer.conf, tools/topology/topology2/platform/intel/dmic-generic.conf, tools/topology/topology2/platform/intel/dmic-wov.conf, tools/topology/topology2/platform/intel/hdmi-4th.conf, tools/topology/topology2/platform/intel/hdmi-generic.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf, tools/topology/topology2/platform/intel/sdw-dmic-generic.conf, tools/topology/topology2/sof-hda-generic.conf
In preparation for making it easier to write topology conf files that can be conditionally included without having to worry about conflicting node ID's for objects between the included file and the top-level conf file, modify all classes to include an instance attribute. This means that irrespective of the object type, all objects will be instantiated as follows:
Object.Widget.gain.1 {} or Object.Base.pdm_config.2 {} etc
The instance ID's are typically only meant for the alsatplg compiler to differentiate the nodes in the conf file and are not relevant for the kernel or the firmware. This change will allow the alsatplg compiler to be modified to automatically make the node ID's unique before conditionally including conf files.
Signed-off-by: Ranjani Sridharan …
=> topology2: Add instance attribute for all classes

src/library_manager/lib_manager.c
It is possible that lib_id from IPC would not match with lib_id of module. That can cause NULL pointer and FW crash.
Signed-off-by: Dobrowolski, PawelX <pawelx.dobrowolski@intel.com>
=> lib_manager: lib_id mismatch prevention

tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-mixin-capture.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-module-copier-capture.conf
Multiple pipelines had incorrect num_audio_formats leading to invalid format structures ending up to topology.
Example FW trace:
[ 1601.624195] sof-audio-pci-intel-tgl 0000:00:1f.3: Get input audio formats for copier.module.8.2 [ 1601.624197] sof-audio-pci-intel-tgl 0000:00:1f.3:  #0: 48000KHz, 32bit (ch_map 0xffffff10 ch_cfg 1 interleaving_style 0 fmt_cfg 0x2002) [ 1601.624201] sof-audio-pci-intel-tgl 0000:00:1f.3:  #1: 0KHz, 0bit (ch_map 0x0 ch_cfg 0 interleaving_style 0 fmt_cfg 0x0)
=> topology2: cavs: fix num_audio_formats to match the actual number

scripts/xtensa-build-zephyr.py
`git describe` differences happen, especially when trying to optimize cloning and this is for instance what happened in
https://github.com/thesofproject/sof/pull/6950#issuecomment-1396150533 where zephyr tags were fetched on Linux but not on Windows
This also makes plain git version differences more obvious; no need to scroll all the way up and scan the build logs.
=> scripts/xtensa-build-zephyr.py: checksum [sof_]version.h files

.github/workflows/SPDX-README.md
Explain when this file applies and why there is a .c/.h difference.
I still don't understand why .c file don't use /* SPDX */ but I think it's still worth quoting a tiny bit from the official documentation anyway.
=> [SKIP CI] .github/SPDX-README.md: clarify .c/.h difference and applicability

tools/topology/topology1/sof-apl-da7219.m4
Headphone output requires MCLK_ID to be set to 1
Fix for headphone issue noticed in #6963
Tested: https://www.youtube.com/watch?v=mtPHPJKPp6o
=> Apollo Lake needs MCLK 1 for working da7219

src/platform/intel/cavs/lib/dma.c
Align HDA DMA platform period count with value used on Intel ACE platforms. This only affects operation with native Zephyr DMA drivers.
=> cavs: dma: increase HDA DMA period count to 4

tools/topology/topology2/cavs-nocodec-bt.conf, tools/topology/topology2/platform/intel/bt-generic.conf
Fix bt offload pipeline with instance ids. This was an unfortunate merge error with recent instance id topology2 commit.
=> topology2: fix bt offload pipeline build

tools/topology/topology2/include/controls/bytes.conf
Use instance IDs as the class definitions have changed.
=> topology2: control: bytes: Use instance ID to instantiate ops and extops

src/audio/kpb.c, src/include/sof/audio/kpb.h, src/platform/meteorlake/include/platform/lib/memory.h
FW infrastructure shall support buffering of historic data from 1ch up to 6 channels 24bit samples in 24bit container. 
KPB module shall support on input 3 to 6 channels (1-4 mics + 2ch reference), 16kHz, 16/24bit . Output pins shall support: 
For buffered pin same number of channels as on input, 16kHz, bit depth same as on input.
=> kpb: add support 24/24bit buffering for 1-6 channels

tools/topology/topology1/development/CMakeLists.txt, tools/topology/topology1/development/sof-hda-generic-2ch-demux-3pcm.m4, tools/topology/topology1/development/sof-hda-generic-2ch-demux-demux-3pcm.m4, tools/topology/topology1/m4/pipeline.m4, tools/topology/topology1/sof/pipe-dai-demux-capture.m4, tools/topology/topology1/sof/pipe-volume-demux.m4
The topology sof-hda-generic-2ch-demux-3pcm.tplg uses a single demux to duplicate three times the same DMIC DAI capture.
The topology sof-hda-generic-2ch-demux-demux-3pcm.tplg uses two demux components to provide to PCMs raw DMIC capture, processing after PGA12.0, and processing after PGA12.0 and PGA14.0.
The patch adds to pipeline.m4 a modified version of macro W_PIPELINE() called W_PIPELINE_TOP() that can be used to add from top level topology pipeline widgets to pipelines those are missing it. It avoids topology load error.
Added pipelines pipe-dai-demux-capture.m4 and pipe-volume-demux.m4 are needed in these two example topologies.
=> Tools: Topology1: Add three demuxed PCMs for DMIC capture example

src/audio/chain_dma.c
Require maintenance in logic to handle multiple start/pause requests by one chain instance.
Signed-off-by: Piotr Makaruk <piotr.makaruk@intel.com>
=> hda: chain transition states fix

src/samples/audio/smart_amp_test.c
Use SOF_MODULE_INIT() to register smart_amp_test module with the Zephyr initialisation framework.
the conversion for smart amp test module is missing from https://github.com/thesofproject/sof/pull/6989, add it here.
=> smart_amp_test: convert to Zephyr native initialisation

src/samples/audio/Kconfig
Enable building smart_amp_test module for MTL.
rimage PR: https://github.com/thesofproject/rimage/pull/127
=> MTL: enable smart_amp_test module

tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/components/copier.conf, tools/topology/topology2/include/pipelines/cavs/deepbuffer-playback.conf
The dma_buffer_size is only applicable from the host/dai copiers and can be calculated using the ibs/obs in the base_cfg in the kernel.
So in preparation for removing the dma_buffer_size token from the audio format objects, add a new attribute, deep_buffer_dma_ms, in the copier that will be used to the send the deep buffer DMA size to the kernel.
=> topology2: copier: Add a new attribute

tools/test/audio/test_utils/test_run.m
This patch fixes a mistake with test run configuration for testbech tests where input and output word lengths are not the same.
=> Tools: Test: Audio: Fix BITS_OUT in test run configuration

tools/topology/topology1/m4/dts_codec_adapter.m4, tools/topology/topology1/sof-adl-nau8825.m4, tools/topology/topology1/sof-eq-iir-dts-codec-smart-amplifier.m4, tools/topology/topology1/sof-tgl-max98357a-rt5682.m4, tools/topology/topology1/sof-tgl-max98373-rt5682.m4
For Intel platforms, C0 is on by default for processes necessary to run in low power cases, while C1..3 for processes with higher loads. This commit moves the default core to C1 for Speakers pipeline.
At the same time, we found this commit can resolve the DSP panic issue on builds with 3P post-processing solutions running on Speakers pipeline.
=> topology: set Speakers PPL running on C1 by default

src/audio/Kconfig
Hda chain work only with IPC4 compatible boards, therefore additional compilation dependency in Kconfig has to be added.
Signed-off-by: Piotr Makaruk <piotr.makaruk@intel.com>
=> hda: enable chain dma with ipc4 only

tools/topology/topology2/platform/intel/hdmi-generic.conf
Allow multichannel audio support for HDMI 1, 2, 3 and optional 4. This change allows maximum of 8 (7+1) channels, provided the connected displays EDID allows it.
Signed-off-by: Jyri Sarha <jyri.sarha@intel.com>
=> topology2: hdmi-generic.conf: Increase channels_max to 8 for HDMI 1-4

src/include/sof/audio/pipeline.h, src/ipc/ipc4/helper.c
During create a new pipeline, the FW is not store information about pipeline attributes. The information is lost and we can not verify later if pipeline has ULP or Autonomous_reset attributes.
This PR added a attributes field in pipeline structure and save the information during pipeline create.
=> ipc: save pipeline attributes

src/samples/audio/Kconfig, west.yml
Enable building smart_amp_test module for MTL.
originally from https://github.com/thesofproject/sof/pull/7005
=> [For MTL 003] MTL: enable smart_amp_test module

west.yml
upgrade rimage to
7bc3cfc946a04cbceebf7d0202a6d490c85dca72
7bc3cfc config: mtl: add smart amp test module config 3da7739 config: correct module config load_type
bc7d49d config: align module_type with mtl for tgl and tgl-h bdf48ee config: tgl-cavs: add fir and iir eq module config
=> west.yml: upgrade rimage to 7bc3cfc

src/audio/CMakeLists.txt, src/audio/Kconfig, src/audio/copier/copier.c, src/audio/ipcgtw.c, src/include/ipc4/gateway.h, src/include/ipc4/ipcgtw.h, src/ipc/ipc-common.c, src/ipc/ipc4/handler.c, zephyr/CMakeLists.txt
Adds IPC4 gateway. IPC4 gateway transfers audio between host and DSP without using DMA: via memory window (audio payload) and IPC messages (commands).
=> ipc4: add IPC4 gateway

scripts/fuzz.sh, src/platform/posix/include/platform/platform.h, src/platform/posix/ipc.c
Come back to the fuzzing rig, dust off my brain (been a rough January here for me, sorry), and update to hopefully finish off IPC coverage.
As mentioned earlier, TPLG_COMP_NEW commands weren't being covered (and if we can't create components, we aren't able to get coverage on anything else!) because of the way they work.  The input wants to match a 128 bit UUID value in the command vs. a table of drivers, and that haystack is too deep for even fuzzing to find the needle.  This plays a trick by using an otherwise-ignored bit of fuzz input to encode a "create a whiteboxed command" metacommand.  When triggered, this adds Just Enough Correct Input to get the code through the driver selection stage of the IPC parser, but leaves the other random bits random.   There were a bunch of ancestor …
=> Update fuzzing rig, make component creation work

src/audio/mixin_mixout/mixin_mixout.c
If mixout is not able to process data, the "assert(sinks_free_frames >= start_frame)" condition is hit.
This is not correct usage of asserts as the condition may be hit due to performance reasons (and is frequently hit in pause-resume stress test with sof-test), and production builds will have asserts disabled, leading to undefined behaviour.
Instead of assert, add a check, emit a warning and truncate the amount of copied frames, to ensure deterministic behaviour in all conditions.
Link: https://github.com/thesofproject/sof/issues/6896
=> mixin-mixout: handle congestion corner case without assert

src/audio/eq_iir/eq_iir.c
eq_iir_set_alignment() should use the  __sparse_cache annotation for both its arguments.
=> eq-iir: fix address space notation

src/include/sof/samples/audio/smart_amp_test.h, src/samples/audio/smart_amp_test.c
Hi,
the module initialization for IPC4 does not contain binary (configuration) blob, only base_cfg and optional bae_cfg_ext.
The configuration blob is sent as a large_config message separately.
=> samples: convert smart amp test module to not expect the blob during init with IPC4

src/include/kernel/abi.h, src/include/kernel/header.h, tools/ctl/ctl.c
Hi,
Update the ABI header to match with the kernel's recent changes to define it's use with IPC4 blobs.
Add support for generating and handling IPC4 blobs to sof-ctl.
this PR should be able to replace #6893
=> sof-ctl: Add support for handling IPC4 blobs

src/audio/chain_dma.c
Hda chain dma buffer require aligning after its size recalculation.
Signed-off-by: Piotr Makaruk <piotr.makaruk@intel.com>
=> hda: Maintain dma buffer alignment

src/audio/mixer/mixer.c, src/audio/mixer/mixer_hifi3.c, test/cmocka/src/audio/mixer/CMakeLists.txt
Using frame aligned API to reduce the division calculation in mixer process function.
Signed-off-by: Andrula Song <andrula.song@intel.com>
=> Audio: Mixer: Use frame aligned API

tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-mixin-capture.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-module-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/dai-kpb-be.conf, tools/topology/topology2/include/pipelines/cavs/deepbuffer-playback.conf, tools/topology/topology2/include/pipelines/cavs/gain-capture.conf, tools/topology/topology2/include/pipelines/cavs/gain-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/gain-module-copier.conf, tools/topology/topology2/include/pipelines/cavs/gain-playback.conf, tools/topology/topology2/include/pipelines/cavs/host-copier-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-host-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/src-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/wov-detect.conf, tools/topology/topology2/include/pipelines/eq-iir-volume-capture.conf, tools/topology/topology2/include/pipelines/passthrough-capture.conf, tools/topology/topology2/include/pipelines/volume-capture.conf, tools/topology/topology2/include/pipelines/volume-demux-playback.conf, tools/topology/topology2/include/pipelines/volume-playback.conf
Changes all routes of form:
Object.Base {
route.1 {
source copier.host..1
sink	gain..1
}
route.2 {
source	gain..1
sink mixin..1
}
}
to
Object.Base {
route.1 {
source copier.host.$index.1
sink	gain.$index.1
}
route.2 {
source	gain.$index.1
sink mixin.$index.1
}
}
E.g. change ".." notation where the route index is expanded in between the dots to explicit reference to the route index.
Signed-off-by: Jyri Sarha <jyri.sarha@intel.com>
=> topology2: Use new attribute references notation in route definitions

src/audio/module_adapter/module/waves.c
There is a rballoc() call during module_init() lacking the correspondent rfree() on module_free(). Replace it with module_allocate_memory() to ensure the memory to be freed by module_adapter.
=> module_adapter: waves: fix unfreed rballoc memory block

src/platform/intel/cavs/include/cavs/lib/pm_memory.h
Memory banks enablement flow is adjusted to reccommended approach. Power status should  be read twice to ensure ebb readiness
Signed-off-by: Michal Bukowski <michal.bukowski@intel.com>
=> cavs: memory bank powerup flow adjustment

src/audio/module_adapter/module_adapter.c
The following problem is observed when testing pause functionality:
in a case of a playback stream host -> mixin -> mixout -> DAI where host and mixin belong to the pipeline A and mixout and DAI belong to pipeline B, pipeline B is scheduled before A. So at start we get: scheduler start
B: no data
A: read 1 period of data
scheduler sleep
(1 period of data pending in pipeline A)
scheduler start
B: send 1 period of data out
A: read 1 period of data
scheduler sleep
(1 period of data pending in pipeline A)
PAUSE
RELEASE
scheduler start
B: old data before sleep isn't sent because A is PAUSED A: read 1 period of data
scheduler sleep
(2 periods of data pending in pipeline A)
...
With repeated pause-release cycles this leads to buffer overrun. To fix this allow sending out data by pipeline B when …
=> module-adapter: allow different statuses

west.yml
Pull in following rimage changes:
3863e94fa5d3 Don't convert ROM addresses to cached aliases 1e0a85b44a19 config:tgl/tglh: Do not set cached/uncached address aliases 9b507ecc82d9 config: set cached and uncached aliases for affected platforms def9d51d7d81 Fix regression - make default return code an error d48ae7aadaa4 config: mtl: Set init_config for smart amp b5d762290f1a config: tgl-cavs: set init_config for smart test 15ea48177a2b src: adsp_config: Use reserved bits for module init config ec649f37d661 Convert all ELF addresses to cached for calculations
=> west.yml: upgrade rimage to 3863e94fa5d3

src/audio/smart_amp/smart_amp.c
There are two pops caused by SOF Firmware.
One pop occurs when switch from headphone to speaker:
When switch to headphone, audio playback data still remains in DSM processing buffer and not consumed by DMA.
So when switch back to speaker, the processing buffer is not clean, then pop noise occurs.
We can clean and reset the point for DSM internal processing buffer by called this function 'DSM_init' in function 'smart_amp_prepare'.
The other pop occurs when switch from speaker to headphone:
The feedback and feed-forward buffer processing should be independent.
But the number of frames processed by DSM feedforward is corrupted by feedback buffer calculation.
When capture pipeline exists, the number of frames for feedforward is always same as feedback.
And the number of frames for feedback is …
=> Fix Bug：Amp: eliminat pops when switch device between speaker and headphone.

src/audio/module_adapter/module/waves.c
Cherry-pick this commit now in case it gets omitted in the future.
Since the reset API commits for module_adapter were merged on this branch.  This one will be necessary for running Waves in module_adapter.
@barry-waves @Zames-Chang PTAL
=> cherry-pick: module_adapter: free memory resource

tools/tune/eq/eq_get_abi.m
No more need for hard-coded blob header, sof-ctl provides an up-to-date header so better to use it.
=> Tools: Tune: EQ: Use updated sof-ctl for tplg2 blob export

src/samples/audio/smart_amp_test.c
The avail_frames should not be used for other than the feedback buffer. Source/sink should be using the avail_passthrough_frames when calculating for the processing.
If we have feedback buffer then the avail_frames can be different than avail_passthrough_frames which will cause underrun reports.
=> smart_amp_test: Correct bytes calculations for processing

src/ipc/ipc-common.c
…omponent
It's not enough to look at the first component in the module's buffer list. Check all of them to make sure that they belong to different pipelines.
=> Fix pipeline source/sink component discovery and smart_amp_test 

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/components/micsel.conf, tools/topology/topology2/include/components/smart_amp.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-smart-amp-dai-copier-playback.conf
This is a replacement for #6799 and depends on the kernel PR https://github.com/thesofproject/linux/pull/4160
=> Add Smart amp feedback pipeline in nocodec topology

src/include/sof/samples/audio/detect_test.h, src/samples/audio/detect_test.c
During the component create (module init) we are not receiving the blob containing the sof_detect_test_config, only the base_cfg is received. The sof_detect_test_config content will be sent via large_config_set at a later time.
The blob received via large_config_set must be the same format as the blob with IPC3 but in runtime the sample_width from the blob is ignored and the audio_fmt.depth is used from the base_cfg.
=> detect_test: Split the module config and blob receiving for IPC4

src/arch/xtensa/include/arch/compiler_info.h, src/lib/lib.c
using incorrect names for compiler, missing ISA header for HiFi check, also should add inlines if we don't have the HiFi implementations
=> lib: fix compiler macro for vec_mem*

src/audio/selector/selector.c, src/include/sof/audio/module_adapter/iadk/system_service.h
New Xtensa xt-clang driver issues new warnings that were not present before when using xt-xcc driver.
Fixed warnings related to enum cast to other enum. Silenced warnings related to C/C++ interoptability.
=> Fixed warnings issued by new xt-clang compiler

src/audio/copier/copier.c
The loop should already handle the check for endpoint_num.
=> copier: remove redundant check

tools/topology/topology2/cavs-rt5682.conf
These changes adds a second stream for DMIC to the MTL Chromebook topology. The second stream can be used as a reference stream by the user. All the needed supporting changes were already merged via #6783.
Verified the functionality by simulataneously capturing data via both the streams and didn't see any issue in the recorded data as of now.
=> topology2: add second capture stream for DMIC0 for MTL topology

src/include/sof/math/exp_fcn.h, src/math/CMakeLists.txt, src/math/Kconfig, src/math/exp_fcn.c, test/cmocka/src/math/arithmetic/CMakeLists.txt, test/cmocka/src/math/arithmetic/exponential.c, zephyr/CMakeLists.txt
The 32-bit exponential library function has an accuracy of 1e-4 and a unit in last place error of 5.60032793 for inputs from -5 to +5 (Q4.28) and outputs from 0.0067379470 to 148.4131591026 (Q9.23).
=> Math: library: Add an exponential function

src/audio/eq_fir/eq_fir.c
Currently, the check to prevent too large filters from being loaded on GCC builds of SOF does not work correctly. This commit makes sure the error occurs immediately, instead of at the next coefficients change.
=> sof: audio: eq_fir: Fix GCC-specific check

tools/topology/topology2/cavs-rt5682.conf
pipeline ID 7 and 8 are taken by ECHO_REF_HOST
and ECHO_REF_DAI, so bump the ID to next free values.
=> topology2: cavs-rt5682: override BT playback pipeline id 

src/audio/dai-zephyr.c, west.yml
Includes patches to dai-zephyr.c to adapt to DMA interface change for DW/HDDMA drivers.
Total of 1168 commits, including following related to intel_adsp/sparse/dmic/xtensa:
8f5bcb2e76c3 intel_adsp: ace: fix linker script for xcc-clang compiler
18ce85c20130 tests: intel_adsp: ssp: fix dma data sizes
60a20471b561 intel_adsp: ace: enable interrupts for secondary core
6045eed2f361 intel_adsp: ace: enable core power gating
e1dbc2efef50 intel_adsp: ace: add core power off step
a99b073392fc intel_adsp: ace: d3 exit update
156c7cd21759 intel_adsp: bbzero/bmemcpy with picolibc fix
60196ca1126a cmake: sparse: deprecate old sparse support
91902c5fd4db cmake: add sparse support to the new SCA infrastructure
a684714d5c82 soc: intel_adsp: Correct HDA parameter docstrings
db495a5ebee3 xtensa: stop …
=> west.yml: upgrade Zephyr to 0c0d73721ed + adapted PR7110

src/audio/pipeline/pipeline-stream.c
Remove left-over unreachable code in pipeline_comp_trigger(): tje err == PPL_STATUS_PATH_STOP case is already processed and leads to a return from the function, therefore the same condition cannot be met a second time immediately after the return.
=> pipeline: (cosmetic) remove unreachable code

src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module_adapter.c
Fix a case of empty or inactive sources and `audio_stream_set_zero()` error handling
=> mixin-mixout: fix 2 corner cases

src/audio/dai-zephyr.c, src/lib/dai.c, west.yml
Start using new version of dai_config_get where config struct is given as pointer argument from outside.
=> dai: change to use new version of dai_config_get

src/audio/module_adapter/CMakeLists.txt, src/audio/module_adapter/module/volume/volume.c, src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi3.c, src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c, src/include/sof/audio/volume.h, test/cmocka/src/audio/volume/CMakeLists.txt, zephyr/CMakeLists.txt
Fix the peak volume calculation error in volume component, calculate the maximum absolute value of input as peak volume as close source firmware did.
Signed-off-by: Andrula Song <andrula.song@intel.com>
=> Audio: Fix the peak volume calculation error in volume component

app/debug_overlay.conf
Enable CONFIG_ASSERT=y in SOF debug overlay.
Also add a commented out list of additional useful Zephyr debugging
tools to the overlay. These incur a higher runtime cost, so are left
disabled by default. These are all debug tools that have been tested to
work with SOF and found useful.
Dependencies for merging (SOF):
Dependencies for merging (Zephyr):
=> app: zephyr: add CONFIG_ASSERT debug overlay

src/audio/chain_dma.c, tools/topology/topology2/avs-tplg/CMakeLists.txt
The known issues with the pipeline-free chain DMA implementation has now been solved, so we can re-enable chain DMA usage.
This reverts commit c3807ae4a7617314b753ae7713200e3ae918e039.
Signed-off-by: Jyri Sarha <jyri.sarha@intel.com>
=> Fix chain dma task handling issue and re-enable it.

CODEOWNERS
Fix minor misunderstanding in review of git commit 430893f18aac ("CODEOWNERS: refer to github documentation on file syntax")
=> [SKIP CI] CODEOWNERS: restore dropped comment

src/audio/module_adapter/module/volume/volume.c
If the initial_ramp is zero, the ramp_finished would always be true, that means we will never copy gain to circular buffer except we reset state.
=> Audio: Fix the volume change doesn't take effect issue

src/audio/chain_dma.c
schedule_task_free() might be a blocking call. E.g. the Zephyr LL-scheduler implementation can call k_sem_take(). Do not call this function with a spinlock held.
Link: https://github.com/thesofproject/sof/issues/7156
=> audio: chain_dma: do not hold spinlock when calling schedule_task_free

tools/topology/topology2/include/components/gain.conf
The previous value 10 is only 0.1 us that disables the gain ramp totally and causes harsh sounding volume transitions.
=> Tools: Topology2: Change PGA widget curve_duration to 20 ms

scripts/xtensa-build-zephyr.py, west.yml, zephyr/CMakeLists.txt
Release toolchain for Intel Meteorlake board is Xtensa RI-2022.10.
Upgraded toolchain to final version. New Xtensa toolchains does not support obsolete xt-xcc driver anymore,
so we need to switch to new xt-clang driver.
In this PR:
- modified `xtensa-build-system.py` to build mtl platform with new Xtensa toolchain version RI-2022.10 and core ace10_LX7HiFi4_2022_10
- modified processes and `xtensa-build-system.py` to use new compiler **xt-clang** as the xt-xcc is not available anymore
in new Xtensa toolchains.
- added requirement to SOF project to use C++17 standard. This was caused by changes in Zephyr https://github.com/zephyrproject-rtos/zephyr/pull/53405 that require C++14 standard.
MTL has cpp code that uses those headers but we can move straight away to C++17 as the newest standard …
=> board: intel_adsp_ace15_mtpm xtensa toolchain upgrade and enable xt-clang

scripts/xtensa-build-zephyr.py
This will be required when signing is transferred to `west build`, see
https://github.com/zephyrproject-rtos/zephyr/pull/54700
=> xtensa-build-platforms.py: build_rimage() only once at start

src/idc/zephyr_idc.c, src/include/sof/schedule/edf_schedule.h, zephyr/edf_schedule.c
One of the functions of the IDC thread is to execute IPCs on secondary cores, those have to be executed with the same priority as when they're run on the primary core, i.e. with the priority of the IPC thread. Set IDC thread priority equal to the IPC thread.
=> IDC: set IDC task priority equal to that of the IPC task

src/audio/chain_dma.c, src/schedule/zephyr_ll.c
Zephyr LL-scheduler is supposed to be able to handle tasks, removed or added while the scheduler is executing. However, there is a bug in that implementation. If the task, that is currently executing, is removed, its list head, that links it into the list of tasks, is initialised. So when trying to get a pointer to the next task we obtain a pointer to the same task.
BugLink: https://github.com/thesofproject/sof/issues/7084
=> ll-schedule: fix tasks removed during execution

src/audio/module_adapter/module/volume/volume_generic.c, src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi3.c, src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
while enable volume ramp, we may need to run the while loop in volume_process function several times, but we only update the read/write pointers of in/output streams in module_adapter copy function after the whole volume_process function finished. Then we would always get and store data from wrong address and lead to discontinuity waveform.
=> Audio: Fix the pointer update errors while volume ramp enabled

tools/topology/topology2/include/pipelines/cavs/wov-detect.conf, tools/topology/topology2/platform/intel/dmic-wov.conf
Minor wov topology issues, fix them in this patch, or the wov feature doesn't work
=> Fix wov topology issue

src/audio/module_adapter/module_adapter.c
The type member in struct sof_abi_hdr is used for component's specific blob type for IPC3, some module count on it to know the blob is for module config or module processing algorithm model. We should pass it to set_configuration ops.
=> module_adapter: use type in abi header as config_id for IPC3

src/audio/google/google_rtc_audio_processing.c, src/include/ipc4/aec.h, zephyr/CMakeLists.txt
It will use google rtc audio processing mock config
=> Ipc4 : add ipc4 support in google rtc audio processing

tools/topology/topology2/cavs-mixin-mixout-hda.conf, tools/topology/topology2/include/pipelines/cavs/highpass-capture-be.conf, tools/topology/topology2/sof-hda-generic.conf
This patch includes to sof-hda-generic.conf the new
highpass-capture-be.conf as passthrough-capture-be.conf replacement
that adds to DAI copier pipeline the IIR high-pass filter. The
response is hard coded to 0 dB amplification and 40 Hz cut-off.
The analog microphone headsets creates a strong DC input when the bias
voltage settles. It can be even full-scale and sound very loud. The
high-pass filter suppresses such input signal.
Fixes #7116
=> Tools: Topology2: Add high-pass IIR to HDA analog capture

src/audio/chain_dma.c
This was not the correct fix for the ll timer free crash issue. Now that the correct fix[1] is found and merged, this workaround can be removed.
[1] b3a808afa8c7 "chain-dma: fix scheduling exception"
This reverts commit 60e9e97e0df842c3030c0772b02120c807f6721a.
This should not be merged before https://github.com/thesofproject/sof/pull/7138 is in.
=> Revert "hda: chain dma: cancel task before freeing it"

src/audio/data_blob.c, src/audio/eq_fir/eq_fir.c, src/include/sof/audio/data_blob.h
These two commits allow the FIR EQ implementation to check for new data inside the set_config function and reject any invalid configuration at that point in time, as opposed to during playback where that currently leads to the playback being aborted (and an xrun happening).
=> Enhance FIR EQ configuration checking

tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/components/pipeline.conf
Adds kcps attribute to pipeline class with 400000 default value, and overrides the value in deepbuffer-playback pipeline with 50000.
=> topology2: Add kcps pipeline attribute

src/audio/Kconfig, src/ipc/ipc4/CMakeLists.txt, src/ipc/ipc4/notification.c, zephyr/CMakeLists.txt
- Add separate file for notifications initializations. All generic
initializations could be stored in one place
- Add initialization for generic xrun notification message which can be sent
by gateway.
=> Add xrun notification initialization

.github/workflows/daily-tests.yml
=> [SKIP CI] .github/daily-tests.yml: add sparse-zephyr.yml

src/audio/module_adapter/module/volume/volume.c
Fix the ramp gain setting bug to start ramp from the previous gain instead of zero.
=> Audio: Fix the ramp gain setting.

src/audio/copier/copier.c
Fix format validation in set_attenuation function.
In previus implementation, bitdepth was compared to sink->buffer_fmt value, which is an enum sof_ipc_buffer_format (interleaved or not).
Format bitdepth is represented by stream.frame_fmt (enum sof_ipc_frame), so it should be compared to this value.
=> copier: fix format check for set_attenuation

.github/workflows/sparse-zephyr.yml
Fixes commit 98b4625a0d8d (".github/daily-tests.yml: add sparse-zephyr.yml") and daily tests which just started failing as found by @aborisovich in
https://github.com/thesofproject/sof/actions/runs/4333619550 and others (thanks!).
=> [SKIP CI] .github/sparse-zephyr: add missing workflow_call to fix daily tests

src/audio/selector/selector.c, src/include/sof/audio/selector.h
This patch converts the selector module to use base config extension for module init, which ensures only base_cfg and base_cfg_ext is received in module init, and align the init blob format with other modules.
The selector module is using the module adapter interface, and it has one input and one output, the input format(base_cfg) is already handled with module adapter, we only need to handle the output format. 
@ranj063 I suppose that the nb_input_pins/nb_output_pins in base_cfg_ext could be zero, this help us to save some memory. If it is not the case, please let me know,  I will also add the input pin format in comp_data (through the input format will never be used in the fw).
=> selector: convert selector module to use base config extension

tools/topology/topology2/cavs-sdw.conf
This patch changes the DAI passthrough pipeline in cavs-sdw.conf
based topologies to similar pipeline but with IIR high-pass. The
cut-off frequency is 40 Hz and gain is 0 dB. The same high-pass
is used for HDA codec.
The change suppresses most of DC signal pop noise from the
beginning of capture or after press of headset button.
The impacted topologies from current build are:
cavs-sdw, mtl-sdw, sof-tgl-rt711-rt1316-rt714,
sof-adl-rt711-l0-rt1316-l12-rt714-l3,
sof-tgl-rt715-rt711-rt1308-mono, sof-tgl-rt711-rt1308-4ch,
sof-adl-rt711-4ch, sof-mtl-rt711-4ch
=> Tools: Topology2: Add high-pass IIR to SDW headset capture

src/audio/module_adapter/module/volume/volume.c, src/audio/module_adapter/module/volume/volume_generic.c, src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi3.c, src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c, src/include/sof/audio/volume.h, test/cmocka/src/audio/volume/volume_process.c
Add support for LargeConfigSet:SET_ATTENUATION IPC.
The purpose is to add attenuation adjustment for peak-meter.
To properly mix multiple streams without saturation, driver configures
attenuation to the input copier of each playback stream that is going
to be mixed into one output stream. In some topologies, PeakVol is
placed behind the copier with attenuation, hence its peak-meter value
is artificially scaled by FW. To report valid peak-meter value, FW has to
adjust the measurement by reverting attenuation provided in copier.
Missing implementation of SET_ATTENUATION for peak-meter blocks all Windows playback scenarios.
=> peakvol: add peak-meter attenuation adjustment

src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module_adapter.c, src/audio/pipeline/pipeline-graph.c, src/audio/pipeline/pipeline-stream.c, src/include/sof/audio/buffer.h, src/ipc/ipc-common.c, src/ipc/ipc-helper.c
buffer_from_list() is always used for buffer objects, the type is always struct comp_buffer. Hard code the type instead of always specifying is as a parameter.
=> buffer: simplify buffer_from_list()

src/audio/copier/copier.c, src/audio/host-zephyr.c, src/include/ipc4/copier.h, src/include/sof/audio/host_copier.h
Currently, copier actually created 2 devices for data input, it is
host and copier, hence there are two times copy from DMA buffer
to local buffer then to component buffer.
This PR intend to remove host device and one more time copy
through use host data to handle host interface calling.
Basically, there are several steps to go there:
1. Add host data to copier data structure.
2. Share host data structure to copier by add a host copier common header file.
3. In copier, all host related ops calling should be replaced with new host exposed interface.
4. Remove one more time copy and host endpoint buffer.
5. Remove host device.
Performance data:
1. mcps, saved 1.9mcps, 5.9 --> 4.0, 33% saved for copier.
Before: comp:0 0x40000 perf comp_copy samples 48 period 1000 cpu avg 586 peak 598
After: …
=> Optimize host copier with one less buffer copy

src/lib/clk.c, src/platform/amd/rembrandt/lib/clk.c, src/platform/amd/renoir/lib/clk.c, src/platform/imx8/lib/clk.c, src/platform/imx8m/lib/clk.c, src/platform/imx8ulp/lib/clk.c, src/platform/intel/ace/lib/clk.c, src/platform/intel/cavs/lib/clk.c, src/platform/mt8186/lib/clk.c, src/platform/mt8188/lib/clk.c, src/platform/mt8195/lib/clk.c, xtos/include/rtos/clk.h, zephyr/include/rtos/clk.h
select_cpu_clock() on cAVS currently takes all the clock locks while adjusting them. And that function is called from clock_set_freq() which also takes one of those locks, which leads to a recursive spin-lock. To fix that remove per-clock spin-locks and use a global clock lock instead.
=> clock: replace per-clock locks with a global one

west.yml
Pull in following rimage changes:
d32db50 mtl: add Aria module to extended manifest
5bc2010 rimage: fix build error
35bc644 mtl: add eq-iir and fir support
6fad356 rimage: Removed hash context from image structure
6c7a151 hash: Remove old hash functions
d258ea2 manifest: pkcs1_5: Use new hash functions
2bd8be3 hash: New hash functions
93c5e8b misc_utils: Move byte_swap function to new misc_utils.c file
9ce1cc8 ext_manifest: Fix fw_ext_man_cavs_header version
a4ca53c toml_utils: Adding support for decimal numbers in hex parser
5ebbd65 rimage: use hex number
36c0c90 elf: Use the get_file_size function
98c7f7b manifest: Use the get_file_size function
6a64cb9 file_utils: Add a new get_file_size function
055ea7e file_utils: manifest: ext_manifest: Add new create_file_name function
fed69d4 …
=> west.yml: upgrade rimage to d32db50

src/audio/module_adapter/module/volume/volume.c, src/include/sof/audio/volume.h
This patch saves about 15% of processing time or about 0.9 MCPS
during volume ramp.
The volume_ramp() functions are inlined to volume_process() function. The
other use of function in idle is replaced by volume_ramp_check().
In ramp calculation the division in ramp time calculation is converted
to faster multiplication with inverse of sample rate.
The unnecessary checks for vol greater than vol_max or vol_min are
eliminated by ensuring that tvolume[] is limited to vol_min and vol_max.
The clear of ramp_coef[] at ramp finish is unnecessary. It's
internal for linear ramp and is not used by the other ramp type.
The other optimization is to pass to ramp math functions struct
vol_data pointer instead of processing_module pointer to direct
access to needed state variables.
Signed-off-by: Seppo …
=> Audio: Simplify volume ramp functions

src/audio/copier/copier.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/audio/pipeline/pipeline-graph.c
The "failed to find dai comp or sink pipeline not running." error message has been bugging SOF developers since a long time without causing any apparent problems. Finally root-cause it and fix the underlying problem.
=> Fix "failed to find dai comp or sink pipeline not running."

tools/topology/topology2/include/components/gain.conf
The missing cpc in gain component results in wrong calculation for clock selection, and causes capture issues.
Link: https://github.com/thesofproject/sof/issues/7228
Link: https://github.com/thesofproject/sof/issues/7230
cherry-pick https://github.com/thesofproject/sof/pull/7242 for mtl-004
=> [FOR MTL-004] topology2: add cpc value for gain

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/development/CMakeLists.txt, tools/topology/topology2/include/pipelines/cavs/mixout-mixin.conf, tools/topology/topology2/platform/intel/nocodec-ssp0-2level.conf
Add a second level of mixin-mixout mixing and a PCM to the nocodec topology. Note, that it adds more hard-coded pipeline, route and PCM numbers in included topology files, but apparently there's no way ATM to specify those numbers at the caller level
=> topology2: add a mixin-mixout level to nocodec

tools/testbench/common_test.c, tools/testbench/topology.c
The simple {0} is not accepted by xt-xcc compiler. It gives "warning: missing braces around initializer".
Adding sufficient number of braces to match the struct definition fixes the build.
=> Tools: Testbench: Change struct of struct zeros initialize

scripts/xtensa-build-zephyr.py
xtensa-build-zephyr.py has always defined XTENSA_ and other environment variables in the current environment shared by all platforms. This was always bad but apparently never a problem until the addition of the new DEFAULT_TOOLCHAIN_VARIANT (xcc or clang) variable.
Before DEFAULT_TOOLCHAIN_VARIANT, each platform's environment would simply override the previous one. However with the new DEFAULT_TOOLCHAIN_VARIANT, the current environment has precedence for more flexibility. This makes each platform "spill" onto the next one and `xtensa-build-zephyr.py -p tgl mtl` fail like this:
```
-- Board: intel_adsp_ace15_mtpm
-- Found toolchain: xcc (/home/XCC/install/tools)
CMake Error at zephyr/cmake/compiler/xcc/generic.cmake:9 (message):
Zephyr was unable to find the toolchain.  Is the environment …
```
=> xtensa-build-zephyr: fix DEFAULT_TOOLCHAIN_VARIANT spill on next platf

.github/workflows/sparse-zephyr.yml, .github/workflows/zephyr.yml, zephyr/docker-run.sh
Windows has always been hardcoded to 0.15.2
Fixes the compare-linux-windows check that just started to fail in daily build https://github.com/thesofproject/sof/actions/runs/4400264770
The `:latest` zephyr-build image was just upgraded to the Zephyr SDK 0.16.0-rc1
https://hub.docker.com/layers/zephyrprojectrtos/zephyr-build/latest/images/sha256-91ef9e556aa2a6b5ee5397536e6c441b87fbaef82b9dfc0d12287c39d884d0af?context=explore
=> [SKIP CI] zephyr/docker-run.sh: hardcode Linux builds to Zephyr SDK 0.15.2

src/include/ipc/channel_map.h, src/include/ipc/topology.h, src/include/ipc4/base_fw.h, src/include/ipc4/gateway.h, src/include/ipc4/ipcgtw.h, src/include/ipc4/module.h, src/include/ipc4/peak_volume.h, src/include/ipc4/pipeline.h, src/include/ipc4/ssp.h, src/include/kernel/header.h, src/include/sof/audio/module_adapter/iadk/system_service.h
Make sure flexible arrays are only used in the end of structures and use them instead of 0-size arrays where possible.
=> Clean up flexible arrays

src/samples/audio/smart_amp_test.c
The config to get for smart_amp_test module is
struct sof_smart_amp_config, instead of the bigger
wrapper struct smart_amp_data, so the config size
should be the size of struct sof_smart_amp_config.
thanks @kv2019i for spotting the issue.
=> smart_amp_test: fix wrong config size in config get

scripts/xtensa-build-zephyr.py
Reduces duplication and provides more flexibility.
Also switch the list of platforms to a dict.
=> xtensa-build-zephyr.py: add new PlatformConfig dataclass

tools/topology/topology2/avs-tplg/CMakeLists.txt, tools/topology/topology2/avs-tplg/tplg-targets.cmake, tools/topology/topology2/development/CMakeLists.txt, tools/topology/topology2/development/tplg-targets.cmake, tools/topology/topology2/sof-ace-tplg/CMakeLists.txt, tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake
The CMakeList.txt files in tools/topology/ have always confused two
different things:
- the list of .tplg files to generate, and
- the CMake logic used to invoke alsatplg and generate them.
Separate the two at last thanks a dead-simple `include()` command.  If I
had knew it was so easy I would have done this much sooner.
The `tools/build_tools/` directory is identical before versus after this
commit.
This will make it much faster to identify what actually changes in
future commits and pull requests.  This will also make CODEOWNERS
smarter and reduce Github notification noise.
Don't do it for topology1 to minimize churn and git disruption in
backports. Topology1 is not very active any more whereas topology2 has
never been released yet.
=> topology2: extract new "tplg-targets.cmake" files from CMakeList.txt

scripts/xtensa-build-zephyr.py
Temporary solution until the `west sign` situation is finalized upstream, see zephyrproject-rtos/zephyr/pull/52942 and others.
Use shlex.split() that supports both some quoting and empty strings nicely.
(cherry picked from commit 190a0ab7b8741e9412bea31d86a6ef4bf851e031)
=> [STABLE v2.5] xtensa-build-zephyr.py: add --extra-rimage-args option

src/lib/ams.c
Current code may end up dereferencing null pointers in case memory allocations fail in ams_init(). Handle this with proper error handling.
=> ams: handle alloc failures in ams_init()

src/audio/dai-zephyr.c
If the max_block_count attribute is zero, this may lead to division by zero error. Handle this explicitly but reporting error if max_block_count is zero.
=> dai-zephyr: possible division-by-zero if max_block_count is zero

scripts/xtensa-build-zephyr.py
Fixes recent commit 8aab18351fd6 ("xtensa-build-zephyr: fix DEFAULT_TOOLCHAIN_VARIANT spill on next platf")
Some XtensaTools installation are missing this `default-params` symbolic link:
```
XtensaTools/config/
|-- X4H3I16w2D48w3a_2017_8-params
|-- X6H3CNL_2017_8-params
|-- cavs2x_LX6HiFi3_2017_8-params
`-- default-params -> cavs2x_LX6HiFi3_2017_8-params
```
Maybe it's missing when installing with the graphical interface?
This symbolic link is surprisingly enough to make `xt-objcopy` work _without_ the XTENSA_ variables. But when the variables _and_ the link are both missing, then `xt-objcopy` fails with the usual error:
```
in current dir: work/current/sof; running command:
XtDevTools/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-objcopy
--remove-section .comment …
```
=> xtensa-build-xephyr: fix xt-objcopy failure when default-params missing

src/audio/dai-zephyr.c, src/audio/module_adapter/module/volume/volume.c, src/ipc/ipc4/handler.c, src/lib/ams.c, src/samples/audio/smart_amp_test.c
Set of fixes to issues found via static code analysis.
=>  [stable-v2.5] Backport of fixes

src/audio/module_adapter/module/iadk_modules.c
iadk_modules_init() already has a pointer for mod->priv, use it.
=> iadk: (cosmetic) use an existing pointer

tools/topology/topology2/cavs-sdw.conf
For some reason the input valid bit depth was 16. But the output valid bit depth of the previous widget is 32. Fix it to 32 now.
Fixes: #7240
=> topology2: cavs-sdw: set capture host in_valid_bit_depth = 32

tools/tplg_parser/tokens.c
Pointer arithmetic with void pointer is not allowed. Functions get_token_uint32_t() and get_token_comp_format() are updated to handle correctly the bytes offset.
=> Tools: Tplg_parser: Fix void pointer arithmetic

src/include/sof/ipc/topology.h, src/ipc/ipc4/handler.c, src/ipc/ipc4/helper.c
Current pipeline implementation assumes that modules are bound one by one from input to output gateway (Host to DAI or DAI to Host). If neighbor module does not have direction configured, FW returns error.
This assumption is incorrect. Driver can bind modules that are not yet bound to any gateway. FW should check connections only when driver finish binding all modules and set pipeline state.
Note: This problem blocks all streams creation by Windows OED. OED playback and capture consist of 3 pipelines. Driver first binds modules inside pipelines and only then bind pipelines. When binding modules in inner pipeline, they do not have reference to gateway.
This patch resolves critical issues for Windows:
https://github.com/intel-innersource/drivers.audio.firmware.converged/issues/453 …
=> ipc4: update comp direction on pipeline complete

src/schedule/zephyr_dp_schedule.c
Fix below sparse warnings:
zephyr_dp_schedule.c:134:20: warning: incorrect type in argument 1 (different address spaces)
zephyr_dp_schedule.c:348:36: warning: incorrect type in assignment (different address spaces)
introduced by 3ee1d787
=> schedule: fix address space mismatches

src/include/ipc4/gateway.h, src/ipc/ipc4/dai.c
In ipc4/alh.h we have:
```
#define IPC4_ALH_MULTI_GTW_BASE 0x50
```
In ipc4/gateway.h:
```
#define ALH_MULTI_GTW_BASE 0x50
```
These were added almost simultaneously by two separate pull-requests. No need to have them both.
is_multi_gateway() is declared in ipc4/alh.h as:
```
/* Multi-gateways addressing starts from IPC4_ALH_MULTI_GTW_BASE */
#define IPC4_ALH_MULTI_GTW_BASE 0x50
static inline bool is_multi_gateway(const union ipc4_connector_node_id node_id)
{
return node_id.f.v_index >= IPC4_ALH_MULTI_GTW_BASE;
}
```
=> ipc4: Remove duplicate ALH_MULTI_GTW_BASE declaration

src/audio/Kconfig, src/audio/dai-zephyr.c
pause/release
Pause the DAI before the DMA and start the DMA before starting the DAI during release.
=> dai-zephyr: Fix the ordering of DAI and DMA triggers during

tools/testbench/CMakeLists.txt, tools/testbench/include/linux/types.h, tools/tplg_parser/CMakeLists.txt, tools/tplg_parser/include/linux/types.h
This patch adds a simplified linux/types.h into testbench headers to enable include of ALSA asoc.h to build without other difficult kernel headers content.
The include path for asoc.h is changed in fuzzer, tplg_parser, and testbench to be without prefix alsa/sound/uapi to allow the Makefile headers path to specify only the uapi directory.
This change avoids build fail with xcc toolchain that can't use the gcc toolchain headers from the system where the ALSA headers are located.
=> Tools: Testbench: Avoid need linux kernel headers in build

src/include/sof/coherent.h
If coherent object is at non-zero offset, the init call ends up invalidating data cache outside the allocated buffer.
All current users of "struct coherent" have the object as the first member, so nothing is broken with current code.
=> coherent: fix cache flush logic if coherent is not the first member

src/audio/aria/aria.c
Configure in/out buffer stream params.
In Windows scenarios, unconfigured values were causing zero-division exception in audio_stream_get_avail_frames.
Correct sample group size calculation for proper buffers management.
=> aria: configure stream params

west.yml
Upgrade rimage but keep Zephyr for now
=> Update rimage to a version, that doesn't need Zephyr ELF mangling

src/include/sof/ipc/common.h, src/include/sof/ipc/msg.h
=> Fix fuzz.sh regression and missing #includes exposed by recent XTOS/zephyr panic.h separation

west.yml
west.yml: upgrade zephyr to e40859f7
Total of 1128 commits, including following related to
dma-dw/intel_adsp/sparse/dmic/xtensa:
e40859f78712 Revert "dma: dw: Do not program SAR/DAR and CTL_HI/LO when using HW LLI"
7a85983ebcf2 xtensa: remove ELF section address rewriting
b32b321f502a dma: dw: Poll to check for channel disable with timeout
6226f9e6e44f dma: dw: fix the return value check
08d9efb202cc dma: dw: Do not program SAR/DAR and CTL_HI/LO when using HW LLI
045c68673491 dma: dw: Add a debug utility function
bd705e68b048 soc: xtensa: esp32: increase shared memory region
9854c915ffdf intel_adsp: cpu init refactor
9d5c21d58003 dts: xtensa: nxp: remove unused include
68c1cafb411e intel_adsp: dts: ace: lower case 71C00 to fix DTC warning
a8c0123d3c54 intel_adsp: cmake: …
=> west.yml: upgrade zephyr to e40859f7

src/include/sof/coherent.h
When adding object allocation to the coherent API the size alignment was misplaced, re-opening a possibility for cache corruption when sharing cache lines with adjacent allocations. Move alignment to the correct places.
=> coherent: fix allocation size

src/drivers/imx/interrupt-irqsteer.c, src/drivers/imx/sdma.c, src/drivers/imx/timer.c
Remove unnecessary blank lines before a close brace as reported by checkpatch script
"CHECK: Blank lines aren't necessary before a close brace '}'"
=> drivers: imx: remove unnecessary blank lines

src/audio/copier/copier.c, src/audio/dai-zephyr.c, src/audio/host-zephyr.c, src/include/sof/audio/ipc-config.h
Add fast mode which enables to support unlimited transfer size (more than
ibs/obs) between a dma buffer and the copier. Enable it to satisfy
specific module requirements to guarantee enough data size to decoders or
from encoders since the pcm audio period size does not apply to variable
size frame.
=> dai: host: add fast mode

src/drivers/imx/ipc.c
Remove unnecessary blank line after '{' as reported
by checkpatch:
"CHECK: Blank lines aren't necessary after an open
brace '{'".
Signed-off-by: Alaa Emad <eng.alaaemad.ae@gmail.com>
=> drivers: imx: ipc: remove unnecessary blank line

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/development/tplg-targets.cmake
There is pinmux conflict between SSP1 and DMIC on MTL, as there are other SSPs can be used, we don't include SSP1 pipelines only for mtl to unlock DMIC test.
=> topology2: cavs-nocodec: include SSP1 pipelines conditionally

src/audio/module_adapter/module/volume/volume.c
When calculating the time_ratio, a situation may occur where cd->initial_ramp is equal to zero. To avoid dividing by zero it is necessary to insert an additional condition
=> peakvol: prevent division by zero

tools/topology/topology2/development/tplg-targets.cmake
MTL nocodec devicies have been configured with DMIC 4 channels. The topology should be aligned with it.
=> topology2: cavs-nocodec: set dmic 4 channels for MTL

src/audio/mixer/mixer.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/mixer.h
[audio: mixer: Improve handling of inactive input streams](https://github.com/thesofproject/sof/commit/cdd2a88cb7dd3b969b22ae210079866578714a87)
This helps the mixer dynamically add/remove input streams when needed. Without this commit I would have the issue where the mixer would read from inactive inputs and outside the used portion of the corresponding input buffers.
[audio: module_adapter: Ensure prepare always runs on modules](https://github.com/thesofproject/sof/commit/bb5052355eb74fc59aa1ed8441cfb7ed4336be7e)
This commit makes sure I can actually start two streams with a delay on different mixer inputs (as opposed to in quick succession, as if given via the & symbol in a shell)
CC: @dbaluta
=> Fix handling of the mixer-module adapter combo on IPC3 platforms

tools/topology/topology2/cavs-mixin-mixout-efx-hda.conf, tools/topology/topology2/cavs-mixin-mixout-hda.conf, tools/topology/topology2/cavs-nocodec-bt.conf, tools/topology/topology2/cavs-rt5682.conf, tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/cavs-src-mixin-mixout-hda.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-be.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-efx-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-smart-amp-dai-copier-playback.conf, tools/topology/topology2/platform/intel/bt-generic.conf, tools/topology/topology2/platform/intel/hdmi-generic.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf, tools/topology/topology2/sof-hda-generic.conf
Rename passthrough-capture.conf to be-dai.conf
And remove setting the default node_type in the BE DAI pipeline class definitions and set them during pipeline object instantiation based on the DAI type.
=> Some more topology cleanups

src/audio/mixer/mixer.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/mixer.h
This backports 3 mixer fixes introduced with switching to new module_adapter interface.
73fc99045 audio: module_adapter: Ensure prepare always runs on modules
70388f635 audio: mixer: Improve handling of inactive input streams
e81c67007 mixer: skip inactive source
=> Backport mixer fixes to stable-v2.5

src/include/sof/schedule/ll_schedule.h, src/platform/imx8/platform.c, src/platform/imx8m/platform.c, zephyr/CMakeLists.txt, zephyr/Kconfig
DMA domain with Zephyr works fine for i.MX platforms. So, remove "experimental" from description and enable it by default for i.MX platforms.
Second patch enables tracing for i.MX platforms with zephyr.
=> Compile DMA domain by default for i.MX with Zephyr & enable tracing on i.MX platforms

tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake
This change sets USE_CHAIN_DMA=true for sof-hda-generic-2ch
and sof-hda-generic-4ch mtl targets in sof-ace-tplg directory.
=> topology2: Enable chain DMA for MTL sof-hda-generic* topologies

tools/topology/topology1/platform/intel/intel-generic-dmic.m4, tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
When GOOGLE_RTC_AUDIO is applied, Speaker and DMIC pipeline tasks are scheduled in the same domain. The AEC function in GOOGLE_RTC_AUDIO has the hard requirement for input sample synchronization between DMIC input and Echo reference (sourced from Speaker).
At present, both pipelines are pri-0 so the task order in schedule list depends on which pipeline starts first. DMIC pipeline task needs the most computation cycles due to AEC and NR processings, even more than the entire schedule period in peak. If DMIC is scheduled former than Speaker, the synchronization may be broken by the peak of DMIC task which punts Speaker task to the next period.
To avoid the above case, this commit sets DMIC as pri-1 on GOOGLE_RTC_AUDIO applied. It guarantees that DMIC task will be always put after Speaker …
=> topology1: set lower priority for DMIC task in GOOGLE_RTC_AUDIO case

src/audio/Kconfig, src/audio/data_blob.c, src/audio/module_adapter/module_adapter.c, src/audio/tdfb/tdfb.c, src/audio/tdfb/tdfb_direction.c, src/audio/tdfb/tdfb_generic.c, src/audio/tdfb/tdfb_hifi3.c, src/audio/tdfb/tdfb_hifiep.c, src/include/sof/audio/component.h, src/include/sof/audio/tdfb/tdfb_comp.h, tools/testbench/common_test.c, tools/testbench/include/testbench/common_test.h
This patch converts the time domain fixed beamformer (TDFB) into module adapter API.
=> Audio: TDFB: Convert to module adapter

app/sample.yaml
Remove old platforms from zephyr testcase file:
- intel_adsp_cavs15
- intel_adsp_cavs18
- intel_adsp_cavs20
=> app: remove old cavs platforms

src/platform/intel/ace/platform.c
Fixes related to cpu-clock-manager.
Fix for Windows OED scenarios, where driver sends LargeConfigSet::RegisterKcps. Such call was causing unexpected behavior, because cpu-clock-manage API is not used in platform_init when registering clock.
=> platform: ace: register clock using core_kcps_adjust api

src/drivers/imx/sai.c
On i.MX8MP, the SAI MCLK is bound with TX/RX enable bit. Therefore, in order to enable MCLK, we need to enable the transmitter.
This fixes a "wm8962 2-001a: DC servo timed out".
=> imx: sai: enable transmitter to output MCLK

src/audio/mixer/mixer.c
The previous patch 908876cc5f introduced a bug where the wrong input buffer had the "consumed" field updated. This affected playing from _only_ the second input stream in weird ways (specifically, sound was slower and every other period I'd get a "no bytes to copy" message from the active host component).
This patch fixes the indexing for that update.
Fixes: 908876cc5f "audio: mixer: Improve handling of inactive input streams"
(cherry picked from commit 5da0812a81cb4e9aa64c35a210c68749f5474943)
=> [BACKPORT to stable-v2.5] audio: mixer: Fix inactive streams handling

scripts/xtensa-build-zephyr.py
This is a typical example of why environment variables are (a sometimes necessary) evil: imagine you're trying to reproduce exactly the `west build` command run by xtensa-build-zephyr.py when building with the `xt-xcc` toolchain. So you would typically look at the logs, feel lucky that it shows the extra environment variables used and copy them:
```
XTENSA_TOOLCHAIN_PATH=/srv/home/jenkins/xcc/install/tools
TOOLCHAIN_VER=RG-2017.8-linux
XTENSA_SYSTEM=/home/jenkins/xcc/install/builds/RG-2017.8-linux/cavs...
In dir: workspace/sof; running: west build ...
```
Except this won't work because there's one variable currently missing: `ZEPHYR_TOOLCHAIN_VARIANT`!
Of course there could be more in the future.
Fix this by leveraging the recent os.environ.copy() added by commit 8aab18351fd6 …
=> xtensa-build-zephyr.py: log ALL "evil" environment differences

src/audio/module_adapter/module_adapter.c
When module_prepare() fails we need to return to calling module the exact specific error not just -EIO.
There is no real use for Host AP to receive an error code that doesn't reflect the actual error.
=> module_adapter: Propagate error from module specific callback

src/include/sof/math/numbers.h
Move the ROUND_DOWN() definition to the nearby #ifndef __ZEPHYR__ block.
The previous `#ifndef ROUND_DOWN` logic depends on the #include order, so it fails sometimes.
Fixes commit a6f8daec2acb ("kpb: add micselection function")
Fixes XCC compilation failure with
```
./scripts/xtensa-build-zephyr.py  mtl --cmake-args='-DEXTRA_CFLAGS=-Werror'
- In file included from sof/src/audio/src/src_hifi4.c:22:
zephyr/include/zephyr/sys/util.h:238:9: warning:
'ROUND_DOWN' macro redefined [-Wmacro-redefined]
^
sof/zephyr/../src/include/sof/math/numbers.h:33:9:
note: previous definition is here
```
=> numbers.sh: do not (re)define ROUND_DOWN() if __ZEPHYR__

src/samples/audio/smart_amp_test.c
Code in unbind is looking at wrong field for queue-id. This works some of the time, but in some cases leads to access to freed heap data and later to heap corruption.
Link: https://github.com/thesofproject/sof/issues/7191
=> smart_amp_test: fix unbind implementation

src/audio/module_adapter/module/cadence.c
Use LOG_MODULE_REGISTER() to register cadence in the Zephyr logger framework.
=> cadence: register module logs in Zephyr

.github/workflows/zephyr.yml
Recent experience has shown that upstream Zephyr regressions are much more common than platform-specific failures. So move the Zephyr version in first position, so this will group zephyr regressions and make them much more obvious.
Use very short keys for the revisions because the left column in Github's results "checks" tab is very narrow and cannot be resized.
=> [SKIP CI] .github/zephyr: move zephyr revision in first results matrix position

zephyr/lib/alloc.c
This commit places the heap inside the .bss section for all ARM64 platforms.
=> zephyr: lib: alloc.c: Add heap for ARM64 platforms

src/include/sof/debug/gdb/gdb.h
GDB debug should only be used when CONFIG_DBG_DEBUG=y. On ARM64 platforms with Zephyr, including this header will cause compilation errors due to the fact that they don't have an arch/ entry. This commit fixes this issue by conditionally defining all symbols based on CONFIG_GDB_DEBUG.
=> include: sof: debug: gdb: gdb.h: Add ifdef guard for symbol definition

src/audio/dai-zephyr.c
buffer_ptr is no longer valid in dai-zephyr.c, remove it.
=> dai-zephyr: remove not used pointer and its assignment

tools/topology/topology2/include/common/input_audio_format.conf, tools/topology/topology2/include/common/output_audio_format.conf, tools/topology/topology2/include/common/tokens.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-smart-amp-dai-copier-playback.conf
Separate the pin index token ID for input/output pin index to avoid collisions between the two and incorrect pin index parsing in the kernel.
Corresponding kernel PR: https://github.com/thesofproject/linux/pull/4311
There is no dependency between the two in terms of merging.
=> topology2: tokens: Split the tokens for input/output pin index

tools/topology/topology2/include/components/mixin.conf, tools/topology/topology2/include/components/mixout.conf, tools/topology/topology2/include/pipelines/cavs/deepbuffer-playback.conf, tools/topology/topology2/include/pipelines/cavs/host-copier-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-smart-amp-dai-copier-playback.conf, tools/topology/topology2/platform/intel/hdmi-generic.conf
The 24-bit formats defined in topologies will never be used because the mixin/mixout only support 32-bit format. So remove these audio formats from the component and pipelines audio format definitions.
Depends on https://github.com/thesofproject/linux/pull/4313 (merged)
=> topology2: Remove unnecessary audio formats 

tools/topology/topology2/avs-tplg/tplg-targets.cmake, tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf
NUM_SDW_AMPS refers to how many sdw links are used by the amp pcm. Rename to NUM_SDW_AMP_LINKS for less confusing.
=> topology2: rename NUM_SDW_AMPS to NUM_SDW_AMP_LINKS

src/audio/src/src.c
No need for type-casting: void * is compatible with any pointers and both pointers already have the __sparse_cache annotation. Dropping it causes sparse warnings.
=> src: drop wrong type-casts to match cache annotations

zephyr/include/sof/compiler_info.h
This is required by ARM64 platforms as they don't have an arch/compiler_info.h so the compilation would fail.
=> zephyr: include: sof: Add Zephyr version of compiler_info.h

scripts/xtensa-build-zephyr.py
--cmake-args is actually safe, just a bit slower. See explanation in
https://github.com/zephyrproject-rtos/zephyr/pull/56671
Fixes unnecessary restriction added by commit https://github.com/thesofproject/sof/commit/9fb7a607ebdaf2049aaa89dd1a2ab1c9758a310b
("xtensa-build-zephyr.py: fix -C option so it can support whitespace")
Also warn for overlays because they act the same.
=> xtensa-build-zephyr.py: downgrade --cmake-args restriction to a warning

src/audio/chain_dma.c, src/audio/copier/copier.c
In most of the user code buffer control structures should only be accessed after acquisition, not via their raw pointers.
=> buffer: fix access without acquisition

src/audio/host-legacy.c, src/audio/host-zephyr.c, src/include/sof/audio/host_copier.h
This fixes breakage introduced by #6951 to legacy driver builds
=> Fix legacy Zephyr builds with non-Zephyr native drivers

zephyr/lib/alloc.c, zephyr/lib/cpu.c, zephyr/wrapper.c
Since i.MX93 doesn't have a soc.h file in Zephyr nor does it need one right now, instead of adding an empty soc.h to Zephyr just encase the '#include <soc.h>' statement in an ifdef block.
=> Remove unused soc.h header inclusions

zephyr/include/rtos/interrupt.h
This PR introduces all required interrupt-related changes for ARM64 platforms.
=> Add interrupt-related changes for arm64-based platforms

tools/topology/topology1/m4/buffer.m4
Calculation of SOF_TKN_BUF_SIZE in COMP_PERIOD_FRAMES() macro led to incorrect results with large period size values. For example at 48000Hz sampling rate, period size larger than 44739us would be incorrectly calculated.
This happens as m4 eval does arithmetic in 32bit signed values and multiplication of period size and sampling rate can easily exceed 2^31.
Fix the issue by splitting the arithmetic in steps that fit available value range.
Link: https://github.com/thesofproject/sof/issues/7476
=> topology1: fix buffer size calculation if period-size >44ms

src/drivers/imx/ipc.c, src/drivers/imx/sai.c
`drivers: imx: ipc`
Split long line into two short lines
at 135: FILE: src/drivers/imx/ipc.c:135:
"CHECK: line length of 103 exceeds 100 columns"
Modified to match the alignment of the open parenthesis
at 227: FILE: src/drivers/imx/ipc.c:227:
"CHECK: Alignment should match open parenthesis"
Split long line into two short lines
at 309: FILE: src/drivers/imx/ipc.c:309:
"CHECK: line length of 101 exceeds 100 columns"
`drivers: imx: sai`
Modified to match the alignment of the open parenthesis
at 353: FILE: src/drivers/imx/sai.c:353:
"CHECK: Alignment should match open parenthesis"
=> drivers: imx: fix checkpatch styling error

src/include/sof/lib_manager.h, west.yml
Changed rimage submodule revision to 25804e7dc8ee37f3cb87b0a96b58300478cd3cff
lib_manager: Use correct manifest header from rimage
By mistake, the lib_manager module used a private manifest header from the rimage project. It included other private headers. Switched to the public header.
=> rimage: Update rimage revision

scripts/xtensa-build-zephyr.py, zephyr/CMakeLists.txt
**zephyr/CMakeLists.txt: remove '..' in include paths**
CMake seems to behave differently on Linux and Windows: it generates
different `-I` command line parameters. This results in spurious
`__FILE__` mismatches and non-reproducible builds when using
CONFIG_ASSERT, see example in https://github.com/thesofproject/sof/pull/7428.
On Windows, '..' seem resolved more often which also seems to convert
forward slashes to backslashes.
They are also less readable and wasting a bit of space. Remove them
using cmake_path(SET ...)
---------
Zephyr's `-fmacro-prefix-map` is working and keeps the builds reproducible when using a recent enough toolchain.
As found in the CONFIG_ASSERT PR https://github.com/thesofproject/sof/pull/6530#issuecomment-1482330214 this is not true for old Xtensa toolchains …
=> zephyr/CMakeLists.txt: remove '..' in include paths 

src/schedule/zephyr_dma_domain.c
We need to make the Zephyr DMA domain thread's priorty higher than the logging thread priority. If this is not done we may have some issues such as some buzzing noises appearing after resuming a paused stream. This was the case for i.MX93. Presumably this is because the SAI FIFO is underrun (please correct me if I'm wrong).
This fixes the issue on i.MX93 but will require some more tests to make sure that it doesn't break anything on the other i.MX boards which will use Zephyr DMA domain. This is why I added the [DNM] tag.
=> schedule: zephyr_dma_domain: Make thread priority higher

src/platform/Kconfig, src/platform/imx93_a55/CMakeLists.txt, src/platform/imx93_a55/include/platform/drivers/idc.h, src/platform/imx93_a55/include/platform/drivers/interrupt.h, src/platform/imx93_a55/include/platform/lib/clk.h, src/platform/imx93_a55/include/platform/lib/cpu.h, src/platform/imx93_a55/include/platform/lib/dai.h, src/platform/imx93_a55/include/platform/lib/dma.h, src/platform/imx93_a55/include/platform/lib/mailbox.h, src/platform/imx93_a55/include/platform/lib/memory.h, src/platform/imx93_a55/include/platform/lib/pm_runtime.h, src/platform/imx93_a55/include/platform/platform.h, src/platform/imx93_a55/include/platform/trace/trace.h, src/platform/imx93_a55/lib/clk.c, src/platform/imx93_a55/lib/dai.c, src/platform/imx93_a55/lib/dma.c, src/platform/imx93_a55/platform.c
This PR introduces all the necessary changes for running SOF using Zephyr and Jailhouse on i.MX93's A55 core.
Will update  https://github.com/thesofproject/sof/issues/7192 to contain a short description of our solution and all of its quirks. (**EDIT**: this is now up)
**EDIT**: Depends on Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/56713
=> Introduce i.MX93 platform support

src/schedule/zephyr_dma_domain.c
There's no need to clear IRQ mask on ARM64 architecture as there's currently no way to mask them. This commit aims to fix the compilation issues that would be caused by calling interrupt_clear_mask() on ARM64-based platforms.
=> schedule: zephyr_dma_domain: Conditionally call interrupt_clear_mask()

.github/workflows/zephyr.yml
Past Zephyr experience showed that CFLAGS is not enough to cover all cases: https://github.com/zephyrproject-rtos/zephyr/commit/8a603da6cde63
=> [SKIP CI] .github/zephyr: add -Werror to AFLAGS, not just CFLAGS

src/audio/asrc/asrc.c
Add missing buffer release calls in asrc_prepare().
=> asrc: fix buffer acquisition

src/lib/ams.c
When changing pointer type between different sparse address spaces, the change has to be forced to let sparse know, that this is intended and to avoid a warning. Fix such type cases in ams.c.
=> ams: fix sparse address space change

scripts/parse_sparse_output.sh
Catch the additional two warnings below:
```
warning: too many warnings
warning: cast removes address space
```
=> [SKIP CI] parse_sparse_output.sh: add "removes address space" and "too many"

.github/workflows/zephyr.yml
This makes sure Zephyr's -fmacro-prefix-map is working and keeps the
builds reproducible when using a recent enough toolchain.
As found in the CONFIG_ASSERT PR
https://github.com/thesofproject/sof/pull/6530#issuecomment-1482330214
this is not true for old Xtensa toolchains.
=> [SKIP CI] .github/zephyr: build with the debug overlay and CONFIG_ASSERT

src/ipc/ipc4/helper.c, zephyr/Kconfig
DP scheduler is intended to work on MTL and
future platforms only - has not been tested on
any legacy.
1) dependency on ACE to compile DP is introduced
2) when a DP module is to be created when DP
is disabled, module creation is rejected
=> ipc4: raise error when DP cannot be created

src/include/sof/common.h
Clang requires fields to have a constant size and does not support variable length array in structure causing build to to fail at compile_check()
```
error: fields must have a constant size: 'variable length array in structure' extension will never be supported
```
This change selects the compatible version of ALIGN_UP and ALIGN_DOWN macro when compiling with Clang.
While there's no official support for LLVM toolchain right now, this change should help in that direction.
=> common.h: Prevent error when compiling with Clang

scripts/xtensa-build-zephyr.py
As recommended by Andrey in #7364, reduce the noise and log the environment only for the `west build` command - unless the log level is increased with `-v`, then log for every command.
Also fix a very unlikely corner case where the caller would invoke execute_command() with `check=None` and get the opposite effect.
=> xtensa-build-zephyr.py: log environment changes only for `west build`

scripts/docker-run.sh, scripts/docker_build/sof_builder/Dockerfile
Upgrade Ubuntu to latest LTS version, 22.04.
This one line change is supposed to be enough but there is permission issue when UID is not matching with local UID.
```diff
-FROM ubuntu:20.04
+FROM ubuntu:22.04
```
All other lines are the fix for the permission issue.
=> [SKIP CI] docker: upgrade to ubuntu 22.04 as a base image

scripts/docker-run.sh
This reverts commit 80e9c3454a0a048704f863a52443b536a27a2410.
This was merged too early, there are still build issues and failures to solve first, notably issues caused by the now missing xtensa-cnl-elf-gcc (for TGL)
https://github.com/thesofproject/sof/actions/runs/4789961860/jobs/8518459642 https://github.com/thesofproject/sof/actions/runs/4789961859/jobs/8518459155 etc.
=> Revert "scripts/docker-run.sh: run with sudo-cwd.sh"

scripts/docker_build/sof_builder/Dockerfile
_[SKIP CI because there is ZERO CI using that file, it's used manually only. See #5073]_
TGL has always been using the `xtensa-cnl-elf` toolchain. That toolchain was removed by accident when cavs 1.8 support (including CNL) was removed by massive search/replace commit dc9ba281d76519 ("platform: remove support for cAVS 1.8 platforms")
=> [SKIP CI] scripts: Dockerfile: re-add TGL toolchain removed by accident

src/library_manager/lib_manager.c
Fix breakage introduced by 32e4f7e27a57 ("buffer: use an accessor to read struct audio_stream::end_ptr") which accidentally wrongly used audio_stream_get_end_addr() to access the .end_addr member of struct lib_manager_dma_buf.
=> lib-manager: fix compilation breakage

src/audio/mixin_mixout/mixin_mixout_generic.c
The copying part of the functions need to update the src/dst buffer pointers after each iteration to correctly account for the possible wrap of the buffer.
This was discovered while doing pause - 1sec_wait - resume - 3sec_wait cycles and around the 10th iteration audio became 'metallic' sounding.
Fixes: #7478 
Thanks @ranj063 to test with XCC which is not affected and pointing me to the correct path.
=> audio: mixin_mixout_generic: normal_mix: Update src/dst after each copy

src/audio/rtnr/rtnr.c
Earlier commits wrongly used struct audio_stream accessors to read members of struct audio_stream_rtnr in rtnr_copy_to_sof_stream(). Revert those changes.
=> rtnr: fix regression

tools/topology/topology2/development/tplg-targets.cmake, tools/topology/topology2/platform/intel/common_definitions.conf, tools/topology/topology2/platform/intel/deep-buffer.conf, tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake
Set the deep buffer PCM as D0I3 compatible only for MTL.
=> topology2: Set the deepbuffer PCM D0i3 compatibility conditionally

src/audio/pipeline/pipeline-graph.c
DSP panic during playback with suspend/resume test.
[  649.505750] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  649.505756] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP panic!
[  649.505757] sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (6)
[  649.505776] sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
[  649.505863] sof-audio-pci-intel-tgl 0000:00:1f.3: reason: runtime exception (0x6)
[  649.505864] sof-audio-pci-intel-tgl 0000:00:1f.3: trace point: 0x00004000
[  649.505865] sof-audio-pci-intel-tgl 0000:00:1f.3: panic at :0
[  649.505867] sof-audio-pci-intel-tgl 0000:00:1f.3: error: DSP Firmware Oops
[  649.505868] sof-audio-pci-intel-tgl 0000:00:1f.3: error: Exception Cause: LoadStorePIFDataErrorCause, …
=> DSP panic during playback with suspend/resume

scripts/xtensa-build-zephyr.py
Here I add the configuration options for building SOF on Zephyr for i.MX8, i.MX8X and i.MX8M platforms. No further changes on top of this are required for the builds to succeed, however I did not do any runtime testing of any of these.
=> Add XCC build support for Zephyr i.MX8 platforms

src/idc/zephyr_idc.c, west.yml, zephyr/lib/alloc.c
Use zephyr cache APIs instead of xtensa specific ones.
=> zephyr: use system cache API

src/audio/aria/aria.c, src/audio/buffer.c, src/audio/chain_dma.c, src/audio/copier/copier.c, src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/audio/google/google_rtc_audio_processing.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/audio/kpb.c, src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module_adapter.c, src/audio/mux/mux.c, src/audio/rtnr/rtnr.c, src/audio/selector/selector.c, src/audio/smart_amp/smart_amp.c, src/audio/src/src.c, src/audio/tone.c, src/include/sof/audio/audio_stream.h, src/include/sof/audio/buffer.h, src/ipc/ipc-helper.c, src/ipc/ipc3/dai.c, src/samples/audio/smart_amp_test.c
This makes `struct audio_stream` completely opaque to users, no direct access outside of audio_stream.h and buffer.c should happen to its fields after this.
=> buffer: add and switch to final read and write accessors for struct audio_stream

src/audio/copier/copier.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/include/sof/audio/host_copier.h, src/include/sof/lib/notifier.h
Using the notifier between the copier and the host makes little sense: it ends up in a direct function call, but before that it has to look for the correct callback in a global notifier list. The callback can perfectly be called directly instead.
=> host-zephyr: remove notifier, call the copier callback directly

src/ipc/ipc3/handler.c, zephyr/wrapper.c
In the case of i.MX93 Linux will send an IPC_FW_READY message to SOF and will expect to receive the following information in the hostbox:
1) reply structure
2) sof_ipc_fw_ready structure
3) sof_ipc_window structure
This flow is required because Jailhouse is currently controlled from user space. This means that SOF will be up before the platform driver from Linux so the IPC_FW_READY sequence can't be initiated by SOF.
=> Add support for SOF_IPC_FW_READY message initiated by host

src/audio/module_adapter/module/generic.c
When md->ops->reset() returns PPL_STATUS_PATH_STOP this means that reset is not propagated along the pipeline. This is a normal condition.
So do not print an error.
=> module_adapter: Don't print an error if reset path stops

scripts/docker-run.sh
There is a UID mistmatch and file permission problem. sudo-cwd.sh will switch id every docker run command.
80e9c3454a0a048704f863a52443b536a27a2410 was reverted due to missing a toolchain.
=> scripts/docker-run.sh: run with sudo-cwd.sh (Ubuntu upgrade of the Docker image)

tools/topology/topology1/CMakeLists.txt
This is to fix issue https://github.com/thesofproject/sof-bin/issues/121 for stable-v2.2 branch.
The ADL integration was botched with missing topologies and errors in topology names in the kernel.
Link: https://github.com/thesofproject/linux/issues/4111
(cherry picked from commit 57e976ec3854cfe4ca34211f6edc041909c9c24a)
=> stable v2.2: cherry pick missing ADL-es8336 topologies.

src/ipc/ipc4/helper.c
In IPC4, the component ID is entirely under the control of the input protocol, and as components of multiple types exist in the list, it's possible for protocol messages to fetch an incorrectly typed object, leading to crashes at runtime.
Force all usage to go through a get_comp() utility that does type checking.  There was already a similar utility for the special case of pipelines (which have a separate ID to query).
=> ipc4: Handle typing errors in component retrieval

tools/topology/topology2/include/components/src_format.conf, tools/topology/topology2/include/pipelines/cavs/host-copier-gain-src-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/src-gain-mixin-playback.conf
This patch avoids with development topology sof-hda-src-generic.tplg the playback start failure and error seen in trace "buffer: buffer_alloc(): new size = 0 is invalid".
The kernel selects in case of multiple output formats defined the format that matches the input. It then caused the obs to become zero. When the SRC is used in the mixin-based playback pipeline, its output format is limited to 32-bits format only. So replace the multiple output formats with a single 48K, 2ch 32-bit format.
=> Tools: Topology2: SRC format fixes

app/src/main.c
With Zephyr adopting a different type for 'main', adapt this application to match.
This is required when building without the `-ffreestanding` compiler flag as the C standard for "hosted" applications requires one of a small set of specific signatures for the `main` function.
=> app: Switch main return type to 'int'

.github/workflows/codestyle.yml, .github/workflows/installer.yml, .github/workflows/repro-build.yml, .github/workflows/testbench.yml, .github/workflows/tools.yml, .github/workflows/unit-tests.yml
Search and replace checkout@v2 with checkout@v3.
This finally gets rid of all warnings "Node.js 12 actions are deprecated".
We've been using v3 in a few other places and never met any backwards compatibility issue.
=> [SKIP CI] .github: upgrade all checkout actions to v3

scripts/rebuild-testbench.sh, scripts/set_xtensa_params.sh, tools/test/audio/comp_run.sh, tools/test/audio/process_test.m, tools/test/audio/test_utils/test_run.m, tools/testbench/common_test.c, tools/testbench/file.c, tools/testbench/include/testbench/common_test.h, tools/testbench/include/testbench/file.h, tools/testbench/testbench.c, tools/testbench/testbench_xcc_sections.txt, tools/testbench/topology.c, tools/tplg_parser/include/tplg_parser/topology.h
Now ready. see commit texts for description.
=> Tools: Testbench: xt-testbench

scripts/xtensa-build-zephyr.py
Remove one intermediate and unnecessary .ri file. Simplify the code and the build directory. Example below with `sof-mtl.ri` for better
readability but this applies the same to `sof-imx8.ri` and every other
`sof-$platf.ri` file.
There were 3 .ri copies before this commit:
```
build-mtl/zephyr/zephyr.ri
copied to  ->   build-mtl/zephyr/sof-mtl.ri
copied to  ->   build-sof-staging/___/sof-mtl.ri
```
Only 2 left after dropping the second and pointless copy:
```
build-mtl/zephyr/zephyr.ri
copied to  ->   build-sof-staging/___/sof-mtl.ri
```
Fewer copies means less wondering about what is what, two identical files in the same directory is at best pointless and at worst misleading.
The `build-mtl/` directory belongs to the zephyr build system exclusively, this wrapper script has no business …
=> xtensa-build-zephyr.py: drop intermediate build-$platf/sof-$platf.ri 

src/include/sof/samples/audio/smart_amp_test.h, src/samples/audio/CMakeLists.txt, src/samples/audio/smart_amp_test_ipc3.c, src/samples/audio/smart_amp_test_ipc4.c, zephyr/CMakeLists.txt
Convert the dummy smart_amp(smart_amp_test) module to use the module adapter interface. Add "id" into input_stream_buffer to record buffer id for feedback buffer identification.
=> Smart_amp: Convert dummy smart_amp component to use the module adapter

.github/workflows/codestyle.yml, .github/workflows/installer.yml, .github/workflows/pull-request.yml, .github/workflows/repro-build.yml
Let's not fall behind.
Ubuntu 22.04 is the latest runner offered by Github: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
=> [SKIP SOF-TEST] .github: upgrade most runners to latest Ubuntu 22.04

src/audio/copier/copier.c, src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/audio/pipeline/pipeline-stream.c, src/include/ipc4/alh.h, src/include/ipc4/copier.h, src/include/sof/audio/component.h, src/include/sof/audio/component_ext.h, src/include/sof/audio/dai_copier.h, src/include/sof/ipc/common.h, src/include/sof/lib/dai-legacy.h, src/include/sof/lib/dai-zephyr.h, src/ipc/ipc3/dai.c, src/ipc/ipc4/dai.c, tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-module-copier-capture.conf
This is a replacement for #7229 
It optimizes the DAI copier performance to bring its MCPS down to 3.8 and also saves memory by not creating an extra DAI device for every DAI copier. 
The limitation with this PR is that it restricts the DAI copier to have only a single sink for now (single sink != single endpoint. Multiple endpoints for SDW aggregation is still supported). Support for multiple sinks with both host and DAI copiers will be added in a follow up PR. (#7554 is a preview for multi-sink support in DAIs)
=> DAI copier optimization

tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/platform/intel/sdw-jack-generic.conf
We assume sdw jack is always there in a sdw topology. 
This commit make it be optional to deal with the sdw amp only case.
=> topology2: cavs-sdw: make jack optional

src/audio/base_fw.c, src/include/ipc4/notification.h, src/init/init.c, src/ipc/ipc4/handler.c, src/ipc/ipc4/helper.c, src/platform/posix/include/platform/drivers/alh.h, src/platform/posix/include/platform/lib/clk.h, src/platform/posix/include/platform/lib/dai.h, src/platform/posix/include/platform/lib/mailbox.h, src/platform/posix/include/platform/lib/memory.h, src/platform/posix/include/platform/platform.h, src/platform/posix/ipc.c, xtos/include/sof/compiler_attributes.h
Support for IPC4 protocol fuzzing with the existing rig.  Just select CONFIG_IPC_MAJOR_4=y and it will adjust as needed.  It seems to have pretty decent coverage as far as I've been able to check manually, has run on my system for about two hours now (running 64 instances in parallel), and has uncovered one bug (in #7528 -- that will obviously want to merge before this does).
@marc-hb I didn't adjust the existing fuzz.sh script in this PR, it's still doing IPC3 by default.  There are lots of ways to handle this: you could run the fuzzer twice in CI for each protocol, we could add new "posix" platform variants for each, etc...  Let me know what you'd prefer.
=> IPC4 fuzzing support

src/audio/ipcgtw.c
Zephyr logging macro comp_cl_err expands to many different logging frameworks depending on log configuration selected (possible z_log_minimal_printk, z_log_printf_arg_checker, cbprintf_package or even syscalls). There is no warranty that a format specifier passed as argument to %x will not be modified. Constant struct members should not be passed to this logging macro. Fixed by provoding macro with value copy.
=> fix: zephyr logging macro comp_cl_err accesses const struct member

src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c
The DMIC interface places 24-bit samples on the most significant bits of a 32-bit container. The correct conversion function for this gateway was used.
=> dmic: Use the correct 24 bit conversion function

tools/topology/topology2/cavs-nocodec-multicore.conf, tools/topology/topology2/development/tplg-targets.cmake
create another topology to test multicore since Currently we have done too much work in cavs-nocodec and CI test will be failed for FW main branch is not ready for multicore feature.
Discussed with @mengdonglin that we need a separate topology to enable multicore feature to help this feature development in FW. This topology is not very complex since it is for test only
=> topology2: enable multicore in nocodec topology for CI test

src/audio/module_adapter/module_adapter.c, src/audio/src/src.c, src/include/sof/audio/component.h, tools/testbench/common_test.c
This patch cleans up SRC component. There is no need to keep
IPC3 version build with legacy component interface. The patch
mainly removes code under CONFIG_IPC_MAJOR_3 and makes some
functions available for all builds from CONFIG_IPC_MAJOR_4.
The IPC4 capture issue is fixed by using the src_init()
IPC rates for source and sink rate initialize. It needs a
similar kernel update to always set those values. In practical
topologies in prepare the buffers may not contain the correct
stream information because the order of host copier and
dai copier pipeline prepare can be host first where capture
SRC is usually placed.
=> Audio: SRC: Audio: SRC: Use only module API and fix IPC4 capture direction

.github/workflows/ipc_fuzzer.yml, scripts/fuzz.sh
=> [SKIP SOF-TEST] .github: fuzz IPC4 too

src/platform/intel/ace/platform.c, west.yml, zephyr/include/sof/lib/cpu.h, zephyr/lib/cpu.c
Informing the primary core that the Idle thread on secondary core is ready. During the D3 exit flow thread is not initialize again, but restored from previously saved context.
Requires:
=> platform: ace: notifying about idle thread readiness

src/audio/buffer.c, src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/audio/ipcgtw.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/buffer.h, tools/testbench/file.c
When the DMA buffer is reallocated pass the alignment argument to honor the buffer address alignment that was used originally. Update the buffer_set_size() to pass the requested alignment and all its users. This is particularly needed in the case of host and DAI DMA buffers that query the buffer address alignment from the DMA driver while allocating the DMA buffers.
=> audio: buffer: Realloc buffer with alignment

src/drivers/intel/ssp/ssp.c
Mainline version of https://github.com/thesofproject/sof/pull/7564 
Link: https://github.com/thesofproject/sof/issues/7548
=> intel: ssp: drain RX fifo when starting

src/audio/copier/copier.c, src/audio/ipcgtw.c, src/include/ipc4/copier.h, src/include/sof/audio/ipcgtw_copier.h
With #6951, #7530, #7554 merged, host and dai device and endpoint buffer got removed from copier, this can save memory and mcps.
For ipc gateway, due to there is no extra copy, only copy from input to endpoint buffer, so buffer can't be removed, only device got removed.
With this patch, below purpose are met:
1. ipcgtw device removed, 112 bytes saved for each ipcgtw.
2. aligned usage model with host and dai.
3. prepare for upcoming copier modulization work.
=> Remove ipcgtw device to align with host and dai usage

src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c
When calculating the out_sample value,
the AE_SLAI32S function is used,
which rounds the result to the value 1/(-1),
resulting in a rectangular signal.
=> peakvol: correct volume processing function

.github/workflows/zephyr.yml
We import hal_xtensa indirectly through zephyr/west.yml.
When overriding the Zephyr revision in sof/west.yml to test the Zephyr main branch "zmain", we must also update the version of hal_xtensa specified in zephyr/west.yml. Stop doing a manual, single repo git fetch and use a submanifest to perform this correctly. This is exactly why submanifests/ were added in the first place.
These fixes the imx8m compilation error spotted and discussed in (unrelated) #7579 following the IMX rename
- https://github.com/zephyrproject-rtos/zephyr/pull/57084
- https://github.com/zephyrproject-rtos/zephyr/pull/57795
=> [SKIP SOF-TEST] .github/zephyr: align hal_xtensa when compiling with Zephyr main branch

src/drivers/intel/ssp/ssp.c
We have the fix #7577 merged in main branch. 
As we need this fix in production devices, please merge the fix in cavs2.5-001-drop-stable.
=> Bt ssp fix

src/audio/copier/copier.c
No change in functionality, just preparatory patches to remove the creation of DAI devices and endpoint buffers for the multi-endpoint DAI copier.
=> Preparation for multi-endpoint copier optimization

tools/topology/topology2/development/tplg-targets.cmake
Change NUM_DMICS to 2 and enable PDM1 only to reflect the tested configuration.
=> sof-lnl-nocodec-fpga: Change 2ch DMIC topologies

src/arch/xtensa/include/xtensa/config/core.h, src/drivers/imx/interrupt-generic.c, src/drivers/imx/interrupt-irqsteer.c, west.yml, zephyr/wrapper.c
These two commits, together with upstream patch https://github.com/zephyrproject-rtos/zephyr/pull/57374 fix the build of SOF for i.MX platforms with the new xt-clang Cadence 2023 toolchain.
Keeping as draft until the Zephyr patch is merged. (edit: Zephyr patch merged, west manifest updated)
=> Fixes for i.MX xt-clang build

tools/tplg_parser/include/tplg_parser/tokens.h, tools/tplg_parser/include/tplg_parser/topology.h
These headers include alsa/sound/asoc.h and some versions of the headers have this conditional include of types.h:
#if defined(__linux__)
#include <linux/types.h>
#endif
To ensure types __le64, __le32, __le16, __u8 are defined explicitly include types.h becore including asoc.h.
=> Tools: Tplg_parser: Add include of <linux/types.h>

src/audio/module_adapter/module_adapter.c, src/audio/pipeline/pipeline-graph.c
ipc4_create_buffer() uses comp_get_attribute(, COMP_ATTR_BASE_CONFIG, ) which returns module's struct processing_module::priv.cfg.base_cfg. Since buffer and module could be created on different cores, this fix makes sure module's struct processing_module is allocated in non-cached memory and can be read from any core.
pipeline_get_dai_comp_latency() iterates over all pipelines and reaches to struct pipeline::pipeline_id. This fix ensures that struct pipeline can be read from any core.
=> Multi-core fixes

.github/workflows/ipc_fuzzer.yml
Let's try to fix the error below spotted in
https://github.com/thesofproject/sof/actions/runs/4981366388
I have no idea why this worked before and not anymore but if it makes apt happy then we're happy.
```
libstdc++-12-dev:i386 :
Depends: libstdc++6:i386 (>= 12.1.0-2ubuntu1~22.04) but it is not
going to be installed
Depends: libc6-dev:i386 (>= 2.13-0ubuntu6) but it is not installable
```
=> [SKIP SOF-TEST] .github/fuzzer: apt-get install i386 dependencies explicitly 

src/include/sof/schedule/ll_schedule_domain.h, src/schedule/zephyr_dma_domain.c, src/schedule/zephyr_ll.c, zephyr/Kconfig
Please see the description of each commit for the problem and the solution they offer. Also, please note that, theoretically, in the case of last commit the following issue can happen: (not sure how this would affect the flow especially during a TRIGGER STOP which will stop the stream)
1) TRIGGER stop comes and does a pipeline graph traversal marking some buffer->walking = true.
2) DMA interrupt comes and the DMA domain thread is scheduled since its priority is in the COOP range.
3) pipeline_copy() will see that some buffers have the walking flag marked as true and will stop.
Theoretically, this should also happen in the case of timer domain. Please do correct me if I'm wrong.
This PR will be marked as [DNM] until NXP internal CI is run.
=> schedule: zephyr_dma_domain: Fix multiple issues

src/samples/audio/smart_amp_test_ipc4.c
The original code confuses static code analyzers since it was
relying on the fact that we have the 2x input and 1x output pin
config in adjacent position in smart_amp_data struct similarly
to the extended module configuration.
While it works, it is not a good practice.
Split the copy of input and output pin formats to make the code
obvious and less error prone.
Fixes: https://github.com/andrula-song/sof/commit/bcc14074cd2b80d2e2a4803932daf6a961b3cb0a ("smart_amp_test: Split the module config and blob receiving for IPC4")
Signed-off-by: Andrula Song <andrula.song@intel.com>
=> Dummy smart_amp: copy input_pins and output_pin separately

src/audio/mixin_mixout/mixin_mixout.c
Reimplementation of mixin/mixout to support multi-core case when connected mixin and mixout are running on different cores.
Previous implementation had dead lock problem.
=> ipc4: mixin/mixout multi-core support

tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf
Use fixed 32 bit format on io-gateway and let host-gateway do the conversion.
=> topology2: sdw-amp-generic: use fixed format on amp feedback io

scripts/rebuild-testbench.sh
3 commits. Main one:
rebuild-testbench.sh: add -j jobs option
This is required to investigate build failures. Because of the way the
build is split, a failure in one component can become totally drown in
the long build logs of another component.
Example: with -j2 the `parser_ep` build failure below is completely
drown by the long (and successful!) build logs of `sof_ep`:
```
./scripts/rebuild-testbench.sh -j 1 -p tgl
sof/tools/testbench/build_xt_testbench/sof_parser/build/include/alsa/
sound/asoc.h:196: error: expected specifier-qualifier-list before ‘__le32’
```
=> [SKIP SOF-TEST] rebuild-testbench.sh: add -j jobs option

.github/workflows/sparse-zephyr.yml
This hasn't been required since Zephyr commit 91902c5fd4db ("cmake: add sparse support to the new SCA infrastructure")
=> [SKIP SOF-TEST] .github/sparse-zephyr.yml: delete obsolete REAL_CC magic

tools/topology/topology2/platform/intel/bt-ssp-config-lbm.conf
The BCLK was incorrect for the loopback (LBM) configuration for BT A2DP (48kHz 2ch 16bit), leading to incorrect playback/capture speed.
=> topology2: cavs-nocodec-bt: fix bclk for loopback A2DP case

src/audio/copier/copier.c, src/audio/dai-zephyr.c, src/include/ipc4/copier.h, src/include/sof/audio/dai_copier.h
Removes the endpoint DAI devices and endpoint buffers for multiple endpoint DAI copiers and saves an extra copy.
=> Multiple endpoint DAI copier optimization

src/include/sof/audio/audio_stream.h
frame_align_shift must be initialised (by audio_stream_init_alignment_constants()) once stream format is set. Not all components do this.
Calling audio_stream_init_alignment_constants() from audio_stream_init() is wrong as stream format is set after audio_stream_init().
This patch is a quick fix and to be redo with proper fix.
=> [WORKAROUND] Add frame_align_shift default init

src/audio/module_adapter/module_adapter.c
Skip .copy() in module_adapter if buffer params are not yet set. Buffer might be configured soon by another pipeline (possibly on another core).
=> module_adapter: Do not run on unconfigured bufs

tools/topology/topology2/cavs-nocodec-bt.conf
This has already been added in bt-generic.conf.
The old topology looks like
and the new one looks like
=> topology2: cavs-nocodec-bt: Remove duplicate route

scripts/cmake/version-build-counter.cmake, scripts/xtensa-build-zephyr.py
This replaces and simplifies commit a823958a8d2d3 ("xtensa-build-zephyr: pass sof build version to rimage") with a constant.
EDIT: That commit was submitted to avoid a test failure in a broken, internal
test looking for an SOF_BUILD value... hardcoded to 1! (internal FW issue
257, test TestLoadFwExtended::()::test_00_01_load_fw_and_check_version")
The final goal is for this script to stop extracting anything from `generated/sof_versions.h` so rimage can be configured _before_ the build has started. Other commits will deal with other parts of sof_versions.h
SOF_BUILD can be replaced by a constant because it has always been one when building with Zephyr. The optional BLD_COUNTERS feature - disabled by default in XTOS since commit 9f8cce152240 ("Disable __TIME__ and the non-reproducible …
=> xtensa-build-zephyr.py: don't extract SOF_BUILD from generated .h file

CODEOWNERS
With the work done for zephyr DMA domain we got a lot of insights about how scheduler works.
So add myself and Laurentiu as codeowners.
=> CODEOWNERS: Add NXP people as owners for scheduler

tools/topology/topology1/CMakeLists.txt
Added RPLP CRB support for SoundWire0 and SoundWire2
@bardliao  , @CBala21 , Please review it !
=> topology1: CMakeLists: add RPLP CRB support for SoundWire

.github/workflows/codestyle.yml, .github/workflows/installer.yml, .github/workflows/pull-request.yml, .github/workflows/repro-build.yml, .github/workflows/tools.yml, .github/workflows/unit-tests.yml, .github/workflows/zephyr.yml, scripts/docker-run.sh, scripts/sudo-cwd.sh, zephyr/docker-build.sh
95%, mostly clean cherry-picks from main branch
This avoids branching the Docker image and turns all checks green.
=> [stable-v2.2] cherry-pick docker and other upgrade from main branch

tools/topology/topology2/cavs-mixin-mixout-hda.conf
Rename mixin and mixout Analog Playback volumes. Rewrite the names of the mixers to better reflect their position in the topology.
As a result of this commit mixers are renamed in sof-hda-generic.tplg.
'gain.1.1 1 2nd Playback Volume' becomes
'gain.1.1 Pre Mixer Analog Playback Volume'
and
'gain.2.1 2 Main Playback Volume' becomes
'gain.2.1 Post Mixer Analog Playback Volume'
=> topology2: cavs-mixin-mixout-hda: Rename mixin-mixout mixers

.github/workflows/sparse-zephyr.yml, .github/workflows/zephyr.yml, west.yml, zephyr/docker-run.sh
Updated Zephyr workflow - installed new Zephyr SDK v0.16.1 that is required by Zephyr main branch.
New Zephyr SDK is **NOT** backward compatible to older Zephyr revisions so the upgrade in `west.yml` is done to the commit: https://github.com/zephyrproject-rtos/zephyr/commit/9fc99928caf0 that requires this toolchain.
Build-windows job changes:
* new Zephyr SDK had changed extension and now is compressed using 7z format.
* from build-windows workflow removed unzip package that is no longer required by the setup.cmd Zephyr SDK installation script
Build-linux job changes:
* updated script `zephyr\docker-run.sh` that clones Zephyr Docker container to clone latest tag versioned v0.26.4.
* new container contains Zephyr SDK v0.16.1
* upgraded runner OS to Ubuntu 22.04 to match OS from Docker …
=> workflows: Zephyr workflow uses new 0.16.1 Zephyr SDK

tools/topology/topology2/cavs-sdw-src-gain-mixin.conf, tools/topology/topology2/cavs-sdw.conf, tools/topology/topology2/include/components/alh-dai-copier.conf, tools/topology/topology2/include/components/copier.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-alh-dai-copier-playback.conf, tools/topology/topology2/platform/intel/sdw-amp-generic.conf, tools/topology/topology2/platform/intel/sdw-dmic-generic.conf, tools/topology/topology2/platform/intel/sdw-jack-generic.conf
For ALH DAI, the new name is changed to reflect the link ID and index in an aggregated group like: dai-copier-ALH.SDW1-Playback.0 or alh-copier.SDW1-Playback.1
Also, today we do  not show the aggregated DAI copiers in the topology graph. So add a route via a virtual widget to show its existence as below
=> Change the naming convention for the ALH DAI copiers in topology

src/audio/module_adapter/module/dts.c
To handle zero config size case in set_configuration would let dts_codec_apply_config never be called due to early return when checking if md->new_config_size is zero. This causes the problem that DTS tuning parameter would never be set. We've found the issue on the latest Chrome OS version on RPL. So, instead, check the config size in dts_codec_apply_config() could resolve the zero config case and let the tuning parameter could be set successfully.
=> dts: handle zero config size case in apply_config instead of set_configuration

tools/topology/topology2/avs-tplg/tplg-targets.cmake
There is no device that uses the topology.
=> topology2: remove cavs-sdw.tplg from avs-tplg

src/drivers/amd/rembrandt/ipc.c, src/drivers/amd/renoir/ipc.c, src/drivers/imx/ipc.c, src/drivers/intel/cavs/ipc.c, src/drivers/mediatek/mt818x/ipc.c, src/drivers/mediatek/mt8195/ipc.c, src/include/sof/ipc/common.h, src/include/sof/ipc/driver.h, src/include/sof/ipc/msg.h, src/ipc/ipc-common.c, src/ipc/ipc-zephyr.c, src/ipc/ipc3/handler.c, src/ipc/ipc4/handler.c, src/platform/library/include/platform/platform.h, src/platform/posix/ipc.c, zephyr/wrapper.c
Send fw panic notification message to host.
=> [Ipc4] add fw panic notification support

scripts/cmake/version.cmake, scripts/xtensa-build-zephyr.py
\+ move some rimage-related code around to prepare for the switch to `west build` (1st part of successfully tested  draft TEST PR #7595)
No functional change.
One of the last parts for this v2.6 requirement:
- #6917
=> xtensa-build-zephyr: parse SOF versions from new versions.json instead of generated sof_versions.h

tools/topology/topology2/platform/intel/sdw-amp-generic.conf
Widget type snd_soc_dapm_out_drv and snd_soc_dapm_output will be treat as virtual widget and be ignored in sof topology in kernel. We need to set type = output or out_drv in topology when it is a virtual widget.
Fixes: 3835846836d4 ("topology2: sdw-amp-generic: Show all aggregated DAIs on the graph")
Fixes: #7677
=> topology2: sdw-amp-generic: set virtual widget type output

tools/test/audio/process_test.m, tools/test/audio/std_utils/ldlg_test_input.m, tools/test/audio/std_utils/ldlg_test_measure.m
This patch adds to process_test.m test with amplitude sweep to determine level dependent logarithmic gain.
Currently there is no test pass/fail criteria. But the test result plot can be examined from directory plots. E.g. first full test for DRC with "process_test('drc', 32, 32, 48000, 1);".
The view the plots from shell with "eog plots/ldlg_drc_*.png". Or examine the plots directory with a file maneger GUI.
=> Tools: Test: Audio: Add test for level dependent gain

src/arch/xtensa/CMakeLists.txt
The bootloader was only used by Intel platforms when building SOF with XTOS. Now that that possibility has been removed, bootloader support can be removed too to eliminate dead code. To be merged after #7527
=> xtensa: xtos: remove bootloader support

src/audio/module_adapter/module/volume/volume.c, src/include/sof/audio/volume.h
This patch changes for IPC4 configuration the DSP internal gain format from Q1.23 to Q8.23. Minimum needed would be Q2.23 but the integer part 8 bits is same as in IPC3 and would allow signal amplification in volume component in some later phase. The code is prepared for amplification due to IPC3.
This change allows the Q1.31 max gain 0x7fffffff to round to exactly one in Q8.23 notation. The gain value one passes effectively input to output unmodified. The change prevents lose about 1 dB of signal-to-noise ratio from peak quality of PCM formats.
The comment from convert_volume_ipc4_to_ipc3() is removed because it is unrelated and some remain from old code version.
The hard coded 23 for conversion to/from Qx.23 is changed to macro VOL_QXY_Y because it's used elsewhere in the component. The …
=> Audio: Volume: Change volume internal gain to Q8.23 from Q1.23

.github/workflows/ipc_fuzzer.yml
Re-submission for review of the fuzzer removal PR.
~Note that this won't apply to main until the first version is reverted.~ done
=> [SKIP SOF-TEST] Remove old fuzzer

scripts/xtensa-build-zephyr.py, zephyr/scripts/clean-expected-release-differences.sh
Move rimage parameters to `west config` instead of passing them to `west sign` directly.
Final part closing #6917
\+ 1 other commit. See commit messages.
=> xtensa-build-zephyr.py: stop calling west sign, rely on west build

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/platform/intel/dmic-generic.conf, tools/topology/topology2/platform/intel/nocodec-ssp0-2level.conf
This tries to fix the first tap in https://github.com/thesofproject/sof/issues/6576 for cavs-nocodec topology.
=> Rename cavs nocodec mixers

src/audio/mixin_mixout/mixin_mixout.c
comp_verify_params() doesn't set the channels. So set it explicitly during params.
=> src: mixin_mixout: Set channels during mixout_params

.github/workflows/ipc_fuzzer.yml
Quoting @andyross in
https://github.com/thesofproject/sof/pull/7668#issuecomment-1561587959
> OK, as it turns out when running native_posix+fuzzing, the fuzzer
> output goes to stderr (and appears here) where the console output goes
> to stdout, and is currently being discarded. For a sanitizer-detected
> failure, that's actually fine as the stack trace will show up in the
> CI logs. But this was just a call to posix_exit(), which is an "error"
> to the fuzzer but not very informative to us without knowing the
> software state that led to it. Most likely this is a Zephyr
> panic (e.g. an assertion failure -- not a trap like SIGSEGV/SIGILL
> that would be caught by the host OS and thus libfuzzer), because the
> default fatal error handler is to tell the arch layer to do a system
> halt, …
=> [SKIP SOF-TEST] .github: ipc_fuzzer: upload stdout logs

src/audio/copier/copier.c, src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/include/sof/audio/dai_copier.h
no change for functionality, changes list below:
1. Removed dependency in dai-zephyr.c and dai-legacy.c for comp_dai_get_hw_params with direct calling.
2. Removed one case for COMP_ATTR_VDMA_INDEX in function: copier_get_attribute, since it only used inside copier.
3. Renamed function name with better aligned with name convention.
4. Removed copier get hw parameters function.
This is for preparation of copier module interface.
=> copier: preparation for copier module adapter interface

src/audio/dai-zephyr.c
A problem was observed with launching capture with dmic. Sometimes the host starts reading data too late, so that the capture buffer becomes full. In this case, the dma descriptors are not reloaded. This leads to stopping the dma. When the host starts reading and reads the accumulated data the stream is already stopped. With this patch, the descriptors are always reloaded and the stream will not be stopped. A glitch may occur but it is better than no data at all.
=> dai: always reload dma ll chain

src/audio/pipeline/pipeline-graph.c
Backport PR https://github.com/thesofproject/sof/pull/7447 to cavs2.5-001-drop-stable branch.
=> DSP panic during playback with suspend/resume: backport to cavs2.5 branch

src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c, src/include/sof/audio/volume.h
Left shift 8 bits the max value to put the valid 24 bits into high 24 bits in 32 bits container.
=> Audio: Fix the 24/32 bits format peak volume calculation

src/audio/host-zephyr.c
When the host component detects use of deep buffering it decreases frequency of dma reloading. The number of processed data is summed up in the partial_size variable and they are acknowledged in larger packets. However, the size of processed data was not subtracted from the number of available data, which could lead to a buffer underrun/overrun.
=> host: zephyr: Subtract partial_size from dma avail/free size.

tools/topology/topology2/include/components/alh-dai-copier.conf, tools/topology/topology2/include/components/dai-copier.conf, tools/topology/topology2/include/components/dai.conf, tools/topology/topology2/include/components/eqfir.conf, tools/topology/topology2/include/components/eqiir.conf, tools/topology/topology2/include/components/google-rtc-aec.conf, tools/topology/topology2/include/components/host-copier.conf, tools/topology/topology2/include/components/kpb.conf, tools/topology/topology2/include/components/micsel.conf, tools/topology/topology2/include/components/mixin.conf, tools/topology/topology2/include/components/mixout.conf, tools/topology/topology2/include/components/module-copier.conf, tools/topology/topology2/include/components/muxdemux.conf, tools/topology/topology2/include/components/smart_amp.conf, tools/topology/topology2/include/components/src.conf, tools/topology/topology2/include/components/wov.conf, tools/topology/topology2/include/pipelines/pipeline-common.conf, tools/topology/topology2/platform/intel/dmic-generic.conf
When all components of a pipeline are scheduled on the same core, use the pipeline's core_id attribute to set the core_id for all the components in it. Also, remove the default core_id in the module-copier and eqiir class definitions so that it doesn't take priority over the value passed from the pipeline object.
=> topology2: intel: dmic-generic: Simplify the core ID setting

scripts/xtensa-build-zephyr.py
2 commits, please review separately. Main commit:
`xtensa-build-zephyr.py: resolve relative --key arguments`
Fixes commit https://github.com/thesofproject/sof/commit/a769d3941d81f6d487e1a2bb6c3f99a193ebdcae ("xtensa-build-zephyr.py: stop calling west
sign, rely on west build")
Before that commit, `xtensa-build-zephyr.py` used to invoke `west sign`
directly and in the same current directory. This allowed relative key
paths to just work. Now that `west sign` is indirectly invoked by `west
build`, there is no possible way to make relative key paths work. So we
must resolve them before using them.
Fixes https://github.com/thesofproject/sof/issues/7718
=> xtensa-build-zephyr.py: resolve relative --key arguments

app/prj.conf
Zephyr has hardcoded this to 'y' because it saves CI some disk space when compiling hundreds of different zephyr/tests/, each in a separate build directory. But when compiling just one "sof/app" it saves practically no space, breaks the incremental build and can make it more difficult to troubleshoot some build issues. So, reset it to the default value.
=> app/prj.conf: restore the CONFIG_CLEANUP_INTERMEDIATE_FILES=n default

tools/topology/topology1/CMakeLists.txt, tools/topology/topology1/kernel_dependent/v5.19/CMakeLists.txt
Yet another permutation. This needs to be back-ported to 2.2 releases
Closes: https://github.com/thesofproject/linux/issues/4399
=> topology1: add support for Dell SKU 0934

tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/platform/intel/dmic-generic.conf
Supposed to fix https://github.com/thesofproject/sof/issues/7093
=> Topo2 fix nocodec capture devices

src/drivers/intel/ssp/ssp.c, src/platform/tigerlake/include/platform/platform.h
Hi,
both the TX and RX FIFO drain handling have issues currently, both fixed by this PR.
On TX side we regularly see:
```
c2 wait                         src/lib/wait.c:52   ERROR poll timeout reg 487496 mask 63 val 0 us 937
c2 ssp-dai      1.0   /drivers/intel/ssp/ssp.c:71   WARN ssp_empty_tx_fifo() warning: timeout
```
The reason is that the 'calculated' timeout is incorrect for low sampling rates.
On RX side the FIFO draining needs to follow different strategies depending on when the draining is done to avoid starting and stopping issues.
**Note:** the TX side is not touched in this PR
This PR can replace https://github.com/thesofproject/sof/pull/7711, so far it is holding up to the local stress tests.
=> [stable-v2.2] intel: ssp: RX FIFO drain fix (try 2)

src/platform/intel/cavs/platform.c, west.yml
If SOF is built with Zephyr, the GPDMA/ALH ownership programming should happen in Zephyr platform code, not on SOF side.
Link: https://github.com/zephyrproject-rtos/zephyr/pull/55738
Closes: https://github.com/thesofproject/sof/issues/7249
=> platform: cavs: do not program GPDMA/ALH ownership in Zephyr builds [MANIFEST UDPATE!]

tools/test/audio/process_test.m, tools/test/audio/test_utils/test_run.m
The changes to scripts/host-testbench.sh have unintentionally dropped valgrind run from test.
This patch enables valgrind for process_test.m runs and fixes issue in test run octave side function to silently ignore error about failed shell command. Normally test fail when there is no data or incorrect data, but a valgrind failure with correct test output was passed.
Valgrind output becomes visible if testbench run trace stderr redirection to file is disabled. If not done valgrind error would stop the test but the analysis would not be printed to console.
=> Tools: Test: Audio: Valgrind run related fixes

src/audio/module_adapter/Kconfig, src/audio/module_adapter/module/volume/volume.c, src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c, src/include/sof/audio/volume.h
Add kconfig to select the period of reporting peak meter value. The default value is reporting peak meter every 10 ms.
=> Audio: Peak volume: Add Kconfig to select the period of reporting peak meter value.

src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/module_adapter/module/generic.h
Add a new flag, is_multi_core, and set it if a module to connected to another module on a different core.
=> [NOT FOR MAIN] module_adapter: skip invalidate/writeback with single_core

src/audio/kpb.c, src/ipc/ipc-helper.c, src/ipc/ipc3/handler.c
A collection of minor fixes discovered by oss-fuzz over the last week.  There's some guesswork involved here, as most of the crashes are lower down as other code follows e.g. bad pointers.  I **think** the conditions here cover most (maybe all) of the failures I'm seeing reported.  We'll see how that evolves, no doubt there will be more to come.
=> Cloud-detected fuzz fixups

scripts/fuzz.sh, src/arch/xtensa/CMakeLists.txt, src/platform/Kconfig, zephyr/CMakeLists.txt
There's really no reason to fall back on a default "platform" and pick up a bunch of other, totally random settings.
Now the following command fails immediately with a useful `platform not defined` error message instead of stopping with a cryptic `platform/trace/trace.h: No such file or directory` after successfully compiling half the .c files in a Frankenstein CONFIG_uration.
```
west build -p --board mimx8mm_evk_a53 modules/audio/sof/app
```
More context in #7192.
=> Kconfig: don't fall back on CONFIG_TIGERLAKE

src/audio/copier/copier.c, src/audio/copier/copier_host.c
When calculating number of frames to be attenuated in HOST copier source stream frame bytes should be used instead of sink frame bytes.
E.g. in case of 24/24 bit to 24/32 bit PCM conversion using sink container size will reduce frames number by 1/4 which will lead to multiple glitches.
Also attenuation has to be applied in HOST copier in playback scenario only, thus remove from do_conversion_copy()
=> copier: fix attenuation stream frames calculation

src/audio/aria/aria.c
Commit 1:
Limiting Aria processing size to IBS. It fixes Aria internal buffers overflow.
Commit 2:
Removing unnecessary writebacks of internal Aria buffers
=> Aria: Fix buffers overflow, remove unnecessary writebacks

src/audio/dai-zephyr.c
No need to init avail_bytes, free_bytes or copy_bytes.
=> src: dai_zephyr: Remove unnecessary init

src/audio/host-zephyr.c
As host_common_params() only sets a subset of the fields, initialize the Zephyr DMA interface struct "dma_block_config" with zeroes before use.
Issue found in code review.
=> host: zephyr: zero dma_block_config before use

tools/topology/topology2/platform/intel/sdw-jack-generic.conf
This was missed earlier.
Fixes: f8ad12734db1 (i"topology2: cavs-sdw: Add option for passthrough pipelines")
=> topolgoy2: sdw-jack-generic: Fix the number of input pins

tools/topology/topology2/cavs-nocodec-multicore.conf, tools/topology/topology2/development/tplg-targets.cmake
For MTL platform, config DMIC pipeline on coreX for CI test.
=> topology2: cavs-nocodec-multicore: run DMIC pipelines on core1

src/drivers/intel/ssp/ssp.c
The receive FIFO needs to be drained in a different way depending when it is done.
- before start If the RX FIFO is in overflow state then we must read all the entries out to empty it (it was after all full).
- before stop The DMA might be already running to read out data. Check the FIFO level change in one sample time which gives us the needed information to decide to wait for another loop for the DMA burst to finish, wait for the DMA to start it's burst (DMA request was asserted) or drain the FIFO directly.
No need to drain the RX fifo at probe time.
(cherry picked from commit 69d56a757740274a6f2ccf17fc77c4188f17fc01)
=> [cavs2.5-001-drop-stable] intel: ssp: Revise receive FIFO draining

tools/topology/topology2/platform/intel/sdw-jack-generic.conf
Somehow s24_le format is missed.
=> Topology2: sdw-jack-generic: add 24 bit format support for sdw jack

src/include/sof/math/exp_fcn.h, src/math/CMakeLists.txt, src/math/Kconfig, src/math/exp_fcn.c, src/math/exp_fcn_hifi4.c, test/cmocka/src/math/arithmetic/CMakeLists.txt, zephyr/CMakeLists.txt
The 32-bit HiFi4 exponential library function has an accuracy of 1e-4, a unit in last place error of 5.60032793, and output ranges from 0.0067379470 to 148.4131591026 for inputs from -5 to +5 (Q4.28) (Q9.23).
=> Math: Library: Add the hifi4 exponential function

src/audio/mux/mux.c
The source frames count need to be checked from every active input_buffers[n].size). Similarly in consuming the source buffers it needs to be updated to every
mod->input_buffers[n].consumed.
Fixes: #7308
=> Audio: Mux: Fix mistake in frames count handling

west.yml
Use sof/stable-2.6 branch for Zephyr and update to take in https://github.com/zephyrproject-rtos/zephyr/pull/59272
=> [sof-2.6] west.yml: update Zephyr to backport bugfix for 7482

src/audio/copier/copier_generic.c, src/audio/copier/copier_hifi.c, src/include/sof/audio/audio_stream.h
The function applying the attenuation should be based on write pointer and the current number of copied data in the current systick.
=> src: copier_hifi: update apply_attenuation function

tools/topology/topology2/platform/intel/deep-buffer.conf
Increase the buffer_size/period_size range for user space snd_pcm_hw_params_get_* to extract, this will allow aplay to run with --period-size=8192 --buffer-size=32768 for deepbuf.
=> topology2: deepbuffer-playback: increase default buffer_size_max

src/platform/Kconfig
All available ACE and CAVS platforms use INCOHERENT config, so set it by default.
=> platform: Kconfig: config INCOHERENT by default for all ACE and CAVS

src/audio/module_adapter/module_adapter.c
Simple copy does not need full buffer info for every iteration. Only calculate what we need.
=> module_adapter: optimize simple copy

src/audio/module_adapter/module/cadence.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/module_adapter/module/cadence.h
Maintain codec configuration initialization for ipc4 protocol in cadence
module by separation critical functions into ipc3/ipc4 versions
Changes affect:
- different size of init/runtime config allocation
- resolving codec id from configuration from configuration params for ipc4
=> cadence: enable processing with ipc4 protocol

src/library_manager/lib_manager.c
Cache invalidation after memory unmap is not required and could trigger exceptions depending on memory protection configuration.
=> lib_manager: Fix library unload flow

src/audio/copier/copier.c
Format for validation in the attenuation function is taken from base_audio_fmt instead of out_fmt
=> Copier: fix frame format in attenuation function

src/schedule/zephyr_domain.c
Fix an off-by-one error in timer statistics calculation and add a warning for scheduling overruns
=> LL scheduler: fix a slight bug and add a warning

west.yml
First Zephyr update after 3.4.0 release.
Contains 554 commits, including following directly affecting
SOF targets:
2958a407f8f1 adsp: dmic: Add source clock selection support
0ee64528168b adsp: ace: dmic: Add missing registers definitions
fbb55d1d5e19 adsp: dmic: Moved registers definitions to a separate file
e2e3dc077118 dts: xtensa: intel: add imr entry to cavs25_tgph
6c9a360647c8 drivers: intel_adsp_gpdma: Fix typo in reg name
a8b28f13c195 soc: intel_adsp: cavs: add simple IMR functionality
339b00de11e5 soc: xtensa: intel_adsp: fix memory bank shutdown
5dfaf23f47b7 xtensa: intel_adsp: lnl: Fix dspcs struct
09085ef63c02 dts: xtensa: intel: update cavs25 sram size
b871138fae1f soc/intel_adsp: fix typo in L1EXP definition
9db44fa2813c toolchain: xtensa: enable C11 features with xt-clang …
=> [DNM] west.yml: update Zephyr to 3.4.99

.github/workflows/zephyr.yml, src/include/sof/audio/module_adapter/iadk/utilities/array.h
Do not unconditionally define assert() to nothing in some obscure and
unrelated array.h file.
This looks like it was a temporary hack that was missed in commit
https://github.com/thesofproject/sof/commit/6f366e2eefe4fa4aaaa8d692fe7d276d8580d8d5 ("Add definition of interfaces of Intel IADK modules."),
part of PR https://github.com/thesofproject/sof/pull/5848 too massive to be properly reviewed.
(docs.zephyrproject.org/latest/contribute/contributor_expectations.html)
In addition to enabling asserts when requested by a debug build (!), fix
the following messenger warning:
```
In file included
from src/include/sof/common.h:30,
from src/include/sof/audio/sink_api.h:10,
from src/include/sof/audio/module_adapter/module/module_interface.h:17,
from …
```
=> iadk/array.h: do not redefine assert() to nothing in an unrelated .h 

src/ipc/ipc-zephyr.c, west.yml
During last changes in Zephyr that implemented power transition for the IPC Device, signature of the intel_adsp_ipc_send_message had changed and now returns negative int error codes (previously bool on success). Updated single function reference in SOF IPC4 `ipc_platform_send_msg()`.
Implementation had not changed as the function may return only `-EBUSY` error code until the Zephyr Device Power Management option is disabled.
=> west.yml: upgrade Zephyr revision - update usage of IPC4 ipc_platform_send_msg function signature

src/audio/tdfb/tdfb_hifi3.c, src/include/sof/audio/tdfb/tdfb_comp.h
Optimize the tdfb_fir_sx functions by remove the duplicated usage of circular buffer.
the performance I got by xt-testbench is here:
Format		original(mcps)		optimized(mcps)	saving mcps
16/16		17.42			17.23			0.19
24/32		17.59			17.32			0.27
32/32		17.30			17.12			0.18
=> Audio: TDFB: Optimize the circular buffer usage

tools/topology/topology2/cavs-mixin-mixout-efx-hda.conf, tools/topology/topology2/cavs-nocodec-multicore.conf
After this the only topology source files that do not have their mixer names fixed are cavs-rt5682.conf and cavs-sdw-src-gain-mixin.conf.  One of the PRs to fix https://github.com/thesofproject/sof/issues/6576
=> Topo2 more mixer name fixes

submanifests/sof-ci-jenkins/zephyr-override-template.yml
This commit allows the CI to make use of the nxp_hal which
is required by i.MX8M. Without it, the build would fail.
Fixes: e9f1531b50d6674a8effda9d4118cfd5ff85264c
Signed-off-by: Laurentiu Mihalcea <laurentiu.mihalcea@nxp.com>
=> Fix CI build issue for i.MX8M

src/audio/module_adapter/module_adapter.c, src/include/sof/audio/module_adapter/module/generic.h
This patch adds a simplified version of simple copy for module adapter clients with one source and one sink. The overhead of discovering multiple source and sink buffers is avoided.
The module_adapter_bind() and module_adapter_unbind() functions are changed to detect multiple sources or sinks condition to control the used simple copy function.
=> Audio: Module adapter: Add a new simple copy function

tools/topology/topology2/cavs-rt5682.conf, tools/topology/topology2/cavs-sdw-src-gain-mixin.conf, tools/topology/topology2/platform/intel/sdw-jack-generic.conf
Hopefully the final PR to complete "all controls and PCM names SHALL have a meaningful name."
in https://github.com/thesofproject/sof/issues/6576
This (and the previous PRs) all touch the PCM names, but does not change them. @plbossart if you would like to see some changes in the PCM names, you can comment that in this PR.
=> Remaining mixer renames

src/library_manager/lib_manager.c
The code to get buffer address alignment is duplicated in lib_manager_dma_init() and its caller.
As the code is useless in lib_manager_dma_init(), thus remove it in this patch.
same code in the caller: https://github.com/thesofproject/sof/blob/73cd960e0ed4d0594dd3a974bec816d261b1fc14/src/library_manager/lib_manager.c#L644C5-L644C33
=> lib_manager: lib_manager_dma_init: remove duplicated code

src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/google/google_rtc_audio_processing.c, src/audio/kpb.c, src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module/volume/volume.c, src/audio/src/src.c, src/samples/audio/detect_test.c
The frame_fmt from
audio_stream_fmt_conversion(32, 24, &frame_fmt, &valid_fmt) is SOF_IPC_FRAME_S32_LE (2). valid_fmt is SOF_IPC_FRAME_S24_4LE (1).
Set of member frame_fmt from struct sof_ipc_stream_params should be done with valid_fmt instead to get the components to handle the S24_LE stream correctly.
=> Audio: Fix IPC4 sink component buffer parameters set for S24_LE

src/audio/buffer.c, src/audio/module_adapter/module_adapter.c
Recent research discovered a set of potential issues related with cache prefetch. Specifically it seems like uncached access to memory can cause cache prefetch. This can cause problems in buffer_attach() and buffer_detach() where buffers are added to or removed from lists respectively via uncached addresses, after which they can be used via cached addresses. Add proper cache synchronisation and interrupt locking to protect against such memory corruption.
=> buffer: prevent cache corruption

tools/topology/topology2/cavs-mixin-mixout-hda.conf, tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/platform/intel/dmic-generic.conf, tools/topology/topology2/platform/intel/sdw-jack-generic.conf
Rename all remaining kcontrols to follow the new naming scheme that is already used for all mixers.
This commit changes kcontrol names as follows:
cavs-nocodec.conf:
'smart_amp_init' -> 'Main Playback and Port0 smart_amp_init'
cavs-mixin-mixout-hda.conf:
'4 Main capture Iir Eq' -> 'Analog Capture Iir Eq'
dmic-generic.conf:
'DMIC0 capture Iir Eq' -> 'DMIC0 Capture Iir Eq'
sdw-jack-generic.conf:
'4 Main capture Iir Eq' -> 'Jack In Capture Iir Eq'
=> topology2: Rename remaining non mixer kcontrols to follow new naming scheme

src/audio/module_adapter/module/volume/volume.c
Likely artifact from module adapter conversion
=> volume: fix log message to match caller

tools/testbench/common_test.c
The pcm_dev is no more used in the code. It also causes a problem with "error: ipc get comp" with some topologies, where p->sched_id is missing. This fix helps testbech to parse a topology like
pcm0p --> buf2.0 --> muxdemux --> buf1.0 --> ssp0.out
^
pcm1p --> buf3.0 -------|
=> Tools: Testbench: Remove unnecessary scheduling component find

tools/topology/topology2/platform/intel/hdmi-default.conf, tools/topology/topology2/platform/intel/hdmi-generic.conf
HDMI BE name may not be iDispx.
=> Topology2: hdmi: use macro to set HDMI BE name

tools/topology/topology2/avs-tplg/tplg-targets.cmake, tools/topology/topology2/platform/intel/sdw-amp-generic.conf
Currently, we add the 2nd sdw amp feedback unconditionally. It will lead
to an issue when aggregated apms don't support feedback function.
Also, adding sof-tgl-rt711-rt1308-rt715.tplg in this PR.
=> Topology2: sdw-amp-generic: add 2nd amp feedback when SDW_AMP_FEEDBACK is true

tools/topology/topology1/development/CMakeLists.txt, tools/topology/topology1/development/sof-tgl-nocodec-mux.m4
Add test topology for muxing 2 pipelines into 1 with SSP dai and capturing the result from loopback.
=> topology1: test topology for tgl nocodec mux

tools/topology/topology2/cavs-benchmark-hda.conf, tools/topology/topology2/development/tplg-targets.cmake, tools/topology/topology2/include/components/aria.conf, tools/topology/topology2/include/pipelines/cavs/mixout-aria-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-dai-copier-playback.conf, tools/topology/topology2/sof-hda-generic.conf
This patch builds new development topologies
sof-hda-benchmark-generic-<tgl/mtl/lnl>.tplg to evaluate performance of a set of playback components.
The topology for PCM0P playback is
host-copier.0 --> gain.1.1 --> mixin.1.1 -->
mixout.2.1 --> aria.2.1 --> gain.2.1  --> mixin
mixout.3.1 --> dai-copier.HDA
=> Tools: Topology2: Add a development HDA generic MCPS benchmark topology

xtos/include/sof/lib/perf_cnt.h
Previously, due to cycle get max is UINT32_MAX, so have to check and wrap the code, however, unsigned int can wrap automatically with minus, remove the check and make perf calculation more simple.
=> perf_cnt: simplify the difference calculation for cycles

src/audio/base_fw.c, src/include/ipc4/base_fw.h, src/include/sof/tlv.h
Adding a header file containing definitions of the TLV structure and related functions.
Most of the code is a copy of the functionality added for the Base_Fw module in the 3efd78048d commit. The only difference are the names change of the base structure, functions and field in the structure. A new feature is a function that allows to find TLV value of the indicated type.
The reason for these changes is the fact that data in the form of TLV will also be transferred to other modules.
=> sof: new header with tlv

tools/topology/topology2/platform/intel/sdw-amp-generic.conf
num_input_pins was missing in passthrough mode.
Fixes: #7899
=> Topology2: sdw-amp-generic: add missing num_input_pins

tools/topology/topology2/platform/intel/sdw-amp-generic.conf
When PASSTHROUGH is true, the topology generation throws this error:
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'host-copier.0.playback'
using the pcm_id 2 used for the host copier fixes the issue.
=> topology2: cavs-sdw: fix bad index in passthrough mode

src/audio/copier/copier_dai.c
drv is left over from the previous implementation when a DAI component was created for each copier. Remove it as it isn't really used anymore.
=> audio: copier_dai: Remove unused variable

zephyr/include/rtos/sof.h
Struct cascade_root & mn are used by xtos build only so remove them. And these two items are too specific to intel platforms.
=> ipc4: zephyr: remove unuseful member in struct sof

src/audio/selector/selector.c
The size argument to the memcpy_s() here is under the control of external data and can fail on garbage.  That needs to be a runtime failure, not an assertion.
=> audio/selector: Don't assert on input-controllable memcpy_s failure

src/audio/mixer/mixer.c, src/include/sof/audio/mixer.h
After commit 867ada28f we only allocate 1 buffer for mixer even if there could be 2 input sources.
So, set correct number of sources for mixer.
Fixes 867ada28f ("audio: module_adapter: Allocate max number of input/output buffers")
=> audio: mixer: Set correct number of sources

src/ipc/ipc-helper.c
[Third time's the charm?  Still trying to extract that rogue rimage submodule delta.]
Found a oss-fuzz error I thought I'd fixed being reported again. Turns out the fix had a typo and only fixed half the problem space. Need to check source and sink, not source and source!
=> ipc: Fix typo in error checking

west.yml
After exiting D3 state if IMR context save is enabled, IDC interrupt must be re-enabled again for all cores. It fixes multicore CI test issue.
431108d89e175: intel_adsp: ace: Restore IDC interrupt on D3 exit
fix https://github.com/thesofproject/sof/issues/7885 [MTL][Multicore] IPC timed out for GLB_CREATE_PIPELINE
=> west.yml: upgrade Zephyr revision - Restore IDC interrupt on D3 exit

src/drivers/mediatek/afe/afe-memif.c
This pull request contains two commits: one adds a missing parameter in the debug log and another updates the MEMIF configuration format. 
Initially, MEMIF format was configured based on DAI configuration. However, DAI DMA(MEMIF) can support a different bit width than that of BE DAI for MediaTek AFE. Hence, it is better to obtain BE frame format from DAI_CONFIG and MEMIF format from the configuration of DAI component which should be identical to the bitwidth in pipeline.
=> drivers: mtk: Add few fixes

west.yml
Changed rimage submodule revision to:
480534e94fae49fc31d449c7683901a0a8427368
This commit points to stable-v2.6 branch in rimage repository.
=> rimage: Update rimage revision to 480534e

src/audio/aria/aria_hifi3.c, src/audio/module_adapter/iadk/system_agent.cpp, src/audio/module_adapter/module/volume/volume_hifi4_with_peakvol.c
When trying to build a sofa with the -Wall and -Werror flags enabled, the compiler reported errors about unused variables. This PR fix it.
=> Fix unused variable warnings

src/audio/module_adapter/module/volume/volume.c
It is possible to fabricate a message for FW that initializes volume module without a configuration. Make a safe guard again crashing from that.
Fixes a similar problem with volume module, as this PR fixes for SRC module: https://github.com/thesofproject/sof/pull/7830
=> volume: Bail out if there is no configuration

src/include/sof/audio/module_adapter/module/module_interface.h
Fixes commit 9cc6454df6d2 ("module_adapter: Extend the module interface for endpoint devices")
As the endpoint_ops methods use only pointers to these two objects, it's not necessary to make their entire object structure visible. However a forward declaration is required to make them known to endpoint_ops users and fix the following warning:
```
error: 'struct comp_dev' declared inside parameter list will not be
visible outside of this definition or declaration [-Werror]
```
=> module_interface.h: add forward struct comp_dev and timestamp_data

src/audio/module_adapter/module/volume/volume.c, src/audio/module_adapter/module/volume/volume_generic_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi3_with_peakvol.c, src/audio/module_adapter/module/volume/volume_hifi4_with_peakvol.c, src/include/sof/audio/volume.h
Shift left the peak meter of 16/16 bit format 16 bits to normalize this value to 32 bits to meet the CI test requirement.
=> Audio: Normalize the 16/16 bit format peak meter to 32 bits.

src/audio/rtnr/rtnr.c, src/include/sof/audio/rtnr/rtklib/include/RTK_MA_API.h, src/include/sof/audio/rtnr/rtnr.h
Fixes
- Invalid buffer access change
- Arg attributes
- Missing headers
=> RTNR adapter fixups

src/ipc/ipc3/helper.c
Return an error code from comp_specific_builder() if the component type is not recognized, instead of just silently ignoring the error.
=> ipc3: helper: Do not silently accept unrecognized component type in IPC

src/include/sof/audio/audio_stream.h
we aren't modifying it, so make it const
=> audio: constify buffer_fmt get args

src/ipc/ipc3/helper.c
With mixer after commit 21ed10abf8a2 ("ipc3: helper: Do not silently accept unrecognized component type in IPC") we get the following error
dma-trace  src/ipc/ipc3/helper.c:333  ERROR comp_new(): component type not recognized
This happens because now we return an error from comp_specific_builder() with the default case.
Fix this by adding a case for mixer.
Fixes: 21ed10abf8a2 ("ipc3: helper: Do not silently accept unrecognized component type in IPC")
=> ipc3: helper: Fix mixer scenario

tools/topology/topology2/cavs-nocodec-multicore.conf, tools/topology/topology2/cavs-nocodec.conf
DMIC now is controlled by two variables, PASSHTHROUGH and NUM_DMICS,
we should consider the values for both variables to decide the inclusion of DMIC
pipelines, routes, widgets, etc.
Fixes: #7931
Without this PR, there are DMIC components declared in the topology even with NUM_DMICS=0, and our tplgtool.py will fail to parse the topology because of a widget apprears in SectionRoute, but not in SectionWidget. Or there is an incomplete and isolated route in the topology graph.
=> topology2: fix conditional inclusion of DMIC snippets for nocodec topology

tools/topology/topology1/sof-smart-amplifier.m4
DYNAMIC topology should not be used for pipeline with volatile Kcontrols.
Hence ensuring the flag is un defined before processing smart amp related PCM and DAI configs
Suggested-by: Sridharan, Ranjani <[ranjani.sridharan@linux.intel.com](mailto:ranjani.sridharan@linux.intel.com)>
=> smart amp : Do not use DYNAMIC topology

zephyr/CMakeLists.txt
Samples should not be built without the kconfig option
=> samples: Fix zephyr config

src/audio/Kconfig, src/audio/pcm_converter/pcm_converter_generic.c, src/include/ipc/stream.h, src/include/kernel/abi.h, src/include/sof/audio/audio_stream.h, src/include/sof/audio/format.h, src/include/sof/audio/format_generic.h, src/include/sof/audio/format_hifi3.h, test/cmocka/src/audio/selector/selector_test.c, test/cmocka/src/audio/volume/volume_process.c
This PR adds basic support for unsigned 8 bit format. 8 bit samples in 8 and 16 bit container and conversion between 32 bit signed format is supported.
=> format: stream: pcm_converter: Add support for 8-bit formats

src/platform/Kconfig, zephyr/lib/cpu.c, zephyr/wrapper.c
Zephyr uses MP_MAX_NUM_CPUS internally to represent the number of cores available and consequently to allocate resources. It is even expected, and checked through assert, that these two symbols have the same value. Use different value can lead to an undesired behavior, so lets use MP_MAX_NUM_CPUS.
=> zephyr: s/MP_NUM_CPUS/MP_MAX_NUM_CPUS/

src/audio/src/src.c
In some error situations the configuration init_data may be NULL, and in such a situations we should fail gracefully and not crash.
=> Audio: SRC: Add safeguard against completely missing init_data

src/schedule/zephyr_ll.c
Calling zephyr_ll_task_cancel() for a task which was actually never scheduled results later in panic in zephyr_ll_task_done().
The fix makes zephyr_ll_task_cancel() do nothing for tasks which were only initialized but never scheduled.
=> zephyr_ll: Fix panic upon cancelling not scheduled task

src/audio/copier/copier.c
In last time copier code split, it split multi-endpoint copy and module copy with commit: e424b87, source buffer consume was missed, added it back with this PR.
Fixes:#7979
=> copier: fix no consume for multi endpoint copy

west.yml
Pull in following rimage changes:
aa0ac9eae675 rimage.c: fix bug where -p requires a new and ignored parameter
=> west.yml: Update rimage revision to aa0ac9ea

src/audio/buffer.c
This is the PR for Issues#7916.
Cache operation at **_buffer_attach_** results in DSP panic problem on MediaTek platform, but cache invalidation is required for INTEL platform to solve the prefetch issue.
Add **#if CONFIG_INTEL** to make the line specific to INTEL platform.
=> buffer: fix DSP panic caused by buffer_attach

src/idc/idc.c, src/include/sof/ipc/topology.h, src/ipc/ipc4/handler.c, zephyr/include/rtos/idc.h
This will allow to correctly set multiple pipelines state even if they are allocated on different cores.
ipc4_set_pipeline_state will check if several cores are involved
- set ppl state if only current core requested
- process IPC on another core if only single secondary core requested
- send IDC messages if several secondary cores involved
=> ipc4: multi pipeline set state on different cores

zephyr/include/sof/lib/regions_mm.h, zephyr/lib/regions_mm.c
Add virtual heap allocators that allocate on proper heaps and map physical memory where nesscessary.
Add free function that frees up the virtual heap memory and unmaps physical memory when possible.
Some relevant links to understand context
https://thesofproject.github.io/latest/architectures/firmware/sof-zephyr/rtos_layer/memory_management/heap_sharing.html
https://thesofproject.github.io/latest/architectures/firmware/sof-zephyr/rtos_layer/memory_management/index.html
https://github.com/orgs/thesofproject/discussions/7514
Added a presentation that outlines the intent of the commit I crafted at the start of this commit lifecycle.
[virtual heaps.pdf](https://github.com/thesofproject/sof/files/11444845/virtual.heaps.pdf)
Summarizing potential benefits that this api introduces:
- Avoid …
=> memory management: Add virtual heap memory allocators

src/audio/mixin_mixout/mixin_mixout.c, src/include/sof/audio/mixer.h
1. remove frame_fmt conversion in mixin mixout init function, it will be converted and assigned in parameter function.
2. change frame format type.
=> mixin_out: remove frame_fmt in mixin mixout init function

src/audio/aria/aria.c, src/audio/aria/aria_generic.c, src/audio/aria/aria_hifi3.c, src/include/sof/audio/aria/aria.h
Convert the component aria to use module adapter interface.
=> Audio: Aria: Convert aria to module adapter interface

src/ipc/ipc4/handler.c
Some minor imrpovements and fixes.
=> ipc4:  fixes for waiting.

src/include/sof/schedule/dp_schedule.h, src/init/init.c, src/schedule/zephyr_dp_schedule.c
At start point an incorrect assumption has been taken that it is enough to have one single instance of
DP scheduler located on a primary core 
This commit introduces a DP instance per each core
=> dp: introduce per-core DP scheduler

src/audio/Kconfig, src/audio/copier/copier_host.c, src/audio/host-zephyr.c, src/include/ipc4/copier.h, src/include/sof/audio/component.h, src/include/sof/audio/host_copier.h, src/ipc/ipc4/helper.c
This PR adds synchronized FPI updates of HD-A gateways. Driver can define group of such gateways via module init IPC. The driver may also specify an update period for each group, different than the default one determined by the system tick frequency.
In addition, a change has been introduced that makes it possible to read config size in module init function.  Each module receive its own configuration at creation (MODULE_INIT IPC). In case of a gateway those configurations can contain additional value (aux_conf). The only way to check if such config was received is to compare size of the data received via ipc and standard configuration size.
=> ace: copier: hda: synchronized FPI updates of HD-A gateways

src/audio/module_adapter/module_adapter.c
In ipc3 module creation, it is possible that ipc data is invalid or corrupted, in this case, module init may crash.
This patch is adding error handling to avoid crash.
=> module adapter: avoid module init crash in case of ipc data invalid

src/audio/copier/copier_host.c
After commit f639fc8e888b ("copier: rename parent_dev to dev") FW for MTL platform is not building. This should be detected b as merge conflict but it went unnoticed.
=> mtl: copier-host: fix build issue

src/audio/src/src.c
In some error situations the configuration init_data may be NULL, and in such a situations we should fail gracefully and not crash. Also adds check that the IPC message is of correct type and for IPC3 only that it is of correct type.
This is a reincarnation of https://github.com/thesofproject/sof/pull/7830 that was reverted due to CI problems: https://github.com/thesofproject/sof/pull/7985
The message type check is now done for IPC3 only.
=> Audio: SRC: Add safeguard against missing, wrong size or type init data

tools/tune/crossover/crossover_build_blob.m, tools/tune/crossover/crossover_coef_quant.m, tools/tune/crossover/crossover_gen_coefs.m, tools/tune/crossover/crossover_plot_freq.m, tools/tune/crossover/example_crossover.m
The script example_crossover.m is converted to export 2, 3, and 4 way crossover configurations for tplg1 and tplg2.
The crossover parameters like number of sinks, pipeline ids of sinks, sample rate, and band limits are added to generate blob filenames.
The changes include fixes for running the script with Matlab in addition to Octave.
=> Tools: Tune: Update crossover configurations export for tplg2

tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake
Dell SKU0C87 devices have below config:
SDW0: RT714 DMIC
SDW1: RT1318 Speaker
SDW2: RT1318 Speaker
Add topology support in this patch for Dell SKU0C87 devices.
This patch is not yet tested due to unavailability of devices, please hold on to merge.
PR is used for Dell to easily get the patch.
Corresponding kernel patch: https://github.com/thesofproject/linux/pull/4468
=> topology2: add SDW topology for Dell SKU0C87 devices

src/audio/mux/mux.c
valid_bit_depth isn't used anywhere.
=> audio: mux: Remove unused variable

src/audio/mixin_mixout/mixin_mixout.c, src/audio/mixin_mixout/mixin_mixout_generic.c, src/audio/mixin_mixout/mixin_mixout_hifi3.c, src/include/ipc4/mixin_mixout.h
there is no user case to support remapping in SOF, remove it to save code size and benefit performance.
=> Mixin_out: remove remap mode from sof mixin out module

src/platform/Kconfig, src/platform/intel/cavs/platform.c
Memory windows is set on zephyr side, so remove it and also remove xsram_window for memory windows to save memory since it is not used by ipc4.
Currently we find bug that when we disable CONFIG_TRACE, memory windows can't work well since the CONFIG_TRACE affects memory windows size. It is designed for IPC3 but it is not fit for IPC4.
=> TigerLake: disable memory windows setting on sof side

Kconfig.sof, src/arch/xtensa/CMakeLists.txt, src/audio/dai-zephyr.c, zephyr/CMakeLists.txt
Enable inline function for cavs 2.5 and above platform, this is a follow up with issue:#5212
=> audio: xtensa: add Kconfig for inline functions

src/audio/audio_stream.c, src/audio/sink_api_helper.c, src/audio/source_api_helper.c, src/include/sof/audio/component.h, src/include/sof/audio/sink_api.h, src/include/sof/audio/sink_api_implementation.h, src/include/sof/audio/source_api.h, src/include/sof/audio/source_api_implementation.h, src/ipc/ipc4/helper.c
1) add min_free / min_available 
Its obvious that to process, a module must have enough data on all inputs (sources) and enough space on all outputs (sinks). 
For each input/output the amount of required data/space may be different. 
This PR adds min_free/min_available) to sink/source
This information will be used by DP Scheduler to determine if the module may be scheduled.
2) add data invalidation to audio_stream sink/src implementation
Audio_stream is not making cache operations on data
buffer itself, it requires that the module to
call data invalidation/writeback
Sink/source interface works differently, it removes any
responsibility from the module providing a ready to
use pointers in cached memory
this PR adds cache operations to audio_stream sink/src implementation
=> DP: changes in sink/source

src/audio/crossover/crossover.c, src/audio/crossover/crossover_generic.c, src/include/sof/audio/component.h, src/include/sof/audio/crossover/crossover.h, tools/testbench/common_test.c
This patch contains basic changes to run crossover component as module adapter client in IPC3 system. Additional changes are needed for IPC4.
=> Audio: Crossover: Convert to module adapter

src/library_manager/lib_manager.c
PR #7986 introduced 3 sparse warnings which got overlooked, fix them with a followup patch
There are sparse warnings on zephyr side as well, I will send a PR to fix that.
=> lib_manager: Fix sparse warnings

src/drivers/amd/common/acp_dmic_dai.c, src/drivers/amd/common/acp_dmic_dma.c, src/drivers/amd/rembrandt/acp_dmic_dma.c, src/drivers/amd/renoir/acp_dmic_dma.c, src/platform/amd/common/include/platform/acp_dmic_dma.h
AMD: DMIC: Initial silence in DMIC path to remove the popping noise during the start of DMIC.
=> Introducing initial silence in DMIC path to remove the popping noise

src/audio/module_adapter/module/volume/volume.c
CONFIG_PEAK_METER_UPDATE_PERIOD depends on CONFIG_COMP_PEAK_VOL
=> audio: volume: Fix compilation error when COM_PEAK_VOL is not selected

tools/topology/CMakeLists.txt, tools/topology/platform/intel/jsl-rt1015.m4, tools/topology/sof-jsl-rt5682.m4
Add a new topology sof-jsl-rt5650 for ALC5650 which supports SSP0 for headset and SSP1 for speakers since this codec implements two I2S interfaces.
DAI format changed to mclk: 24.576MHz, bclk: 3.072MHz, sample bits: 24-bit to avoid using ASRC function on codec side.
=> topology1: sof-jsl-rt5650

src/audio/src/src.c, src/include/sof/audio/module_adapter/module/generic.h, src/include/sof/audio/module_adapter/module/module_interface.h
dependencies:
This is a modification of module API - add is_ready_to_process call
In case of LL modules all modules have "copy" or "process" method
called periodically, regardless if they're ready to process or not
In case of DP processing the module must have enough data on all
its inputs, enough space for result storage on all outputs, etc.
Unfortunately simply check of number of bytes at all sources/sinks
may not be sufficient (i.e. in case of variable rate audio formats)
The is_ready_to_process call will be called when DP scheduler makes
decision if the module is to be scheduled at this LL tick or not.
If the module wants its thread to start (and process called) it should
return TRUE
=> Add "is_ready_to_process" call to module API

src/audio/src/src.c
Rate for sink was not set properly in src.c
=> src: bugfix: rate for sink not set

src/library_manager/Kconfig, src/library_manager/lib_manager.c
The module allocate/free uses APIs from MM_DRV but it does not declare dependency on it.
Make the code compile in the case when MM_DRV is not selected by only providing a reduced allocate/free functions with a print only.
Use a local define (PAGE_SZ) to store the page size to be used in the library manager code and in case of !MM_DRV set it to a default 4096 which is also used by the rimage when creating the manifest for the libraries.
=> lib_manager: Fix compilation if MM_DRV is not enabled

src/arch/xtensa/CMakeLists.txt, src/platform/Kconfig
commit ae72e4bd342b37ea54c6a4874313f0135443a867 (HEAD -> 202308-tgl-kconfig-prune, kv/202308-tgl-kconfig-prune)
Author: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Date:   Mon Aug 21 20:05:41 2023 +0300
platform: tigerlake: remove XTOS options
When CONFIG_TIGERLAKE is selected, omit all XTOS specific
build options.
src/platform/Kconfig | 10 ----------
1 file changed, 10 deletions(-)
commit 36db7c9c7b08100bca7c886faac194799a068183
Author: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Date:   Mon Aug 21 19:51:36 2023 +0300
arch: xtensa: remove tigerlake platform option
Remove Intel Tiger Lake from available XTOS platforms in arch/xtensa.
Now done in sof/zephyr/CMakeLists.txt instead.
Signed-off-by: Kai Vehmanen …
=> Remove Tiger Lake XTOS platform Kconfig option (arch + platform)

src/platform/intel/cavs/platform.c, src/platform/tigerlake/include/platform/platform.h
platform: tigerlake: cleanup unused code for IPC3, SPI, GPIO, XTOS
platform: tigerlake: remove unused definitions
=> platform: tigerlake: remove unused definitions

src/audio/crossover/crossover.c
The component build fails if it is enabled in Kconfig. The variable pipeline_id is not defined, it should be sink_id.
Fixes: 5bcbcf19f7e1 ("Audio: Crossover: Convert to module adapter")
=> Audio: Crossover: Fix build error

west.yml
Contains 2211 commits, including following directly affecting SOF targets:
ab0ed577111b mm: intel_adsp_tlb: Handle address space conversion warnings
823e6b70d240 arch: xtensa: Implement arch_float_enable&disable
be779f2a6195 intel_adsp: hda: fix usage of FIFORDY bit
498f294b2720 west: update sof ref in manifest
42ca64d60cd2 tests: dma_sg: intel_adsp_ace15 specific config
0e373019d65e dma: intel_adsp_gpdma: Unmask interrupt on ACE
6e66efa08871 soc: intel_adsp_ace15: Include stdint.h
250748bfe671 intel_adsp: Add option about switch off hpsram
b4293ec026c4 dts: xtensa: nxp: add nodes for IPC
1295283a8a72 soc: xtensa: nxp: add resource_table section in linker script
e6d89268572d xtensa: set no optimization for arch_cpu_idle() with xt-clang
a458d0443a91 xtensa: allow arch-specific …
=> west.yml: update Zephyr to b92e749c3e5f

src/audio/Kconfig, src/audio/copier/copier_generic.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/include/ipc/stream.h, src/include/kernel/abi.h, src/include/sof/audio/audio_stream.h, src/include/sof/audio/pcm_converter.h, test/cmocka/src/audio/selector/selector_test.c, test/cmocka/src/audio/volume/volume_process.c, tools/topology/topology2/include/common/audio_format.conf, tools/topology/topology2/include/common/input_audio_format.conf, tools/topology/topology2/include/common/output_audio_format.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-be.conf, tools/topology/topology2/include/pipelines/cavs/dai-kpb-be.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway.conf
Reverts thesofproject/sof#7959
defect https://github.com/thesofproject/sof/issues/8086
=> Revert "IPC4: simplify pcm conversion function and add LSB & MSB support"

src/include/ipc4/header.h, src/include/sof/lib_manager.h, src/ipc/ipc4/handler.c, src/library_manager/lib_manager.c
The hardware programming flow dictates that the DSP side should set the GEN bit first followed by the host setting the EN bit. We cannot assume that the GEN bit is already enabled (and it would in fact will leave the DMA on the DSP side wrongly configured at best).
To support the currently used flow (single step) and add support for the correct programming flow, the proposed solution is to use the lib_id as indication of the method the host software is going to use.
Two stage flow:
The first LOAD_LIBRARY_PREPARE with valid dma_id
- just allocate and set the GEN bit Second LOAD_LIBRARY with valid lib_id and dma_id
- proceed to the loading of the library via host DMA to local buffer
Single stage flow (currently supported)
LOAD_LIBRARY with valid lib_id and dma_id
- allocate, set GEN bit and …
=> lib-manager: Support for two stage library loading

src/audio/dai-zephyr.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/host_copier.h, src/include/sof/audio/module_adapter/module/generic.h, src/include/sof/lib/dai-zephyr.h
this PR did following things:
optimize module adapter and copier, reduce host and dai performance increase caused by #7890.
below is the rough result:
=> module adapter and copier performance optimization

scripts/run-mocks.sh
The script runs the unit tests natively as gcc compiled.  The tgph_defconfig is no more available, so use another configuration that is available in src/arch/xtensa/configs.
=> Scripts: run-mocks.sh: Change default config to avoid error

west.yml
Includes following rimage commits:
4fb9fe00575b config: lnl+mtl: fix length of ADSP.man CSE manifest 
c809af816859 Config: Add crossover component for TGL and TGL-H cAVS platforms 
8c8440070a08 style: trailing whitespace is the root of all evil 
d20f1d8a85e7 actions: remove travis
af9a2fe58f21 Config: Fix comment typo for EQ FIR module 
b8ee1aa8f695 Config: Add DRC component to TGL, TGL-H, MTL, LNL
=> west.yml: Update rimage revision to 4fb9fe00575b

src/audio/crossover/crossover.c
In IPC4 system the output sinks of crossover are not defined by pipeline identifiers but by pin indices. The error message is updated to be IPC version agnostic to avoid confusion.
=> Audio: Crossover: Adjust error message for pin index usage in config

scripts/xtensa-build-zephyr.py
Now we can avoid bitrot again thanks to recent rimage fix https://github.com/thesofproject/rimage/commit/4fb9fe00575bc
Also update outdated comments.
=> xtensa-build-zephyr.py: re-enable sof_ri_info.py on MTL and LNL

src/audio/mfcc/mfcc_hifi4.c
Audio: MFCC: Fix compilation error
/home/bamboo/sof_dir/sof/src/audio/mfcc/mfcc_hifi4.c: In function
‘mfcc_source_copy_s16’:
/home/bamboo/sof_dir/sof/src/audio/mfcc/mfcc_hifi4.c:86: warning:
assignment from incompatible pointer type
/home/bamboo/sof_dir/sof/src/audio/mfcc/mfcc_hifi4.c: In function
‘mfcc_fill_prev_samples’:
/home/bamboo/sof_dir/sof/src/audio/mfcc/mfcc_hifi4.c:119: warning:
assignment from incompatible pointer type
=> Audio: MFCC: Fix compile time error

src/ipc/ipc4/helper.c
source_set_ibs() and source_set_obs() take a cached pointer. Fix code in ipc_comp_connect() to adhere to the prototype.
Fixes sparse warnings:
ipc4/helper.c:389:49: warning: incorrect type in argument 1 (different address spaces)
ipc4/helper.c:390:45: warning: incorrect type in argument 1 (different address spaces)
=> ipc4: helper: adhere to cached/uncached interface

src/include/ipc4/module.h, src/ipc/ipc4/helper.c
The existing component ID is composed with
'module_id << 16 | instance_id', it doesn't
comply to the initial instance IPC structure:
struct {
uint32_t module_id   : 16;
uint32_t instance_id : 8;
...
};
When the ID is logged through mtrace, it is
hard to use the ID to find the related linux
kernel message.
This patch fixes component ID composition macros,
thus helps to eliminate component ID inconsistency
between firmware and linux kernel.
Link: https://github.com/thesofproject/sof/issues/8051
=> include: ipc4: module: fix component ID macros

.github/workflows/zephyr.yml
Fixes commit 6f9f2ee28ecf (".github/zephyr: build with the debug overlay and CONFIG_ASSERT")
Remove misspelled `zephyr_revsion` matrix variable. It was a hasty copy/paste in that commit.
It's a harmless no-op because build-windows does not play any git tricks and always builds from the manifest. However it makes the list of configurations confusing in the Github interface.
=> [SKIP SOF-TEST] .github/zephyr.yml: remove spurious `zephyr_revsion` matrix variable

src/drivers/imx/CMakeLists.txt, src/drivers/imx/Kconfig, src/drivers/imx/sdma.c, src/include/sof/drivers/sdma.h
SDMA support loading firmware RAM scripts in order to enhance functionality. We will need this for supporting multi-fifo with upcoming MICFIL PDM driver.
Allow SDMA to load such scripts selected via CONFIG_HAVE_SDMA_FIRMWARE config.
A RAM script interface guarantees that there will be the following information provided:
- sdma_code, an array of bytes containting the actual script binary
- RAM_CODE_START_ADDR, location in RAM where to load the script
- RAM_CODE_SIZE, size of the sdma_code array.
Because RAM scripts are NXP proprietary binaries we won't make them public but offer the interface to integrate them with SOF in private builds.
We use for now sdma_script_code_imx7d_4_5.h header file which must be present in location indicated by CONFIG_SDMA_SCRIPT_CODE.
=> imx: sdma: Add support for loading RAM script

.github/workflows/zephyr.yml
Fixes commit 4286bb3ee186 (".github/zephyr: west update with new, faster git --filter-tree:0") that accidentally dropped git tags from `git describe` in Zephyr since April and made the build different from everyone else.
See detailed explanation added to the source.
To find the output of `git -C zephyr/ describe`, search for `generated/version.h` in the build logs.
=> .github/zephyr.yml: fix tags missing from `git -C zephyr/ describe`

app/prj.conf
This reverts commit 80c6738b89bc3e677cc125dd189aac97f111dfd5.
The Zephyr default changed in commit [385ad46a39ca](https://github.com/zephyrproject-rtos/zephyr/commit/385ad46a39ca) so this is not needed anymore.
=> Revert "app/prj.conf: restore CONFIG_CLEANUP_INTERMEDIATE_FILES=n default"

tools/topology/topology2/cavs-rt5682.conf
Make it less error-prone for maintenance.
=> topology2: cavs-rt5682: use macros for all PCM IDs

zephyr/edf_schedule.c
The z_delayed_work field in struct task is a delayed work, so to go from k_work to it safely there's an extra step. Add a
k_work_delayable_from_work to fix that.
This is harmless right now because k_work is the first field in k_work_delayable but the extra step is the safe way of doing it.
=> zephyr: edf-schedule: fix CONTAINER_OF type

src/schedule/zephyr_domain.c
print out core ID in each core performance log tracing.
=> audio: perf: add core information into performance log

CODEOWNERS
Add myself to the list of default owners that get added to all pull requests if no other entries match.
=> CODEOWNERS: add kv2019i to the list of default owners

west.yml
Contains 367 commits, including following directly affecting SOF targets:
ffd2121c65d3 soc: xtensa: intel_adsp: cavs: fix power_down_cavs() signature
a1d7ffdc374d soc: xtensa: intel_adsp: cavs: fix incorrect cached/uncached cast
ce7c30c12978 soc: intel_adsp/ace: use WAIT_FOR for core power transitions
3f0ee7f6db7a power_domain: intel_adsp: initialize after DMA
ca23a5f0cf75 xtensa: mmu: allow SoC to do additional MMU init steps
088a31e2bffa xtensa: mmu: preload ITLB for VECBASE before restoring...
40f2486b685c xtensa: mmu: rename MMU_KERNEL_RING to Z_XTENSA_KERNEL_RING...
18eb17f4cd69 xtensa: mmu: add arch_reserved_pages_update
4778c13bbeab xtensa: mmu: handle all data TLB misses in double exception
c723d8b8d3ac xtensa: Add missing synchronization
24148718fc6e xtensa: mmu: cache common …
=> west.yml: update Zephyr to 5689916a70ad

src/include/sof/math/fir_config.h, src/include/sof/math/iir_df2t.h
The normally undefined SOF_FIR_FORCEARCH or SOF_IIR_DF2T_FORCEARCH can be defined at command line to force the build of other code optimized version for any compiler. The usage is only for debugging, e.g. build generic FIR version with xcc.
=> Math: Cleanup FIR and IIR build type select

src/ipc/ipc4/handler.c
BUG: Various IPC timed out with multi-core run simultaneously https://github.com/thesofproject/sof/issues/7774.
This issue is very random and can be reproduced after many cycles test. The direct reason is that : there is a self loop
in the ipc message list like:   ipc msg -> M1 -> M2 ->..... > Mn ->Mn , this result to a infinite loop with ipc spin lock hold for the logging function. This is one major reason that the issue can't be reproduced with logging disabled.
````c
-static bool is_notification_queued(void)
{
struct ipc *ipc = ipc_get();
-       struct list_item *slist;
-       struct ipc_msg *msg;
k_spinlock_key_t key;
bool queued = false;
key = k_spin_lock(&ipc->lock);
-       if (list_is_empty(&ipc->msg_list))
-               goto out;
-
-       list_for_item(slist, &ipc->msg_list) …
```
=> Ipc4 multicore issue fixes

src/schedule/zephyr_domain.c
Replace the call to z_abort_timeout() to be able to drop dependency to timeout_q.h. This header is intended to be Zephyr kernel private and plan is to remove this.
Unblock https://github.com/zephyrproject-rtos/zephyr/pull/62051
=> zephyr: ll-schedule: stop using zephyr/timeout_q.h

src/platform/Kconfig
Linux driver set ipc timeout duration to 500ms, but FW wait 5000ms in cpu_disable_core for SET_DX ipc message. This makes driver stop but fw is still waiting. Actually the disabling can be successful in far less than 5000ms and it was first designed for FPGA case. Now change it to 400ms to make debugging easier.
This patch changes cavs and ace15 platforms and doesn't change ace20 for its current state.
fix https://github.com/thesofproject/sof/issues/8115
=> core: set timeout to 400ms for secondary core disabling

src/audio/Kconfig, src/audio/copier/copier_generic.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/include/ipc/stream.h, src/include/kernel/abi.h, src/include/sof/audio/audio_stream.h, src/include/sof/audio/pcm_converter.h, test/cmocka/src/audio/selector/selector_test.c, test/cmocka/src/audio/volume/volume_process.c, tools/topology/topology2/include/common/audio_format.conf, tools/topology/topology2/include/common/input_audio_format.conf, tools/topology/topology2/include/common/output_audio_format.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-be.conf, tools/topology/topology2/include/pipelines/cavs/dai-kpb-be.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway.conf
This patch was merged by https://github.com/thesofproject/sof/pull/7959  but revert by https://github.com/thesofproject/sof/pull/8089 for a internal CI issue. Now the CI issue has been resovled so add it again. please check issue https://github.com/thesofproject/sof/issues/8086 for detail
=> Add 24bit msb support

src/audio/Kconfig, src/audio/copier/copier_generic.c, src/audio/pcm_converter/pcm_converter_generic.c, src/audio/pcm_converter/pcm_converter_hifi3.c, src/include/ipc/stream.h, src/include/kernel/abi.h, src/include/sof/audio/audio_stream.h, src/include/sof/audio/pcm_converter.h, test/cmocka/src/audio/selector/selector_test.c, test/cmocka/src/audio/volume/volume_process.c, tools/topology/topology2/include/common/audio_format.conf, tools/topology/topology2/include/common/input_audio_format.conf, tools/topology/topology2/include/common/output_audio_format.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-be.conf, tools/topology/topology2/include/pipelines/cavs/dai-kpb-be.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway.conf
Backport of https://github.com/thesofproject/sof/pull/8151
=> [SOF-2.7] Add 24bit msb support

src/audio/google/google_rtc_audio_processing.c
The input and output audio formats are sent during module init already. So no need to overwrite it with topology data that could be incorrect.
=> audio: google_rtc: Remove set_large_config op for IPC4

tools/topology/topology1/sof-cavs-nocodec.m4
When we added the flags to disable SSP0 and SSP1 on the UP2, we took the shortcut of just removing the PCMs in topology but left the pipelines and widgets in the topology in. While this works in practice to prevent us from testing those SSPs, the right way is to also remove those pipelines also when the SSPs are disabled.
This stops tplgtool2.py from complaining constantly about this inconsistency since https://github.com/thesofproject/sof-test/pull/1079 which made the sof-test verify-tplg-binary.sh fail every time:
```
tplgtool2.py sof-glk-nocodec.tplg
ERROR: No pcm id=0 for widget=PCM0C
ERROR: No pcm id=1 for widget=PCM1C
ERROR: No pcm id=0 for widget=PCM0P
ERROR: No pcm id=1 for widget=PCM1P
ERROR: tplgtool2.py returned 4
```
This change affects only sof-apl-nocodec and …
=> sof-glk-nocodec: disable pipelines when disabling SSPs

src/audio/buffer.c, src/audio/chain_dma.c, src/audio/copier/copier_generic.c, src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/audio/module_adapter/module_adapter.c, src/audio/pipeline/pipeline-graph.c, src/include/sof/audio/buffer.h, src/include/sof/coherent.h, src/ipc/ipc-helper.c, src/ipc/ipc3/helper.c, src/ipc/ipc4/helper.c, test/cmocka/src/audio/buffer/buffer_copy.c, test/cmocka/src/audio/buffer/buffer_new.c, test/cmocka/src/audio/buffer/buffer_wrap.c, test/cmocka/src/audio/buffer/buffer_write.c, test/cmocka/src/math/fft/fft.c, test/cmocka/src/util.h
this is a step 1 of https://github.com/thesofproject/sof/pull/8106
=> Remove sparse step1

src/audio/audio_stream.c, src/audio/dp_queue.c, src/audio/sink_source_utils.c, src/audio/source_api_helper.c, src/audio/src/src.c, src/include/sof/audio/dp_queue.h, src/include/sof/audio/source_api.h, src/include/sof/audio/source_api_implementation.h, src/include/sof/audio/src/src.h, zephyr/CMakeLists.txt
re-inroducing DP queue. This PR contains DpQueue code only
dependencies:
some sparse warning are reported now till RFC changes are implemented
DP queue is a lockless circular buffer
providing safe consumer/producer cached operations cross cores
prerequisites:
1) incoming and outgoing data rate MUST be the same
2) Both data consumer and data producer declare
max chunk sizes they want to use (IBS/OBS)
required Buffer size:
- 2*MAX(IBS,OBS) if the larger of IBS/OBS
is multiplication of smaller
- 3*MAX(IBS,OBS) otherwise
The queue may work in 2 modes
1) local mode
in case both receiver and sender are located on
the same core and cache coherency
does not matter. dp_queue structure is located in cached memory
In this case DP Queue is a simple ring buffer
2) shared mode
In this case we need to …
=> pipeline 2.0: Introducing Data Processing Queue

src/audio/aria/aria.c, src/audio/copier/copier.c, src/audio/crossover/crossover.c, src/audio/dcblock/dcblock.c, src/audio/drc/drc.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/mfcc/mfcc.c, src/audio/mixer/mixer.c, src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module/cadence.c, src/audio/module_adapter/module/dts/dts.c, src/audio/module_adapter/module/generic.c, src/audio/module_adapter/module/modules.c, src/audio/module_adapter/module/passthrough.c, src/audio/module_adapter/module/waves/waves.c, src/audio/module_adapter/module_adapter.c, src/audio/multiband_drc/multiband_drc.c, src/audio/mux/mux.c, src/audio/selector/selector.c, src/audio/src/src.c, src/audio/tdfb/tdfb.c, src/audio/up_down_mixer/up_down_mixer.c, src/audio/volume/volume.c, src/include/sof/audio/module_adapter/module/generic.h, src/samples/audio/smart_amp_test_ipc4.c
Module adapter interfaces are a collection of methods, implementing the API, they never change. Make them const.
=> module-adapter: make interface const

src/include/sof/samples/audio/smart_amp_test.h
platform.h isn't needed in smart_amp_test.h, remove it from there.
=> smart-amp: remove unused header

src/ipc/ipc4/handler.c
module_init in ipc4_init_module_instance() is completely overwritten, no need to initialise it.
=> IPC4: remove a superfluous initialisation

tools/tune/multiband_drc/example_multiband_drc.m
This patch helps to find the right tool to create the setup blobs.
=> Tools: Tune: Multiband-DRC: Add comment about generator script

src/drivers/imx/sai.c
Fix sof run fail issue:
Don't need to enable packed mode for sai on 8ulp.
Also correct frame size for 8ulp.
=> imx: sai: Fix sof run fail issue on imx8ulp

src/ipc/ipc4/helper.c
This is a workaround to protect bind/unbind operations to be preempted by LL scheduler.
=> ipc4: Add preeption guard to bind/unbind

src/audio/host-zephyr.c, src/include/sof/audio/host_copier.h
before copier move to module interface, with same condition, its one time cycle is 420, now, it is 455.
After this PR, copier host playback path is lower 3% compared with before module interface.
=> audio: host: continue optimization for  host path

src/drivers/imx/sai.c
When I2S-like interface is enabled we must have
2 words in a frame because this is how I2S works (it has 2 channels)!
So, even if the user plays a mono file we must configure 2 words per slot and the second slot will be masked so the users will get silence on the second channel.
=> drivers: imx: sai: Fix frame size computation

src/include/sof/ipc/topology.h, src/ipc/ipc4/handler.c, src/ipc/ipc4/helper.c
At the pipeline reset stage, the direction of the components is not always known (example for the pipeline below), resulting in a call to a field that is null (src_buf->source->direction_set/src_buf->source->direction) and consequently a crash/timeout.
=> helper: add a condition before updating the component direction

src/audio/buffer.c, src/audio/module_adapter/module_adapter.c, src/audio/pipeline/pipeline-graph.c, src/audio/pipeline/pipeline-params.c, src/audio/rtnr/rtnr.c, src/include/sof/audio/buffer.h, src/include/sof/audio/component.h, src/ipc/ipc-helper.c, src/ipc/ipc3/helper.c, src/ipc/ipc4/helper.c
this is step 3 of implementation of https://github.com/thesofproject/sof/issues/8006
Remove usage buffer_acquire and buffer_release from pipeline infrastructure files:
- buffer.c
- module_adapter,c
- all ipc helpers
- pipeline-graph
- pipeline-params
- component.h
functions comp_get_copy_limits_with_lock and comp_get_copy_limits_with_lock_frame_aligned removed as those are identical to comp_get_copy_limits / comp_get_copy_limits_frame_aligned now
=> cache: remove buffer_acquire/release form infrastructure

src/audio/dai-zephyr.c
If sink is full and so no bytes were copied, reload DMA anyway as otherwise xrun may happen if reload is skipped for a long time.
=> dai-zephyr: Do not skip dma_reload() when sink if full

src/ipc/ipc4/logging.c
If both SOF_PROBES and MTRACE logging backends are disabled at build time, IPC4 build failed due to undefined ipc4_logging_enable_logs(). Fixes a bug in commit 1721f7042638 ("logging: add logging through probes").
=> ipc4: logging: fix builds with mtrace and probes both disabled

tools/topology/topology2/cavs-nocodec-multicore.conf, tools/topology/topology2/cavs-nocodec.conf, tools/topology/topology2/platform/intel/dmic-generic.conf
This change increases the ramp duration from 20 ms to 50 ms. It lowers the peak load of peak volume component due to longer same gain value blocks. The internal update rate for gain becomes 250 us instead of 125 us. The longer fade-in ramp also conceals better possible analog capture start transients.
This changes for 4ch capture for gain.11.1 in sof-hda-generic-4ch.tplg from
CPU_PEAK(MAX) = 21.95
PEAK(MAX)/AVG(AVG) = 7.51
to
CPU_PEAK(MAX) = 9.07
PEAK(MAX)/AVG(AVG) = 3.12
=> Tools: Topology2: Change in capture gain curve_duration to 50 ms

tools/topology/topology2/platform/intel/bt-ssp-config-lbm.conf, tools/topology/topology2/platform/intel/bt-ssp-config.conf
All existing SSP-based topologies use the audio cardinal clock, *EXCEPT* Bluetooth related ones. This doesn't make much sense, let's use the same clock source for all SSPs.
=> topology2: intel: bt-ssp-config: use cardinal clock as source

.github/workflows/zephyr.yml, app/overlays/tgl-h/ipc4_overlay.conf, app/overlays/tgl/ipc4_overlay.conf, scripts/xtensa-build-zephyr.py
For legacy CAVS platforms (TGL/ADL/EHL), the default build config is IPC4 now,
and the overlay file is already emptied. Remove the option in this build script.
=> clean up IPC4 overlay for TGL/TGL-H

src/audio/copier/copier.c, src/audio/copier/copier_dai.c, src/audio/copier/copier_generic.c, src/audio/copier/copier_host.c, src/audio/copier/copier_ipcgtw.c, src/audio/mixer/mixer.c, src/audio/mixin_mixout/mixin_mixout.c, src/audio/smart_amp/smart_amp.c
This is step 4 of implementation of #8006
next part: https://github.com/thesofproject/sof/pull/8218
=> cache: remove buffer_acquire/release part 2

src/audio/aria/aria.c, src/audio/asrc/asrc.c, src/audio/chain_dma.c, src/audio/crossover/crossover.c, src/audio/kpb.c, src/audio/volume/volume.c, src/audio/volume/volume_ipc3.c, src/audio/volume/volume_ipc4.c
This is step 5 of implementation of #8006
next part:https://github.com/thesofproject/sof/pull/8219
=> cache: remove buffer_acquire/release part 3

tools/topology/topology2/include/pipelines/cavs/dai-copier-be.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-eqiir-module-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-mixin-capture.conf, tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-module-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/dai-kpb-be.conf, tools/topology/topology2/include/pipelines/cavs/deepbuffer-playback.conf, tools/topology/topology2/include/pipelines/cavs/gain-capture.conf, tools/topology/topology2/include/pipelines/cavs/gain-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/gain-module-copier.conf, tools/topology/topology2/include/pipelines/cavs/gain-playback.conf, tools/topology/topology2/include/pipelines/cavs/google-rtc-aec-capture.conf, tools/topology/topology2/include/pipelines/cavs/highpass-capture-be.conf, tools/topology/topology2/include/pipelines/cavs/host-copier-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/host-copier-gain-src-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/host-gateway-capture.conf, tools/topology/topology2/include/pipelines/cavs/host-gateway-playback.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway-capture.conf, tools/topology/topology2/include/pipelines/cavs/io-gateway.conf, tools/topology/topology2/include/pipelines/cavs/mixout-aria-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-alh-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-efx-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-efx-mbdrc-dai-copier-playback.conf, tools/topology/topology2/include/pipelines/cavs/mixout-gain-host-copier-capture.conf, tools/topology/topology2/include/pipelines/cavs/mixout-mixin.conf, tools/topology/topology2/include/pipelines/cavs/src-gain-mixin-playback.conf, tools/topology/topology2/include/pipelines/cavs/wov-detect.conf
The pipeline-common.conf helps us to define several common pipeline attributes
include pipeline index, there is no need to define pipeline index in each
pipeline class definition if pipeline-common.conf is included.
=> topology2: remove duplicated pipeline index attribute definition

.github/workflows/zephyr.yml
Ninja seems to have just mysteriously disappeared from https://github.com/actions/runner-images/blob/win22/20230918.1/images/win/Windows2022-Readme.md See #8250 for more details.
Let's try to install it explicitly.
=> [SKIP SOF-TEST] .github: build-windows: choco install ninja

tools/topology/topology2/cavs-nocodec-multicore.conf, tools/topology/topology2/cavs-nocodec.conf
We need to care about audio user experience and peak MCPS usage in production topologies.
The alsabat test is disturbed by longer ramp so it can be removed from nocodec topologies since the codec is never used by end users and also the peak MCPS mitigation is not relevant for a test topology, as long as higher MCPS is not triggering error reports. The curve duration becomes without explicit set the default 20 ms.
Fixes: #8238
Fixes: d0d74a477f64a83654bccb3905175584d05d9257
("Tools: Topology2: Change in capture gain
curve_duration to 50 m")
=> Tools: Topology2: Remove 50 ms curve duration set from nocodec

app/prj.conf
Starting from Zephyr commit f0daf904bb02, CONFIG_PICOLIBC is on by default.
PICOLIBC does not seem compatible with sparse yet: https://github.com/zephyrproject-rtos/zephyr/issues/63003
Even if it were compatible with sparse, it seems like a pretty big change that we should not immediately and blindly accept.
=> app/prj.conf: disable PICOLIBC with CONFIG_MINIMAL_LIBC=y

src/platform/lunarlake/include/platform/lib/memory.h
FW infrastructure shall support buffering of historic data from 1ch up to 6 channels 24bit samples in 24bit container. For this reason, the heap should be extended. Increase HEAPMEM_SIZE by 0x90000 because for audio format 16000Hz/6ch/24bit history_buffer_size = 16 * 6 * 3 * 2100s = 604800 bytes (0x93A80)
The same change was applied to MTL previously.
=> lnl: memory: expand HEAPMEM_SIZE for KPB

tools/logger/CMakeLists.txt, tools/logger/config.h.in, tools/logger/convert.c, tools/logger/convert.h, tools/logger/filter.c, tools/logger/logger.c, tools/logger/misc.c
Preparation for backporting #8216 release fixes.
Zero conflict, fully automated backport with just:
```
git log --oneline --format=%h  2c1f089d3965..origin/main -- tools/logger/*.c  |
tac | git cherry-pick -x --stdin
```
=> [stable-v2.2] backport all sof-logger updates from main

zephyr/CMakeLists.txt
The file is found from subdirectory src/audio/google. Without fix if CONFIG_COMP_GOOGLE_HOTWORD_DETECT is enabled build fails:
CMake Error at sof/zephyr/cmake/modules/extensions.cmake:424 (add_library):
Cannot find source file:
/src/audio/google_hotword_detect.c
=> Zephyr: Fix path to google_hotword_detect.c

src/audio/dcblock/dcblock.c, src/audio/eq_fir/eq_fir.c, src/audio/eq_iir/eq_iir.c, src/audio/igo_nr/igo_nr.c, src/audio/mfcc/mfcc.c, src/audio/multiband_drc/multiband_drc.c, src/audio/mux/mux.c, src/audio/mux/mux_generic.c, src/audio/rtnr/rtnr.c
This is step 6 of implementation of #8006
next part: https://github.com/thesofproject/sof/pull/8220
=> cache: remove buffer_acquire/release part 4

smex/elf.c, tools/logger/convert.c, tools/logger/logger.c
Fixed many minor bugs in sof tools applications.
=> Fix code quality issues in sof tools

tools/probes/probes_demux.c, tools/probes/probes_demux.h, tools/probes/probes_main.c
The finalize_wave_files() should be called to update the WAV header to be valid.
This should be only done when demuxing to files.
=> tools/probe: Fix WAV header creation for extracted audio streams

src/audio/drc/drc.c, src/audio/google/google_hotword_detect.c, src/audio/google/google_rtc_audio_processing.c, src/audio/module_adapter/module/cadence.c, src/audio/module_adapter/module/dts/dts.c, src/audio/module_adapter/module/waves/waves.c, src/audio/selector/selector.c, src/audio/tdfb/tdfb.c, src/audio/tone.c, src/probe/probe.c
This is step 7 of implementation of #8006
next part: https://github.com/thesofproject/sof/pull/8221
=> cache: remove buffer_acquire/release part 5

src/audio/module_adapter/module_adapter.c, src/audio/pipeline/pipeline-graph.c, src/audio/src/src_ipc4.c, src/include/sof/audio/component.h, src/schedule/zephyr_dp_schedule.c
This PR introduces a Earlier Deadline First scheduling policy for DP processing
currently there's a limitation - DP module must be surrounded by LL modules.
it simplifies algorithm - there's no need to browse through DP chains calculating
deadlines for each module in function of all modules execution status.
Now is simple - modules deadline is its start + tick time.
example:
Lets assume we do have a pipeline:
LL1 -> DP1 -> LL2 -> DP2 -> LL3 -> DP3 -> LL4
all LLs starts in 1ms tick
for simplification lets assume
- all LLs are on primary core, all DPs on secondary (100% CPU is for DP)
- context switching requires 0 cycles
DP1 - starts every 1ms, needs 0.5ms to finish processing
DP2 - starts every 2ms, needs 0.6ms to finish processing
DP3 - starts every 10ms, needs 0.3ms to finish processing …
=> dp: Eearliest deadline first scheduling policy

.github/workflows/sparse-zephyr.yml, app/prj.conf
Add a sparse-specific workaround for the incompatibility with picolibc (the new Zephyr default)
- https://github.com/zephyrproject-rtos/zephyr/issues/63003
Also fix comment in commit 2a9473a17be4 ("app/prj.conf: disable PICOLIBC with CONFIG_MINIMAL_LIBC=y"): we don't need to disable PICOLIBC _everywhere_; we only need to disable it when using sparse.
=> .github/sparse-zephyr: add -DCONFIG_MINIMAL_LIBC to avoid picolibc

src/audio/dai-legacy.c, src/audio/dai-zephyr.c, src/audio/host-legacy.c, src/audio/host-zephyr.c, src/include/sof/audio/buffer.h, src/ipc/ipc3/dai.c, src/samples/audio/detect_test.c, src/samples/audio/smart_amp_test_ipc3.c, src/samples/audio/smart_amp_test_ipc4.c
This is step 8 of implementation of #8006
=> cache: remove buffer_acquire/release part 6

.github/workflows/zephyr.yml
At the beginning, we have two build jobs in github action to build IPC3 and IPC4 firmware for TGL/TGL-H.
The PR https://github.com/thesofproject/sof/pull/8048 switches cAVS2.5 configs to use IPC4 by default and empties the cAVS2.5 overlay files. After the change, the xtensa-build-zephyr.py script is building the
same IPC4 firmware with or without '-i IPC4' option. So we have two jobs running different build command but build the same IPC4 firmware.
Recently, commit 5004d0fe1e74 ("zephyr.yml: remove ipc option for zephyr build") removes '-i IPC4' option in github action for TGL/TGL-H IPC4 build. So we have duplicated jobs to build firmware for TGL and TGL-H now.
This patch removes the duplicated build job which previously is used to build IPC3 firmware for TGL/TGL-H.
=> [SKIP CI]github action: remove duplicate build for TGL/TGL-H

src/include/sof/audio/buffer.h
This is step 9 of implementation of #8006
buffer_acquire and buffer_release are no longer in use
remove stubs from the code
=> cache: remove buffer_acquire/buffer_release stubs

smex/elf.c, tools/logger/convert.c, tools/logger/logger.c
Clean backport of #8216, zero git conflict.
=> [stable-v2.2] backport  Fix code quality issues in sof tools #8216

src/audio/module_adapter/module_adapter.c
This patch fixes a confusing error message typo in module_adapter.c.
=> Audio: Module adapter: Fix error message typo sinks -> sources

src/audio/mixin_mixout/mixin_mixout.c, src/audio/module_adapter/module_adapter.c, src/include/sof/audio/module_adapter/module/generic.h, src/samples/audio/smart_amp_test_ipc4.c
Mutex protected module_source_info was an old failed attempt to support cross-core connection of mixin and mixout. That functionality was never properly tested as FW did not support cross-core connections there.
For connected mixin and mixout located on same core, that functionality is not needed. For cross-core connection, that functionality creates dead-lock.
=> ipc4: mixin/mixout: Remove redundant source_info stuff

west.yml, zephyr/lib/regions_mm.c
Zepych update: total of 853 commits.
i8c4eec7ac6 intel_adsp: boot_complete must be done PRE_KERNEL_1
1fc16e6565 release: Zephyr 3.5.0-rc1
c910dc81a6 sys_clock: header: minor cleanup and doxygenization
b9f8b91692 kernel: sys_clock: remove stray z_enable_sys_clock prototype
cc2a558707 kernel: move more internal smp calls into internal domain
a1c7bfbc63 kernel: remove unused z_init_thread_base from kernel.h
209ff606be kernel: move internal smp calls to a internal header
e19f21cb27 kernel: move z_is_thread_essential out of public kernel header
f0c7fbf0f1 kernel: move sched_priq.h to internal/ folder
e6f1090553 kernel: Integrate object core statistics
1d5d674e0d kernel: Add initial k_obj_core_stats infrastructure
6df8efe354 kernel: Integrate object cores into kernel
55db86e512 …
=> west.yml: update zephyr to v3.5.0-rc1

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
Enable bclk early start to remove speaker pop noise when resuming from S3 or switching audio path.
[copy from issue tracker]
What steps will reproduce the problem?
1. Updated Rev8 image via recovery media,went to OOBE and boot into OS.
2. Play audio file with Gallery app.
3. Plug Typec headphone to unit then unplug it.
4. Find Po noise output from speaker.
What is the expected output?
There is no" Po" noise output from speaker when unplug Typec headphone/Rusume unit from S3 with audio playing.
What do you see instead?
Po noise output from speaker when unplug Typec headphone/Rusume unit from S3 with audio playing.
=> topology1: sof-adl-cs35l41: remove pop noise

src/audio/volume/peak_volume.h, src/audio/volume/volume.c, src/audio/volume/volume_ipc4.c, tools/topology/topology2/include/components/gain.conf
The first patch adds a conversion from IPC4 to SOF volume ramp types.
The second patch changes further volume to be able to handle the supported ramp types.
The third patch adds to gain.conf the other supported ramp types. The default is kept as windows fade.
=> Audio: Volume: Handle all volume ramp types

CMakeLists.txt, src/arch/xtensa/CMakeLists.txt, src/ipc/ipc4/CMakeLists.txt, zephyr/CMakeLists.txt
2 minor, zero-change commits preparing the big rimage merge #8178. Successfully tested in test PR #8286
=> cmake: add new ${RIMAGE_TOP} variable

src/include/ipc4/module.h
When IPC4_MOD_ID was introduced it returned a non-zero module ID under IPC4 and 0 under IPC3.
After commit "45ca3d430 (include: ipc4: module: fix component ID macros)", the IPC4_MOD_ID, under IPC3, is not 0 anymore.
Therefore, in order to not propagate the commands across pipelines for IPC4, add them under CONFIG_IPC_MAJOR_4.
This fixes playback with mixer.
Without this patch, with IPC3, we get:
src/audio/component.c:130  ERROR comp_set_state(): wrong state = 1, COMP_TRIGGER_PRE_START ../pipeline-stream.c:436  ERROR pipeline_trigger_run(): ret = -22, host->comp.id = 12, cmd = 7 src/ipc/ipc3/handler.c:540  ERROR ipc: comp 12 trigger 0x40000 failed -22
That's because, at some point, the trigger command is not propagated across pipeline and the component state remains unmodified.
=> ipc: don't propagate commands across pipelines for IPC4

west.yml
This commit bumps up the Zephyr revision to contain the fix for the i.MX93 CI build failure.
=> west.yml: Bump up Zephyr revision

src/audio/tdfb/tdfb.c, src/include/ipc4/header.h, src/include/sof/audio/tdfb/tdfb_comp.h
First patch adds the needed IPC4 header
Second patch updates the TDFB component
=> Audio: TDFB: Update component for IPC4

src/audio/module_adapter/CMakeLists.txt, src/audio/module_adapter/module/generic.c, src/audio/module_adapter/module_adapter.c, src/audio/module_adapter/module_adapter_ipc3.c, src/audio/module_adapter/module_adapter_ipc4.c, src/include/sof/audio/module_adapter/module/generic.h, test/cmocka/src/audio/eq_fir/CMakeLists.txt, test/cmocka/src/audio/eq_iir/CMakeLists.txt, test/cmocka/src/audio/mixer/CMakeLists.txt, test/cmocka/src/audio/mux/CMakeLists.txt, test/cmocka/src/audio/volume/CMakeLists.txt, zephyr/CMakeLists.txt
Create ipc3 and ipc4 specific source file, these files will only be used to store specific code.
Then move code from module_adapter.c to module_adapter_ipc3.c and module_adapter_ipc4.c.
=> audio: module adapter: split out module adapter ipc3 and ipc4 code

src/audio/module_adapter/Kconfig
previously, linear ramp only applicable for ipc3, however, linear is also applicable for chrome/linux with ipc4, so remove ipc3 restriction.
=> audio: volume: enable linear ramp for ipc4 volume

zephyr/CMakeLists.txt
A stray } is at the end of RIMAGE_CONFIG_PATH causing issues when
signing images.
=> zephyr: remove stray } from RIMAGE_CONFIG_PATH

src/schedule/zephyr_domain.c, west.yml
Also, backport 98e8f8fdc zephyr: ll-schedule: stop using zephyr/timeout_q.h  to get rid of a compilation issue.
=> [imx-stable-v2.7] Update west.yml for imx-stable-v2.7 to point to zephyr v.3.5 rc2

tools/topology/topology2/cavs-sdw-src-gain-mixin.conf, tools/topology/topology2/include/pipelines/cavs/host-gateway-capture.conf
With input_audio_format/output_audio_format objects in preparation to deprecate the audio_format class.
=> topology2: host-gateway-capture: Replace audio_format objects

src/audio/module_adapter/module_adapter_ipc3.c
Revert "module_adapter: avoid module init crash in case of ipc data invalid"
This reverts 'commit https://github.com/thesofproject/sof/commit/e847c8b270150353551d4720e382502c9a916496 ("module_adapter: avoid module
init crash in case of ipc data invalid")'.
No data is not an invalid case for mixer, for example.
Fixes: https://github.com/thesofproject/sof/issues/8265
=> Revert "module_adapter: avoid module init crash in case of ipc data invalid"

tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake
rt713 and rt1713 are in different SoundWire links. So, no DAI type will be appended to DAI link name. We should use default stream name in the topology.
=> topology2: sof-mtl-rt713-l0-rt1316-l12-rt1713-l3: use default stream name

src/audio/module_adapter/module_adapter.c, src/include/ipc4/module.h
Backport mixer fixes on imx-stable-v2.7
Second commit is not the one from main, is the revert of e847c8b27 ("module_adapter: avoid module init crash in case of ipc data invalid").
That's because, on main, there is a split of module_adapter into module_adapter_ipc3 and module_adapter_ipc4, and the fix applies  only to ipc3.
=> Backport to imx-stable-v2.7

tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
Backport PR https://github.com/thesofproject/sof/pull/8282 cavs2.5-001-drop-stable branch.
=> [cavs2.5-001] topology1: sof-adl-cs35l41: remove pop noise: backport to cavs2.5-001

tools/topology/topology2/development/cavs-nocodec-rtcaec.conf, tools/topology/topology2/development/tplg-targets.cmake
The first playback PCM is for AEC mic input via SSP0 LBM. The second playback PCM is for AEC reference via SSP2 LBM. The first capture PCM is the AEC output.
The AEC (mockup) can be run and tested with the topology like this:
$ aplay -Dhw:0,0 mic_clip.wav &
$ aplay -Dhw:0,2 ref_clip.wav &
$ arecord -Dhw:0,0 -f dat -d 10 output.wav
With AEC mockup version output.wav is mix of microphone and reference.
=> Tools: Topology2: Add nocodec topology to test google-rtc-aec

tools/tune/common/tplg2_write.m, tools/tune/common/tplg_write.m, tools/tune/dcblock/example_dcblock.m
This patch modifies script example_dblock.m to create in addition to existing default coefficients blob with parameter R=0.98 a set of blobs those provide (-3 dB) cut-off frequencies 20, 30, 40, 50, 100, 200 Hz for 16 kHz and 48 kHz for various usages. Human understandable parameters for blobs helps to select the configuration for the needed dcblock usage.
The parameter value R for given frequencies is calculated with iterative function dcblock_rval_calculate(). A closed form equation might be possible to derive from the transfer function. If such is found this function can be replaced with quicker equation -- or with more advanced faster converging iteration.
The topology blob export functions are also modified to add comment line for exact build command.
=> Tools: Tune: dcblock: Create set of cut-off frequencies

tools/topology/topology1/CMakeLists.txt
Use dynamic for all the rpl SDW topologies.
I am not sure if this should be applied to main branch, too.
=> [stable-v2.2] topology1: Use DYNAMIC for RPL SDW topologies

src/audio/pipeline/pipeline-schedule.c
After enabling deadline calculation DP threads began to lose priority in relation to logger thread which currently is set to the same priority but has zeroed deadline.
Since processing should be not disturbed by logging operations, the ZEPHYR_DP_THREAD_PRIORITY must be set to lower value than logger.
=> [MTL-006] DP: fix DP thread priority

tools/rimage/README.md
We still have tomlc99 as a git submodule for now.
=> [SKIP SOF-TEST] tools/rimage/README.md: update following transfer to sof.git

tools/topology/topology2/platform/intel/sdw-amp-generic.conf, tools/topology/topology2/platform/intel/sdw-dmic-generic.conf
Setting the in bit depth for the second audio format in the host-gateway-capture object results in resetting the channel count to 4. The in_bit_depth is set to 32-bit by default for all audio formats in host-gateway-capture class already.
Fixes: 7a11e27bf2a19e9acf643d416fc079f479fd2748 ('topology2: host-gateway-capture: Replace audio_format objects')
=> topology2: sdw-amp-generic: Remove incorrect audio format
