tools/topology/topology2/cavs-nocodec.conf

The num_output_pins was set for pass-through path but missed in normal path. Without it Linux kernel driver wouldn't set second output pin format for dai copier which connects smart amp and gain module.

topolog2: nocodec: set output_pin number

---

src/audio/volume/volume.c
src/audio/volume/volume.h
src/audio/volume/volume_ipc3.c
src/audio/volume/volume_ipc4.c

windows volume ramp peak optimization, currently, with these patches, nearly 20% are reduced, measured on TGL with 48k 2 channel stream. if there is 4 channel or more, the reduction will be higher due to no matter channels you have, as long as target volume are same, ramp calculation only take once.

audio: volume: optimize windows volume ramp

---

tools/rimage/config/lnl.toml
tools/rimage/config/tgl-cavs.toml
tools/rimage/config/tgl-h-cavs.toml

This patch adds same RTC_AEC module entry as added earlier to config/mtl.toml. The purpose is enable testing the component in other platforms.

Tools: Rimage: Config: Add RTC_AEC to TGL. TGL-H, and LNL

---

src/audio/pipeline/pipeline-schedule.c

After enabling deadline calculation DP threads began to lose priority in relation to logger thread which currently is set to the same priority but has zeroed deadline.
Since processing should be not disturbed by logging operations, the ZEPHYR_DP_THREAD_PRIORITY must be set to lower value than logger.

DP: fix DP thread priority

---

tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake

This is additional HW board: No SDW_DMIC configuration
SDW0: rt713 Jack codec
SDW1: rt1316 smart amp l
SDW2: rt1316 smart amp r

topology2: add rt713_rt1316, no sdw_dmic

---

tools/topology/topology2/doc/sof.doxygen.in

The main page sources were dropped out from the document sources in the last review rounds of the original PR. Add *.doxy to FILE_PATTERNS to add it back.

topology2: doc: Fix main page

---

tools/tune/tdfb/bf_blob_pack.m
tools/tune/tdfb/bf_defaults.m
tools/tune/tdfb/bf_export.m
tools/tune/tdfb/bf_filenames_helper.m
tools/tune/tdfb/example_line_0mm36mm146mm182mm.m
tools/tune/tdfb/example_pass_config.m
tools/tune/tdfb/example_two_beams.m

This patch adds generation of.conf format blobs for tplg2 with IPC4 format blob. The blob ABI header retrieving is changed to common helper functions path those already have the support.

Tools: Tune: TDFB: Add support for IPC4 and tplg2 blobs

---

tools/rimage/.gitignore

rimage is not so special that it needs its personalized .gitignore

[SKIP SOF-TEST] Delete inherited tools/rimage/.gitignore

---

.github/workflows/zephyr.yml

It's bold enough with the SOF main branch, it's obviously not going to work with a stable branch of SOF.

[stable-v2.7] [SKIP SOF-TEST] .github/zephyr: stop trying Zephyr main branch with a stable branch

---

tools/topology/topology2/CMakeLists.txt

We'll use this new function to require ALSA 1.2.5 and finally rename to
"codec_consumer" (see revert discussion https://github.com/thesofproject/sof/pull/5192)

topology2/cmake: extract new function "alsatplg_version()" for re-use

---

.github/workflows/zephyr.yml

Fixes issue reported in stable-v2.7 #8353 which wants to use our own,
downstream Zephyr branch.

[SKIP SOF-TEST] .github/zephyr: de-hardcode the name of the zephyr remote

---

tools/topology/CMakeLists.txt
tools/topology/topology2/CMakeLists.txt

Stop producing corrupted .tplg files when using `codec_consumer` (e.g.:
sof-imx8mp-btsco-dual-8ch.tplg, sof-imx8ulp-9x9-btsco-16k.tplg, ...)
Then we'll be able to finally search/replace "codec_master", see revert

topology/cmake: skip all topologies when alsatplg < 1.2.5

---

src/drivers/imx/micfil.c

There is no need to print an error at the beginning of a function. The usual behavior should be to print an info.

drivers: imx: micfil: Change loglevel to info

---

src/include/sof/schedule/ll_schedule_domain.h
src/ipc/ipc4/helper.c
src/schedule/zephyr_domain.c
zephyr/Kconfig

Implements binding of two pipelines from different cores so stream could travel cross-core.

ipc4: Add cross-core binding support

---

west.yml

Updating zephyr version to v3.5.0 release.
Total of 352 commits.

west.yml: update zephyr to v3.5.0

---

.github/workflows/zephyr.yml
versions.json
west.yml

commit 335c51b98c2eaa390df1435f1f8b8a026e70abd2 (HEAD -> stable-v2.7)
Author: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Date:   Thu Oct 19 17:59:52 2023 +0300
versions.json: bump version to 2.7.1
Set version to 2.7.1 as we start merging bugfixes.
commit f6b74afe4e471431c4fa30168253100a43e628cf
Author: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Date:   Thu Oct 19 17:56:49 2023 +0300
west.yml: update Zephyr to sofproject stable-v2.7
Update Zephyr to use thesofproject/zephyr/stable-v2.7 with
following one commit backported from Zephyr main.
3c58926487eb drivers: dma: intel-adsp-hda: Correct DGCS:SCS bit for
Link: https://github.com/thesofproject/sof/issues/8236

[stable-2.7] west.yml: update Zephyr to sofproject stable-v2.7

---

.github/workflows/zephyr.yml

Fixes commit 4bc6488b24e44 (".github/zephyr: de-hardcode the name of the zephyr remote")
(Yay for duplication)

[SKIP SOF-TEST] .github/zephyr: de-hardcode the remote name in the Windows build too

---

scripts/rebuild-testbench.sh

It's not clear why `LDFLAGS=-Wl,-LE` was added in
commit https://github.com/thesofproject/sof/commit/10d0b3b5e107506583f1a8b6d16ef1f14f30a233 ("Scripts: Add xt-run build target for
rebuild-testbench.sh"). Maybe it was supposed to be `-Wl,-EL`?
Either way this flag has always been interpreted as adding the directory
`./E/` to the search library path, which obviously never had any
effect; proof below. So it can safely be removed.
Here's the proof:
```
mv ~/XCC/install/builds/RG-2017.8-linux/cavs2x_LX6HiFi3_2017_8/xtensa-elf/lib/libm.a .
./scripts/rebuild-testbench.sh -p tgl
cmake --build tools/testbench/build_xt_testbench/ -- testbench
mkdir tools/testbench/build_xt_testbench/E/
cp libm.a  tools/testbench/build_xt_testbench/E/
cmake --build tools/testbench/build_xt_testbench/ -- testbench …
```

[SKIP SOF-TEST] rebuild-testbench.sh: drop no-op LDFLAGS=-Wl,-LE

---

tools/sof_ri_info/sof_ri_info.py

Print out some information from the Signed package info extension, the most important information being is the partition_usage which is used to select key slot to be used for verification.

sof_ri_info: Decode the Signed package info extension

---

src/drivers/intel/ssp/ssp.c
src/include/ipc/dai-intel.h
src/include/kernel/abi.h
src/include/sof/drivers/ssp.h
tools/topology/topology1/platform/common/ssp.m4

In the earliest design, mclk is turned on in set_config() and never turned off. The behavior is modified in this commit:
d5840a920073 ("ssp: move mclk request/release to pre_start and post_stop")
Now the mclk is enabled only during audio streaming so some codec may pop. This commit adds the always-on behavior back as an new feature.
(cherry picked from commit 8dfc008b8b99a1bdbe7707739b62714aaa65abf6)

[stable-v2.2] intel: ssp: implement mclk always-on feature

---

src/audio/audio_stream.c
src/include/sof/audio/audio_stream.h

Set the default alignment value after buffer format is set in audio_stream_set_params instead of in audio_stream_init where the buffer format hasn't been set yet.

Audio: Fix the default alignment setting

---

tools/rimage/src/include/rimage/toml_utils.h
tools/rimage/src/toml_utils.c

3 commits.
Also fix compilation with clang 15
I checked that the MTL checksums are identical before/after these code changes.

rimage: stop ignoring errors in parse_uuid()

---

.github/workflows/zephyr.yml

Resuming abandoned:
- #8387
Two clean .github cherry-picks without any conflict or other change.

[SKIP SOF-TEST] .github: fix stable-v2.7 branch

---

west.yml

Contains 800+ commits merged after 3.5.0 release, including following directly affecting SOF targets:
f4cb487b79f9 modules: sof: Options only when module is available
02deea0e806a ace: alh: Only ACE1.5 has OSEL feature
f0326f72498c tests: dma_loopback: Intel ADSP ACE15 disable PM
adf6d0e3d80e soc: intel_adsp: lpsram enable retention mode
eeb4f2f76d6d soc: intel_adsp: hpsram enable retention mode
16f729214b50 soc: intel_adsp: lpsram init refactor
112611378f85 soc: intel_adsp: hpsram init refactor
cdd4d8470323 xtensa: add custom mem range check functions

west.yml: update Zephyr to 460c2167e4f3

---

src/include/sof/trace/preproc.h
src/include/sof/trace/trace.h

The xt-clang RI-2022.10 compiler headers define UNUSED. The rename of the macro for trace fixes in testbench build this error:
In file included sof/tools/tplg_parser/pga.c:17:
In file included sof/tools/tplg_parser/
../../src/include/sof/lib/uuid.h:11:
In file included sof/tools/tplg_parser/
../../src/include/sof/common.h:105:
/home/singalsu/work/current/sof/sof/tools/tplg_parser/
../../src/include/sof/trace/preproc.h:162:9: error:
'UNUSED' macro redefined [-Werror,-Wmacro-redefined]
#define UNUSED(arg1, ...) do { META_RECURSE(
xtensa/XtDevTools/install/tools/RI-2022.10-linux/XtensaTools/
xtensa-elf/include/xtensa/xtensa-types.h:60:9:
note: previous definition is here
#define UNUSED(x)       ((void)(x))

Trace: Rename UNUSED() macro to SOF_TRACE_UNUSED()

---

tools/rimage/src/include/rimage/module.h
tools/rimage/src/module.c

Fixed the order in which sections are placed in the output firmware image for platforms using a simple manifest.
Fixes: #8336

rimage: module: Fix section order in output image

---

west.yml

Update rimage to version 469102a8f6052ce6a374b870ea945a84d04c3b1a
Only one new commit to fix Github Actions:
config/lnl.toml: drop now invalid signed_pkg.partition_usage
See https://github.com/thesofproject/rimage/pull/190

[STABLE-v2.7] rimage: config/lnl.toml: drop now invalid signed_pkg.partition_usage

---

tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake

This patch adds sof-mtl-rt722-l0.tplg, which is used to support MTL RVP + RT722 EVB combination.
Headphone, speaker and DMIC functions are verified with this topology.

topology2: Add sof-mtl-rt722-l0 support

---

tools/topology/topology2/include/components/google-rtc-aec.conf

Add new token to adjust the input/output buffer size for process modules.

topology2: google-rtc-aec: adjust the IBS/OBS size based on process needs

---

app/stub_build_all_ipc3.conf
src/audio/smart_amp/smart_amp.c

smart_amp: fix code and re-enable it on stub builds

---

src/idc/zephyr_idc.c

When executing a blocking operation on a remote core it is expected that an exit code of the operation is passed to the caller as if the operation was on the same core
In fact, a result of message passing was returned, so in most cases result was success, no matter what operation result was

idc: bugfix - exit code was not passed to the caller

---

src/drivers/intel/ssp/ssp.c
src/include/sof/drivers/ssp.h

Hi,
This PR contains two patches:
This first one (verified on product: #7732) changes how the DMA request is managed (or not managed currently):
instead of keeping both TX and RX DMA request active, only keep the one enabled which is in use.
The second one is an improved version of #7735 to make sure that the DMA is not running to fill the TX FIFO when we disable the SSP (in case of playback only stop).
#7735 has been verified on production, this change just makes it a bit safer.
Replaces #7732 and #7735

[stable-v2.2] intel: ssp: DMA request management and TX stop simplification

---

src/platform/intel/ace/include/ace/lib/mailbox.h
src/platform/intel/cavs/include/cavs/lib/mailbox.h

mailbox_sw_regs_write is used by dai to update llp node. In multi-core test, the updated llp node is invisable to other cores although dcache_writeback_region is used on both cavs & ace platforms. Now use uncached address to write memory directly which is aligned with other mailbox access functions.
Validated on cavs & ace platforms.
multi-core topology: https://github.com/thesofproject/sof/pull/8240

mailbox: use uncached address to write sw regs

---

app/sample.yaml

This will catch earlier compile-time regressions like this one: https://github.com/zephyrproject-rtos/zephyr/pull/61166#issuecomment-1789717233
Zephyr commit 06cfbd4159fd ("drivers: power_domain: Introduce a gpio monitor driver")

[SKIP SOF-TEST] app/sample.yml: add MTL and LNL to Zephyr CI

---

src/platform/intel/ace/lib/watchdog.c

This will fix num cpus and use runtime data to work properly on diffrent HW configs

platform: ace: watchdog: fix num cpus

---

src/audio/dai-zephyr.c

Refactor dai params into more feasible functions and remove duplicate code. No functional change.
The original pr: https://github.com/thesofproject/sof/pull/7345 was done by Jaska but was not merged. Since he has leaved intel, I will help to rebase it and submit it again .

dai-zephyr: refactor dai params

---

src/samples/audio/smart_amp_test_ipc3.c
src/samples/audio/smart_amp_test_ipc4.c

Avoids conflicts with the "real" smart_amp.c when the "stub" compilation check enables everything and compiles everything.
Also makes `git grep smart_thing` a bit more convenient in some cases.
Only the IPC3 sample clashed because the real code does not use MODULE_ADAPTER(). Pre-emptively rename the IPC4 sample too for consistency and in case the real code changes its mind later.
Only global symbols are renamed; no need to git churn private symbols.
Fixes commit ba2cfe3daa55 ("app/stub*.conf: add
CONFIG_SAMPLE_SMART_AMP=y") which clashed with commit d4d0a0ca134f ("smart_amp: fix code and re-enable it on stub builds")
CI did not detect the clash because these two commits were merged at the same time.
In case anyone is interested, the CI "fix" to prevent this type of race is a GitHub …

samples: change smart_amp_test prefix `smart_amp_` to `smart_amp_test_`

---

tools/topology/topology2/cavs-rt5682.conf
tools/topology/topology2/platform/intel/google-rtc-aec-reference.conf

RTC AEC module is using DP and rest of echo ref pipeline is LL, and both can run on secondary cores.
In order to assign RTC_AEC DP alone on secondary core, add new macro GOOGLE_AEC_DP_CORE_ID.

topology2: google-rtc-aec: expose component core_id for override

---

tools/topology/topology1/sof-imx8-compr-wm8960-mixer.m4
tools/topology/topology1/sof-imx8-wm8960-mixer.m4

Set correct TDM slot width to 32 bits.
The error has been discovered after commit
0ba64e98ec7d ("SAI: use topology params").
We start using the tdm_slot_width from topology,
rather than hardcoded in code.

topology: imx: fix tdm slot width value

---

west.yml

Contains 500+ commits, including following directly affecting SOF targets:
0a6fc6f70a25 soc: intel_adsp: cavs: fix dts memory address format
4b02bbc3297f cmake: xtensa: update xtensa SoC to use SOC_LINKER_SCRIPT variable
8bccb645aae8 boards: intel_adsp: fix board flashing
a4b9692155a3 soc: intel_adsp/cavs: add secondary dsp context save support
0891448ac908 soc: intel_adsp: don't enable interrupt before k_cpu_idle
c73e67018d0a power_domain_intel_adsp.c: revert recent INIT_PRIORITY change
385ceb714537 soc: xtensa: nxp_adsp: rt595: move .noinit

west.yml: update Zephyr to 26002b060708

---

src/platform/intel/cavs/platform.c
zephyr/lib/cpu.c

Register pm_state_notifier to set ready_flag for secondary core when it is powered up for second time after first fw boot. We can remove CONFIG_ADSP_IMR_CONTEXT_SAVE check for cavs platform for this feature.
zephyr side pr: https://github.com/zephyrproject-rtos/zephyr/pull/62522
It has been discussed in https://github.com/thesofproject/sof/pull/8156 and https://github.com/thesofproject/sof/pull/8170
The IMR_CONTEXT_SAVE check was first introduced by https://github.com/thesofproject/sof/pull/8027

[Depends on 62522] zephyr: cavs: add secondary core context save support

---

tools/topology/topology2/development/cavs-nocodec-rtcaec.conf

It was confirmed that the IPC4 version of Google RTC AEC is not using the bytes control, so it can be safely removed from topology.
This fixes topologies build error:
ALSA lib conf.c:838:(get_char_skip_comments)
Cannot access file include/components/google-rtc-aec/rtc-aec-blob.conf
Fixes: 	64fcebbd64bf8e8be4ec7098215d7281fa6a4791
("Tools: Topology2: Add nocodec topology to test google-rtc-aec")
Fixes:	#8357

Tools: Topology2: Remove bytes control from cavs-nocodec-rtcaec.conf

---

src/schedule/zephyr_ll.c

When a chain DMA stream is the only one running, stopping it currently takes 100ms. The reason is that the chain DMA driver is trying to stop the task directly from the IPC context instead of letting the task exit on its next scheduling event. The IPC thread is indeed trying to wait on a semaphore for the task to exit, but that doesn't work either, because zephyr_domain_unregister() terminates the thread before it signals the semaphore. To fix this we swap the order and signal the semaphore before terminating the thread. Fixes #8445

schedule: cancel a task before freeing it

---

src/audio/asrc/asrc.c
src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc3.c
src/include/sof/audio/component.h
src/include/sof/audio/module_adapter/module/module_interface.h
tools/testbench/common_test.c

convert ASRC to module interface with IPC4.

Asrc module convert

---

tools/testbench/topology.c

Before the fix the comp->core in ipc_comp_new() is garbage and the check for maximum core count fails. The pointer to struct comp should be passed here instead of asrc.
Fixes:	d9f9340e1a8ebc276fb67bf9e0a0c7bd08e4e52b
("tplg_parser: split out testbench logic and partition
features per file.")

Tools: Testbench: Fix ASRC component load

---

src/audio/source_api_helper.c
src/include/ipc4/base-config.h
src/include/sof/audio/source_api.h
src/ipc/ipc4/helper.c

sink/src API must grow to provide similar functionality to comp_buffers.
This commit adds 2 helpers for IPC4 format set

sink_src: add ipc4 update format functions

---

tools/topology/topology2/avs-tplg/tplg-targets.cmake
tools/topology/topology2/cavs-sdw-src-gain-mixin.conf
tools/topology/topology2/include/pipelines/cavs/mixout-gain-alh-dai-copier-playback.conf
tools/topology/topology2/platform/intel/sdw-amp-generic.conf
tools/topology/topology2/platform/intel/sdw-dmic-generic.conf
tools/topology/topology2/platform/intel/sdw-jack-generic.conf
tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake

topology2: add cs42l43 + cs35l56 topology for MTL and TGL

topology2: add cs42l43 + cs35l56 topology for MTL and TGL

---

west.yml

Update Zephyr to bring in following Zephyr commit:
155f866ecc2c dts: intel_adsp: ace remove dw watchdog
Link: https://github.com/thesofproject/sof/issues/8418

west.yml: update Zephyr to 063ce9caf54f

---

scripts/xtensa-build-zephyr.py

As of today's Zephyr commit 92fb8b223825, imx8ulp does not compile.
Do not remove any of its data from `xtensa-build-zephyr.py` but exclude it from --all
Fixes:
```
scripts/xtensa-build-zephyr.py --all
-- Board: nxp_adsp_imx8ulp
No board named 'nxp_adsp_imx8ulp' found.
CMake Error at zephyr/cmake/modules/boards.cmake:167 (message):
Invalid BOARD; see above.
Call Stack (most recent call first):
cmake/modules/zephyr_default.cmake:129 (include)
share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
CMakeLists.txt:5 (find_package)
```
Fixes 61ccb4c8da75 ("scripts: zephyr: Add support to build sof for imx8ulp")

xtensa-build-zephyr.py: remove imx8ulp from --all

---

src/audio/volume/volume_ipc4.c

The current values result in incorrect signal
amplitudes at the peakvol module output.

peakvol: set the correct vol_min and vol_max values

---

src/idc/zephyr_idc.c

If for any reason a secondary core is down, IDC message has no chance to be processed. This may lead to process hang in case of blocking calls and to undefined actions in case of non blocking.
This commit adds a check and error log message in case of target core is down.

idc: check if secondary core is down before sending IDC

---

src/audio/module_adapter/module_adapter.c

in case module prepare fails, dp_queue lists were left uninitialized.
It may lead to crash if module reset was performed later

DP: bugix - lists initialization was done too late

---

src/schedule/zephyr_ll.c

Clarify the inline comment in zephyr_ll_task_insert_unlocked() explaining the task priority semantics. The old text is not clear on what is "high priority". Make it explicit that 0 is the highest priority and that the tasks are executed in order of task priority.

schedule: zephyr_ll: update zephyr_ll_task_insert_unlocked comments

---

src/audio/copier/copier.c
src/audio/copier/copier_generic.c
src/audio/dai-zephyr.c
src/audio/dp_queue.c
src/audio/google/google_rtc_audio_processing.c
src/audio/kpb.c
src/audio/mixin_mixout/mixin_mixout.c
src/audio/module_adapter/module_adapter.c
src/audio/mux/mux.c
src/audio/pipeline/pipeline-graph.c
src/audio/rtnr/rtnr.c
src/audio/sink_api_helper.c
src/audio/source_api_helper.c
src/include/sof/audio/audio_stream.h
src/include/sof/audio/buffer.h
src/include/sof/audio/dp_queue.h
src/include/sof/audio/sink_api.h
src/include/sof/audio/source_api.h
src/ipc/ipc-helper.c
src/ipc/ipc4/helper.c
src/probe/probe.c
src/samples/audio/smart_amp_test_ipc4.c

sink/src API should grow to fulfill all requirements
this PR adds stream ID to sink/src api

Add get buffer ID to sink/src api

---

src/drivers/intel/ssp/ssp.c
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof-tgl-max98373-rt5682.m4

Dynamic pipeline breaks mclk always-on feature by freeing dai component in HW_FREE stage; the ssp_remove() will be called and disables mclk unconditionally. Check mclk always-on quirk in ssp_remove() to avoid releasing mclk when external codec (i.e. ALC5682)  still needs it.
Linux log:
[  102.479240] sound pcmC0D1p: snd_pcm_common_ioctl: HW_FREE
[  102.479257]  Headset: ASoC: hw_free FE Headset
[  102.479351] sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: free stream 1 dir 0
[  102.479383] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000: GLB_TPLG_MSG: COMP_FREE
[  102.479746] sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM1P freed
[  102.479764] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30210000: GLB_TPLG_MSG: BUFFER_FREE
[  102.480007] sof-audio-pci-intel-tgl 0000:00:1f.3: …

intel: ssp: check mclk always-on quirk in ssp_remove

---

src/audio/pipeline/pipeline-stream.c

One major difference in IPC4 versus IPC3 is that each pipeline will get a separate SET_PIPELINE_STATE command. This is in stark contrast to IPC3 where host sends STREAM_TRIG_START and firmware is expected to propagate the state change to all connected pipelines in the graph.
Change the code such that when pipeline component trigger is executed in IPC4 build, propagation is stopped whenever we reach another pipeline.
This prevents bugs stemming from IPC3 related logic to propagate pipeline triggers, interfering with IPC4 usages like in bug 8481.
Link: https://github.com/thesofproject/sof/issues/8481

audio: pipeline: do not propagate pipeline triggers for IPC4

---

src/ipc/ipc4/handler.c

Fix a side-effect of commit 068f14381026 ("ipc4: handler: Use separate loops for pipeline state phases") where the order of pipeline triggers was changed when the trigger handling was delayed to the pipeline thread. If host asked for pipelines to be triggered in order 0, 1, 2, the actual trigger order might end up as 2, 1, 0 based on how the pipes were connected.
Fix the issue by adding a blocking wait to the IPC thread between each delayed trigger.
Link: https://github.com/thesofproject/sof/issues/8481

ipc4: handler: maintain IPC set_pipeline_state order

---

west.yml

Update Zephyr to bring in following Zephyr commit: efc32081893d soc: intel_adsp: cavs: mask idc interrupt before halting cpu
Link: https://github.com/thesofproject/sof/issues/8492
Fix github CI failure on cavs platforms.

west.yml: update Zephyr to efc32081893d

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-adl-sdw-cs42l42.m4

Add a new topology sof-adl-sdw-cs42l42 for CS42L42 which supports SDW1 for headset on ADL board.

topology1: adl-sdw-cs42l42: support CS42L42-SDW codec

---

src/audio/base_fw.c
src/include/ipc4/base_fw.h

If CONFIG_ADSP_IMR_CONTEXT_SAVE is enabled, base fw will report fw_context_save is supported to host
kernel pr: https://github.com/thesofproject/linux/pull/4680

basefw: add support for fw config query for context save

---

src/drivers/intel/ssp/ssp.c
tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
tools/topology/topology1/sof-tgl-max98373-rt5682.m4

Backport PR https://github.com/thesofproject/sof/pull/8505 cavs2.5-001-drop-stable branch.

[cavs2.5-001] intel: ssp: check mclk always-on quirk in ssp_remove: backport to cavs2.5-001

---

src/audio/module_adapter/module/waves/waves.c

Store/apply config blob in a cache to avoid that
cfg.data will be released after prepare.

waves: store config blob in a cache in waves.c

---

src/audio/drc/drc_hifi4.c
src/include/sof/common.h

Commit 16d126a36fd821 ("audio: Header files cleanup") removed rtos/panic.h include but this is still needed.
Otherwise, we get the following compilation error:
/work/repos/sof/src/lib/lib.c: In function ‘memset’:
/work/repos/sof/src/lib/lib.c:31: warning: implicit declaration of function ‘sof_panic’
Fixes: 16d126a36fd821 ("audio: Header files cleanup")

Fix compilation errors / warnings

---

src/audio/google/google_rtc_audio_processing.c

This is fixup for a62b7cf1c3f73e3209222d5362a66389e7ae68bf

audio: google_rtc_audio_processing: fixup error caused by removed struct member

---

scripts/cmake/misc.cmake
src/math/CMakeLists.txt
src/math/auditory/CMakeLists.txt
src/math/fft/CMakeLists.txt
src/module/audio/CMakeLists.txt
zephyr/CMakeLists.txt

CMake deduplication #8260 
No migration yet, just splitting the change in two to minimize review strain.

Preparation for zephyr/cmake/math transfer

---

src/include/kernel/tokens.h
tools/topology/topology1/m4/buffer.m4
tools/tplg_parser/buffer.c

Flags have been a part of IPC3 for ages, add support for them in the topology.

topology: Add support for buffer flags

---

src/audio/data_blob.c
src/audio/eq_fir/eq_fir.c
src/audio/eq_iir/eq_iir.c
src/audio/kpb.c
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module_adapter.c
src/audio/mux/mux.c
src/audio/selector/selector.c
src/audio/src/src.c
src/audio/src/src_ipc3.c
src/audio/tdfb/tdfb.c
src/audio/volume/volume_ipc3.c
src/include/sof/ipc/common.h
src/ipc/ipc3/handler.c
src/ipc/ipc3/host-page-table.c
src/platform/imx93_a55/include/platform/lib/memory.h
src/samples/audio/smart_amp_test_ipc3.c

Currently, building SOF on a 64-bit system (i.e: i.MX93) leads to compilation warnings such as:
"format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int'" or
"cast to pointer from integer of different size"
This is because pointers are 64-bit and size_t resolves to a 64-bit type. As such, casting a pointer to uint32_t when printing leads to int-to-pointer-cast warnings. Also, printing a size_t variable using the "%d" or "%u" formats leads to format warnings.
To fix this, cast all size_t variables to uint32_t when printing. Pointers shall also be casted to uintptr_t before casting to uint32_t. This is fine to do because i.MX93 uses 32-bit addresses anyways.
This in conjunction with https://github.com/thesofproject/sof/pull/8528 fixes all compilation warnings …

Fix i.MX93 compilation warnings related to mis-formatting / casting 64-bit types

---

.github/workflows/zephyr.yml

Now that all 64bits warnings have just been fixed, let's keep that build clean.

[SKIP SOF-TEST] .github/zephyr: add -Werror to LP64 compilation

---

src/include/sof/coherent.h

Supersedes the "best effort" use of `packed`, being removed by #8528

coherent.h: assert(sizeof(struct coherent)  <= DCACHE_LINE_SIZE)

---

scripts/set_xtensa_params.sh
scripts/xtensa-build-all.sh
scripts/xtensa-build-zephyr.py

2 commits.
Main one: set_xtensa_params.sh: add missing LNL, ACP_6_3 and vangogh
This adds support for:
```
./scripts/rebuild-testbench.sh -p lnl
```
But the real motivation is to re-use `set_xtensa_params.sh` before `west build` and `twister`. More commits about that after this PR.

set_xtensa_params.sh: add missing LNL, ACP_6_3 and vangogh, remove duplication with xtensa-build-all.sh

---

src/audio/up_down_mixer/up_down_mixer.c
src/audio/up_down_mixer/up_down_mixer.h
src/audio/up_down_mixer/up_down_mixer_coef.h
src/audio/up_down_mixer/up_down_mixer_hifi3.c
src/audio/up_down_mixer/up_down_mixer_ipc4.h

This is a clean up, purpose is de-cluster headers, toml files,
Readme.md etc per module basis, since today everything is scattered
in current code base.

Audio: up_down_mixer: move up_down_mixer header files to module folder

---

tools/ctl/ctl.c

The option -s is also needed for binary input file.

sof-ctl: minor update for help text

---

src/module/audio/source_api.c

This patch prevents division by zero, when
source_get_frame_bytes() routine returns 0.
This change fixes issue https://github.com/thesofproject/sof/issues/8414. The problem happens due to race condition during pipeline pause operation. The exact failure mechanism require additional debug, but checking frame_bytes value before division prevents exceptions.

module: sink: source: Prevent division by zero issue

---

west.yml

Update Zephyr to pull in imx8ulp support. This includes following zephyr commits:
- cfb68f827202 ("boards: xtensa: adsp: add support for imx8ulp board")
- a9a0c28282c3 ("dts/xtensa/nxp: Add dtsi for imx8ulp")
- 4b33c65f7108 ("soc: xtensa: adsp: add support for NXP ADSP for i.MX8ULP")
- ceae1d83ca4b ("west: sign: add support for NXP i.MX8ULP board")

west.yml: update Zephyr to efc32081893

---

src/module/audio/source_api.c

This patch prevents division by zero, when
source_get_frame_bytes() routine returns 0.
This change fixes issue https://github.com/thesofproject/sof/issues/8414. The problem happens due to race condition during pipeline pause operation. The exact failure mechanism require additional debug, but checking frame_bytes value before division prevents exceptions.
(cherry picked from commit d467eee4ca227b234ca4966933474d0c9a7574c3)

[SOF-2.8] module: sink: source: Prevent division by zero issue

---

tools/topology/topology2/include/components/google-rtc-aec.conf

Add binary controls for AEC tuning data with
max size set to 2048.

topology2: google-rtc-aec: Add Byte control

---

scripts/xtensa-build-zephyr.py

This was broken from the start when converting the script from shell script to Python.
A good reference was left in the non-Zephyr script which is still active: `./scripts/xtensa-build-all.sh -h`
Fixes initial commit 1de3ef367584 ("Rewritten xtensa-build-zephyr.sh to python")

xtensa-build-zephyr.py: untabify XCC installation in --help message

---

tools/topology/topology2/include/pipelines/cavs/dai-copier-eqiir-module-copier-capture.conf

Remove the attributes that do not belong to Pipeline class. There are no changes to compiled binary.

topology2: Remove pcm cap attributes

---

tools/rimage/src/include/rimage/misc_utils.h
tools/rimage/src/manifest.c
tools/rimage/src/module.c
tools/rimage/src/plat_auth.c
tools/rimage/src/rimage.c

Added limit of a number of input modules provided in a command line to the maximum number of supported modules (size of module array / MAX_MODULES)
Created ALIGN_UP macro to simplify calculations.
Used DIV_ROUND_UP macro to calculate page count.

rimage: Set of small improvements

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-hda-generic.m4

Enabling dts pipeline on HDA0 speaker/headphone playaback.
In this case, using defined macro W_PIPELINE_TOP() to add missing dai pipeline is due to topology not found it for PCM0P.
Verified dts test blobs via sof-ctl.

[cavs2.5-001] topology1: sof-hda-generic: enable dts playback

---

src/audio/module_adapter/module/generic.c

The build of testbench for MTL platform simulation causes this build fail (rebuilt-testbench -p mtl):
src/audio/module_adapter/module/generic.c:213:6:
error: variable 'ret' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
if (md->ops->prepare) {
^~~~~~~~~~~~~~~~
src/audio/module_adapter/module/generic.c:236:9:
note: uninitialized use occurs here
return ret;
^~~
Since it's a possibility to have a module without prepare() operation, the initialize to zero is added to avoid the return of undefined value.
Reported-by: Marc Herbert <marc.herbert@intel.com>

Audio: Module adapter: Fix return value when no prepare operation

---

west.yml

Update Zephyr to bring in total of 290 commits, including the following related to SOF targets:
0ebeca2eb7d0 intel_adsp: ace: add firmware loading tool
0e73c225bb54 drivers: ssp: Reverted CPA check condition

west.yml: update Zephyr to ffd716b4a214

---

src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc4.c

We need to build params based on module base config first then we can verify it since the income params is built for the source of the this module . In comp_verify_params the params is applied to buffer so the sequence is vital. And also remove redundant stream_param set.

module_adapter: build params first then verify it

---

.github/workflows/zephyr.yml
zephyr/docker-run.sh

This updates docker container version and zephyr workflows to support new Zephyr SDK (0.16.4).

Use Zephyr SDK 0.16.4

---

scripts/xtensa-build-zephyr.py

This re-adds imx8ulp to --all platform list. This was removed in commit 7737efadf4fc ("xtensa-build-zephyr.py: remove imx8ulp from --all")

xtensa-build-zephyr.py: Re-add imx8ulp to -all

---

src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc3.c
src/audio/module_adapter/module_adapter_ipc4.c
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/audio/module_adapter/module/modules.h

Module will update source & sink information when bind & unbind event happen.

module: prepare sink & source in bind & unbind function

---

app/debug_overlay.conf

- This test has failed on MTL since it was enabled.  Running tests that
we systematically ignore the failure of is much worse than not running
them because it provides a false impression of quality.
- This can cause DSP panics as seen in
https://github.com/thesofproject/sof/pull/8621

debug_overlay.conf: temporarily disable SOF_BOOT_TEST

---

src/audio/pipeline/pipeline-graph.c
src/audio/pipeline/pipeline-params.c
src/include/sof/audio/component_ext.h

[Split out from https://github.com/thesofproject/sof/pull/8571 for separate review]
Clean up some cut/paste code that had spread around, replacing it with a simpler "comp_same_dir()" predicate.  No behavioral changes, just refactoring.
Also remove the big comment that was repeated in triplicate.  It explained this as error handling (i.e. it must be broken topology from which we want to recover), but in fact cross-pipeline widget connections in modern SOF do run in opposite directions (c.f. echo cancellation, which need to look at the output stream to process microphone input, or smart amp devices that do the reverse).
So just explain it as policy: we don't propagate across opposite-direction pipelines, period.  Usages that need them need to manage their pipeline lifecycles manually.

component: pipeline: Refactor direction testing in pipeline propagation

---

src/audio/asrc/asrc.h
src/audio/asrc/asrc_ipc3.c

Fix the IPC3 incompatibal pointer type of timestamp struct.

Audio: ASRC: Fix the IPC3 incompatibal pointer type

---

src/audio/mux/mux.c

[Split out from #8571 for separate review]
It may happen that a demux is configured to write to a buffer in a stopped pipeline (consider echo cancellation when the mic is not in use: the output reference stream has nowhere to go).  This doesn't work in the tree currently; the general pipeline design is to try to turn on pipes that are required, but that's incomplete for the case (again, echo cancellation) where the pipelines are oriented in different directions and in any case is undesirable as a microphone stream shouldn't be required to be active for playback to work.
Instead, detect the situation at PRE_START time, configure the output buffers overrun_permitted (as there may not be a reader), and drop the unconfigured streams dynamically at process() time, as the target pipeline may be …

demux: Support inactive cross-pipeline sinks

---

.github/workflows/build_all.yml
.github/workflows/codestyle.yml
.github/workflows/daily-tests.yml
.github/workflows/installer.yml
.github/workflows/ipc_fuzzer.yml
.github/workflows/repro-build.yml
.github/workflows/rimage.yml
.github/workflows/testbench.yml
.github/workflows/tools.yml
.github/workflows/unit-tests.yml

~Also fuzz for longer in daily tests: 30 minutes instead of 5 minutes~
3 commits.
It's sometimes hard to find whether a check failure is due to the PR in which it fails. 
It also happens that two passing PRs are merged around the same time and conflict with each other[*] (recent example: #8560).
Running all checks daily on a "pure" main branch without any PR helps with these problems.
[*] "Merge trains / merge queues" solve this problem but they would a lot of work and overkill considering how rarely this happens.

[SKIP SOF-TEST] Run all workflows in daily tests

---

.github/workflows/zephyr.yml

Now that imx8ulp support is ready with Zephyr add it as compilation target for CI.

.github/zephyr: Add imx8ulp target to CI

---

src/audio/base_fw.c
west.yml

Add new parameter for SW to force DMI L1 exit on IPC request.
Associated with: https://github.com/zephyrproject-rtos/zephyr/pull/66042
Separating two new functions force and allow l1 to have the current state with separated functions in the power manager so that SOF can call these functions via IPC DMI_FORCE_L1_EXIT. DMA sometimes slows down and does not perform, therefore the workaround is to switch off l1. Change related to the addition of a new parameter to force DMI L1 exit on IPC request.

base_fw: add DMI_FORCE_L1_EXIT FW config (depends on Zephyr 66042)

---

.github/workflows/build_all.yml
scripts/fuzz.sh

3 commits.
Main ones:
- add -Werror to catch warnings like 3f572b8cb67ede1e47719d49fa29d451ae0f3887 / #8631 
- add a proper -h text

[SKIP SOF-TEST] fuzz.sh: add -Werror in GitHub workflow

---

scripts/rebuild-testbench.sh
tools/testbench/CMakeLists.txt

Minor cleanups spotted when looking at past issue 240cc9786ae245c
5 commits, please review separately.
The only really visible addition is this:
```
[100%] Linking C executable testbench
[100%] Built target testbench
Success!
For temporary, interactive Kconfiguration use:
make -C /home/me/SOF/sof/tools/testbench/build_xt_testbench/sof_ep/build/  menuconfig
Permanent configuration is "src/arch/host/configs/library_defconfig".
For instant, incremental build:
source  /home/me/SOF/sof/tools/testbench/build_xt_testbench/xtrun_env.sh
make -C /home/me/SOF/sof/tools/testbench/build_xt_testbench/ -j8
....
```

[SKIP SOF-TEST] rebuild-testbench.sh: cosmetic improvements

---

scripts/xtensa-build-zephyr.py

The IPC4_CONFIG_OVERLAY is no longer used, remove it.

xtensa-build-zephyr.py: Remove IPC4_CONFIG_OVERLAY from PlatformConfig

---

app/debug_overlay.conf
src/audio/Kconfig
src/audio/dai-zephyr.c

Triggered by
https://github.com/thesofproject/sof/issues/4672
and
https://github.com/thesofproject/sof/pull/8621
... let's put the warnings behind a build option.

audio: dai-zephyr: put no-data checks behind a build option

---

src/audio/module_adapter/iadk/iadk_module_adapter.cpp
src/audio/module_adapter/module/modules.c
src/include/sof/audio/module_adapter/iadk/iadk_module_adapter.h

The IADK libraries should support source/sink interface. 
This patch changes IADK adapter part to implement source/sink interface.

iadk: module_adapter: Switch IADK modules to use source/sink

---

src/audio/module_adapter/module_adapter.c
src/include/module/module/base.h
src/schedule/zephyr_dp_schedule.c

lets assume DP with 10ms period (a.k.a a deadline). It starts and finishes earlier, i.e. in 2ms providing 10ms of data LL starts consuming data in 1ms chunks and will drain 10ms buffer in 10ms, expecting a new portion of data on 11th ms
BUT - the DP module deadline is still 10ms,
regardless if it had finished earlier and it is completely fine that processing in next cycle takes full 10ms - as long as it fits into the deadline.
It may lead to underruns:
LL1 (1ms) ---> DP (10ms) -->LL2 (1ms)
ticks 0..9 -> LL1 is producing 1ms data portions,
DP is waiting, LL2 is waiting
tick 10 - DP has enough data to run, it starts processing tick 12 - DP finishes earlier, LL2 starts consuming,
LL1 is producing data
ticks 13-19 LL1 is producing data,
LL2 is consuming data (both in 1ms chunks)
tick 20  - DP …

DP: provide data to next LL module no earlier than DP deadline

---

west.yml

Update Zephyr to bring in total of 169 commits, including the following related to SOF targets:
dab6f665ca77 xtensa: fix build errors with cache functions
039e5ef1b813 intel_adsp: remove rimage sign() from `west flash`
c7e3ccd51ad4 drivers: dma: intel_adsp_gpdma: fix issue with stop and PM refcounts
Link: https://github.com/thesofproject/sof/issues/8503

west.yml: upgrade Zephyr to a1042c40796

---

src/audio/module_adapter/module_adapter.c

DP may produce a huge chunk of output data (i.e. 10 LL cycles), and the following module should be able to consume it in 1 cycle chunks, one by one
unfortunately LL modules are designed to drain input buffer
That leads to issues when DP provide huge data portion
FIX: copy only the following module's IBS in each LL cycle

DP: LL module should get 1ms data chunk in each cycle

---

src/audio/mixin_mixout/mixin_mixout.c
src/audio/mixin_mixout/mixin_mixout.h
src/audio/mixin_mixout/mixin_mixout_generic.c
src/audio/mixin_mixout/mixin_mixout_hifi3.c

These are cleanup commits extracted from PR https://github.com/thesofproject/sof/pull/8537. That PR failed the CI (or maybe random fail?), more time to verify needed. Also these changed are not very related to sink/source API support in mixin/mixout, so having 2 smaller PR is better then 1 big.

ipc4: mixin/mixout cleanup after channel remapping mode been removed

---

src/audio/module_adapter/module_adapter.c

After https://github.com/thesofproject/sof/pull/8594 been merged, sources and sinks are now setup on .bind() and .unbind(). Previously they were setup in .prepare(). However, there were code left in module_adapter_reset() which clears sources and sinks arrays. That broke some tests: modules which use source/sink API stopped working correctly after pipeline reset.

ipc4: Regression FIX: Do not clear sources/sinks on reset

---

tools/topology/topology2/cavs-nocodec-bt.conf

The pipelines for PCM0 and PCM1 only support S32_LE audio format. Fix the PCM capability descriptions to match the actual pipeline definitions. This allows to run test suites that enumerate all support PCMs and their formats.

topology2: cavs-nocodec-bt: fix PCM0 and PCM1 capabilities

---

src/audio/module_adapter/iadk/iadk_module_adapter.cpp
src/include/sof/audio/module_adapter/iadk/iadk_module_adapter.h

Add check of return code for sink/source API functions.
The IADK processing module interface uses uint32_t return code
while cSOF is using int type. Checks return value
from processing() method and returns -ENODATA in case of
failure.

iadk: module_adapter: Check return code for sink/source api

---

src/include/sof/common.h

Commit 16d126a36fd821 ("audio: Header files cleanup") removed rtos/panic.h include but this is still needed.
Otherwise, we get the following compilation error:
/work/repos/sof/src/lib/lib.c: In function ‘memset’:
/work/repos/sof/src/lib/lib.c:31: warning: implicit declaration of function ‘sof_panic’
Fixes: 16d126a36fd821 ("audio: Header files cleanup")
(cherry picked from commit a4a3b3aed9c9a78087a0c796827ec608d0cd621c)

include: sof: common.h Fix compilation error

---

src/drivers/imx/edma.c
src/schedule/dma_multi_chan_domain.c
src/schedule/zephyr_dma_domain.c
xtos/include/sof/lib/dma.h

Did basic tests(playback&record in parallel, with suspend) in i.MX8QM/i.MX8ULP platform. The fix changed edma driver behavior, so need check not only zephyr but also xtensa build.
@dbaluta Please tell me if you think the fix still impact some tests, I will do the tests you mentioned. Thanks a lot!

Work round Fix for noise issue when playback and capturer in parallel.

---

scripts/xtensa-build-zephyr.py

ARL-S is using the same debugkey/community key binary as MTL.

xtensa-build-zephyr.py: Add arl-s alias to mtl platform

---

src/audio/mixin_mixout/mixin_mixout.c
src/audio/mixin_mixout/mixin_mixout.h
src/audio/mixin_mixout/mixin_mixout_generic.c
src/audio/mixin_mixout/mixin_mixout_hifi3.c
src/include/sof/audio/audio_stream.h

Modifications to mixin/mixout implementation to switch to use sink/source API.

ipc4: mixin/mixout: Switch to use sink/source API

---

test/cmocka/src/common_mocks.c

Direct numbers are hard to know what exactly means, it actually represent log error level print, use macro to replace it.

Testbench: use macro replace immediate number

---

tools/topology/topology2/cavs-benchmark-hda.conf
tools/topology/topology2/development/tplg-targets-bench.cmake
tools/topology/topology2/include/bench/host_io_gateway_pipelines_src.conf
tools/topology/topology2/include/bench/src_hda_route.conf
tools/topology/topology2/include/bench/src_s32.conf

This patch adds build of hda-generic development topologies to test SRC component with s32 format.

Topology: Topology2: Add sof-hda-benchmark-src32-<platform>

---

.github/workflows/sparse-zephyr.yml

This should work now that Guennadi's endianness fix 98b20341967 has been
merged.
EDIT: it does work https://github.com/thesofproject/sof/actions/runs/7350497231

[SKIP SOF-TEST] .github/sparse: switch sparse version back to the upstream main branch

---

zephyr/CMakeLists.txt
zephyr/lib/alloc.c

Split out from #8571 as it should be relatively uncontroversial.
See commit messages, basically this just forward ports some pre-existing trickery to make Google AEC (which is a C++ library) build with existing toolchains.  As the commit message indicates, really this is something the Zephyr toolchain layer should be prepared to provide, but it doesn't (yet).

C++ & AEC support for Zephyr builds

---

src/audio/drc/Kconfig
src/audio/drc/drc_generic.c
src/audio/drc/drc_hifi3.c
src/audio/drc/drc_hifi4.c
src/audio/drc/drc_math_generic.c
src/include/sof/math/exp_fcn.h
src/math/exp_fcn.c
src/math/exp_fcn_hifi.c
zephyr/CMakeLists.txt

For DRC performance, replace `exp_small_fixed()` with `sofm_exp_int32()`.
Included supporting change to include `sofm_exp_int32()` within `exp_fixed()`
and repositioned `exp_small_fixed()` for future use.

DRC: math: Replace exponential function for performance

---

src/audio/aria/aria.c
src/audio/asrc/asrc.c
src/audio/audio_stream.c
src/audio/crossover/crossover.c
src/audio/dcblock/dcblock.c
src/audio/drc/drc.c
src/audio/eq_fir/eq_fir.c
src/audio/eq_iir/eq_iir.c
src/audio/google/google_rtc_audio_processing.c
src/audio/kpb.c
src/audio/mfcc/mfcc.c
src/audio/mixer/mixer.c
src/audio/multiband_drc/multiband_drc.c
src/audio/mux/mux.c
src/audio/mux/mux_ipc4.c
src/audio/selector/selector.c
src/audio/tdfb/tdfb.c
src/audio/volume/volume.c
src/include/sof/audio/audio_stream.h

PR was reworked from the version described in the initial version.  See comments below and commit message.  This text is stale:
Audio stream objects are generally allocated out of zero'd heap memory, but the computed alignment fields need non-zero values to have correct behavior.  These were being left as garbage.
Set them to a byte and frame alignmnt of 1, as this corresponds to pervasive convention in the tree.  But note that a byte alignment of 1 is actually technically incorrect, as all existing DSP targets are on architectures which don't allow misaligned loads.  But existing component code is universally coded correctly anyway.
(It's worth pointing out that "set_alignment_constants()" is now exposed as an API call on abstracted source/sink objects.  But the only current …

audio_stream: Fix uninitialized data in alignment_constants

---

tools/topology/topology2/cavs-benchmark-hda.conf
tools/topology/topology2/development/tplg-targets-bench.cmake
tools/topology/topology2/include/bench/src_lite_hda_route.conf
tools/topology/topology2/include/bench/src_lite_s16.conf
tools/topology/topology2/include/bench/src_lite_s24.conf
tools/topology/topology2/include/bench/src_lite_s32.conf
tools/topology/topology2/include/components/src_lite.conf

This PR adds build of hda-generic development topologies to test SRC LITE component with s32/24/16 format.

Topology: Topology2: Add sof-hda-benchmark-src_lite32/24/16-<platform>

---

src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc4.c
src/include/module/module/base.h
src/ipc/ipc4/helper.c

This is a different take on a fix for #8639 than the workaround in #8575 on which it was originally coded.  It removes the requirement for components to have to muck with module internals[1] and places the complicated byte-offset math into just one place (in the module code that owns the struct format).  Really I think this is a lot cleaner.  If you guys want to merge the first version for clarity (given it's already "shipped"[2]), I can submit this as cleanup on top of that instead (which, again, is how this was written originally anyway).
With this, the big IPC4 workaround patch at the end of the AEC work is down to just one line, hope to have that cleaned up by tomorrow.  (see https://github.com/andyross/sof/commits/mtl-aec-tmp/ for the current status of my working tree).
[1] …

Better handling of module base_config_ext data

---

src/include/sof/audio/module_adapter/module/generic.h

The default "is ready to process" implementation used to look at a first sink and first source only.
This change makes it to look at all sinks and sources.
dependency:
OR

dp: look at all sinks and sources in default "is ready"

---

src/audio/aria/aria.c
src/audio/aria/aria_generic.c
src/audio/aria/aria_hifi3.c

After the following change:
"copier: add support for windows driver (383d17a19e25f804d2ba37b6b621131918544e6a)"
aria stopped working properly. It is necessary to adapt the module
S24_LE format processing.

aria: change to S24_LE format processing

---

tools/topology/topology2/sof-ace-tplg/tplg-targets.cmake

This patch adds the topology for LNL RVP with rt722 multiple function codec.

Topology2: Add sof-lnl-rt722-l0

---

src/lib/dai.c

The error log is convenient for developer to check failed case in stress test.
We have a bug : https://github.com/thesofproject/sof/issues/8056. The failed log provided limited information.
````
[  766.013925] <err> dai_comp: dai_common_new: comp:1 0x10004 dai_new(): dai_get() failed to create DAI.
[  766.013945] <err> copier: copier_dai_create: comp:1 0x10004 failed to create dai
[  766.013978] <err> copier: copier_init: comp:1 0x10004 unable to create dai
````
It is hard to be reproduced in private environment, so add error log for CI to catch it

dai: add error log for failed path

---

tools/rimage/src/adsp_config.c
tools/rimage/src/include/rimage/sof/user/manifest.h
tools/rimage/src/manifest.c

The image header contains a bitfield with flags specifying a image type. This commit sets correct image type depending on whether firmware or a loadable module is being signed.

rimage: loadable_modules: Set correct image type

---

scripts/xtensa-build-zephyr.py

Not sure why I thought it would be complicated; I should have done this much sooner.
Before:
```
build-sof-staging
|-- sof
|   +-- intel
|       +-- sof-ipc4
|           |-- adl
|           |   +-- community
|           |       +-- sof-adl.ri
|           |-- adl-n
|           |   +-- community
|           |       +-- sof-adl-n.ri
|           |-- arl
|           |   +-- community
|           |       +-- sof-arl.ri
```
After:
```
build-sof-staging
|-- sof
|   +-- intel
|       +-- sof-ipc4
|           |-- adl
|           |   +-- community
|           |       +-- sof-adl.ri  -> ../../tgl/community/sof-tgl.ri
|           |-- adl-n
|           |   +-- community
|           |       +-- sof-adl-n.ri  -> ../../tgl/community/sof-tgl.ri
|           |-- arl
|           |   +-- community
| …
```

xtensa-build-zephyr.py: show symbolic links at the end

---

src/audio/dai-zephyr.c

Guard sink_list in order to avoid the following variable unused warning:
$ sof/src/audio/dai-zephyr.c: In function 'dai_dma_cb': $ sof_dir/sof/src/audio/dai-zephyr.c:259:35: warning: unused variable 'sink_list' [-Wunused-variable]
259 |                 struct list_item *sink_list;
|                                   ^~~~~~~~~

audio: dai-zephyr: Fix unused variable warning

---

scripts/xtensa-build-zephyr.py

xtensa-build-zephyr.py: fail on --deployable-build + older options
From experience, no one scrolls up and looks at warnings that are not in the current screen.
There's no reason to use both the old options and the brand new one at the same time, it would be a huge mistake.

xtensa-build-zephyr.py: fail on --deployable-build + older options

---

src/audio/module_adapter/module/waves.c

Store/apply config blob in a cache to avoid that
cfg.data will be released after prepare.

[mt8186-v02] waves: store config blob in a cache in waves.c

---

src/include/sof/common.h

common.h defines the IS_ALIGNED macro, which conflicts with a Zephyr macro of the same name. Add guards to define it only if it is not already defined by Zephyr.

common.h: Guard definition of IS_ALIGNED for Zephyr builds

---

tools/sof_ri_info/sof_ri_info.py

Fix the typo for 8MB imr size.

sof_ri_info: fix imr size for cnl

---

tools/sof_ri_info/sof_ri_info.py

Fix the typo for 8MB imr size.
(cherry picked from commit 40f6de58da5ceb6d88510a615de23d3e113e7e37)

[stable-v2.2] sof_ri_info: fix imr size for cnl

---

scripts/xtensa-build-zephyr.py

Everyone should use deployable builds by default.  Don't switch the
default behavior yet but add a --no-deployable-build option in case
anyone is stuck.

Add new --no-deployable-build option

---

src/audio/aria/CMakeLists.txt
src/audio/aria/aria.h
src/audio/aria/aria_hifi5.c
zephyr/CMakeLists.txt

Add HiFi5 implementation of aria algorithm functions, compared with HiFi3 version, can reduce about 10% cycles.

Audio: ARIA: Add HiFi5 implementation

---

src/audio/module_adapter/module/modules.c

In SOF we have a two type loadable modules, IADK and native whose are sharing the same registering mechanism but for C++/C needs IADK is using adapter which translates methods for SOF needs.
Native loadable module is not using any additional adapters and returns pointer for API used in built-in modules and loadable.

loading module: fix native module interface register

---

src/include/sof/lib_manager.h
src/library_manager/Kconfig
src/library_manager/lib_manager.c

The previous code have several issues:
- Did not support empty `data` segment.
- It assumed that certain types of segments would be at fixed indexes, without taking into account their flags/types.
- Incorrect handling of mapping error. If the virtual address cannot be mapped because is already in use, the error handler will unmap this address.
- If there is an error loading one of the modules marked as `lib_code`, previously loaded modules are not unloaded.
This commit fixes the above issues, but it probably introduces new problems :)

library_manager: Update module load flow

---

tools/topology/topology2/production/CMakeLists.txt

The target name for the production should have been more precise as it ended up:
```
ninja -C tools/build_tools/ help
topology2_dev: phony
...
topology2_dev_sof-tgl-nocodec: phony
topology2_dev_sof-tgl-nocodec-crossover-2way: phony ...
topology2_prod: phony
...
topology2_sof-hda-generic: phony
topology2_sof-hda-generic-2ch: phony
...
```
Change it to be consistent:
```
topology2_dev: phony
...
topology2_dev_sof-tgl-nocodec: phony
topology2_dev_sof-tgl-nocodec-crossover-2way: phony ...
topology2_prod: phony
...
topology2_prod_sof-hda-generic: phony
topology2_prod_sof-hda-generic-2ch: phony
...
```
No functional change.
Suggested-by: Marc Herbert <marc.herbert@intel.com>

topology2: Tidy up the production target name as topology2_prod

---

tools/topology/topology2/production/tplg-targets-cavs25.cmake

Hi,
NHLT blob is not needed when the DMIC is via SDW.
The sof-adl-rt711-l0-rt1308-l12-rt715-l3 is identical configuration as sof-tgl-rt711-rt1308-rt715.

topology2: production: cav2.5: Remove NHLT from SDW topologies and add sof-adl-rt711-l0-rt1308-l12-rt715-l3

---

tools/logger/convert.c
tools/logger/convert.h

Using Compiler version: aarch64-poky-linux-gcc (GCC) 13.2.0 we get the following error:
```
tools/logger/convert.c: In function 'convert':
tools/logger/convert.c:357:34: error: '%*s' directive output between 4294967264 and 4294967284 bytes exceeds 'INT_MAX' [-Werror=format-overflow=]
|   357 |                 fprintf(out_fd, "%*s(us)%*s  ", -ts_width, " TIMESTAMP", ts_width, "DELTA");
|       |                                  ^~~                       ~~~~~~~~~~~~
| In file included from /opt/builds/OBNand/build/tmp/work/armv8a-poky-linux/sof-tools/2.8.0/recipe-sysroot/usr/include/stdio.h:964,
|                  from /opt/builds/OBNand/build/tmp/work/armv8a-poky-linux/sof-tools/2.8.0/git/tools/logger/convert.h:13,
|                  from …
```

logger: convert: Fix compile time error with newer toolchain

---

src/audio/module_adapter/module_adapter.c

Fix handling of input_pins free. Module reset can be called multiple times, so move the resource release to module_adapter_free().
Fixes: 70460043844f ("module_adapter_ipc4: Save and pre-parse base_cfg_ext data")

module_adapter: fix double-free of base_cfg_ext data

---

tools/logger/convert.c
tools/logger/convert.h

Using Compiler version: aarch64-poky-linux-gcc (GCC) 13.2.0 we get the following error:
```
tools/logger/convert.c: In function 'convert':
tools/logger/convert.c:357:34: error: '%*s' directive output between 4294967264 and 4294967284 bytes exceeds 'INT_MAX' [-Werror=format-overflow=]
|   357 |                 fprintf(out_fd, "%*s(us)%*s  ", -ts_width, " TIMESTAMP", ts_width, "DELTA");
|       |                                  ^~~                       ~~~~~~~~~~~~
| In file included from /opt/builds/OBNand/build/tmp/work/armv8a-poky-linux/sof-tools/2.8.0/recipe-sysroot/usr/include/stdio.h:964,
|                  from /opt/builds/OBNand/build/tmp/work/armv8a-poky-linux/sof-tools/2.8.0/git/tools/logger/convert.h:13,
|                  from …
```

[STABLE-v2.2] logger: convert: Fix `%*s` compile time error with newer toolchain

---

tools/topology/topology2/production/tplg-targets-ace1.cmake

The layout is configured as:
- Link0: CS42L43 Jack and mics
- Link2: 2x CS35L56 Speaker (amps 3 and 4, right)
- Link3: 2x CS35L56 Speaker (amps 1 and 2, left)

topology2: cavs-cs42l43: Add topology for cs42l43/cs35l56 on MTL

---

west.yml

Total of 287 commits with no known impact to SOF to builds.

west.yml: update zephyr to 9852e8e15bc8

---

tools/topology/topology2/platform/intel/sdw-amp-generic.conf

Some ALH DAI copier missed SAMPLE_TYPE_MSB_INTEGER setting.

fixup! topology2: Use SAMPLE_TYPE_MSB_INTEGER for ALH copier

---

src/include/sof/audio/igo_nr/igo_nr_comp.h

This change avoids error, seen with testbench build for MTL platform with "scripts/rebuild-testbench.sh -p mtl":
sof/src/include/sof/audio/igo_nr/igo_nr_comp.h:29:27: error: field 'config' with variable sized type
'struct sof_igo_nr_config' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]

Audio: IGO_NR: Fix build fail variable size data structure

---

src/ipc/ipc4/handler.c

No need to re-calculate cdma_comp in ipc4_process_chain_dma(), keep using the already calculated value.

chain DMA: remove redundant code

---

src/audio/dcblock/Kconfig
src/audio/dcblock/dcblock.h
src/audio/dcblock/dcblock_generic.c
src/audio/dcblock/dcblock_hifi3.c
src/audio/dcblock/dcblock_hifi4.c
src/include/sof/common.h

1. The `if XCHAL_HAVE_HIFI4` macro logic is duplicated across many source files. Starting with dcblock.h, make it generic and move it to common.h
2. Add the ability to override the max available HIFI level using Kconfig

Add new CONFIG_DCBLOCK_HIFI and move generic XCHAL_HAVE logic to common.h

---

app/sample.yaml

nxp_adsp_imx8ulp needs to be in allowed platforms.

app: fix filter in sample.yaml

---

src/audio/copier/copier_dai.c
src/include/ipc4/alh.h
src/include/sof/audio/ipc-config.h
src/include/sof/ipc/topology.h
src/include/sof/tlv.h
src/ipc/ipc4/dai.c
src/ipc/ipc4/helper.c

Since LNL SoundWire interface uses HDA DMA to transfer stream data. 
This approach uses HDA dai and HDA DMA. No changes needed on Zephyr side.
Following solution involves FW based SoundWire link aggregation mechanism which
is also used on MTL for backward compatibility with Windows driver.
This is a working solution. It was tested in E2E scenarios with Windows driver.

lnl: sndw: use HDA DMA to transfer stream data 

---

.github/workflows/build_all.yml
.github/workflows/codestyle.yml
.github/workflows/installer.yml
.github/workflows/ipc_fuzzer.yml
.github/workflows/pull-request.yml
.github/workflows/repro-build.yml
.github/workflows/testbench.yml
.github/workflows/tools.yml
.github/workflows/unit-tests.yml
.github/workflows/zephyr.yml

2 commits to review separately.
Main change, fixes the new, mass warnings:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3. For more information
see:
https://github.blog/changelog/
2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

[SKIP SOF-TEST] .github: upgrade all checkout actions, v3 -> v4 (deprecated Node.js 16). Extend fetch-depth when building firmware

---

tools/topology/topology2/cavs-benchmark-hda.conf
tools/topology/topology2/development/tplg-targets-bench.cmake
tools/topology/topology2/include/bench/asrc_hda_route.conf
tools/topology/topology2/include/bench/asrc_s16.conf
tools/topology/topology2/include/bench/asrc_s24.conf
tools/topology/topology2/include/bench/asrc_s32.conf
tools/topology/topology2/include/components/asrc.conf

This patch adds build of hda-generic development topologies to test ASRC component with s32/24/16 format.

Topology: Topology2: Add sof-hda-benchmark-asrc32/24/16-<platform>

---

.github/workflows/testbench.yml

Parallel builds are fast but they bury errors, for instance good luck finding the cause of this failure:
https://github.com/thesofproject/sof/actions/runs/7667629748/job/20897861756?pr=8019
Use the well known technique of falling back on a single thread when failing.

[SKIP SOF-TEST] .github: fallback on rebuild-testbench -j 1 when failing

---

src/audio/volume/Kconfig
src/audio/volume/Kconfig.simd
src/audio/volume/volume.c
src/audio/volume/volume.h
src/audio/volume/volume_generic.c
src/audio/volume/volume_generic_with_peakvol.c
src/audio/volume/volume_hifi3.c
src/audio/volume/volume_hifi3_with_peakvol.c
src/audio/volume/volume_hifi4.c
src/audio/volume/volume_hifi4_with_peakvol.c

Based on #8787, this patch is adding volume build option for different HIFI levels.

Volume: Add volume SIMD build option

---

src/library_manager/lib_manager.c
zephyr/lib/alloc.c
zephyr/lib/cpu.c

This patch implements recommended hardware flow for Intel ACE platforms.
The L3 heap should be accessed via cached pointers including management data.
This change is fixing D3 save/restore flow on LNL.

zephyr: lib: alloc: Use cached memory for L3 Heap

---

.github/workflows/zephyr.yml
app/prj.conf
scripts/xtensa-build-zephyr.py

... keep disassembling in github actions.
2 commits, see commit messages.

app/prj.conf: stop disassembling by default - 2x faster build

---

src/module/audio/sink_api.c
src/module/audio/source_api.c

System-service modules cannot include Zephyr headers and don't use exported symbols, they link sink_api.c and source_api.c into their images. Disable symbol exporting for them.

lmdk: fix building system-service modules

---

src/ipc/ipc4/helper.c

sink_basecfg_ext should actually be src_basecfg_ext in one location in ipc_comp_connect(), fix it and move variable definitions to where they are used to reduce the chance of such a bug in the future.

ipc4: fix a wrong variable

---

src/audio/volume/volume_ipc4.c
tools/topology/topology2/include/components/gain.conf
tools/topology/topology2/platform/intel/dmic-generic.conf

I'm asked to add a mixer switch for MIC LED mute control so I studied how it is supported on IPC3 then add missing code to IPC4 firmware and topology.
Three missing parts are identified and restored:
1. add volume mute support to IPC4 firmware. (FW)
2. add a switch to gain widget for the mute control. (TPLG)
3. crate this switch with led mute function in dmic topology. (TPLG)
FW and TPLG are tested on MTL chromebook with chrome-v6.6 kernel. DMIC recording could be mute/unmute by mixer switch.
A side effect is the gain widget is default muted. Machines using PCH DMIC need to update UCM config to control 'Dmic0 Capture Switch' mixer properly.

Support DMIC mute LED and volume mute function on IPC4 firmware/topology

---

src/audio/module_adapter/module_adapter.c
src/schedule/zephyr_dp_schedule.c

When DP start, copy from DP to LL should be delayed till first
DP deadline time.
In current implementation the cycle counter is set at every
DP scheduler trigger. If DP is - for any reason - scheduled
again before its deadline passes, the counter will be set again
and copying delay time will be too long. In extreme situation
(i.e. if OBS is set to long value when IBS is short - in this case
DP will proceed a short data chunks with a long deadline), it may
lead to permanent stuck in processing.

dp: delayed start should apply to the first DP cycle only 

---

tools/topology/topology1/sof-imx8ulp-9x9-btsco.m4
tools/topology/topology1/sof-imx8ulp-btsco.m4

On 8ULP SAI is connected to BT which supports
only 1 channel for both playback and record.
Fixes: aaff3523144e ('topology1: pipe-volume-capture.m4: Set minimum number of channels to 2')

topology1: imx8ulp: overwrite CHANNELS_MIN

---

tools/logger/convert.c
tools/logger/convert.h

This will fix scan tool reported issue:
time_precision variable can be used as -1
```
case 'f':
config.time_precision = atoi(optarg);
if (config.time_precision < 0) {
case 'g':
config.time_precision = -1;
```
Fixes commit ff9343aa4a59

logger: convert: fix variable type for negative value

---

src/include/ipc4/fw_reg.h

Disable delay reporting as a workaround to bug
https://github.com/thesofproject/linux/issues/4781 SOF driver checks the ABI version and if it's not 1, delay reporting is disabled.

ipc4: fw_reg: downgrade FW_REGS version to 0 to disable delay reporting

---

.github/workflows/installer.yml
.github/workflows/pull-request.yml
installer/tests/staging_sof_ref.txt
scripts/test-repro-build.sh
scripts/xtensa-build-all.sh

To prepare for XTOS deprecation and switch to Zephyr native drivers on i.MX8QM/i.MX8QXP, remove the ability to build SOF with XTOS on said platforms. Also, remove all XTOS builds/tests for these platforms from CI.

Deprecate XTOS on imx8/imx8x platforms

---

zephyr/docker-build.sh

Pure comment change, no code change.
Kudos to Stephanos Ioannidis for patiently explaining this to me on Discord.

[SKIP SOF-TEST] zephyr/docker-build.sh: explain why we autodetect with FindZephyr-sdk

---

lmdk/libraries/dummy/CMakeLists.txt
src/include/module/iadk/adsp_error_code.h

Ported additional error code definitions from iadk module API.
Removed unused api version definitions. The API version used by the module is now defined in the module api version header file. The definitions in CMakeLists.txt are no longer needed.

lmdk: module: Extend module error code definitions

---

src/audio/host-zephyr.c

Currently, the DMA block configuration (struct dma_block_config) is placed on the stack during host_common_params(). Later on, host_copy_one_shot() tries to re-configure the DMAC driver using the same block configuration that's located in a stack frame that's no longer valid. As such, allocate a DMA block configuration on the heap during host_common_params() which can be used later on (e.g: during host_copy_one_shot()) to reconfigure the DMAC.
Cherry-picked from https://github.com/thesofproject/sof/pull/8859

audio: host-zephyr: Allocate DMA block configuration on heap

---

tools/topology/topology2/cavs-es83x6.conf
tools/topology/topology2/cavs-nocodec-bt.conf
tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/cavs-rt5682.conf
tools/topology/topology2/cavs-sdw-src-gain-mixin.conf
tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/development/cavs-nocodec-crossover.conf
tools/topology/topology2/development/cavs-nocodec-rtcaec.conf
tools/topology/topology2/development/sof-plugin.conf
tools/topology/topology2/imx8-wm8960.conf
tools/topology/topology2/include/common/common_definitions.conf
tools/topology/topology2/include/common/tokens.conf
tools/topology/topology2/include/components/dai-copier.conf
tools/topology/topology2/include/components/dai.conf
tools/topology/topology2/include/dais/sai.conf
tools/topology/topology2/include/pipelines/gain-capture.conf
tools/topology/topology2/include/pipelines/gain-playback.conf
tools/topology/topology2/production/CMakeLists.txt
tools/topology/topology2/production/tplg-targets-imx8.cmake
tools/topology/topology2/sof-hda-generic.conf

Add SAI class for topology2.
Add simple playback topology2 for i.MX8MP.

topology2: add support for imx8mp

---

tools/tune/src/src_export_coef.m
tools/tune/src/src_export_table_2s.m

This patch makes to SRC coefficients tables generator same changes as done in recent git commits.
commit 88fdb10e522c ("audio: src: rename sample rate converter coefficient folder name") moved coefficients files location to src/audio/src/coefs.
commit 90fef5afd2ad ("src_lite: add module") removed include of src.h from upper level due to another src-lite version.
'commit 7f4e6aed7469 ("src: make coefficients constant") added const to struct src_stage.

Tools: Tune: SRC: Update generator to produce similar as edited

---

zephyr/lib/cpu.c

Keep timer interrupt handling on the primary core, this avoids secondary cores failing to handle timer interrupts immediately after power on.
This fixes the IPC timeout when starting a secondary core, most frequently happening on mtl-008

multicore: don't enable timer interrupts on secondary cores

---

src/audio/mixin_mixout/CMakeLists.txt
src/audio/mixin_mixout/Kconfig
src/audio/mixin_mixout/mixin_mixout.h
src/audio/mixin_mixout/mixin_mixout_generic.c
src/audio/mixin_mixout/mixin_mixout_hifi5.c
zephyr/CMakeLists.txt

Add HiFi5 implementation of mix functions, compared with HiFi3 version, can reduce about 27% cycles.

Audio: Mixin_mixout: Add HiFi5 implementation.

---

zephyr/lib/regions_mm.c

Fix various cases of allocation errors.

Virtual memory heaps fixes

---

.github/workflows/ipc_fuzzer.yml
scripts/fuzz.sh

There was no need to use the external "timeout" command + some complicated exit code logic, libFuzzer has that feature built-in. Switch to it and delete a few good line.
Add an option to use the built-in, concurrent -jobs feature which saves a massive amount of time. It has some quirks so do not enable it by default.
Decrease verbosity by default.
Add in the help message the magic replay command that saves a ton of time.
cc:
- #8832
- https://github.com/zephyrproject-rtos/zephyr/pull/68494
- #8886

[SKIP SOF-TEST] fuzz.sh: add -jobs parameter. Switch to built-in -max_total_time.

---

src/audio/module_adapter/module/modules.c

modules_init() already has a "dev" variable, no need to re-calculate it repeatedly.

module: (cosmetic) use an existing local variable

---

zephyr/lib/pm_runtime.c

Clean up an incorrect TODO comment in the power management runtime policy.
The removed comment suggested the need for substates to handle cases where power gating (PG) is enabled and clock gating (CG) is disabled. However, this is not accurate because:
- Enabling PG when CG is not allowed is not feasible; entering PG could inadvertently gate the clock even if CG prevent is active.
- Substates are no longer required as clock gating is now always enabled.
This change clarifies the power management behavior and removes confusion around the handling of power and clock gating.

zephyr: pm_runtime: Remove outdated TODO comment

---

src/platform/Kconfig

Current commit message:
In Zephyr, L3_HEAP is available in `intel_ace15_mtpm/adsp_memory.h` and
`intel_ace20_lnl/adsp_memory.h` but not in `intel_tgl_adsp/adsp_memory.h`
Don't allow configuration that can't possible compile.

config L3_HEAP: add missing "ACE" dependency

---

src/ipc/ipc4/handler.c
zephyr/boot_test.c
zephyr/test/vmh.c

Change boot test trigger from ipc to zephyr API call.
Change existing vmh tests and expand it.

Virtual Memory Heaps boot testing improvements

---

src/include/ipc/topology.h
src/ipc/ipc-helper.c
src/ipc/ipc3/handler.c

Fixes lack of SOF_MEM_CAPS_* input validation found in #8832

ipc-helper.c: reject invalid SOF_MEM_CAPS_* bits

---

tools/topology/topology2/development/tplg-targets-bench.cmake
tools/topology/topology2/development/tplg-targets.cmake

Since there is no NHLT blob included to these topologies, the same topology works for all HDA platforms, e.g. TGL, MTL, LNL.

Tools: Topology2: No need for HDA platform variants for benchmark tplg

---

app/boards/mimx93_evk_a55.overlay
west.yml
zephyr/lib/alloc.c
zephyr/lib/cpu.c

Modified https://github.com/thesofproject/sof/pull/8901 to address the failures seen in CI.

west.yml: update Zephyr to 9d1df132b1c + one revert

---

west.yml

Update Zephyr with backported fixed from Zephyr upstream including the following patches:
337b518c3311 dai: intel: dmic: demote spurious LOG_ERR in dai_nhlt_get_clock_div()
802baf38426b soc: xtensa: intel_adsp: restore bootctl with per-core state
576924d5f201 drivers: dma: intel-adsp-hda: modify stop dma logic
369241d7bf7d drivers: dma: intel-adsp-hda: add delay to stop host dma

[stable-v2.9] west.yml: update Zephyr with backported fixes

---

.github/workflows/ipc_fuzzer.yml
.github/workflows/zephyr.yml

2 similar commits
Fixes a lot of these warnings:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Example in daily tests:
https://github.com/thesofproject/sof/actions/runs/8165043709

[SKIP SOF-TEST] upgrade deprecated Github Actions (node.js v16)

---

src/audio/drc/drc_math_hifi3.c

Use the xtense intrinsic instrunctions directly can save at least 10% cycles for those functions, and save about 0.9mcps for DRC component.

Audio: DRC: DRC math function optimization

---

src/audio/dai-zephyr.c
src/audio/host-zephyr.c
src/ipc/ipc3/dai.c
src/ipc/ipc3/host-page-table.c
src/lib/dai.c
zephyr/lib/dma.c

This PR is a combination of patches cherry-picked from https://github.com/thesofproject/sof/pull/8520 and https://github.com/thesofproject/sof/pull/8844. These patches don't require a Zephyr hash bump and are needed for the transition of NXP platforms to native Zephyr drivers.

Preparatory patches for NXP platforms transition to Zephyr native drivers

---

src/audio/multiband_drc/multiband_drc.c
src/audio/multiband_drc/multiband_drc_generic.c
src/include/sof/audio/multiband_drc/multiband_drc.h

In present multiband_drc design, the enabled state is determined by the switch control while multiband_drc starts to process. If the switch control toggles while processing, it will take effects on the next time multiband_drc starts to process.
This commit makes change to let the enabled state update instantaneously by the switch control toggle when multiband_drc is processing.

multiband_drc: instantaneous enabled state switch on processing

---

src/idc/zephyr_idc.c

Replace infinite wait with a time-limited wait. In case a blocking IDC message is not handled within IDC_TIMEOUT, return an error instead of waiting. This allows to debug stuck core-to-core communication easier.

idc: zephyr: add a timeout to blocking IDC send

---

scripts/xtensa-build-zephyr.py

Add new file generated since commit cf9a444bfc13 ("toml: modularise TOML configuration")
Optional because it's not generated for all platforms.

xtensa-build-zephyr.py: checksum newly generated rimage_config.toml file

---

src/audio/module_adapter/module/modules.c
src/include/sof/ipc/topology.h
src/include/sof/lib_manager.h
src/include/sof/llext_manager.h
src/ipc/ipc4/helper.c
src/library_manager/lib_manager.c
src/library_manager/llext_manager.c

Added a const modifier to the module manifest variable in the lib_manager_store_library function to prevent it from being accidentally modified.
Added verification of preload_page_count from module manifest. The preload_page_count value from the loadable library manifest is used to determine size of allocated memory buffer. If this value is smaller than the manifest size, it will lead to memory corruption.
Removed pointer to a library manifest from the parameters list of the lib_manager_register_module function.
Instead of a pointer to a component driver and ipc config, the lib_manager_free_module and llext_manager_free_module functions now gets component id.
To prevent unintentional modification of a loadable library manifest, a const modifier has been added to all variables pointing to …

lib_manager: llext_manager: Add const to variables and function parameters cleanup

---

zephyr/lib/dma.c

With the switch to HWMv2, `CONFIG_SOC_SERIES_MIMX9_A55` has been renamed to `CONFIG_SOC_MIMX9352_A55` so make sure we also use the correct name when fetching the driver structure associated with 93's DMACs.

zephyr: lib: dma: adapt imx93 Kconfig name to HWMv2 name

---

west.yml

Update Zephyr to newer baseline. Among other updates, this brings in Zephyr commit "intel_adsp/ace: power: Lock interruption when power gate fails" that fixes a frequent issue seen in SOF CI on Intel MTL platforms.
Link: https://github.com/thesofproject/sof/issues/8908

west.yml: update Zephyr to 251f52cbceb8  (March 13)

---

tools/topology/topology2/cavs-mixin-mixout-hda.conf

This patch replaces pipeline mixout-gain-dai-copier-playback with mixout-gain-efx-dai-copier-playback. The purpose is to allow enhance of audio playback quality with equalizers (IIR and FIR) and dynamic range control (DRC).
The components are programmed by default to passthrough for minimal overhead. They can be activated via sof-ctl or UCM with ALSA controls.
- Post Mixer Analog Playback IIR Eq bytes
- Post Mixer Analog Playback FIR Eq bytes
- Post Mixer Analog Playback DRC bytes
- Post Mixer Analog Playback DRC switch
The recommendation is to keep headphone playback flat and enable processing only when HDA output is in speaker mode.

Tools: Topology2: Add IIR, FIR, DRC to HDA analog playback

---

tools/topology/topology2/development/tplg-targets.cmake

Multicore is not working correctly for Intel cAVS2.5 in Zephyr upstream and the fixing will take a longer time, so disable this feature in nocodec configuration.
Link: https://github.com/thesofproject/sof/issues/8942

topology2: sof-tgl/adl-nocodec: disable multicore

---

src/library_manager/lib_manager.c

Memory region must first be mapped as writable to allow data to be placed there. Then the target access flags are set, e.g. read-only and executable.
Updated zephyr to https://github.com/zephyrproject-rtos/zephyr/commit/9cf3e084290c8ea58c9751a1131f985304ad3e27

lib_manager: Set target memory flags after data loading from storage

---

src/audio/asrc/asrc_ipc4.c
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module/modules.c
src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc3.c
src/audio/module_adapter/module_adapter_ipc4.c
src/include/module/module/base.h
src/include/sof/audio/component.h
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/audio/module_adapter/module/modules.h
src/library_manager/lib_manager.c

Moved pointer to module_interface from struct module_data to comp_driver structure. The change is aimed at clearing the module_data structure of fields intended for exclusive use by sof. All modules are eventually use module interface so this pointer will be in comp_driver anyway.

component: module_adapter: Move module_interface pointer to comp_driver

---

scripts/xtensa-build-zephyr.py

autoconf.h has strings, configs.c has not.
We can do this now since this $BOARD_REVISION fix:
https://github.com/zephyrproject-rtos/zephyr/commit/811a74c0199f

[SKIP SOF-TEST] xtensa-build-zephyr.py: checksum autoconf.h instead of configs.c

---

src/audio/dai-zephyr.c

The DMAC has the same view of the address space as the HOST. As such, the source and destination addresses need to be converted to HOST-relative addresses before attempting to perform a DMA transfer. This is only relevant for platforms for which the DSP and HOST have different views of the address space (e.g: i.MX8ULP).

audio: dai-zephyr: convert DMA src/dst addresses to host-relative addresses

---

src/audio/multiband_drc/multiband_drc.c
src/audio/multiband_drc/multiband_drc_generic.c
src/include/sof/audio/multiband_drc/multiband_drc.h

In present multiband_drc design, the enabled state is determined by the switch control while multiband_drc starts to process. If the switch control toggles while processing, it will take effects on the next time multiband_drc starts to process.
This commit makes change to let the enabled state update instantaneously by the switch control toggle when multiband_drc is processing.

[cavs2.5-001] multiband_drc: instantaneous enabled state switch on processing [cherry-picked from stable-v2.2]

---

west.yml

Contains following updates affecting SOF targets:
81658e67e7c0 dts: xtensa: intel_adsp: Remove ALH nodes from ACE 2.0 LNL DTS
4ea52bdd1297 soc: xtensa: intel: Update power status bitfields for LNL
a39a61015c59 dts: xtensa: intel: Reorder LNL power domains
64a81ffb23ba dts: xtensa: intel_adsp: ace15: Update power domain for hda link nodes
ff2dd7f25a99 dts: xtensa: intel: Reorder ACE 1.5 power domain nodes
315ee38b95a2 ADSP: don't use timer interrupts on secondary cores
e914c60ae156 boards: intel_adsp: fix dead link
010f39a409e0 soc: intel_adsp_cavs: store PS when power gating secondary core

west.yml: update Zephyr to 8858a024c015

---

src/ipc/ipc4/helper.c

- list_is_empty is required to properly check source list
- at this stage empty list is allowed since source bind might not happen yet

ipc4: helper: fix checks in comp dir update

---

src/idc/zephyr_idc.c

The IDC message objects are stored to static "idc_work", so the cache operations are unnecessary when pointers to these messages are passed around.

idc: zephyr: remove unnecessary cache invd/flush calls

---

src/audio/module_adapter/module_adapter.c

Module adapter DP copy checks shouldnt block pipeline, similarly to  LL-only scenario

dp: do not block ppl because of sink/source limits

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-imx8ulp-9x9-btsco.m4
tools/topology/topology1/sof-imx8ulp-btsco.m4

These patches are needed for the native transition. Trying to upstream them before the transition itself to make the PR doing the transition easier to review.

tools: topology1: imx8ulp: correct BCLK rate and change BCLK polarity and protocol

---

app/boards/imx93_evk_mimx9352_a55.conf
app/boards/imx93_evk_mimx9352_a55.overlay
src/platform/Kconfig
src/platform/imx93_a55/platform.c
tools/topology/topology1/sof-imx93-wm8962.m4
west.yml
zephyr/CMakeLists.txt

With this PR, the i.MX93 platform will now start using the timer domain in conjunction with the Zephyr native drivers.
Zephyr dependencies:
1. https://github.com/zephyrproject-rtos/zephyr/pull/65671 (EDMA)
2. https://github.com/zephyrproject-rtos/zephyr/pull/65187 (DAI)
3. https://github.com/zephyrproject-rtos/zephyr/pull/65679 (removal of SAI3 and EDMA static mappings)
4. https://github.com/zephyrproject-rtos/zephyr/pull/65684 (DAI_DIR_{TX/RX} value adjustment)
**Important notes**:
1. Currently, the PR is split in multiple commits. This is done to ease the reviewing process, but most of the commits will be squashed into a single one to avoid breaking git bisect.
2. If git dependency 3 is merged before this PR and the Zephyr revision is bumped up this will lead to SOF no longer working on …

nxp: imx93_a55: Switch to timer domain and Zephyr native drivers

---

src/audio/copier/copier.c

The latency value is in number of periods (1ms) while the buffer allocated for the DAI copier is at least 2 periods.
This can shoot up the calculated  stream_start_offset resulting invalid delay reporting.
Use the period size of the DAI copier to correct this error.
The kernel reported delay currently (on normal non DeepBuffer PCM): at start: ~302 frames
after 20x pause/resume: ~6530 frames
With this patch:
at start: ~254 frames
after 20x pause/resume: ~3600 frames
The drift rate is about the same with DeepBuffer.

copier: Use correct multiplier for latency to bytes calculation

---

tools/topology/topology1/CMakeLists.txt

Add support to generate the topology which can be used to support 
4channel DMIC,SSP based codec and HDMI-in capture via I2S combo.

[stable-v2.2] topology1: Add topology for 4ch DMIC+ SSP codec+HDMI-in capture..

---

scripts/xtensa-build-zephyr.py

_[OLD commit message]_
Everyone should use deployable builds by default.
------
_[NEW commit message]_
Every Linux developer should use deployable builds by default.
Until Peter Ujfalusi's very recent work in this script, we had a
complete `/lib/firmware/` structure disconnect between the IPC4 output
of this script and the IPC4 expectations of the Linux kernel. To
workaround this disconnect, every CI and Linux developer used to
implement duplicate and inconsistent firmware deployment hacks.
People crafting sof-bin releases also had to organize IPC4 releases
manually, which was extremely error-prone and with limited test
coverage (Thanks Kai and Mengdong!)
Now that Peter gracefully fixed the layout, documented it in sof-docs
and implemented it in this script, the time for all Linux …

xtensa-build-zephyr.py: make --deployable-build the default

---

src/audio/module_adapter/library/native_system_agent.c
src/audio/module_adapter/module/modules.c
src/include/module/module/base.h
src/include/sof/audio/module_adapter/library/native_system_agent.h

Removed unnecessary functions from Processing Module Adapter. To ensure proper operation of native loadable modules it is necessary to bypass Processing Module Adapter used by FDK modules. This is currently done by overriding the pointer to module_interface used by the Module Adapter. Thanks to this, the Module Adapter directly calls functions provided by native module. As in this case the Processing Module Adapter functions are omitted, support for native libraries are removed from it as
it is no longer needed. This leads to remove is_native_sof variable and modules_process_raw, modules_process_audio_stream functions.
The code allocating/freeing in_buff and out_buff buffers, which were not used, was removed from the processing module adapter.
The value stored by the Processing Module …

modules: Remove unused code and variables

---

src/math/auditory/auditory.c

In psy_get_mel_filterbank() if fb->slaney_normalize isn't set, 3 variables are reset to the same values needless every loop iteration. Move initialisations outside the loop instead.

math: avoid re-initialising variables every loop iteration

---

tools/tune/eq/example_spk_eq.m

The IIR files export overwrites the FIR files due to mistake in the script.
Fixes commit 5ddbd34ba917 ("Tools: Tune: EQ: Add tplg2 blobs create")

Tools: Tune: Eq: Fix IIR data files names in example_spk_eq.m

---

.github/workflows/zephyr.yml

Fixes the following warning:
https://github.com/thesofproject/sof/actions/runs/8289483047
```
Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: actions/setup-python@v4. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

[SKIP SOF-TEST] .github/zephyr: upgrade obsolete actions/setup-python@v4 to v5

---

tools/topology/topology2/include/components/pipeline.conf

Add a note that priority 0 is the highest priority and indicates pipeline that should be run first. This matches with the SOF scheduler implementation.

topology2: pipeline: document pipeline.priority attribute

---

tools/topology/topology2/production/tplg-targets-cavs25.cmake

The widget name size will exceed the character limit and lead to below error
failed to find module info for widget
alh-copier.SDW0-Playback-SimpleJack.0 with UUID
00000000-0000-0000-0000-000000000000
Shorten the stream name to fix it.

Topology2: sof-tgl-rt712: remove SDWx from stream name

---

west.yml

Contains the following patches affecting SOF:
bba8641354bf dts: xtensa: nxp_imx8: add ESAI0 node
bd9b3c67b240 drivers: dai: add driver for NXP's ESAI
f4c73105e55a drivers: dai: sai: add pinctrl support
Cherry-picked from https://github.com/thesofproject/sof/pull/8863

west.yml: update Zephyr to fd1a129a3e63

---

src/init/init.c

This patch refines the initialization process for secondary cores in a multicore environment when using Zephyr as the RTOS. The patch introduces a `check_restore` function specifically for Zephyr, which checks if basic core structures (IDC, notifier, schedulers) have been previously allocated and are still present in memory, indicating that the system is not undergoing a cold boot.
By adding this check, the system avoids unnecessary re-allocation of these structures during the power-up sequence of secondary cores, effectively preventing the memory leak observed during repeated power cycle tests.
fix #9005

init: zephyr: Fix memory leak during secondary core init

---

src/audio/aria/aria.toml
src/audio/codec/dts/dts.toml
src/audio/copier/copier.toml
src/audio/crossover/crossover.toml
src/audio/dcblock/dcblock.toml
src/audio/drc/drc.toml
src/audio/eq_fir/eq_fir.toml
src/audio/eq_iir/eq_iir.toml
src/audio/google/google_rtc_audio_processing.toml
src/audio/igo_nr/igo_nr.toml
src/audio/kpb.toml
src/audio/mixin_mixout/mixin_mixout.toml
src/audio/module_adapter/module/cadence.toml
src/audio/multiband_drc/multiband_drc.toml
src/audio/mux/mux.toml
src/audio/rtnr/rtnr.toml
src/audio/selector/selector.toml
src/audio/src/src.toml
src/audio/src/src_lite.toml
src/audio/tdfb/tdfb.toml
src/audio/up_down_mixer/up_down_mixer.toml
src/audio/volume/gain.toml
src/audio/volume/peakvol.toml
src/probe/probe.toml
src/samples/audio/detect_test.toml
src/samples/audio/smart_amp_test.toml

Having to find source files to read comments is not convenient.
This depends on https://github.com/zephyrproject-rtos/zephyr/pull/67019 which was merged a while ago.

Use new '-DREM=#' prefix to preserve comments in pre-processed .toml

---

src/audio/volume/volume.c
src/audio/volume/volume_ipc4.c

In IPC4 the individual channel gains are passed in separate messages. One channel may have started to ramp to a new gain while a new channel gain arrives for other channel. If the gain is same as the previous control value, the ongoing ramp is stopped and the gain remains at a transition value.

Audio: Volume: Fix ongoing gain ramp stop and wrong final gain

---

west.yml

Update to a Zephyr version, containing
2ccf775396c2 ("llext: add support for relocatable objects on Xtensa")

west: update to a newer Zephyr version

---

src/audio/module_adapter/module/modules.c
src/include/sof/ipc/topology.h
src/include/sof/lib_manager.h
src/ipc/ipc4/helper.c
src/library_manager/lib_manager.c
src/library_manager/llext_manager.c

Added the lib_manager_get_module_manifest function that returns manifest of selected module based on its id. It was performed in many places and moving it into function simplified the code and increased its readability.
The lib_manager_get_library_module_desc function was renamed to lib_manager_get_library_manifest, which better describes what it do.
All calls to the ipc4_get_comp_drv function pass the uint32_t value as a parameter, so the type of functions parameter was changed to uint32_t.

lib_manager: Add lib_manager_get_module_manifest function

---

tools/topology/topology2/sof-hda-generic.conf

This quick fix avoids build of NHLT blob for the default (TGL) for LNL HDA generic platform.
The DMIC part of NHLT from TGL is not suitable for LNL, while a blob for MTL can be used. A proper lnl.conf will be added later.

Tools: Topology2: Add include of mtl.conf for LNL HDA generic

---

src/audio/pipeline/pipeline-graph.c
src/audio/pipeline/pipeline-params.c
src/ipc/ipc-helper.c
src/ipc/ipc4/helper.c

This pull request includes a series of commits that standardize the logging format for component IDs across different parts of the audio firmware. The changes convert component ID logs from decimal to hexadecimal format, aligning with the common logging practices within the firmware and other debugging tools. This consistency simplifies the process of cross-referencing component IDs during development and debugging.
The commits cover updates to ipc-helper logs, ipc4 helper logs, and pipeline graph logs, ensuring that component IDs are uniformly displayed in hexadecimal format. These changes not only improve readability but also enhance the efficiency of searching and correlating logs when investigating issues.
List of changes:
- ipc4: helper: Use hex format for component IDs in ipc-helper …

ipc4: Unify component ID logging format across various IPC and pipeline logs

---

src/audio/module_adapter/module/cadence.c

Assuming the following pipeline:
HOST ---> MA (CADENCE [MP3 DECODER]) ---> DAI
for native Zephyr SOF, data is first copied from the host component to MA and then from Linux to the host component. This means that the first chunk of data will be 0s (since the host DMA buffer is zero'd via host_prepare()) instead of useful data. Because of this, the `XA_CMD_TYPE_INIT_PROCESS` command will return a non-fatal error (i.e:
`XA_MP3DEC_EXECUTE_NONFATAL_NEXT_SYNC_NOT_FOUND`). This is not the case for non-native SOF since data is first copied from Linux to host and then from host to MA so the aforementioned command will get actual data instead of 0s.
Instead of having to alter the flow of data for native Zephyr SOF (i.e: change the order in which data is copied), which could impact other components …

module: cadence: don't return on non-fatal error

---

src/samples/audio/smart_amp_test_ipc4.c

This patch fixes a rare crash while testing multiple-pause-resume.sh described in https://github.com/thesofproject/sof/issues/8651 
Explanation:
Dai copier sends data to smart_amp in lnl nocodec. Smart_amp_test uses a process function to just copy buffer contents from sources to sink. The bind between those two uses a 16bit format buffer, while other smart amp pins use 32bit. Smart_amp_test in .prepare function chooses a process callback based only on the format of the sink. This way a 32bit process function is chosen, despite one of the sources being 16bit which risks misalignment. Crash is pretty rare because the misalignment only happens when dai_copier outputs one sample less (an odd number), probably due to stress.
Pushing one of the possible fixes here, but there are other options I …

smart_amp_test: fix crash due to different source formats

---

scripts/llext_link_helper.py
src/library_manager/lib_manager.c
src/library_manager/llext_manager.c
src/samples/audio/smart_amp_llext/CMakeLists.txt
tools/rimage/src/elf_file.c

a split up of https://github.com/thesofproject/sof/pull/9013/commits/fb6286dbfc48e3f8d12dc99d5ac982cfd4d16124 . Can be merged independently since this code isn't used yet, but to work it'll need the rest of #9013, including a Zephyr update, which is now available as #9019

Part 1 of #9013

---

tools/topology/topology2/include/common/pcm_caps.conf

Use 'rates' instead to specify that 48K is the default supported rate.

topology2: pcm_caps: Remove defaults for rate_min/rate_max

---

src/samples/audio/detect_test.c

Default threshold should be applyed only if it was not already set via IPC4_DETECT_TEST_SET_CONFIG call.

detect_test: Do not overwrite supplied threshold

---

src/audio/module_adapter/module/modules.c
src/audio/module_adapter/module_adapter.c
src/include/module/module/base.h
src/include/sof/lib_manager.h
src/include/sof/llext_manager.h
src/library_manager/lib_manager.c
src/library_manager/llext_manager.c

This PR addresses an issue with non-iadk loadable modules for which the `modules_free` function is not called.
For some of following commits I already prepared PRs - pending review.
<del>d37d68961 modules: Remove unused module_entry_point from module_data
87f5e3e69 module_adapter: modules: Remove unused sys_service pointer
c951d57d6 module/base: modules: Remove module_adapter from module_data
c85d87216 modules: Remove unused buffers
2b49f997e modules: Remove unnecessary functions from Processing Module Adapter</del>
Actual PR content:
e27ea44f5 lib_manager: modules: move native lib support to lib_manager
<del>94b9976df lib_manager: Rename lib_manager_get_library_module_desc function
ca42dff5a lib_manager: Add lib_manager_get_module_manifest function
11d8a423b ipc4/helper: …

lib_manager: modules: Fix missing call to modules_free

---

tools/plugin/pipe/ipc4.c

A label must be followed with a statement and declaration is not a statement. Enclose the case in brackers to avoid compiler error on this.

tools: plugin: ipc4: fix build error in switch-case

---

west.yml

Update Zephyr to new baseline containing following patches affecting SOF targets:
8a63a0a56339 intel_adsp: ipc: Fix policy state lock usage
e85226fd1a03 soc/intel_adsp: ipc: Remove fragile device state check
741bbaca6dd7 soc/intel_adsp: ipc: Remove unnecessary device state lock
a200dd88d878 dts: xtensa: intel_adsp: Set soft-off state as disabled
d5897a48aaab ipc: intel_adsp: Ensure IPC completion before runtime idle

west.yml: update zephyr Apr17

---

src/audio/base_fw.c
src/include/ipc4/base_fw_platform.h
src/platform/intel/ace/lib/base_fw_platform.c
src/platform/posix/base_fw_platform.c
zephyr/CMakeLists.txt

First patch to address https://github.com/thesofproject/sof/issues/8391 - more to come later.
Some of the HW_CONFIG fields are platform specific and cannot be filled with generic means in generic code.
Handle this data via a simple platform abstraction to hook platform specific code to HW_CONFIG handling. Move out existing code for Intel cAVS and ACE platforms.

audio: base_fw: add platform layer to hw_config data

---

src/audio/module_adapter/module_adapter_ipc3.c
src/audio/module_adapter/module_adapter_ipc4.c

At present, if get_configuration is not implemented by internal module, module_adapter will return 0 directly on config read commands. Under the circumstances, the host will suppose the reading is succeeded, but in fact the ata in IPC buffer is unwanted.
This commit changes the return code to non-zero for such cases, which prevents the host getting the unwanted config data.

module_adapter: return error if get_conf is not implemented

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

This patch adds following hardware configuration on LNL product:
SDW link0: RT714 DMIC
SDW link1: RT1318 Left Speaker
SDW link2: RT1318 Right Speaker

topology2: add rt1318 and rt714 support on LNL

---

src/audio/mixin_mixout/mixin_mixout.c
src/audio/mixin_mixout/mixin_mixout.h
src/audio/mixin_mixout/mixin_mixout_generic.c
src/audio/mixin_mixout/mixin_mixout_hifi3.c
src/audio/mixin_mixout/mixin_mixout_hifi5.c

Restore gain support which was accidentally removed during previous HIFI optimization/refactoring.
This commit only adds gain supports to "generic" and "HIFI3" mixin implementation. Implementation for "HIFI5" version is a TODO.

ipc4: mixin: Add gain support (generic and HIFI3)

---

src/audio/volume/volume_ipc4.c

Fade out was not working due to wrong order of operations. Ramp type was set up before the correct type was set (init_ramp was used before set_volume_ipc4), so the default ramp was always used.
Issue is there since 8f9c68ae57dbeb1958756a9def803fbadf86c8f3

volume: fix wrong volume ramp being chosen

---

scripts/xtensa-build-zephyr.py

Installing most of the tools/ directory does not technically require building any platform, so add that possibility.
This is useful because the Jenkins-based CI builds the (userspace) tools separately. So far it has been picking hardcoded source paths but of course the HWMv2 transition just broke that:
- https://github.com/thesofproject/sof/pull/8913
While it's too late this time (we want to keep CI able to test stable branches for some time), this commit prepares a future where all CIs can stop hardcoding Zephyr source paths and pick the output of the xtensa-build-zephyr.py installer and indirection layer instead.

xtensa-build-zephyr.py: add flexibility to generate `tools/` only

---

.github/workflows/zephyr.yml
west.yml

Pulls in the following patches relevant to SOF:
94d156c9c84c nxp: imx8ulp: enable serial interface
bc63835ba240 dts: xtensa: intel_adsp_cavs25_tgph: correct SSP definition
aecf19c3c1be dts: xtensa: intel_adsp_ace15: correct SSP definition
45205f865e18 dts: xtensa: intel_adsp_ace20: correct SSP definition
17081222e2e7 drivers: dai: intel: ssp: fix LOG_ERR level / false positive
fb7e9379e137 cmake: add control over inline source code disassembly
and fixes https://github.com/thesofproject/sof/issues/9034

Zephyr manifest update and fix for repro build issue

---

src/audio/base_fw.c
src/include/sof/ipc/topology.h
src/ipc/ipc4/handler.c

Added support for ipc4 query no 255 (10).
This make it possible to get information about
the current loaded pipelines.

Audio: basefw: Implement ipc4 pipeline info get

---

src/audio/base_fw.c
src/include/ipc4/base_fw.h
src/include/ipc4/base_fw_platform.h
src/include/sof/lib_manager.h
src/platform/intel/ace/lib/base_fw_platform.c
src/platform/posix/base_fw_platform.c

Added support for ipc4 query no 16.
This makes it possible to get information about the current basefw library.

Audio: basefw: Implemented ipc4 libraries info get

---

west.yml

Pulls in the following patches relevant to SOF:
799a456c2586 nxp: imx8ulp: add audio-related nodes
Needed for https://github.com/thesofproject/sof/pull/9076. Submitted as independent PR for visibility reasons.

west.yml: update Zephyr to 799a456c2586

---

src/audio/base_fw.c
src/include/ipc4/base_fw.h
src/include/ipc4/base_fw_platform.h
src/platform/intel/ace/lib/base_fw_platform.c
src/platform/posix/base_fw_platform.c

Continue from https://github.com/thesofproject/sof/pull/9059 (first 2 patches here are from #9059) and move more implementation out from the generic file.
UPDATE: 9059 closed, let's review the whole set in one go.
Addressing https://github.com/thesofproject/sof/issues/8391 and https://github.com/thesofproject/sof/issues/7549

audio: base_fw: move platform specific code from base_fw.c

---

tools/topology/topology2/include/common/pcm_caps.conf
tools/topology/topology2/platform/intel/deep-buffer.conf

topology2: Revisit period and buffer size settings
To be pragmatic about the period/buffer size values:
period_size_min = 192 is for Stereo, S16_le, 48Khz, 1ms
period_size_max = 2097152 common value among other sound cards
The buffer size:
buffer_size_min	=	384 # period_size_min * periods_min
buffer_size_max	=	4194304 # period_size_max * 2
The deep buffer PCM only changes the buffer_size_min to (S16_LE, Stereo, 48KHz, DEEPBUFFER_FW_DMA_MS) * 2

topology2: Revisit period and buffer size settings

---

src/audio/dp_queue.c
src/audio/module_adapter/module_adapter.c
src/include/sof/audio/dp_queue.h

Dp_queue is currently used only as a comp_buffer "shadow"  for DP modules.
Shadow buffers must have the very same param set as main buffers.
Problem: till now the complete vector of params was copied from comp_buffer to dp_queue inm prepare method.
If anything will change any of params afterwards, the change won't propagate.
This commit introduces sharing the param vector between comp_buffer and its shadow

dp: make dp_queue using externally provided params set

---

src/audio/copier/copier_dai.c
west.yml

This commit updates the copier DAI creation logic for I2S links to use the `v_index` field from the `node_id` structure as the DAI index. This change ensures that the correct DAI index is used when creating I2S links, aligning with the new SSP link management mechanism.
The following PR must be merged into the Zephyr repository before we can merge this PR:

audio: copier: use v_index for DAI index in I2S link creation

---

tools/topology/topology2/platform/intel/bt-generic.conf

Commit c77a4feb2f1f1 ("topology2: pcm_caps: Remove defaults for rate_min/rate_max") changed how rate constraints are described in topology. After this change, the rate_min/max was ignored by SOF Linux driver and the rate was incorrectly limited to 48000Hz for these topologies.
Fix this issue by enumerating the supported sampling rates with "rates".
Link: https://github.com/thesofproject/sof/issues/9067

topology2: intel: bt-generic.conf: fix rate constraints

---

src/trace/dma-trace.c

Dropping logs is bad but it should not be fatal in itself.
This ERROR is one of the last remaining errors in stable-v2.2, see https://github.com/thesofproject/sof-test/pull/1075#issuecomment-2049051006
Also switch to the "etrace": drop the dubious recursion and stop using the DMA trace when it's already saturated.
Disclaimer: this was (successfully) tested only on stable-v2.2, see #9036

dma-trace.c: lower log level of dropped logs and stop recursion

---

src/audio/base_fw.c
src/include/ipc/header.h
src/include/ipc4/base_fw_platform.h
src/platform/intel/ace/lib/base_fw_platform.c
src/platform/posix/base_fw_platform.c

Add support to handle IPC4_MODULES_INFO_GET message.
This make it possible to get information about the current loaded modules.

Audio: basefw: Implement ipc4 modules info get

---

src/trace/dma-trace.c

Dropping logs is bad but it should not be fatal in itself.
This ERROR is one of the last remaining errors in stable-v2.2, see
https://github.com/thesofproject/sof-test/pull/1075#issuecomment-2049051006
Also switch to the "etrace": drop the dubious recursion and stop using
the DMA trace when it's already saturated.
Disclaimer: this was (successfully) tested only on stable-v2.2, see https://github.com/thesofproject/sof/pull/9036
(cherry picked from commit https://github.com/marc-hb/sof/commit/bb31696aa6c9b6785e07237f8c6d4b29f59a7946)

[STABLE-2.2] dma-trace.c: lower log level of dropped logs and stop the recursion

---

tools/tune/eq/cmocka_data_eq_iir.m
tools/tune/eq/eq_defaults.m
tools/tune/eq/eq_norm.m
tools/tune/eq/example_fir_eq.m
tools/tune/eq/example_iir_bandsplit.m
tools/tune/eq/example_iir_eq.m
tools/tune/eq/example_spk_eq.m
tools/tune/eq/gui.m

This allows more freedom to scale the equalizers. Common criteria resulted with safe scaling to unnecessarily silent result or risk for audible clipping in the equalizer.

Tools: Tune: EQ: Normalize IIR and FIR separately

---

tools/topology/topology2/cavs-es83x6.conf
tools/topology/topology2/cavs-nocodec-bt.conf
tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/cavs-rt5682.conf
tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/development/cavs-nocodec-crossover.conf
tools/topology/topology2/development/cavs-nocodec-rtcaec.conf
tools/topology/topology2/platform/intel/lnl.conf
tools/topology/topology2/sof-hda-generic.conf

The new lnl.conf is copy of mtl.conf but DMIC_DRIVER_VERSION needs to be increased by one for a small registers change.

Tools: Topology2: Use for LNL own platform configuration lnl.conf

---

scripts/xtensa-build-zephyr.py

Pure comment fix, zero code change.
Fixes miss in commit f55338a985acf ("Switch Zephyr build to new sof/tools/rimage location")

[SKIP SOF-TEST] xtensa-build-zephyr.py: remove obsolete and misleading comment

---

tools/topology/topology2/production/tplg-targets-ace1.cmake

Two configurations for sof-mtl-rt713-l0-rt1318-l12-rt1713-l3 and sof-mtl-rt713-l0-rt1318-l1-rt1713-l3.

Topology2: add mtl rt713 rt1318 rt1713 support

---

src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc4.c

Cherry-pick from main. Note the code got revised during cherry-picking from main due to branch difference.

[mt8188/v0.2] module_adapter: return error if get_conf is not implemented

---

tools/topology/topology2/include/common/common_definitions.conf

Clarify documentation of SAMPLE_TYPE_MSB_INTEGER sample type value and fix documentation of SAMPLE_TYPE_LSB_INTEGER. These definitions are often confused with integer endianness, which is not related. Clarify this better.

topology2: common_definitions: improve SAMPLE_TYPE documentation

---

tools/topology/topology2/platform/intel/dmic-generic.conf
tools/topology/topology2/platform/intel/dmic1-passthrough.conf

This patch allows the kernel to choose 16 bit format if the DMIC NHLT is missing the recommended 32 bit mode blob.
The DAI copier is converting the output format for internal pipelines into S32_LE format, so the other operation is not impacted. For systems with 32 bit DMIC NHLT there is no impact.

Tools: Topology2: Intel: Add 16 bit DMIC DAI copier format option

---

src/audio/src/src_ipc4.c

The check of cd->ipc_config.base.audio_fmt.depth results to select S32_LE format processing function for SRC when the format is S24_LE. The check need to be done for valid_bit_depth instead.
The S32_LE function appears to work but any sample that exceeds the range -2^23 .. +2^23-1 is overflow for S24_le. Also the use of S24_LE processing core will improve the signal-to-noise ratio.
Reported-by: Tomasz Leman <tomasz.m.leman@intel.com>

Audio: SRC: Use valid_bit_depth to select processing function

---

src/audio/audio_stream.c
src/audio/buffer.c
src/audio/dp_queue.c
src/audio/mixin_mixout/mixin_mixout.c
src/audio/module_adapter/module_adapter.c
src/include/module/module/base.h
src/include/sof/audio/audio_stream.h
src/include/sof/audio/buffer.h
src/include/sof/audio/dp_queue.h
src/ipc/ipc4/helper.c

This is a follow up to https://github.com/thesofproject/sof/pull/9063 and a bugfix
The PR is connecting shadow dp_queue tightly with comp_buffer/audio_stream. 
1) it is more natural way, after changes comp_buffer is exposing either its own sink/src API or one provided by dp_queue 
2) race prevention. In internal tests there was a race condition found during frequent binding/unbinding DP to a running pipeline
3) less code in heavy module_adapter

Dp shadow as a part of comp_buffer / audio_stream

---

src/audio/base_fw_intel.c
src/platform/intel/cavs/include/cavs/lib/pm_memory.h
src/platform/lunarlake/include/platform/lib/shim.h
src/platform/meteorlake/include/platform/lib/shim.h
src/platform/tigerlake/include/platform/lib/shim.h

This change improves the TLV assembly algorithm in accordance with how the part for hpsram is assembled. In the case when ebb_state_dword_count is equal to 0, we skip adding the LSPGCTL register value for lpsram.
The following PR must be merged into the Zephyr repository before we can merge this PR:

base_fw: update mem_state_info TLV

---

tools/topology/topology2/cavs-benchmark-hda.conf
tools/topology/topology2/development/tplg-targets-bench.cmake
tools/topology/topology2/include/bench/tdfb_controls_capture.conf
tools/topology/topology2/include/bench/tdfb_controls_playback.conf
tools/topology/topology2/include/bench/tdfb_hda_route.conf
tools/topology/topology2/include/bench/tdfb_s16.conf
tools/topology/topology2/include/bench/tdfb_s24.conf
tools/topology/topology2/include/bench/tdfb_s32.conf

This patch adds s16/s24/s32 format test topologies for the time domain fixed beamformercomponent.

Tools: Topology2: Add benchmark topologies for TDFB component

---

src/audio/module_adapter/module/passthrough.c

Use LOG_MODULE_REGISTER() to register cadence in the Zephyr logger framework.

module_adapter: passthrough: register module logs in Zephyr

---

west.yml

Fast-forward Zephyr by around 350 patches, including following affecting SOF build targets:
soc/intel_adsp: ipc: initialize semaphore in driver init
drivers: dai: ssp: fix MN_MDIVCTRL_M_DIV_ENABLE for ACE+ platform
drivers: dai: intel: ssp: Only setup mclk/bclk when it is needed by role

west.yml: update Zephyr to e97d33d0c896 

---

src/drivers/intel/hda/hda-dma.c

Lower the log level of `tr_err(&hdma_tr, "hda_dma_link_check_xrun(): underrun detected");` to `tr_warn()`.
Underruns are expected when testing pause/start and these errors can hide other, "real", not expected errors; more details in https://github.com/thesofproject/sof-test/pull/1188
This "fixes" 2019 commit 293dfe2469cb ("hda-dma: refactor xrun handling")
Note this driver is not in the main branch anymore, removed by commit 59028ad3d136 ("drivers: Intel: remove Intel XTOS drivers")

[STABLE-v2.2] drivers: Intel: hda-dma: lower log level of "underrun detected"

---

tools/topology/topology2/production/tplg-targets-ace1.cmake

For some reason the sof-mtl-rt712-l0 topology was not created despite being listed in the kernel, and we now need the rt712 VB support with an additional SmartMic path.

topology2: add mtl-rt712 topologies version

---

west.yml

Fast-forward Zephyr by 700+ commits including following patches affecting SOF build targets:
ae082064ffa5 drivers: dai: sai: write some data into TX FIFO before start
0ca7ef78bc50 soc: intel_adsp: tools: merge cavstool.py and acetool.py code

west.yml: update Zephyr to 9d8059b6e5541 (May 20th)

---

src/audio/tdfb/tdfb.c
src/audio/tdfb/tdfb.h
src/audio/tdfb/tdfb.toml
src/audio/tdfb/tdfb_comp.h
src/audio/tdfb/tdfb_ipc3.c
src/audio/tdfb/tdfb_ipc4.c
tools/rimage/config/tgl-h.toml
tools/rimage/config/tgl.toml

The code in tdfb_params() was incorrect for a component that can have different number of channels in source and sink. The update of sink format can it worst case crash the successive component in pipeline if the source channels count has changed from the value the component has been initialized for.
The channels count need to be retrieved from input and output pins information in extended IPC4 base config. To get the extension the rimage toml files need to add for TDFB component the line init_config = "1".

Audio: TDFB: Fix firmware crash caused by TDFB sink format set

---

scripts/docker-run.sh

latest_ubuntu22.04 was used when upgrading to Ubuntu 22.04. Now it is time to go back to the latest.

scripts/docker-run.sh: thesofproject/sof:latest to default

---

.github/workflows/pull-request.yml

mt8188 toolchain is added to SOF docker image.

pull-request.yml: add mt8188 to gcc-build-only

---

tools/topology/topology2/platform/intel/dmic-generic.conf

This patch defines e.g. for sof-hda-generic-2ch.tplg DMIC0 only stereo formats as s16/24/32. Similarly for e.g. sof-hda-generic-4ch.tplg only four channels formats are defined.
The reduction of input formats options avoids the issue with kernel that it possibly selects invalid channels count for DMIC0 DAI when the channels count in connected pipelines varies due to processing components.
In such error the capture fails to no suitable DMIC NHLT blob found from BIOS or from topology depending platform.

Tools: Topology2: Define only same channels counts for DMIC0 dai-copier

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/development/CMakeLists.txt
tools/topology/topology1/development/sof-imx8-src-wm8960.m4
tools/topology/topology1/sof-imx8-compr-wm8960-mixer.m4
tools/topology/topology1/sof-imx8-wm8960-mixer.m4
tools/topology/topology1/sof-imx8-wm8960.m4

Add DMA_DOMAIN variable and based on this we set
SCHEDULE_DOMAIN to SCHEDULE_TIME_DOMAIN_DMA, otherwise is SCHEDULE_TIME_DOMAIN_TIMER.
Now, only i.MX8MP is using SCHEDULE_TIME_DOMAIN_DMA. Therefore the DMA_DOMAIN is added only for 8MP topologies.

topology: imx: Add a variable for schedule domain

---

zephyr/lib/regions_mm.c

The previous memory mapping function did not work properly if the buffer size exceeded the memory page size. In this case the size of the region to be checked passed to the `sys_bitarray_is_region_cleared` function was zero, causing the function to always return false. As a result, the allocator stated that a page was already mapped for a given address and did not map it. This led to a cpu exception when trying to access the allocated buffer. 
The function responsible for unmapping memory had a similar problem. Additionally, the size of the freed area was incorrectly determined and an incorrect offset was passed to the `sys_bitarray_is_region_cleared` function.
New functions have been created to map and unmap memory pages for allocated buffers. It don't need allocation of temporary array …

regions_mm: New memory mapping functions

---

app/winconsole_overlay.conf

Add a new overlay to enable logging via winstream backend. This is alternative memory window based logging backend that typically uses memory window 3 as transport. The backend is directly using Zephyr winstream protocol, and has no dependency to SOF IPC definitions.
One client is available in Zephyr upstream at:
zephyr/soc/intel/intel_adsp/tools/cavstool.py
Note: winstream backend is not supported by Linux SOF driver.

app: add winconsole_overlay.conf

---

src/audio/volume/volume_generic_with_peakvol.c

Fixed a problem with generic implementation of function vol_passthrough_s16_to_s16.

Audio: Volume: fix problem with generic peakVol

---

scripts/xtensa-build-zephyr.py
zephyr/CMakeLists.txt

3 small LLEXT fixes. Main one:
Reset the llext.uuid file so it does not start with content from the
previous build.
Fixes incremental builds.

zephyr/cmake: fix llext.uuid growing from the last build

---

tools/topology/topology2/development/tplg-targets.cmake

The NHLT binary is not needed in these audio processing development and test topologies. With the current build options the NHLT would work only with cAVS2.5 platforms (TGL). Without NHLT add these are safe to use in all platforms where the NHLT blob is retrieved from BIOS.

Tools: Topology2: Remove unnecessary NHLT binary from EFX topologies

---

scripts/xtensa-build-all.sh

The Kconfig for mt8188 has already been included in #6796, and I have added the toolchains support for mt8188 in #9137.
So I moved mt8188 from the SUPPORTED_PLATFORMS list to the DEFAULT_PLATFORMS list in xtensa-build-all.sh.

scripts: Add support for MediaTek mt8188 platform

---

west.yml

Fast-forward Zephyr by 450+ commits including following patches affecting SOF build targets:
5ca3bc92c8e0 intel_adsp: power: SoC restores the clock
4c5ee9b2dbc5 pm: system: Restore clock after sleep
1860dd9153c7 pm: system: Resume devices in pm_system_resume
f7437ac3b1a3 pm: Move z_pm_save_idle_exit to pm subsys
f54232e9124d intel_adsp/ace: power: Do not re-implement cache func
693b65583c88 power_domain: intel_adsp: Use register definitions
b496d0e52d3c intel_adsp/ace: pm: Remove unnecessary cache flush
c335cb542c24 intel_adsp/ace: pm: Keep irq locked until restore context
e728adffd276 intel_adsp/ace: pm: Remove unnecessary cache flush
301055dec086 intel-adsp/ace: pm: Only core 0 can d0i3
991b3623b014 soc: intel_adsp: ipc: don't call k_sem_init() multiple times
369a3a167584 soc: intel: …

west.yml: update Zephyr to 69d790b29331 (May 27th)

---

zephyr/CMakeLists.txt

Everywhere, where IPC3 and IPC4 are distinguished in CMakeLists.txt the only difference is the use of x_ipc3.c vs. x_ipc4.c. Instead of duplicating all build instructions for IPC3 and IPC4 just define and use a suffix variable.

ipc: simplify CMakeLists.txt by using a suffix variable

---

scripts/xtensa-build-zephyr.py
west.yml
zephyr/CMakeLists.txt

Update Zephyr baseline to 53ddff639562 . The location of generated headers has changed, so modify the SOF build scripts to use the new location.
Change affecting SOF build targets:
6509b8199b02 shell: add shell backend for audio DSP using shared memory window
5a7600bec60b soc: intel_adsp: tools: add shell support to cavstool.py
db00b813f043 soc: intel_adsp: tools: align code style in maps_regs()
44dd5a4da9c0 soc: intel_adsp: tools: fix ace20 fw load flow
fa798ce2d5be soc: intel_adsp: only implement FW_STATUS boot protocol for cavs
8fc76f1b6d16 soc: intel_adsp: tools: improve FW boot handling on ace1.x
024bd41efb65 llext: xtensa: add support for the xt-clang toolchain

west.ytml: update to Zephyr 53ddff639562 (May 31st)

---

src/audio/eq_iir/eq_iir.c
src/audio/mixin_mixout/mixin_mixout.c
src/include/sof/lib_manager.h
src/library_manager/llext_manager.c

Cleanly separate LLEXT code and data segments, handle .bss together with .data. Using Zephyr's automatic section grouping, based on feature flags.

LLEXT: clean data and code segmentation

---

src/audio/rtnr/rtnr.c
src/include/sof/audio/module_adapter/module/generic.h
src/platform/mt8195/include/platform/lib/memory.h

Minor changes needed for working Mediatek builds

Misc mt8xxx-related fixups

---

tools/testbench/common_test.c

The load of MFCC fails with testbench due to missing call of sys_comp_module_mfcc_interface_init() in common_test.c testbench initialize.

Tools: Testbench: Fix load of MFCC component

---

tools/topology/topology2/cavs-benchmark-hda.conf

The rate_min/rate_max is obsolete, should use rates with list of rates to support. Without this change the playback of non-48 kHz content happens with 48 kHz rate with pitch shift effect. Aplay shows only a warning.

Tools: Topology2: Use rates instead of rate_min/max in benchmark

---

tools/topology/topology2/include/common/pcm_caps.conf

HDA host DMA has limitation on the number of BDL entries which translates to number of periods, this limit is 256.
The Chrome ALSA compliance test is eagerly try to use as many periods as it can which exceeds the BDL limit and the stream cannot be started.
Fixes: b3a6d1c5708e ("topology2: common: pcm_caps: Increase periods_max from 16 to 1024")

topology2: common: pcm_caps: Change the periods_max from 1024 to 256

---

src/audio/volume/volume_hifi3_with_peakvol.c
src/audio/volume/volume_hifi4_with_peakvol.c

HIFI4 has been disabled. HIFI3 is being used for
the volume component with peakVol.
There was a problem with test
test_01_09_peakvol_quality[44100Hz_16in16bit_1ch-0].
The main problem was with frequencies: 11025,
22050, 44100, 88200, 176400 Hz.
Because frame is different for these frequencies. For f=44100Hz
frame is equal 44 or 45. Some of the samples were simply not processed.
Changes to HIFI4 are not-trivial and failed to fix the problem.
However, HIFI3 is fully compatible and works properly.
Performance is worse by 1-2,5% in CPU cycle usage
but no glitches appear and all samples are processed correctly.
Signed-off-by: Grzegorz Bernat <grzegorzx.bernat@intel.com>

audio: volume: disable HIFI4 optimizations

---

src/platform/intel/ace/platform.c
zephyr/lib/cpu.c

PTL has CONFIG_PM disabled. SOF should still build without this configuration flag. This patch fixes the compilation issue.

intel_adsp: ptl: Fix SOF compilation without PM

---

west.yml

Update Zephyr to point to SOF Zephyr clone but do not change the commit yet.

[stable-v2.10] west.yml: update Zephyr to stable-v2.10

---

src/audio/volume/volume_hifi3_with_peakvol.c
src/audio/volume/volume_hifi4_with_peakvol.c

HIFI4 has been disabled. HIFI3 is being used for
the volume component with peakVol.
There was a problem with test
test_01_09_peakvol_quality[44100Hz_16in16bit_1ch-0]. The main problem was with frequencies: 11025,
22050, 44100, 88200, 176400 Hz.
Because frame is different for these frequencies. For f=44100Hz frame is equal 44 or 45. Some of the samples were simply not processed.
Changes to HIFI4 are not-trivial and failed to fix the problem. However, HIFI3 is fully compatible and works properly. Performance is worse by 1-2,5% in CPU cycle usage
but no glitches appear and all samples are processed correctly.
(cherry picked from commit 87571f337c10ddd87663f3c75dc0cfaf6b932f0e)

[stable-2.10] audio: volume: disable HIFI4 optimizations

---

tools/plugin/README.md

Fix the tplg name to match the actual name used in example.

tools: plugin: README: remove reference to tgl-nocodec

---

src/audio/base_fw_intel.c
src/audio/dai-zephyr.c
src/include/ipc4/base_fw.h
west.yml

Regarding to https://github.com/zephyrproject-rtos/zephyr/pull/74030 there is necessary to pass properly v_index value.
In addition, PTL has a new version of the IPC4 blob, which will be configured in the TLV information
Necessary zephyr changes:
This PR also changes the **West version** to be consistent with the changes from PR 74030

src: base_fw: adjust ssp copier init flow for ptl (with Zephyr update)

---

tools/topology/topology2/cavs-mixin-mixout-efx-hda.conf

The controls names for IIR, FIR need to be same as in sof-hda-generic for UCM to find the controls and set up the components for processing.

Tools: Topology2: Update sof-hda-efx-generic controls names

---

west.yml

Fast-forward the Zephyr version with two fixes:
0f7a01d360ed drivers: dma: intel_adsp_hda: change L1 exit defaults
8f9384c0fe69 Revert "soc: intel_adsp: only implement FW_STATUS boot protocol for cavs"

[stable-v2.10] west.yml: update Zephyr to sof/stable-v2.10 0f7a01d360e

---

src/audio/module_adapter/module/generic.c
src/audio/pipeline/pipeline-schedule.c
src/include/sof/schedule/dp_schedule.h
src/schedule/zephyr_dp_schedule.c
tools/plugin/alsaplug/tplg.c

Backport following fixes from SOF main:
1e0a9c2338cf dp: wait till dp thread stops in thread cancel
fe06ef7c32b6 tools: plugin: tplg: Fix a couple of memory leaks

[stable-v2.10] backport bugfixes PR9055 and PR9136

---

tools/topology/topology2/cavs-mixin-mixout-efx-hda.conf

The controls names for IIR, FIR need to be same as in sof-hda-generic for UCM to find the controls and set up the components for processing.
(cherry picked from commit 3da8e6474531411bef64819113a29a7edbd51fcf)

[stable-v2.10] Tools: Topology2: Update sof-hda-efx-generic controls names

---

src/audio/google/Kconfig
src/audio/google/google_rtc_audio_processing.c
src/audio/google/google_rtc_audio_processing_mock.c
src/include/ipc4/aec.h

This is almost exactly the code as it stands in PR #8571, but rebased on top of current main (which descends from mtl-008-drop-stable) and with as many individual changes split out as I could.  Basically this unbreaks AEC for IPC3 targets (mt8195 in particular) with a unified implementation, supports dynamic stream sample formats, improves performance and code size significantly, and removes a few hundred lines of duplicated/unparametrized code.   Tested on mt8195 and MTL, will pull out a ADL board and try that as soon as I get a chance.
See individual patch commit messages for more details.

Google AEC rework: dynamic formats, legacy platform support

---

src/audio/buffer.c
src/audio/dai-zephyr.c
src/audio/host-zephyr.c
src/include/sof/audio/buffer.h

For the needs of deep buffering, a new functions `buffer_alloc_range` and `buffer_set_size_range` have been added that allocate a buffer with a size given as a range. The suggested buffer size coming from ipc doesn't have to be met if there is not enough memory. It is then reduced step by step until it reaches its minimum size. These functions were used in dai and host.

zephyr: buffer: host: dai: Introduction of functions that allocate a buffer from a range

---

src/audio/copier/copier_dai.c

Enable support for HDA DMA on SoundWire interface for ACE_VERSION > ACE_VERSION_1_5

copier: dai: fix sndw init flow

---

src/audio/tdfb/tdfb_direction.c
src/include/sof/math/numbers.h

This commit optimizes the division by the speed of sound in the `theoretical_time_differences` function. By precomputing the fixed-point reciprocal of the speed of sound, we eliminate the need for a costly division operation in each iteration.

Audio: Optimize division by speed of sound using fixed-point reciprocal

---

src/audio/multiband_drc/multiband_drc.c

This check-in improves error handling in the `multiband_drc` component by enabling error logging and returning `-ENOMEM` if memory allocation fails. It replaces asserts with conditional checks to detect and log errors during memory copy operations. Finally, it streamlines the return logic in` multiband_drc_setup` and propagates the `init_coef` error code.

Audio: Improvement of multiband_drc memory allocation error handling.

---

tools/topology/topology1/CMakeLists.txt

Remove BT_OFFLOAD on all Intel RVPs, otherwise we will have a run-time mismatch between kernel and topologies.

topology1: BT_OFFLOAD is only supported on Chromebooks

---

.github/workflows/zephyr.yml
scripts/xtensa-build-zephyr.py

As reported in #9262, this fixes the --all option.
Fixes commit https://github.com/thesofproject/sof/commit/05bfc36dacbd1afe55b1e8d73b978713a5f7abfc ("ptl: Add initial PTL configuration")

[SKIP SOF-TEST] xtensa-build-zephyr.py: move PTL out of "all" and into "extra".

---

west.yml

Update Zephyr baseline to 650227d8c47f
Change affecting SOF build targets:
32d05d360b93 intel_adsp/ace: power: fix firmware panic on MTL
a3835041bd36 intel_adsp/ace: power: Use MMU reinit API on core context restore
a983a5e399fd dts: xtensa: intel: Remove non-existent power domains from ACE30 PTL DTS
a2eada74c663 dts: xtensa: intel: Remove ALH nodes from ACE 3.0 PTL DTS
442e697a8ff7 dts: xtensa: intel: Reorder power domains by bit position in ACE30
d1b5d7092e5a intel_adsp: ace30: Correct power control register bitfield definitions
31c96cf3957b xtensa: check stack boundaries during backtrace
5b84bb4f4a55 xtensa: check stack frame pointer before dumping registers
cb9f8b1019f1 xtensa: separate FATAL EXCEPTION printout into two
e9c23274afa2 Revert "soc: intel_adsp: only implement FW_STATUS …

west.ytml: update to Zephyr 650227d8c47f (July 3rd)

---

src/audio/base_fw_intel.c

There was a problem with test test_102_08_extended_time_check. The structure ext_system_time_data was sending with wrong size. Because of this it was not possible to correctly read the value from the art clock to determine the HH counter.

audio: base_fw_intel: Fix problem with send structure ext_system_time_data

---

scripts/fuzz.sh
src/platform/posix/fuzz.c

The older native_posix board is being deprecated, use native_sim, which is the future-proof API.  In theory this should be as simple as just swapping the board name at the west level, but there are a few changes:
The C API is broadly identical between the two, modulo some prefix renaming.
Unfortunately linkage is more of a hassle, as the fuzzing framework inverts the sense of "entry point" and causes some trouble with the way native_sim does its two-stage link.  We have to add some hackery:
1. Make sure the fuzz entry point doesn't get dropped during the initial zephyr.elf link, as it calls OS/sim layer and not the reverse.
2. Force it to be a global symbol in the final stage, so it can be seen by the code in libfuzzer that needs to call it (normally all Zephyr-side symbols are forced to …

[SKIP SOF-TEST] platform/posix: Port fuzzer to upstream "native_sim" board

---

src/audio/google/google_rtc_audio_processing.c

Commit 0eb34dbb9214 ("google_aec: Don't allocate giant blobs on the heap") dropped some sparse annotations and exposed warnings with dealing with the cached temporary buffers handed to the AEC code.
Unfortunately the underlying API isn't sparse-aware, so rather than go through the trouble to keep the tags consistent through the new conversion API (which is a little non-trivial syntactically) just to throw it away on entry to the library, force it off at conversion time for simplicity.  Essentially now it's checking that all computation in this module is "uncached", which is fine as long as we don't try to mix conventions.

google_aec: Sparse fixups

---

src/math/numbers.c

Symbols like __udivdi3 aren't available in 64-bit builds, use CONFIG_64BIT to hide them.
This is to test CI so far, should be converted to non-draft after further conflicting LLEXT changes are merged.

[SKIP SOF-TEST] build: use CONFIG_64BIT for symbol exporting

---

zephyr/CMakeLists.txt
zephyr/sof_shell.c

Builds on (and contains all commits of) PRs https://github.com/thesofproject/sof/pull/9133 
#9133 adds the basic shell support and this PR adds SOF custom commands to the shell. Both are draft until the Zephyr side PRs are merged.

zephyr: shell: add initial SOF custom commands

---

src/schedule/zephyr_domain.c

Include the possible domain block time into measurement of the low-latency scheduler thread execution time. The ll timer metrics are typically used for initial system debug and it is very misleading when domain block events are not counted in reported average/max numbers.
Change the timing code to start measurement immediately after domain thread semaphore is taken.

schedule: zephyr_domain: include domain block in ll time tracking

---

src/audio/module_adapter/module/cadence.c

This change improves and standardizes the naming convention of the cadence module during its creation.

cadence: unification of cadence module naming

---

src/ipc/ipc3/helper.c

This is effectively a no-op, but does not look good. It runs the risk of a type divergence when a major ABI update comes. So lets just use the right type in the right place.

ipc3: fix type usage bug

---

src/audio/copier/copier.c
src/audio/copier/copier_generic.c

Setting the source/sink buffers parameters in the copier_update_params function is not sufficient. If a sink buffer is attached during copier operation, the module will not set buffers parameters. Move the buffer parameter configurations to the new copier_bind bind function. Delete the sink buffers configurations from the copier_module_copy function. There is no need to configure sink buffers parameters on each copy. We are assured that they were configured at the time of bind.
Fixes: #9123

copier: Add bind function to configure source/sink buffers params

---

tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/platform/intel/sdw-amp-generic.conf
tools/topology/topology2/platform/intel/sdw-dmic-generic.conf
tools/topology/topology2/platform/intel/sdw-jack-generic.conf
tools/topology/topology2/production/tplg-targets-ace1.cmake

Using S32_LE wastes bandwdith for no good reason, we should use 24 bits on the link to maximize bus efficiency with the 9.6 MHz bus clock.
~~FIXME: it's likely we need a kernel-side change as well to configure the hw_params to S24_LE, currently the stream/port is configured with~~
~~sconfig.bps = snd_pcm_format_width(params_format(params));~~
Link: https://github.com/thesofproject/sof/issues/8960

topology2: force all SoundWire link-side copiers to use S24_LE

---

west.yml

Total of 369 commits.
46b356a6b0e intel-adsp: fix ACE power-off assembly
fb53d2ef8dd ace: power: replace pseudo-assembly movi

west.yml: update zephyr to 740d7f735e2

---

posix/include/sof/lib/dma.h
src/audio/Kconfig
src/audio/copier/copier.c
src/audio/copier/copier.h
src/audio/copier/copier_dai.c
src/audio/copier/copier_generic.c
src/audio/copier/copier_host.c
src/audio/copier/copier_ipcgtw.c
src/audio/copier/dai_copier.h
src/audio/dai-legacy.c
src/audio/dai-zephyr.c
src/audio/host-legacy.c
src/audio/host-zephyr.c
src/audio/pcm_converter/CMakeLists.txt
src/audio/pcm_converter/pcm_converter.c
src/audio/pcm_converter/pcm_converter_generic.c
src/audio/pcm_converter/pcm_converter_hifi3.c
src/audio/pcm_converter/pcm_remap.c
src/include/module/ipc/stream.h
src/include/sof/audio/pcm_converter.h
src/include/sof/lib/dai-zephyr.h
src/lib/dma.c
test/cmocka/src/audio/pcm_converter/pcm_float.c
xtos/include/sof/lib/dma.h
zephyr/CMakeLists.txt

Adds a device posture feature. The driver sends IPC4_COPIER_MODULE_CFG_PARAM_CHANNEL_MAP with a channel map to be used for swapping channels according to the device orientation.
IPC4_COPIER_MODULE_CFG_PARAM_CHANNEL_MAP is applied only for the DAI gateway.

Add device posture feature

---

app/boards/intel_adsp_ace15_mtpm.conf

Temporarily disable CONFIG_MODULES to get MTL working again.
Avoids crash https://github.com/thesofproject/sof/issues/9308

intel_adsp_ace15_mtpm.conf: temporarily disable CONFIG_MODULES

---

tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/platform/intel/ptl.conf
tools/topology/topology2/production/CMakeLists.txt
tools/topology/topology2/production/tplg-targets-ace3.cmake

Start moving SoundWire topologies from the shadows into main...

topology2: add basic definitions for PTL

---

west.yml

Total of 391 commits.
44464c4d4fc drivers: dai: intel: ssp: Introduce DMA control set API
5084decbc46 drivers: dai: intel: ssp: Refactor TLV parsing into a separate function
230709e4ae6 include: dai: Introduce runtime DAI configuration update API
1497f77cc89 intel: adsp: make SRAM power-off configurable
293fa118df9 intel: adsp: fix firmware image in IMR overwriting

west.yml: update zephyr to 3bcaa6f8d63

---

posix/include/sof/lib/dma.h
src/audio/dai-zephyr.c
src/lib/dma.c
xtos/include/sof/lib/dma.h

In the case where the copier has more than one output and, additionally, we will be using a pin other than pin 0 (for example, when we want to copy data from pin 1 of a gateway-type copier to the next pipeline), it is necessary to copy data in playback path from the source to the output for all possible sinks.

src: dai-zephyr: copy data to all available sinks

---

src/audio/tdfb/tdfb_direction.c

This check-in refines the TDFB direction calculation, addressing both
performance and correctness:
- **Fixes:**
- Correct infinite loop in `max_mic_distance` by fixing loop conditions.
- **Optimizations:**
- Fix off-by-one error in `line_array_mode_check` ensuring all checks
for co-linearity among microphone locations are performed.

Audio: Optimize and fix TDFB direction calculation

---

tools/topology/topology2/platform/intel/sdw-dmic-generic.conf
tools/topology/topology2/platform/intel/sdw-jack-generic.conf

For some reason we had the EQIIR for topology1/IPC3 but we didn't add it for topology2/IPC4.  All recordings show there's a strong DC offset with RT722 and other codecs, so let's add this component by default in the non-passthrough cases.
FIXME: the instance numbers for eqiir don't look quite right, for some reason we cannot use eqiir.41.0, as if the instance number was global and not in the scope of a pipeline?

topology2: sdw-dmic-generic: add eqiir to control DC offset

---

src/audio/module_adapter/CMakeLists.txt

The CADENCE_CODEC_MP3_ENC option was present in `Kconfig` and handled in `module/cadence.c` but missing from `CMakeLists.txt`.
Changes:
- add the CADENCE_CODEC_MP3_ENC option in `src/audio/module_adapter/CMakeLists.txt`.

src/audio/module_adapter/CMakeLists.txt: add CADENCE_CODEC_MP3_ENC

---

lmdk/README.md
lmdk/cmake/ldscripts/data_linker_script.txt
lmdk/modules/smart_amp_test/CMakeLists.txt
src/samples/audio/smart_amp_test_ipc4.c

* Fix typo in README.md
* Fix compilation error when building smart_amp_test as loadable module using LMDK.
* Fix linker script: specifying 0 address for .module section results in few GB binary file. Instead, put .module section near .text or .rodata.

Few LMDK fixes

---

src/include/sof/ipc/common.h
src/ipc/ipc3/helper.c

We have a few gaps in input validation from the kernel. Right now we check the IPC doesn't claim its larger the window, this patch adds the following checks:
1. That the IPC size is at least large enough for any downcast type on comp new
2. That any reported size for a process total size is less than the IPC window.

ipc3: Add size checks on ipc subtypes

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-hda-generic.m4

Add new pipelines to sof-hda-generic.m4 to support BT audio offload on SSP2 and also add an new topology sof-hda-generic-4ch-bt.tplg with BT audio offload enabled.

[STABLE-v2.2] topology1: sof-hda-generic: support BT offload pipelines

---

smex/CMakeLists.txt
src/arch/xtensa/CMakeLists.txt
tools/plugin/alsaplug/CMakeLists.txt
tools/plugin/modules/CMakeLists.txt
tools/plugin/modules/ov_noise_suppression/CMakeLists.txt
tools/plugin/pipe/CMakeLists.txt

This was discovered while reviewing #9351
See commit messages for details.
It's 2024 and copy/paste/diverge still rulez :-(

Eradicate -Wl,-EL for good

---

west.yml

Total of 553 commits.
2fcdbba534b intel_adsp/ace: power: pad the hpsram_mask passed to power_down
d590c186728 intel_adsp: ace: call soc_num_cpus_init early
c79bbfadbbd xtensa: move arch_kernel_init code into prep_c
dbfbf0edbad xtensa: adapt soc code to use prep_c
42396735bf7 xtensa: introduce prep_c for xtensa
299dddfdce1 xtensa: remove mention of crt0-app.S
ed31037d5fd drivers: ssp: fix program of MLCS register
cbb9613d83b dai: intel/ssp: Use proper flexible array

west.yml: update zephyr to 795ac34f291

---

scripts/cmake/xtensa-toolchain.cmake
scripts/rebuild-testbench.sh
scripts/set_xtensa_params.sh
scripts/xtensa-build-all.sh

As required by ACP_7_0 addition submitted in #9351
Other related cleanups, see commit messages.
Switch rebuild-testbench.sh to new variable.

Add $SOF_CC_BASE variable for building XTOS with clang-based, Cadence toolchains

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-hda-generic.m4

Backport PR https://github.com/thesofproject/sof/pull/9336 cavs2.5-001-drop-stable branch.

[cavs2.5-001] topology1: sof-hda-generic: support BT offload pipelines: backport to cavs2.5-001

---

tools/topology/topology2/platform/intel/dmic-default.conf
tools/topology/topology2/platform/intel/dmic-generic.conf

The NUM_DMICS=4 controls DAI channels count, while recently added DMIC0_PCM_CHANNELS controls host copier channels count. But in most topologies built the DMIC0_PCM_CHANNELS remained in default 2 setting if it was not set in cmake target definitions.
As result the "arecord -c 4" attempt failed e.g. with common sof-hda-generic-4ch.tplg.
Fixes: 88366121b3f50a4fe86675860af9426b8b946240 ("Tools: Topology2:
Add DMIC Enhanced Audio Capture development tplg")

Tools: Topology2: DMIC: Bug fix 4ch host copier channels count

---

Kconfig.sof
src/platform/Kconfig
src/samples/audio/detect_test.c
zephyr/include/rtos/interrupt.h
zephyr/lib/alloc.c

imx93_a55 is an imx platform so it should select `CONFIG_IMX`. As such, make `CONFIG_IMX93_A55` also select `CONFIG_IMX`. Since `CONFIG_IMX` has only been used for xtensa-based imx platforms, make necessary changes for it to also work on arm-based imx platforms (i.e: imx93_a55).

platform: imx93_a55: select `CONFIG_IMX`

---

.github/workflows/build_all.yml
scripts/fuzz.sh

OVERLAY_CONFIG was deprecated in Zephyr 3.4 commit https://github.com/zephyrproject-rtos/zephyr/commits/3a345682ba81
Also enhance example and demonstrate the syntax to pass multiple files.
This finishes the work started by commit 6cd34c89a11b ("xtensa-build-zephyr.py: use EXTRA_CONF_FILE instead of OVERLAY_CONFIG")

[SKIP SOF-TEST] fuzz.sh: replace deprecated OVERLAY_CONFIG with newer EXTRA_CONF_FILE

---

tools/test/audio/src_test.m

The SRC module tools have moved, so the path to retrieve SRC filter spec has changed.

Tools: test: Audio: Fix src_test.m run error

---

src/audio/module_adapter/iadk/system_agent.cpp
src/audio/module_adapter/library/native_system_service.c
src/include/module/module/logger.h
src/include/module/module/system_service.h
src/include/sof/audio/module_adapter/iadk/adsp_stddef.h
src/include/sof/audio/module_adapter/iadk/system_service.h
src/include/sof/audio/module_adapter/library/native_system_agent.h
src/include/sof/audio/module_adapter/library/native_system_service.h

Move logging priority definitions used by iadk modules to the modules directory so other types of loadable modules can use them. Propose a function to convert log priority used by loadable modules to log level used by sof.
Move definitions of functions exposed by system_service to the modules directory so that loadable modules can use them.

Move log and system_service headers to module directory

---

src/include/ipc/topology.h
src/include/kernel/abi.h
src/include/module/ipc4/base-config.h

Normally, the type of enums is "unsigned int" or "int". GCC has the "-fshort-enums" option, which instructs the compiler to use the smallest data type that can hold all the values in the enum (i.e: char, short, int or their unsigned variants).
According to the GCC documentation, "-fshort-enums" may be default on some targets. This seems to be the case for "arm-zephyr-eabi-gcc", which is used to build Zephyr on ARM platforms.
On Linux, this is not the case (tested with "aarch64-linux-gnu-gcc"), which means enums such as "enum sof_comp_type" will end up having different sizes on Linux and SOF. Since "enum sof_comp_type" is used in IPC-related structures such as "struct sof_ipc_comp", this means the fields of the structures will end up being placed at different offsets. This, in turn, leads …

ipc: replace enum fields with uint32_t in some IPC structures

---

src/include/sof/audio/format_hifi3.h

- Updated `sat_int32` to support 64-bit to 32-bit saturation with proper bitwise shifting.
- Added `vec_sat_int32x2` function to saturate and pack two 64-bit integers into `32x2` vector.
- Improved `sat_int24` for 32-bit to 24-bit saturation.
- Added `vec_sat_int24x2` to saturate and pack two 32-bit integers into a `32x2` vector.
- Corrected `sat_int16` to return a single 16-bit saturated integer.
- Added `vec_sat_int16x4` function to saturate and pack four 32-bit integers into `16x4` vector.
- Improved `sat_int8` to properly extract the lower 8 bits of a 32-bit integer.
- Added `vec_sat_int8x2` to pack two 32-bit integers in an `8x2` vector.

Audio Math: Improve audio format saturation functions.

---

src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module_adapter_ipc3.c

cleanup dead code and some typos

Module adapter cleanup

---

src/audio/mfcc/mfcc.c

The comp_err() trace in mfcc_init() causes an error:
sof/src/audio/mfcc/mfcc.c: In function 'mfcc_init': sof/src/include/sof/audio/component.h:160:20:
error: format '%u' expects argument of type 'unsigned int',
but argument 4 has type 'size_t' {aka 'long unsigned int'}
[-Werror=format=]

Audio: MFCC: Fix 64 bit build issue

---

tools/topology/topology2/cavs-nocodec.conf

The rate_min and rate_max no more work with IPC4 topologies. The SSP2 PCM host pipeline contains a sample rate converter so it can support multiple rates. With attempt to play (or capture) with other than 48 kHz the error is printed and resulting playback has wrong pitch:
Warning: rate is not accurate (requested = 44100Hz, got = 48000Hz)
please, try the plug plugin
Use of rates with list of all rates in topology fixes the issue.

Tools: Topology2: Fix cavs-nocodec.conf SSP2 PCM rates

---

src/audio/smart_amp/smart_amp.c
src/include/sof/audio/smart_amp/smart_amp.h

If 0 is a error then override it so the outer function doesn't think we ran successfully and then hit a null ptr after we freed everything.

smart_amp: fix return errors

---

zephyr/CMakeLists.txt

zephyr: don't build host targets with xtos headers

---

src/audio/dai-zephyr.c
src/audio/host-zephyr.c

The comp_* macros will print the function name from where they are called,
there is no need to print them twice.
The context-less 'nothing to copy' print does not give much help to understand _why_ we are not copying.

src: dai-/host-zephyr: Drop the duplicated function name print and print the src/sink frames when there is nothing to copy on dai side

---

src/audio/crossover/crossover_generic.c

Optimize `crossover_s32_default` by pre-determining the active sinks before processing frames. This check-in reduces redundant null checks for each frame and channel, leading to performance improvements in processing audio streams with multiple sinks.

Audio: Optimize sink checks in crossover_s32_default

---

src/include/ipc/header.h

The testbench and unit tests use a simplified simulated IPC that currently doesn't support messages split to multiple parts. As workaround to unblock other SOF development the size is increased from 384 bytes to 8192 bytes.
This allows run of current test set with scripts/host-testbench.sh that is also used in SOF CI. The change can be reverted after the capability is added to testbench.

IPC: Increase SOF_IPC_MSG_MAX_SIZE for testbench and unit test

---

tools/test/audio/comp_run.sh
tools/test/audio/process_test.m

The verbose test trace flood slows down the test to near unusable test times due to a lot of text printed to Octave console. As result also the SOF CI logs become large.
This patch adds redirect of testbench trace into a temporary file instead of standard output in process_test.m. The trace content is printed in comp_run.sh to console only if there has been an error. To prevent growing /tmp the trace file is deleted after test run and possible print to console.

Tools: Test: Audio: Mitigate trace flood in process_test.m

---

tools/topology/topology2/cavs-passthrough-hda.conf
tools/topology/topology2/development/tplg-targets.cmake
tools/topology/topology2/sof-hda-generic.conf

Reviving an old branch I had in 2023 to test LNL, this PR adds support for ultra-simple pipelines for the HDA codec and the option to use the CHAIN_DMA for minimal firmware involvement.
When I tried last year, the CHAIN_DMA capture didn't work, let's see if this is still a problem

topology2: hda: add passthrough option as well as CHAIN_DMA

---

src/ipc/ipc3/helper.c

I missed a case where the process size should be less than the ext size. Fuzzer found the loophole and had some fun.

ipc3: add subsize check

---

src/audio/module_adapter/module_adapter_ipc3.c

This switch case is non exhaustive and has not guards on config types which means assuming all types that are default are process types is false. The fuzzer found a way to utilize a DAI to bypass IPC layer checks but break the module adapter.

module_adapter: fix switch case for spec parsing

---

CODEOWNERS

New assignment, need to silence notifications.

[SKIP SOF-TEST] CODEOWNERS: remove marc-hb

---

tools/rimage/config/lnl.toml.h
tools/rimage/config/mtl.toml.h
tools/rimage/config/ptl.toml.h

The MFCC component is not loading in these platforms due to missing edit to <platform>.toml.h.
As editorial change the missing newline in the end of ptl.toml.h is fixed.
Fixes: f7715b814b66
("Audio: MFCC: Fix build of component for current SOF")

Tools: Rimage: Config: Add mfcc.toml include for MTL, LNL, PTL

---

src/audio/volume/volume_hifi3_with_peakvol.c
src/audio/volume/volume_hifi4.c
src/audio/volume/volume_hifi4_with_peakvol.c

This patch fixes an issue with gain and peakvolume processing with s16 sample format and with sample rates where period is not multiple of four samples SIMD processing assumption. With 44.1 kHz rate the period is normally 44 frames but every 10th is 45. However, the value of 45 was not handled correctly. A Glitch appeared to output when this happened.
The fixed code adds sample-by-sample volume process code for the remaining amount of up to 3 samples to process.
The earlier workaround (87571f337c10 "audio: volume: disable HIFI4 optimizations") is reverted.

Audio: Volume: Fix problem with Hifi4

---

tools/plugin/modules/ov_noise_suppression/noise_suppression.c

Recent changes to UUID naming dropped the _comp in the UUID declaration. Fix the noise suppression module to adhere to the new naming while declaring the module interface and trace.

tools: plugin: noise_suppression: Fix build error

---

.github/workflows/build_all.yml
.github/workflows/ipc_fuzzer.yml
app/configs/fuzz_IPC3_features.conf
app/configs/fuzz_IPC4_features.conf
app/configs/fuzz_features.conf
scripts/fuzz.sh

3 commits, see messages.
The goal of these new files is to:
1. Fuzz more code
2. Reduce the configuration gap between fuzzed SOF and the real thing.
cc:
- #9386

[SKIP SOF-TEST] Add new -i3/-i4 flags + fuzz_*features.conf files to add more CONFIG_ when fuzzing 

---

west.yml

Total of 191 commits, including following affecting SOF build targets:
81977f2bff2e drivers: dma: intel_adsp_hda: fix intel_adsp_hda_unused() check
9fd2e119445e drivers: dma: intel-adsp-hda: Report total_copied bytes on ACE2/3
dd50ff558537 llext: add dependencies
c5e305fce6c4 llext: fix flag evaluation for section grouping
a8db637ead17 llext: export a symbol needed for immediate logging
fe609dd8e8e1 llext: look for symbols in other LLEXT objects too
19ccec6a0390 llext: use EXPORT_SYMBOL() universally
bd09a5c73921 llext: make EXPORT_SYMBOL() universal
92a7c772d90b llext: remove an unused variable
4902f189ae00 dts: xtensa: intel_adsp: Set soft-off state as disabled
b9a4900c3002 drivers: dma: intel_adsp_hda: change L1 exit defaults

west.yml: update Zephyr to 689d1edee1d5

---

src/ipc/ipc3/handler.c
src/ipc/ipc3/helper.c

UBSAN fuzzing fixes

---

src/arch/xtensa/include/xtensa/config/core.h

xt-clang uses UINT32_C() without importing it.  Commit ef38a0c2654e ("arch: xtensa: core.h: Add define for UINT32_C") added it but only for `__ZEPHYR__`, add it unconditionally.
Provide an alternative, assembly-compatible definition apparently needed by XTOS ACP 7.0 compiled with xt-clang.
For C code, simply include <stdint.h>
Longer and convoluted story in #9413.

xtensa/config/core.h: provide UINT32_C() not just for __ZEPHYR__

---

src/Kconfig
src/debug/debug_stream/CMakeLists.txt
src/debug/debug_stream/Kconfig
src/debug/debug_stream/debug_stream_slot.c
src/debug/debug_stream/debug_stream_thread_info.c
src/include/user/debug_stream.h
src/include/user/debug_stream_slot.h
src/include/user/debug_stream_thread_info.h
tools/debug_stream/debug_stream.py
zephyr/CMakeLists.txt

This PR contains following things:
- debug-stream definitions
- implementation for transporting the debug-stream records over debug window slot
- thread info implementation
- extracts per thread stack and cpu usage statistics from Zephyr core
- sends the statistics as debug-stream records
- python script for receiving the debug-stream records over debug window slot transport and decoding them to human readable form
This PR requires following PR to compile (if the feature is enabled in Kconfig):
https://github.com/zephyrproject-rtos/zephyr/pull/77467
and following PR to work (for python script to access the debug window slot):
https://github.com/thesofproject/linux/pull/5154
and this fix to be able to disable tlemetry performance measurements, that tries to use the same debug-window slot …

Debug stream thread info pr

---

src/audio/base_fw.c
src/audio/base_fw_intel.c
src/include/ipc4/base_fw_vendor.h
src/include/sof/lib/dai-zephyr.h
src/lib/dai.c

This pull request introduces a handling of IPC4_DMA_CONTROL messages for the SSP DAI driver. 
Below is a summary of the commits included in this pull request:
- 64ce0b9b31b91b17f63cd435cc11d93fd3be28be Exposes the function to retrieve Zephyr DAI device structures, allowing other parts of the SOF codebase to access Zephyr native DAI drivers.
- 3801123335de58e0f5f2782f66beeffded1323c6: Implements handling for the IPC4_DMA_CONTROL message within the base firmware.
TODO before merge:

basefw: Add handling of IPC4_DMA_CONTROL messages

---

src/library_manager/lib_manager.c
src/library_manager/llext_manager.c

MOD_INIT_INSTANCE IPCs can be processed on different cores, different cores can use the same modules. Make shared data uncached.

llext: fix multi-core use cases

---

.github/workflows/zephyr.yml
scripts/xtensa-build-zephyr.py

With addition of loadable modules, SOF firmware installation depends much more on symbolic links. Add a step to build script to create a tarball of the installed firmware binaries in the build-staging-sof tree. The created tarball (build-sof-staging/sof/sof.tar.gz) provides a ready structure that can be unpacked to e.g. /lib/firmware on Linux target machines.

xtensa-build-zephyr.py: create /lib/firmware tarball

---

app/boards/native_sim_libfuzzer.conf
app/configs/fuzz_asan.conf
scripts/fuzz.sh

Allows for switching out zephyr configs for other sanitizers

[SKIP SOF-TEST] fuzz: add argument to support other sanitizers

---

src/audio/module_adapter/module_adapter_ipc3.c

Add mixer component in module_adapter initialization function otherwise, for IPC3, we get the following error:
"module_adapter_init_data() unsupported comp type 6".
Fixes: 0f4a246df10d ("module_adapter: fix switch case for spec parsing")

module_adapter: add mixer component for initialization

---

tools/topology/topology2/production/tplg-targets-ace1.cmake
tools/topology/topology2/production/tplg-targets-ace2.cmake
tools/topology/topology2/production/tplg-targets-cavs25.cmake

SoundWire#
├── link 0: cs42l43 Audio Jack and DMICs/Bridge to amplifiers.
|  |     -> sof-rpl-cs42l43-l0.tplg
│ │     -> sof-mtl-cs42l43-l0.tplg
│ │     -> sof-arl-cs42l43-l0.tplg
│ │     -> sof-lnl-cs42l43-l0.tplg
│ │
│ ├── link 2: cs35l56 Left and Right Amplifier.
│	            -> sof-arl-cs42l43-l0-cs35l56-l2.tplg
│
├──── link 2: cs35l56 Right/Rightx2 Amplifier.
├──── link 3: cs35l56 Left/Leftx2 Amplifier.
-> sof-adl-cs42l43-l0-cs35l56-l23.tplg
-> sof-arl-cs42l43-l0-cs35l56-l23.tplg
-> sof-lnl-cs42l43-l0-cs35l56-l23.tplg
SoundWire#
├── link 2: cs42l43 Audio Jack and DMICs.
│       -> sof-arl-cs42l43-l2.tplg
│ 
├──── link 3: cs35l56 Left and Right Amplifier.
-> sof-arl-cs42l43-l2-cs35l56-l3.tplg

topology2: cavs-sdw: Add cs42l43 and cs35l56 support on ADL/RPL, MTL/ARL, LNL

---

src/audio/igo_nr/igo_nr.c

When using sink/src API and DP processing, there are no comp_buffer based buffers on inputs and outputs
There must not be any usage of comp_buffer in the module
this commit changes a forgotten reference to comp_buffer

fix: remove reference to comp_buffer form sink/src based mod

---

src/platform/intel/ace/include/ace/lib/memory.h

Platforms that can only be built with Zephyr, can directly use Zephyr cached/uncached functions in memory.h. It turns out the SRAM address and size definitions were only needed for these duplicate cache operations, so they can be removed as well.
Related to https://github.com/thesofproject/sof/issues/9015

platform: intel: ace: remove redundant definitions from memory.h

---

src/platform/posix/include/platform/lib/memory.h
src/platform/posix/posix.c

Using unaligned mailboxes with UBSAN causes fuzzing failures with aligned data structures

posix: align mailboxes

---

xtos/include/sof/lib/dai.h
zephyr/include/sof/lib/dai.h

Implement sof/lib/dai.h for Zephyr build and do not rely o the xtos version for Zephyr builds. Add a warning to catch invalid build configurations.

rtos: add Zephyr implementation of sof/lib/dai.h

---

app/configs/fuzz_ubsan.conf
scripts/fuzz.sh

This PR adds support for undefined fuzzing in SOF.
This is blocked by 2 PRs. One to oss-fuzz to add undefined to the supported manifest. The second is https://github.com/zephyrproject-rtos/zephyr/pull/77963 which blocks the fuzzer currently.

fuzzer: add ubsan support

---

tools/topology/topology2/cavs-mixin-mixout-hda.conf
tools/topology/topology2/production/tplg-targets-hda-generic.cmake

This patch adds to DMIC0 capture TDFB beamformer and DRC for dynamic range control. The impacted topology names are:
- sof-hda-generic-2ch.tplg
- sof-hda-generic-4ch.tplg
- sof-hda-generic-cavs25-2ch.tplg
- sof-hda-generic-cavs25-4ch.tplg
- sof-hda-generic-ace1-2ch.tplg
- sof-hda-generic-ace2-2ch.tplg
The DMIC0 capture pipelines before this patch was:
DAI-copier -> IIR -> gain -> module copier -> host-copier
After:
DAI-copier -> IIR -> gain -> module copier ->
TDFB -> DRC -> host-copier
The beamformer is set for 2ch topologies to a narrow user direction stereo image enhance with about 3 dB signal-to-noise ratio improvement with blob "line2_generic_pm10deg.conf". In 4ch topologies the beamformer is set to pass-through due to large variations in notebook array geometries. The processing …

Tools: Topology2: Enable DMIC capture pre-processing for hda-generic

---

src/ipc/ipc3/helper.c

Sizes are not currently checked for alignment, this can generated unaligned pointers for aligned types which is undefined behaviour.

ipc3: check alignment of ext data

---

src/debug/debug_stream/debug_stream_slot.c
src/debug/debug_stream/debug_stream_thread_info.c
src/include/user/debug_stream_slot.h

Couple of loose ends that were left from hasty merging to 2.11.

Debug stream thread info fixe. Should be backported for 2.11

---

.github/workflows/zephyr.yml

Zephyr commit b3b8360f3993 ("west: runners: Add `west rtt` command with pyocd implementation") adds some functionality to the west commands making use of the pipe ("|") operator for function return type hinting. As per PEP 604 [1], this operator can be used for writing union types starting from python 3.10. Since the SOF windows builds use python 3.8 this leads to the CI failing.
To fix this, switch to using python 3.10. This is not a problem for Linux CI jobs as they already use python 3.10.
The following is a snippet of a failed windows CI job regarding this:
File "D:\a\sof\sof\workspace\zephyr\scripts/west_commands\runners\core.py", line 780, in ZephyrBinaryRunner
def get_rtt_address(self) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[1]: …

.github/zephyr: switch to python 3.10 on windows

---

src/audio/module_adapter/module_adapter_ipc3.c
src/include/ipc/topology.h
src/include/sof/audio/ipc-config.h
src/ipc/ipc3/helper.c
tools/testbench/common_test.c
tools/testbench/file.c
tools/testbench/include/testbench/common_test.h
tools/testbench/include/testbench/file.h
tools/testbench/testbench.c
tools/testbench/topology.c

This is done as preparation for testbench IPC4 support. The update to IPC4 is simpler for a module adapter component.

Tools: Testbench: Convert file component to module adapter

---

src/audio/volume/volume.c
src/audio/volume/volume_ipc4.c

This patch avoids garbage values to be sent to mailbox by peak_vol_update() as very first peak volume measurement in stream start. The data structures cd->peak_vol and cd->peak_regs.peak_meter were not cleared.

Audio: Volume: Clear peak meter channel max values in prepare()

---

src/audio/module_adapter/iadk/system_agent.cpp
src/audio/module_adapter/module/modules.c
src/include/sof/audio/module_adapter/iadk/api_version.h
src/include/sof/audio/module_adapter/iadk/iadk_module_adapter.h
src/include/sof/audio/module_adapter/iadk/system_agent.h

Add a definition specifying the size of space reserved in module memory for module handle and a iadk adapter.
Add a brief description of the iadk module loading sequence.
Change the definition of the system_agent_start function so that it returns the error code returned by the module's entry point functions. Return the created IadkModuleAdapter object via a parameter.

iadk: Define pass buffer size and return error code from entry point function

---

zephyr/include/rtos/mutex.h

The RTOS layer should provide the same interface for all OS'es. Currently rtos/mutex.h is only defined for XTOS. Add rtos/mutex.h also for Zephyr to allow generic SOF code to use this interface.

zephyr: add rtos/mutex.h

---

xtos/include/sof/lib/mm_heap.h
zephyr/CMakeLists.txt
zephyr/include/sof/lib/mm_heap.h

Definitions of mm_heap.h interface are not needed in Zephyr builds. To avoid pulling in XTOS definitions when building with CONFIG_SOF_ZEPHYR_STRICT_HEADERS=n, add a no-op version for Zephyr.

zephyr: sof/lib/mm_heap.h added Zephyr version

---

zephyr/include/sof/compiler_attributes.h

Introduce a separate file for Zephyr compiler_attributes.h and move all Zephyr-specific definitions to this file. This is a prerequisite to build with CONFIG_SOF_ZEPHYR_STRICT_HEADERS=y.

rtos: branch compiler_attributes.h for XTOS and Zephyr

---

src/debug/debug_stream/debug_stream_slot.c
src/debug/debug_stream/debug_stream_thread_info.c

Couple of compile warning fixes.

Debug stream thread info compile warning fixes

---

west.yml

Update Zephyr to include f94427deecf0 ("Intel: ADSP: move HPSRAM mask into assembly").

zephyr: update to today's "main"

---

src/include/sof/trace/trace.h
zephyr/wrapper.c

This series removes the need to add ".trace_ctx" and ".static_log_entries" linker sections for Zephyr platforms not using trace.

smex and trace sections cleanup

---

CODEOWNERS

People typically don't git branch like software does. It may actually happen in some projects but not in SOF AFAIK so let's stop spamming people who left - especially myself :-)
This makes the CODEOWNERS file almost identical to the one in the main branch, see below.
This means a few patterns that don't match anything in this branch are getting added - who cares.
This was performed with the usual "brute force" forklift method...
```
git rev-list  origin/main ^HEAD -- CODEOWNERS | tac | git cherry-pick -x --stdin
```
... + skipping platform removals and fixing a couple git conflicts.
----------
`git diff origin/main -- CODEOWNERS`
```diff
--- a/CODEOWNERS
+++ b/CODEOWNERS
@@ -48,6 +48,8 @@ src/audio/module_adapter/*            @ranj063 @jxstelter
src/audio/google/* …
```

[SKIP SOF-TEST] [stable-v2.2] sync CODEOWNERS with main branch

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/platform/intel/jsl-rt1015.m4
tools/topology/topology1/sof-jsl-rt5682.m4

After topology1 was removed from main branch, some topology changes to JSL boards only commits to jsl-005-drop-stable. In this PR we cherry-pick those commits to stable-v2.2 branch.
This PR impacts following topology files:
1. sof-jsl-rt5650.tplg
=> new topology
2. sof-jsl-rt5682.tplg
4. sof-jsl-rt5682-max98360a.tplg
5. sof-jsl-rt5682-rt1015.tplg
6. sof-jsl-rt5682.-rt1015.tplg
=> ALC5682's SOF_TKN_INTEL_SSP_CLKS_CONTROL token value changes from SSP_CC_BCLK_ES to SSP_CC_MCLK_AON since BCLK_ES flag is for CS42L42 and MCLK_AON is for ALC5682.

[stable-v2.2] Missing topologies commits from jsl 005

---

zephyr/lib/cpu.c

Zephyr's device power management framework offers two methods for reducing power consumption: Device Runtime Power Management and System-Managed Device Power Management. These methods allow devices to be suspended when idle, either independently or as part of system power state transitions. The framework is designed to minimize power usage with minimal intervention from applications, relying on device drivers to manage the power state transitions of their devices.
The SOF firmware uses Zephyr's Device Runtime Power Management for DAIs, where the device driver is responsible for indicating the active or idle state of the device. However, during system-wide power state transitions such as D3 entry and exit, explicit power state management is necessary to maintain audio data integrity and …

zephyr: cpu: Suspend and resume DAIs during D3 state transitions

---

scripts/xtensa-build-zephyr.py
versions.json

Backport https://github.com/thesofproject/sof/pull/9509 plus bump version to 2.11.1

[stable-v2.11] rimage: use platform extra flags when signing LLEXT modules

---

src/ipc/ipc3/helper.c

A bad IPC can mismatch UUID and type, causing downstream processes to operate differently than the final component target. This is because get_drv will not reject the mismatch and given we don't know the state of topology we can't start now. Instead we can override the ipc with the proper type.

ipc3: override type field once comp_driver found

---

scripts/xtensa-build-zephyr.py

The user can configure west to pass additional arguments to rimage for signing, we need to use them when signing LLEXT modules too.

rimage: use platform extra flags when signing LLEXT modules

---

app/shell_overlay.conf
app/winconsole_overlay.conf

Workaround for https://github.com/thesofproject/sof/issues/9513

app: shell/winconsole_overlay: disable SOF telemetry

---

src/audio/buffers/comp_buffer.c
src/audio/buffers/ring_buffer.c
src/audio/copier/copier.c
src/audio/copier/copier_dai.c
src/audio/copier/copier_generic.c
src/audio/dai-zephyr.c
src/audio/google/google_rtc_audio_processing.c
src/audio/mux/mux_ipc4.c
src/audio/pipeline/pipeline-graph.c
src/audio/pipeline/pipeline-params.c
src/audio/selector/selector.c
src/include/ipc/stream.h
src/include/module/audio/audio_stream.h
src/include/module/ipc/stream.h
src/include/sof/audio/audio_buffer.h
src/include/sof/audio/buffer.h
src/include/sof/audio/component.h
src/include/sof/audio/ring_buffer.h
src/ipc/ipc-helper.c
src/ipc/ipc4/helper.c

This PR moves many of parameters that are common for all buffers to struct sof_audio_buffer
there are 4 left:
```
struct comp_dev *source;	/* source component */
struct comp_dev *sink;		/* sink component */
/* lists */
struct list_item source_list;	/* list in comp buffers */
struct list_item sink_list;	/* list in comp buffers */
```
and will be moved to sof_audio_buffer in next PR

Pipeline2.0: low hanging fruits - move buffers' common params to struct sof_audio_buffer.

---

tools/demo-gui/README-dev.md
tools/demo-gui/README.md
tools/demo-gui/demo-gui/sof_controller_engine.py
tools/demo-gui/demo-gui/sof_demo_gui.py
tools/demo-gui/demo-gui/sof_demo_tui.py
tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof/pipe-gui-components-capture.m4
tools/topology/topology1/sof/pipe-gui-components-playback.m4

Implements a gui and tui that can be used to easily demonstrate SOF on target HW. See README and README-dev for more information on functionality and purpose.
See https://github.com/thesofproject/sof/issues/9223 for the initial description of the project and overall scope. Most features from that description were met here.
One important goal before this PR is ready to be merged is for this to be tested on a variety of platforms. At this point, the GUI is tested on most NXP platforms, but little other testing has been done yet. Please feel free to comment with any issues that are had on any platform, and I'll work on resolving them ASAP.
A second focus is on understandability of the docs, please let me know if any sections are unclear. A large goal of this project is to allow for new …

SOF_GUI: Implement GUI and TUI for SOF demonstration

---

src/include/sof/lib/perf_cnt.h

The SOF perf_cnt.h provides a simple performance counter interface that is used in SOF to track performance at audio module and pipeline level.
Majority of the implementation is RTOS agnostic, relying on sof_cycle_get_64() to sample platform clock, and timer_get_system() for CPU clock, both defined in rtos/timer.h. There is however some conditional rules for Zephyr to use timing_counter_get() if SOF is built with CONFIG_TIMING_FUNCTIONS=y.
The amount of RTOS variation does not seem to warrant branching the whole perf_cnt.h to RTOS layer. Move perf_cnt.h back to application interface, so the single implementation can be shared.

xtos: move sof/lib/perf_cnt.h to application interface

---

src/audio/buffers/comp_buffer.c

On initialization we use rzalloc which 0s out all fields. We later call audio_stream_recalc_align which uses the frame_bytes to align the buffer. This is problematic as clz() is passed the size of the frame size which is 0 since channel is 0 and passing 0 to clz is undefined behaviour.

buffer: init channels to 2

---

src/audio/base_fw.c

This patch addresses the issue of inconsistent error code usage in the base_fw.c file, where a mix of POSIX and IPC4 error codes was previously present.
The IPC4 error codes are now used consistently throughout the file, ensuring that the error handling is aligned with the IPC4 protocol expectations. The changes include replacing POSIX error codes such as 0, -EINVAL, and -ENOMEM with their corresponding IPC4 status codes IPC4_SUCCESS, IPC4_ERROR_INVALID_PARAM, and IPC4_OUT_OF_MEMORY, respectively. This standardization helps to avoid confusion and potential bugs that can arise from the mixed usage of different error code conventions.

ipc4: base_fw: Consistently use IPC4 status codes

---

src/audio/copier/CMakeLists.txt
src/audio/copier/Kconfig
src/audio/copier/copier_dai.c
src/audio/copier/copier_gain.c
src/audio/copier/copier_gain.h
src/audio/copier/copier_generic.c
src/audio/copier/copier_hifi.c
src/audio/dai-zephyr.c
src/include/sof/audio/ipc-config.h
src/include/sof/lib/dai-zephyr.h
zephyr/CMakeLists.txt

This PR introduces the Copier Gain feature which will be used by DMIC and with Microphone Privacy.
Gain algorithm utilizes Xtensa HiFi3 instruction set for efficient audio processing and has following modes:
- Static gain
- Transition gain (fade-in/fade-out)
- Mute 
Gain has an option to change gain coefficients in runtime using DMA Control IPC message, therefore has dependency on
https://github.com/thesofproject/sof/pull/9156: [DNM] basefw: Add handling of IPC4_DMA_CONTROL messages
Common use cases:
- control level of the audio signal coming from DMIC interface
- initial DMIC DC offset removal
- mute/unmute in case of Microphone Privacy
- simplification of detector pipelines (no need for volume and selector components)

Add copier gain feature

---

src/ipc/ipc3/helper.c

This reverts commit b53573a15ca56da680dd646d63f9c192bce314b5. This commit broke cmocka unit tests.

Revert "ipc3: override type field once comp_driver found"

---

src/audio/base_fw.c

This commit addresses the limitation in the schedulers_info_get function where scheduler information could only be retrieved for the primary core. The updated implementation now validates the core_id against the number of configured cores (CONFIG_CORE_COUNT) and initiates an IPC process on the requested core if it is not the current core.
- Adding a check to ensure the core_id is within the valid range.
- Calling ipc4_process_on_core to handle IPC processing on secondary cores.
- Returning appropriate IPC4 error codes based on the result of ipc4_process_on_core.

ipc4: base_fw: Enable scheduler info retrieval for secondary cores

---

tools/mtrace/mtrace-reader.py

Sometimes it can help to see how the chunks arrive from firmware when comparing logs with the kernel for example.
The --mark-chunks flag will add a marker for each new chunk that is printed with a running number and the size of the given chunk, for example:
--- Chunk #604 start (size: 652) ---
[    0.000000] <inf> init: print_version_banner: FW ABI 0x301d001 DBG ABI 0x5003000 tags SOF:v2.5-stable-branch-2772-g76e650e56598-dirty zephyr:v3.7.0-2127-ge7c84756087f src hash 0x4ff3fd64 (ref hash 0x4ff3fd64)
*** Booting Zephyr OS build v3.7.0-2127-ge7c84756087f ***
[    0.000000] <inf> main: sof_app_main: SOF on intel_adsp
[    0.000000] <inf> main: sof_app_main: SOF initialized
[    0.000000] <inf> ipc: ipc_cmd: rx   : 0x44000000|0x31400008
[11896.403666] <inf> ipc: ipc_cmd: tx-reply     : …

tools: mtrace-reader.py: Add option to mark chunk starts in output

---

scripts/fuzz.sh

fuzz: add support for 64 bit builds

---

src/audio/asrc/asrc.c
src/audio/buffers/comp_buffer.c
src/audio/copier/copier.c
src/audio/crossover/crossover.c
src/audio/dai-zephyr.c
src/audio/google/google_rtc_audio_processing.c
src/audio/kpb.c
src/audio/mixer/mixer.c
src/audio/mixin_mixout/mixin_mixout.c
src/audio/mux/mux.c
src/audio/selector/selector.c
src/audio/smart_amp/smart_amp.c
src/include/sof/audio/buffer.h
src/include/sof/audio/component.h
src/samples/audio/smart_amp_test_ipc3.c

step 5 - make all components use API to access sink/src components linked to buffers

Pipeline2.0: add API to access sink/src components linked to a buffer

---

west.yml

Includes the following changes potentially relevant to SOF:
155f3f3ba688 west_commands: sign: add imx95 to target list
01754956de29 boards: nxp: imx95_evk: add rimage support for m7 ddr variant
848907c0f81d soc: imx: imx95: enable cache management for M7
f3e870dfa5d4 boards: nxp: imx95_evk: add edma and sai nodes
Needed for https://github.com/thesofproject/sof/pull/9512.

west.yml: update Zephyr to 155f3f3ba688

---

src/audio/copier/copier_generic.c
src/include/sof/lib/dai-legacy.h

Two patches for copier to prevent IPC4 testbench build fail. Copier is part of SOF lib build that is linked to testbench executable. File component is a minimal implementation of a copier and uses copier headers.

Lib: Add to dai-legacy.h struct copier_gain_params for testbench

---

tools/tplg_parser/tokens.c

This change fixes for testbench support for topologies where widgets have more than one format. Without this change if not all e.g. count = 8 tokens are found but e.g. count = 7 the tokens are applied to the format array but the index (offset) to next format (of num_sets) is not advanced. So the first entry will be written again for all found formats. The found tokens count can be less than 8 if the optional
SOF_TKN_CAVS_AUDIO_FORMAT_INPUT_PIN_INDEX or
SOF_TKN_CAVS_AUDIO_FORMAT_OUTPUT_PIN_INDEX are not set.
As fix the offset should be advanced when one or more of tokens is found from topology. The total is incremented by count for the loop end condition check.

Tools: Tplg_parser: Fix handling of tokens found count

---

src/audio/base_fw.c
src/audio/base_fw_intel.c
src/audio/copier/copier_dai.c
src/audio/copier/copier_gain.c
src/audio/copier/copier_gain.h
src/include/ipc4/base_fw.h
src/include/ipc4/dmic.h

Apply Copier Gain feature, introduced in https://github.com/thesofproject/sof/pull/9323, to DMIC interface.
Add complete DMIC configuration blob definitions.
Use DMA Control IPC message to update gain coefficients in runtime.

Enable Copier Gain feature for DMIC interface

---

app/debug_stream_overlay.conf
src/debug/debug_stream/debug_stream_slot.c
tools/debug_stream/debug_stream.py

Access debug slot directly using cavstool.py, by specifying the debug slot number where the debug_stream data is transferred.
Adds one command line parameter for selecting the debug slot directly, adds an alternative mainloop for polling the slot through cavstool.py direct access, and relaxes some often occurring warning print. The warning prints happen when the FW boots and the cavstool code wakes up before the init code has initialized the slot.
NOTE:
This code depends from this PR: https://github.com/zephyrproject-rtos/zephyr/pull/78753 . However, since the import line is in the function that is only called if the --direct-access-slot flag is present, the old code will still work without cavstool.py, but that would in turn need this PR: https://github.com/thesofproject/linux/pull/5154

debug: debug_stream: Access debug slot directly using cavstool.py

---

zephyr/lib/regions_mm.c

Platforms based on xtensa have a non-coherent cache between cores. Before releasing a memory block, it is necessary to invalidate the cache. This memory block can be allocated by another core and performing cache writeback by the previous owner will destroy current content of the main memory.
Invalidate cache when freeing allocated memory block.
The memory block allocated by the allocator may be larger than a requested one. If the allocated block size exceeds the memory page size, only enough pages are mapped to satisfy the request. Thanks to this optimization, it don't map memory pages that will not be used. When freeing memory, the allocator knows only size of the allocated block. Information about the
number of pages actually mapped isn't stored anywhere.
Before unmapping memory, …

regions_mm: Fix vhm allocator behavior on memory freeing 

---

zephyr/include/sof/lib/memory.h

Implement sof/lib/memory.h for Zephyr build and do not rely on the xtos version for Zephyr builds.

rtos: add Zephyr implementation of sof/lib/memory.h

---

src/ipc/dma-copy.c
src/ipc/ipc4/handler.c

dma-trace.h is only needed to implement the IPC3 sof-logger DMA trace and the definitions are not needed for IPC4 or dma-copy.c implementation.

ipc: remove unnecessary inclusion of dma-trace.h

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

SDW link0: rt713
SDW link1: rt1318
And 2ch PCH-attached DMICs.

topology2: add rt713 and rt1318 support on LNL machine

---

src/audio/dai-legacy.c
src/audio/host-legacy.c

audio: fix trace function names

---

src/audio/google/google_ctc_audio_processing.c
src/audio/google/google_rtc_audio_processing.c

Never gonna give you up
Never gonna let you down
Never gonna run around and modify you

audio: google: constify ops drivers

---

zephyr/include/sof/lib/dma.h

Related to https://github.com/thesofproject/sof/issues/9015

rtos: branch out dma.h for Zephyr and XTOS

---

src/include/sof/audio/component.h

Spec is missing and config was incorrect.

component: fix doxygen args

---

src/audio/base_fw.c

The behavior expected by the driver on the host is that if the IPC `IPC4_SCHEDULERS_INFO_GET` is sent for an inactive core, the FW will return success with an empty list in the payload.
This patch addresses these shortcomings in the implementation by adding the appropriate IF statement and initializing an empty list regardless of whether something will be added to it later.

ipc4: base_fw: Return an empty list for inactive cores

---

scripts/build-tools.sh

NXP platforms do not support tplg2 and we don't want to build them every time.
So introduce new options to ./scripts/build-tools.sh so that it can build tplg1 and tplg2 separately.
- ./scripts/build-tools.sh -X, will only build topology1
- ./scripts/build-tools.sh -Y, will only build topology2
Target:
- ./scripts/build-tools.sh -T, remains unchanged and will build both topology1 and topolog2.

scripts: build-tools: Add support to build tplg1/tplg2 individually

---

src/ipc/ipc4/helper.c

Removes unused process_dma_index() from src/ipc/ipc4/helper.c.
In addition to being unused, that func also requires all IPC4 platforms to define PLATFORM_MAX_DMA_CHAN. On some platforms that unused func is the only place such define is used. Removing the unused func allows to skip defining of PLATFORM_MAX_DMA_CHAN on platforms where it is not needed.

ipc4: remove unused code

---

src/audio/dcblock/dcblock_hifi4.c
src/audio/drc/drc_hifi4.c
src/audio/drc/drc_math.h
src/audio/drc/drc_math_hifi3.c
src/audio/eq_fir/eq_fir.h
src/audio/eq_fir/eq_fir_hifi3.c
src/audio/tdfb/tdfb_comp.h
src/include/sof/common.h
src/include/sof/math/fir_hifi3.h
src/math/fir_hifi3.c
src/math/iir_df1_hifi3.c
src/math/iir_df2t_hifi3.c

This patch avoids build error when testbench is built with a Xtensa HiFi5 tool chain. The changes select for HiFi5 the best option of available HiFi4 or HiFi3 code options. No HiFi5 specific optimizations are done.
The updated components those got build issues are: DCblock, DRC, FIR, TDFB, and IIR.

Audio: Fix Xtensa HiFi5 build for audio processing components

---

src/include/sof/trace/trace.h
tools/test/audio/comp_run.sh
tools/test/audio/tdfb_direction_test.m
tools/test/audio/tdfb_test.m
tools/testbench/file.c
tools/testbench/include/testbench/trace.h
tools/testbench/include/testbench/utils.h
tools/testbench/testbench.c
tools/testbench/topology_ipc3.c
tools/testbench/topology_ipc4.c
tools/testbench/utils.c
tools/testbench/utils_ipc3.c
tools/testbench/utils_ipc4.c

This speeds up a lot scripts/host-testbench.sh execution that should also help CI workload. The xt-testbench shows with this comparable MCPS to a real device after not consuming most of performance to debug traces printing. The other patches also improve the testbench traces print format.

Tools: Testbench: Set default trace level to info

---

src/audio/copier/copier_gain.h

The ROUND_UP() is provided by Zephyr headers and can't be used in testbench (IPC4) build.

Audio: Copier: Use SOF_DIV_ROUND_UP() instead of ROUND_UP()

---

app/sample.yaml

We are not able to build this platform in CI yet due to missing
toolchain. This causes errors in twister, so remove as integration
platform until we have the toolchain in place.

app: remove ptl as integration platform

---

tools/topology/topology2/production/tplg-targets-ace1.cmake

Adding support to generte the topology binary for the products which contains everest codec with out HDMI-in capture feature.

topology2: mtl: Generate topology for Everest(Es83x6) codec.

---

posix/include/sof/lib/mailbox.h
src/platform/library/include/platform/lib/mailbox.h

Without this change testbench IPC4 build fails with copier with implicit definition of the function. The mailbox_sw_reg_read64() function should be there in the same platform library mailbox.h header as the 32 bit version of similar function. The header mailbox.h for all Intel platforms is organized similarly.
The argument type is changed to size_t from uint32_t to follow other similar functions.

Platform: Library: Move mailbox_sw_reg_read64() from posix mailbox.h

---

src/init/init.c
zephyr/include/rtos/alloc.h

Small series to fix header dependencies. Unrecovered while cleaning up RTOS headers and noticed these files won't compile unless e.g. trace.h pulls a bunch of common headers.

Add missing header includes to init.c and IPC3 handler

---

zephyr/include/sof/init.h

Add Zephyr version of sof/init.h. This is used define main entry points to the SOF application. The arch_init() entry point is not needed on Zephyr.

zephyr: add Zephyr version of sof/init.h

---

tools/testbench/topology_ipc4.c

This mistake causes the module id and instance number number to be garbage, so the control can't be set up later in widget setup. The issue fixes the valgrind step fail with new proposed IPC4 version of scripts/host-testbench.sh.

Tools: Testbench: Fix IPC4 PGA controls load

---

src/ipc/CMakeLists.txt
src/ipc/ipc3/handler.c
src/platform/imx8ulp/platform.c

As part of RTOS header cleanups, I've noted a few incorrect dependencies between common code and DMA trace. This series has a few small fixes to add proper ifdef guards to code only needed for DMA trace (like dma-copy).

Clean up dma-trace.h and dma-trace.c dependencies

---

src/audio/mux/mux.c

There is IPC time out after disabling core1. However, we don't have sufficient log on FW side.
```
[   55.979513] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[   55.979904] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[   55.979916] sof-audio-pci-intel-tgl 0000:00:1f.3: Core 1 powered down
[   55.979921] sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.1.SSP1.OUT freed
[   55.980386] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x20140000 successful
[   55.980403] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x90050000: GLB_TRACE_MSG: DMA_FREE
[   56.487374] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx timed out for 0x90050000 (msg/reply size: 8/0)
[   56.487382] …
```

[cavs2.5-001] IPC timeout on max98373 boards

---

src/audio/copier/copier_hifi.c

This fixes build error of non-static functions without prototypes:
cc1: warnings being treated as errors
sof/src/audio/copier/copier_hifi.c:142:
warning: no previous prototype for ‘copier_load_slots_and_gain16’
sof/src/audio/copier/copier_hifi.c:161:
warning: no previous prototype for ‘copier_load_slots_and_gain32’

Audio: Copier: Fix testbench HiFi3 build

---

tools/topology/topology2/production/tplg-targets-ace3.cmake

Adding topology support for rt721-sdw monolithic codec
Verified on PTL-RVP

topology2: add support for rt721-sdw topology

---

posix/include/sof/compiler_attributes.h
src/audio/module_adapter/module_adapter_ipc3.c
src/audio/pipeline/pipeline-graph.c
src/ipc/ipc3/dai.c
src/trace/Kconfig
xtos/include/sof/compiler_attributes.h
zephyr/include/sof/trace/preproc.h

Alternative to pull request https://github.com/thesofproject/sof/pull/9598 and follow-up to discussion in https://github.com/thesofproject/sof/pull/9598#issuecomment-2425917932 .
This takes the decision to not support dma-trace (sof-logger) in Zephyr builds. and this allows to drop preproc.h family of preprocessor macro infra. In current CI, one IMX target is built with CONFIG_TRACE=n and CONFIG_ZEPHYR_LOG=n, and will hit build errors without the patches in this set to add maybe_unused attribute and a simple definition of SOF_TRACE_UNUSED().
Motivation for this work is #9015 and clean separate of XTOS and Zephyr headers.

Zephyr preproc.h implementation (OPTION B)

---

src/audio/aria/aria.c
src/audio/aria/aria.h
src/audio/aria/aria_generic.c
src/audio/aria/aria_hifi3.c
src/audio/aria/aria_hifi5.c

In aria_hifi5.c
- The needed type for "in" in AE_LA32X2X2_IP() needs to be ae_int32x4. The HiFi5 code was likely developed with an earlier toolchain that used different type.
- Removed unused declared variables, warnings are errors in testbench build.
- Changed index_tab to common sof_aria_index_tab[]
In aria_generic.c, hifi3 changed INDEX_TAB[] to a common sof_aria_index_tab[]. It avoids link error in HiFi5 build where aria.c is missing the INDEX_TAB[].
The sof_aria_index_tab[] is changed from uint8_t to int32_t type to use the same table in every build.

Audio: Aria: Fix compilation for HiFi5

---

tools/testbench/include/testbench/utils.h
tools/testbench/topology_ipc4.c
tools/testbench/utils_ipc4.c

The previous ibs and obs calculate was wrong but it appeared to work since not many components use it. The issue was seen with Aria. Since the ibs depends on audio frame format and number of frames in period, the testbench parameter period_size is changed to period_frames to calculate ibs and obs in component setup.
This fix is a workaround until parsing ibs/obs from topology is done to testbench.

Tools: Testbench: Fix ibs/obs calculation

---

src/audio/aria/tune/sof_aria_blobs.m

This script creates blobs for Aria to embed to topology. All attenuation parameter values 0 - 3 are exported for use in topologies.

Audio: Aria: Add tool to create configuration blobs for Aria

---

src/audio/module_adapter/module/passthrough.c

After commit 5f6f22d25e3a ("audio: module_adapter: Prepare to convert copier to use module interface") period_bytes are no longer computed in module generic prepare.
This break the passthrough module as it was using period_bytes computed by upper layers.
Fix this by computing period_bytes inside passthrough module prepare function.
Fixes: 5f6f22d25e3a ("audio: module_adapter: Prepare to convert copier to use module interface")

audio: module: Fix passthrough module

---

tools/topology/topology2/platform/intel/sdw-amp-generic.conf

These two patches expand the possible combinations of feedback channel count and number of links.
It has been tested on these combinations:
1 bus, 2 amps, 1 fb channel per amp, total 2 channels
1 bus, 2 amps, 2 fb channel per amp, total 4 channels
1 bus, 4 amps, 1 fb channel per amp, total 4 channels
2 buses, 1 amp per bus, 1 fb channel per amp, total 2 channels
2 buses, 1 amp per bus, 2 fb channel per amp, total 4 channels
2 buses, 1 amp per bus, 4 fb channel per amp, total 8 channels
2 buses, 2 amp per bus, 1 fb channel per amp, total 4 channels
2 buses, 2 amp per bus, 2 fb channel per amp, total 8 channels
2 buses, 3 amp per bus, 1 fb channel per amp, total 6 channels
2 buses, 4 amp per bus, 1 fb channel per amp, total 8 channels

Support a larger range of amp feedback channel counts

---

smex/CMakeLists.txt
zephyr/CMakeLists.txt
zephyr/Kconfig

Remove CONFIG_SOF_ZEPHYR_STRICT_HEADERS and make strict headers mode the only supported way to build SOF with Zephyr. This means SOF Zephyr builds do not use any headers from sof/xtos/include anymore.
This change simplifies the SOF build as full RTOS adaptation is in sof/zephyr/include for Zephyr builds.

zephyr: move to strict headers builds for all targets

---

src/audio/volume/CMakeLists.txt
src/audio/volume/Kconfig.simd
src/audio/volume/volume.c
src/audio/volume/volume.h
src/audio/volume/volume_hifi3.c
src/audio/volume/volume_hifi4.c
src/audio/volume/volume_hifi4_with_peakvol.c
src/audio/volume/volume_hifi5.c
src/audio/volume/volume_hifi5_with_peakvol.c
src/include/sof/common.h
zephyr/CMakeLists.txt

Add HiFi5 implementation of volume functions, compared with HiFi3 version, can reduce about 28% cycles.

Audio: Volume: Add HiFi5 implementation.

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-icl-rt711-rt1308-rt715-hdmi.m4

The topology includes multi-function codec support on single SoundWire link. The hardware configuration on RPL product is below:
Soundwire#
link 0: cs42l43 multi-function codec with
JACK, DMIC and Speakers endpoints.
The SDW used bidirectional DAI for each sdw link. DAI index starts from 2. sdw0/1/2/3: 2(ALH_OUT/IN) / 3(ALH_IN/OUT)
In this SKU, reorder to match cs42l43 DAIs Pin on sdw link 0: sdw0: 2(JACK_OUT), 3(DMIC_IN), 4(JACK_IN), 5(AMP_OUT)
Besides, align the partial string match of dai name from main branch.

[stable-v2.2] topology1: add sdw multi-function codec support

---

src/audio/drc/drc.c

The configuration blob is checked in drc_prepare(). If the blob does not have params.enable set, then it is safe to switch to a more efficient buffer copy function that bypasses the internal DRC lookup delay with channels de-interleave and interleave operations. The enable in the blob is a master switch for DRC. With such configuration in the blob the switch control from user space can't switch the processing on. Therefore it is safe to change the processing function. This change minimizes the MCPS overhead of unused DRC and reduces audio latency.
If a new blob is received during streaming, the params.enable is checked again and the processing function is set again if the pass-through copy mode was in use.
A pass-through blob can be applied e.g. when the same pipeline is used for both …

Audio: DRC: Use audio_stream_copy() with pass-through configuration

---

src/probe/probe.c

This commit converts probe debug feature from component to module API.
With this PR the probes does not work without this fix in the Linux side: https://github.com/thesofproject/linux/pull/5221
So its maybe better to wait a bit before merging this? Or what do you say @lgirdwood ?

probe: Convert to module API

---

src/ipc/ipc4/helper.c

Fix `ipc4_base_module_cfg_to_stream_params()` which uses valid bit depth value from IPC4 base module config instead of container size (depth) to set `frame_fmt`.

ipc4: helper: fix stream params frame format update

---

src/include/sof/ipc/msg.h
src/ipc/ipc-common.c
src/ipc/ipc4/handler.c
src/library_manager/lib_notification.c

This patch addresses an issue with incorrect IPC responses due to the lack of cache flushing and invalidation on secondary cores.
The following changes have been made:
1. Added cache writeback for IPC message data in `ipc_msg_send` when the current core is not the primary core.
2. Added cache invalidation for IPC message data in `ipc_prepare_to_send` before writing to the mailbox.
These changes ensure that the IPC data is correctly synchronized between cores.

ipc: add cache flushing and invalidation for IPC data

---

tools/topology/topology2/platform/intel/sdw-jack-generic.conf

Add 96KHz rate support for SoundWire jack device.

Topology2: add 96KHz rate support for SDW jack

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

The rt1320 could use the same SoundWire link as rt712. In that case there is still one rt1320, but  the NUM_SDW_AMP_LINKS should be 1. Name the tplg with the exact link number to avoid confusing.

Topology2: rename sof-lnl-rt712-rt1320x1

---

west.yml

Includes the following changes potentially relevant to SOF:
ac162b041abf intel_adsp: set exec for simulator targets
475878428c11 soc: intel_adsp: tools: cavstool.py: add RPL and ADL-N support
7ad012d3bbd1 soc: intel_adsp: tools: sort cAVS2.5 PCI DIDs in cavstool.py
2c79024b2f71 soc: intel_adsp: tools: cavstool.py: add PCI DIDs for Intel Arrow Lake
8795a17fa210 soc: intel_adsp: tools: reword cavstool.py startup log message
52bd2ff9a6ca soc: intel_adsp: tools: continue cavstool.py legacy cleanup
cdd563500292 nxp: imx8m: adsp: enable the irqstr interrupt controller
18419b618f20 llext: xtensa: fix relocations with multiple SLOT0_OP
d3aa1709631b drivers: dai: sai: support pm runtime operations
52efa3bb9b8a soc: intel_adsp: tools: fix ace15 ROM status check in cavstool.py
256ab0c9191c ace: mm: …

west.yml: update Zephyr to c50777a84311 (Zephyr Nov 11 update)

---

src/audio/Kconfig

Add explicit dependency to CONFIG_DMA_INTEL_ADSP_HDA as the current chain DMA uses HDA definitions in its implementation.

audio: chain_dma: update build time dependencies

---

src/audio/drc/drc_hifi4.c

The HiFi4 build is looking for enable only from the configuration blob and the ALSA switch control has no impact. This change unifies the operation with generic and HiFi3 builds.

Audio: DRC: Fix DRC enable control switch handling for HiFi4

---

src/schedule/Kconfig
src/schedule/zephyr_domain.c

Here's a series to make the LL scheduler stat logging more configurable, and tune the defaults using the new tools.

schedule: zephyr_domain: make LL reporting build-time configurable and change the defaults

---

src/include/sof/probe/probe.h
src/init/init.c
src/ipc/ipc-common.c
src/ipc/ipc4/logging.c
src/lib/dma.c
src/lib/notifier.c
src/logging/log_backend_probe.c
src/probe/Kconfig
src/probe/llext/CMakeLists.txt
src/probe/llext/llext.toml.h
src/probe/probe.c
src/probe/probe.toml
src/schedule/zephyr_ll.c
zephyr/CMakeLists.txt
zephyr/schedule.c

For probe llext module to work, this https://github.com/zephyrproject-rtos/zephyr/pull/81098 needs to be merged to Zephyr tree.

Probe llext

---

src/library_manager/llext_manager.c
west.yml

Recent Zephyr LLEXT updates seem to have introduced ELF layout changes, which require updated SOF support

Zephyr: A subset of #9522 to fix #9659

---

tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/platform/intel/sdw-amp-generic.conf

Add cases for NUM_SDW_AMP_LINKS=3 so that speaker playback and capture can be aggregated across 3 SoundWire buses.
The target hardware configurations for this is a SmartCodec plus multiple buses of SmartAmps. Typically the codec drives tweeters and the amps drive woofer/midrange.
This has been tested with the configuration:
SDW0: 2x CS35L56
SDW1: 2x CS35L56
SDW3: CS42L43
with only speaker playback aggregated.
It has also been tested with the configuration:
SDW0: 2x CS35L56
SDW1: 2x CS35L56
SDW3: 2x CS35L56
with playback and amp feedback aggregated.

topology2: Support for NUM_SDW_AMP_LINKS=3 aggregation

---

src/init/ext_manifest.c

Put probe information into manifest by CONFIG_PROBE=y would be better.
This change could help to avoid annoying kernel log from SOF loader ("unknown sof_ext_man header type 3 size 0x30") if CONFIG_PROBE=n on most SOF machines.

ext_manifest: include probe information by CONFIG_PROBE

---

scripts/llext_link_helper.py
src/audio/drc/drc.c
src/include/module/module/llext.h
src/library_manager/llext_manager.c
src/math/numbers.c
tools/rimage/src/include/rimage/module.h
tools/rimage/src/include/rimage/sof/user/manifest.h
tools/rimage/src/module.c

very raw, still work in progress, not fully functional
update: working so far, might still need to improve the API

LLEXT: run non-performance critical code in DRAM

---

src/include/sof/audio/kpb.h
zephyr/Kconfig
zephyr/include/sof/lib/regions_mm.h
zephyr/lib/alloc.c

The buffer allocation method for ace platform has been changed. They are allocated using the virtual memory heap. This consists of a set of buffers with a predefined size.
Dividing memory into buffers of a predefined size is necessary for the proper operation of the allocator, which creates a buffer with a size given as a range (`buffer_alloc_range` https://github.com/thesofproject/sof/pull/9145) - a functionality used for deep buffering.
PR needed before merge this PR:

ace: zephyr: alloc: Use virtual memory heap for buffers

---

tools/topology/topology2/cavs-sdw.conf

The existing default is high-pass 40 Hz with 0 dB gain. This change amplifies captured sound from DMIC by 20 dB. The same amplifying IIR type is used in hda-generic.
The change is for now, but not the final solution. After we have UCM2 control for capture processing in SOF we can shift applying more gain to the DRC component that will provide more robustness with silent and loud environments.

[stable-v2.11] Tools: Topology2: SDW: Use for PCH DMIC IIR type with +20 dB gain

---

tools/topology/topology2/production/tplg-targets-hda-generic.cmake
tools/topology/topology2/sof-hda-generic.conf

This entry creates a topology for the HDA codec with PDM0 DMIC for PTL.

topology2: Add HDA with DMIC, HDMI topologies support for ACE3 architecture

---

src/audio/kpb.c

This patch addresses a potential NULL pointer dereference issue in the `devicelist_reset` function within the Key Phrase Buffer (KPB) component. The issue was exposed by a recent change in Zephyr's MMU mapping for Intel ADSP ACE30, which now catches NULL pointer accesses.
The `devicelist_reset` function previously iterated over the entire `DEVICE_LIST_SIZE` when clearing items and zeroing pointers, which could lead to dereferencing NULL pointers. The fix involves iterating only up to `devlist->count` to ensure that only valid pointers are accessed.
This change prevents potential NULL pointer dereference and ensures the stability of the KPB component.

audio: kpb: fix potential NULL pointer dereference in device list reset

---

tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/cavs-rt5682.conf
tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/include/pipelines/cavs/dai-copier-gain-eqiir-module-copier-capture.conf
tools/topology/topology2/platform/intel/dmic-generic.conf
tools/topology/topology2/platform/intel/dmic1-mfcc.conf
tools/topology/topology2/sof-hda-generic.conf

This patch swaps the order of IIR and gain components in capture pipeline. In IPC4 systems the gain component can only attenuate the signal, largest gain is 0 dB (pass-through). The IIR component can be set up to amplify the signal by e.g. +20 dB that is currently default in many topologies. The gain can possibly distort the signal in loud environment.
With current "dai-copier -> eqiir -> gain -> module-copier" topology the user configurable gain (ALSA mixer control) can't prevent clipping of audio signal in IIR. While with swapped order "dai-copier -> gain -> eqiir -> module-copier" using attenuation in gain component can be used to prevent audio signal clipping in IIR. It would be useful in capturing audio in a very loud environment.
Since the pipeline is 32-bits there is no practical …

Tools: Topology2: Swap gain and eqiir in DMIC capture

---

src/audio/mux/mux.c
src/include/sof/lib_manager.h
src/library_manager/llext_manager.c
tools/rimage/src/manifest.c

Add support for libraries with multiple modules. This handles loading of libraries. Creation will be added later, isn't too complex, needs minor additions to cmake and Python.

LLEXT: libraries with multiple modules

---

west.yml

Total of 084 commits.
caece8dd54cd drivers: dai: Place API into iterable section
c2f02533a6ad drivers: dma: intel_adsp_hda: change L1_EXIT defaults
b4fb833eb9cc soc/mediatek/adsp: Source timer rate from DTS
09495c9e4807 soc/mediatek: Ruffify python scripts
fe5c11db0538 boards/mediatek: Add mt8196_adsp
e35de00f86c3 soc/mtk_adsp: Update gen_img.py address space rules
3c0269f4f697 soc/mtk_adsp: Add missing z_prep_c() prototype
4b3874b9ea42 boards/mediated: Add twister.yaml
cc43e3a52738 soc/mediatek: Add missing snippets sections
2b8d54281507 boards/mtk_adsp: Add a doc page
5364783ba181 soc: boards: Add Mediatek MT8186 and MT8188 audio DSPs
cdd4cbcc676c soc/mtk_adsp: Remove "msg" API
48a84911acf6 soc/mtk_adsp: Add default console hook
22de29e76875 soc: intel_adsp/ace: put …

west.yml: update zephyr to 1d40a7ee3415 (Dec 5th)

---

.github/workflows/zephyr.yml
app/boards/imx93_evk_mimx9352_a55.overlay

As of Zephyr commit 93d60ecdb01("boards: Remove all deprecated HWMv1 board aliases") HWMv1 naming is no longer allowed. As such, change to HWMv2 naming for the imx93_evk board.
Fixes #9716.

.github/zephyr: switch to HWMv2 naming of imx93_evk

---

src/platform/posix/dma.c

this commit refactors dma_driver_api in iterable_section

platform: posix: dma: place api in iterable section

---

src/audio/buffers/ring_buffer.c

Increase buffer size to 3 times `max_ibs_obs` to prevent starving a DP module that process different block sizes in different periods (44.1 kHz case). The full description has been added as a comment in the source code.

ring_buffer: Increase buffer size to prevent a DP module starvation

---

src/audio/crossover/crossover_generic.c

To use audio_stream_copy function in place of manual implementation.
For issue https://github.com/thesofproject/sof/issues/4487

crossover: use audio_stream_copy for passthrough

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

The 2ch DMIC TDFB blob should be "line2_generic_pm10deg". The blob for 4ch pass-through does not work correctly with a 2ch stream. Note: Another option for pass-through is "line2_pass". But I'm assuming here that the same blob as used for other 2ch systems should be suitable.
Fixes: f4cd55c2e879e7f822cb793bd65449fa1da36b04
("topology2: Add support for cs42l43 SKU with two host DMICs")

Tools: Topology2: Fix DMIC TDFB blob in sof-lnl-cs42l43-l0-2ch

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

The 2ch DMIC TDFB blob should be "line2_generic_pm10deg". The blob for 4ch pass-through does not work correctly with a 2ch stream. Note: Another option for pass-through is "line2_pass". But I'm assuming here that the same blob as used for other 2ch systems should be suitable.
Fixes: f4cd55c2e879e7f822cb793bd65449fa1da36b04
("topology2: Add support for cs42l43 SKU with two host DMICs")
(cherry picked from commit 7650d0ac21f2a51e7dfb63b785142e7bb5a0921a)

[stable-v2.12] Tools: Topology2: Fix DMIC TDFB blob in sof-lnl-cs42l43-l0-2ch

---

tools/topology/topology1/sof/pipe-highpass-switch-capture.m4
tools/topology/topology1/sof/pipe-volume-switch-capture.m4

We should only use mute led on the PCH dmic.
pipe-highpass-switch-capture.m4 and pipe-volume-switch-capture are only used by SoundWire and nocodec pipelines. It will not impact the existing products.

topology1: remove mute led from SoundWire capture

---

tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/sof-icl-rt711-rt1308-rt715-hdmi.m4

The configuration has no jack and use rt1316 amps and PCH DMIC.

topology1: add sof-adl-rt1316-l02-4ch support 

---

src/audio/chain_dma.c
src/audio/dai-zephyr.c
src/audio/host-zephyr.c
src/drivers/imx/ipc.c
src/lib/dma.c
src/library_manager/lib_manager.c
src/probe/probe.c
zephyr/include/sof/lib/dma-legacy.h
zephyr/include/sof/lib/dma.h

Add "sof_" namespace to dma_get()/put() calls in and modify all uses of the interface for builds with native Zephyr drivers.
Keep the old name for XTOS builds. This reduces the amount of code that needs to be touched, and in XTOS code, there is no confusion with the namespaces as all dma_foo() calls are to SOF DMA layer.
Link: https://github.com/thesofproject/sof/issues/9561

treewide: zephyr: add sof_ prefix to dma_get/put()

---

west.yml

Total of 380 commits.
6d0c23be314 soc: intel_adsp: add support for .cold* sections
09cdc1f4b8c soc: intel_adsp: add a "cold" module manifest
de4003c07be soc: intel_adsp: check module address before copying to SRAM
020985b38b4 dts: xtensa: nxp_imx8m: Add SAI3 and SDMA3 node
e94c86f3951 drivers: dma: Add initial support for NXP SDMA
b0416f51b64 drivers: ssp: start with xtal clock on ssp ver >= 2.0

west.yml: update zephyr to 42701fdb272

---

.github/workflows/llext.yml
.github/workflows/sparse-zephyr.yml
.github/workflows/zephyr.yml

We're getting GitHub workflow failures like:
docker: failed to register layer: write /usr/lib/x86_64-linux-gnu/libz3.so.4: no space left on device.
e.g. in
https://github.com/thesofproject/sof/actions/runs/12651056289/job/35250849879?pr=9702 This patch frees some space before running tests.

[SKIP SOF-TEST] github: free some disc space

---

app/boards/mt8186_mt8186_adsp.conf
app/boards/mt8188_mt8188_adsp.conf
app/boards/mt8195_mt8195_adsp.conf
app/boards/mt8196_mt8196_adsp.conf
scripts/xtensa-build-zephyr.py
src/drivers/mediatek/afe/afe-dai.c
src/drivers/mediatek/afe/afe-drv.c
src/drivers/mediatek/afe/afe-memif.c
src/platform/Kconfig
src/platform/mtk/dai.c
src/platform/mtk/include/platform/lib/clk.h
src/platform/mtk/include/platform/lib/cpu.h
src/platform/mtk/include/platform/lib/dai.h
src/platform/mtk/include/platform/lib/dma.h
src/platform/mtk/include/platform/lib/mailbox.h
src/platform/mtk/include/platform/lib/memory.h
src/platform/mtk/include/platform/lib/pm_runtime.h
src/platform/mtk/include/platform/platform.h
src/platform/mtk/include/platform/trace/trace.h
src/platform/mtk/platform.c
src/platform/mtk/tools/README.txt
src/platform/mtk/tools/build.sh
src/platform/mtk/tools/mt-dai-gen.c
tools/rimage/config/mt8196.toml
tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/platform/mediatek/mt8196.m4
tools/topology/topology1/sof-mt8196-mt6681.m4
zephyr/CMakeLists.txt
zephyr/lib/alloc.c

Unify the MediaTek 8195/86/88 devices into a single Zephyr-based "mtk" platform.
+ Almost all the device config and core (interrupt, timer) drivers are in upstream Zephyr now.  There's almost no per-device code left in SOF.
+ In fact it's really quite small.  Just two sub-300-line C files and some mostly boilerplate headers.
+ This still builds with ZEPHYR_NATIVE_DRIVERS=n.  The pre-existing dummy-dma and afe drivers are used unchanged.  The former has an equivalent in upstream Zephyr.  The latter will need a port.
+ The AFE driver is "half Zephyr" though.  The C code remains a legacy SOF driver but all the config is source from Zephyr DTS and converted at runtime to the legacy struct.
+ It's still a IPC3 platform.  Kernel support for IPC4 doesn't exist yet. 
This PR depends for build and …

src/platform: Add "mtk" Zephyr platform for MediaTek DSPs

---

zephyr/include/rtos/string.h

This patch addresses an issue in the `memcpy_s` function within the Zephyr RTOS string header. The issue was identified during IPC3 fuzz testing with UndefinedBehaviorSanitizer enabled.
- Adding `stdint.h` for `uintptr_t` type.
- Adding checks to prevent overflow in pointer arithmetic.
- Adjusting overlap checks to avoid overflow.
These changes ensure that the `memcpy_s` function correctly handles edge cases, preventing undefined behavior due to pointer arithmetic overflow and memory overlap.
Fixes #9768

zephyr: fix overflow and overlap checks in memcpy_s

---

zephyr/include/rtos/string.h

This patch addresses an issue in the `memcpy_s` function within the Zephyr RTOS string header. The issue was identified during IPC3 fuzz testing with UndefinedBehaviorSanitizer enabled.
- Adding `stdint.h` for `uintptr_t` type.
- Adding checks to prevent overflow in pointer arithmetic.
- Adjusting overlap checks to avoid overflow.
These changes ensure that the `memcpy_s` function correctly handles edge cases, preventing undefined behavior due to pointer arithmetic overflow and memory overlap.
Fixes #9768
(cherry picked from commit 7d11802b0c531c022747f7fca82a045cc6f4c16e)

[stable-v2.12] zephyr: fix overflow and overlap checks in memcpy_s

---

README.md

Replace the direct #sof Discord channel link with a reference to the
Zephyr project's documentation for accessing their server, where the
channel is hosted.
The previous link only worked for users already in the Zephyr Discord
server, potentially confusing new visitors looking to join the channel.
Pointing to Zephyr's community docs provides the necessary context and
instructions for getting an invite to access the #sof channel.
Since the channel is part of Zephyr’s Discord server, directing readers
to their official documentation ensures the instructions remain accurate
while sparing this project from duplicating details.
Fixes GitHub issue #7161.

README.md: update Discord channel instructions

---

src/library_manager/lib_manager.c
src/library_manager/lib_notification.c

With Zephyr function names are included in log messages, no need to supply them in the format string. Also reduce verbosity of lib_manager_module_create() - it's called every time a loadable module is instantiated, no need to log this fact.

lib_manager: clean up logging

---

src/audio/chain_dma.c

This patch corrects the format specifier used for printing error codes in the chain_dma.c file. The error codes are signed integers, but the format specifier used was `%u`, which is for unsigned integers. This caused negative error codes to be printed incorrectly as large positive values. The format specifier has been changed to `%d` to correctly print signed integers.
This is a cosmetic change that ensures error codes are accurately represented in the logs, aiding in debugging and analysis.
**Before the Patch**
```txt
[    3.322131] <err> chain_dma: chain_task_run: chain_task_run(): dma_reload() host error, ret = 4294967291
```
**After the Patch**
```txt
[    2.254653] <err> chain_dma: chain_task_run: chain_task_run(): dma_reload() host error, ret = -5
```

audio: chain_dma: fix incorrect format specifier for error codes

---

zephyr/lib/regions_mm.c

The vmh_free function may have referenced a null pointer if an invalid pointer was passed to it. Before referencing the allocator array item, check if it has been initialized.
Add k_panic() function call in error handling code to help detect potential memory release errors.

regions_mm: vmh_free: Prevent null pointer dereference

---

tools/topology/topology2/cavs-nocodec-bt.conf
tools/topology/topology2/development/tplg-targets.cmake

Add rules to create sof-nocodec-bt-ptl.tplg and
sof-nocodec-bt-ptl-lbm.tplg.

topology2: cavs-nocodec-bt: add Intel PTL support

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

It is the same as sof-lnl-cs42l43-l0-cs35l56-l23.tplg except PCH DMIC instead of SoundWire DMIC is used.

topology2: add sof-lnl-cs42l43-l0-cs35l56-l23-2ch

---

zephyr/Kconfig

If data processing (DP) scheduler is enabled on Xtensa HiFi platforms, CONFIG_HIFI_SHARING should be enabled as well. Otherwise modules running via DP scheduler cannot use HiFi extensions (as the HiFi register state is not saved and restored on context switches).

zephyr: enable HIFI_SHARING if DP scheduler is enabled with HIFI

---

scripts/sof-testbench-build-profile.sh

The script sof-testbench-helper.sh is not found if it has not been set to user's path. Not finding it fails the profiler runs.

Scripts: Fix path in script sof-testbench-build-profile.sh

---

src/audio/mixin_mixout/mixin_mixout_hifi3.c

AE_ADD24S() expects input arguments to be Q9.23 values. Therefore, negative 24-bit values in a 32-bit container should have their sign extended to the upper 8 bits. All other five implementations of 24-bit mixing (IPC3 mixer's generic and HIFI3, IPC4 mixin's generic, IPC4 mixin's mix with gain generic and HIFI3) perform sign extension prior to mixing and do not rely on samples being already sign-extended.

ipc4: mixin: Fix HiFi3 impl of 24-bit mixing

---

.github/workflows/pull-request.yml
.github/workflows/sof-docs.yml
.github/workflows/zephyr.yml

Fixes the git describe/tag performance hack added in commit 23284780d7cb (".github/zephyr.yml: fix tags missing from `git -C zephyr/ describe`") which worked for an amazingly long time (1.5 year) but apparently ran its course. Git version 2.48 apparently does not like it anymore. Replace it with something slower but simpler and safer.
Should fix build reproducibility issue #9797, much more details there.
Also fixes commit 4bc6488b24e4 (".github/zephyr: de-hardcode the name of the zephyr remote")

[SKIP CI] .github/zephyr: simplify and fix the git describe performance hack

---

src/ipc/ipc-common.c
zephyr/Kconfig
zephyr/edf_schedule.c

Low level IPC processing should be confined to the primary core. Move delayed IPC sending to a dedicated work queue with core 0 affinity.
Fixes: #8165

ipc: move delayed IPC sending to the primary core

---

src/lib/dai.c

dai_get_device is called using DAI-types from IPC definition but calls dai_config_get() which returnes a Zephyr DAI type.
So, in order to fix this, we introduce `dai_type_to_zephyr` which converts a DAI-type from IPC definition to a Zephyr DAI type, so that later we can compare types in the same space.
The current code works because the two DAI types are matching, but it is no longer the case with latest introduces types.
Fixes: https://github.com/thesofproject/sof/issues/9803

lib: dai: Fix dai_get_device

---

src/audio/mixin_mixout/mixin_mixout_hifi3.c

Simpler and faster implementation of HiFi3 mix with gain functions. The previous version works fine. This is just an improvement to make the code faster and more straightforward.

ipc4: mixin: Improve HiFi3 mix with gain impl

---

tools/topology/topology2/cavs-nocodec-bt.conf

Align Port0 and Port1 PCM parameters with Port2, so that all PCMs can be used to test pipelines aligned with Bluetooth profiles.
Continue using the common infrastructure in "bt-generic.conf" for Port2 as these definitions are used by many other topologies. Set up Port0/1 manually in cavs-nocodec-bt.conf and always enable loopback configuration for these ports.

topology2: cavs-nocodec-bt: align Port0/1 configuration with Port2

---

src/audio/mixin_mixout/mixin_mixout_hifi3.c
src/audio/mixin_mixout/mixin_mixout_hifi5.c

* Adds HiFi5 implementation of "mix with gain" functions.
* Adds sign-extension to HiFi5 implementation of 24-bit mixing (similarly as it was done recently for HiFi3).
AE_ADD24S() expects input arguments to be Q9.23 values. Therefore, negative 24-bit values in a 32-bit container should have their sign extended to the upper 8 bits. Our other implementations of 24-bit mixing all perform sign extension prior to mixing and do not rely on samples being already sign-extended.
* Fixes to HiFi5 implementation of mix functions and correcting comments.

ipc4: mixin: Add "mix with gain" HiFi5 impl

---

scripts/gen-uuid-reg.py

Extend the script that generates the `uuid-registry.h` file to also generate definitions containing the uuid as a string. These definitions (UUIDREG_STR_...) can be used in toml files, allowing get values from the uuid-registry.
After merge, `uuid-registry.h` will contain following entries:
```C
#define _UUIDREG_dcblock { 0xb809efaf, 0x5681, 0x42b1, { 0x9e, 0xd6, 0x04, 0xbb, 0x01, 0x2d, 0xd3, 0x84 } }
#define UUIDREG_STR_DCBLOCK "b809efaf-5681-42b1-9ed6-04bb012dd384"
```
For example, following toml file fragment:
```
[[module.entry]]
name = "DCBLOCK"
uuid = "B809EFAF-5681-42B1-9ED6-04BB012DD384"
```
will be possible to change to:
```
[[module.entry]]
name = "DCBLOCK"
uuid = UUIDREG_STR_DCBLOCK
```
Require update `sign.py` on Zephyrs side: …

scripts: gen-uuid-reg.py: Generate string identifier for toml files

---

tools/rimage/config/platform.toml

This is required to build single PTL loadable module

rimage: config: add ptl to generic platform toml

---

src/audio/crossover/crossover.c
src/audio/crossover/crossover.h
src/audio/multiband_drc/multiband_drc.c
src/audio/multiband_drc/multiband_drc_generic.c
src/include/sof/math/iir_df1.h
src/math/iir_df1_generic.c
src/math/iir_df1_hifi3.c
src/math/iir_df1_hifi4.c
src/math/iir_df1_hifi5.c

The simpler 4th order hard-coded IIR version saves MCPS in in band split filter bank and emphasis/de-emphasis IIR filters.

Audio: Multiband DRC:  Use optimized 4th order IIR filter version

---

src/drivers/mediatek/mt8196/intc.c
zephyr/CMakeLists.txt

This wasn't including the needed third party library.  Also rework it a little to make the cmake a little less of a mess.  Not sure I actually improved things, but I tried.
Also one trivial warning fixup I stumbled on with a variant xt-clang.

Update waves codec integration for Zephyr production builds

---

tools/testbench/testbench.c
tools/testbench/topology_ipc4.c

These fixes/improvements improve the usability for development work.

Tools: Testbench: Small improvements

---

src/include/sof/math/exp_fcn.h
src/math/exp_fcn.c
src/math/exp_fcn_hifi.c
test/cmocka/src/math/arithmetic/exponential.c

The function sofm_exp_int32() if replaced with new sofm_exp_approx()
function. It's not a direct replacement so the name is
changed. The input range changes from +/- 5 to +/- 8.
The wrapper function sofm_exp_fixed() with input range -16 .. +7.6
is updated to use the new function with a simpler range reduction
for large negative input values. All current exponent function
usage in SOF components is for the wrapper function that remains
compatible.
The function sofm_db2lin_fixed() is updated to handle larger
negative input decibels values made possible by the new more
accurate exponent function.
The accuracy in exponent function for input ranges from -8 to +8 or
-16 to 7.6 depending on used exponent function improves from
absolute error of 1 to 1000 ppm to constant less than 1 ppm.
The …

Math: Replace exp() function with more accurate and fast version

---

zephyr/lib/fast-get.c

Use uncached aliases for potentially shared objects, synchronise cache properly when sharing cached access

DRAM: `fast_get()` cache-handling improvements

---

src/include/sof/lib_manager.h
src/ipc/ipc-common.c
src/library_manager/llext_manager.c
src/math/sqrt_int16.c
src/math/trig.c
zephyr/CMakeLists.txt

Extract a couple of simple changes from #9804

LLEXT: simple changes

---

tools/demo-gui/demo-gui/sof_controller_engine.py
tools/demo-gui/demo-gui/sof_demo_gui.py

- Improve error handling and readability
- Refactor GUI initialization and structure
- Add stop and mute functionality to playback
- Update GUI color scheme

tools: demo-gui: improvements

---

tools/test/audio/src_test.m

This patch adds to src_test.m as optional 8th argument possibility to launch SRC component tests with xt-run for xtensa binaries.
With this option it's easy to check objective audio quality parameters for Xtensa implementation of SRC and ASRC components.

Tools: Test: Audio: Add to src_test.m option for xt-run

---

zephyr/lib/alloc.c

Add k_panic() function call in error handling code to help detect potential memory release errors.
The vmh_free function returns an error if:
1. heap belongs to another core,
2. given pointer to be freed is invalid (doesn't belong to the allocator),
3. there is an error in the code determining the size of the block to be freed
4. memory unmapping fails.
Log entry is easy to miss, stopping the firmware at this point will draw attention to a critical problem related to memory allocation. Otherwise, it will have a slowly progressing memory leak.
If we decide this is a desirable change, we can merge it after https://github.com/thesofproject/sof/pull/9776 and https://github.com/thesofproject/sof/pull/9777 have been merged.

zephyr: alloc: virtual_heap_free: Panic on deallocations errors

---

tools/topology/topology2/platform/intel/bt-generic.conf
tools/topology/topology2/platform/intel/bt-ssp-config.conf
tools/topology/topology2/platform/intel/lnl.conf
tools/topology/topology2/platform/intel/mtl.conf
tools/topology/topology2/platform/intel/ptl.conf

Fix a bug in clock definitions for BT offload configurations. The BT_MCLK and link_control.clock_source definitions must match and this has not been the case for all ACE1.5+ scenarios.
The practical impacts are limited as this does not impact the common HFP NB/WB configuration, as the DSP is not the clock provider in these cases.
Impacts can be seen on ACE1.5+ with A2DP offload and BT HFP LBM test mode. Result is incorrect playback/capture speed.

topology2: intel: fix default BT clock for ACE1.5 and newer

---

src/drivers/intel/ssp/ssp.c

Update some ssp-related commits from cavs2.5-001-drop-stable to jsl-005-drop-stable.
(we didn't do cherry-picking from main directly because the code has been diverted by the age. cavs2.5-001-drop-stable is the nearest branch and has been verified as good.

[ported from cavs2.5-001-drop-stable] ssp-related changes

---

tools/rimage/src/module.c

Calculate and print percentage of cold text and data when building loadable modules.

rimage: print cold data and text percentage

---

src/audio/codec/dts/llext/CMakeLists.txt
src/audio/google/llext_ctc/CMakeLists.txt
src/audio/google/llext_rtc/CMakeLists.txt
src/audio/igo_nr/llext/CMakeLists.txt
src/audio/rtnr/llext/CMakeLists.txt

Third-party modules should be built individually
or in a separate vendor lib

llext: remove third-party modules from SOF lib

---

src/audio/src/src.c
src/audio/src/src_common.c
src/audio/src/src_ipc4.c

Mark further initialisation, configuration and freeing paths as "cold."

src: mark code as "cold"

---

src/include/module/module/interface.h

Document methods from struct module_interface to specify which methods can be attributed with __cold and which ones should stay "hot." No functional changes, so skipping run-time CI

[SKIP SOF-TEST] audio: add Doxygen comments for cold / hot module methods

---

tools/topology/topology2/production/tplg-targets-ace2.cmake
tools/topology/topology2/production/tplg-targets-ace3.cmake

The audio config is cs42l43 codec on SoundWire link 2, 3*cs35l56 amps on SoundWire link 1 and 3*cs35l56 amps on SoundWire link 3.

topology2: add sof-lnl-cs42l43-l2-cs35l56x6-l13.tplg support

---

src/library_manager/llext_manager.c

When copying LLEXT modules from DRAM to SRAM we allocate and copy .data and .bss together because they have the same access flags, but .bss doesn't have to be copied, this can in fact generate an error because it isn't present in the ELF image. Only copy valid sections.

library_manager: llext: don't try to copy .bss

---

src/include/sof/lib_manager.h
src/library_manager/llext_manager.c

This PR tries to improve SOF by minimizing its dependency on LLEXT internals. 
Instead of relying on direct field access, the code in `llext_manager.c` is refactored to use a set of new, stable LLEXT APIs that expose the same information. These code changes should have no measurable effects in the rest of SOF.
[LNL test passed](https://sof-ci.01.org/sofpr/PR9831/build10984/devicetest/index.html) as of commit 23478ef20cb4390c7bbfd62a9e19288077794c79.

 llext: use the new inspection API

---

src/audio/volume/volume.c

Need to use "volume4" explicitly in SOF_LLEXT_MODULE_MANIFEST().

audio: volume: fix PEAKVOL UUID with LLEXT

---

src/audio/asrc/asrc.c
src/audio/asrc/asrc_farrow.c
src/audio/asrc/asrc_farrow.h
src/audio/asrc/coef/asrc_farrow_coeff_24000Hz_to_08000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_24000Hz_to_16000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_44100Hz_to_48000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_08000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_11025Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_12000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_16000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_22050Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_24000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_32000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_44100Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_48000Hz_to_48000Hz.h
src/audio/drc/drc.c
src/audio/multiband_drc/multiband_drc.c
src/audio/multiband_drc/multiband_drc_ipc4.c
src/audio/src/src.c
src/audio/src/src_common.c
src/audio/src/src_ipc4.c

Move ASRC filter coefficients and some DRC functions to DRAM

ASRC: move to DRAM

---

src/library_manager/lib_manager.c

Don't type-cast pointers to "const" objects to writable pointers even temporarily. This is error-prone and might cause future compiler warnings.

lib-manager: don't cast away "const"

---

src/audio/codec_adapter/codec/waves.c

Missing commits. Backport to jsl branch to align the pipeline 48 frames buffers.
Scheduling period should be acquired from dev->pipeline->period
(backport from commit 285df36f1b435278cd230500385d4bd9f515c56f)

[jsl-005-drop-stable] codec_adapter: correct the way to get the scheduling period

---

tools/topology/topology2/production/CMakeLists.txt
tools/topology/topology2/production/tplg-targets-ace1.cmake
tools/topology/topology2/production/tplg-targets-ace2.cmake
tools/topology/topology2/production/tplg-targets-ace3.cmake
tools/topology/topology2/production/tplg-targets-sdca-generic.cmake
tools/topology/topology2/sof-hda-generic.conf

Add topologies for each sdca function. Linux kernel will load the corresponding topology per sdca function. The naming rule is sof-<platform>-<function>-<BE id>

Topology2: add topologies for SDCA functions

---

tools/plugin/README.md

This PR corrects broken heading formatting in the SOF ALSA plugin `README.md`. 
The previous formatting caused improper Markdown rendering due to missing spaces
after `#` and inconsistent heading levels.  
- Added missing spaces after `#` to ensure proper Markdown parsing.  
- Adjusted heading levels (`#`, `##`, `###`) to reflect correct title priorities.  
These are purely formatting fixes—no content modifications were made.  
Let me know if any further improvements are needed!

tools/plugin: Fix broken README.md formatting

---

src/audio/module_adapter/module/waves/waves.c

Save the blob into the cache and ensure that MaxxEffect_Message
is not called before MaxxEffect_Initialize to avoid returning
an error code from MaxxEffect_Message.

waves: avoid calling MaxxEffect_Message before MaxxEffect_Initialize

---

src/audio/asrc/CMakeLists.txt
src/audio/asrc/asrc.c
src/audio/asrc/asrc_farrow.c
src/audio/asrc/asrc_farrow_generic.c
src/audio/asrc/asrc_farrow_hifi3.c
src/audio/asrc/asrc_farrow_hifi5.c
src/audio/asrc/coef/asrc_farrow_coeff_4x_24000Hz_to_08000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_24000Hz_to_16000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_44100Hz_to_48000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_08000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_11025Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_12000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_16000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_22050Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_24000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_32000Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_44100Hz.h
src/audio/asrc/coef/asrc_farrow_coeff_4x_48000Hz_to_48000Hz.h
zephyr/CMakeLists.txt

Now ready, please check the commit messages for changes in every patch.

Audio: ASRC: HiFi5 optimizations

---

src/audio/chain_dma.c

Implementation of get_connector_node_id() incorrectly assumes link and host DMA channel counts are always the same. Modify the implementation to look up the host and link properties separately.
Link: https://github.com/thesofproject/sof/issues/9883

audio: chain_dma: don't mix link/host HDA DMA channel counts

---

src/audio/kpb.c
src/include/sof/audio/kpb.h

Mainly two fixes:
* Avoid long seizure of EDF scheduler thread.
The draining task could run for quite a long time (e.g., a few seconds). It is implemented as an EDF scheduler task. While working, it blocks other EDF scheduler tasks: the IPC processing task and the mtrace logging task. The fix replaces the while loop in the draining task with a return SOF_TASK_STATE_RESCHEDULE, so other EDF scheduler tasks can have CPU time.
* Fix drain interval calculation
The previous drain interval calculation ignored the actual DSP load by LL and only worked for light LL loads (high DSP clock). The drain interval was not appropriate for slow FPGA, where LL takes half of the DSP time. This update introduces code that dynamically readjusts the drain interval and does not depend on LL load (works on low …

kpb: KPB fixes

---

tools/mtrace/mtrace-reader.c

Add a C implementation of mtrace-reader.py for use in environments where Python is not available.
No Cmake rules added as the mtrace-reader.py remains the preferred tool to use.

tools: mtrace-reader.c: add C version of mtrace-reader.py

---

scripts/llext_link_helper.py
zephyr/CMakeLists.txt

Cold sections within LLEXT modules should be page-size aligned to allow setting permission flags. They're never copied after being initially placed in DRAM, so alignment should happen already in ELF files.

llext: fix alignment of cold / detached sections

---

tools/testbench/README.md

Updated `tools/testbench/README.md` to include missing dependencies
for Ubuntu/Debian and Fedora. This ensures users can install the
required packages beforehand, avoiding setup issues.
Running `scripts/host-testbench.sh` failed due to missing dependencies  
like `octave`, `valgrind`, and `signal` package in Octave. This update  
helps prevent similar errors for newcomers.  
Attached screenshots show the errors encountered before installing  
the missing dependencies: 
Let me know if any modifications are needed.

tools: testbench: Add missing dependencies in README.md

---

tools/plugin/README.md

This PR fixes a broken OpenVINO noise suppression model link in  
`sof/tools/plugin/README.md`. The previous link was inaccessible,  
preventing users from completing the OpenVINO noise suppression
setup. The link has been updated to the correct version.  
- Replaced:  
**Old (broken) link:**  
https://docs.openvino.ai/archive/2023.0/omz_demos.html#build-the-demo-applications-on-linux
**New (working) link:**  
https://docs.openvino.ai/2023.3/omz_demos.html#a-name-build-demos-linux-a-build-the-demo-applications-on-linux  
- Verified that the new link is accessible and leads to the correct  
OpenVINO documentation page.

tools: plugin: Fix broken OpenVINO model link in README.md

---

Kconfig.sof
src/ipc/ipc4/handler.c

Kconfig option DEBUG_IPC_TIMINGS to add logging after IPC handling right before sending IPC reply. The logging contains both the reply and the original request message headers and the time that it took to process the request in micro seconds. The value can be used to collect statistics on changes in firmware response times. This also disables the logging of the received request on core 0 to avoid flooding the logs too much.

ipc4: handler: Kconfig option to add IPC processing timing prints

---

src/audio/multiband_drc/multiband_drc.c
src/audio/multiband_drc/multiband_drc_ipc4.c
src/audio/src/src.c
src/audio/src/src_common.c
src/audio/src/src_ipc4.c
src/include/module/module/interface.h
src/include/sof/ipc/topology.h
src/init/init.c
src/ipc/ipc-common.c
src/ipc/ipc-helper.c
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c
src/platform/intel/ace/platform.c
zephyr/include/sof/lib/memory.h

Move all of IPC and some initialisation code to DRAM.

DRAM: more cold functions

---

west.yml

Total of 432 commits.
3df1ffe1d5b xtensa: mmu: Fix partition permission definitions 
6249470b669 intel_adsp: ace30: mm: Set write permissions during memory mapping
e7f2e1412d5 soc: intel_adsp: set MMU permissions for .cold* sections

west.yml: update zephyr to 0837ad5be84

---

src/audio/eq_iir/tune/sof_eq_blob_plot.m
src/audio/eq_iir/tune/sof_eq_blob_read.m
src/audio/eq_iir/tune/sof_mls_freq_resp.m

The main fix is for failure of full test of process_test() for EQ components. See commit texts for descriptions.

Audio: EQIIR: Tune: Small fixes and improvements

---

src/include/sof/math/exp_fcn.h
src/math/exp_fcn.c
src/math/exp_fcn_hifi.c

Bodgan was a key contributor to the new exponent calculation algorithm so adding him as well!

Math: Exp: Add contributor to sofm_exp_approx()

---

src/audio/copier/host_copier.h
src/audio/host-zephyr.c
src/include/sof/ipc/topology.h
src/ipc/ipc-common.c
src/ipc/ipc-helper.c
src/ipc/ipc4/handler.c
src/ipc/ipc4/helper.c

fix IPC timeouts and move IPC processing back to DRAM

fix IPC timeouts

---

posix/include/sof/lib/memory.h
src/debug/CMakeLists.txt
src/debug/dram.c
src/debug/gdb/CMakeLists.txt
src/debug/tester/CMakeLists.txt
src/idc/idc.c
src/ipc/ipc-zephyr.c
src/ipc/ipc4/handler.c
xtos/include/sof/lib/memory.h
zephyr/CMakeLists.txt
zephyr/include/sof/lib/memory.h

Additional DRAM / cold code debugging. This allows to designate and verify and run-time interval as performance-critical and banned for DRAM code. ATM this includes #9850 , will remove once merged

DRAM debug take 2

---

tools/rimage/config/imx95.toml

For imx95, the firmware is meant to be put in SRAM instead of the DRAM. Fix this.
When https://lore.kernel.org/linux-arm-kernel/20241216145039.3074-1-laurentiumihalcea111@gmail.com/T/ and
https://lore.kernel.org/imx/20250203171808.4108-10-laurentiumihalcea111@gmail.com/T/ will land, the SOF imx95 driver will expect the firmware to be placed in SRAM instead of DRAM. Make appropriate changes to rimage.

rimage: configs: imx95: use SRAM instead of DRAM

---

tools/plugin/README.md

The current documentation suggests setting the
NOISE_SUPPRESSION_MODEL_NAME variable using a quoted tilde (~):
`export NOISE_SUPPRESSION_MODEL_NAME="~/path/to/model.xml"  `
However, when quoted, ~ is not expanded to the home directory,
causing ls -l $NOISE_SUPPRESSION_MODEL_NAME to fail with
"No such file or directory." & Getting error while testing OpenVino noise 
suppression model with the SOF plugin.
The correct way to set this variable is without quotes:
`export NOISE_SUPPRESSION_MODEL_NAME=~/path/to/model.xml  `
This ensures the path expands correctly.
Manually tested by setting the variable and verifying with ls -l.
This PR updates the documentation accordingly.

[SKIP SOFCI-TEST] tools: plugin: Fix incorrect tilde expansion in environment variable

---

posix/include/sof/lib/memory.h
src/debug/dram.c
src/idc/idc.c
src/ipc/ipc-zephyr.c
src/ipc/ipc4/handler.c
xtos/include/sof/lib/memory.h
zephyr/include/sof/lib/memory.h

Rename debugging functions to clearly indicate their debugging purpose.

[SKIP SOF-TEST] dram: (cosmetic) rename debugging with dbg_

---

src/audio/chain_dma.c

Move non-performance critical functions to DRAM.
Note, that `chain_task_create()` is one of the largest functions in the image, so moving it to DRAM frees a significant amount of SRAM

chain-dma: move .init() and .free() into DRAM

---

tools/plugin/README.md

This PR updates the README with additional information regarding the setup for testing the OpenVino noise suppression model with the SOF plugin.
- Added information to ensure `LD_LIBRARY_PATH` includes `build-plugin/modules/ov_noise_suppression`
- Specified that `OpenVINO_DIR` should be set properly to include CMake files like `OpenVINOConfig.cmake` for building plugins
- Added instructions for building the XML model file by building the Open Model Zoo demo applications
These changes aim to make the setup process clearer and easier for users.
Testing:
- Tested all steps and successfully ran OpenVino noise suppression model
with SOF plugin.

tools: plugin: Update README for OpenVino noise suppression

---

posix/include/rtos/idc.h
src/idc/idc.c
xtos/include/rtos/idc.h
zephyr/include/rtos/idc.h

IDC implementation has moved on with Zephyr on Intel platforms. Clean up and remove code to reflect that.

intel: idc: removal of xtos related Intel IDC code. 

---

src/audio/module_adapter/module_adapter.c
src/audio/src/src_ipc4.c

For DP there's a crucial part to properly estimate period that the module will be called. Period value is used in several places in DP scheduling
There were 3 defects:
1) period should always be a multiplication of LL cycle, currently 1000us. If estimated period is i.e. 1300us, it should be aligned down to 1000
2) periods lower that 1LL cycle is not allowed, DP scheduler is triggered from LL 
3) for some enormous high bitrates, like 192KHz/8 channels, there was an 32bit overflow in period calculations

bugfix in DP/Src: some audio formats have incorrectly estimate period

---

src/audio/base_fw.c
src/audio/base_fw_intel.c
src/audio/copier/copier.c
src/audio/copier/copier_dai.c
src/audio/copier/copier_gain.c
src/audio/copier/copier_generic.c
src/audio/copier/copier_hifi.c
src/audio/copier/copier_host.c
src/audio/copier/copier_ipcgtw.c
src/audio/dai-zephyr.c
src/audio/host-zephyr.c
src/include/sof/audio/component.h
src/ipc/ipc4/dai.c
src/lib/dai.c

DAI, host and copier code is always hard linked into the base firmware image, never as loadable modules. Move a large part of non-performance critical code to DRAM

audio: move more code to DRAM

---

src/lib/CMakeLists.txt
src/library_manager/CMakeLists.txt
src/logging/CMakeLists.txt
src/probe/CMakeLists.txt
src/samples/audio/CMakeLists.txt
src/trace/CMakeLists.txt
zephyr/CMakeLists.txt

Last set of Zephyr cmake changes. This has all the commits from #9918. The gdb rule change is not included as @lyakh has those in #9907 .
UPDATE: #9918 and #9907 merged, so dependencies are all in main

cmake/zephyr: unify cmake rules for lib, probes and... 

---

src/platform/mtk/platform.c

Fix crash [thesofproject#9933](https://github.com/thesofproject/sof/issues/9933) in DEBUG build on MTK platform.
ipc_init() must be called after scheduler_init_ll().

platform: mtk: Fix crash in DEBUG build on MTK platform

---

src/audio/aria/aria.c
src/audio/asrc/asrc.c
src/audio/codec/dts/dts.c
src/audio/crossover/crossover.c
src/audio/dcblock/dcblock.c
src/audio/drc/drc.c
src/audio/eq_fir/eq_fir.c
src/audio/eq_iir/eq_iir.c
src/audio/google/google_ctc_audio_processing.c
src/audio/google/google_rtc_audio_processing.c
src/audio/igo_nr/igo_nr.c
src/audio/mfcc/mfcc.c
src/audio/mixin_mixout/mixin_mixout.c
src/audio/module_adapter/module/waves/waves.c
src/audio/multiband_drc/multiband_drc.c
src/audio/mux/mux.c
src/audio/rtnr/rtnr.c
src/audio/selector/selector.c
src/audio/src/src.c
src/audio/src/src_lite.c
src/audio/tdfb/tdfb.c
src/audio/volume/volume.c
src/debug/tester/tester.c
src/probe/probe.c
src/samples/audio/smart_amp_test_ipc4.c

All module adapter drivers interface with the infrastructure using entries similar to
DECLARE_MODULE_ADAPTER(src_interface, SRC_UUID, src_tr); SOF_MODULE_INIT(src, sys_comp_module_src_interface_init);
which create instances of struct comp_driver and define several functions. They aren't needed when built as a LLEXT module.

llext: remove unneeded data and functions

---

src/audio/drc/drc_math_generic.c
src/audio/drc/drc_math_hifi3.c

"inline" without "static" suggests that the function is inlined when called in the same file and will also be compiled out-of-line to be called from other files. This wasn't intended in drc_math_hifi3.c nor in drc_math_generic.c because in most cases those functions are never even called in those files. Remove "inline."

audio: drc: clean up "inline" usage in .c

---

src/audio/volume/volume.c

Commit https://github.com/thesofproject/sof/commit/fcfcb0770e883e05086dee137eb06903c58041ea ("llext: remove unneeded data and functions")
introduced some "ifdef" guards that make the volume component unusable
unless "CONFIG_COMP_GAIN" or "CONFIG_COMP_PEAK_VOL" is enabled. This
change in behavior results in the following error on the firmware side:
<ERROR_MSG>
<err> ipc: get_drv(): the provided UUID (b77e677e41885ff4a8fb14af8286bfbd)
doesn't match to any driver!
</ERROR_MSG>
for an i.MX platform using the volume component with "CONFIG_COMP_GAIN=n"
and "CONFIG_COMP_PEAK_VOL=n".
Based on the Kconfig description, "CONFIG_COMP_GAIN" refers to the gain
component, while "CONFIG_COMP_PEAK_VOL" refers to (snippet taken from the
volume Kconfig): "This option enables reporting to host peak vol …

audio: volume: drop CONFIG_COMP_PEAK_VOL guards

---

zephyr/CMakeLists.txt

Pass includes, cflags, libraries and library paths to llext target. This will permit linking external libraries to llext modules.

llext: cmake: Add support for passing more config to llext build

---

scripts/gen-doc.sh

Build the sof docs outside of the source directory and within a Python virtual environment.

sof-docs: build out of source directory

---

src/audio/module_adapter/module/modules.c
src/audio/module_adapter/module_adapter.c
src/include/sof/lib_manager.h
src/library_manager/lib_manager.c

Simplyfy module instance allocate functions by extend the `lib_manager_get_instance_bss_address function` to also return the size of the `bss` section. This simplify the `lib_manager_allocate_module_instance` and `lib_manager_free_module_instance` functions.
Remove redundant value assignment to `ops.prepare` in the `lib_manager_register_module` function. This value is already set by the `lib_manager_prepare_module_adapter` function.
Fix memory leak in lib_manager_register_module - free allocated driver structure when an unsupported loadable module api version is detected.
Add verification of the module id passed as a parameter to the `lib_manager_get_mod_ctx` function. Add error handling to the
`lib_manager_free_module` function.
Fix memory leak in `module_adapter_new` - add missing …

lib_manager: Set of small fixes for loadable modules (sp1)

---

scripts/xtensa-build-zephyr.py

Add support to build menuconfig from the convenience script. This makes it easier to use the same environment for config and build which is especially useful if using non open compilers.

scripts: xtensa build: add support to build menuconfig

---

tools/test/audio/tdfb_enable.sh
tools/test/audio/tdfb_test.m

Here's some fixes needed to validate recent HiFi5 changes.

Tools: Test: Audio: Fixes for TDFB component tests

---

src/audio/audio_stream.c

audio_stream_recalc_align() is called from micsel, which can be build as a module, export it.

llext: export audio_stream_recalc_align()

---

tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/development/tplg-targets.cmake
tools/topology/topology2/include/common/tokens.conf
tools/topology/topology2/include/components/widget-common.conf

NOTE: https://github.com/thesofproject/linux/pull/5382 is needed before this PR does anything.
The PR defines a new topology2 attribute for any widget. With the scheduler_domain attribute one can select if the component defined by the widget node is execute in Low Latency thread or in Data Processing mode. The PR also adds new test topologies for testing the DP mode.

Topology2 sched domain support

---

tools/topology/topology2/platform/intel/deep-buffer.conf
tools/topology/topology2/production/tplg-targets-ace3.cmake

The topology supports rt712_vb multi-function codec and rt1320 on SoundWire link 3 and shareing the sdw3-clock, sdw3-data[0] and sdw3-data[1] data lanes.

Topology2: Add sof-ptl-rt712-l3-rt1320-l3 support

---

src/audio/module_adapter/module/cadence.c

cadence_code_get_api_id() is only used with IPC3, move it to the respective preprocessor branch.

audio: cadence: fix IPC4 build

---

scripts/xtensa-build-zephyr.py

Remove the Intel EHL platform from list of aliases. This platform is supported from old stable-v2.2 branch and upgrade to IPC4 is not planned.

build: xtensa-build-zephyr.py: remove Intel ehl target

---

tools/topology/topology2/cavs-nocodec.conf

The purpose of PASSTHROUGH is to exclude processing modules from paths, but in case of the nocodec topologies the PASSTHROUGH enables formats on the SSP DAI side for which we don't have a blob generated and no hw_config either.
We only really support in this mode S32_LE and nothing else, S16_LE and S24_LE formats are invalid.
Support only S32_LE on dai side only and do the conversion if needed on the host side so all internal (non-)processing is 32bit.
Link: https://github.com/thesofproject/sof/issues/9979

tools: topology2: cavs-nocodec: Fix PASSTHROUGH configuration for SSPs

---

src/audio/module_adapter/module/cadence.c

This patch eliminates the unused variables `ret` and `codec_params` from the `cadence_codec_resolve_api` function in the cadence module.

audio: cadence: ipc4: remove unused variables

---

src/audio/template_comp/template.c

This patch adds comments that there may be more than one input and/or output.

Audio: Template_comp: Add note about inputs and outputs number

---

src/audio/igo_nr/igo_nr.c
src/audio/smart_amp/smart_amp.c
src/audio/smart_amp/smart_amp_generic.c
src/ipc/ipc4/helper.c
src/platform/posix/ipc.c

Fixes to IGO NR, Smart Amp, IPC4 Helper, POSIX IPC to fix stub-build check.

global: Avoid warnings about unused variables

---

tools/plugin/README.md

Replace completed ones with new items.

tools: plugin: Fix TODOs in README

---

tools/testbench/README.md
tools/testbench/include/testbench/utils.h
tools/testbench/utils.c
tools/testbench/utils_ipc3.c
tools/testbench/utils_ipc4.c

With this change sof-ctl commands can be executed during sof-testbench4 simulation, e.g.
sof-ctl -c name='Post Mixer Analog Playback IIR Eq bytes' \ -s tools/ctl/ipc4/eq_iir/loudness.txt
No other than switches -c and -s are supported for simulated sof-ctl. The blob file must be in normal comma separated ASCII uint32_t numbers format with nothing else in it.
With this change the SOF processing components can be tested extensively for their controls during simulated audio streaming.

Tools: Testbench: Add sof-ctl simulation to control scripts

---

west.yml

After commit
f726cb5123eda12fe ("modules: CMSIS_6: Switch to CMSIS_6 for Cortex-M") SOF needs cmsis_6 to be used for Cortex-M (imx95).
So import cmsis_6 and fix the compilation error.
Fixes: https://github.com/thesofproject/sof/issues/10014

west.yml: Import cmsis_6 to be used by SOF for Cortex-M targets

---

src/audio/CMakeLists.txt
src/audio/Kconfig
src/audio/nxp/CMakeLists.txt
src/audio/nxp/Kconfig
src/audio/nxp/eap.c
src/audio/nxp/eap_stub.c
src/include/sof/audio/component.h
src/include/sof/audio/nxp/eap/EAP_Parameter_presets.h
src/include/sof/audio/nxp/eap/eap_lib_defines.h
third_party/include/nxp/eap/EAP_Includes/EAP16.h
third_party/include/nxp/eap/EAP_Includes/EAP32.h
third_party/include/nxp/eap/EAP_Includes/LVC_Types.h
tools/topology/topology1/CMakeLists.txt
tools/topology/topology1/m4/eap.m4
tools/topology/topology1/m4/eap_controls.m4
tools/topology/topology1/sof/pipe-eap-playback.m4
uuid-registry.txt

comp: Add initial NXP Essential Audio Processing component
NXP’s Essential Audio Processing (EAP) library is a bundle of audio
processing blocks for enhancing the tonal and spatial perception
of sound in audio applications
The initial support adds some presets parameters that can be set
using the standard alsamixer interface.
* AllEffectOff
* VoiceEnhancer
* MusicEnhancer
* AutoVolumeLeveler
* ConcertSound
* LoudnessMaximiser
Library binaries, headers and more documentation can be found here: https://github.com/nxp-mcuxpresso/EAP

comp: Add initial support for NXP Essential Audio Processing component

---

src/audio/dai-zephyr.c
src/audio/host-zephyr.c
src/include/sof/audio/audio_stream.h

The HDA DMA hardware keeps track of data in the DMA buffer using hardware Read and Write Position registers. The software uses the struct audio_stream with w_ptr and r_ptr for a similar purpose. If the software w_ptr and r_ptr do not point to the same location as the hardware Write and Read Position registers, the problem occurs.
Such desynchronization happens upon a pipeline reset. The dma_buffer is freed during a reset in dai-zephyr or host-zephyr and reallocated in prepare() after the pipeline resume. The reallocated dma_buffer has w_ptr and r_ptr set to NULL, while the hardware HDA DMA Read and Write Position registers retain their values.
If, for example, in the DAI playback case, the difference between the Write Position register and w_ptr is more than one period, the problem could …

hda-dma: Fix HDA DMA position regs going out of sync with w_ptr/r_ptr

---

src/audio/dai-zephyr.c
src/audio/host-zephyr.c
src/include/sof/audio/audio_stream.h

The HDA DMA hardware keeps track of data in the DMA buffer using hardware Read and Write Position registers. The software uses the struct audio_stream with w_ptr and r_ptr for a similar purpose. If the software w_ptr and r_ptr do not point to the same location as the hardware Write and Read Position registers, the problem occurs.
Such desynchronization happens upon a pipeline reset. The dma_buffer is freed during a reset in dai-zephyr or host-zephyr and reallocated in prepare() after the pipeline resume. The reallocated dma_buffer has w_ptr and r_ptr set to NULL, while the hardware HDA DMA Read and Write Position registers retain their values.
If, for example, in the DAI playback case, the difference between the Write Position register and w_ptr is more than one period, the problem could …

[stable-v2.13] hda-dma: Fix HDA DMA position regs going out of sync with w_ptr/r_ptr.

---

tools/rimage/src/manifest.c

Add support for ace 1.5 manifest to resign_image function. Subtract the number of skipped bytes from the file size to avoid going
beyond of memory buffer. Copy data preceding the cse header to the output file to preserve extended manifest.

rimage: Add support for resigning ace manifest

---

src/audio/mic_privacy_manager/mic_privacy_manager_intel.c
src/include/sof/audio/mic_privacy_manager.h
zephyr/lib/cpu.c

This PR fixes two issues with the microphone privacy feature during D3 state transitions:
1. Re-establishes proper microphone privacy functionality after D3 resume by:
- Re-initializing the `mic_privacy_manager` in the `resume_dais()` function
- Restoring privacy settings after D3 transitions
- Re-enabling privacy IRQ handlers to ensure continued operation
2. Eliminates unwanted fade effect in audio when resuming from D3 with privacy enabled by:
- Force setting `mic_privacy_state` to `MUTED` without fade effects
These changes ensure microphone privacy works reliably through power state transitions and correctly mutes audio without any fade artifacts when privacy is enabled.

audio: mic_privacy: Fix incorrect state after D3 exit

---

src/audio/mic_privacy_manager/mic_privacy_manager_intel.c
src/include/sof/audio/mic_privacy_manager.h
zephyr/lib/cpu.c

When resuming from D3 state, the microphone privacy feature wasn't properly restored, causing two critical issues:
1. The system didn't respond to privacy button inputs after D3 transitions
2. A short fade-out effect appeared in audio when privacy was enabled, causing test failures that expected complete silence
This patch provides a comprehensive solution by:
- Adding mic_privacy_manager_init() to resume_dais() to ensure proper re-initialization of the microphone privacy subsystem after D3
- Implementing mic_privacy_get_mic_disable_status() to correctly retrieve the current microphone disable status
- Storing the mic_disable_status before entering D3 and comparing it after resume to detect changes during low power state
- Enhancing mic_privacy_enable_dmic_irq() to immediately check for …

[stable-v2.13] audio: mic_privacy: Fix feature functionality after D3 resume

---

zephyr/lib/cpu.c

When transitioning to D3 state with a pipeline containing a DAI that supports microphone privacy but is in HW-managed mode, the DSP can panic. This occurs because the mic_privacy_get_mic_disable_status() function is called unconditionally during suspend/resume regardless of the privacy mode.
Fix the issue by explicitly checking for
mic_privacy_manager_get_policy() == MIC_PRIVACY_FW_MANAGED before attempting to save/restore the mic disable status. This ensures we only interact with the privacy status when the firmware is responsible for managing it, and allows HW-managed configurations to properly transit through D3 power states without exceptions.
This is a small but critical fix to the previous microphone privacy D3 resume patch, addressing panic cases observed with HDA and SoundWire …

audio: mic_privacy: Fix DSP panic during D3 entry with HW managed mode

---

zephyr/lib/cpu.c

When transitioning to D3 state with a pipeline containing a DAI that supports microphone privacy but is in HW-managed mode, the DSP can panic. This occurs because the mic_privacy_get_mic_disable_status() function is called unconditionally during suspend/resume regardless of the privacy mode.
Fix the issue by explicitly checking for
mic_privacy_manager_get_policy() == MIC_PRIVACY_FW_MANAGED before attempting to save/restore the mic disable status. This ensures we only interact with the privacy status when the firmware is responsible for managing it, and allows HW-managed configurations to properly transit through D3 power states without exceptions.
This is a small but critical fix to the previous microphone privacy D3 resume patch, addressing panic cases observed with HDA and SoundWire …

[stable-v2.13] audio: mic_privacy: Fix DSP panic during D3 entry with HW managed mode

---

src/audio/module_adapter/module_adapter.c

Remove a check for an impossible condition and make code clearer. The check became redundant after 097405872507 ("module_adapter: Don't propagate ENOSPC and ENODATA error codes"). Presence of redundant checks makes code confusing.

module-adapter: remove a superfluous check

---

.github/workflows/close-stale.yml

Add workflow to close stale issues.
Workflow will first mark the issue as stale if there is no activity for 60 days, and close it after the next 14 days if no action is taken.
Successful close-stale.yml dry-run [thesofproject/sof/actions/runs/15581796351/job/43878613576?pr=10051](https://github.com/thesofproject/sof/actions/runs/15581796351/job/43878613576?pr=10051)
Signed-off-by: Mateusz Redzynia <mateuszx.redzynia@intel.com>

[SKIP SOFCI-TEST] close-stale: close stale issues with workflow

---

.github/workflows/testbench.yml

The 24.10 runner availability is not great and 24.10 is not strictly needed, so use 24.04LTS instead.

[SKIP SOFCI-TEST] .github: workflow: use 24.04LTS for testbench build

---

scripts/host-testbench.sh

This add ensures that basic functionality of the template component is tested regularly.

Scripts/host-testbench: Add test run for template_comp

---

tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/development/tplg-targets.cmake

This commit creates three new topologies, sof-mtl-nocodec-dp-core-test.tplg, sof-lnl-nocodec-dp-core-test.tplg, and sof-ptl-nocodec-dp-core-test.tplg.
They are otherwise the same as the corresponding standard nocodec topologies, but both the src.11.1 on SSP2_Playback and src.5.1 on SSP2 Capture have scheduler_domain attribute set to "DP" and core_id to 1.
This configuration executes SRC components for playback and capture to/from hw:0,2 on DSP core 1 in Data Processing mode, while the rest of the SSP2 pipelines are executed on DSP core 2.

Topology2: Add nocodec DP core 1 test topologies for MTL, LNL, and PTL

---

tools/topology/topology2/production/tplg-targets-ace3.cmake

topology2: add support for cs42l43-sdw topology
Adding topology support for cs42l43-sdw monolithic codec at l3
Verified on ptl & wcl-bep platforms for configuration:
1. sof-ptl-cs42l43-l3: uses SDW-DMIC
2. sof-ptl-cs42l43-l3-4ch: uses PCH-DMIC
md5sum sof-ptl-cs42l43-l3-4ch.tplg 1c1b8eb8758a1827bc8f9748826496a8
md5sum sof-ptl-cs42l43-l3.tplg fa54c27123619df1bfff47c8f2bad3d4

WCL BEP CS42l43 Topology

---

tools/topology/topology2/production/tplg-targets-ace2.cmake

This topology support for rt1320 left, right amplifiers on two Soundwire link 1, 2 and rt714 dmic codec on Sounwire link 0. No JACK codec and rt1320 AMP_IN capture DAI is unused.

topology2: add support for sof-lnl-rt1320-l12-rt714-l0

---

scripts/docker_build/zephyr_lite/Dockerfile
zephyr/docker-run.sh

Change docker image used in zephyr workflows to zephyr-lite built for the sof project.
zephyr-lite contains less toolchains compared to zephyr-build to fit into 14GB max storage of free tier runners.
Final size of zephyr-lite is appx 10.5GB vs 16.2GB of zephyr-build.
List of toolchains left in the docker:
```bash
aarch64-zephyr-elf
arm-zephyr-eabi
xtensa-amd_acp_6_0_adsp_zephyr-elf
xtensa-intel_ace15_mtpm_zephyr-elf
xtensa-intel_ace30_ptl_zephyr-elf
xtensa-intel_tgl_adsp_zephyr-elf
xtensa-mtk_mt8195_adsp_zephyr-elf
xtensa-nxp_imx8m_adsp_zephyr-elf
xtensa-nxp_imx8ulp_adsp_zephyr-elf
xtensa-nxp_imx_adsp_zephyr-elf
xtensa-nxp_rt500_adsp_zephyr-elf
xtensa-nxp_rt600_adsp_zephyr-elf
xtensa-nxp_rt700_hifi1_zephyr-elf
xtensa-nxp_rt700_hifi4_zephyr-elf
```
New docker also includes python3.12 which …

[SKIP SOFCI-TEST] zephyr: docker: change docker image to zephyr-lite

---

app/os_linux_overlay.conf

Add an OS overlay for Linux. This overlay configures SOF to be used with SOF Linux kernel driver. The overlay modifies Kconfig configuration options to align with requirements of of the Linux driver.
Similar overlays may be added later for other OS'es.

app: add os_linux_overlay.conf

---

src/audio/chain_dma.c
src/audio/copier/host_copier.h
src/include/sof/ipc/common.h
src/include/sof/lib/dai-zephyr.h
src/ipc/ipc3/host-page-table.c
src/lib/dma.c
src/library_manager/lib_manager.c
src/platform/imx8m/lib/dma.c
src/platform/posix/dma.c
zephyr/include/sof/lib/dma.h
zephyr/lib/dma.c

Add "sof_" namespace to dma_get()/put() in the Zephyr native drivers builds. The main "struct dma" is also renamed, so this touches quite many places in code.
V2 of https://github.com/thesofproject/sof/pull/9728. Now that XTOS code is removed (see https://github.com/thesofproject/sof/issues/9983 ), this is now a very simple patch. No need for ugly typedefs anymore.
I ketp the NATIVE_DRIVERS bits still in the codebase, but that's obviously the next bit that can be removed (along with dai-legacy.c and host-legacy.c -- and their dependencies).

treewide: zephyr: add sof_ prefix to dma_get/put() and struct dma

---

src/audio/pcm_converter/pcm_converter_generic.c
src/audio/pcm_converter/pcm_converter_hifi3.c

Enables missing FLOAT <--> s24_4LE conversions. Other conversions between FLOAT and integer formats, such as FLOAT <--> s16 and FLOAT <--> s32, have already been enabled.

pcm_conv: Enable conversion between FLOAT and s24_4LE

---

src/audio/module_adapter/iadk/system_agent.cpp
src/audio/module_adapter/library/native_system_agent.c
src/audio/module_adapter/module/modules.c
src/audio/module_adapter/module_adapter.c
src/include/sof/audio/module_adapter/iadk/system_agent.h
src/include/sof/audio/module_adapter/library/native_system_agent.h
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/lib_manager.h
src/library_manager/lib_manager.c

- Move module allocation and system agent call from modules_init to lib_manager_module_create to unify the module loading process.
- Add a bitmask to the LIB_MANAGER_GET_LIB_ID macro to discard the instance identifier placed on the high order bits of the component id.
- Create a function `module_adapter_new_ext` that allows to assign a pointer to the private data of the module for which the adapter is being created.
- Add missing include headers for list and component in lib_manager.
- Change type of the `entry_point` parameter in the `native_system_agent_start` and `system_agent_start` functions to uintptr_t which allows safe pointer passing.
- Change signature of the `native_system_agent_start` function to match with the `system_agent_start` function. The function returns an error code …

lib_manager: modules: Set of improvements for loadable module 

---

app/boards/imx95_evk_mimx9596_m7_ddr.overlay

Zephyr commit 774370a1d712 ("boards: nxp: imx95_evk_mimx9596_m7: add uart dma support") replaces the configuration of the "edma2" node with that mandated by the programming model associated with the "nxp,mcux-edma" compatible. This change was done because the EDMA driver associated with said compatible is compatible with multiple peripheral drivers as opposed to the previous "nxp,edma" driver.
However, SOF currently requires using the previous EDMA driver (i.e. the one associated with the "nxp,edma" driver). Therefore, switch back to the previous programming model.
Furthermore, the DMA channels used by the SAI IP were also changed. Since these were not tested, switch back to the previous DMA channels.

app: boards: imx95: switch to using nxp,edma driver

---

src/audio/kpb.c
src/audio/module_adapter/module_adapter.c
src/ipc/ipc4/handler.c
src/samples/audio/detect_test.c

The module_adapter_params() functions set the stream params based on the base config for each module which is available right after module init. So configure the params for IPC4 during module_new() and remove the call to ipc4_pipeline_params(). This should help with reducing the time to trigger pipelines during start.

src: audio: module_adapter: Do the params config right after init

---

src/ipc/ipc4/logging.c

This patch addresses an issue with the logging backend initialization in the `ipc4/logging.c` file. The previous implementation used `log_backend_activate`, which does not fully enable the backend for log collection. This was initially masked by the fact that backends are currently autostarted, but disabling backend autostart would reveal that logs are not being collected as expected. By switching to `log_backend_enable`, the backend is correctly initialized, ensuring logs are collected reliably.
The use of `CONFIG_SOF_LOG_LEVEL` as a parameter does not impact runtime filtering, as it is not enabled, but it aligns with the current logging configuration practices.
This update fixes the logging backend initialization issue, ensuring reliable log collection within the SOF firmware, and …

ipc4: update logging backend management

---

src/audio/buffers/audio_buffer.c
src/audio/buffers/comp_buffer.c
src/audio/buffers/ring_buffer.c
src/include/sof/audio/audio_buffer.h

The 4 buffer operation sets: comp_buffer_source_ops, comp_buffer_sink_ops, ring_buffer_source_ops and
ring_buffer_sink_ops are pointed to by every buffer. Yet when initialising each of those buffers attempts are made to overwrite those global objects with the same pointers. So in practive when the first buffer is registered, it overwrites those object members, and then all further buffers inherit those changes. This works because those values are always the same, still this isn't a good practice. Assign those members statically and make objects constant instead.

audio: buffer: don't overwrite global objects

---

zephyr/Kconfig
zephyr/include/sof/lib/regions_mm.h
zephyr/lib/alloc.c
zephyr/lib/regions_mm.c

This PR does 2 things:
- removes MEM_REG_ATTR_SHARED_HEAP, add function stubs and  - to allow merging changes to zephyr
- forces buffers location in the very first memory region. This is required because of conflict of virtual addresses with loadable modules in case the platform has 5 cores

mem: workaround - remove MEM_REG_ATTR_SHARED_HEAP from SOF

---

.github/workflows/close-stale.yml
.github/workflows/daily-tests.yml

The XTOS-make-install job is removed from the daily tests
workflow since the workflow is no longer
present in the sof repo.
Signed-off-by: Christopher Turner <christopher.g.turner@intel.com>

[SKIP SOFCI-TEST] ci: Remove XTOS-make-install job from daily-tests workflow

---

src/audio/codec/dts/dts.c
src/audio/module_adapter/module/cadence.c
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module/waves/waves.c
src/audio/module_adapter/module_adapter.c
src/audio/src/src.c
src/audio/src/src_common.c
src/audio/src/src_common.h
src/audio/src/src_ipc3.c
src/audio/src/src_ipc4.c
src/audio/src/src_lite.c
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/schedule/ll_schedule_domain.h
zephyr/sof_shell.c

Module memory allocation API functions face lift. Once this is approved I go through the rest of the modules after SRC.

Module heap api

---

tools/topology/topology2/include/components/src_format_s32_convert_from_48k.conf

This patch fixes the issue in nocodec topologies with 48 kHz to 11.025 kHz capture.

Tools: Topology: SRC: Increase 48 kHz capture source buffer size

---

src/library_manager/lib_manager.c

module_adapter_free() called in lib_manager_module_free() frees the device object, dereferencing it after that is invalid and can lead to exceptions.

lib-manager: fix use-after-free

---

src/audio/template_comp/llext/CMakeLists.txt

The build of template component as module fails because of wrong and missing file names for needed source files for build.

Audio: Template component: Add missing llext sources

---

src/audio/template_comp/template-generic.c

The build of template-generic.c would fail if only S24_LE format would be enabled without S32_LE.

Audio: Template Comp: Fix build for CONFIG_FORMAT_S24LE only

---

posix/include/rtos/alloc.h
posix/include/rtos/userspace_helper.h
src/audio/buffers/ring_buffer.c
src/audio/module_adapter/module_adapter.c
src/audio/module_adapter/module_adapter_ipc4.c
src/include/sof/audio/component.h
src/include/sof/audio/module_adapter/module/generic.h
src/include/sof/audio/ring_buffer.h
src/include/sof/lib_manager.h
src/ipc/ipc4/helper.c
src/library_manager/lib_manager.c
zephyr/CMakeLists.txt
zephyr/Kconfig
zephyr/include/rtos/alloc.h
zephyr/include/rtos/userspace_helper.h
zephyr/lib/alloc.c
zephyr/lib/userspace_helper.c

- Introduce MMU shared memory heap commit splits system heap into two sections. One section which will contatin shareable data will be located in separate memory partition. Each non-privilidged module will obtain it in its private memory domain. In case of CONFIG_USERSPACE enabled, all memory is accessible form kernel space. For accessing it from user space we need to grant access to its explicitly. However there are some infrastructure components that could be shared between kernel and user spaces.
- Introduce driver heap for non-privileged modules. Non-privileged modules should be isolated each other. It means that module related data should be located in memory available for kernel and the owner module only. To manage access all such data should be allocated from single, separate …

userspace: Preparation for userspace loadable modules support

---

src/audio/kpb.c
src/audio/mixin_mixout/mixin_mixout_hifi3.c

If build format.h as generic without intrinsics, these modules fail to build due to no header included for HiFi3.

Audio: KPB, Mixin-Mixout: Fix missing HiFi3 header include

---

src/audio/volume/volume_hifi3.c
src/audio/volume/volume_hifi3_with_peakvol.c
src/audio/volume/volume_hifi4.c
src/audio/volume/volume_hifi4_with_peakvol.c

The AE_SRAI32R() right shift with round could cause the value to go over S24_LE range by one if the gain would be over one or 0 dB (only possible in IPC3). The rounding shift is unnecessary because the gain product is already rounded in the multiply instruction. The SRAI32() instruction does just the shift.
Fixes: f3e34039db4b ("Audio: Volume: Add IPC4 native Q1.31 mode
and optimize")

Audio: Volume: Fix a possible overflow in S24_LE format volume

---

src/ipc/ipc3/handler.c

Fix spinlock validation assertion failure during fuzzing on native_sim builds with IPC3.
Recent Zephyr commit added spinlock validation that detects context switching while holding spinlocks. This revealed that `ipc_pm_context_save` calls `arch_irq_lock` before the EDF work queue yields, causing:
ASSERTION FAIL [arch_irq_unlocked(key) || ...] Context switching while holding lock!
The hardware PM operations (arch_irq_lock, platform_timer_stop, etc.) are not needed for POSIX simulation environments. Extend the existing guard to exclude these operations when CONFIG_ZEPHYR_POSIX is defined.
This preserves PM functionality while avoiding spinlock violations in native simulation builds.

ipc3: Fix spinlock violation in PM context save on fuzzer

---

src/audio/module_adapter/Kconfig
src/audio/module_adapter/module/generic.c
src/audio/module_adapter/module_adapter.c
src/audio/src/src_common.c
src/include/module/module/base.h
src/include/sof/audio/module_adapter/module/generic.h
test/cmocka/src/audio/mixer/CMakeLists.txt
zephyr/sof_shell.c

I pushed this out for review already now even if there is more modules to convert, to get some early feedback from my additions and changes to the module resource API.

Module API additions and conversion of some modules to use them

---

tools/rimage/src/include/rimage/sof/user/manifest.h

Update `sof_man_module_type` to match the layout defined in the reference firmware. This includes <s>reordering and</s> extending the structure with new fields such as `domain_rtos`, `core_type`, `user_mode`, `large_param`, and `stack_on_bss`.
<s>The previously added `init_config` field (https://github.com/thesofproject/sof/commit/15ea48177a2b4cb93eaa9858e90a4da89f9f84b1), which had been added earlier using reserved bits has been moved to the end of the structure to avoid layout conflicts and maintain compatibility with the reference FW.
This change is required for ABI alignment but will cause CI failures due to the need for a software rebuild.</s>

manifest: rimage: Update manifest module type with reference FW state

---

tools/topology/topology2/cavs-nocodec.conf
tools/topology/topology2/cavs-rt5682.conf
tools/topology/topology2/cavs-sdw.conf
tools/topology/topology2/platform/intel/deep-buffer-default.conf
tools/topology/topology2/platform/intel/deep-buffer.conf
tools/topology/topology2/sof-hda-generic.conf

Related to #10221 and solving the issue found in #10165
Marking as draft, need to do more testing, but getting this out early as this impacts #10221 review process.

tools: topology2: move deepbuffer defaults to separate file

---

src/include/ipc4/header.h
src/ipc/ipc4/handler.c

Add definition for generic bytes control and fix the get functionality
The LARGE_CONFIG_GET for generic controls have been broken (no module implements it) because the information about the control's ID was not propagated to the modules.
kernel PR: https://github.com/thesofproject/linux/pull/5531

IPC4: add support for generic bytes control and fix LARGE_CONFIG_GET for generic controls.

---

test/cmocka/src/audio/mux/demux_copy.c
test/cmocka/src/audio/mux/mux_copy.c

After comp_check_eos() checks were added mux_copy and demux_copy started crashing. Add dummy pipeline with expect_eos = false to bypass the tests.
Fixes: d472d22b38a2 ("component: Add eos support in components copy function")

cmocka: mux_copy and demux_copy: Fix comp_check_eos() checking

---

zephyr/CMakeLists.txt

Xtensa L32R instruction requires the literal it loads to be located in memory before the L32R address. Such a requirement is usually satisfied by linker script rules which put literals sections before text sections in which they are used. LLEXT module builds do not use a linker script, and so correct placement of literals is ensured by a compilation option.

llext: Fix wrong literals placement in modules

---

west.yml

Total of 686 commits.
- **68be678c4b9** intel_adsp: tlb: Configure HPSRAM retention mode after power transitions
- **a1adced1c42** intel_adsp: ace: Remove redundant HPSRAM init from D3 restore
- **91d17f69312** kernel: add k_thread_absolute_deadline_set call
- **df40dff6fb1** arch: xtensa: clean up interrupt handling
- **827a4f73874** coredump: xtensa: Add support for ARCH_SUPPORTS_COREDUMP_STACK_PTR

west.yml: update zephyr to 5bef4a9d626

---

app/boards/intel_adsp_ace30_ptl.conf
src/audio/host-legacy.c
src/audio/host-zephyr.c

This patch introduces the Google RTC Audio Processing component into the PTL configuration for the SOF firmware. The component is added as a loadable module (`m`).
**Changes:**
- Added `CONFIG_COMP_GOOGLE_RTC_AUDIO_PROCESSING=m` to enable Google RTC Audio Processing.
- Included `CONFIG_GOOGLE_RTC_AUDIO_PROCESSING_MOCK=y` for mock testing support.

boards: ptl: add Google RTC Audio Processing to PTL configuration

---

.github/workflows/llext.yml
.github/workflows/sparse-zephyr.yml
.github/workflows/zephyr.yml
scripts/docker_build/zephyr_lite/Dockerfile
zephyr/docker-build.sh
zephyr/docker-run.sh

Update base to zephyr-build v0.28.4 and add improvements to the dockerimage
- Remove python3.12 installation as it's already supplied by new
docker base
- Remove sysroots from toolchains to free up space
- Install jsonschema and cmake
- Update SDK to 0.17.4
- Use venv for python packages
Drop support of docker-run.sh wrapper used in zephyr workflows in favor of using ```container: image:``` tag that is built into github workflow syntax
Reworked workflows include:
- .github/workflows/zephyr.yml - https://github.com/thesofproject/sof/actions/runs/18163609096
- .github/workflows/sparse-zephyr.yml - https://github.com/thesofproject/sof/actions/runs/18163609031
- .github/workflows/llext.yml - https://github.com/thesofproject/sof/actions/runs/18163609061/job/51700001165
Signed-off-by: Mateusz …

zephyr-lite: update base to zephyr-build v0.28.4 and rework zephyr workflows

---

versions.json

Open mainline for development and set version to 2.14.99 as stable-v2.14 has branched out.

versions.json: set version to 2.14.99

---

src/audio/copier/copier.c

This PR fixes a NULL pointer dereference crash in the IPC4 copier module that occurs when sink buffer IDs map to non-zero `sink_queue_id` values but corresponding converters are not initialized.
The crash occurs in `do_conversion_copy()` when accessing `cd->converter[i]` where `i` is extracted from sink buffer IDs using `IPC4_SINK_QUEUE_ID(buf_get_id(sink))`.
1. **Buffer ID Mapping**: `IPC4_SINK_QUEUE_ID()` can extract non-zero queue IDs from buffer IDs, even in single-sink scenarios
2. **Limited Initialization**: `copier_prepare()` only initializes `converter[0]` for pin 0
3. **Runtime Mismatch**: Accessing `converter[1]` when only `converter[0]` exists causes NULL pointer dereference
The crash occurs when **all** conditions are met:
- Copier component has `endpoint_num == 0` (module …

copier: fix NULL converter crash for non-zero sink_queue_id

---

src/audio/base_fw.c
src/include/ipc4/base_fw.h

The host buffer default or minimum size can be platform dependent and it is not know by the host.
It is in sole discretion of the firmware and the hardware where it is running and can be changed by recompiling the firmware.
Add new tlv item to fw_config with ID 33 and store the host DMA default period size, which is the indication of the default, minimum size of the host buffer in ms.

base_fw: Extend fw_config with information about the host buffer size

---

posix/include/rtos/alloc.h
src/audio/module_adapter/module/generic.c
src/include/sof/audio/module_adapter/module/generic.h
src/ipc/ipc4/helper.c
src/platform/library/lib/alloc.c
test/cmocka/src/common_mocks.c
zephyr/include/rtos/alloc.h
zephyr/lib/alloc.c

The message bellow is mostly obsolete. 
It appears that virtual heap is not  able to cope with all module allcations, so move away from using rballoc() and friends to avoid moving all the module allocations to virtual heap. Use rmalloc() friends in stead. To do this rmalloc() family needs to be extended with rmallloc_aling(). Adding new function requires some additions to cmocka and testbench. Then there is also couple of minor fixes at the end of series.
This is the first split of this huge PR: https://github.com/thesofproject/sof/pull/10195
The older already merged PR on the same subject is here: https://github.com/thesofproject/sof/pull/10164

Module api: various fixes and developments

---

src/platform/intel/cavs/platform.c

With Zephyr commit ae1f13149fcd ("pm: Extend pm notifier to be able to report substate"), the pm_notifier struct was changed to include multiple structs within a union. The xcc toolchain used for cAVS targets cannot initialize the struct with the existing code.
Modify the code to work with the new pm.h definition and the old compiler used.

platform: intel: cavs: modify pm_notifier init for older toolchains
